### ISSUE TITLE
Images über IPFS verteilen

### ISSUE THREAD

**Issue by Tyberhertz** [RPiList/specials#10]
Moin RPiList, nach eurem Video zum Thema IPFS habe ich mir gedacht, man könnte doch die Images auch über das IPFS Netzwerk verteilen lassen. Habe bereits einen Server im Betrieb und habe euer erstes Images schon bei mir hochgeladen.

Hier der Hashwert:

svpihole1911.img = QmZwXR75DjLXKs18PL2zZ8pWjCvdmDrwcVxeJYYpMMvU39

und hier ein paar Links, um sich dieses Image herunterzuladen:

# Über Cloudflare:
https://cloudflare-ipfs.com/ipfs/QmZwXR75DjLXKs18PL2zZ8pWjCvdmDrwcVxeJYYpMMvU39

# Über ipfs.io
https://ipfs.io/ipfs/QmZwXR75DjLXKs18PL2zZ8pWjCvdmDrwcVxeJYYpMMvU39

# Über gateway.ipfs.io
https://gateway.ipfs.io/ipfs/QmZwXR75DjLXKs18PL2zZ8pWjCvdmDrwcVxeJYYpMMvU39

**Comment by RPiList** [comment]
Links wurden hinzugefügt.

Vielen Dank und viele Grüße.
