### ISSUE TITLE
optimierbare regex Regeln

### ISSUE THREAD

**Issue by Th3M3** [RPiList/specials#100]
Wenns nur um die TLD geht, kann auch einfach
z.B.
`\.cn$` anstatt `([a-zA-Z0-9\-\._]{2,256})(\.cn$)`
geschrieben werden.

Die Regel ist damit nicht nur kürzer und übersichtlicher, lt. https://regex101.com sind dadurch auch weniger Schritte zum Matchen notwendig und sie funktioniert komplett ohne Beschränkungen (wie `{2,256}` in der bisherigen Regel).

Zudem sollten auch die TLDs `.life`, `.agency`, `.agency`, `.club`, `.fun`, `.icu`, `.il`, `.life`, `.live`, `.space`, `.su`, `.cl`, `.top`, `.xyz`, `.art`, `.vip`, `.ph` grundsätzlich blockiert werden, da sie für'n Apfel und 'n Ei zu bekommen sind und daher gerne zu Betrugszwecke verwendet werden. Habe schon diverse in freier Wildbahn angetroffen.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für den Hinweis. Wir hatten auch schon gesehen, dass der von
uns gewählte 100% Ansatz nicht optimal ist. Schon das Entfernen des
"Grouping" würde die "Last" um 75% senken.

Wir haben nachgefragt, ob sich die FTL-Engine genauso verhält, wie die
"Regex101.com".

Viele Grüße


Am Mi., 26. Feb. 2020 um 22:56 Uhr schrieb TheME <notifications@github.com>:

**Comment by AleksCee** [comment]
Hatte ich auch schon vorgeschlagen, wäre zu kompliziert wurde gesagt. Aber es funktioniert in der  FTL-Engine ich nutze die kurzen Regex bei mir.

**Comment by RPiList** [comment]
Wer hat gesagt, dass es zu kompliziert sei?

Dass die kurze, wie auch die lange Anweisung funktioniert stand außer Frage. Es geht sich hier lediglich darum, ob die lange Anweisung mehr Arbeitscyclen braucht um die Erkennung abzuschließen.

Auf unsere Anfrage hin, haben wir noch keine Antwort von den Entwicklern erhalten. Alle anderen Antworten die wir bisher erhalten haben, kann man summieren mit: "Ja, ist mehr Aufwand, aber diese mündet nicht in mehr Last".

Insoweit sind wir da noch unentschlossen.

**Comment by AleksCee** [comment]
Ihr, hier: https://github.com/RPiList/specials/issues/75#issuecomment-581521427

**Comment by Th3M3** [comment]
> Auf unsere Anfrage hin, haben wir noch keine Antwort von den Entwicklern erhalten.

Wo habt ihr denn diese Anfrage gestellt? Ich habe weder auf Github noch im [Community Forum](https://discourse.pi-hole.net) etwas gefunden.

<br>

> Alle anderen Antworten die wir bisher erhalten haben, kann man summieren mit: "Ja, ist mehr Aufwand, aber diese mündet nicht in mehr Last".

Natürlich stellt auch eine komplexere Regel mit mehr Schritten zum Matchen keine wirkliche Last für den Prozessor dar.
Für den Endbenutzer, der die Regel aber auch gerne verstehen und ggf. auch an seine Bedürfnisse (z.B. weitere TLDs) erweitern möchte, ist eure Regel zum Blockieren unnötig kompliziert und birgt die Gefahr, dass letztendlich eine ungültige oder gar prozessorlastige Regel eingegeben wird.

Und wie ich bereits zu Beginn geschrieben hatte, blockiert `([a-zA-Z0-9\-\._]{2,256})(\.cn$)` aufgrund angegebenem _Quantifier_  bei weitem nicht alle Domains der TLD `.cn`.
`a.cn` würde z.B. durch eure Regel garnicht gematcht werden.

**Comment by RPiList** [comment]
> Ihr, hier: [#75 (comment)](https://github.com/RPiList/specials/issues/75#issuecomment-581521427)

richtig... die Komprimierung war so weit, dass sie für den normalen Nutzer zu schwer zu modifizieren war.

**Comment by RPiList** [comment]
> 
> Natürlich stellt auch eine komplexere Regel mit mehr Schritten zum Matchen keine wirkliche Last für den Prozessor dar.

Ja, das deckt sich mit den Aussagen die wir bisher zu dem Thema erhalten haben. Und ja, das ist bei den paar RegEx Anweisungen die wir bisher haben unerheblich. Aber im gleichen Zuge skaliert das Problem, wenn künftig immer weitere Anweisungen dazu kommen.

> Für den Endbenutzer, der die Regel aber auch gerne verstehen und ggf. auch an seine Bedürfnisse (z.B. weitere TLDs) erweitern möchte, ist eure Regel zum Blockieren unnötig kompliziert und birgt die Gefahr, dass letztendlich eine ungültige oder gar prozessorlastige Regel eingegeben wird.
> 
> Und wie ich bereits zu Beginn geschrieben hatte, blockiert `([a-zA-Z0-9\-\._]{2,256})(\.cn$)` aufgrund angegebenem _Quantifier_ bei weitem nicht alle Domains der TLD `.cn`.
> `a.cn` würde z.B. durch eure Regel garnicht gematcht werden.

Ja, aber das ist ein anderes Problem.

**Comment by Th3M3** [comment]
> Ja, aber das ist ein anderes Problem.

Das ist aber das **größere** Problem/Risiko!
Eine unnötig komplexe RegEx-Regel wäre ja noch okay wenn sie das machen würde was man erwartet.

Wenn Ihr jedoch `Sperrt alle Domains aus China:` dazu schreibt und dann eine falsche Regel preäsentiert, die eben **nicht** alle Domains mit TLD `.cn` blockiert, wägt ihr eure Nutzer in falscher Sicherheit.

**Comment by RPiList** [comment]
Ja, wie ich sagte, das ist ein anderes Problem, dass nichts mit der "Vereinfachung" der RegEx Einträge zu tun hat.
