### ISSUE TITLE
False Positive - phish.report

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [RPiList/specials#1001]
Phish.report is, how the domain name suggests, a website for reporting phishing sites.
However, it now appeared in the block list. Can this be removed?
![image](https://github.com/RPiList/specials/assets/27149563/bed290d2-dcf0-4bf4-bac5-c5c560b7d214)

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings
