### ISSUE TITLE
Domians wie bestellt.

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1002]
Moin, Hier sind die ganzen Domaons die mir die Bank geben hat
https://oberbank-mobile.com
https://oberbank.site
https://oberbank.press
https://oberbank-app.site
https://oberbank-app.online
https://oberbank.online
https://oberbank-id.site
https://oberbank-ag.web.app
https://oberbank-app.com
https://oberbank.pw
https://oberbank-site.com
https://oberbank-banking.app

mehr domians sind es nicht

**Comment by Vickyistda2003w** [comment]
So ich habe nochmal bei der bank nachgefragt und noch diese 2 domains erhalten

https://iberbank.at
https://oberrbank.at

PS: meine liste wurde geuptet

**Comment by RPiList** [comment]
oberrbank.at???

wirklich mit dem doppel R? Oder ist das ein Schreibfehler?

**Comment by RPiList** [comment]
und iberbank.at ist ein typischer Tippfehler... DomainSquatting und ist deswegen auch auf der Blockliste drauf. :-)

**Comment by Vickyistda2003w** [comment]
Da habe ich mich vertippt, Oberbank ist die original domain, hab mich wohl vertan beim copy pasten

**Comment by RPiList** [comment]
Wir müssen ebenfalls noch mal drüber nachdenken, in welche Liste die Domains wandern. Vom Thema her würden die natürlich in die DomainSquatting Liste der entsprechenden Bank gehören.

ABER: Wenn derzeit eine Phishing-Welle mit dieser Bank läuft, müsste das Ziel sein, die Nutzer zu schützen. Die Liste die am meisten genutzt wird, dann ist das die Malware, die Phishing und die Fake-Shop Liste. Wenn das Ziel ist so schnell wie  möglich (fast) alle Nutzer zu erreichen, dann müssten wir das in diese Listen packen.

**Comment by Vickyistda2003w** [comment]
Du kannst es doch einfach in alle der drei genannten listen und dann noch in die Oberbank liste damit diese geblockt sind falls sich andere heckenpenner diese später mal schnappen

**Comment by RPiList** [comment]
Alle AT-Banken sind jetzt wie besprochen aktualisiert. Bitte auf dem Laufenden halten, wenn neue "Endungen" hinzu kommen. 
Nun stellt sich die Frage, ob wir die gleichen Endungen auch bei den CH und DE Banken anwenden. Viele Grüße und noch mal vielen Dank.

**Comment by Vickyistda2003w** [comment]
oberbank.click
oberbank.services
