### ISSUE TITLE
Blockliste zu Trading

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1003]
Dere,

Wie wäre eine Blockliste zum Thema Trading, da es viele Fake Seiten gibt die mit einen Schneeballsystem arbeiten bzw wenn man sich nicht auskennt ist es besser die Leute davor zu schützen.

MFG

(Dere heißt in Österreich sowas wie Hallo, man kann es auch als Verabschidung nutzen)

**Comment by RPiList** [comment]
Kommt Dere von "Habe die Ehre"... oder hört sich das nur in meinem Kopf ähnlich an?

Deine Blockliste zu dem Thema wäre sicher sehr hilfreich. 

Das würde ich mindestens in die Child-Protection Liste packen. Ob wir daraus eine eigene Liste oder auch noch in die Spam/Scam Liste packen schauen wir dann.

Dann stellt sich noch die Frage, gibt es Websites die solche Abzocker schon auflisten? Wie finden wir die Websiten? Vielleicht mal Beispiels-Domains schicken. Danke.

**Comment by SGirl-Zockt** [comment]
Ja das ist möglich,

Ich habe diese Listen dazu gefunden:
https://www.testsieger-konto.de/depotkonto/betrug/scammer-liste/
https://finanzsache.at/broker/betrug/#

Dies sind nur 2 Listen, es wird sicher mehr geben wenn man Google befragt.

**Comment by RPiList** [comment]
Vielen Dank. Die Einträge sind inzw. in die NotSerious Liste (für Fake-Shops) gewandert. Viele Grüße
