### ISSUE TITLE
Vorschlag zur Aufnahme des GitLab-Projekts "Piracy Index" in den Listen von RPiList

### ISSUE THREAD

**Issue by Wh1t3Pige0n** [RPiList/specials#1004]
Liebes SemperVideo Team,

Ich möchte einen Vorschlag machen, der das Projekt RPiList weiter stärken könnte. Mein Vorschlag besteht darin, das GitLab-Projekt "[Piracy Index](https://gitlab.com/piracy/piracy)" in den Listen von RPiList aufzunehmen.

Das "[Piracy Index](https://gitlab.com/piracy/piracy)"-Projekt ist eine Website, die eine Sammlung der besten digitalen Piraterieressourcen bietet. Obwohl die Ziele der beiden Projekte unterschiedlich sind, sehe ich einen Mehrwert darin, den "Piracy Index" in Ihre Liste aufzunehmen. Durch die Integration der Links des "[Piracy Index](https://gitlab.com/piracy/piracy)" können Sie den Nutzern von RPiList eine erweiterte Schutzmöglichkeit bieten, indem der Zugriff auf diese Ressourcen blockiert wird.

Ziel von RPiList ist es, die Nutzer vor Bedrohungen wie Fakeshops, Werbung, Tracking und anderen Angriffen aus dem Internet zu schützen. Durch die Aufnahme von Links aus dem "[Piracy Index](https://gitlab.com/piracy/piracy)" in den Blocklisten erweitern Sie den Schutzumfang und helfen den Nutzern, potenzielle Risiken der digitalen Piraterie zu vermeiden. Dies würde auch ungeschulte Nutzer schützen und potenzielle Abmahnungen sowie andere rechtliche Konsequenzen minimieren.

Ich bin der festen Überzeugung, dass die Aufnahme des "[Piracy Index](https://gitlab.com/piracy/piracy)" in RPiList einen Mehrwert für das Projekt und die Nutzer darstellt. Die Möglichkeit, den Zugang zu bekannten Piraterieressourcen zu sperren, trägt zur Förderung einer sicheren und geschützten Internetumgebung bei.

Neben GitLab hat das Projekt auch eine [Website](https://piracy.vercel.app/) wo alles übersichlich in Kategorien dargestellt wird.

Vielen Dank für Ihre Aufmerksamkeit.

Mit freundlichen Grüßen
Wh1t3Pige0n

**Comment by RPiList** [comment]
Hi,
wir bräuchten dafür entsprechende URLs die in die Blockliste augenommen werden wollen/sollen. 
Ferner wäre auch noch nicht ganz klar, in welche Liste sie gepackt werden sollten. Es ist ja keine Schadware... da bliebe allenfalls die Child-Protection List. 

Viele Grüße
