### ISSUE TITLE
False-positive: chatgpt.peterdavehello.org

### ISSUE THREAD

**Issue by PeterDaveHello** [RPiList/specials#1007]
I don't know why but found my chatgpt.peterdavehello.org is listed here, which is obviously false-positive:https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

**Comment by RPiList** [comment]
Hi,
we discussed your site and have decided it has to stay on the list. It seems like a chatGPT cover and there are a lot of bad players in this field.

Greetings.

**Comment by PeterDaveHello** [comment]
No any malware evidence, and keep it on the malware list after receiving false-positive report? That's sad to sad, but you're losing the project's credit.

**Comment by RPiList** [comment]
Dude, you are cashing in on the name and the works of OpenAI's ChatGPT, which in some countries is a violation of copyright laws. You even ask for money with your donation buttion for some minor translation of the original website?
That's considered as scaming. And that's a kind of malware, when users get scamed. There's your evidence.

**Comment by PeterDaveHello** [comment]
No man, the title and the homepage is very clear "**is for testing purpose only**", and also says very clearly **Please consider to purchase OpenAI ChatGPT buy your own if you found this is useful!**, just the requests are too high, that's why I add a small text at the corner "_consider_ to sponsor", "if you found this is useful".

No matter what, there's no meaning to make people think it's an OpenAI service, there's no payment button or link, and of course, there's nothing to do with malware, categorizing like that is really a mistake.

**Comment by PeterDaveHello** [comment]
BTW, I understand your concerns, and thanks for the copyright reminder, just want to clarify some misunderstanding above.
