### ISSUE TITLE
False-positive: https://www.skylinewebcams.com/

### ISSUE THREAD

**Issue by andihome** [RPiList/specials#1009]
Hallo in die Runde

Die Webseite 'https://www.skylinewebcams.com/' ist in den Porno-Filtern drin.
Wie es dazu gekommen ist, weiß ich nicht, aber GIFs (Girl-In-File) habe ich dort nicht gefunden. ;-)
Wer muss denn dazu angesprochen werden?

Gruß Andi

**Comment by andihome** [comment]
Hier noch der Eintrag:

Exact match for skylinewebcams.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
