### ISSUE TITLE
PiHole lässt sich nicht updaten

### ISSUE THREAD

**Issue by ultim4te** [RPiList/specials#101]
Moin,

mein sv-PiHole lässt sich nicht updaten. 
"Pihole -up" per SSH ausgeführt ergibt folgende Fehlermeldung:
/etc/pihole/setupVars.conf: line 12: fe80::e1b7:bd0b:5d71:f267/64: No such file or directory

**Comment by RPiList** [comment]
Hi,

welche Version des SV-Pihole wird auf welcher Hardware eingesetzt?
Können Sie einen Screenshot der Ausgabe von $ sudo nano /etc/pihole/setupVars.conf schicken?

Ferner würde mich interessieren, ob der Befehl date, der die Zeit auswirft, die korrekte Zeit zeigt. Oder ob die Zeit stark von der richtigen Zeit abweicht.

Viele Grüße und vielen Dank für Ihre Mühen.

**Comment by ultim4te** [comment]
Hi,

PiHole läuft auf einem Raspberry Pi 3B. Laut date abfrage geht der Pi eine Stunde nach, das Datum stimmt.

<img width="565" alt="Bildschirmfoto 2020-02-27 um 21 01 40" src="https://user-images.githubusercontent.com/61522695/75482617-7673d500-59a5-11ea-8bad-836952e226ab.png">
<img width="664" alt="Bildschirmfoto 2020-02-27 um 21 06 28" src="https://user-images.githubusercontent.com/61522695/75482641-81c70080-59a5-11ea-85ee-7ba642b78c45.png">

**Comment by RPiList** [comment]
Ihr Problem dürfte sich erledigen, wenn Sie die letzten zwei Zeilen löschen.
Also alles ab IPV6 entfernen.

Ich interpretiere das so, dass Sie im LAN IPv4 nutzen. Dann brauchen Sie
den IPv6 Eintrag nicht.

Ich frage mich nur, wo die "komische" vorletzte Zeile herkommt.

Können Sie mir noch einen Screenshot von "ifconfig" zusenden? Dann kann ich
evtl. sehen, wo die lange IPv6 herkommt.

Viele Dank für Ihre Mühen.

Viele Grüße

Am Do., 27. Feb. 2020 um 21:10 Uhr schrieb ultim4te <
notifications@github.com>:

**Comment by ultim4te** [comment]
Richtig ich nutze IPv4.
Ich habe die letzten beiden Zeilen gelöscht, nun kann ich updaten, danke.

Hier trotzdem nochmal der Screen von ifconfig:

<img width="567" alt="Bildschirmfoto 2020-02-27 um 21 23 45" src="https://user-images.githubusercontent.com/61522695/75483979-264a4200-59a8-11ea-9cae-6153cad0e6a7.png">


Danke für die Hilfe und einen angenehmen Abend noch.

**Comment by RPiList** [comment]
Vielen Dank für den Screenshot.
Ich sehe die zwei IPv6 Einträge und weiß jetzt warum unser Script beide in die Konfig-Datei geschrieben hat. Wichtiger ist aber die Frage, warum da überhaupt so viele IPv6 Einträge bei einem IPv4 Netzwerk sind.

Daher noch eine Abschließende Frage. Bei welchem Provider sind Sie und welchen Router nutzen Sie?

Vielen Dank und viele Grüße.

**Comment by ultim4te** [comment]
Provider ist Vodafone ehemals Unitymedia, wir nutzen eine Fritzbox 6591 Cable.
