### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#1010]
Hallo,

mir ist gerade diese Domain per SMS gemeldet worden: speicher-jetzt.online
Ist eine Fake-Volksbank.

nach Aufruf der Seite wird folgendes geladen: https://speicher-jetzt-23.in/De/H78321HJFHWQUYH837271hhgewhfrye7873281ggfegw/T774327HhjfwyeyfDYUEWYUF781737!HGGHFEWHQHE72763/P7821HFUQUIUW77237hdfhq1728!hhfehHFYHE/?index=45277&feeder=df49b9873025e1fcb083793cbee5a71245579a15

Bitte zu den entsprechenden Blocklisten hinzufügen. Danke

**Comment by RPiList** [comment]
Hi,

Domain wurde der Liste hinzugefügt. Viele Grüße
