### ISSUE TITLE
einzigartigdeutscherfuhrerschein.com

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1012]
Moin,

wenn ich die Seite richtig verstehe, handelt es sich um einen Shop wo man gefälschte Führerscheine kaufen kann

mfg

**Comment by SGirl-Zockt** [comment]
Kleines Update:

Auf derFB seite von dennen schrieben viele das damit ihre Identität geklaut wurde

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Domains wurden der Liste hinzugefügt. Viele Grüße.
