### ISSUE TITLE
American Civil Liberties Union & child-protection

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1013]
`www.aclu.org` setzt sich ein für Privatsphäre & Bürgerrechte, warum steht die American Civil liberties Union auf der Liste?

**Comment by RPiList** [comment]
Ist ne gute Frage, die ich auch nicht beantworten kann. Aber einige Dienste "flaggen" Kinderschutz auch schon bei einzelnen Bildern. Ob dies hier der Fall war weiß ich aber nicht. Ist aber jetzt erst mal gelöscht. Schauen wir mal ob sie von Dritten wieder eingespielt wird. Vielen Dank für die Info. Viele Grüße
