### ISSUE TITLE
wren.co 

### ISSUE THREAD

**Issue by Undefined101** [RPiList/specials#1014]
Hi,

warum ist wren.co auf der malware liste, es handelt sich um eine klimaschutz projekt.

lg

**Comment by RPiList** [comment]
Der Inhalt einer Website hat nichts mit der Klassifizierung als Schadware zu tun. Auch eine Klimaschutz-Seite kann Schadware verteilen.  Wahrscheinlich nicht freiwillig; kommt aber regelmäßig vor.

Derzeit wird die Seite aber von keinem bekannten Dienst markiert. Insoweit denke ich auch, dass die Seite raus kann. Ist entfernt. Viele Grüße und vielen Dank für die Info.
