### ISSUE TITLE
Blocklisten funktionieren nicht richtig

### ISSUE THREAD

**Issue by TxS1** [RPiList/specials#102]
Nach dem neu setzen der Blocklisten URL's funktionieren die Blocklisten scheinbar nicht richtig.

Bsp Springer-Blocker

beim Update:
 [i] Target: github.com (Springer-Blocker)
  [✓] Status: Retrieval successful

auf Bild.de komme ich noch... definitiv nicht in der whitlist ;)

**Comment by RPiList** [comment]
Hi,

also hier funktioniert es problemlos.

[image: image.png]

Evtl. mal bei Ihnen die Log-Daten checken.

Am Do., 27. Feb. 2020 um 20:41 Uhr schrieb TxS1 <notifications@github.com>:
