### ISSUE TITLE
Unbedenkliche Domain in Blocklist Phishing-Angriffe (live.login.com)

### ISSUE THREAD

**Issue by hduelme** [RPiList/specials#103]
Die Domain  **login.live.com** ist direkt von Microsoft und wird z.B. für den Windows-Store benötigt.
Bitte diese Domain aus der Blocklist Phishing-Angriffe entfernen.

**Comment by RPiList** [comment]
Die Domain ist schon aus der Liste raus.
Damit das gültig wird, müssen Sie die Liste im Pi-hole aktualisieren.
Pi-hole selbst macht das nur 1x pro Woche selbsttätig.

Am Do., 27. Feb. 2020 um 23:28 Uhr schrieb hduelme <notifications@github.com

**Comment by hduelme** [comment]
Vielen Dank für die Info :+1:
