### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by Ulyzzeus** [RPiList/specials#1030]
- tz.de Zeitung aus München
- readly.com [https://de.m.wikipedia.org/wiki/Readly](https://de.m.wikipedia.org/wiki/Readly)

**Comment by RPiList** [comment]
Hi,

Domains wurden entfernt. Viele Grüße und vielen Dank für die Meldung.

**Comment by soonic6** [comment]
> Domains wurden entfernt. Viele Grüße und vielen Dank für die Meldung.

ist immer noch Zeile 51305 vorhanden.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Wurde wieder entfernt und diesmal auf die Whitelist gesetzt. Viele Grüße
