### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Zoey2936** [RPiList/specials#1031]
In der spam mails liste sind mehrere Domains, enthalten, welche unter `allegutendinge.jetzt` und `agg-reform.jetzt`, aber diese domains, samt subdomains sind keine spam mail domains. Ich würde mich freuen, wenn diese entfernt werden würden.

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Infos, Domains wurden entfernt. Viele Grüße
