### ISSUE TITLE
Alles von sky XDrage punkt de sperren

### ISSUE THREAD

**Issue by Janmm14** [RPiList/specials#1038]
Aktuell ist nur eine subdomain von `skyrage.de` auf der Malware-Liste, vermutlich durch externe Einträge, wahrscheinlich ursprünglich in der abuse.ch-Datenbank.
Da die gesamte Domain aber zumindest seit August 2022 ausschließlich (und mit Wissen des Eigentümers, Quelle: Privatchat mit ihm) absichtlich weiter Malware verbreitet, bzw Malware auch über die Domain mit C&C verbindet / weitere Malware herunterlädt

und auch dns-records auf neue Malware-Server geändert wurden (zb nach kostenloser anmeldung nachschaubar auf securitytrails com, nachdem alte server höchstwahrscheinlich gesperrt wurden),

sollte sie am Besten komplett gesperrt werden.

Dort wird auch kein Minecraft-Server oder anderes in irgendeiner weise interessantes mehr gehostet.

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Domain wurde auf die entsprechende Liste gesetzt.
