### ISSUE TITLE
What about fake science sites?

### ISSUE THREAD

**Issue by ChillerDragon** [RPiList/specials#104]
There is this interesting [DEF CON 26 - Svea, Suggy, Till - Inside the Fake Science Factory](https://youtu.be/ras_VYgA77Q?t=3362) talk about for example waset.org publishing non scientific papers. In the talk they mentioned a randomly generated paper that got accepted and it is still public on [thescipub.com](https://thescipub.com/abstract/10.3844/jcssp.2018.747.752). I did not do any more investigations than watching this one talk and in general I do not know if this repository is about blocking fake facts. So its more a recommendation or idea to look into sites that claim to publish reviewed scientific papers which include made up marketing oriented fake facts.

Seems like this collection here is all about protecting the user from harm. And buying wrong medication based on false studies can be a harm imo.

**Comment by RPiList** [comment]
This is a very tricky area to cover.
I have no problem blocking fake-news websites. The problem is getting a reliable source or list of those fake-news domains. Determing a fake-shop is easy. But determing a fake-news website is way harder.

**Comment by ChillerDragon** [comment]
Yea proofing the fake facts is hard. But the few sites mentioned in the talk by Svea, Suggy and Till seem to be properly researched and there can be even found their randomly generated article. So its somewhat proofen that these sites include false fact papers but they likley also have legit papers as well.

But I would say its fine to block a site that knowingly publishes any papers just to make money even if some papers are legit.

**Comment by RPiList** [comment]
I have added a first fake-science list. Thanks for making us aware of such scams. Greetings

**Comment by ChillerDragon** [comment]
Thanks for looking into it.
closed by https://github.com/RPiList/specials/commit/dd3233544a2f20fe0c0d998fedf0920df86af5a7
