### ISSUE TITLE
sos.de 

### ISSUE THREAD

**Issue by Undefined101** [RPiList/specials#1041]
Die firma stellt desinfektionsmittel und andere hygieneartikel für den endkunden her.
Kann also von der Block liste, scheinbar ein irrläufer 

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Sparkasse/Brandenburg:
  sos.de
  www.sos.de

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
