### ISSUE TITLE
Entfernung von Corona-Blacklist

### ISSUE THREAD

**Issue by haruzept** [RPiList/specials#1044]
Hallo,

leider wird in der Corona-Blacklist auch der Solar Anbieter corona.solar blockiert.
Hierbei handelt es sich jedoch um ein seriöses Unternehmen für Solaranlagen.

Gruß
Haruzept

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
