### ISSUE TITLE
ip-adress.com

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1045]
Moin Kollege.

Bitte entfernen von der Liste, da es weder Gamling noch was anderes ist:
Exact matches for ip-adress.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling

**Comment by RPiList** [comment]
Hi, vielen Dank für die Info.

Aber wir lassen die Adresse besser drin.

Wir haben uns den Fall gestern genauer im Stream angeschaut und sind zu folgendem Schluss gekommen:

Klar, im Gambling ist die Domain falsch, dort ist sie inzw. entfernt.
Aber in der Easylist kommt die Meldung nicht von uns.

Grund dürfte sein, dass die Domain "ipadress.com" (mit nur einem "d") nur auf die richtige Domain "ipaddress.com" (mit 2x "d") weiterleitet. Wir haben jetzt nicht geprüft, ob die Domain 2x dem gleichen Inhaber gehört der DomainSquatting vermeiden will. Oder ob jemand vorher Werbung/DomainSquatting selbst betrieben hat. Wenn ja, kann der Faker das jeden Moment wieder ändern. Insoweit haben wir beschlossen, dass die Fake Domain bleibt. Die richtige Domain ist ja nicht gesperrt. 

Vielen Dank für die Mühen und viele Grüße
