### ISSUE TITLE
easy add links to adguardhome

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1048]
this is the continuation of #1046 as an issue because it allows you to test the script without having to merge it directly.
_____
I have created a script with which it is possible via a links.txt in which the links to the block lists should be, to intrigue them easily and quickly into the adguardhome config. The prerequisite is that you create a `./links.txt` in the same directory of the script and save the links in it and there must not be any empty lines in between.

before using adguardhome, you have to remove all previous and standard lists so that the script can insert it without errors.

If Adgurdhome is run as a docker image, you have to go to the volume that contains the `adguardhome.yaml` and adjust the full path to the `adguardhome.yaml` in the script and restart the docker container after using the script. 
Instructions written in German can also be found in the script with the `#` sign.

The script has just been put together, so it can't be guaranteed to work, but I tested it under the instructions (see this comment) and it should probably work

Example of how the `./links.txt` should be structured:
```
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry
```

Example of how the `./links.txt` should **not** be structured:
```
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry
```

_____
### Here is the Code of the script:
```
#!/bin/bash

# Wenn Adguardhome als Docker Image genutzt wird, dann unter "configfile=" den genauen Pfad der AdGuardHome.yaml zu finden ist
configfile=/etc/adguardhome/AdGuardHome.yaml

# Die Textdatei in den die Links eingetragen sind. Es dürfen keine Leerzeilen dazwischen sein.
linkfile=./links.txt

# Vorher in AdguardHome alle bisher eingetragenen bzw. die Standard Listen löschen damit, das Script das besser einfügen kann.


sed -i 's/^filters: .*$/ /g' $configfile

echo "filters:" >> $configfile

while read line; do
    echo "  - enabled: true" >> $configfile
    echo "    url: $line" >> $configfile
    echo "    name: $line"  >> $configfile
    echo "    id: 9$RANDOM" >> $configfile
done < $linkfile

# Nur verwenden wenn Adguardhome nicht als Docker Image läuft ansonsten auskommentieren.
systemctl restart adguardhome.service
```

**Comment by RPiList** [comment]
Hi,

gibt es die Möglichkeit die Anlage einer links.txt hier im Projekt zu vermeiden und dass das Script die bereits vorhandene Blocklisten.md nutzt? Also die notwendigen Links dort rauszieht. Weil wir sonst für alle Änderungen in zwei Listen durchführen müssten. Viele Grüße und vielen Dank für die Mühen.

**Comment by LizenzFass78851** [comment]
I built it into the script that loads the `blocklisten.md` from github. adapts them accordingly (removes the emply new lines, removes the comments beginning with `#` and filters the double links) so that the insertion of the links from the `blocklisten.md` works.

Here is the changed code of the script:
```
#!/bin/bash

# Hinweis: Wenn Adguardhome als Docker Image genutzt wird, dann unter "configfile=" den genauen Pfad der AdGuardHome.yaml zu finden ist
configfile=/etc/adguardhome/AdGuardHome.yaml

# Hinweis: Die Textdatei in den die Links eingetragen sind. Es dürfen keine Leerzeilen dazwischen sein.
linkfile=links.txt

# Hinweis: Vorher in AdguardHome alle bisher eingetragenen bzw. die Standard Listen löschen damit, das Script das besser einfügen kann.

# Hinweis: Download der Listen (ausklammern wenn eine eigene links.txt erstellt wurde)
curl -L -o $linkfile https://github.com/RPiList/specials/raw/master/Blocklisten.md

# Erklärung: Mit # beginenden Zeilen Wörter entfernen
sed -i 's/^#.*$//g' $linkfile
# Erklärung: Leere Leerzeilen entfernen
sed -i '/^$/d' $linkfile
# Erklärung: Doppelte Zeilen filtern
sort -u $linkfile > $linkfile.tmp
mv $linkfile.tmp $linkfile

# Erklärung: Bestimmte Zeile aus config löschen
sed -i 's/^filters: .*$//g' $configfile

# Erklärung: Einfügen der links aus der linkfile
echo "filters:" >> $configfile

while read line; do
    echo "  - enabled: true" >> $configfile
    echo "    url: $line" >> $configfile
    echo "    name: $line"  >> $configfile
    echo "    id: 9$RANDOM$RANDOM" >> $configfile
done < $linkfile


# Hinweis: Nur verwenden wenn Adguardhome nicht als Docker Image läuft ansonsten auskommentieren.
systemctl restart adguardhome.service
```

The lines in the script beginning with `"Hinweis:"` should be read before execution and followed accordingly
the lines beginning with `"Erklärung:"` are only explanations of what the command does when it is executed.
