### ISSUE TITLE
Falsch positiv: hna.de

### ISSUE THREAD

**Issue by DSG5TRDD** [RPiList/specials#1049]
Hallo,

HNA.de ist eine größere Tageszeitung in Nordhessen. Hier wird die Domain geblockt:

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
- hna.de
- www.hna.de

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
