### ISSUE TITLE
SMS Phishing: spk-tan-s.info

### ISSUE THREAD

**Issue by Nickwasused** [RPiList/specials#1050]
Nach einem reCAPTCHA gehts weiter zur Phishing Seite, ziel ist die Sparkasse.

SMS link: https://spk-tan-s.info/de/sp/index4.php
URL: spk-tan-s.info

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde der Liste hinzugefügt. Viele Grüße
