### ISSUE TITLE
false positive in phising list

### ISSUE THREAD

**Issue by mschmitter-dba** [RPiList/specials#1051]
The following entries are blocking the full list of the Oracle Cloud Object Storage - OCI. Probably a very wide range… 

Imagine this to be equivalent blocking the whole s3 storage from AWS.

objectstorage.ap-chuncheon-1.oraclecloud.com
objectstorage.ap-mumbai-1.oraclecloud.com
objectstorage.ap-tokyo-1.oraclecloud.com
objectstorage.ca-toronto-1.oraclecloud.com
objectstorage.eu-amsterdam-1.oraclecloud.com
objectstorage.eu-frankfurt-1.oraclecloud.com
objectstorage.eu-marseille-1.oraclecloud.com
objectstorage.eu-milan-1.oraclecloud.com
objectstorage.eu-stockholm-1.oraclecloud.com
objectstorage.me-abudhabi-1.oraclecloud.com
objectstorage.me-dubai-1.oraclecloud.com
objectstorage.sa-santiago-1.oraclecloud.com
objectstorage.uk-cardiff-1.oraclecloud.com
objectstorage.uk-london-1.oraclecloud.com
objectstorage.us-ashburn-1.oraclecloud.com
objectstorage.us-phoenix-1.oraclecloud.com
objectstorage.us-sanjose-1.oraclecloud.com

**Comment by RPiList** [comment]
Thx for letting us know. Domains have been removed. Greetings.
