### ISSUE TITLE
Wieder eine Fake seite der Kronen Zeitung

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1053]
Moin,

Egal auf welchen Link man auf der Seite klickt man kommt immer zur Fake Trading Seite
Es gibt wieder eine Fake Seite der Kronen Zeitung die auf Fake Trading lenkt
https://roostoten.com/landers/kronen_at_kurz/?a=Sebastian_Kurz&p=Bitsoft_360&header=logo&cep=KEJsfgmXvXWEWmjuzAhSWHL3d7cbQs-QdmrZhbrm8Baz5tjnrIpag9rCpo09ixsrCuey30c724DRldX1UZdjpi0g54_8jW8hkudV5f_Oac6sD8uDoSj3Aq5gYD5K5lKO6OxClyaxYFxavLM_ahDXqX2_tm6xfEA4wOnoTiEZRfcPfJyix3BPefNfxC9UqpY8BzW9tp9qMVWji4vLR1kX8bQlyu-4ZVAJdGzqUW22GQWdcqjYl_Xb5oGOTXGq2PtMcaaA75MLTar0RI6sqwHJC_wBkKsF1rfOVuX4xNPmz6IRbkpESOc8NGzIgKJCUMyfH_BnSE1nmNPQfmwqm05yQX2TrWRxirx1eXBDcX1QTbWnM0-mImULjX7rV1gUMuV-dONwlU3janIF5I97Jc4vDq-pvETVSXOBhHihacEpYUvIMzo2_4t6ph5xg8G8JdlB9VM7cr5-LUKcSI-Qm1JaHIgRRvsN1aFS6nIVgQsKkCO2F8W_NZDHmrYoeIJlnBEXGH6l4lnt11ehtiEL9IflEyA-o2XdmZxHqUF_kXgnja_Jw03OTwreU0ZNpNVLqNpZC4ASMl1fLWP5OaIt7ycFPWfqb69cmh69MSVSA3FwvUjQ0D6IoI8x1OEQSNSRXqEQ&lptoken=1627863e75d8296800af&q=%2Fangel-delight-makes-major-comeback-after-receiving-a-modern-makeover%2F&ad_id=6324573860313&adset_id=6324573859913&campaign_id=6324573860913&ad_name=AT+-+bank&adset_name=AT&campaign_name=AT+-+credit+-+Kurz&source=fb&placement=Facebook_Desktop_Feed&domain=%7Bdomain%7D&cvu=%7Bcvu%7D&fbclid=IwAR0RtBqB244Q9tAu6fAsetD2F5jIsviFlQwG4fJVnkJHQjWHZyOltmNMCB4

**Comment by SGirl-Zockt** [comment]
> Moin,
> 
Egal auf welchen Link man auf der Seite klickt man kommt immer zur Fake Trading Seite
> Es gibt wieder eine Fake Seite der Kronen Zeitung die auf Fake Trading lenkt https://roostoten.com/landers/kronen_at_kurz/?a=Sebastian_Kurz&p=Bitsoft_360&header=logo&cep=KEJsfgmXvXWEWmjuzAhSWHL3d7cbQs-QdmrZhbrm8Baz5tjnrIpag9rCpo09ixsrCuey30c724DRldX1UZdjpi0g54_8jW8hkudV5f_Oac6sD8uDoSj3Aq5gYD5K5lKO6OxClyaxYFxavLM_ahDXqX2_tm6xfEA4wOnoTiEZRfcPfJyix3BPefNfxC9UqpY8BzW9tp9qMVWji4vLR1kX8bQlyu-4ZVAJdGzqUW22GQWdcqjYl_Xb5oGOTXGq2PtMcaaA75MLTar0RI6sqwHJC_wBkKsF1rfOVuX4xNPmz6IRbkpESOc8NGzIgKJCUMyfH_BnSE1nmNPQfmwqm05yQX2TrWRxirx1eXBDcX1QTbWnM0-mImULjX7rV1gUMuV-dONwlU3janIF5I97Jc4vDq-pvETVSXOBhHihacEpYUvIMzo2_4t6ph5xg8G8JdlB9VM7cr5-LUKcSI-Qm1JaHIgRRvsN1aFS6nIVgQsKkCO2F8W_NZDHmrYoeIJlnBEXGH6l4lnt11ehtiEL9IflEyA-o2XdmZxHqUF_kXgnja_Jw03OTwreU0ZNpNVLqNpZC4ASMl1fLWP5OaIt7ycFPWfqb69cmh69MSVSA3FwvUjQ0D6IoI8x1OEQSNSRXqEQ&lptoken=1627863e75d8296800af&q=%2Fangel-delight-makes-major-comeback-after-receiving-a-modern-makeover%2F&ad_id=6324573860313&adset_id=6324573859913&campaign_id=6324573860913&ad_name=AT+-+bank&adset_name=AT&campaign_name=AT+-+credit+-+Kurz&source=fb&placement=Facebook_Desktop_Feed&domain=%7Bdomain%7D&cvu=%7Bcvu%7D&fbclid=IwAR0RtBqB244Q9tAu6fAsetD2F5jIsviFlQwG4fJVnkJHQjWHZyOltmNMCB4

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde der Liste hinzugefügt. Viele Grüße
