### ISSUE TITLE
Ein Vorschlag für Internet Services

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1056]
Ich würde noch so anbeiter wie 
Cloud Gaming wo man ein Abo abschlissen kann.

Wäre socher praktisch

**Comment by RPiList** [comment]
Hi,
können wir gerne machen. Jedoch müssen wir dann wissen, welcher Cloud-Gaming Anbieter es sein soll und welche Domains diese nutzen. Viele Grüße
