### ISSUE TITLE
Pi-hole kann ABP-style domains in Blocklisten erkennen (wie adguardhome)

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1058]
### Ich habe herausgefunden das das Pi-hole in Blocklisten [ABP-style](https://adblockplus.org/filter-cheatsheet#blocking2) domains benutzen kann.
Dies entspricht dem gleichen ABP-style domain Unterstützung wie beim adguardhome

### Beispiel:
![Screenshot-2023-03-22-210421](https://github.com/RPiList/specials/assets/82592556/e70a6a0c-8305-43bb-93a4-440f6b0c4f1e)

-----

Daher gibt es, wenn das Pi-hole ebenfalls diese Art der Blocklisten wie bei Adguardhome unterstützt das so ggf. mehr Möglichkeiten ergibt, die Blocklisten so zu strukturieren, das man die Domains als ABP-style domains hinterlegt und damit evtl. ein effizienteres blocken von u. A. Subdomains einer Hauptdomain ohne alle Subdomains einzeln in einer Blockliste aufzulisten (dies könnte auch Platz für neue Einträge im bestehende Listen schaffen).

Auf die Idee gekommen bin ich durch diesen Link, da dort erwähnt wurde das die Erkennung von ABP-style Domains ins Pi-hole **wieder** hinzugefügt wurde:
https://pi-hole.net/blog/2023/03/22/pi-hole-ftl-v5-22-web-v5-19-and-core-v5-16-1-released

-----

Ich habe auch testweise mit einer Blockliste die ABP-style Domains beinhaltet, auf einen Pi-hole mit folgenden Version getestet: 
Docker Tag [2023.05.2](https://github.com/pi-hole/docker-pi-hole/releases/2023.05.2) Pi-hole [v5.17.1](https://github.com/pi-hole/pi-hole/releases/v5.17.1) FTL [v5.23](https://github.com/pi-hole/FTL/releases/v5.23) Web Interface [v5.20.1](https://github.com/pi-hole/AdminLTE/releases/v5.20.1)

Mit folgenden Ergebnis von `pihole -g`
`Parsed 0 exact domains and 549 ABP-style domains`
Unter der Verwendung der Blockliste: https://github.com/AdguardTeam/AdguardFilters/raw/master/BaseFilter/sections/adservers.txt

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Das Thema hatten wir vor 2 Wochen noch im Twitch-Stream. Aber wir hatten den Link nicht und insoweit haben wir das evtl. falsch interpretiert.

Es kam die Frage auf, ob Adguard Home ABP-Style Domains unterstützen kann und das haben wir verworfen. 

Aber gem. dem o.g. Link, scheint das Pihole den einen dort beispielhaft angegebenen ABP-Style jetzt doch zu unterstützen. Das eröffnet natürlich viele Möglichkeiten. :-) Auch zum Overblocking. :-(

Müssen wir mal schauen, wie wir das ordentlich umsetzen.

Vielen Dank und viele Grüße

**Comment by RPiList** [comment]
Fast alle Listen wurden umgestellt. Vielen Dank noch mal für den Hinweis. Viele Grüße
