### ISSUE TITLE
False Positive openairsg.ch

### ISSUE THREAD

**Issue by higgs01** [RPiList/specials#1059]
Hallo

Das Openair St. Gallen ist ein grosses OpenAir-Festival in der Schweiz. Die URL davon ist fälschlicherweise in `Blocklisten/malware` enthalten. Es handelt sich dabei um folgende URLs:

- blog.openairsg.ch
- openairsg.ch
- proto.openairsg.ch
- www.openairsg.ch

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Die Domains wurden entfernet. Viele Grüße

**Comment by JohnKNess** [comment]
Hallo zusammen 

Aus irgendwelchen unerfindlichen Gründen haben es die folgenden Adressen wieder in die Liste (malware.txt) geschaftt. 

- blog.openairsg.ch
- proto.openairsg.ch
- www.openairsg.ch

Bei der Suche in Pi-Hole werden die folgenden Infos herausgegeben: 

> Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
>   ||blog.openairsg.ch^
>   ||proto.openairsg.ch^
>   ||www.openairsg.ch^

Fragen: 
- Wie kommen die Domains / Subdomains wieder in die Liste? (Siehe Issue #1059)
- Könntet ihr die Domains bitte wieder entfernen? 

Gruss aus der Schweiz

JohnKNess
