### ISSUE TITLE
goooogle.com: weiterleitung

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#106]
goooogle.com leitet zu https://investcheckbot.info/blog?utm_campaign=VbXRQWUkOs&match=ron&placement=519e8a023a63fd1c04021672&keyword=ron&cost=0.0307&clickid=01fa37d27eabd016fd47adbbcb8859d65588b0c683.r.1582909958.3f9eaf9a510fac2b93f76db1db2a0c5e&campaignname=RON-DE-DESKTOP-Jan20&v3=ron weiter.

Das ist dann eine weitere Seite nach dem https://youtu.be/64C30gpzBvU Prinzip.

**Comment by RPiList** [comment]
goooogle.com genauso wie die Zielseite sind jetzt in der spam.mails Liste eingetragen. 

Vielen Dank für Ihre Mühen.

Viele Grüße
