### ISSUE TITLE
Neue fake shops

### ISSUE THREAD

**Issue by Lignumium** [RPiList/specials#1064]
Hallo zusammen,

die Verbraucherzentrale Hamburg hat eine Liste mit diversen Online Fake Shops veröffentlicht. [Fake Shop Liste: Wenn günstig richtig teuer wird!](https://www.vzhh.de/themen/einkauf-reise-freizeit/online-shopping/fake-shop-liste-wenn-guenstig-richtig-teuer-wird)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
