### ISSUE TITLE
Fake Post SMS

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1065]
Heute reinbekommen

Ihre Paketlieferadresse ist falsch, bitte aktualisieren Sie die Adresse innerhalb von 24 Stunden, sonst werden wir sie zurucksenden. https://s.id/1Nzcn

Das sonst werden wir sie zurücksenden, klinkt auch als würden die mich dann wegsenden, haha

**Comment by Vickyistda2003w** [comment]
Domian schon in meiner Liste durch die selbe FakeSMS die ich letzte Woche bekommen haben

**Comment by RPiList** [comment]
Wunderbar, dann kann das hier schon geschlossen werden. Viele Grüße und vielen Dank für die Mühen.
