### ISSUE TITLE
False Positive: pecl.php.net

### ISSUE THREAD

**Issue by kimberlyeet** [RPiList/specials#1066]
pecl.php.net ist in pornblock3 drinnen, Ist eine repo für php extensions.

**Comment by RPiList** [comment]
pecl.php.net is not in our lists listed. Just checked. Greetings.

**Comment by kimberlyeet** [comment]
![image](https://github.com/RPiList/specials/assets/44536631/f04b66ff-ad9a-4730-9dc2-2920d7d04aca)

In row 1356435, just downloaded the file from git, if I'm being mistaken sorry.
