### ISSUE TITLE
False positive scrumpoker-online.org

### ISSUE THREAD

**Issue by dennisvandehoef** [RPiList/specials#1069]
Heey, 

Ich sehe das `scrumpoker-online.org` so wie `blog.scrumpoker-online.org` in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling gelistet sind.

Dies sind aber keine `gambling` Seite, es betrifft hier ein kostenloses Tool zur Betreibung von [Planning poker](https://en.wikipedia.org/wiki/Planning_poker). Es ist für mich leider nicht einsehbar, aus welcher eure Quelle dieser Seite kommt.

Der Liste enthält mehr Domains die `scrum poker` in ihr Name habe und womöglich ein false-positive sind.

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info, die Domains wurden entfernet. Viele Grüße
