### ISSUE TITLE
onedrive Syncronisation geblockt!?

### ISSUE THREAD

**Issue by CGather** [RPiList/specials#107]
Hallo,
bitte nehm die Adresse "onedrive.live.com" aus diese Liste raus.
Darüber syncronisiert sich Onedrive!
Grüße
Christian

**Comment by CGather** [comment]
Sorry, vergessen.
onedrive.live.com ist in der Liste: Phishing-Angriffe

**Comment by RPiList** [comment]
Liste wurde aktualisiert.

Vielen Dank für Ihre Mühen.

Viele Grüße.
