### ISSUE TITLE
Sparkasse Phishing?

### ISSUE THREAD

**Issue by Zoey2936** [RPiList/specials#1071]
Hallo, heut kam bei uns folgende SMS an, ich vermute, es ist Phishing, bin mir aber tatsächlich nicht sicher, weil das ganze kam nicht von einer Handynummer, sondern von „Sparkasse“, aber das lässt sich vermutlich leicht fälschen.
![grafik](https://github.com/RPiList/specials/assets/75573284/3e756826-bacd-4915-a84a-7667668a38c0)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde importiert. Viele Grüße
