### ISSUE TITLE
verschiedene Einträge in Listen werden nicht mehr erkannt.

### ISSUE THREAD

**Issue by Bloodpack** [RPiList/specials#1075]
Hallo, 

ich nutze diese Blocklisten mit meiner pfSense und PFblocker, leider werden einige Listen und deren Einträge nicht mehr erkannt

mal einige als Beispiel:

- [notserious](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious)
- [streaming](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming)
- [Domainsquatting1](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1)
- [Domainsquarring2](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting2)

hängt das mit der Formatierung zusammen??

`||007drones.de^` speziell am Anfang der Domain `||`

Gruß

**Comment by RPiList** [comment]
Hi,

ja, das wird damit zusammenhängen. Wir "kastrieren" unsere Listen freiwillig, weil das Pihole mit dieser Formatierung erweiterte Möglichkeiten bietet. 

Auf Wunsch können wir gerne eine eigene Abteilung pfSense und PFblocker erstellen. Vielleicht mal prüfen, ob es andere Möglichkeiten gibt, pfSense und Co. auch solche Fähigkeiten beizubringen. Ich baue die Listen gerne wunschgemäß um.

Im schlimmsten Fall werden die "alten" Listen für pfSense und Co weitergeführt...

**Comment by Bloodpack** [comment]
Hallo und danke für die Antwort.

Es wäre MEGA wenn es eine pfSense/pfblocker Abteilung geben würde mit dem alten Format.

Die Listen sind einfach genial! Vielen Dank für die Arbeit
