### ISSUE TITLE
False positives 

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#1077]
Hallo Sprecher,

nachdem letztens meine .de-Domain in einer der Blocklisten aufgetaucht ist, habe ich heute durch Zufall entdeckt, dass fast alle andere Domains von mir auch in der Liste enthalten sind. 

Könnte ich wissen, weshalb all diese Domains in der Blockliste gelandet sind und darum bitten, diese daraus zu entfernen?

Unten befindet sich eine Liste die einfacher zum rauskopieren sein sollte.

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  spielenmitlili.com
  www.spielenmitlili.com

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  cute-lili.de
  www.cute-lili.de

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  lilink.de
  www.lilink.de

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  lili-urban.net
  www.lili-urban.net

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  pawel-urban.com
  www.pawel-urban.com

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  smlili.systems
  www.smlili.systems

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  spielenmitlili.eu
  www.spielenmitlili.eu

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  familie-gralczyk.eu
  www.familie-gralczyk.eu

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  lili.business
  www.lili.business

Hier einmal die Liste zum rauskopieren:
 spielenmitlili.com
 www.spielenmitlili.com
 cute-lili.de
 www.cute-lili.de
 lili.business
 www.lili.business
 familie-gralczyk.eu
 www.familie-gralczyk.eu
 spielenmitlili.eu
 www.spielenmitlili.eu
 smlili.systems
 www.smlili.systems
 lili-urban.net
 www.lili-urban.net
 pawel-urban.com
 www.pawel-urban.com
 lilink.de
 www.lilink.de

**Comment by RPiList** [comment]
Hallo Lili,

sorry für die Umstände. Die Domains wurden durch Vicki aus dem Twitch-Chat bei uns eingespielt. Werde sie morgen mal fragen, wie das passieren konnte.

Domains sind jetzt alle entfernt und auf der internen Whitelist. Können also auch künftig nicht gelistet werden. Viele Grüße
