### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#1078]
Hallo Sprecher,

beim Surfen sind mir ebenfalls 2 Mastodon-Instanzen aufgefallen, welche sich jeweils in den Blocklisten befinden sowie ein Dienst zum Zusammentragen eigener Reisen mit ÖPNV.

Ich nutze diese beiden schon seit längerer Zeit persönlich und sehe keinen Grund für eine Sperre, da alle "gefährlichen" oder auf andere Art problematischen Inhalte moderiert werden:

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  www.zug.network
  zug.network

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  cuties.social
  www.cuties.social

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  traewelling.de
  www.traewelling.de

Einmal die entsprechenden Einträge aus der Blocklist 
zug.network
www.zug.network
cuties.social
www.cuties.social
traewelling.de
 www.traewelling.de

**Comment by RPiList** [comment]
Hi,
die kommen ebenfalls alle aus Vickis Liste. Konnte noch nicht mit ihr sprechen. 

Domains sind alle entfernt. 

Nochmals sorry... viele Grüße und vielen Dank für die Info.
