### ISSUE TITLE
False positives qognify.com

### ISSUE THREAD

**Issue by rliegmann** [RPiList/specials#1080]
Hallo zusammen,

die Domain `qognify.com` steht als gesperrte Liste in `child-protection` und wird durch pihole gesperrt.
Es handelt sich hier um die Firma Qognify die Video Management Systeme vertreibt.
Ist es Möglich diese Domain aus der Blockliste zu entfernen?

Für Fragen stehe ich gerne zu Verfügung
LG rliegmann

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
