### ISSUE TITLE
Domains erneut in der Blocklist

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#1083]
Guten Abend Sprecher,

ich greife hierbei nochmal das Issue: https://github.com/RPiList/specials/issues/1078 auf. 

die Domains:

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  www.zug.network
  zug.network

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  cuties.social
  www.cuties.social

sind wieder in derselben Liste aufgetaucht. Hat das bestimmte Gründe?

Liebe Grüße

**Comment by RPiList** [comment]
Hi,

also den Schuh werd' ich mir wohl anziehen müssen. Das war der erste Fund von Dir und den hatte ich noch nicht in die Whitelist gepackt. Jetzt sind sie es aber.

Viele Grüße
