### ISSUE TITLE
Megaliste

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1094]
Hey Sprecher und Chat,

Ich habe das Problem das sobald ich die megaliste.py starte und das Skript mir die Liste erstellt kommt es das alle Listen unter Domiansqating/AT mitreingekommen.

Ich habe auch schon mehrmals die Quellen im Skript geuptet aber es kommt immer das diese Domians nicht in der Liste sind.
Da ich mit meinen Wissen nicht weiter kommen, hoffe ich sehr das du mir weiterhelfen kannst

Ganz liebe grüße
Vicky

Kuss

**Comment by RPiList** [comment]
Die Megaliste ist wieder auf dem neuesten Stand. Viele Grüße
