### ISSUE TITLE
fastly.net geblockt

### ISSUE THREAD

**Issue by Zoey2936** [RPiList/specials#1103]
Hallo, auf der gambling liste wird fastly.net geblockt, das hat zur folge das mein AdguardHome per CNAME/IP reddit blockt...

**Comment by Zoey2936** [comment]
wie ich sehen gibt es aktuell viele Probleme mit der Liste, ich hab die erstmal aus gemacht

**Comment by andreaswilli** [comment]
Mein Pi-hole blockt aktuell ebenfalls reddit:

```
www.reddit.com
(blocked reddit.map.fastly.net)
```
```
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling:
   ||fastly.net^
```

**Comment by xXFabi95** [comment]
Twitch ist auch davon betroffen.

**Comment by BilginSahin** [comment]
fast alle seiten sind davon betroffen =P von playstation bis insta bis zalando =D

**Comment by RPiList** [comment]
Hi,

sorry für die Umstände. Liste in Pihole neu updaten, dann hat sich das Problem erledigt. Viele Grüße
