### ISSUE TITLE
*.ac.at blockiert, viele Probleme bei anderen Domains und Services

### ISSUE THREAD

**Issue by rockermeier** [RPiList/specials#1106]
Es werden fälschlicherweise alle akademische Institute in Österreich blockiert. So z.B. tuwien.ac.at oder univie.ac.at

**Comment by rockermeier** [comment]
Es scheint beim Algorithmus mehrere Probleme zu geben. Viele Services lassen sich nicht nutzen.

**Comment by BilginSahin** [comment]
Gleiche Probleme hier. Viele Seiten gehen nicht mehr

**Comment by RPiList** [comment]
Hi,

sorry für die Umstände. Liste in Pihole neu updaten, dann hat sich das Problem erledigt. Viele Grüße
