### ISSUE TITLE
Akamai, Microsoft und viele mehr blockiert, ebenso DynDNS-Anbieter

### ISSUE THREAD

**Issue by rockermeier** [RPiList/specials#1107]
Es werden seit heute plötzlich Services von Akamai (edgekey.net), Services von Microsoft wie www.microsoft.com, login.microsoftonline.com sowie mehrere Dyndns-Anbieter blockiert. Getestet wurden akamai.com, ddnss.de, duckdns.org, de.godaddy.com

Vgl. ebenso #1106

**Comment by smpby** [comment]
Betrifft auch tesla.com

**Comment by Monty2kle** [comment]
Folgende Domains sind in der Gambling und Pornblock1 blockiert;
akamaiedge.net
akadns.net
fastly.net

Das blockiert mir das "halbe Internet" - reddit.com, bing.com etc., weil die DNS-Aliase verwenden.

Für alle anderen Betroffenen hier mal mein quick'n'dirty-Walkaround:
1. Kommandozeile: "nslookup <blockierte Domain> 1.1.1.1"  oder auch statt 1.1.1.1 mal 8.8.8.8
2. unten stehen u.U. die Alias-Domains - die sucht ihr dann im pihole über "tools - search adlists"
3. wenn sie da drin waren, legt ihr euch unter "Domains" einen Whitelist-Eintrag an und setzt den Wildcard-Haken

Achtung: die genannten Domains werden auch für Schmutz verwendet - mit diese Workaround werden die Schmutz-Seiten auch freigegeben. Die andere Alternative wäre der Verzicht auf o.g. Listen (auch nicht gut) oder das Bearbeiten der Listen (kein Plan, wie man das update-beständig machen kann).

**Comment by RPiList** [comment]
Hi,

sorry für die Umstände. Liste in Pihole neu updaten, dann hat sich das Problem erledigt. Viele Grüße
