### ISSUE TITLE
Synology domain geblockt

### ISSUE THREAD

**Issue by 0x404-NameNotFound** [RPiList/specials#1108]
es werden seit gestern (zumindest hat sich da mein pihole geupdated) ide Synology domains die auf:

disktation.me

enden geblockt. Resultierte darin das ich mein NAS nicht mehr erreichen konnte.
Wird bestimmt einigen Leuten so gehen.

Der entsprechende Eintrag ist in der Liste gambling

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling:
  ||diskstation.me^

**Comment by synic2009** [comment]
Gleiche Problem bei:
dscloud.me

**Comment by RPiList** [comment]
Hi,

sorry für die Umstände. Liste in Pihole neu updaten, dann hat sich das Problem erledigt. Viele Grüße
