### ISSUE TITLE
Blocklisten.md

### ISSUE THREAD

**Issue by vaake** [RPiList/specials#111]
In der Blocklisten.md hat sich ein Fehler eingeschlichen.
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock-1
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock-2
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock-3
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock-4

Bitte ändern auf 
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock1
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock2
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock3
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4

Thx

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

Änderung wurde durchgeführt.

Vielen Dank für Ihre Mühen.

Viele Grüße

Am Sa., 29. Feb. 2020 um 10:59 Uhr schrieb vaake <notifications@github.com>:
