### ISSUE TITLE
Gambling Liste Crasht Netzwerk

### ISSUE THREAD

**Issue by FoxXxHater** [RPiList/specials#1114]
Moin, 

ich wollte hier auch nochmal unterstreichen das die Liste fast den gesamten Internet Verkehr lahm legt. 
Der fastly Eintrag scheint rein zu hauen...

Lösung:
Liste Deaktiviert

Was mir jetzt aufgefallen ist:

![image](https://github.com/RPiList/specials/assets/54017453/d331e374-0ceb-435a-b456-bb0d9e661d24)
![image](https://github.com/RPiList/specials/assets/54017453/9f47e180-60c7-4f8d-af17-e55f726f3c9c)
![image](https://github.com/RPiList/specials/assets/54017453/ce40c0b3-654f-4a57-8a26-95394c47e179)
![image](https://github.com/RPiList/specials/assets/54017453/620ba7e5-7bde-4bbf-9560-6be8fe861e45)

**Comment by RPiList** [comment]
Hi,

sorry für die Umstände. Liste in Pihole neu updaten, dann hat sich das Problem erledigt. Viele Grüße
