### ISSUE TITLE
Edgesuite domains werden blockiert

### ISSUE THREAD

**Issue by MeteorTheLizard** [RPiList/specials#1115]
> https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling
`||edgesuite.net^`

Blockiert viele inhalte auf steam und anderen seiten.

**Comment by RPiList** [comment]
Hi,

sorry für die Umstände. Liste in Pihole neu updaten, dann hat sich das Problem erledigt. Viele Grüße
