### ISSUE TITLE
Gambling und Porn Listen updaten!

### ISSUE THREAD

**Issue by RPiList** [RPiList/specials#1116]
Hi,

die Probleme mit diesen zwei Listen sind bekannt und deswegen wurden die jetzt erstmal komplett geleert. D.h. wer Probleme hat, aktualisiert seine Listen (oder deaktiviert sie in Pihole).

Wir bauen die von Grund auf neu auf. Sorry für die Umstände

**Comment by Rikkert-RS** [comment]
Alles klar hab mich nun gerade schon gewundert warum die Listen nun ganz leer ist.

War ein revert auf den 30.06 oder früher keine Option?

Mit freundlichen Grüßen

**Comment by Littleeeeeeee** [comment]
Mal so aus Interesse. Wie kommt's dass beispielsweise ultimate-guitar.com auf die Gambling-Liste kam?

**Comment by RPiList** [comment]
> War ein revert auf den 30.06 oder früher keine Option?

So wie ich das sehe, hätte ein Revert das eigentliche Problem nicht gelöst. Mit einer sauberen Liste neu anzufangen halte ich für sinnvoller. Das hätte schon längst gemacht werden müssen.

Durch die zweite Stufe der Umstellung auf die ABP-stlye Domains ist es mir jetzt um die Ohren geflogen.

**Comment by RPiList** [comment]
> Mal so aus Interesse. Wie kommt's dass beispielsweise ultimate-guitar.com auf die Gambling-Liste kam?

Da gibt es verschiedene Theorien, aber alle haben damit zu tun, dass mal eine falsche Liste von mir importiert wurde.

Ich habe mal vor Ewigkeiten ausversehen eine Tracking-Liste in die Gambling Liste importiert. Tracking passiert in Subdomains (z.B. tracking.ultimate-guitar.com) und fällt daher nie jemandem auf.

Jetzt hatten wir ja das Update mit ABP-style Format und da hat das letzte Update diese Fehler nach oben gespült.

Geplant war dass z.B.:

de.pornsite.de
uk.pornsite.de
www.pornsite.de
fetisch1.pornsite.de
fetisch2.pornsite.de

alle (und noch viel mehr) mit ||pornsite.de^ geblockt werden. Dazu werden aber dann alle Subdomains gelöscht.

Wenn ich aber einen false Positiv wie "tracking.good-site.de" drin hatte... ist das wie gesagt, vorher nie jemandem aufgefallen. Weil die Hauptdomain ja immer funktioniert hat.

Mit dem o.g. Update wurde aber auch hier die Subdomain entfernt und nur noch good-site.de drin gelassen.

Deswegen der große Kollateral-Schaden.

**Comment by Littleeeeeeee** [comment]
Danke für die Erklärung! 👌
