### ISSUE TITLE
Fake ÖBB seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1118]
Moin,

Hinter diesen link befindet siche eine Fake seite der Österreichischen Bundesbahn

https://8brickarcade.com/KxgcvqYP?utm_creative=F475_AT4&utm_campaign=F475_AT4&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=23855010773130533&adset_id=23855010774350533&ad_id=23855010774460533&adset_name=F475_AT4&fbp=1299416604115777&web=ars&fbclid=IwAR1d0hPjCLwD43FQptQy5gBMq00lL-ZVcOVPg5yuFo3Q_pyGwOaFSffvAq0#

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
