### ISSUE TITLE
svpihole zusammen mit ovpn?

### ISSUE THREAD

**Issue by sponkpi** [RPiList/specials#112]
Hallo,
ist es möglich svpihole zusammen mit OVPN auf einen Raspi zu betreiben?
Ich habe das kurz ausprobiert und svpihole installiert, konnte mich aber für die OVPN Installation nicht per SSH aufschalten weil der Zugang über das Standardlogin -pi - und - raspberry- nicht funktionierte. Gibt es da andere Zugangsdaten?
LG

**Comment by RPiList** [comment]
Ja, das ist möglich, das haben wir ein einem Video auch bereits gezeigt. Die Logindaten liegen in der info.txt Datei, die ebenfalls in der ZIP Datei war.
