### ISSUE TITLE
In Blocklisten.md a link is no longer valid

### ISSUE THREAD

**Issue by domalex** [RPiList/specials#1120]
Please change the following URL accordingly.

Old:
[https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt)

New:
[https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers_justdomains.txt](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers_justdomains.txt)

**Comment by RPiList** [comment]
Hi,

change of link has been done. thx @ [LizenzFass78851](https://github.com/LizenzFass78851) for the pull request. Greetings.
