### ISSUE TITLE
Swedish state railways (sj.se) blocked on malware list

### ISSUE THREAD

**Issue by Mekkornia** [RPiList/specials#1123]
sj.se was recently added which seems peculiar since that is the Swedish state railways where most of go for national and international train tickets. Other blocking lists contain subdomains, but blocking sj.se in full is a little aggressive it seems.

https://v.firebog.net/hosts/RPiList-Malware.txt accessed 2023-07-03

**Comment by RPiList** [comment]
Hi,

thx for letting us know. Domain has already been removed from our Lists on Saturday. We just have to way until firebog.net imports our list.

Or you just import the original. Greetings
