### ISSUE TITLE
Entry ||edgekey.net^ too restrictive

### ISSUE THREAD

**Issue by KHerzberg** [RPiList/specials#1124]
With this entry, the media library of the public broadcaster ARD is blocked in the "Pornblock1" blocking list.

**Comment by KHerzberg** [comment]
The entry ||akamai.net^ then blocks the playback of the programmes/videos (a958.dscw4.akamai.net).

**Comment by ryrun** [comment]
See issue #1116 
Its related.

**Comment by RPiList** [comment]
Hi,

issue has been fixed. Please update your lists. Greetings
