### ISSUE TITLE
Moin ist eine Fake Jet Tankstellen Gewinnspiel

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1126]
https://dein-benzin.deingoldesel.de/campaign_4046.html?coyoteAffiliTokenId=496835938&fbclid=IwAR2swOOGUWukqROxh1XTUJm-rXAiTzlqVjx14Cg0zFfyRGeAb3Z-cNK09y4&

**Comment by RPiList** [comment]
Vielen Dank für die Einsendung. Hier nutze ich mal die neuen Möglichkeiten und Blocke alle Subdomains von deingoldesel.de. Viele Grüße. Domain ist jetzt in der fake-shop Liste. Viele Grüße
