### ISSUE TITLE
false positive fastly.net

### ISSUE THREAD

**Issue by pud-micha** [RPiList/specials#1133]
Moin,

bei gambling steht *.fastly.net. Damit wird auch reddit.map.fastly.net ausgeschlossen. Das ist ein CNAME von www.reddit.com

Gruß

**Comment by RPiList** [comment]
Bitte die Gaming und Porn-Listen updaten. Die Domains wurden am Sonntag entfernt. Das Update ist nur noch nicht bei Ihnen angekommen. Viele Grüße
