### ISSUE TITLE
false positive "obo.de"

### ISSUE THREAD

**Issue by Prideland** [RPiList/specials#1134]
Die Seite der Firma OBO Bettermann (Elektro- und Gebäudeinstallationstechnik) wird in der Liste DomainSquatting1 geblockt.

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1:
  ||obo.de^

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
