### ISSUE TITLE
webseiten-daten.cc

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1135]
Moin, diese URL ist auf einer Webseite eingebunden und mein Antivirus Programm hat sofort einen harten bekommen dabei und die seite als verdächtig gesperrt, wird auch von Virustotal erkannt.

LG

**Comment by Vickyistda2003w** [comment]
Hey, das ist meine URL, da liegen einfach Bilder und Videos die ich für meine Webseiten nutze, da ist überhaupt nix mit viren oder was anderes

**Comment by RPiList** [comment]
Virustotal sagt bei mir, dort wäre alles clean. Bis auf natürlich die üblichen Wichtigtuer... die immer was erkennen wollen.
