### ISSUE TITLE
DomainSquatting/DE/Sparkasse/Brandenburg anpassen

### ISSUE THREAD

**Issue by c0by85** [RPiList/specials#1136]
Bitte `||kbs.de^` von [DomainSquatting/DE/Sparkasse/Brandenburg](https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting/DE/Sparkasse/Brandenburg) entfernen.  `kbs.de` gehört zur Knapp­schaft-Bahn-See (KBS) und hat nichts mit Domain Squatting zu tun.

Danke.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
