### ISSUE TITLE
Blocklisten mit Putty einfügen?

### ISSUE THREAD

**Issue by renner1962** [RPiList/specials#114]
Hallo,wie kann man Blocklisten mit Putty einfügen ?Geht das?

Danke René

**Comment by benjaminwolkchen** [comment]
In dem Video von Sempervideo wird es gezeigt: https://www.youtube.com/watch?v=dFPKoKq7qM8

**Comment by RPiList** [comment]
@benjaminwolkchen Danke für die Beantwortung.

Zu beachten ist noch, dass das Video eine ältere Version von Pi-hole zeigt. Es ist (theoretisch) möglich, dass das Gezeigte in der aktuellsten Version nicht mehr funktioniert. Also vor Änderungen ein Backup der Datei anlegen.

**Comment by renner1962** [comment]
@benjaminwolkchen Danke für die Beantwortung .

René
