### ISSUE TITLE
False positives in der crypto-Sperrliste

### ISSUE THREAD

**Issue by gamerxD1998** [RPiList/specials#1147]
In der Crypto-Sperrliste befinden sich einige Domains von Anbietern für Ad-Tracking, Analytics hinsichtlich Ads oder CDNs für Ads.
Diese haben offensichtlich nicht zwingend etwas mit Domains zu tun, auf denen Cryptomining oder Ähnliches betrieben wird.
Sie befinden sich daher in der falschen Liste und wären in der EasyList besser aufgehoben (falls sie da nicht schon drin sind, nutze diese nicht).

Folgende Domains konnte ich bereits identifizieren, es könnten aber auch noch weitere solche Domains drin sein:

- bh.contextweb.com
- adnxs.com und sämtliche Subdomains
- doubleclick.net und einige/sämtliche Subdomains (nicht alle geprüft)
- pr-bh.ybp.yahoo.com (evtl. weitere Subdomains von yahoo.com vorhanden, bisher war bei meinen Tests nur diese Domain auffällig)
- ad.turn.com
- rubiconproject.com und sämtliche Subdomains
- ads.pubmatic.com
- googlesyndication.com und sämtliche Subdomains
- 2mdn.net und sämtliche Subdomains
- adsafeprotected.com und sämtliche Subdomains
- amazon-adsystem.com und sämtliche Subdomains
- www.google-analytics.com
- sync-tm.everesttech.net
- match.prod.bidr.io
- match.adsrvr.org
- taboola.com und sämtliche Subdomains
- dpm.demdex.net
- sync.mathtag.com
- adform.net und sämtliche Subdomains
- dsp.adfarm1.adition.com
- static.criteo.net

Es ist jedenfalls erstaunlich, dass sowas über 7 Monate (letzter Commit für diese Liste ist so alt) nicht auffiel. Vielleicht weil die meisten die EasyList nutzen und somit eh keine Werbung angezeigt wird. In meinem Fall ist das Blocken von Werbung jedoch nicht gewünscht sondern nur das Blocken von schädlichen Seiten/Domains.

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info. Die Liste ist uralt, erfährt praktisch keine Pflege mehr, da sich das Thema weitgehend erledigt hat. Vielleicht ist es deswegen nie jemandem aufgefallen. Auf der anderen Seite ist die easylist die beliebteste Liste... und da fallen die doppelten Einträge nicht auf.

Wie dem auch sei: 92 Domains wurden von der Cryptoliste entfernt. Viele Grüße
