### ISSUE TITLE
Analyticsseite zum Sperren

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#1148]
Hallo zusammen,

unter analytics.learningapps.org scheinen Analytics-Daten gesammelt zu werden.

Die Seite scheint ohne diese Domain weiterhin funktional zu sein, sodass tatsächlich nur Analyticdaten darunter gesammelt zu sein scheinen.

Bitte daher am besten einmal wegsperren

Liebe Grüße 

Lili

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
