### ISSUE TITLE
https://www.thegadgetreviewguy.com

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#115]
https://www.thegadgetreviewguy.com ist eine weitere Seite nach dem Prinzip: "Bitcoin Abzocke" https://youtu.be/64C30gpzBvU

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

Der Eintrag wurde in unsere Spam.Mails Liste hinzugefügt.

Viele Grüße
