### ISSUE TITLE
Seltsame Blocks in specials/easylist

### ISSUE THREAD

**Issue by JeGr** [RPiList/specials#1151]
Hi,

wir haben u.a. nach den Problemen mit der "gambling" Liste das Logging unserer DNSe erhöht um false positives zu tracken. Aktuell sehe ich in meiner eigenen PiHole Instanz wieder legitime Seiten geblockt, diesmal in der "easylist".

Aktuell seltsam: 

* congstar.de
* www.congstar.de

Damit gehen dann weder Web noch App vom Anbieter, das macht wenig Sinn für mich. Die Banner Subdomain wird ja separat geblockt?

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
