### ISSUE TITLE
Vorschlag: Domains aus "Piracy Index" in Streaming-Liste aufnehmen

### ISSUE THREAD

**Issue by Wh1t3Pige0n** [RPiList/specials#1155]
Liebes SemperVideo Team,

Gemäß dem geschlossenen Issue [#1004] über den Vorschlag, das GitLab-Projekt "Piracy Index" in RPiList einzubinden, habe ich die benötigten Informationen aus der "Piracy Index"-Domain extrahiert. Durch die Aufnahme der Domains aus "Piracy Index" in die Streaming-Liste könnten Nutzer erweiterte Schutzmöglichkeiten erhalten, indem der Zugriff auf diese illegalen Ressourcen, welche urheberrechtlich geschütztes Material anbieten, blockiert wird.

RPiList zielt darauf ab, Nutzer vor Bedrohungen wie Fakeshops, Werbung, Tracking und anderen Internetangriffen zu schützen. Die Integration des "Piracy Index" in die Blockliste würde den Schutzumfang erweitern und Nutzern helfen, potenzielle Risiken der digitalen Piraterie zu vermeiden.

Viele Grüße

Hier sind die entsprechenden Domains:

## Anime streaming:
9anime.to
4anime.to
anime8.me
gogoanime.io
gogoanime.video
gogoanimes.co
gogoanime.in
anilinkz.to
kisscartoon.info
kisscartoon.ac
kisscartoon.love
kissanime.nz
kissanime.ac
kissasian.ch
watchcartoononline.com
watchcartoononline.io
watchcartoonsonline.la
toonova.net
animepahe.com
animeram.cc
animeseries.co
animevibe.tv
animetoon.org
watchanime.info
animekisa.tv
animesimple.com
anime2you.de
animetake.tv
animebam.net
animebam.se
animereborn.io
animeboys.net
kaze-online.de
animedao.com
animefever.tv
animeflix.io
animeflv.net
animefreak.tv
animehub.ac
animekisa.com
animelon.com
animerush.tv
animetv.ge
animeultima.eu
animeultima.to
aniwatch.me
animeworldbd.com
aniwatcher.com
twist.moe
cartooncrazy.tv
cartoonwire.to
chia-anime.cc
daiweeb.org
dubbedanime.net
dubbedanime.biz
eyeonanime.tv
kawaiifu.com
kickassanime.io
kickassanime.rs
moviesever.com
nineanime.com
randaris.app
ryuanime.com
serienjunkies.org
sganime.org
novelplanet.com
tokyotosho.info
unblocked.gdn
your-anime.com
kimcartoon.co
topcartoons.tv
supercartoons.net
b98.tv
fullepisodes.biz
serieslan.com
animetoast.cc

## Anime downloading:
hi10anime.com
animekayo.com
animencodes.com
animeout.xyz
horriblesubs.info
animevibe.xyz
darkanime.stream
thehylia.com
megatronencodes.com
animk.info
animekaizoku.com
animedimension.me
animes.so

## Filme/Serien Streaming:

movie123.club
streamlord.com
flixgo.net
123movies.website
yesmovies.to
spacemov.io
hdonline.eu
1movies.is
azmovies.xyz
arabseed.tv
bestfreestreaming.com
cmovieshd.bz
dpstream.net
fmovies.to
fmovies.se
fmovies.is
filmz.cc
flixanity.xyz
hdm.to
hdo.to
indoxxi.cx
k-streaming.tv
lookmovie.ag
mkvhub.com
nox.tv
pelispedia.tv
qwemovies.com
rainierland.is
series9.io
soap2day.com
sokrostream.vip
solarmoviez.ru
sharemania.us
streamcouch.com
streamcomplet.me
takiartmovies.ga
tubeninja.net
voirfilms.ws
cine.to
cinebloom.com
emule-island.ru
libertyvf.org
yourptflixmovies.com
movie-forum.co
filmyzilla1.com
puretoons.me
deadtoonsindia.ne
reelgood.com

## Filme/Serien Streaming HDR/4k:
4kmedia.org
predb.me
4k-hd.club
4k-hdr.org
beyond-hd.me
blu-ray.world
hdss.watch
moviefiles.org
nima4k.org
privatehd.to
rarbg.to
uhdbits.org
uhdmv.org
zamunda.net
vidflix.net
freemovie4konline.com

## Filme/Serien Downloading:
5movies.to
solarmovie.fm
solamovies.cc
worldsrc.org
two-movies.net
putlocker.onl
putlockerfreely.online
putlockeri.club
8putlocker.com
afdah.to
bs.to
cafehulu.com
dokujunkies.org
freemoviesz.online
los-movies.com
m4ufree.tv
movie4k.io
primewire.is
sockshare.ac
solarmoviehd.to
torrentdownloads.me
vioozgo.org
mxplayer.in
rmz.cr
60-fps.org
filmxy.one
mkv4u.net

## Third Party Hosts:
vmovee.me
uwatchfree.tv
oakmovies.com
vexmovies.org
openloadmovies.net
vodlocker.tv
movie2k.st
xpau.se
megashare9.su
xmovies8.ru
icefilms.info
1movies.nl
watchfullmovie.co
watchfree.at
pahe.in
Pahe.me
pahe.ph
megaddl.co
mp4upload.com

## Filme/Serien Streaming 1080p:
0123moviesback.com
sonycrackle.com
cyberflix.me
crawler.to
fembed.com
goldesel.to
europixhd.net
topeuropix.net
katmoviehd.nl
leonflix.net
coolmoviejagg.pro
moviestreams.org
onemov.net
onmovies.to
streammango.com
streamplay.to
teatv.net
verystream.com
videospider.in
vmovee.ws
ymovies.tv
psarips.one
bonsaihd.site
allostream.biz
annuaire-telechargement.best
annuaire-telechargement.al
annuaire-telechargement.fr
movies4you.ovh
divxtop.com
dpstream.com
dpstreaming.vip
etopop.fr
filmcomplet.vip
filmstreaming1.rip
filmstreaming1vf.co
frstream.org
hds-stream.to
libertyland.al
n1streamings.com
papy-streaming.fr
streaming-planet.com
rarefilm.net
rarefilmm.com
radego.com
guardaserie.tube
seriecomplete.com
launchpad.net
streamcomplet.page
vostfree.com
StreamingDIVX1.com
time2watch.gg
voirfilms.al
vostfrserie.biz
wikiserie.biz
dramaday.net
enthus1ast.com
magellantv.com
hevcbay.com
x265movies.co
hugewarez.net
mkvbee.com
yourserie.com
crazy4tv.com
movieswbb.com
gdrivedl.com
streamingita.live
123movies.is
dirtywarez.org
hdmovie8.com
hindimoviesonline.club

## Filme/Serien Streaming 720p:
123gomovies.net
123moviesuk.to
123netflix.pro
bmovies.to
bmovies.life
bmovies.se
bmovies.is
cafemovie.live
ddlhub.xyz
flix555.com
flixtor.to
gomovieshub.se
hackimdb.com
hdeuropix.io
hdvix.com
ilovetowatch.online
iwannawatch.is
khaanflix.com
megadede.com
movidy.co
movieglide.com
movies24.top
nicemoviezion.pro
niter-movies.com
surge.sh
sendit.gg
seriesfree.to
seriestop.net
allsprk.tv
streamdreams.org
tfp.is
timetowatch.video
tubitv.com
tvmovies.to
nicetvzion.pro
ulmovies.com
vidcloud.icu
vidflox.me
vipbox.live
watchfree.ac
watchfree.at
watchfree.movie
watchonline.al
wawacity.ec
yesmovies.fun
zmovies.top
worldscinema.org
xyztv.xyz
ask4movie.co
seriesvault.org
o2tvseries.co
ok.ru
tuga.tv
mrpiracy.xyz

## Sports Streaming:
bestsportstreaming.com
crickfree.org
cytu.be
footybite.com
livesx.eu
mamahd.org
sendit.gg
stream2watch.ws
streamwoop.net
vipbox.live
nbafullhd.com
nbahdreplay.com
watchraw.com
watchwrestling24.net
allwrestling.live
watchwrestling.in
bellator.com
highlightstore.me
mma-core.com
gomostream.com
speedsports.me
720pstream.me
yoursports.stream
crackstreams.com

**Comment by RPiList** [comment]
Vielen Dank für die Mühen. Domains wurden der Streaming-Liste hinzugefügt. Viele Grüße
