### ISSUE TITLE
philipplang-consulting.com

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1157]
volume-trader.com das ist auch so eine Fake Scheiße
gelddasbuch.de nochmehr davon
Ist wieder so einer der auf Facebook sagt mit nur seinen Online Kurs wird man reich, so ein bullshit

Wenn ihr wollt, sammel ich mal alles und mach jeden sonntag oder so einmal ein issues mit allen domains die so nen müll anbeiten

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Wenn nicht zu viel Stress, können Sie gerne die Listen auf einmal hier posten. Viele Grüße
