### ISSUE TITLE
false positive cdn.webde.de

### ISSUE THREAD

**Issue by madzodiac** [RPiList/specials#1158]
In der Liste https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting1 wird die Domain cdn.webde.de m.M.n fälschlicherweise als DomainSquatting geführt. Web.de hat mit dem Domainnamen sicherlich keine Glanzleistung an Seriosität abgeliefert, aber ohne das Whitelisting der Domain funktioniert ansonsten das Webmail bei Web.de nicht mehr.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
