### ISSUE TITLE
Seltsame Angebote auf Facebook

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1162]
Trading: 
hatch.one
digitale-safari.de
prosperi.academy
forexfreiheit.de
deal.academy
companisto.com
thisismarketing.de
volume-trader.com
bitbull-trading.de
vipanzeiger.com
member-trading.de
lionandcrown-ecom.com
mikehager.de
clevertipps.com

Phishing:
stcaribe.com Google melden Phisching Verdacht beim Aufrufen
linktr.ee ist ein Link Verkürzer und bei euch schon mit paar Domians in spam.mails

Unsicher ob Fake oder Echt
padronus.at da bin ich mir selber unsichter

**Comment by RPiList** [comment]
Hi, 

vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
