### ISSUE TITLE
Amazon Echo leuchtet rot.

### ISSUE THREAD

**Issue by oDerPaul** [RPiList/specials#1164]
Nach dem letzten großen Update aller Listen, wollten meine Echos nicht mehr. (Roter Ring, sagt, dass es Probleme mit dem Netzwerk gibt.)

Ich habe daraufhin folgende Domain freigegeben, 

bob-dispatch-prod-eu.amazon.com

Damit funktionierte es wieder alles und Alexa Antwortet wieder.

**Comment by RPiList** [comment]
Die Domain ist nicht in unseren Listen vertreten. 
Entweder kommt das von einer Liste eines Dritten Maintainers oder aber die Domain war auf unseren Listen; ist aber schon in einem der letzten Updates entfernt worden. Viele Grüße
