### ISSUE TITLE
GEZ Medien

### ISSUE THREAD

**Issue by qyqsoft** [RPiList/specials#117]
Interesting for german users...
Für viele ein Ärgernis (Umweltsau/Nazisau Skandal), daher ein Listenvorschlag um GEZ Medien zu blocken: https://raw.githubusercontent.com/qyqsoft/Pihole/master/no-gez.txt

**Comment by vaake** [comment]
Kann das bitte mal jemand löschen.

Inhalt der List....

##############################################
##              GEZ Staatsfunk Medien sperren            ##
##############################################

Einfach nur überflüssig.

**Comment by Ian-Drunkenson** [comment]
Warum sollte man das löschen??? Auch wen man die Liste nicht für sich einsetzen will, könnten es andere das doch nützlich finden. Ich bin allgemein gegen Zensur und Gedankenverbote, sonst kommt der nächste daher und will die Pornolisten löschen lassen und der Dritte will die Jugendschutz Liste weg haben. Wo soll das hinführen?

**Comment by vaake** [comment]
Gegen die Liste ist nichts einzuwenden.

Mich stört nur die Überschrift der Liste. 
„GEZ Medien Sperren“ hatte gereicht. 

Das hat so was unterschwelliger Propaganda !!
Zensur ist was ganz anderes, die Wortwahl ist entscheidend....

**Comment by Ian-Drunkenson** [comment]
Hm, bei mir kommt nur "GEZ Medien sperren"... Aber das ist doch nur im Kommentarteil und welche Propaganda soll das sein? Verstehe den Gedanken jetzt nicht.

**Comment by RPiList** [comment]
Mir würde sich auch nicht erschließen, warum man GEZ-Dienste blockieren wollen würde. Das Projekt SVPihole würde solch eine Liste auch nicht führen. Aber das ist ja auch nicht nötig, da es solch eine Liste schon gibt.

Der Vollständigkeit wegen, werden wir die Liste aber in unsere Datei über die Blocklisten aufnehmen. Dort kann dann jeder entscheiden, ob er so etwas bei sich importieren möchte.

Den gleichen Gedankenprozess durchlaufen wir derzeit für die Springer-Blocker Liste. Die Bild & Co ist sicher geeignet den Leser vollständig verblöden zu lassen. Die gehören ganz sicher auf eine Blockliste. Aber da gibt es auch (Sub-)Unternehmen, die mit solch einer Liste in Sippenhaftung genommen werden, obwohl sie es nicht zwingend "verdient" haben.

Dann würden wir da auch "nur" drauf verlinken, die Liste selbst aber nicht führen.

**Comment by RPiList** [comment]
Ups... den Close Button zu früh gedrückt. Daher hier direkt wieder geöffnet, für den Fall dass noch jemand eine Meinung beitragen möchte.

**Comment by ich423** [comment]
Wo ist [wdrmaus.de](wdrmaus.de)?

**Comment by Stengah966** [comment]
In einer liberalen Demokratie sollte es doch möglich sein, dass jeder für sich entscheidet, ob er diese Liste aktiviert oder nicht.

**Comment by ArnaudFeld** [comment]
Diese Liste sollte nicht aufgenommen werden da sie unabhängige Berichtserstattung blockiert und damit Fascho-Anhängern Macht verleiht andere in mehr Propaganda für die rechte Gesinnung zu treiben.

@RPiList wollt ihr wirklich Helfer für sowas sein?

**Comment by Kleriger** [comment]
Ich verstehe auch nicht warum man die Liste verwenden sollte. Die GEZ Seiten sind eine der wenigen deutschsprachigen Anlaufstellen, die zum einen gute Dokumentationen vorweisen (History, gegenwärtige Skandale [Arbeitsbedingungen in In.- und Ausland, Massentierhaltung, Tiertransporte, ...], ...) und zum anderen politisch bilden (was bei vielen Deutschen leider Mangelware ist).
Warum sollte man außerdem Nutzern etwas sperren, für das sie Steuern zahlen und es demnach selbst finanzieren? 
Wäre so als würde ich den Nutzern verbieten, die steuerlich finanzierten Straßen zu nutzen.
Ich bin auch der Meinung, dass diese Liste nur einer Personengruppe dient, Verschwörungstheorikern die etwas verkaufen wollen und den Menschen die der Demokratie, den Menschenrechten und der Gleichheit jedes einzelnen überdrüssig sind und lieber über Fake News (neues Wort für Gerüchte) versuchen, Angst zu schüren und damit andere Menschen von ihren Ansichten aus dem letzten Jahrtausend zu überzeugen.

Solche Medien zu sperren sehe ich als sehr riskant an für die Aufklärung in unserem Land. 

P.S. und off topic: früher war ich auch stinkig jeden Monat GEZ zu zahlen, aber seitdem ich im Radio DLF Kultur höre, immer mal Nachrichten schaue und die echt guten Dokus entdeckte, habe ich meinen Frieden damit geschlossen (wäre wohl mit so einer Liste nicht möglich gewesen ;) ).

**Comment by qyqsoft** [comment]
Kann jeder verwenden wie er will. Ist dir freigestellt die Liste zu verwenden oder nicht. Ist genau so wie mit den Springer Medien Liste oder der Samsung Liste oder der Straming Liste etc. Es handelt sich um Meinungsfreiheit und die Freiheit in seinem Netz das zu sperren was man nicht möchte. Hat weder was mit Fascho noch mit sonst was zu tun und wer in diese Richtung denkt sollte die Probleme bei sich suchen und sich fragen ob er oder sie auf dem Boden des Grundgesetzes steht.

**Comment by Stengah966** [comment]
Kern einer liberalen Demokratie sollte es doch sein, dass jeder selber entscheiden kann, ob er die Liste verwendet oder nicht. Das gilt auch, wenn die Mehrheit meint, sie sollte nicht verwendet werden. 
Offenbar sind sich zu wenig Menschen noch bewußt, was es heißt, in einem autoritären Staat zu leben, der lenkt, welche Meinung gut oder schlecht für einen ist.

**Comment by ArnaudFeld** [comment]
Wie frage von @Kleriger wurde nicht beantwortet...

Auch stelle ich meine ,etwas klarer, erneut:
Warum sollte man unabhängige (nicht abhängig von privaten Firmen und deren Geldern) Medien sperren darunter auch Kindersendungen?

Ich bekämpfe Anti-demokratische Kräfte aktiv und passiv seit Jahren. Und Sperrung der öffentlich rechtlichen wurde bisher nur gefordert von Leute aus dem rechten Spektrum oder Leuten die Verschwörungstheorien Sehr sehr nahe stehen.

Daher bitte ich im Sinne des gesunden Menschenverstandes diese Liste NICHT aufzunehmen.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die rege Teilnahme an der Diskussion.

Natürlich kann jeder die Listen in sein Pihole importieren, die er will. Jeder kann auch eigene Listen erstellen und die anderen Nutzern, im Internet zur Verfügung stellen. Das wird auch kaum einer abstreiten wollen.

Aber der Vergleich von @qyqsoft bzgl.: "ist genau so wie mit [ ... ] der Samsung Liste oder der Straming Liste etc. " ist nicht korrekt. Denn die Samsung-Liste bzw. die Streaming-Liste blockiert keine "Inhalte", sondern soll nur das Tracking/Werbung verhindern.

ABER in Bezug auf die Springer-Blocklist hat @qyqsoft Recht, diese fällt nicht in das Schema Werbung, Tracking oder Malware.

Wie uns aber u.a. per eMail mitgeteilt wurde, ist das eigentliche Problem, dass die angebotenen Listen auf SemperVideo reflektieren. Sollen demnächst Listen folgen, die z.B. die ettablierten Parteien blocken? Oder alle Webseiten des Rechtsstaats, weil es Reichsbürger gibt, die das gebrauchen könnten? Oder alle Seiten die der Evolutionstheorie folgen, weil es Anhänger der Schöpfungsgeschichte gibt?

Die Antwort hier kann dann nur "Nein" lauten. Suchmaschinen bieten alle Seiten und verhalten sich neutral. Wir sind keine Suchmaschine und verhalten uns daher nicht neutral. Wir (bzw. SemperVideo) bekommen hier ein Problem, wenn Nutzer eine Liste sehen und dann meinen "Das ist die Meinung von SemperVideo?", obwohl die Liste NICHT unsere Meinung wiedergibt. Um das zu verhindern müssten wir uns dann von entsprechenden Listen distanzieren. Das ist aber langfristig auch keine Lösung.

Insoweit wird die GEZ-Blockliste von uns nicht geführt und auch nicht verlinkt. Zusätzlich ist die Springer-Blockliste auch aus der Blocklisten.md entfernt worden. Dies hatte ich ja schon ausgeführt. Ja, die Blödzeitung grenzt an Malware. Aber eine Jobbörse die der gleichen Muttergesellschaft gehört in Sippenhaftung zu nehmen ist nicht zielführend.

Es ist nachvollziehbar, dass nicht alle mit dieser Entscheidung zufrieden sein werden. Aber die hier nicht gelisteten Listen werden von der Zielgruppe auch weiterhin über die Standard-Suchmaschine gefunden werden.

Viele Grüße.

**Comment by qyqsoft** [comment]
Nur um mal klar zu stellen. Diejenigen, die meinen ich hätte was mit rechts oder Verschwörung zu tun oder sonstigem geistigen Dünnpfiff. Alles falsch. Bin weder links noch rechts noch oben oder unten, sondern bin für eine komplett freie Gesellschaft ohne politische Einflüsse. Der Parteien-Demokratie wie sie bei uns existiert inklusive dem Zwangsgebühren finanziertem Staatsfernsehen kann ich nichts abgewinnen. Deswegen habe ich die Liste erstellt um meine Familie und mich davor zu schützen. Wer die Liste verwenden will, gut. Wen nicht auch fein. Aber den Quatsch hinter allem freiheitlichen eine rechte Verschwörungstheorie zu wittern ist zwar dem Zeitgeist entsprechend, aber natürlich bei nüchterner Betrachtungsweise totaler Blödsinn.

**Comment by Ian-Drunkenson** [comment]
@RPiList Ja, is klar, Springer und Gez löschen, aber auf eurer Jungendschutzliste ist die Domain jungefreiheit.de, eine ganz normale Wochenzeitung. Wer weiss was ihr da sonst noch für normale Medien gesperrt habt einfach nur in einer anderen Liste versteckt. Die Aussagen passen vorne und hinten nicht zusammen.

**Comment by RPiList** [comment]
Wie schon gesagt, man kann es nicht allen Recht machen. Wenn aber jetzt hier absichtlich alles durcheinander geworfen wird, ist das ebenso nicht zielführend.

> @RPiList Ja, is klar, Springer und Gez löschen, aber auf eurer Jungendschutzliste ist die Domain jungefreiheit.de, eine ganz normale Wochenzeitung. Wer weiss was ihr da sonst noch für normale 

![Unbenannt](https://user-images.githubusercontent.com/56664851/77861252-15455880-7214-11ea-8ebc-d125d0ae097e.PNG)

Ja, für den Einen ist es eine ganz normale Wochenzeitung, für den Anderen ist die Zeitung im Grenzbereich zum Rechtsextremismus.

Da der Eintrag aber Jugendschutzliste steht, kann das jeder Vater/Mutter selber entscheiden, ob er/sie seinen/ihren Kindern den Zugang dazu sperren will.

> Medien gesperrt habt einfach nur in einer anderen Liste versteckt. Die Aussagen passen vorne und hinten nicht zusammen.

Hätten Sie also auch nur ansatzweise Recht mit Ihrer Anspielung, hätten wir die URL in der Adblocker oder FakeShop Liste "versteckt". Insoweit dürfte Ihnen selbst klar gewesen sein, dass Ihre Behauptung unrichtig ist. Aber ich glaube darauf kam es Ihnen dann gar nicht mehr an.

**Comment by Ian-Drunkenson** [comment]
Jo, wer an das glaubt was Wikipedia im politischen Bereicht so schreibt ist auch selber Schudl. Inzwischen wurde glaube ich sogar von einem gericht gesagt, dass die Autoren da alle aus dem linksextremen Lager stammen. Aber egal. Haben eigentlich nix anderes erwartet.

**Comment by ArnaudFeld** [comment]
@Ian-Drunkenson nur auf Wikipedia soll man sich nicht verlassen.
Wenn mal ein paar Minuten sucht findet man schnell u.a.  das in WirtschaftsWoche ein Bericht zur Gesichte der Jungen-Freiheit.

![813AFC7F-28E2-491C-B213-43EA1AC8A458](https://user-images.githubusercontent.com/1561416/77889470-2d49c600-726e-11ea-9f4a-3e1516d6408a.jpeg)

Daher ist die Einordnung von @RPiList mit dem Wiki-Artikel korrekt.

@qyqsoft schau mal in andere Länder die keine von privaten Geldern unabhängige Berichtserstattung haben. Sowas willst du in Deutschland nicht. 
Klar könnte man hier und da was an dem System der Erhebung anpassen ABER wir brauchen unabhängige Berichtserstattung.

Als der Anschlag in Hanau war hat ein Nachrichtensender der zu einer privaten Sendergruppe gehört, versucht dem Augenzeugen aus dem Dönerladen etwas in den Mund zu legen um das ganze in eine bestimmte Richtung eines großen Aufreißers zu bewegen. Der Typ reagierte gut und fiel nicht auf diese Dame rein.
