### ISSUE TITLE
Domaisn

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1173]
Moin Chat und Sprecher, Hier alle Domians die ich von Montag bis Heute gesammelt habe
Allee Domians wurden mit hilfe des Pi-Hole gegen gecheckt ob sie schon in listen sind
Fake Investment/Traiding
investmentpunk.com
digitalxresults.de
network-leads-training.de
ecomscaling.org
cashflow-agentur
deoscarkarem.com
mike-bergmann-akademie.de
vitori-kristallmatte.com
sebastian-fend.de
mariolueddemann.com
tobiaswessling.com
jacqueline-strecker.de
pjmueller.de
wearedevelopers.com
trend-kurier.com
erfolgmagazin.net
keetsch.com
boersenrevue.com
christinasternbauer.com
cashflow-agentur.de
adstronauts.de
jil-langwost.de
kontaktfluss.de
antonwieprecht.com
drdanielasussmann.de
noack-statistik.com
starmeldung.com
pramer.com
vipkolumne.com
vipnachrichten.com
lead-table.com
bioderma-recruitment.com

Sex/Porno Emails
tacticalknight.org
eatguardian.com
fastleanfit.net
thefitnesshammer.com
fitnesscrux.com
theselfsurvival.com
welnesstrainer.com
iwkoeln.de
sklavin-sylvia.online
sklavin-sylvia.de

Fake AppStore
playmarketgameo.shop

Fake Glücklspielwerbung
gamezonewow.online

Unsicher ob Fake oder Echt
in-and-out-consulting.com
impactofwords.com
factorialhr.de factorial.co #Ist die selbe Firma laut Facebook Seite
stefangrove.de
xd-i.com,
extra-report.com
blickmagazin.com
limak.at

**Comment by RPiList** [comment]
Vielen Dank für die Infos. Domains wurden hinzugefügt. Viele Grüße

**Comment by sir106** [comment]
wearedevelopers.com gehört nicht zu Fake Investment/Trading. We Are Developers in Berlin: world's leading developer community.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
