### ISSUE TITLE
My Subdomain is wrongfully get blacklisted.

### ISSUE THREAD

**Issue by GaryKamHK** [RPiList/specials#1180]
Hello,

My Subdomain somehow wrongfully get blacklisted. The subdomain chatgpt.kamserver.com is a test environment that solely for internal use of testing ChatGPT plugin. 

Please fix this issue accordingly.

Best Regards,
Gary Kam

**Comment by RPiList** [comment]
Hi, we have a lot of scamers faking chatgpt. So when its only for your internal testing... you shouldn't experience any problems of our blocking, right?

**Comment by GaryKamHK** [comment]
Hello, it's totally unexpected having a subdomain with Chatgpt wording would get into trouble of getting blacklist. 
Provided that such subdomain was never disclosed to public and it also had no backlinks at all since it's for internal use only.

Please remove my subdomain from the list because Bitdefender flags the whole domain (including main domain) as malware after you added my subdomain into your blacklist. I already change my test environment to another subdomain is avoid further issue.

Best Regards,
Gary Kam

**Comment by GaryKamHK** [comment]
Greeting,

Since my subdomain was never disclosed to public. 
I would imagine that you discovered my subdomain by doing DNS lookup against all the domains listed in Zone file. By doing this, you would easily blocking all the ChatGPT related subdomain but you would also blocking some legitimate users just liked me.

I hope you would fix this issue as soon as possible,

Best Regards,
Gary Kam

**Comment by RPiList** [comment]
> Hello, it's totally unexpected having a subdomain with Chatgpt wording would get into trouble of getting blacklist. Provided 

There is a huge scam wave on the internet reguarding chatgpt. Lots of scamers offer phishing sites to grab user-account credentials.

> Please remove my subdomain from the list because Bitdefender flags the whole domain (including main domain) as malware after you added my subdomain into your blacklist. I already change my test environment to another subdomain is avoid further issue.

What I still don't quite get. If your domain is just being used by you, and it's for internal testing... how are you affected by a blocklist (that you are not using).

Don't get me wrong. If your site is legit, we will unblock it.

But we catch our sites when they are not even set up. So its hard to determined.

> 
> Best Regards, Gary Kam

**Comment by RPiList** [comment]
> Since my subdomain was never disclosed to public. I would imagine that you discovered my subdomain by doing DNS lookup 

No. We catch domains, when they apply for a SSL-Certificate. There are internet phenomenon like Corona or ChatGPT and bang... thousands of Domains get registered to profit from the boom. Offering medicine or other solutions, which were all scam of course.

> I hope you would fix this issue as soon as possible,

Easiest fix would be not using a sub-domain having chatgpt or openai in it. That's just the trigger for it.
You mentioned Bitdefender, which is certainly not blocking your domain because of us. They just "judge" a domain the same way as we do.

> 
> Best Regards, Gary Kam

**Comment by GaryKamHK** [comment]
Hello,

You have to understand that some AntiVirus companies are indeed using your list as cross reference to block malware website.  

Due to above reason, after you classified my internal testing subdomain as malware and added it into your list, at least three AntiVirus engines including BitDefender, G-Data, VIPRE immediately flags the whole domain as malware. If you checking Virustotal, you would see that my internal testing subdomain domain is first seen on  2023-7-25 by Virustotal and the time is matched with the time you added my subdomain into your malware list.


They trusted your malware list and they're not only blocking the subdomain you listed, they blocked the whole domain and also block my main domain as malware. My main domain is a personal website and it had nothing to do with malware at all. My computers had Bitdefender installed and I have a hard time to visit my own website. 


Best Regards,
Gary Kam

**Comment by RPiList** [comment]
Hi,
your domain has been removed. Hope that fixes your problems. Greetings
