### ISSUE TITLE
Blocket domain

### ISSUE THREAD

**Issue by T3cWhy** [RPiList/specials#1181]
Hi, the fallowing site is used in my country for open air cinemas to look up play time of movies: www.open-air-kino.ch
Virus Total doesn't find this site in it's list.

**Comment by T3cWhy** [comment]
Affected List: https://v.firebog.net/hosts/RPiList-Malware.txt
https://www.virustotal.com/gui/domain/www.open-air-kino.ch
Screenshots as proof  
![grafik](https://github.com/RPiList/specials/assets/70317356/242a453d-2e4e-4d1e-9507-2266df216a23)

**Comment by RPiList** [comment]
Hi, thx for letting us know. Domain has been removed. Greetings.
