### ISSUE TITLE
Kinderschutz Waffenläden

### ISSUE THREAD

**Issue by stephan1827** [RPiList/specials#1183]
Hallo,
ich habe mal die Jugendschutzliste importiert und dann testweise nach waffen gesucht. Einer der ersten Treffer ist 

www.frankonia.de

aber die Seite wird nicht geblockt. Würde eine solche Seite nicht unter Jugenschutz fallen?

**Comment by RPiList** [comment]
Domain wurde hinzugefügt. Viele Grüße
