### ISSUE TITLE
list update broken

### ISSUE THREAD

**Issue by ruhannduplessis** [RPiList/specials#1185]
Hello

Appreciate the work you doing!!, Currently some of the lists are broken.
Why does some of the lists now have a double line at beginning of line "| |"? This is breaking autoupdate lists:
eg.:

Current:
||0-free-porn.com^
||0-hardcoresex.net^
||0-livechatlady.com^
||0-porno.com^

**Comment by RPiList** [comment]
These lists are not broken. It depends on the way you are using them.

The format you are refering to is called ABP-style format. The double pipe  in front and cirkumflex at the end make sure that pihole (and others) block all subdomains as well.

So not only 0-porno.com is blocked, fr.0-porno.com, or de.0-porno.com are all blocked as well. That makes it easier to catch all subdomains.
So if you are using pihole or adguard-home you can just keep using them.

If not... you might want to check your software if it understands the ABP-style syntax.

Greetings
