### ISSUE TITLE
false-positive www.redditmedia.com in easylist

### ISSUE THREAD

**Issue by User123698745** [RPiList/specials#1187]
In https://github.com/RPiList/specials/blob/master/Blocklisten/easylist ist ein false-positive.
www.redditmedia.com wird von www.reddit.com genutzt um u.a. Twitter Posts darstellen zu können.

`www.redditmedia.com` und `redditmedia.com` müssen wieder aus easylist raus.
Es gibt auch noch `events.redditmedia.com`, aber die domain wird korrekt geblocked und muss drin bleiben.

Aktuell sieht Reddit deshalb so aus:
![image](https://github.com/RPiList/specials/assets/1911682/b26a018b-b297-4296-b8fa-73a0be6bdd62)

**Comment by RPiList** [comment]
vielen Dank. Domain wurde entfernt.
