### ISSUE TITLE
False Positive HOA website

### ISSUE THREAD

**Issue by kb-elmo** [RPiList/specials#1188]
Apparently the hackenopenair.de website and all it's subdomains somehow ended up on the malware blacklist despite not containing any malicious content.

It's the official info website for the Hacken Open Air festival-camp which is an event for IT-sec people, makers and hackers organized by the german makerspace organization Stratum-0.

Despite it's name the website has absolutely nothing to do with any malicious hacking activities.

**Comment by RPiList** [comment]
Catched because of OpenAI scam. Fixed now.
