### ISSUE TITLE
canva.com false positive

### ISSUE THREAD

**Issue by MaDill** [RPiList/specials#1190]
In "Phishing-Angriffe" is canva.com listet. This is for painting.

**Comment by RPiList** [comment]
Reported for phishing by https://github.com/mitchellkrogza/Phishing.Database
So it has to stay on the list. Greetings.

**Comment by dasdiesernoah** [comment]
same problem. Also had some other false prositive with RPIlists i'm gonna delete them lists from my pihole It's just annoying
