### ISSUE TITLE
False positive: openair-karlsruhe.de

### ISSUE THREAD

**Issue by thomasmerz** [RPiList/specials#1193]
This is **not** malware, so I will leave a PR to remove this site from malware list again.

<img width="627" alt="image" src="https://github.com/RPiList/specials/assets/18568381/14632f08-5af3-40f6-b214-b50a312f2fe7">

**Comment by RPiList** [comment]
catched because of openai. Will be fixed immediately

**Comment by thomasmerz** [comment]
Maybe there are **some more false-positives around openair-karlsruhe with different TLD**. I was only triggered by my wife who was "not amused" when she couldn't have a look on this site 🤷🏼‍♂️
