### ISSUE TITLE
www.vodafone.de in Phising false positive

### ISSUE THREAD

**Issue by games647** [RPiList/specials#1195]
Der Eintrag landete in der Phising-Liste obwohl dieser auf der Whitelist steht:

https://github.com/RPiList/specials/blob/6aebde78499eb2beb63549012d61c32437c50f2f/dev/whitelist#L4286

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Eine Phishing-Quelle betrachtet den Link wohl als Phishing für vodafone.co.uk. Muss aber auch mal schauen, warum das nicht durch die Whitelist gefiltert wird.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
