### ISSUE TITLE
Wieder ein paar Domians die ich eine Woche lang gesammelt habe

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1196]
Fake Investment/Traiding
gemini-inwest.info #macht werbung mit elon musk
gedacht-getan-trading.com
perspective.co
digitalxresults.de
wiserthinking.com
ecommerce-workshop.at
berend-heins.de
finanzenverstehen.at
berlinerinsider.com
boersenratgeber.net
feusto.com
trustvideo.de
geldhelden.org
a-mk.com
avanskredi.com #leider werden hier viele fakeangebote in Unterverzeichnisen abgelegt, wie das hier z.b. https://www.avanskredi.com/spkprivat/
loansline24.com
serveeveryone.xyz
loan-company1.shop
pensionloan1.space

Sex/Porno/Gewinnspiel Emails
ngtuit.top
wl.co
ikawson.uk
lookattme.com
gooddaten.com
jbdates.com
hwaboutwe.com
elitesinglles.com
xreate3d.com
datingmot.com
usodates.com
jaiilz.com
markove.online
bulddozerz.online
fisherhann.shop
brooksli.co.uk
hailtoangel.com

Fake AppStore
#Heute habe ich leider keine Domians für dich

Fake Glücklspielwerbung
bitgovfondusm.cfd

Unsicher ob Fake oder Echt
master-of-search.de
getsurance.at
workers.dev #wird scheinbar von mehrer seiten genutzt da das Pihole über 100 Treffer ausgibt

**Comment by RPiList** [comment]
Vielen Dank, Domains wurden hinzugefügt. Viele Grüße
