### ISSUE TITLE
false positive - (www.)magentacloud.de in Phishing-Angriffe

### ISSUE THREAD

**Issue by OlafGH** [RPiList/specials#1197]
magentacloud.de und www.magentacloud.de werden neuerdings geblockt. Magentacloud ist die Cloud der Deutschen Telekom und IMHO eindeutig seriös.

**Comment by RPiList** [comment]
Phishing hat nichts mit Seriösität zu tun. Eine Seite kann gehackt sein und Schadware verteilen. Passiert den Besten.

Werde mal prüfen, ob die magentacloud die Kundencloud der Telekom-Kunden ist. Dann machen die den Blödsinn.

**Comment by OlafGH** [comment]
Danke für die Antwort. Die Magentacloud IST die Kundencloud der Telekom. Ich nutze sie selber als Telekom-Kunde. Es gibt allerdings auch ein (eingeschränktes) Angebot für Nichtkunden.

**Comment by RPiList** [comment]
Domain wurde entfernt. Vielen Dank für den Hinweis. Viele Grüße
