### ISSUE TITLE
Potential False Positive: d3ag4hukkh62yn.cloudfront.net (Amazon US)

### ISSUE THREAD

**Issue by firoze** [RPiList/specials#1199]
Not sure if this is a recent change or not, but it appears Amazon is entirely hosted out of `d3ag4hukkh62yn.cloudfront.net`. Therefore, when using the list from ``https://v.firebog.net/hosts/RPiList-Phishing.txt``, the browser no longer opens `www.amazon.com`. Temporarily whitelisting `d3ag4hukkh62yn.cloudfront.net`.

<pre>
nslookup www.amazon.com 9.9.9.9
Server:		9.9.9.9
Address:	9.9.9.9#53

Non-authoritative answer:
www.amazon.com	canonical name = tp.47cf2c8c9-frontier.amazon.com.
tp.47cf2c8c9-frontier.amazon.com	canonical name = d3ag4hukkh62yn.cloudfront.net.
Name:	d3ag4hukkh62yn.cloudfront.net
Address: 108.138.248.64
Name:	d3ag4hukkh62yn.cloudfront.net
Address: 2600:9000:234c:b400:7:49a5:5fd2:8621
Name:	d3ag4hukkh62yn.cloudfront.net
Address: 2600:9000:234c:f000:7:49a5:5fd2:8621
Name:	d3ag4hukkh62yn.cloudfront.net
</pre>

**Comment by RPiList** [comment]
Thx for helping us. Domain has been removed from our list. Greetings
