### ISSUE TITLE
homebank.ro

### ISSUE THREAD

**Issue by CzC-RO** [RPiList/specials#1206]
www.homebank.ro was recently added to the list. It is the legitimate e-banking site of ING Romania which can be accessed via https://ing.ro/persoane-fizice ( Orange Home Bank button top right)

Thank you for this and thank you for your work with the list.

**Comment by RPiList** [comment]
Hi,

thx for supporting us. 

Homebank.ro is currently not on our lists. But we had an earlier request about this domain two days ago.

Please update your lists and it should work alright.

Greetings
