### ISSUE TITLE
amazon.com blocked false positive

### ISSUE THREAD

**Issue by TheShawnMiranda** [RPiList/specials#1208]
amazon.com is currently being blocked by the file

https://github.com/RPiList/specials/blob/master/Blocklisten/Phishing-Angriffe

It can be fixed by removing the domain d3ag4hukkh62yn.cloudfront.net from the list

**Comment by TheShawnMiranda** [comment]
<img width="1017" alt="Screenshot 2023-08-04 at 11 38 16 PM" src="https://github.com/RPiList/specials/assets/36976097/8bc9c725-a0e1-4eca-b2b6-d697272b25d8">

**Comment by RPiList** [comment]
Thx for supporting us. Domain has been removed. Greetings
