### ISSUE TITLE
Overblocking of website 'www.freiewelt.net' and 'freiewelt.net' for political reasons only

### ISSUE THREAD

**Issue by tobrunn** [RPiList/specials#1216]
'www.freiewelt.net' 
and
'freiewelt.net'

are blocked also they are no threat in the sense of "Fakeshops, Werbung, Tracking und anderen Angriffen aus dem Internet" in any way. 
This webside is just a blog respectively online newspaper of the political right wing AfD politicans 'von Storch'.
The only 'attac' is that this side offers another point of view on politics which is clearly outside the minimal left opinion corridor.
I don't think the authors of this blocklists are supposed to politically educate their users nor to protect them from other opinions  that differ from their own. This is a clear political misuse of the blocklist and censorship and the domains should be removed from it.

**Comment by RPiList** [comment]
Hi,
our blocklists are an offer to parents who might wanna use them. It's entirely on them to decide. So I suggest we let parents decide. If you are against that, take it up to them.

Greetings.
