### ISSUE TITLE
firebog.net phishing blocklist False Positive https://www-la-villetta-info.filesusr.com

### ISSUE THREAD

**Issue by itcab** [RPiList/specials#1217]
firebog.net phishing blocklist false positve
https://www-la-villetta-info.filesusr.com 

Restaurant Menu from: https://www.la-villetta.info/

**Comment by RPiList** [comment]
Both domains you mentioned are not listed on our blocklists. Maybe you are using an old version, where is was blocked.
Please try updating your list. Greetings
