### ISSUE TITLE
RPiList-Phishing blocks Backblaze S3 API s3.eu-central-003.backblazeb2.com

### ISSUE THREAD

**Issue by tdiekel** [RPiList/specials#1218]
RPiList-Phishing blocks Backblaze S3 API under adress `s3.eu-central-003.backblazeb2.com`.
The [Backblaze documentation](https://www.backblaze.com/apidocs/introduction-to-the-s3-compatible-api) defines the following schema for their API `s3.<region>.backblazeb2.com`.

**Comment by RPiList** [comment]
I could not find any domain on the Phishing list. But they were on the spam-mail list.
Removed them all. Greetings.
