### ISSUE TITLE
VPN CyberGhost geblockt

### ISSUE THREAD

**Issue by radze90** [RPiList/specials#1219]
Hallo,

gibt es einen triftigen Grund, warum der VPN Anbieter "CyberGhost" in der "proxies Blockliste" geblockt ist?

Gruß

**Comment by RPiList** [comment]
Hi,
ob es einen wichtigen Grund zur Sperrung gibt, häng davon ab, in welcher Liste die Sperrung vorliegt. Ohne die entsprechende Domain, kann ich aber leider auch nicht nachschauen. Viele Grüße

**Comment by radze90** [comment]
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/proxies

cyberghostvpn.com
www.cyberghostvpn.com

**Comment by RPiList** [comment]
Hi,

ja, hier ist der Eintrag richtig. In der Proxies Liste geht es darum Dienste zu sperren, mit denen man "umgehen" kann. Da fallen dann auch VPN-Dienste rein. Ist also richtig.

Viele Grüße
