### ISSUE TITLE
Spielwarenhandel in der Pornliste

### ISSUE THREAD

**Issue by Wackelblume** [RPiList/specials#122]
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock3:
   mytoys.de
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4:
   www.mytoys.de

Es handelt sich hierbei um einen Online Spielwarenversender :)

**Comment by RPiList** [comment]
die o.g. URLs wurden entfernt.

Vielen Dank für Ihre Mühen.

Viele Grüße.
