### ISSUE TITLE
Invalid domains in notserious und streaming

### ISSUE THREAD

**Issue by StephanBussmann** [RPiList/specials#1222]
Hi, 
ich habe grade mal im PiHole gestöbert und bin darüber gestolpert:

[i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  [✓] Status: Retrieval successful
  [i] Analyzed 66843 domains, 66843 domains invalid!
      Sample of invalid domains:
      - ||007drones.de^
      - ||009972.com^
      - ||01discount.com^
      - ||0ffcloud.com^
      - ||0k.ru^

[i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming
  [✓] Status: Retrieval successful
  [i] Analyzed 2469 domains, 2469 domains invalid!
      Sample of invalid domains:
      - ||007-os-diamantes-sao-eternos.olink.tv^
      - ||0123movie.net^
      - ||0123movies.10s.live^
      - ||0123moviesback.com^
      - ||1.kinogo.by^

Was mich wundert, laut der Meldung sollen alle Domains in den Listen nicht valide sein.
Das kann ich mir irgendwie nicht vorstellen.
Gab es ein Update vom PiHole, welches die Syntax geändert hat?

**Comment by RPiList** [comment]
Ja, das ist richtig. Im März 2023 gab es ein Update, dass das sog. ABP-Format unterstützt. Deswegen wurden vor ca. 7 Wochen viele Listen auf das neue Format umgestellt.
Also einfach Pihole aktualisieren, dann funktioniert wieder alles. Viele Grüße
