### ISSUE TITLE
failed to download svpihole images from sempervideo.de

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1224]
The [Download.md](https://github.com/RPiList/specials/blob/master/Download.md) contains the download links for the svPihole images for the RPi and as a VM.

Attempting to download this failed because the download links hosted by [sempervideo.de](http://sempervideo.de) are no longer accessible.
Instead, Firefox gives the error message `The server at sempervideo.de is taking too long to send an answer`

-----

I am aware that there are also "further download options" but I wanted to mention it anyway.

**Comment by RPiList** [comment]
> 
> I am aware that there are also "further download options" but I wanted to mention it anyway.

It will be fixed soon and stay open until fixed. :-)

**Comment by RPiList** [comment]
Links are working again. Thx for pointing it out. Greetings.
