### ISSUE TITLE
Jotform

### ISSUE THREAD

**Issue by dylan-cobscook** [RPiList/specials#1226]
Jotform is a legitimate form site that's been blocked:
jotform.com
cdn.jotfor.ms

maybe others, still working to fully unblock it this morning.

**Comment by RPiList** [comment]
Hi,

thx for supporting us. Bot Domains you mentioned are not blocked by our lists. You might be using an old version. Please just update your lists.

If updating doesn't fix your problem, you might be using a third-party list or an old copy of our lists. Greetings.
