### ISSUE TITLE
Domians

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1227]
Moin, Sorry das zwei Wochen nichts gekommen ist, Ich befand mich im Urlaub auf Ibiza.

Fake Investment/Traiding
verdienendeingeld.de
awk-management.at
quentn.com
florianwawrosch.com
ulrichmueller.de
smsloan2.world

Sex/Porno/Gewinnspiel Emails
shopinggear.com
matildahtekeshe.co.uk

Fake AppStore

Fake Glücklspielwerbung

Unsicher ob Fake oder Echt

**Comment by RPiList** [comment]
Alle Domains wurden hinzugefügt. Viele Grüße
