### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by nicolajlerch** [RPiList/specials#1232]
Hallo zusammen,

Ich habe eine kurze Frage. Wieso ist die Domain "kleinanzeigen.de" in der notserious Blockliste eingetragen. 

Hierdurch verliert die App/Website ihre Funktionalität (API, Gateway, etc.).

Diese Domain ist meines Wissens nach der Nachfolger von "ebay-kleinanzeigen.de"

Könnt ihr bitte die Richtigkeit überprüft.

Vielen Dank

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Ihr Pihole wird das Update automatisch in ca. 5 Std. laden. Viele Grüße
