### ISSUE TITLE
false positive: anime2you.de

### ISSUE THREAD

**Issue by liadala** [RPiList/specials#1233]
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming:
  ||anime2you.de^

News Page

Anime2You versorgt dich jeden Tag mit den wichtigsten Anime- und Manga-News aus Deutschland und Japan. Immer aktuell, schnell und auf Deutsch!

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
