### ISSUE TITLE
Pi-Hole reports invalid entries

### ISSUE THREAD

**Issue by JustTotallyMe** [RPiList/specials#1235]
Hi,

for all of those block-lists, Pi-hole tells me, that the entries are wrong.

For example the pornblock4 give me the following output when running gravity-update:

[i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4
  [✓] Status: Retrieval successful
  [i] Analyzed 172343 domains, 172343 domains invalid!
      Sample of invalid domains:
      - ||xpornforall18.blogspot.pe^
      - ||xpornforall18.blogspot.pt^
      - ||xpornforall18.blogspot.qa^
      - ||xpornforall18.blogspot.ro^
      - ||xpornforall18.blogspot.rs^
  [i] List stayed unchanged
  
  I tried to clean up the list and it seams, that Pi-hole has an issue with the || and the ^ char at the beginning and end of the entries.
  Does anyone else have this problem or is it just me?
  
  Kind regards,
  Andy

**Comment by RPiList** [comment]
The domains you mentioned are formatted in the new ABP-format.

Pihole understands this new format since March 2023. This means you are running an older pihole version. Please update your pihole and these lists will automatically start working again.

You can update your pihole by dropping to the console or terminal and type in pihole -u. 

Greetings

**Comment by JustTotallyMe** [comment]
> The domains you mentioned are formatted in the new ABP-format.
> 
> Pihole understands this new format since March 2023. This means you are running an older pihole version. Please update your pihole and these lists will automatically start working again.
> 
> You can update your pihole by dropping to the console or terminal and type in pihole -u.
> 
> Greetings

omg, I just checked and I had a version from 2022 :D
I am sorry for wasting your time and also thx for the info :)
