### ISSUE TITLE
Einige - cloud-object-storage.appdomain.cloud - Domains

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1240]
ahjif4733s3t0verdr39wgusvne71v.s3.syd.ap.cloud-object-storage.appdomain.cloud
uf8t2b5xcs5unph5uze0ie4eoo6pa1.s3.mil.eu.cloud-object-storage.appdomain.cloud
0yc23773j8snsod18wyzku3c6r0m25.s3.fra.eu.cloud-object-storage.appdomain.cloud
twrl6avrscww6g4xs8d7o782qrnicd.s3.mil.eu.cloud-object-storage.appdomain.cloud
gjpcrqhtr657kt12pv0sgafhlah286.s3.fra.eu.cloud-object-storage.appdomain.cloud
9lvbpc5hvv5uzfyd3mko3dfpgby2di.s3.fra.eu.cloud-object-storage.appdomain.cloud
tykkcklbgv0gchk4y3h8oouk4bvcnk.s3.osa.ap.cloud-object-storage.appdomain.cloud
onvnvw1nc39twjc2nlaa7fvkd8ky23.s3.fra.eu.cloud-object-storage.appdomain.cloud

Die Domain kommt aus einer E-Mail Spam Welle.

Die Webseite der Domain betreibt Phishing oder ähnliches.
Ziel sind wohl alles mögliche.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
