### ISSUE TITLE
Einige weitere Domains

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1241]
-----
api.adrtx.net
cl.s50.exct.net
click.yourmeliahotel.com
degoutewllah.dontexist.net
ea.pstmrk.it
edacihh.r.bh.d.sendibt3.com
email.reports.tidioreply.com
fgiaggi.r.af.d.sendibt2.com
fgiaggi.r.bh.d.sendibt3.com
harchasab3a.homelinux.net
logi242.xiti.com
mailing-api1.sms-timing.com
nadimadizazlouz.gotdns.com
postoffice.sms-timing.com
r20.rs6.net
smstim.in
thethreeishere.thruhere.net
u18081512.ct.sendgrid.net
u5629107.ct.sendgrid.net
visitor.constantcontact.com
yugiyhoolol.dontexist.org

-----

1gbps5y9tsjj1pni9gyyc3n7fz15e0.s3.ams.eu.cloud-object-storage.appdomain.cloud
2g60fvzouvkp40rkj562muc3gxhyve.s3.mil.eu.cloud-object-storage.appdomain.cloud
7u2iibgaa1x8rqki5t13ra5ofnfyqc.s3.ams.eu.cloud-object-storage.appdomain.cloud
htrtx2ctytg11qqunobxgow4y6u0cj.s3.fra.eu.cloud-object-storage.appdomain.cloud
ispoacozhctdznqnfkslnwfrkdcrue.s3.us-south.cloud-object-storage.appdomain.cloud
jglfua70yxa9va62hg1sij184u99hv.s3.fra.eu.cloud-object-storage.appdomain.cloud
mvbifn3i20kftwjolxnxemq79r9hl2.s3.us.cloud-object-storage.appdomain.cloud
opi28mqnr1e1p3d4w5pk4hh2p8m630.s3.fra.eu.cloud-object-storage.appdomain.cloud
qgsukbosvaprfyrhpliargmynbddaw.s3.us-south.cloud-object-storage.appdomain.cloud
rs6dadmhp6ehxii02e8w5s2mblwjmp.s3.eu.cloud-object-storage.appdomain.cloud
tncdifwvpwfehovxfsfkqwaabccdmp.s3.us-south.cloud-object-storage.appdomain.cloud
ur3p5ov40ajpo287v5br5mqptx2bax.s3.fra.eu.cloud-object-storage.appdomain.cloud
uzmd3n71ao7vsc4vlqh4hahdzoo28a.s3.eu.cloud-object-storage.appdomain.cloud
xip58ewgqahrsiyhq3p669hb2hw9z1.s3.ams.eu.cloud-object-storage.appdomain.cloud
yighmkrudxtgrvjxwqluhwoaxohzma.s3.eu-de.cloud-object-storage.appdomain.cloud
zr9tmjcsy5odiwlahirzaf278iqnhm.s3.mil.eu.cloud-object-storage.appdomain.cloud

-----

-----

Die Domains kommen (vermutlich) aus mehren E-Mail Spam Wellen.

Es könnten Domains dabei sein die Phishing betreiben, manche oder vereinzelte Domains könnten aber auch Gute Domains sein (konnte ich nicht genau Prüfen).
Ziel des Phishers sind wohl alles mögliche.

**Comment by RPiList** [comment]
Vielen Dank für die Info, Domains wurden hinzugefügt. Viele Grüße
