### ISSUE TITLE
Wieder eine Lieferung

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1242]
Fake Investment/Traiding
copecart.com
smarttradinggains.at
bernsteinberatung.info
finally-freelancing.de
business-days.de
adsking.de
funnelcockpit.com
stefaniescheel.de
weberandco.cc
floriansondershausen.de
adsking.de
discountinfo.life
funnelcockpit.com
reviewstream.de
detradefx.com
immo-masterclass.de
dieterkiwus.de
familyservice.space
erfolgsthemen.com
jessica-schneider.de
highenergysecrets.net
thorstenkreutz.com
volume-trader.com
funnel-king.de
wa.me
verborgene-frequenz.de

Sex/Porno/Gewinnspiel Emails
shopinggear.com
setecnorte.com
strict-mistress.co.uk
rain-post.com
comstockhoa.net
kucherakane.com
maramuresazi.ro
klclick3.com
bulddozerz.online
stabrino.info
amo-azojp.com/
usodates.com
amoursins.com

Fake AppStore
fordomino.com

Fake Glücklspielwerbung

Unsicher ob Fake oder Echt

**Comment by RPiList** [comment]
Vielen Dank für die Infos. Domains wurden hinzugefügt. Viele Grüße
