### ISSUE TITLE
fediverse.jetzt freischalten

### ISSUE THREAD

**Issue by Tealk** [RPiList/specials#1243]
Hallo,

die Domain fediverse.jetzt steht auf der Liste der [spam.mails](https://github.com/RPiList/specials/blob/master/Blocklisten/spam.mails) ist aber eine seriöse Seite (WIP) die Informationen über das Fediverse und die Vereinsgründung anbietet.

Wäre es möglich diese von der Liste zu entfernen?

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße

**Comment by ccoenen** [comment]
Vielen Dank!
