### ISSUE TITLE
[False Positive] dlf-audiothek-appapi.deutschlandradio.de

### ISSUE THREAD

**Issue by D3rHase** [RPiList/specials#1244]
Die Domain wird von der [Dlf Audiothek](https://www.deutschlandfunk.de/apps-100.html) zum anzeigen und abspielen der Beiträge benötigt.
Gefunden in [spam.mails](https://github.com/RPiList/specials/blob/master/Blocklisten/spam.mails).

Vielen Dank!

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
