### ISSUE TITLE
ipfs.io is beeing blocked

### ISSUE THREAD

**Issue by oe3gwu** [RPiList/specials#1249]
ipfs.io - the host of the interplanetary filesystem is beeing blocked from you list. This is a valid site.

**Comment by oe3gwu** [comment]
Maybe subdomains are spam, that can be - like 

bafybeihsexyg5zxbdpg3lqcz7htkq6t3kafvlvqiwbsinnfurtyze6qs34.ipfs.infura-ipfs.io

But the root ipfs.io is valid.

**Comment by RPiList** [comment]
Hi,
thx for supporting the project. Domain has been removed. Greetings.
