### ISSUE TITLE
Lokal Auflösen

### ISSUE THREAD

**Issue by Coder246** [RPiList/specials#125]
Guten Abend,
Ich hätte eine Idee bezüglich der Configuration des PiHoles:
Für unerfahrene Nutzer wäre es eventuell besser verständlich wenn gesperrte Adressen
Lokal aufgelöst werden, um damit wiederum eine Fehlermeldung über den Webserver anzuzeigen (z. B. Diese Website wurde gesperrt...). Ansonsten könnten Nutzer denken sie hätten Internet Probleme oder Sonstiges.

Bin gespannt was ihr von dem Vorschlag haltet.

Grüße Tim 

P.S.: Hier ein Link: [https://docs.pi-hole.net/ftldns/blockingmode/#pi-holes-ip-ipv6-nodata-blocking](https://docs.pi-hole.net/ftldns/blockingmode/#pi-holes-ip-ipv6-nodata-blocking)

**Comment by RPiList** [comment]
Die Standardeinstellung (die auch derzeit von SVPi-hole genutzt wird) ist auf Geschwindigkeit ausgelegt. Lokale Auflösung verlangt einen HTTP-Server, was wiederum eine erhöhte Prozessorlast bedeuten würde. Ferner soll es Probleme mit https-Aufrufen geben, die im Grunde in einem Timeout enden.

Die erhöhte Last wäre für einen Raspberry Pi oder gar Pi Zero nicht so einfach zu verkraften. Hängt natürlich auch mit der Anzahl der Geräte zusammen, die im Netzwerk sind.

Auf der anderen Seite: Will man wirklich für jedes blockierte Werbebanner eine Website angezeigt bekommen?

Daher bleiben wir vorerst bei der von den Entwicklern empfohlenen Einstellung.

**Comment by Coder246** [comment]
Hallo
Ok von dieser Geschwindigkeits Einschränkung wusste ich bisher nichts.
Bei mir war es allerdings so das werbe Banner einfach ausgeblendet werden, nur wenn man die gesperrte Website direkt aufruft kommt die Warnung.

Einen schönen Tag noch!
