### ISSUE TITLE
Diskusion / sperr-requests für betrügerische Dating-Webseiten

### ISSUE THREAD

**Issue by christopherpross** [RPiList/specials#1254]
Hallo,

ich habe im letzten Twitch-Stream dieses Thema bereits angesprochen. Ich möchte hier noch einmal das Thema ausführlich erklären und auch Beispiele geben, um welche Webseiten es geht.
HINWEIS:
Das ganze ist recht lang geworden, sorry. Bringt entweder Zeit mit, oder lasst euch von ChatGPT das ganze zusammenfassen. 

### Um was geht es?

Es gibt bekanntlich Webseiten wo sich Nutzer anmelden können, um mehr oder weniger nette Menschen kennen zu lernen. Entweder zur Partnersuche oder etwas "lockeres". 
Manche sind kostenlos, manche sind kostenpflichtig. Manche sind recht hochpreisig, um diese soll es aber hier nicht gehen, zumindestens nicht direkt.
Es geht mir um Webseiten, die so genannte Moderatoren/Animatöre/CUsers einsetzen. Die benahmung ist hier recht unterschiedlich. Eines haben sie jedoch gemeinsam. Sie arbeiten für das Unternehmen, welches hinter der Platform steht oder werden von einem Drittunternehmen vermittelt.
Diese Mittarbeiter erstellen viele Fake-Profile und teilen sich diese auch mit vielen weiteren, so das rund um die Uhr, ein Moderator mit dem "Kunden" schreiben kann.
Ein treffen o.ä ist natürlich nicht möglich mit diesen Nutzern. Jede Webseite die solche Moderatoren einsetzen, benutzen eine virtuelle Währung, meist "Coints" genannt, mit dem sich der User dann das Recht erkauft mit einem Profil zu schreiben. Für jede Nachricht werden also diese Coints verlangt. Meist auch für das aufdecken von Bildern etc. Die Moderatoren haben die Aufgabe, dass der Nutzer immer mehr coints kauft, damit er mit der Person schreiben kann. Bei einigen Platformen bestreiten diese Moderatoren auch, dass sie fake sind. Auf das Thema ist auch bereits die [Verbraucherzentrale](https://www.verbraucherzentrale.de/wissen/digitale-welt/onlinedienste/onlinedating-achtung-fake-21848)  aufmerksam geworden. Auch würde ich empfehlen sich mal auf [dieser Webseite](https://dating-portal-advisor.de/) um zu schaun. Sie ist zwar etwas älter, arbeitet das Thema aber auch gut auf.

### Wieso sollten wir das blocken?

Ich sehe hier ein Betrügerisches Verhalten. Viele Webseiten benutzen übliche Psychotrix, um die Nutzer dazu zu bewegen sich zu registrieren, dass erste Geld auszugeben etc. Ebenfalls werden fake-Profile benutzt, um den Nutzer an die Webseite zu binden. Meist sitzen die Firmen in Dritt-Eu-Ländern (z.B. Schweitz), oder in nicht Eu-Ländern.
Die Daten, inkl. der persönlichen Daten die natürlich wärend eines Gesprächs von Moderatoren herausgefunden werden, werden natürlich weiter verkauft. Manche Platformen erwähnen, dass sie Moderatoren einsetzen, manche aber auch nicht. In jedenfall bin ich dafür sollche Seiten zu sperren. Ich selbst bin vor einigen Jahren auf solch eine Webseite reingefallen und habe viel Geld verbrand.  Deshalb ist es mir wichtig, andere Menschen davor zu schützen.
Ich widerhole mich noch einmal, es geht mir nicht darum alle dating-webseiten zu sperren, dass wäre nur evtl. für den Kinderschutz relevant. Mir geht es hier ausschließlich um diese betrügerischen Platformen.

### Ok, wie finden wir diese Seiten?

Mit hilfe von ein paar Telegram-Gruppen, die von spammern gekarpert wurden, habe ich einige redirecter ausgemacht, die hauptsächlich auf solche Webseiten weiterleiten. Falls auch an solchen Links interesse besteht, einfach bescheid sagen.
Mit hilfe der Agb's und ChatGPT, habe ich eine Google-Suchabfrage gebaut, die viele Seiten findet. Aber achtung, auch false positive enthält. Wenn man die Suche verfeinert bekommt man entweder nicht mehr alle, oder  man stößt an das limit von 32 Begriffen.
Im folgenden die Suchabfrage, eigentlich wollte ich noch eine Txt-Datei anhängen, mit beispiel-Webseiten und die Stellen aus der AGB, welches zeigt, dass sie Moderatoren einsetzen. Nun habe ich aber gemerkt, dass ich hier keine Dateien anhängen kann, deshalb poste ich das einfach auf Pastebin. [Hier ist der Pastebin.](https://pastebin.com/bdnXb41W) 

Suchabfrage:
`inurl:agb (Animateure OR CUser OR Controller OR "moderierte Dienste" OR Moderator) (dating OR matching OR profile OR chat)`

Diese Suchabfrage hilft natürlich nicht, bei Webseiten die nicht in ihren AGB's kommunizieren, dass sie solche Moderatoren einsätzen, oder ihre agb z.b. in englisch geschrieben haben.
Allgemein kann man solche Webseiten recht schnell erkennen, hier eine kleine Checkliste:

- Die Webseiten nutzen eine virtuelle Währung, um Nachrichten zu verschicken usw.
- Wenn man für 10 minuten online ist, auch ohne Bild und unausgefülltes Profil, bekommt man mindestens 5 Nachrichten
- Zufällig sind die Profile, die einem eine Nachricht geschickt haben, immer online wenn man selbst auch online ist.
- Wenn die Coints zu neige gehen, mit denen man Nachrichten schickt, kommt plötzlich eine Nachfrage nach einem Treffen, ein Foto oder sonst eine Nachricht die recht verlockend sein soll.
- Meist sitzen die Firmen nicht in der EU und wenn sie es tun, ist das meist nur eine Tochterfirma eines ausländischen Unternehmens.

### Vorschläge
- Wir könnten entweder für solche Webseiten eine eigene Liste machen, oder sie in notserious packen, beides denke ich würde passen.
- Wenn ihr die Suchabfrage benutzt, klickt kurz auf die Webseite und checkt ob es eine entsprechende Dating-Seite ist
- Vielleicht auch in die Liste für Kinderschutz?

Was denkt ihr zu diesem Thema?

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Issue. Im ersten Schritt erstellen wir eine eigene Liste für Dating-Sites (diese wurde schon angelegt). Solange das eine Stand-Alone Liste ist, können alle Dating-Sites drauf, egal ob "gut" oder "böse".

In den nächsten Schritten können wir dann festlegen, ob wir die "Guten" streichen und die Liste in die Fake-Shop Liste überführen oder ob Sie als einzelne Liste weiter fortgeführt wird.

**Comment by RPiList** [comment]
Keine weiteren Wortmeldungen, Liste ist in Entwicklung, dann mache ich hier mal zu. Viele Grüße
