### ISSUE TITLE
Scamseite Roblox

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#1257]
Guten Abend,

hier einmal ein Link zu einer Seite welche gutgläubige Kinder scammt, welche Robux in Roblox kostenlos bekommen möchten:
izzlintapptap.com
bigbucs.com
jimmyzsecret.fun

Wäre einmal etwas für die Blockliste denke ich

Liebe Grüße

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
