### ISSUE TITLE
Web Mail Client von Yahoo auf der phishing Liste.

### ISSUE THREAD

**Issue by AleksCee** [RPiList/specials#126]
mail.yahoo.com ist der webmailer von Yahoo, wieso ist der auf der Liste?

Liebe Grüße, Alex

**Comment by RPiList** [comment]
Der Eintrag ist auf der Liste, weil von dieser Domain ein Phishing-Angriff ausgeführt wurde.

Die Domain wurde ebenfalls unserer internen Whitelist hinzugefügt, so dass sie künftig direkt entfernt wird.

Vielen Dank für Ihre Mühen.

Viele Grüße
