### ISSUE TITLE
ichbinsjetzt.de

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1262]
Moin,

Die Seite gehört denn Streamer IchbinsJetzt auf Twitch, keinen Plan wie das in die spam.mails gekommen ist
https://www.twitch.tv/ichbinsjetzt

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Die Domain landete in der LIste aufgrund des "jetzt"-Scams.
