### ISSUE TITLE
Aktuelleres SVPihole Image (für Raspberry Pi)

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1264]
### Das Image ist gedacht für den:
- raspberrypi 3
- raspberrypi 4

Es ist genauso konfiguriert und beinahe auch so eingestellt wie das image von Dezember 2022
Es baut auf das Aktuelle RPiOS von April und alle Pakete wurden aktuallisiert.
Webmin (neuste Version) ist installiert, Portainer, Watchtower, Woogle und Pihole ist installiert und Pihole mit den nötigsten RPilist Blocklisten ausgestattet.
SSH und VNC ist auch aktiviert.

Link: [mega.nz](https://t1p.de/rplist-svpihole2309_001) (Sicherheitshalber über einen Link-Shortener)
@RPiList bitte die Datei, falls gewünscht, selbst hosten weil mein Link nicht dauerhaft existieren wird (zwecks Cloud Platzmangel, nur bis 01.11.2023)
Das Image ist Beta und damit nicht zu 100 Prozent komplett getestet und daher auch dieses Final Testing und nachfolgende Konfiguration (falls ich was vergessen habe oder falls was fehlt) auch selbst durchführen.

Die img selbst in der ZIP Datei ist mit XZ zusätzlich komprimiert und lässt sich so, ohne es aus der XZ zu entpacken auch mit den RPI Imager, Rufus, etc. (Die image.xz flaschen können) auf SD Cards flaschen (von RPi per USB mit den Image booten funktioniert leider nicht, war aber auch mit den Dezember 2022 Image so (liegt an die behandlung mit PiShrink)

### Prüfsummen:
CRC32: `91067ae1`
SHA256SUM: `4c6fe9ae0db6c9412fbb39dded0616b04d7b8d58b8f20fa44004beed0401dca1`
MD5SUM: `03c9b8c716b5cefc4772e7f0411034f5`

**Comment by RPiList** [comment]
Hi,

das Projekt SV-Pihole als VM wurde eigentlich eingestellt. Da die neuen Synology-Geräte Docker unterstützen ist ein Pihole in Docker wesentlich sinnvoller als in einer VM. Das ging nicht, als wir das Projekt vor 4 Jahren gestartet haben.

Aber inzw. ist das Video dazu online gegangen und es gibt keine Notwendigkeit für die VM.

Viele Grüße

**Comment by LizenzFass78851** [comment]
Das Image ist für den raspberrypi (3 / 4) gedacht.

**Comment by LizenzFass78851** [comment]
### Das Image ist für den raspberrypi (3 / 4) gedacht.

In der [Download.md](https://github.com/RPiList/specials/blob/master/Download.md#Raspberry-pi) wird für den raspberrypi auf ein svpihole images verwiesen.
Das synology mittlerweile Docker unterstützt, ist mir bereits bewusst.

Mir ging es darum das svpihole Image für den raspberrypi (was dem Stand von Dezember 2022 hat), ggf. auf einen aktualisieren Stand zu bringen. 

-----

Andernfalls besteht auch die Möglichkeit über einen raspberrypi, pihole über docker zu installieren. (je nach dem ob man auch für den raspberrypi den selben Ansatz (bezüglich pihole über docker) geben möchte, wie bei synology)

Dann könnte man das auch so machen wie bei synology, das man für den raspberrypi einen Video veröffentlicht mit der Installation von pihole über docker / docker-compose und diese Möglichkeit genauso wie für synology auf die Download.md verweisen und auch dahingehend das svpihole Image für den raspberrypi einstellen.
