### ISSUE TITLE
Spam Mail Domians

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1265]
correosprepago.es
transportexpress.cl
sheemaflourmill.com
helder-wop.com
builddozer.co.uk
fastshopily.xyz
joculator.city
goonavi.net
gary-automobiles.com
shoplineapp.com
taxidi.uk
megakons.com.ec

In viele E-Mails sind nur diese IPs hinter denn Bottens
77.91.100.144
144.172.64.113

**Comment by RPiList** [comment]
Vielen Dank für die Hilfe. Domains wurden alle der entsprechenden Liste hinzugefügt. Viele Grüße
