### ISSUE TITLE
Fehler in den neuen Blocklisten (upload heute vor 9h) 

### ISSUE THREAD

**Issue by retrogamer7ties** [RPiList/specials#1267]
am Ende jeder domain steht jetzt das Zeichen "^"
somit kann pihole diese nicht mehr verwenden.

Grüße

**Comment by RPiList** [comment]
Das ^ Zeichen am Ende ist der sog. ABP Style. Pihole versteht diese Domains seit dem März 2023 Update. Demnach wäre Ihre Installation veraltet. Bitte mal auf Update prüfen. Viele Grüße

**Comment by retrogamer7ties** [comment]
Danke!
Das war das Problem.
Hab‘ heute das PiHole mit dem Image SVPihole auf eurer Seite neu installiert. Und leider dauert es etwas bis PiHole unten anfängt das nötige Update anzuzeigen.

**Comment by LizenzFass78851** [comment]
Ref. #1264 
An. @RPiList

-----

Wäre das svpihole Image mindestens den Stand von März / April 2023 (oder neuer), dann wäre auch das neue pihole mit den ABP-style intrigiert (zusätzlich zu dem teils geänderten Pfaden zu bestimmten Listen (z. B. DomainSquatting)) und es würde zumindest mit einen neueren Image für svpihole (2023) ohne manuelles Update seitens der enduser out of the box mit den seit März 2023 existierenden Update von pihole funktionieren.

-----

Mir ist auch klar das es auch ggf. Nicht notwendig ist das svpihole zu aktualisieren da bestimmte Updates auch gemacht werden oder teils bis voll automatisch gemacht werden.
Dann müsste man evtl. das ggf. als disclaimer auf die Download.md hinterlegen damit man als enduser zumindest wenn es um das neue pihole und den ABP-style Listen, bescheid weiß denn es gibt auch enduser mit einen raspberrypi auch wenn diese (Stand: 13.09.2023) zumindest erschwinglicher sind als noch in ersten Halbjahr 2023.
