### ISSUE TITLE
Stackoverflow survey page not working

### ISSUE THREAD

**Issue by lightr4in** [RPiList/specials#1269]
In der `notserious` Blockliste ist folgender Eintrag falsch: `||stackoverflow.co^`

Grund: Die Ergebnisse der jährlichen StackOverflow Developer Surveys werden unter folgendem Link gehostet: https://survey.stackoverflow.co/2023/

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
