### ISSUE TITLE
Korrektur RegEx Anweisung

### ISSUE THREAD

**Issue by RPiList** [RPiList/specials#127]
Wie von einem Nutzer aufmerksam gemacht, beinhalten einige RegEx Anweisungen einen Fehler. 

Obwohl seit 1993 keine 1-stelligen Domains mehr zugelassen werden dürfen, ist es theoretisch möglich, dass der gewünschte Länder-Block mit einer 1-stelligen Domain unterlaufen wird.

Daher wurde der sog. Quantifier angepasst. Dieser würde jetzt auch einstellige Domains "fangen".

**Comment by Th3M3** [comment]
https://github.com/RPiList/specials/issues/100#issue-571685436
https://github.com/RPiList/specials/issues/75#issuecomment-581020669

**Comment by Deagol-03** [comment]
Die Einträge für die TLD's "(\.cn$|\.ru$|\.co$|\.vn$)" könnte man noch weiter vereinfachen:
\.(co|ru|cn|in|vn|io)$ bzw. \.(porn|sex|xxx|webcam|cam|tube|adult)$
