### ISSUE TITLE
Amazon Visa

### ISSUE THREAD

**Issue by Flashaholic88** [RPiList/specials#1271]
Hallo,

ich weiß nicht warum die Domain folgende Domain gesperrt ist aber man braucht sie um die Amazon Visa App von der LBB (Landesbank Berlin) zu benutzen.

Domain : amazon.lbb.de

**Comment by RPiList** [comment]
Hi,
die Domain war als Phishing/DomainSquatting Eintrag in der Liste für die Landesbank BadenWuerttemberg. 
Ist aber jetzt gefixt, Domain wurde entfernt. Viele Grüße
