### ISSUE TITLE
False Positive vrs.de

### ISSUE THREAD

**Issue by Chennec** [RPiList/specials#1273]
In der Volks- und Raiffeisenbank Blockliste (PLZ 7 Teil 1) ist der Eintrag ||vrs.de^ enthalten. Dieser sperrt die App und Webseite des Verkehrsverbunds Rhein-Sieg (VRS).

U.a. ekap-app.vrs.de

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist jetzt gefixt. Viele Grüße
