### ISSUE TITLE
False Positive: cdn-apple.com

### ISSUE THREAD

**Issue by AlexHuebi** [RPiList/specials#1277]
In der Corona-Blocklist ist der Eintrag "||cdn-apple.com^" 

cdn-apple.com wird bei Apple für u.a. Updates und AppleID verwendet. 
https://support.apple.com/en-us/HT210060

Diese Domäne wird auch für iCloud Drive Shares verwendet und vermutlich dadurch in die Liste eingebunden.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße

**Comment by florianjokeit** [comment]
Eintrag ist noch immer vorhanden

**Comment by RPiList** [comment]
Ja, weil er noch in einer zweiten Liste vertreten war. Hatten den aufgrund der Meldung nur aus der Corona Liste genommen.
Sollte sich jetzt auch in der Spam-Mail Liste erledigt haben.
