### ISSUE TITLE
False positive: NZXT App

### ISSUE THREAD

**Issue by Ollipop030** [RPiList/specials#1278]
Hi,

die Domäne nzxt-app.nzxt.com sollte nicht geblockt werden (in spam.mails). 
NZXT ist ein Hardware Hersteller, zur Überwachung und zur RGB Steuerung gibt es dazu eine App. Solange die Domäne geblockt ist, bekommt die App keine automatischen Updates mehr.

![grafik](https://github.com/RPiList/specials/assets/121013633/8fcc7482-6d32-46f1-8046-81196a875539)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt und auf die Whitelist gesetzt.
