### ISSUE TITLE
zvbwv.info

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1279]
Wieder eine Fake ÖBB Gewinnspiel

Ist wieder ein geackter Server scheinbar
https://zvbwv.info/inside/nachtzug-angebot-waechst-kraeftig/?utm_campaign=tNaASu1PyQ&utm_medium=AT+-+%C3%96BB&utm_content=%D0%9D%D0%BE%D0%B2%D0%B8%D0%B9+%D0%BD%D0%B0%D0%B1%D1%96%D1%80+%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B8+%D0%B7+%D1%86%D1%96%D0%BB%D0%BB%D1%8E+%C2%AB%D0%9B%D1%96%D0%B4%D0%B8%C2%BB&utm_term=2&fbclid=IwAR2nFQqlb0DQdJifBVvnbhbKZmiJKasKxlvA9RTVwWSUhqKJFVY2Jpv55oI

**Comment by RPiList** [comment]
vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
