### ISSUE TITLE
Scam oder echt?

### ISSUE THREAD

**Issue by RPiList** [RPiList/specials#1280]
![image](https://github.com/RPiList/specials/assets/56664851/a7c13c4d-a230-42fa-b3d5-5381ff1b9dbf)

Nutze keine Apple Geräte insoweit kann ich nicht feststellen, ob die Domains "echt" sind.

ms als TLD ist so eine "mini" Domain... Glaubt Ihr das ist ne Art von Phishing.... oder benutzt Apple wirklich diese Domains?

**Comment by SGirl-Zockt** [comment]
Moin,

Ich habe 2 Apple geräte und keines dazu telefnoiert laut Pi-Hole einer dieser Domains an, Ich finde es auch komisch das diese MS TLd in britischen Überseegebietes [Montserrat](https://de.wikipedia.org/wiki/Montserrat) gehört und warum sollte Appel diese Domians nutzen?
Desweiteren lassen sich viele dieser Domains nicht mal anpingen...
Ich bin für sperren

**Comment by Vickyistda2003w** [comment]
Hey Sprecher und Chat,

Die sehen für mich auch sehr fake aus. finde auch in meinen Pi keinen dieser Domians.

LG

**Comment by Vickyistda2003w** [comment]
Ich würde Sie einfachmal gesperrt lassen.
Wenn man die Doch braucht kann man sich ja melden bei Sprecher
