### ISSUE TITLE
affex.info

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1281]
Ist die nächste ÖBB Fake Seite
Das ist auch eine: baogeng.info
https://affex.info/2020/12/21/a-review-of-jakartas-public-transport-and-its-supporting-infrastructure/?utm_campaign=2WrIEJC8jj&utm_medium=Sermoon+%2F+AT+-+QBB+%281%29+%2F+Creo_OBB_1&utm_content=Sermoon+%2F+AT+-+QBB+%281%29+%2F+Creo_OBB_1&utm_term=4%29+Sermoon+%2F+OBB_1&fbclid=IwAR32gyTkBFYDnmhk6IWS6MbMbj9Yb8durQ6TwJFUdI-1tNgNjse4MONHgu0

https://baogeng.info/touristik/markt-und-produkte/bahnreise-inspirationen-2023-oebb-rail-tours-praesentiert-den-neuen-ganzjahres-katalog-82284?utm_campaign=tJxgFMNATQ&utm_medium=%7B%7Bcampaign.name%7D%7D&utm_content=%7B%7Badset.name%7D%7D&utm_term=%7B%7Bad.name%7D%7D&fbclid=IwAR1qYBM_x_lrerrsaMpCW4kbFnfvJVZOolbYgqLGVAsA4IrgG4tRaBgf0-s

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
