### ISSUE TITLE
Domians aus Bank Spam Mail

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1282]
Moin Sprecher und Chat,

Wir haben keine Blockliste in denn AT Banken für die Bawag Bank wo diese URLs rein sollten und die Bank 99 fehlt auch noch in denn AT Listen
kif.re.kr
taurus-online.ch
sga.bet
http://www.kif.re.kr/kif2///publication/viewer.aspx?controlno=229274&returnurl=http://taurus-online.ch/wp/za/

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domainsquatting für die 2 Banken jetzt hinzugefügt. Viele Grüße
