### ISSUE TITLE
Falsch beschuldigt, eine Malware-Domain zu sein

### ISSUE THREAD

**Issue by Dakai** [RPiList/specials#1283]
Hallo, ich habe zufällig Ihre Liste gefunden, und eine unserer Domains: chatgpt.thecopierparts.com, befindet sich auf Ihrer Malware-Domain-Liste:

[https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware)

Ich glaube, es muss ein Missverständnis vorliegen, da die Subdomain für unsere interne Nutzung der Open-AI-Chatgpt-Schnittstelle gedacht ist. Es hat nichts mit Malware zu tun. Könnten Sie bitte die Domain aus Ihrer Liste entfernen? Vielen Dank.

**Comment by RPiList** [comment]
Hi,
aufgrund des ChatGPT Scams landen pro-aktiv alle Domains mit dem Namen in unserer Liste.

Bei uns haben sich auch schon viele Nutzer gemeldet, dass Ihre ChatGPT Seite nicht Schadware wäre, sondern "nur" das Angebot an Dritte den Dienst zu nutzen. Das ist im Grunde die Definition von Phishing, weil dann i.d.R. versucht wird die Anmelde-Daten von den Dritten abzugreifen.

Wenn also die Domain nur von Ihnen "intern" genutzt wird, erfährt Ihre Seite durch die Listung bei uns keinen Schaden. Sie können immer noch drauf zugreifen. Für den Rest der Welt ist die Seite geblockt, aber die sollen ja sowieso nicht drauf zugreifen.

Das einzige Szenario das mir auf die Schnelle einfällt wäre, wenn Sie die Malware Liste in Ihrem Netzwerk nutzen. In dem Fall ist es aber wahrscheinlich sinnvoller, wenn Sie Ihre interne Domain whitelisten. Damit wäre sie dann für Sie "frei" und für den Rest der Welt, der nicht drauf zugreifen soll, geblockt.

Viele Grüße

**Comment by SevagBalk** [comment]
hi can you please remove our domain from the list? 
chatgptconsultancy(dot)com
