### ISSUE TITLE
updates.cdn-apple.com

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#1285]
o.g. domain für iOS Updates wird geblockt.
Verursacher:

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist:
  ||cdn-apple.com^

**Comment by RPiList** [comment]
Hi,

das Problem wurde vor ein paar Tagen gefixt. Bitte die Liste updaten. Ich verweise mal auf Issue #1280
