### ISSUE TITLE
gmp.de fälschlicherweise auf DomainSquatting1 Liste

### ISSUE THREAD

**Issue by sonst-was** [RPiList/specials#1287]
Moin,

gmp.de ist auf der DomainSquatting1 Liste:
![grafik](https://github.com/RPiList/specials/assets/1457478/06bc4ea2-e51a-46d3-a3f0-967acd63f0cf)

(vermutlich als squatting von gmx.de)

Die Domain ist aber eigentlich die Website von Hamburger Architekten.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
