### ISSUE TITLE
ebay-kleinanzeigen

### ISSUE THREAD

**Issue by Wackelblume** [RPiList/specials#129]
Keine Ahnung, ob das von den Nutzern der Kleinanzeigen nur "gewhitelisted" werden soll oder ob hier ein Fehler ist. 
Generell solle eigentlich die (www.)ebay-kleinanzeigen.de so erreichbar sein oder?

Match found in https://mirror1.malwaredomains.com/files/justdomains:
   ebay-kleinanzeigen.de-item23881822.com
   ebay-kleinanzeigen.de-item188522644.com
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
   ebay-kleinanzeigen.de
   ebay-kleinanzeigen.de.m-einloggen.html.targeturl.anzeigen.genericservers.com
   m.ebay-kleinanzeigen.de.s-anzeige.snvs.de
   www.ebay-kleinanzeigen.de
   www.ebay-kleinanzeigen.de.m-einloggen.html.targeturl.anzeigen.genericservers.com
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
   ebay-kleinanzeigen.de-item188522644.com
   ebay-kleinanzeigen.de-item23881822.com

**Comment by Twisterado** [comment]
Außerdem in dem Zusammenhang:
shop-apotheke.com
www.shop-apotheke.com
sind auch geblockt.

**Comment by MoweME** [comment]
### Die Seiten von eBay-Kleinanzeigen sollten wieder klappen!
Nicht alle deiner geschriebenen Domains sollten gewhitelistet sein.
Auf die Liste von MalwareDomains haben wir leider keinen Zugriff. Dort handelt es sich auch nicht um Sperren für eBay-Kleinanzeigen, sondern um Sperren für die Domains ,,de-item(irgendwelche Zahlen).com''.
