### ISSUE TITLE
Bitcointalk & SPam

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1290]
`bitcointalk.org`
ist ein Forum um über Bitcoin sich auszutauschen.
```https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails``` ist nicht der richtige Ort für die Domain.

**Comment by RPiList** [comment]
Eigentlich schon, wenn sie mit Spam um sich wirft... ich nehme mal an, deswegen ist sie überhaupt in der Liste gelandet.
