### ISSUE TITLE
Neue falsche United Domains Seite

### ISSUE THREAD

**Issue by adiko01** [RPiList/specials#1291]
Hallo,
bei uns ist heute eine kleine Welle an neuen fake United Domains Seiten angekommen.
Diese sind noch nicht in den Listen vorhanden. Ein hinzufügen wären schön.

`united-dannains.com`
`6161a2f773a.united-dannains.com`
`30bb9453.clinicaalphamed.com.br`

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
