### ISSUE TITLE
cdn-apple.com false positive?

### ISSUE THREAD

**Issue by andreaswilli** [RPiList/specials#1292]
Ich musste `updates.cdn-apple.com` whitelisten, um tvOS updaten zu können.

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist:
  ||cdn-apple.com^
```

**Comment by RPiList** [comment]
Wurde gerade entfernt. Weiß nicht warum die blöde Domain jetzt schon zum 3. Mal immer wieder in der Liste landet.

Viele Grüße
