### ISSUE TITLE
cdn-Apple.com in Coronablockliste, keine Updates für iPhones und co.

### ISSUE THREAD

**Issue by MeisterMio** [RPiList/specials#1293]
Warum ist das Apple cdn, und damit die Update-Server,  als RegEx Filter in der Corona Liste?
z.B. updates.cdn-apple.com

**Comment by RPiList** [comment]
Die Sperrung als RegEx Filter kommt nicht von uns. Aber in der Corona Liste war es vor ein paar Tagen drin und wurde schon entfernt. Einfach die eigenen Listen aktualisieren. Viele Grüße
