### ISSUE TITLE
Apple-Geräte können nicht geupdatet werden

### ISSUE THREAD

**Issue by Prideland** [RPiList/specials#1294]
Hi,
Ich musste "updates.cdn-apple.com" auf die Whiteliste setzen, damit ich mein iPhone updaten kann.

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist:
  ||cdn-apple.com^

**Comment by RPiList** [comment]
Der entsprechende Eintrag wurde vor mehreren Tagen bereits entfernt. Bitte updaten Sie Ihre Liste. Viele Grüße
