### ISSUE TITLE
Aufnahme von advenced-ip-scanner.com in DomainSquatting-Liste

### ISSUE THREAD

**Issue by sonst-was** [RPiList/specials#1295]
Gemäß https://www.golem.de/news/gehacktes-anzeigenkonto-angreifer-verbreiten-malware-via-bing-chat-2309-178094.html

wird die Domain `advenced-ip-scanner.com` dazu genutzt um Schadsoftware zu verteilen.

Man könnte auch überlegen, ob die ebenfalls im Artikel genannte Domain `mynetfoldersip.cfd` ebenfalls aufgenommen werden sollte, obwohl diese wohl nicht direkt Schadsoftware verteilt.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
