### ISSUE TITLE
Eher eine Frage

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1299]
Servas,

Ihr habe das Skript um eine Megaliste zuerstellen, ist die Ausgabe der Megaliste dann schon im ABP-style Format? oder noch im herkömlichen Format?

**Comment by RPiList** [comment]
Musste selbst im Code nachschauen...

Also es werden alle Listen, auch die ABP-Format Listen eingelesen. Die Ausgabe ist aber dann im NICHT-ABP-Format.

Wenn das Zielgerät/Zielsoftware mit dem ABP-Format umgehen kann, kann man aber auch drüber nachdenken eine Version zu erstellen, die dann die ABP-Formatierung beinhaltet. Wäre hier kein großes Problem.

**Comment by SGirl-Zockt** [comment]
Es wäre sehr gut wenn alle Domians in denn ABP-Format ausgeben werden.
Könntest du das bitte umbauen Danke

**Comment by RPiList** [comment]
Neues Skript ist fertig und hochgeladen. Auf Funktion habe ich es aber noch nicht testen können. Aber es war nur eine Stelle die geändert werden musste.
