### ISSUE TITLE
Lieferung

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1301]
Fake Investment/Traiding
aktiennomaden.com
scalinghub.de
skool.com
faktencheck24.com
baumdick.de
luckydomain.fun

Sex/Porno/Gewinnspiel Emails
lawnprosoftware.com
clonscript.com
dps.de #Versender kommt angeblich aus denn USA
mailspam.or.com.tw
am-our.live
theowensfamily.info
builddozer.co.uk
freebitco.in
cointiply.com
burakcinar.online
honeygain.me
kif.re.kr
teaseservice.live
leonidipotrero.com
megakons.com.ec
setecnorte.com
fas.ae
swagbucks.com
chroniclethinking.co
angebote-preissturz.de

Fake AppStore

Fake Glücklspielwerbung

Unsicher ob Fake oder Echt

**Comment by RPiList** [comment]
Vielen Dank, alle Domains hinzugefügt. Viele Grüße
