### ISSUE TITLE
aircash.eu

### ISSUE THREAD

**Issue by shunkica** [RPiList/specials#1303]
```
Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  aircash.eu
  www.aircash.eu
  
```
  Aircash is an electronic money institution with a license issued by Croatian National Bank and validity throughout the whole European Union.
  
  As far as #987 is concerned, I could not find any other evidence or mention that the e-vignettes bought through Aircash are not valid.

**Comment by RPiList** [comment]
> As far as #987 is concerned, I could not find any other evidence or mention that the e-vignettes bought through Aircash are not valid.

But as #987 stated, she has first hand experience.

Whats your kind of experience? Just hearsay or first hand like hers?

**Comment by shunkica** [comment]
I do not use the service but others on my network do.
It is a cash transfer app used by hundreds of thousands of people, not a scam site.

**Comment by RPiList** [comment]
Domain has been removed. Greetings.
