### ISSUE TITLE
Win10Telemetry - a few additions

### ISSUE THREAD

**Issue by Obegg** [RPiList/specials#1309]
Fresh Install of Windows 10, used debloater tools to remove any telemetry by disabling all the options.

`www.bing.com` - when searching anything on the search for windows 10, it always pings this URL, I even disabled bing search and it still pings.
`login.live.com` - no idea, but I don't need it
`cxcs.microsoft.net` - no idea but I don't need it

https://www.michaelhorowitz.com/Windows10.spying.onsettings.php

**Comment by LizenzFass78851** [comment]
According to https://learn.microsoft.com/en-us/windows/privacy/windows-endpoints-1909-non-enterprise-editions the domains have to do with the following:

-----

| Domain                       | Explanation                                                                            |
|-----------------------------|----------------------------------------------------------------------------------------|
| `www.bing.com`  | Used for updates for Cortana, apps, and Live Tiles |
| `login.live.com` | Device Authentication. *It will definitely also be needed if you want to use Windows with a Microsoft account.* |
| `cxcs.microsoft.net` | *Microsoft doesn't say anything, other sources probably say: Microsoft customer experience Center* | 

-----

I'm also wondering what exactly Microsoft uses the cxcs.microsoft.net domain for, but I wouldn't block the Bing domain and live.com.  If you were to go to Bing.com with your browser, this is the search engine that not many use, but some do use, and live.com is Microsoft's login server for logging in with a Microsoft account, both in the browser and in  Microsoft Windows.  Store, Xbox, etc.

**Comment by LizenzFass78851** [comment]
> Fair enough, I understand, one addition I forgot about is `ecn.dev.virtualearth.net`

According to other sources, the domain is used for Bing Maps (if applicable, under Windows the Microsoft/Windows Maps app or its offline maps function).
