### ISSUE TITLE
False Positive openairamberg.de

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#1311]
openairamberg.de belongs to Kulturverein JOKE e. V. and represents a local rock festival.

Associated domains:
dev.openairamberg.de
helfer.openairamberg.de
openairamberg.de
www.openairamberg.de

https://www.eichstaett.de/vereine/kulturverein_joke_e_v-10987/

**Comment by RPiList** [comment]
Vielen Dank für die Unterstützung. Domain wurde entfernt. Viele Grüße

**Comment by dieechtenilente** [comment]
@RPiList Die Domain ist weiterhin auf der Blocklist: https://github.com/RPiList/specials/blob/master/Blocklisten/malware
