### ISSUE TITLE
False positive: www.betsy-peymann.de

### ISSUE THREAD

**Issue by v411e** [RPiList/specials#1316]
Die Domain steht auf der Gambling Liste aber hat nichts mit Gambling zu tun.

Wie funktioniert eigentlich das Auto-Update? Also wo kommen die Domains her, die auf der Liste landen? :)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt.

Unser eigener Crawler scant ausgestellte Zertifikate auf die Domains.
