### ISSUE TITLE
scam domain: Deutsche Bank

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#1317]
https://db-legitimierung-photo.com.de

![image](https://github.com/RPiList/specials/assets/61943052/e7920ca7-4194-48d3-b99a-b24487aa4fe9)

**Comment by RichardBeisser** [comment]
wird auch in der gleichlautenden SMS-Kampagne verwendet:

deutsche.114077.com

ist nur über mobile Geräte erreichbar.

Ich würde die ganze Domain *.114077.com auf die Sperrliste setzen

**Comment by RPiList** [comment]
Vielen Dank für die Info. Beide Domains wandern, im ABP-Format, in die Schadware-Liste.
