### ISSUE TITLE
New SMS scam domain

### ISSUE THREAD

**Issue by cms04** [RPiList/specials#1318]
Hello,

today I received an (obvious) phishing SMS with a hostname that is not listed in the phishing blocklist.

`auslieferung-gesicherter.de`

![Screenshot_20231027_193159_Messages](https://github.com/RPiList/specials/assets/49516535/10d5af3f-c1d3-458c-ba27-c87fd427b131)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wandert, im ABP-Format, in die Schadware-Liste.
