### ISSUE TITLE
getmonero.org

### ISSUE THREAD

**Issue by andreaswilli** [RPiList/specials#1319]
False positive der offiziellen Monero-Seite?

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto:
  0.0.0.0getmonero.org
  build.getmonero.org
  cloud.getmonero.org
  coreteam.getmonero.org
  ctrl.getmonero.org
  dlsrc.getmonero.org
  donate.getmonero.org
  downloads.getmonero.org
  getmonero.org
  lab.getmonero.org
  mattermost.getmonero.org
  repo.getmonero.org
  static.getmonero.org
  taiga.getmonero.org
  updates.getmonero.org
  www.build.getmonero.org
  www.cloud.getmonero.org
  www.coreteam.getmonero.org
  www.ctrl.getmonero.org
  www.dlsrc.getmonero.org
  www.donate.getmonero.org
  www.downloads.getmonero.org
  www.getmonero.org
  www.lab.getmonero.org
  www.mattermost.getmonero.org
  www.repo.getmonero.org
  www.static.getmonero.org
  www.taiga.getmonero.org
  www.updates.getmonero.org
```

**Comment by RPiList** [comment]
Bin mir nicht sicher, ob ich verstehe, warum das "false positive" ist. Monero macht doch immer noch in Crypto oder haben sie das inzw. vollständig aufgegeben?

**Comment by andreaswilli** [comment]
Dann habe ich vielleicht das Ziel dieser Liste missverstanden. Ich dachte, es geht um unerwünschtes Crypto-Mining?

**Comment by RPiList** [comment]
Ja, das ist so richtig. Die Nutzer der Liste wollen vermeiden, dass ihr Browser oder andere Software "im Hintergrund" Crypto-Mining betreibt. 

Soweit ich das noch richtig in Erinnerung habe, hatte Monero dieses Vorgehen damals sehr leicht gemacht. Weswegen die (nicht von uns) auf diese Liste gepackt wurden.

Wenn also gesichert ist, dass dies heute nicht mehr möglich ist (auch nicht gegen den Willen von Monero), könnte man sie löschen.

**Comment by andreaswilli** [comment]
Danke für die Erklärung, davon habe ich nichts mitbekommen.
Auf den erste Blick sehe ich keine Anzeichen von Mining, habe mich aber nicht im Detail damit befasst.
Ich werde die Domain jedenfalls bei mir auf die Whitelist packen.
