### ISSUE TITLE
Sample of non-domain entries: "www..securecd-st.com" on Blocklist "Phishing-Angriffe"

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1321]
Mir ist aufgefallen das bei den Laden der Blockliste "`Phishing-Angriffe`" wohl ein unklarer Domaineintrag hinterlegt ist:
- `www..securecd-st.com`
##### Wohl ein Punkt zuviel enthalten

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
