### ISSUE TITLE
Whitelist store.minisforum.de 

### ISSUE THREAD

**Issue by GieGit** [RPiList/specials#1325]
store.minisforum.de ist der EU Shop von minisforum.de und wird von der RPiList-notserious geblockt, bitte whitelisten
Danke

**Comment by RPiList** [comment]
minisforum.de ist derzeit noch nicht online wie es scheint. Insoweit wird es wohl drauf bleiben müssen, bis das bestätigt werden kann.

**Comment by GieGit** [comment]
es scheint da nur die https://store.minisforum.de/ zu geben

**Comment by RPiList** [comment]
Denke mal wg. solcher Gebaren ist der Laden in der Abzocker-Liste gelandet. Seriös ist anders.

![Unbenannt1](https://github.com/RPiList/specials/assets/56664851/c1f8e70d-4d0f-4018-9758-f65c43af0d05)
![Unbenannt2](https://github.com/RPiList/specials/assets/56664851/27f39da2-ea76-4079-9174-fa54b6cd3825)

**Comment by GieGit** [comment]
ah okay, das ist mir garnicht aufgefallen. Produkte sind aber gut, ich habe seit Jahren mehrere davon im Einsatz!
