### ISSUE TITLE
False positiv firebasestorage.googleapis.com 

### ISSUE THREAD

**Issue by AleksCee** [RPiList/specials#133]
Die Domain wird von vielen opensource Projekten genutzt die eine Datenbank bei Google nutzen so wie ihr den pihole v-host von Google. Die Domain ist aber auf der phishing-Site:

firebasestorage.googleapis.com 

Liebe Grüße, Alex

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist gefixt.

**Comment by privatehosting** [comment]
Hallo, 
der Firebase Storage wird auch für Phishing Mails benutzt. 
Ich denke es wäre sinniger jedem das Whitelisten für sich zu erlauben, falls er es braucht. Allgemein würde ich diese jedoch blacklisten. Ich habe leider alle Phishing Mails mittlerweile gelöscht. Sollte ich jedoch wieder eine haben, werde ich diese dann gerne an euch weiterleiten. 

Gruß
Dominik

**Comment by privatehosting** [comment]
Hallo nochmal, 

hab tatsächlich ein Report gefunden wo man dies erkennen kann.
https://app.any.run/tasks/da43413b-3ac2-4732-b5ca-1fe9712e6330/

Gruß
Dominik

**Comment by MoweME** [comment]
Hi Dominik,

mir fallen auch ein paar Apps ein die die Firebase und deren Storageservice nutzen, deshalb würde ich es erstmal entsperrt lassen.

Mit freundlichem Gruß
Finn
