### ISSUE TITLE
duplicate blocklists found

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1330]
Die folgenden Blocklisten sind doppelt.
```
https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting/AT/DenizBank
https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting/AT/Denizbank
```

Der Unterschied ist das der erste Link mit den Wort "Bank" (groß-kleingeschrieben) und den zweiten Link mit den Wort "bank" (kleingeschrieben) ist. Diese sind auch doppelt im Repository vorhanden.
![Screenshot (102)](https://github.com/RPiList/specials/assets/82592556/54410fbc-0eba-41ae-8fb5-692172cb41f9)

**Comment by RPiList** [comment]
Ja, die Banken-Listen bekommen derzeit ein großes Update. Wird aufgeräumt wenn fertig. Vielen Dank für den Hinweis und viele Grüße
