### ISSUE TITLE
Frage zu SmartHome Geräten

### ISSUE THREAD

**Issue by blub4747** [RPiList/specials#1333]
Hi Community,

Wie wird hier mit SmartHome Geräten auf den Listen umgegangen ?
Schliesslich kann Ich keine extra Liste dafür sehen.

Sollte man da nach Hersteller gehen? Oder über den Anbieter im Hintergrund im Hintergrund? (Telekom, Amazon..etc)
Thx,blub4747

**Comment by RPiList** [comment]
Hi,

wir haben keine besonderen Listen für IoT bzw. SmartHome Geräte. Evtl. gibt es andere Anbieter deren Liste man im Pihole importieren kann. Ist mir aber nicht bekannt.

Aber bei der Vielzahl von Geräten die bei den Servern oftmals andere Dienstleister nutzen, ist eine Einteilung nach Namen recht schwierig. 

Eine "Liste" für die eigenen Geräte zu erstellen ist auf der anderen Seite ziemlich einfach. Das Gerät über das Pihole zwingen und man kann über die Pihole Log-Funktion sehen wohin es will.

Meine IoT-Geräte kaufe ich i.d.R. so, dass sie mit dem Home-Assistant "kompatible" sind. Wenn ja, dann kann man sie komplett im LAN einsperren, dann funkt da nichts mehr raus.

**Comment by blub4747** [comment]
> Das Gerät über das Pihole zwingen und man kann über die Pihole Log-Funktion sehen wohin es will.

Das würde in der Praxsis, etwa bedeuten den DNS Eintrag nochmals per Hand auf den Gerät einzutragen ?
Habe ich das so richtig verstanden ?

> Meine IoT-Geräte kaufe ich i.d.R. so, dass sie mit dem Home-Assistant "kompatible" sind. 

Ja, Grundsäztlich klingt das auch so, wie soetwas angehen würde.
Leider Handelt es sich meinen Fall nicht um mein eigens Netz, sondern um ein Netz von ein bekannten von mir, welcher alles Kreuz und Quer 'eingesammelt hat'. Was dann bedeutet, das ich bei diesen Menschen, mich immer einklinken muß.
Aber mit etwas 'treten' wäre auch das zu machen :)
