### ISSUE TITLE
Bad names in "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware"

### ISSUE THREAD

**Issue by WFANG12719** [RPiList/specials#1334]
Hi, 
I have been using the malware list for quite a long time. Recently I found in DNSMASQ log file indicating the following lines are in bad names:

l3p2hfgujoge5etzfmbkfci6wmy7azjpdwjipauwwkdokq6m-ipfs-dweb-link.translate.goog^
7t6woa4zoy7asclmd7l5t3n6tjuvvjda54clkm366t5ri7h4-ipfs-dweb-link.translate.goog^
bsjcj6aanp2oubchq5hpeinpmrtbaivx56bxoce3jf225mou-ipfs-dweb-link.translate.goog^
l3p2hfgujoge5etzfmbkfci6wmy7azjpdwjipauwwkdokq6m-ipfs-dweb-link.translate.goog^

Would you please help look into this?

Thanks,

**Comment by RPiList** [comment]
Hi,
thanks for supporting our project.

The domains mentioned by you are valid domains, formatted in the so called ABP-Style.

Are you using our list in your Pihole? Update your Pihole to the latest version.

Greetings.

**Comment by WFANG12719** [comment]
Thanks. 
I don't use Pihole as it can not be installed on my OpenWRT. 
I use DNSMASQ version 2.88 instead. Seems it does not support the ABP format names.

**Comment by RPiList** [comment]
Hi,

sorry but sooner or later all lists (not just the ones on our webpage) will be converted to the new ABP-style.

How does a domain in DNSMASQ have to be formatted to block all subdomains as well?

I read an article which claims it could be done with '.malware.com'. This should block malware.com and *.malware.com. Can you confirm it? Because if this is the case, we could make variations of your lists for DNSMASQ. 

Greetings.

**Comment by WFANG12719** [comment]
Hi,
I'd be glad to do the validation.Would you please give me the link which claims it could be done by applying ".malware.com"? I didn't find that and don't know how to apply.
________________________________

**Comment by RPiList** [comment]
Hi,
unfortunatly, I can't find it anymore. :-(

But trying to resulted in a few hits suggesting, that "blocking" all subdomains is the standard on DNSMASQ.

https://serverfault.com/questions/431605/dont-automatically-include-all-subdomains-in-dnsmasq-address

https://stackoverflow.com/questions/22313142/wildcard-subdomains-with-dnsmasq

Maybe you can verify that. If this is the case we could convert the lists to just lists without ABP-style.

Greetings

**Comment by LizenzFass78851** [comment]
according to the wiki of [ubuntuusers](https://wiki.ubuntuusers.de/Dnsmasq/):

> For example, you might want to prevent access to Facebook and the display of like buttons. To do this, enter the following two lines in the /etc/dnsmasq.conf file and then restart dnsmasq.
> 
> ```
> address=/facebook.com/127.0.0.1
> address=/fbcdn.net/127.0.0.1
> ```
> 
> This manipulates all DNS requests for facebook.com, fbcdn.net (the Facebook Content Delivery Network) and their subdomains (e.g. www.facebook.com) so that the requests are redirected to your own computer. There they then come to nothing.

I can't counter-test it, but the way this wiki describes it could provide certainty as to what blocking domains including subdomains on dnsmasq works.
Can also be used under e.g. Debian/ubuntu can be tested but as I said, I couldn't test it.

**Comment by RPiList** [comment]
> > This manipulates all DNS requests for facebook.com, fbcdn.net (the Facebook Content Delivery Network) and their subdomains (e.g. [www.facebook.com](http://www.facebook.com)) so that the requests are redirected to your own computer. There they then come to nothing.
> 

That's enough to also offer a ABP-style free version of our lists.

**Comment by RPiList** [comment]
Most lists have been converted. You will find them in the DNSMASQ subdir. Please update your lists and let us know if it works. Greetings.

**Comment by WFANG12719** [comment]
Thanks, everyone.

Most of files in the DNSMASQ folder are working well except the malware one. Why this file contains two pipe keys ( that is "| |" ) before some domain names ?

**Comment by WFANG12719** [comment]
By the way, would you please let me know what is the time and timezone roughly you automatically update the DNSMASQ folder ? So I can better change my cron job after the auto update by you guys. Thanks a lot !!!

**Comment by RPiList** [comment]
> Most of files in the DNSMASQ folder are working well except the malware one. Why this file contains two pipe keys ( that is "| |" ) before some domain names ?

Thats the ABP-style for pihole. It should be deleted, but an error in the update script prevented it. 

It is fixed now. Greetings

**Comment by WFANG12719** [comment]
> > Most of files in the DNSMASQ folder are working well except the malware one. Why this file contains two pipe keys ( that is "| |" ) before some domain names ?
> 
> Thats the ABP-style for pihole. It should be deleted, but an error in the update script prevented it.
> 
> It is fixed now. Greetings

It works well now. You are my hero. Thanks a lot!

**Comment by WFANG12719** [comment]
> > By the way, would you please let me know what is the time and timezone roughly you automatically update the DNSMASQ folder ? So I can better change my cron job after the auto update by you guys. Thanks a lot !!!
> 
> We don't have fixed update times.
> 
> Minor Updates are done when needed (requests for removal). Bigger Updates occur every 48 hrs.
> 
> If you want to set cronjob, set it to 4 a.m CET.
> 
> Greetings

Got you. I will adjust my cron job accordingly then. Have a good day.
