### ISSUE TITLE
False-positive: renault-banking-direkt.de

### ISSUE THREAD

**Issue by GermanPumpkin** [RPiList/specials#1337]
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/AT/RenaultBankdirekt:
  ||renault-bank-direkt.de^
  
Dies ist jedoch die gültige Domain der Renault Bank direkt.

**Comment by GermanPumpkin** [comment]
Wurde bereits behoben, danke.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
