### ISSUE TITLE
TORProject is blocked

### ISSUE THREAD

**Issue by oe3gwu** [RPiList/specials#1339]
The homepage of the real TOR Browser (https://www.torproject.org) is blocked. This seems to be an error. You do a great job to block similar sites or rip offs, but you also block the real one.

Please unblock it.

Thanks!

**Comment by RPiList** [comment]
Torproject.org is blocked in the proxies list. This is correct. Since you get a software on the website, that helps you circumventing services (a.k.a. proxy).

Greetings
