### ISSUE TITLE
drivy.pro

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1341]
Jetzt fangen die Jungs in Polen auch an damit

**Comment by RPiList** [comment]
Womit fangen die an? In welche Liste geht die Domain?

**Comment by SGirl-Zockt** [comment]
Die verkaufen Führerscheine

**Comment by RPiList** [comment]
Ist das sicher dass das ein Fakeshop ist?

Weil die verkaufen nichts. 
>Assistance in changing any national driver's license to Polish. We work with driving schools. Change DL without presence.

Die Website ist in englisch gehalten, weil sie sich an Ausländer in Polen richtet.

Und sagt ebenfalls ziemlich eindeutig:

>EU and EFTA Member States mutually recognise the validity of their driving licences, motor insurances and vehicle registration certificates. Therefore, driving licences been issued in EU and EFTA Member States remain valid in Poland.

Weiter geht es dann mit: "Wer mehr als 6 Monate in Polen wohnt **sollte**... nicht muss...

Hört sich okay an. 

Es sei den man findet im Internet in polnischen Foren, dass die die Kunden aktiv übern Tisch ziehen...
