### ISSUE TITLE
Domain freamer[.]de blocked - List: malware

### ISSUE THREAD

**Issue by freamer1** [RPiList/specials#1343]
freamer.de is my own domain and more less actual only used for mails. Do not know why it is on https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

**Comment by RPiList** [comment]
Reason is most likely malware on your server or your SSL certificate was also used on a domain hosting malware

**Comment by RPiList** [comment]
If you send me a list of other domains you used in conjunction with your certificate, I could check that. Greetings.

**Comment by freamer1** [comment]
> If you send me a list of other domains you used in conjunction with your certificate, I could check that. Greetings.

I only use this domain with the SSL Certificate, but only for mails. So no content. Do not understand where malware should come from.

**Comment by RPiList** [comment]
Domain has been removed. Let's see if it gets listed again. Greetings.
