### ISSUE TITLE
justbuyswiss.com

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1344]
Hey, unter der Domian ist eine Fake ORF Seite die wieder über Passves Einkommen geht

https://justbuyswiss.com/Sv2q6BNF?fbclid=IwAR0BQGLrPIrexTiqI0uJzIPa4cKrPHR_N5w1nD_gfMdEUrLidqeRDgFQpkE&ad_campaign_id=%7B%7Bad_campaign_id%7D%7D&utm_campaign=329_AT_BITQT_KC96_6982_KURZ&utm_adset=329_AT_BITQT_KC96_6982_KURZ&utm_kreo=329_AT_BITQT_KC96_6982_KURZ&ad_id=6516657307486&utm_placement=Facebook_Desktop_Feed&utm_buyer=38&p=630430282629697

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
