### ISSUE TITLE
digitalsday.com

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1347]
Wiedermal ein tolles Fake sind haben 1 Mio€ gewonnen

https://cc.digitalsday.com/de/?domain=mediatrck.com&offer=31&sp_domain=gameinnovative.club&device_brand=Desktop&city=Boeheimkirchen&region=Lower%20Austria&pixel_id=1756823091361785&clickid=42f39ntfy16vr7ee&camp_id=15422&fbclid=IwAR14-Ipof-yPizHeqv4AgsW9XxtJj-wOEixo40bwwLftvcE8yzUuXzoNLwo&click2lead=true&tsid=7&ev=AddToCart&uclick=ntfy16vr&uclickhash=ntfy16vr-ntfy16vr-pm7si4-0-heib6o-fyg53y-fyg5bl-0c10e7

**Comment by RPiList** [comment]
Auch hier vielen Dank. Domain wurde hinzugefügt. Viele Grüße
