### ISSUE TITLE
towfestive.fun

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1348]
Wird auf Facebook beworden das es angeblich von Mr Beast ist aber der ist aus denn USA, warum sollte er eine Deutsche App machen...

https://towfestive.fun/?fbp=193081009895861&fbclid=IwAR0ctvbCYnuh-MEli9mSUKvwU1dHXnRJm--ecJdrBg2az3DYddETvhlY-TY

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
