### ISSUE TITLE
False positive: frankonia.de

### ISSUE THREAD

**Issue by Teonyr** [RPiList/specials#1350]
Hey,

Frankonia ist ein großer Jagd- & Outdoor Fachhändler (sogar [mit eigenem Wikipediaeintrag](https://de.wikipedia.org/wiki/Frankonia)).

In der Liste "child-protection" wird allerdings die Domain [frankonia.de](https://www.frankonia.de/) geblockt.

Danke & viele Grüße

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
