### ISSUE TITLE
Overblocking für ipv64.net

### ISSUE THREAD

**Issue by JPRauwolf** [RPiList/specials#1358]
Ist ein relativ neuer DNS provider eines anderen deutschen Youtubers. Siehe https://schroederdennis.de/

In DNSMASQ/Phishing-Angriffe und Blocklisten/Phishing-Angriffe jeweils:
Zeile 80751 "ipv64.net"
Zeile 222649 "www.ipv64.net"

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info und die Unterstützung.

Die Domain wird vom Dienst Phishing-Army als feindlich eingestuft.

![image](https://github.com/RPiList/specials/assets/56664851/d39cc82b-811c-4cc1-b18a-90201d8be49d)

**Comment by JPRauwolf** [comment]
Interessant, ich werde es mal auf dem Discord ansprechen. Ich nutze den Dienst jetzt sesit gut nem halben Jahr und der ist zumindest meiner Meinung nach seriös.

**Comment by JPRauwolf** [comment]
Ist aber schon bekannt und gemeldet, wird sich in den nächsten Tagen also hoffentlich geklärt haben.
