### ISSUE TITLE
Netzwerk Config wird nicht angezeigt /eingerichtet

### ISSUE THREAD

**Issue by blaugrau90** [RPiList/specials#136]
In der Einstellung des iPhones wird keine IP angezeigt. DNS Auflösung funktioniert nicht (Synology DS918+)

![9EE7E9C3-98F7-4259-9AF6-BCF8968FB445](https://user-images.githubusercontent.com/61945343/76167971-116d6b80-616b-11ea-9a92-31f9c9b46ade.jpeg)

**Comment by MoweME** [comment]
Ein paar mehr Informationen wären hilfreich. Läuft es in einem Dockercontainer, hast du was umgestellt?
Vielleicht klappt das Pi-Hole auch und zeigt nur keine IP an?

**Comment by blaugrau90** [comment]
Das SV-PiHole läuft auf einem RPi3B. 
Allerdings hatte ich es auch schon im Virual Machine Manager auf einer Synology Disk Station DS918+ laufen. hier tritt das gleiche Problem auf. 

Auf dem RasPi kann ich den DNS benutzen. Auf der Synology DS918+ komme ich lediglich auf das Admin Panel

**Comment by MoweME** [comment]
Auf einer Diskstation hatte ich Pi-Hole Erfahrungen bis jetzt nur im Dockercontainer.
Ist das das selbe wie der ominöse VM-Manager?
Hast du ggf. Auch Port 53 für DNS Anfragen freigegeben?

**Comment by blaugrau90** [comment]
Es gibt auf des Diskstation sowohl Docker als auch einen VM-Manager zur Virtualisierung. In Docker habe ich auch keine Probleme. Eine Firewall ist ausgeschaltet bzw. eine Freigabe ist eingerichtet.

**Comment by MoweME** [comment]
Sind alle Ports freigegeben für die VM?

**Comment by blaugrau90** [comment]
Welche Ports sollen den freigegeben werden? Ausgenommen 53 für DNS?

**Comment by blaugrau90** [comment]
Habe gerade festgestellt, das die DNS Auflösung funktioniert. Allerdings funktionieren die Dienste wie z.B. Das Gravity Update funktioniert nicht. Aufgrund dessen, dass keine IP dort eingetragen wird. 

Eigentlich sollte das PiHole Image so konfiguriert sein, das es sich beim ersten Start selbst konfiguriert. Hier soll auch die IP mit eingetragen werden. Das tut es scheinbar jedoch nicht.

**Comment by RPiList** [comment]
Wurde die Version 2003 für die Diskstation genuttz?
Wurde abgewartet, ob sich die VM nach 45 Sekunden neu startet?
Kennen Sie sich Linux insoweit aus, dass ich Ihnen schreibe was Sie eingeben und Sie können das nachvollziehen?

Ansonsten lass ich mir was anderes einfallen. :-)

**Comment by RPiList** [comment]
Welchen Provider nutzen Sie? Bekommen Sie von dem Provider eine IPv6?

**Comment by blaugrau90** [comment]
Es wurde die Version 2003 benutzt. Sowohl auf der DiskStation als auch auf einem Pi3B tritt das Problem auf. Beide starten wie gewünscht neu. Allerdings wird die IP nicht in die PiHole Config eingetragen. 

Ich bin relativ versiert was Linux angeht. Ich denke also, dass ich nachvollziehen kann was sie schreiben.

**Comment by RPiList** [comment]
> Ich bin relativ versiert was Linux angeht. Ich denke also, dass ich nachvollziehen kann was sie schreiben.

Perfekt. 

Bitte mal über die Console den Befehl "sudo -i" aufrufen und sich mit dem Passwort 123456 Rootrechte verschaffen.

Danach "ifconfig" aufrufen und einen Screenshot der Ausgabe anfertigen.

Danach "nano /etc/pihole/setupVars.conf" aufrufen. Dann erhält man den Inhalt der setupVars.conf angezeigt. Da dürften dann keine/die Falschen IPs drin stehen. Die Frage ist dann, warum stehen die da. :-)

Aber mit den Screenshots helfen Sie uns schon sehr weiter. Welches ist Ihr Provider? Unitymedia/Vodafone? Bekommen Sie vom Provider eine IPv6-Adresse?

Vielen Dank für Ihre Mühen.

Viele Grüße.

**Comment by blaugrau90** [comment]
Im Config file steht gar keine IP. Das ist es eben. Ich kann sie manuell hinzufügen. Dann löst sich auch das Problem. Aber das ist ja nicht Sinn des Scripts, dass man es hinterher selbst einfügt. 

Ich habe in meinem Netz nur IPv4 und auch vom Provider bekomme ich nur IPv4 zugewiesen. Telekom ist der Provider.

**Comment by RPiList** [comment]
Ja, deswegen brauche ich die Screenshots, wenn möglich.

**Comment by RPiList** [comment]
Kann es sein, dass Sie Ihren Pi gestartet haben, als er noch nicht am Netzwerkkabel angeschlossen war? Weil dann würde das Skript bei dem Erststart ins Leere greifen.

**Comment by Stengah966** [comment]
Ich hatte übrigens exakt dasselbe Problem gehabt. Zusätzlich zur Erläuterung wäre vielleicht zu sagen, dass keinerlei manuelles Update möglich ist. Es erscheint jedes mal die Fehlermeldung „No IP addresses found! Please run 'pihole -r' to reconfigure“. Der Screenshot würde bei mir identisch sein wie bei BlauGrau90.
Ich verwende den PiHole auf einem RasperryPi 3 Modell B. Ich habe das Image auf eine SD Karte gezogen und dann den Raspberry zur Installation gestartet. 
Ich hatte den Raspi jedoch bereits früher im Wifi-Netz genutzt, so dass er bereits früher eine IP-Adresse hatte. Ihm wurde auch dieselbe wieder zugewiesen. Aber diese kannte er natürlich nicht, nachdem ich das Image raufgezogen hatte.

Vielleicht wichtig. Ich hatte den Raspi mit dem Wifi, also nicht Lan-Kabel verbunden. Wenn ich das Image verwende und erstmals starte, muss ich natürlich die Internetverbindung manuell nachträglich herstellen. Vermutlich deshalb wird bei der Erstinstallation die IP nicht eingetragen. Dies sollte anders sein, wenn Raspi per eth0 verbunden ist. Nachträglich habe ich den Raspi mit Eth0 verbunden, natürlich war das keine Lösung. Sauber wird die Installation vermutlich nur funktionieren, wenn der Raspi an Lan hängt.

Der Raspi arbeitete im Wifi auch und wurde nach den Netzwerkeinstellungen in der Fritzbox von allen Geräten angesprochen. Nur manuelle Updates waren nicht möglich, weshalb vermutlich auch keine automatischen Updates möglich waren. Das habe ich aber nicht geprüft.

Nach ipconfig waren IPv4 und IPv6 zusehen. Sie wurden aber wie im Screenshot nicht dargestellt und offenbar kannte PiHole diese nicht.

Inzwischen habe ich beide IPs manuell nachgetragen und alles funzt super. Nach dem Update hatte ich ein Wow-Effekt, als ich statt 550.000 geblockten Seiten dann 3,8 Millionen sah. 

Großen Dank an euch. Als nächstes werde ich den PiHole bei meiner 80 Jahre alten Mutter einbauen, die völlig verrückt nach dem Internet ist und keinerlei Hemmungen hat, dort was neues auszuprobieren. Beispielzitat: „Du musst mir helfen, ich glaube, ich habe das Internet gelöscht....Oh Gott....“

**Comment by RPiList** [comment]
Ja, das dürfte das Problem sein. Im entsprechenden Video wird auch gesagt, dass der Pi über Netzwerkkabel angeschlossen ist. DNS über WLAN ist nicht zu empfehlen.

Daher geht unser Init-Script hin und greift die eth0 Schnittstelle ab, nicht die wlan0 Schnittstelle.
