### ISSUE TITLE
Vorschlag zur Entfernung von `*.arpa` Domains aus der Blockliste

### ISSUE THREAD

**Issue by mschabhuettl** [RPiList/specials#1360]
Hallo Andreas,

ich möchte ein Anliegen bezüglich der Blockliste ansprechen. Es geht um die Einträge von `*.arpa` Domains, die derzeit in einer der Blocklisten enthalten sind.

## Problem
Die `*.arpa` Domains werden üblicherweise in internen und Heimnetzwerken verwendet. Diese Domains sind für spezielle Netzwerkfunktionen und -dienste vorgesehen und nicht für Werbung oder Tracking. Die Blockierung dieser Domains kann zu Problemen in Netzwerken führen. Als konkretes Beispiel: Ich verwende in meinem Netzwerk die Domain `mein_computer.vlan10.home.arpa`. Die Blockierung solcher Domains kann bei mir und anderen Nutzern, die ähnliche Konfigurationen verwenden, zu unerwarteten Netzwerkproblemen führen.

## Vorschlag zur Lösung
Ich schlage vor, sämtliche `*.arpa` Domains von der Blockliste zu entfernen. Diese Domains sind Teil der "Infrastructure Top-Level Domain" (ARPA steht für Address and Routing Parameter Area) und werden in der Regel für Netzwerkverwaltung und nicht für kommerzielle Zwecke genutzt. Ihre Entfernung würde die Funktionalität von Heim- und internen Netzwerken sicherstellen, ohne die Sicherheit oder Effektivität der Blockliste zu beeinträchtigen.

## Zusätzliche Informationen
Insbesondere `home.arpa` ist in RFC 8375 für spezielle Zwecke in Heimnetzwerken definiert. Die Blockierung dieser Domain könnte wesentliche Dienste in Heimnetzwerken stören. Daher ist es wichtig, solche kritischen Domains von Blocklisten auszunehmen, um die Netzwerkfunktionalität nicht zu beeinträchtigen.

Ich hoffe, du nimmst diesen Vorschlag in Betracht und freue mich auf dein Feedback. Vielen Dank!

Beste Grüße,  
Matthias

**Comment by blubbablasen** [comment]
Wenn pihole Domains im privaten Netzwerk auflöst ist doch grundsetzlich schon was falsch. pihole ist bei mir in der Kette für DNS Auflösung die letzte Instanz und hat nur die Aufgabe Domains außerhalb meines privaten Netzwerks aufzulösen. An erster Stelle steht bei mir ein Bind9 für interne DNS Fragen und wenn er nicht weiter weiß, schickt er die Anfrage an pihole. pihole wiederum schaut natürlich in die Listen und nutzt dann selber öffentliche DNS Server. Für mich sieht so eine funktionierende DNS Kette aus. Und anstelle des Bind9 könnte in "normalen" privaten Netzwerken eine Fritzbox sein, die ja intern alle Geräte mit der fqdn.fritz.box auflöst.

BTW: .arpa. ist auch die Endung für jeden Host mit einem gültigen PTR Record und diese Hosts können natürlich auch schädlich sein.

Gruß blubba

**Comment by mschabhuettl** [comment]
@blubbablasen kommt bei mir durch nextcloud am TrueNas Kubernetes "cluster" zustande. Das kann ich aber nicht beeinflussen warum meine Nextcloud IP auf den INTERNEN Postgres/PG Bouncer/Prometheus Container zugreift. Das ist Sache von den HELM Charts Entwicklern. Ich bin froh dass der Cluster so läuft, da Kubernetes immer noch ein bisschen Vodoo für mich ist und nie das macht was ich will. Aber egal. Sollte meiner Meinung nach trotzdem nicht .arpa sperren.
