### ISSUE TITLE
Import aller Listen scheitert 

### ISSUE THREAD

**Issue by mtdnet** [RPiList/specials#1362]
Wenn alle Listen importiert werden kann die FTL Database nicht mehr erstellt werden. :-)

**Comment by LizenzFass78851** [comment]
Bei mir auf einen frischen Stable Pihole (v5) konnte ich dies nicht reproduzieren.
```
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 42744663 (40533890 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

Werden bei dir Fehlermeldungen angezeigt, vorallem wenn du auf der Konsole (Terminal) `pihole -g` ausführst?

**Comment by mtdnet** [comment]
A ha, spannend, habe PiHole im Docker laufen, ich teste nochmal mit einer neuen Instanz.
Danke für die Info. 

Version:
Docker Tag [2023.11.0]
Pi-hole [v5.17.2]
FTL [v5.23]
Web Interface [v5.21]

**Comment by RPiList** [comment]
Gerade auch noch mal probiert. Funktioniert problemlos. Viele Grüße
