### ISSUE TITLE
Network overview 

### ISSUE THREAD

**Issue by vaake** [RPiList/specials#137]
Hey SVteam,
gibt es eine Möglichkeit die Network Liste zu bereinigen ?
Sieht Screenshot: 
![D20DCB70-32C8-4F81-8B15-946F111F4E73](https://user-images.githubusercontent.com/4558343/76208126-58a53c00-61ff-11ea-9dd4-05d047b767a9.jpeg)
Thx

**Comment by MoweME** [comment]
Jap. Dürften 2 Befehle sein:

```
sudo -u pihole sqlite3 /etc/pihole/pihole-FTL.db "DELETE FROM network"
```

```
sudo service pihole-FTL restart
```

**Comment by vaake** [comment]
Besten Dank 
Hat funktioniert.... :)
