### ISSUE TITLE
Fake gewinnspiel

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1372]
https://marricoyes.online/index.php?key=qnkjjir69ffgw1nt84p8&fbclid=IwAR2WRpa7EO4tbG6jI6sTahg7TwQ2l7EQRUQi_i7nNQ40nnfL0SvnU3eqOdg

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
