### ISSUE TITLE
Fake Casion/Playstore websetite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1373]
https://tintinsolve.fun/?sub_id_1=Kiev&sub_id_2=YevhenAT&sub_id_3=HS_AT_0029&sub_id_4=10102320711886650&sub_id_5=HS_AT_Velden_0001&external_id=%7BUSER_ID%7D&fbp=300854372820738&fbclid=IwAR1bEPmzwji81bCi_hBfiSAq8jr0dDHDtG6KbPEGVju7PvQ18IuB51HQ5zE

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
