### ISSUE TITLE
Linkfehler  | SPK BaWü/Bayern

### ISSUE THREAD

**Issue by T1z3n** [RPiList/specials#1374]
![image](https://github.com/RPiList/specials/assets/145705427/dad4584d-6545-4ebd-841c-ca6ca0d01137)
![image](https://github.com/RPiList/specials/assets/145705427/8cbe56e6-ee13-4ec5-adbe-5415e6de3af8)

Folgende Links zeigen Probleme auf:
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Sparkasse/Bayern3
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Sparkasse/BadenWuertemberg2
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Sparkasse/BadenWuertemberg1

Ob diese nun dafür verantwortlich sind, dass mein Pi-Hole sich in eine "readonly"-Database Situation bringt, habe ich stand jetzt noch nicht überprüft.
Die Links weißen aber zumindest Probleme auf . . .

**Comment by RPiList** [comment]
Hi,

die Datei Bayern3 gibt es nicht mehr. Die kann bei Ihnen also gelöscht werden.
Die zwei BaWü-Dateien wurden umbenannt, weil Schreibfehler im Namen. Wuerttemberg wird mit zwei T geschrieben. Also Die Dateien auch löschen und neu importieren.

Viele Grüße
