### ISSUE TITLE
Fake Nachrichten Seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1377]
https://pertidose.site/?ad_name=New+Sales+Ad+-+Copy&adset_name=1+-+Copy&campaign_name=Armin&pixel=343076971639658&token=EABe6vsb0UAQBOzjoYOO9SdhTlfLQeanwFoSWSEw2cDJAmDOTZAHcUZBrRZCOLEyAd9cIsZBehJfCh6lyt6ZBEiM8OQKITXJ5koXIC575QlD6CI47WtKX17jfdHlVxLblnfHHIkT3AvhwGLxzRYAbEzO9pW8Br4elyzbLvoLWXGQRFq0ZA9db716CyobNztRLZBvNgZDZD&acc=167702136&ad_id=6550529658153&key=m84agwlbqeotl2u0sx33&fbclid=IwAR2pu63xHZkrh2sVQs7YQtCCB8IELCbIbo2TOwJ_d9If_StYkxeGbtmVeCs

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
