### ISSUE TITLE
Ohne fls-eu.amazon.com kein Amazone Prime Video?

### ISSUE THREAD

**Issue by thomasmerz** [RPiList/specials#1379]
Bzw. erscheint mir diese Adresse in [child-protection](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection) nicht richtig aufgehoben zu sein… Meinetwegen Werbung, Tracking, aber mit Kinder-Schutz ist sicher was anderes gemeint!? 😜 

Wenn ich mir die anderen, nahe drum herum liegenden Adressen in der Liste anschaue…
```
||fls-eu.amazon.com^
||fls-fe.amazon-adsystem.com^
||fls-na-amazon.com^
||fls.au.doubleclick.net^
||fls.doubleclick.net^
||fls.uk.doubleclick.net^
```
vermute ich, dass es vielleicht
```
||fls-eu-amazon.com^
```
heissen sollten oder müsste!? 🤔

**Comment by RPiList** [comment]
Hi,

die Liste der  Child-Protection wurde absichtlich mit Schadware-Domains verunreinigt. Dies damit die Liste nicht zu leicht als "Anleitung" für Kids dienen kann.

Viele Grüße

**Comment by thomasmerz** [comment]
Aber dass man so kein Amazon Prime Video mehr schauen kann, hat doch nichts damit zu tun?! 🤷🏻‍♂️ Sollte die schadhafte domain nicht mit Bindestrich (domainsquatting) statt Punkt (Amazon) heißen?

**Comment by thomasmerz** [comment]
Und ein paar exemplarisch rausgepickte tracking-filternde Upstream-DNS-Resolver finden diese Domain auch nicht so schlecht, dass sie weggefiltert würde 😄  (oben NextDNS, unten AdGuard-filtered, siehe https://adguard.com/en/blog/adguard-dns-new-addresses.html)
```
✔ ~/temp/PRs/specials [master|✔] 
10:32 $ dig fls-eu.amazon.com @45.90.28.241
fls-eu.amazon.com.	806	IN	CNAME	gateway.prod.eu-west-1.forester.a2z.com.
gateway.prod.eu-west-1.forester.a2z.com. 45 IN CNAME endpoint.prod.eu-west-1.forester.a2z.com.
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 34.242.91.16
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 52.50.112.28
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 63.34.77.187
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 54.171.146.89
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 99.81.194.3
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 52.19.18.198
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 63.33.236.229
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 52.30.194.113
✔ ~/temp/PRs/specials [master|✔] 
10:32 $ 
✔ ~/temp/PRs/specials [master|✔] 
10:32 $ dig fls-eu.amazon.com @94.140.14.14
fls-eu.amazon.com.	45	IN	CNAME	gateway.prod.eu-west-1.forester.a2z.com.
gateway.prod.eu-west-1.forester.a2z.com. 45 IN CNAME endpoint.prod.eu-west-1.forester.a2z.com.
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 54.155.133.181
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 63.32.128.190
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 63.34.244.37
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 54.229.144.172
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 34.250.79.141
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 34.253.67.196
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 54.195.43.13
endpoint.prod.eu-west-1.forester.a2z.com. 45 IN	A 99.80.155.91
✔ ~/temp/PRs/specials [master|✔] 
```

**Comment by RPiList** [comment]
Hi,

vielen Dank fürs nachhaken...

dass man dann kein Amazon Video mehr schauen kann, war mir entgangen.

Ich benutze die Liste bei mir im Netzwerk ebenfalls, kann aber Prime Video schauen.

Die in der Überschrift stehende Domain wird gleich aus der Liste (einmalig) entfernt. Schauen wir mal ob sie wieder als Schadware gemeldet wird. Das ist aber wohl nicht zu erwarten, weil sonst wäre sie ja auch in der Schadware-Liste vorhanden.

> Dass diese Domain trackt ist absolut klar oder naheliegend, aber sie als "Schadware-Domains" einzustufen finde ich nicht richtig. Denn ohne sie kann ich/man kein Amazon Prime Video schauen

Unsere Schadware-Liste (die Version, die damals zur Verunreinigung der Kids-Liste genommen wurde) sammelt ihre Einträge aus verschiedenen Internet-Quellen. Einige dieser Quellen fassen Tracking als Schadware auf. Es gibt noch andere Gründe, warum einige den Schadware-Begriff weiter fassen, als nur Domains, die virus.exe verteilen.

Was mir selbst noch nicht klar ist: Wir haben eine Abteilung "Internet Services" die die notwendigen Domains für Amazon Prime Video auflistet. Da ist die in Frage stehende Domain auch nicht vertreten. Werde ich aber auch noch prüfen.

Viele Dank für die Mühen und viele Grüße

**Comment by thomasmerz** [comment]
Jo, vielen lieben Dank für die Mühe und die Listen im Allgemeinen ❤️ Ich kann's mir auch nicht erklären, warum es bei mir nur mit whitelisting dieser Domain geht und bei dir auch ohne 🤷🏻‍♂️
Auf jeden Fall sind wir uns ja nun einig, dass es mit sehr hoher Wahrscheinlichkeit ein false positive ist 😁 Ich bin gespannt, ob und was du bzw die Abteilung noch rausfindest…
