### ISSUE TITLE
forms.gle

### ISSUE THREAD

**Issue by AleksCee** [RPiList/specials#138]
Das ist der kürzlink zu Google Formularen die oft für Umfragen genutzt werden. Der ist auf der phishing Liste.

**Comment by RPiList** [comment]
Auf dieser Domain gab es in den letzten 90 Tagen insgesamt 122
Phishingangriffe.
[image: formsgle.PNG]

Da müssten wir abwägen, ob des für Nutzer der Liste wichtiger ist geschützt
zu sein oder ob es wichtiger ist auf den Dienst zugreifen zu können.

Ich muss zugeben, dass ich den Dienst von Google noch gar nicht kannte.

Evtl. ist es sinnvoll, den Eintrag hier zu entfernen und eine neue Liste
erstellen, auf der solche "Domains" landen, die "größeren"
Kollateralschaden mitbringen könnten. So dass der Nutzer entscheiden kann.

Am Mi., 11. März 2020 um 20:24 Uhr schrieb Alexander Palm <
notifications@github.com>:

**Comment by AleksCee** [comment]
Letztendlich kann ja jede Cloud App / CDN zum phishing genutzt werden.

**Comment by RPiList** [comment]
Richtig. Und in der Phishing-Liste werden wahrscheinlich 100% der Domains für Phishing UND normale Zwecke genutzt. Weil eben die eigentliche Phishing-Seite nur auf einer Seite auf der Domain liegt, wir aber die ganze Domain sperren.

Deswegen ist es so schwer festzulegen, wann wir die Domain sperren sollten und damit auch den legitimen Zugang zur Domain sperren.

Im Fall von forms.gle ist jetzt also die Frage, wie oft ruft die Zielgruppe solch eine Domain zu "normalen" Zwecken auf. Welche der beiden Nutzungen ist höher zu gewichten.

**Comment by RPiList** [comment]
Ist inzw. auf der Whitelist angekommen. Insoweit mache ich hier zu. Viele Grüße und vielen Dank für den Hinweis.
