### ISSUE TITLE
telegram api geblockt

### ISSUE THREAD

**Issue by migro3466** [RPiList/specials#1381]
Kann es sein, dass "api.telegram.org" in der "Malware" Blockliste versehentlich enthalten ist?

**Comment by cartercadse** [comment]
Kann ich bestätigen. Seit heute nacht ist wohl "||api.telegram.org^" in der Liste eingetragen

**Comment by austrogaucho** [comment]
Gibt es nen Grund?

**Comment by RPiList** [comment]
Hi,

die Domain wurde von urlhaus.abuse.ch gemeldet.

![image](https://github.com/RPiList/specials/assets/56664851/6e73c3bc-43b1-4102-81a8-de95206204c9)

Aber das ist natürlich nicht zielführend insoweit wird das direkt wieder entfernt.

**Comment by RPiList** [comment]
Domain wurde entfernt. Vielen Dank für die Hinweise. Viele Grüße

**Comment by austrogaucho** [comment]
gut so, vielen Dank! Respekt für euren Einsatz! 
Keep it up!!
