### ISSUE TITLE
False Positiv minisforum.de und schroederdennis.de

### ISSUE THREAD

**Issue by haruzept** [RPiList/specials#1382]
Moin,

minisforum.de ist auf der "notserious" Liste gelandet. Hier handelt es sich um den deutschen/europäischen Webshop von minisforum.com (siehe https://store.minisforum.com/)

schroederdennis.de ist auf der "malware" Liste gelandet. Hierbei handelt es sich um einen deutschen YouTuber/Blogger.

Bei beiden Einträgen scheint es sich um false positiv zu handeln.

**Comment by Nollknolle** [comment]
+1

**Comment by ipv64net** [comment]
Ich denke auch das es sich hier um False Positiv handelt..

**Comment by fiowhe** [comment]
Beide sind False Positiv

**Comment by RPiList** [comment]
Schnell ist die Jugend mit dem Worte... :-)

Es scheint kein False Positive zu sein.

urlhaus.abuse.ch ist sich sicher, dass Schadware von der Domain verteilt wurde.

![image](https://github.com/RPiList/specials/assets/56664851/af13d273-6da6-46de-9b08-094afa631522)

Die Schadware die da erkannt worden sein soll nennt sich Gootloader2

Mir ist auch klar, dass Dennis selbst über jeden Zweifel erhaben ist. Aber nutzt oder nutzte er mal Wordpress mit irgendwelchen Addons die ne Lücke hatten?

**Comment by RPiList** [comment]
Domain wird entfernt. Viele Grüße und vielen Dank für die Hinweise.

**Comment by RPiList** [comment]
Zum Thema "minisforum.de":

Ist das nur ein Backend?

Weil auf der Website nicht nicht viel, dass die Seite seriös erscheinen läßt:

![image](https://github.com/RPiList/specials/assets/56664851/0da6e730-f580-4d39-a2f3-d2fca7859fe9)

**Comment by haruzept** [comment]
Es geht um https://store.minisforum.de
Dort kommt man hin, wenn man auf der US Seite beim Shop EU auswählt.

**Comment by ipv64net** [comment]
> Schnell ist die Jugend mit dem Worte... :-)
> 
> Es scheint kein False Positive zu sein.
> 
> urlhaus.abuse.ch ist sich sicher, dass Schadware von der Domain verteilt wurde.
> 
> ![image](https://private-user-images.githubusercontent.com/56664851/291091756-af13d273-6da6-46de-9b08-094afa631522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MzQwNzcsIm5iZiI6MTcwMjgzMzc3NywicGF0aCI6Ii81NjY2NDg1MS8yOTEwOTE3NTYtYWYxM2QyNzMtNmRhNi00NmRlLTliMDgtMDk0YWZhNjMxNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE3MjI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NjA4YmQwM2E5MmEzMTMwMDhlMjZlNmQ3NWY0MDI2ODA0YmI1YTZjODIzMTY2OWVjYzNlNWZjZGM3MjZkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UdUO7azjN-kndGx4o5zSARgUIRpvCvk233frPyFHcxQ)
> 
> Die Schadware die da erkannt worden sein soll nennt sich Gootloader2
> 
> Mir ist auch klar, dass Dennis selbst über jeden Zweifel erhaben ist. Aber nutzt oder nutzte er mal Wordpress mit irgendwelchen Addons die ne Lücke hatten?

Das Problem ist - das es mal ein Problem WAR und dritte (in dem Fall abuse.ch) nun denken das ich noch ein Problem IST. Und Zack sind saubere Seiten auf Drecklisten. Sowas sollte validiert werden.

**Comment by RPiList** [comment]
Konkretisierung: Gootloader2 war wohl der Nutzer, der die Domain gemeldet hat.

**Comment by RPiList** [comment]
Hi,

> Das Problem ist - das es mal ein Problem WAR und dritte (in dem Fall abuse.ch) nun denken das ich noch ein Problem IST. Und Zack sind saubere Seiten auf Drecklisten. Sowas sollte validiert werden.

Validierung ist nicht möglich. Schon alleine aus dem noch unten folgenden Grunde.

Über 10 Mio. Domains mal eben zu prüfen ist nicht drin. Wir verlassen uns auf Dritte, die wie es bis jetzt ausschaut, in weit über 99% aller Fälle auch Recht hatten.

Wie Du selbst schreibst, scheint es ja auch hier richtig gewesen zu sein. 

Bei URLHaus fliegt Dein Eintrag nach 90 Tagen aus der Datenbank. Dies weil es absolut üblich ist, dass das Schadware-Domains vorübergehend offline gehen um dem Blacklisting zu entgehen. Nur um dann wenig später wieder online zu gehen. Deswegen die 90 Tage Sicherheitslistung.

Viele Grüße

**Comment by RPiList** [comment]
> Es geht um https://store.minisforum.de Dort kommt man hin, wenn man auf der US Seite beim Shop EU auswählt.

Vielen Dank für den Hinweis. Hier liegt ein strukturelles Problem unserer Liste vor.

store.miniforum.de ist in unserer Whitelist drin.

Aber der Eintrag wird vom Pihole negiert, weil "minisforum.de" mit dem ABP-Style formattiert ist. Normalerweise sollten Whitelistings höher gewichtet werden, als Blacklistings.

Da muss ich mir also was einfallen lassen.

Domain wird auch entfernt. Vielen Dank für die Mühen. Viele Grüße
