### ISSUE TITLE
crutchfield.com is blocked

### ISSUE THREAD

**Issue by go2null** [RPiList/specials#1384]
Found out I could not connect to crutchfield.ca.

I use ReThinkDNS and looking it's logs indicated that crutchfield.com was blocked per PRiList Child Protection.

crutchfield.com is blocked in `/Blocklisten/child-protection`.

crutchfield.com is a legitimate site for [Crutchfield Corporation](https://en.m.wikipedia.org/wiki/Crutchfield_Corporation), a Ccnsumer electronics retailer.

**Comment by go2null** [comment]
interesting titbit from [Wikipeadia](https://en.m.wikipedia.org/wiki/Crutchfield_Corporation)
> Crutchfield.com, was the first vendor-authorized audio/video retailer on the Internet.

**Comment by RPiList** [comment]
Hi,

thx for supporting our project and letting us know. Domain has been removed. Greetings
