### ISSUE TITLE
Please use comprehensive and descriptive commit messages with Bocklisten.md

### ISSUE THREAD

**Issue by domalex** [RPiList/specials#1385]
I find it rather difficult to follow alterations made in the Blocklisten.md file. Useful commit messages are missing most of the time. Users should easily understand what has changed and why. Otherwise it becomes a nightmare to make the required changes on their installations.

Commits for the Blocklisten.md file are in general a mess. Out of the last 4 commits there seem to be only one relevant. Useful commit messages are missing entirely:

### Commits on Nov 1, 2023
@RPiList: What has changed? Everything was deleted and afterwards added again.

### Commits on Dec 1, 2023
@RPiList: What has changed? Everything was deleted and afterwards added again.
@RPiList: What has changed? Everything was deleted and afterwards added again.
@LizenzFass: 2 lists were altered, 1 deleted, 1 added

**Comment by LizenzFass78851** [comment]
I am aware that I don't necessarily document well, but to explain below which commit of the file [blocklisten.md](https://github.com/RPiList/specials/blob/master/Blocklisten.md) caused which changes:

| Commit | Description |
|:------------------:|:--------------:|
| https://github.com/RPiList/specials/commit/af8b3d4afead259f2e62e823b532e069a4390b59 | In the commit, based on #1324, the problem with the bloated lines in the display of [blocklisten.md](https://github.com/RPiList/specials/blob/master/Blocklisten.md) was fixed. (more information in specified hashtag number) |
| https://github.com/RPiList/specials/commit/c4a624720ce8fbbe79d5a010ef2f7c636dd6e01f | Links were updated in the commit | 
| https://github.com/RPiList/specials/commit/256ed893ce9c76df56a3b4fe8f61818292e0ea19 https://github.com/RPiList/specials/commit/98e34c6a37e1b3836d26e8a54c6bee0206499534 | An additional space was added after the link. What's behind it can only be explained by @RPiList |

**Comment by RPiList** [comment]
Hi,

if there were no URLs added or changed by an update, they were changes of a technical matter. 

For example the last update was just adding a second space character at the end of each line. That was a small problem only Firefox users experienced. Chrome is working fine with just one space.

Explaining it in detail would add too much workload for a free project like this.

Greetings.

**Comment by domalex** [comment]
@RPiList We are all grateful for your initiative in providing and curating these lists.

However, If you left just a briefe message explaining the changes in your commits would help allot to keep up with the project and executing the required changes in everyone's local installation. Providing messages like @LizenzFass78851 does in his commits  helps already a great deal and doesn't cost you more than a few seconds. Please reconsider. Thank you.
