### ISSUE TITLE
False Positive: apple.news

### ISSUE THREAD

**Issue by maof97** [RPiList/specials#1389]
Hallo,

erstmal wollte ich danke sagen für diese tollen Listen, die sind echt gold Wert!

Hier zum False Positive:

`apple.news` taucht in der DomainSquatting1 Liste auf:
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1

Dies ist jedoch die offizielle Seite von Apples News+ Angebot.
https://www.virustotal.com/gui/domain/apple.news/ (Grün + Top-1k)

Speziell mein Mac ruft ab und zu `c.apple.news` auf was dann zu falschen Alarmen führt.

Glaube der ursprüngliche Grund für die Aufnahme in die Liste ist, dass `c.apple.news` letztendlich ein canonical für `cdn-icloud-content.g.aaplimg.com` ist, welches zum Beispiel [diese Malware](https://maltiverse.com/sample/06967a5904e582523b414b60a8a274a92933002b0762e89919a853c7af7d5ab0) dann benutzt hat um heimlich ein Bild zu laden (das dann wahrscheinlich bösartig war) ohne offensichtlich die iCloud CDN Domain zu benutzen (möglicherweise eine defense-evasion Taktik).

Im browser redirected die domain dann übrigens zu https://www.apple.com/apple-news/:
https://urlscan.io/result/9a378558-062f-482c-8931-e675e3eb6cc4/

Bitte entfernen.

Grüße und noch schöne Feiertage
Martin

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
