### ISSUE TITLE
Open source repo „disconnectme“ aufnehmen

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#139]
Hallo,

ähnlich wie das DuckDuckGo repo, steht das disconnectme (Antitracking) repo frei to Verfügung und kann für den SVPihole genutzt werden. 
Aktuell wird das o.g. Repo als Trackingschutz in Firefox genutzt.
Hier der link zum repo: https://github.com/disconnectme/disconnect-tracking-protection

**Comment by MoweME** [comment]
Hi BulldozerPete,

das Repo ist im JSON-Format, welches Pi-Hole nicht ohne Umwege lesen kann.
Ob wir es zwischenspeichern und im Pi-Hole Format hochladen, muss sich noch entscheiden.

**Comment by RPiList** [comment]
Vielen Dank für die Info.

Schauen wir uns auf jeden Fall mal an. Eigentlich haben wir https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt schon in unserer Auflistung aller Blocklisten verlinkt. Aber es ist natürlich möglich, dass das Original regelmäßig aktualisiert wird, unsere verlinkte Liste aber nicht. In dem Fall würden wir dann anfangen die Liste hier selbst zu hosten.

Der Grund warum wir DuckDuckGo übernommen haben liegt ganz ähnlich. Alle Listen die wir von Dritten gefunden haben listen nur die Main-Domain auf. Damit ist das ganze ziemlich sinnlos, da der DDG-Tracker explizit aufzeigt, dass das Tracking über Subdomains läuft. Insoweit machen wir uns hier derzeit die Mühe die einzelnen Subdomains in die Blocklist aufzunehmen.

**Comment by RPiList** [comment]
Ja, die Befürchtung hat sich bestätigt. Die verlinkte Liste wurde wohl überhaupt nicht mehr gepflegt bzw. ist total veraltet. Das original hat über 5000 Domains mehr auf der Liste. 

Insoweit noch mal vielen Dank für den Hinweis. Viele Grüße
