### ISSUE TITLE
mediamarkt.de

### ISSUE THREAD

**Issue by DiamantTh** [RPiList/specials#1390]
Kann einer Sagen wieso genannte Domain und evtl auch andere Seriöse Seiten in SupportingRussia Blacklist sind? 

Große Diskussion ob man die Blockieren sollte scheint es in der Ecke von Pihole gar nicht zu geben(also was ich eben kurz in meiner Suche gefunden habe)..

**Comment by RPiList** [comment]
Hi,
die Domain ist auf der SupportingRussia Liste, weil die Marke zu einem Unternehmen gehört, dass - wie der Name der Liste sagt - Russland unterstützt. 

Ob man die Liste im Pihole in die Blocklisten einträgt ist dann jedem Nutzer selbst überlassen. Theoretisch kann man ja auch dafür sein und die gleiche Liste dann in die künftige Whitelist zu importieren.

Viele Grüße
