### ISSUE TITLE
False positive in Malware list: `i.ibb.co`

### ISSUE THREAD

**Issue by vincejv** [RPiList/specials#1393]
This domain is used by a legitimate image hosting site https://imgbb.com/
Since this domain is blocked by your list, any images hosted on imgbb does not load, hope you can fix it asap
https://github.com/RPiList/specials/blob/master/Blocklisten/malware#L148885

Line 148885 as of commit fcea972

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
