### ISSUE TITLE
Bitte Sperren

### ISSUE THREAD

**Issue by maof97** [RPiList/specials#1398]
Bank Phishing: https://deutschebank-kundendienst.comidrekt.net/verifizierung/

Tatsächlich ziemlich gut gemacht (und somit auch ziemlich gefährlich).

Also 
`deutschebank-kundendienst.comidrekt.net`
und gleich auch 
`comidrekt.net`

bitte sperren.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
