### ISSUE TITLE
Bitte beurteilen

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1399]
https://schnellmpu.com/

https://www.facebook.com/profile.php?id=61554212090193

**Comment by RPiList** [comment]
Scheint ein Fake von https://www.fahrschuletischmacher.de/ zu sein.

Ist dann jetzt auf der Fake-Shop Liste.

Facebook Links kann ich leider nicht aufrufen, weil ich keinen FB-Account habe. Aber ich denke der wird nichts gegenteiliges ziegen.

**Comment by SGirl-Zockt** [comment]
[Facebook.pdf](https://github.com/RPiList/specials/files/13773173/Facebook.pdf)
