### ISSUE TITLE
Fake Casions Austria app

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1405]
https://casinos-austria.install-app.com/?sub3=90&fbp=1414304849182367&sub2=9OPdtKFIEB&sub5=AT3ad&fbclid=IwAR1Vy2lo8uMdozeuqfvi8phRv9-Peo_q4QHzAnTpn_sDh6HEj4aGlIarJLE

Ich glaube Casions Austria haben nicht mal eine APp

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
