### ISSUE TITLE
device-metrics-us-2.amazon.com

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1408]
Hallo,

gerade im pihole entdeckt:

device-metrics-us-2.amazon.com

Kommt von FireTV-Fernbedienungs-App.
Metrics ist nichts was man haben möchte.

Ich überlasse es euch in welche Blacklist ihr das aufnehmt.
Regex würde sich auf jeden Fall anbieten, evtl. noch weitere für statische Einträge.

**Comment by RPiList** [comment]
Hi,

sorry für die Verspätung, ist jetzt erst mal auf der Malware Liste.

Laut Berichten kann es sein, dass das Pihole jetzt mit Anfragen zugespamt wird und das geht evtl. auf die Batterie. Also das beobachten.

Viele Grüße
