### ISSUE TITLE
Phishing/Spam: "sanityflash.mom"

### ISSUE THREAD

**Issue by Gandalf1783** [RPiList/specials#1411]
Hier eine Domain die mir grad untergekommen ist:

https://sanityflash.mom/ca/s66/?clickid=w2jo3tq2u5otfp7u240uc70s&af_siteid=f73f9fa0-17af-4f39-80b1-f06057d6db6d&af_c_id=2867ee01-b7c9-4551-bfec-aacb808cc3a3&c=16.11%2FIOS%20geo%20test%20multi%20geo%20Maxshield-CoreDefender&af_click_lookback=7&model=iPhone&brand=Apple&app=qeur

**Comment by RPiList** [comment]
vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
