### ISSUE TITLE
False-Positive ||swisslife.com^

### ISSUE THREAD

**Issue by netranger512** [RPiList/specials#1417]
Good day

I found a false positive:

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious:
  ||swisslife.com^

The company is described here:
https://en.wikipedia.org/wiki/Swiss_Life

By the way: why do the entries start with || ? I am not quite getting it.

Thanks and wishing you a good rest of the weekend

**Comment by iam-py-test** [comment]
> By the way: why do the entries start with || ? I am not quite getting it.

That is the filter syntax for AdBlock Plus/uBlock Origin/AdGuard: `||[domain]^` blocks all connections to *domain*
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-network-filtering
https://adguard.com/kb/general/ad-filtering/create-own-filters/#blocking-by-domain-name
Thank you

**Comment by RPiList** [comment]
Hi, 

thx for supporting us. Domain has been removed.

And as @iam-py-test already stated, the "double pipe" || means that all possible subdomains of a domain are blocked too.

Greetings
