### ISSUE TITLE
RPiList-Malware shows "Number of Domains on List: 0" in PiHole adlist details

### ISSUE THREAD

**Issue by CraigeryTheKid** [RPiList/specials#1418]
I tried searching existing issues, but had trouble truly checking for an old response due to languages.

When adding the RPiList-Malware Adlist from Firebog.net, it shows "0 domains" in the details. All the other lists correctly show a number of domains similar to number of lines in the document.

I do notice that all domains in List-Malware are preceded by "||" - which seems like it could be related?
Given the popularity of this list, I assume I am doing something wrong, but none of the other lists required additional action.

Please and thank you,
Craig

**Comment by RPiList** [comment]
Hi Craig,

you missed a few updates from Pihole. The update from March 2023 made sure to understand the new ABP-Format using the "||".

Greetings.

**Comment by CraigeryTheKid** [comment]
I am running latest pihole.
what else can I check?

![list-malware](https://github.com/RPiList/specials/assets/96599827/41c3acf5-36b7-4e45-bbbd-c514bf7fa9e9)
![pihole](https://github.com/RPiList/specials/assets/96599827/18e44abe-b125-434d-a305-f7ba666d471d)
