### ISSUE TITLE
example.com / example.org

### ISSUE THREAD

**Issue by Zoey2936** [RPiList/specials#1421]
Hallo,
irgendwie haben es example.com und example.org auf die Blacklisten geschafft, können diese bitte entfernt werden? Ich frage diese ab um zu schauen, ob meine DNS-Server laufen. https://www.iana.org/help/example-domains

**Comment by RPiList** [comment]
Auf welcher Liste soll das drauf sein?
Weil ich kann es nicht finden. Viele Grüße

**Comment by RPiList** [comment]
gefunden und wird gleich entfernt. Viele Grüße
