### ISSUE TITLE
Phishing - Apple Prizes

### ISSUE THREAD

**Issue by netranger512** [RPiList/specials#1422]
Hello

A phishing email reached my inbox today, telling me I had won some apple products. The links and pictures are pointing to:
nelyc5h5x.jaynapatel.co.uk

The domain jaynapatel.co.uk was registered today, so I think it is safe to block the whole domain.

Let me know if I should provide the complete URL.

Cheers & Thanks

**Comment by RPiList** [comment]
Thx for supporting us. Domain has been added. Greetings
