### ISSUE TITLE
False Positive kvb.de

### ISSUE THREAD

**Issue by chessgarf** [RPiList/specials#1424]
kvb.de is Kassenärztliche Vereinigung Bayern and surely not a bank squatting domain.

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-5-Teil-1:
  ||kvb.de^
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-6:
  ||kvb.de^

**Comment by RPiList** [comment]
Thx for supporting us. Domain has been removed. Greetings
