### ISSUE TITLE
False Positve: Domain Squatting PSD-Bank ||psd-nord.de^

### ISSUE THREAD

**Issue by brunick** [RPiList/specials#1432]
Hi, 
there is a false positive on the 

> **RPiList/specials/master/Blocklisten/DomainSquatting/DE/sonstige_Banken/PSD-Bank**

```
||psd-nord.de^
```

this is the real + current domain of PSD-Nord, please remove it, thx

**Comment by RPiList** [comment]
Hi,
thx for supporting our project. Domain has been removed. Greetings.
