### ISSUE TITLE
whitelist hopp.bio

### ISSUE THREAD

**Issue by shaulgo** [RPiList/specials#1434]
Hey, our service is now using hopp.bio as well as hopp.to (that is already whitelisted). 

Hopp.bio is aimed at link-in-bio part of our platform. It is being blocked by multiple ISPs, causing widespread disruption for a substantial number of users.

hopp.to issue: https://github.com/RPiList/specials/issues/942

Thanks

**Comment by RPiList** [comment]
Hi,
thx for letting us know. Domain has been removed. Greetings

**Comment by shaulgo** [comment]
@RPiList Thanks, is it possible to add it to the whitelist. 
PR https://github.com/RPiList/specials/pull/1436
