### ISSUE TITLE
`fritz.box`-Domain wurde gecovert

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1440]
Ich habe gehört, dass die Domain `fritz.box` nun jemanden gehört, was am Ende dazu führt, dass wenn man keine fritzbox hat (über Mobilfunk oder beim Ändern des DNS-Servers bzw. beim VPN zum Server im Internet gut demonstrierbar) und auf den Browser `fritz.box` eingibt, das man (laut den News) auf eine NFT-Webseite geleitet wird.

![nft](https://github.com/RPiList/specials/assets/82592556/5e78b0f6-7867-4a6d-ac13-a0155e7b8fc6)

#### Sollte die Domain in die Blockliste (wie etwa DomainSquatting)? 

> [!NOTE]
> Verkäufer von *.box Domains ist `my.box`

Quellen:
- whois Domain zur Domain `fritz.box` und `my.box`

https://whois.domaintools.com/fritz.box
https://whois.domaintools.com/my.box

- News dazu:

[Borncity](https://www.borncity.com/blog/2024/01/26/fritzbox-problem-eingabe-der-url-fritz-box-leitet-pltzlich-auf-externe-seite-um/)
[Deskmodder](https://www.deskmodder.de/blog/2024/01/27/avm-fritz-box-kann-auf-nft-webseite-fuehren/)
[Stadt-Bremerhaven](https://stadt-bremerhaven.de/fritz-box-warnung-an-fritzbox-nutzer/)
[Heise](https://www.heise.de/news/Verwirrend-Internet-Domain-fritz-box-zeigt-NFT-Galerie-statt-Router-Verwaltung-9610149.html)

**Comment by LizenzFass78851** [comment]
@RPiList, soll die Domain `fritz.box` (und `my.box` bzw. alle *.box Domains) in die Blockliste? (wie etwas DomainSquatting)

**Comment by RPiList** [comment]
Ich habe noch keine Lösung gefunden, die allen Bedenken gerecht wird.
Ich glaube wir können nicht einfach fritz.box in die Blockliste packen, weil wir es dann für 100% aller Nutzer blockieren, die evtl. ihre Fritzbox auf die Art aufrufen. Durch den internen Aufruf kann dem Nutzer aber (scheinbar) auch ohne die Sperre kein Schaden entstehen, weil seine Fritzbox den Aufruf "abfängt".

Scheint mir also so, dass wir mit einem Blocking im Pihole für den normalen LAN Nutzer gar nichts erreichen.

Die Gefahr lauert "draußen", wenn ein Nutzer fritz.box z.B. mit dem Handy aufruft. Da hätte er bis her keine Antwort erhalten und landet jetzt auf der neuen Website des "Domain-Squatters". Von seinem Pihole mit der Blockliste wird er aber "draußen" sowieso nicht geschützt...

Geht er über VPN local, bestünde wieder keine Gefahr... wir erreichen mit einem Block hier wieder nichts. 

AVM hat imho ein ganz anderes Problem. Die verkaufen jetzt Hardware die "legitime" Zugriffe aufs Internet umbiegt. Derzeit ist fritz.box ja nur ein NFT-Website... rechtlich gesehen völlig okay, die von keiner Fritzbox intern durchgelassen wird.

AVM müsste hier mit einem Security-Patch die Firmware der Boxen fixen und aus fritz.box einfach fritz.fritzbox draus machen. Gibt natürlich noch andere Möglichkeiten, aber AVM müsste das patchen...

Ich wollte das am Montag mal im Twitch-Stream ansprechen... evtl. entgeht mir auch etwas...

**Comment by Bob-Nixkoenner** [comment]
Moin Moin Zusammen!

Da das Thema am Montag im Stream angesprochen wurde, ist man natürlich schon etwas verwundet, wie es AVM überhaupt dazu kommen lassen konnte. 
[Stream](https://www.twitch.tv/videos/2047417350)
Aber Vorwürfe und Beschuldigungen bringen ja die Sache nicht wirklich Voran. 

Da hier in der SemperVideo Gemeinde zu Teilen auch über die TLD .box die AVM und selbst O2 (dem Stream Chat nach - ungeprüft) angesprochen wird stelle ich mir die Frage, WER greift WIE OFT darauf zu. 
Die Netzwerkadmins / IT-Familienangehörigen, ausschließen können wir aber die Kinder , Eltern oder Großeltern. 

Warum also nicht die TLD .box gleich auf die Regex Blacklist? 
Die, die darauf zugreifen müßen aus administrativen Gründen, wissen, wie sie ein den DNS umgehen können, oder rufen einfach gleich die IP auf. 

Zumindest fällt mir auf die Schnelle nicht ein, was für eine .box Domain wirklich spannend wäre, ausser "doener.box" ( Döner Witze gehen immer!) 

Zusatz:
Da allerdings nicht jeder die REGEX übernommen hat, wäre auch ein Listeneintrag eine Option, der bestimmt durchaus mehr Haushalte erreichen würde. 
Nur da ist wieder die nächste Frage, wie oft wird dies dann durch andere als "Falschmeldung" angesehen.

Aus Spaß und Freude KÖNNTE man ja AVM mal anfragen, was die für eine Idee dazu haben, ggf beschleunigt dies dann die Vorgänge etwas, und man hat dann fritte.lan oder .local, oder was auch immer.
Damit könnte AVM zeigen, wie sehr diese an der Sicherheit der Nutzer interessiert ist, gerade jetzt, wo man Käufer sucht, wäre das bestimmt ein gutes Zeichen. 
Falls man da nicht reagiert, packt man es hier auf die Easylist oder was anderes eingängiges, was jeder hat, und verweist bei Beschwerden auf AVM, die wohl nicht handeln wollen.

**Comment by LizenzFass78851** [comment]
#### Kleines Update was das nslookup von `fritz.box` betrifft,

Bis Anfang der Woche war noch als cname `site.my.box` hinterlegt.
Nun steht als cname bei `fritz.box`: `example.com`.

- Seit heute
```
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> fritz.box @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22891
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;fritz.box.                     IN      A

;; ANSWER SECTION:
fritz.box.              3600    IN      CNAME   example.com.
example.com.            16502   IN      A       93.184.216.34

;; Query time: 119 msec
;; SERVER: 9.9.9.9#53(9.9.9.9) (UDP)
;; WHEN: Wed Jan 31 17:58:31 CET 2024
;; MSG SIZE  rcvd: 79
```

-----
Das führt dazu das die Webseite nun folgendes Zurückgibt:
![Screenshot (1)](https://github.com/RPiList/specials/assets/82592556/d49fb539-c855-42db-9821-23a5b0a0502d)

-----
Daher vermute ich das der Domainbesitzer von `fritz.box` den cname geändert hat, damit zumindest derzeit die NFT-Webseite nicht mehr dadurch aufrufen kann.

-----
Verwendeter 'dig' Befehl:
`dig fritz.box @9.9.9.9`

**Comment by LizenzFass78851** [comment]
> Aus Spaß und Freude KÖNNTE man ja AVM mal anfragen

Bei [Borncity](https://www.borncity.com/blog/2024/01/26/fritzbox-problem-eingabe-der-url-fritz-box-leitet-pltzlich-auf-externe-seite-um/) hat der Autor des Beitrags (im ersten comment verlinkt) AVM auch schon versucht da mal nachzufragen.:

- Zitat:
> [!IMPORTANT]
> In der Antwort-Mail hat mir die Pressesprecherin von AVM, Doris Haar noch eine Erklärung gegeben, was passiert ist. Demnach befindet sich die Domain fritz.box derzeit in einem Verkaufsprozess, an dem auch AVM beteiligt ist. Daher können Anwender zurzeit gelegentlich auf eine andere unpassende, harmlose Seite, gelangen, wenn die URL fritz.box im Browser angegeben wird.
> 
> Der Aufruf von fritz.box im Heimnetz sei, wie gehabt möglich, und liege in der Hoheit der heimischen FRITZ!Box. Bisher haben Anwender, die versehentlich fritz.box außerhalb ihres Heimnetzes aufriefen, einen Fehler des Browsers gemeldet bekommen, oder wurden auf eine Suchmaschine geleitet. Momentan wird Anwendern, die versehentlich fritz.box außerhalb ihres Heimnetzes aufrufen, eine offensichtlich unpassende und harmlose Seite angezeigt.
> 
> Die Pressesprecherin teilte mir mit, dass AVM in der Zwischenzeit alle Aktivitäten rund um die Domainvergabe beobachtet und die sicherheitsrelevanten Anforderungen im Blick habe.
> 
> Verhindern könnte man das, indem man die IP-Adresse zum Zugriff auf die FRITZ!Box verwendet – oder die IP-Adresse 192.168.178.1 in der hosts-Datei von Windows mit fritz.box verknüpft, wie das auch in den nachfolgenden Kommentaren vorgeschlagen wurde.

Evtl. ist das nicht die konkrete Antwort, die @Bob-Nixkoenner bzw. @RPiList erwartet haben.

**Comment by LizenzFass78851** [comment]
@RPiList Ich habe noch keine weiteren Informationen gefunden, die bestätigen, dass die Domain fritz.box nicht für böse Zwecke missbraucht werden.

Für das Pihole gibt es eine Möglichkeit was einzustellen, damit trotz Verweis auf externe DNS-Server die `*.fritz.box` Reihe immer lokal aufgelöst werden.
Siehe: https://docs.pi-hole.net/routers/fritzbox-de/#hostnamen-in-pi-hole-statt-ip-addressen-conditional-forwarding
Ob es andere Möglichkeiten gibt dies zu bezwecken weiß ich nicht.

**Comment by LizenzFass78851** [comment]
Mittlerweile gehört die `fritz.box` Domain wieder AVM, wie [schmidtisblog](https://www.schmidtisblog.de/avm-holt-sich-fritz-box-domain-zurueck-sicherheitsrisiko-gebannt-1745118/) bestätigte.
Demnach ist wenn man die `fritz.box` Domain aufruft, nun folgendes zu sehen:
![Bild1](https://github.com/RPiList/specials/assets/82592556/25b539c1-ddee-41ac-af9f-3f0f58f24c26)

Demnach ist `fritz.box` Domain wieder in guten Händen.
