### ISSUE TITLE
False positive in Malware list: `iili.io`

### ISSUE THREAD

**Issue by vincejv** [RPiList/specials#1443]
Domain: `iili.io`
Used by image hosting site: https://freeimage.host/

Images won't load, site is unusable this is a LEGITIMATE image hosting site, sample pages that pictures won't load
https://freeimage.host/i/f359a7ee1dac.J7F8QUv
https://freeimage.host/i/c4418252a33e.J7F86WF
https://freeimage.host/i/abe9e0253bc8.J7F8UOB

Without your blocklist:
![image](https://github.com/RPiList/specials/assets/1276544/db785ab3-75a6-4fa8-948c-814d51f51573)

With your blocklist ON:
![image](https://github.com/RPiList/specials/assets/1276544/85973b87-6153-49cc-8c90-ac14824a143c)

Last seen:
Line 178156 of Malware List as of commit 6e42b12700fa027088ffcf60b28d3caf39a49831
https://github.com/RPiList/specials/blob/6e42b12700fa027088ffcf60b28d3caf39a49831/Blocklisten/malware#L178156

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.
