### ISSUE TITLE
False positive gambling Liste

### ISSUE THREAD

**Issue by prjktx86** [RPiList/specials#1445]
Die Gambling Liste enthält den Eintrag storeedgefd.xbetservices.akadns.net meiner Meinung nach ein False-positiv da es sich um ein Teil von Akamai akamai.com handelt. Hier genauer um die Weiterleitung im Windows Store

**Comment by frostieDE** [comment]
Muss ich leider bestätigen. Habe die Domain `xbetservices.akadns.net` (als Wildcard) in die Allowlist aufgenommen :)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße

**Comment by soonic6** [comment]
@RPiList  ist leider wieder drinne:

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling:
  ||8xbetservices.micro.blog^
  ||8xbetservicesvn.micro.blog^
  ||instant-arcade-stg.xbetservices.akadns.net^
  ||instant-arcade-stg2.xbetservices.akadns.net^
  ||xbetservices.akadns.net^
  ||xbetservices.com^
```

**Comment by RPiList** [comment]
Domain wurde entfernt.

xbetservices.akadns.net ist jetzt auch auf der Whitelist. Vielen Dank und viele Grüße
