### ISSUE TITLE
False positives on phishing and malware lists

### ISSUE THREAD

**Issue by sarimc** [RPiList/specials#1447]
Maybe unpopular, but all official domains for a subscribe only email list with unsubscribe links readily available. Certainly not phishing or malware.

Match found in https://v.firebog.net/hosts/RPiList-Phishing.txt:
  email.deskofdonaldjtrump.com
  email.event.donaldjtrump.com
  email.press.donaldjtrump.com
  email.victory.donaldjtrump.com
  email.win.donaldjtrump.com
Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  ||email.deskofdonaldjtrump.com^
  ||email.event.donaldjtrump.com^
  ||email.press.donaldjtrump.com^
  ||email.victory.donaldjtrump.com^
  ||email.win.donaldjtrump.com^

Thank you

**Comment by fionnlagh** [comment]
I've also noticed a false positive:
in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
||flyff.com^

this is a legitimate online MMORPG.

**Comment by RPiList** [comment]
> Maybe unpopular, but all official domains for a subscribe only email list with unsubscribe links readily available. Certainly not phishing or malware.

It has not been listed because of it's popularity or unpopularity, it has been listed because all domains are so called disguised mail trackers.

Tracking is widely considered as a form of malware so it has to stay on the list.

But will be deleted from phishing, because tracking is not phishing. Could not trace who put it in.

Greetings

**Comment by RPiList** [comment]
> ||flyff.com^
Thx for letting us know. Domain has been removed. Greetings

**Comment by sarimc** [comment]
> > Maybe unpopular, but all official domains for a subscribe only email list with unsubscribe links readily available. Certainly not phishing or malware.
> 
> It has not been listed because of it's popularity or unpopularity, it has been listed because all domains are so called disguised mail trackers.
> 
> Tracking is widely considered as a form of malware so it has to stay on the list.
> 
> But will be deleted from phishing, because tracking is not phishing. Could not trace who put it in.
> 
> Greetings

Thank you. If tracking links alone are eligible for the malware list, one might expect that the other party domains are included as well (they are not). i.e. click.actionnetwork.org, used in exactly the same manner (campaign email tracking links).

What are the sources for your list? One must wonder if there's some sort of astroturfing contribution happening to the source.

**Comment by RPiList** [comment]
> Thank you. If tracking links alone are eligible for the malware list, one might expect that the other party domains are included as well 

If you encounter other tracking domains, you can report them and they will be listed as well.

> 
> What are the sources for your list? One must wonder if there's some sort of astroturfing contribution happening to the source.

I am not a native english speaker so I don't know the term 'astroturfing' but the domains in question are listed on

https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_mail_trackers_justdomains.txt

by the Adguard Team.

Greetings
