### ISSUE TITLE
Overblocking of DynDNS service on crypto

### ISSUE THREAD

**Issue by TotalyNotANoob** [RPiList/specials#1448]
Hello,

with the entry `||ddns.net^` you cover quite a lot legitimate domains as this is a free DynDNS service provided by noip.com
I assume this was added after you noticed some bad subdomains under this same domain but this also hurts anyone using the free DynDNS for legitimate purposes.

**Comment by RPiList** [comment]
Hi,
thx for pointing it out. Domain has been removed. Greetings
