### ISSUE TITLE
Bitfinex ist Okay.

### ISSUE THREAD

**Issue by vonnull** [RPiList/specials#1449]
Hallo,

bitfinex.com gehört nicht in notserious.txt. Es reicht wenn es in crypto.txt ist. Es ist eine ganz normale Börse mit KYC und anderen Regulationskram. Bin da seit Jahren.

Liebe Grüße

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
