### ISSUE TITLE
Wie sammele ich aufgerufene DNS-Requests?

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#145]
Ich möchte gerne mit dem SVPihole DNS-Requests, die nicht blockiert wurden, sammeln.
Danach exportieren (z.B. Excel o.ä.) und nach Häufigkeit der Aufrufe sortieren.
Diese DNS-Anfragen möchte ich dann gerne nach Werbung/ Tracking und ähnlichem durchsuchen und diese Infos gerne teilen.

1.) Wie sammle ich die DNS-Anfragen, exportiere diese und sortiere diese nach Häufigkeit der Aufrufe?
2.) Wollen wir hier eine Liste pflegen nach gut/böse? Die guten könnten dann in die whitelist aufgenommen werden. (Dazu sollten wir noch ein automatisches Upload-Skript (siehe mmonti) erstellen).

Bitte um Feedack.
Danke

**Comment by AleksCee** [comment]
Hi, gesammelt werden die schon im log oder in der Datenbank.
Für das komplette log des Vortages kann man z.b. quick/dirty das machen:

 ./whitelist.sh
   1302 times: spectrum.s3.amazonaws.com
    914 times: fritz.box
    715 times: fireoscaptiveportal.com
    644 times: gateway.fe.apple-dns.net
    637 times: device-metrics-us.amazon.com
    497 times: api-global.netflix.com
    457 times: gspe11-ssl.ls.apple.com.edgekey.net
    439 times: api.eu.amazonalexa.com
    431 times: gsp64-ssl.ls-apple.com.akadns.net
    409 times: content-eu.drive.amazonaws.com
........


Hier der Inhalt von whitelist.sh:

```
#!/bin/bash
awk 'BEGIN{found=0}
        /query\[/ {found=1;host=$6}
        /forwarded|reply/ && found {
                found=0;
                print "times:", host;
        }

' /var/log/pihole.log.1 | sort | uniq -c | sort -nr
```

**Comment by RPiList** [comment]
Hi,

> 2.) Wollen wir hier eine Liste pflegen nach gut/böse? Die guten könnten dann in die whitelist aufgenommen werden. (Dazu sollten wir noch ein automatisches Upload-Skript (siehe mmonti) erstellen).
> 

Ein Liste nach gut/böse haben wir eigentlich schon. die Bösen stehen auf der Liste, die Guten nicht. :-)

Die Whitelist ist "nur" dafür da, die ambivalenten Domains von der Liste der Bösen zu löschen. Beispiel ist da derzeit Youtube.com. Über deren externen Link Redirector wird vermehrt auf Phishing-Seiten verwiesen.  Daher ist YouTube dann auf den Phishing-Listen drauf. Da das aber nicht sinnvoll ist, sorgt die Whitelist dafür, dass der Eintrag dann gelöscht wird.

Die Whitelist in unserem "dev" Verzeichnis ist also keine Empfehlung an die Nutzer diese Einträge ins eigene Pi-hole aufzunehmen. 

Die "Whitelist" sind all die Domains, die nicht auf der "Blacklist" bzw. den verschiedenen Blocklisten stehen.

**Comment by BulldozerPete** [comment]
Dann bitte Vodafone.de in die whitelist aufnehmen. Die ist z.Z. in der DDG-Blacklist.

**Comment by RPiList** [comment]
@BulldozerPete erledigt.

**Comment by BulldozerPete** [comment]
> Hi, gesammelt werden die schon im log oder in der Datenbank.
> Für das komplette log des Vortages kann man z.b. quick/dirty das machen:
> 
> ./whitelist.sh
> 1302 times: spectrum.s3.amazonaws.com
> 914 times: fritz.box
> 715 times: fireoscaptiveportal.com
> 644 times: gateway.fe.apple-dns.net
> 637 times: device-metrics-us.amazon.com
> 497 times: api-global.netflix.com
> 457 times: gspe11-ssl.ls.apple.com.edgekey.net
> 439 times: api.eu.amazonalexa.com
> 431 times: gsp64-ssl.ls-apple.com.akadns.net
> 409 times: content-eu.drive.amazonaws.com
> ........
> 
> Hier der Inhalt von whitelist.sh:
> 
> ```
> #!/bin/bash
> awk 'BEGIN{found=0}
>         /query\[/ {found=1;host=$6}
>         /forwarded|reply/ && found {
>                 found=0;
>                 print "times:", host;
>         }
> 
> ' /var/log/pihole.log.1 | sort | uniq -c | sort -nr
> ```

Danke, aber kannst Du mir die Eingaben im Terminal auflisten?

**Comment by AleksCee** [comment]
Entweder kopierst du den Teil der mit awk anfängt und packst es in die console und führst es aus oder du packst es in eine Datei und rufst diese denn auf. Das sind alles consolen bzw Shell Befehle. Ich verstehe die Frage nicht.

**Comment by AleksCee** [comment]
![152EC18A-071A-4F22-8F62-38A5AA9F60BF](https://user-images.githubusercontent.com/2960655/76705229-c01b2a00-66de-11ea-9ec5-3feb74f3ee9f.jpeg)

Das | Head ist nur dahinter um nur die ersten Einträge für den Screenshot zu zeigen.

**Comment by BulldozerPete** [comment]
Danke.
Ich kenne mich noch nicht mit allen Terminal-Befehlen aus.

**Comment by BulldozerPete** [comment]
Danke hat funktioniert!
