### ISSUE TITLE
False positive docusaurus-app.cloudgems.tech

### ISSUE THREAD

**Issue by remmahad** [RPiList/specials#1451]
Dear all,

i really love your project and the effort you are putting in here :)
Unfortunately one of my applications gets blocked:
`|docusaurus-app.cloudgems.tech^`in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware.

Would be happy if you would unblock the domain, Many thanks!

**Comment by RPiList** [comment]
Hi,
thx for letting us know. Domain has been removed. Greetings.
