### ISSUE TITLE
false positive: meteoswiss-app.ch

### ISSUE THREAD

**Issue by higgs01** [RPiList/specials#1456]
Currently `meteoswiss-app.ch` is being flagged as malware in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware.

This is a legitimate and official swiss weather app and shouldn't be classified as malware: https://www.meteoswiss.admin.ch/services-and-publications/service/weather-and-climate-products/meteoswiss-app.html

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings.
