### ISSUE TITLE
Was fehlt noch für das SVPihole?

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#146]
Was sind die nächsten geplanten Funktionen/Erweiterungen für das SVPihole?

1. Wie wäre es mit einem automatischen Update des Systems? Bin ja nicht so oft bei meiner Oma^^
2. Oder einem Update der Blocklist alle 3 Tage? Gibt es Möglichkeit das Blocklist-Verzeichnis zu syncen? Damit müssen neue Listen nicht manuell eingpflegt werden.

**Comment by RPiList** [comment]
zu 1.: Das Pi-hole automatisiert seine Listen alle 7 Tage automatisch. In der Regel an einem Sonntag morgen.

zu 2.: Ein Update in schnelleren Intervallen als die o.g. 7 Tage kann einfach über crontab  durchgeführt werden. Das sollte kein Problem sein. Die Frage ist, ob das sinnvoll ist. 

Ein kürzeres Intervall bedeutet das Fehler schneller eingespielt werden. Es bedeutet aber auch, dass Fehler schneller wieder mit dem Fix behoben werden...

Blocklist-sync ist mit Pi-hole 4 nicht möglich. Evtl. wird das ja mit Pi-hole 5 eingeführt.

**Comment by BulldozerPete** [comment]
Kürzere Iterationszyklen ermöglichen schnelles Feedback.
Vielleicht sollten wir einen experimentellen und stabilen Zweig aufbauen.

Stabil für Oma und experimentell für Menschen die Euch unterstützen möchten.

**Comment by RPiList** [comment]
Ich glaube zwei verschiedene Entwicklungszweige kriegen wir nicht gestemmt.
Aber künftig ist es sicher cleverer neue Listen der im Unterverzeichnis DEV zu prüfen bevor des in den Blocklisten Ordner wandert. Da kann dann getestet werden. 

Besonders schmerzlich erfahren wir das an der DuckDuckGo Liste. Da sind Einträge drauf, die zwar sicher "tracken", aber die Nutzer i.d.R. trotzdem nicht gesperrt haben wollen.

**Comment by retrogamer7ties** [comment]
Sind in irgend einer Liste sogenannte Abzock Seiten zusammengefasst?
Ich habe heute - trotz PiHole eine geöffnet, die mir "von Google gesponsert" angezeigt wurde.
Die sieht aus wie von der POST/DHL:
post-nachsenden.de
