### ISSUE TITLE
false positive: report-app.com and related domains

### ISSUE THREAD

**Issue by immortaly007** [RPiList/specials#1461]
I manage these domains for a client and there is no malware on it as far as I know.
It's about these domains on malware blocklist:

report-app.com
report-app.dev.gametailors.com
report-app.gametailors.com
report-app.staging.gametailors.com

Is it also possible to determine how the malware flag was reported or where it came from?

**Comment by RPiList** [comment]
Thx for supporting us. Domains have been removed. Greetings
