### ISSUE TITLE
False positive:  api.flatastic-app.com

### ISSUE THREAD

**Issue by LinusHoppe** [RPiList/specials#1462]
The Flatastic app is used to manage shopping list, chores, common budgets etc. for families and shared households.
Currently, the following entry is blocking requests to `*.flatastic-app.com`:

`||flatastic-app.com^`

If there is any need still to block `flatastic-app.com`, you may just unblock `api.flatastic-app.com` which is called by the app.

**Comment by RPiList** [comment]
Thx for supporting us. Domain has been removed. Greetings
