### ISSUE TITLE
False Postitive openairsg.ch (wieder)

### ISSUE THREAD

**Issue by JohnKNess** [RPiList/specials#1463]
Hallo zusammen 

Aus irgendwelchen unerfindlichen Gründen haben es die folgenden Domains/Subdomains wieder in die Liste (malware.txt) geschafft. 

- blog.openairsg.ch
- proto.openairsg.ch
- www.openairsg.ch

Bei der Suche in Pi-Hole werden die folgenden Infos herausgegeben: 

> Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
>   ||blog.openairsg.ch^
>   ||proto.openairsg.ch^
>   ||www.openairsg.ch^

Fragen: 
- Wie kommen die Domains / Subdomains wieder in die Liste? (Siehe Issue #1059)
- Könntet ihr die Domains / Subdomains bitte wieder entfernen? 

Gruss aus der Schweiz

JohnKNess

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
