### ISSUE TITLE
mail.google.com wird geblockt?

### ISSUE THREAD

**Issue by hagezi** [RPiList/specials#147]
Hallo,

warum wird die offizielle GoogleMail URL mail.google.com über die Phishing-Angriffe Blockliste geblockt?

Gruß,
Gerd

**Comment by RPiList** [comment]
Da es innerhalb der letzten 90 Tage von dieser Domain aus Phishing-Angriffe gab. 
Die Domain wurde entfernt.

**Comment by Randlos-bini** [comment]
Hallo, 
google.at
google.ch
funktionieren leider nicht. 

Danke für eure Arbeit!
Roland

**Comment by RPiList** [comment]
Hi,

sorry für die späte Rückmeldung. Das Problem sollte inzw. gefixt sein.
Damit das im eigenen Pihole wirksam wird, bitte die Blocklisten im Pihole
aktualisieren.

Viele Grüße

Am Di., 17. März 2020 um 16:14 Uhr schrieb Randlos-bini <
notifications@github.com>:
