### ISSUE TITLE
false positive ||vrr.de^

### ISSUE THREAD

**Issue by Tinsus** [RPiList/specials#1473]
Hi there.

found a false positive in 
/Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-7-Teil-1

||vrr.de^

blocks away the main public transportation provider in the Ruhrgebiet area.

please remove it from the dataset. beside the possible typo for reaching the a account, the VRR will probably dont setup a lookalike/phising site. [Ignoring the event it gets hacked]

**Comment by RPiList** [comment]
Hi,

thx for supporting our project. Domain has been removed. Greetings.
