### ISSUE TITLE
false positive io.pagopa.it

### ISSUE THREAD

**Issue by 4L3xN3t** [RPiList/specials#1475]
Hi all,
I found some days ago that the two urls "api-app.internal.io.pagopa.it" and "api-app.io.pagopa.it" are in the https://v.firebog.net/hosts/RPiList-Malware.txt list but these addresses are Italian governative web services to manage payment of various public services or taxes used for example by the governative app "IO" (https://play.google.com/store/apps/details?id=it.pagopa.io.app&hl=it&gl=US)
They definitely souldn't be blocked!
can you please remove them from the list?
thank you

**Comment by 4L3xN3t** [comment]
thank you! just to know, what it takes to go online?

**Comment by RPiList** [comment]
Hi,
I am not quite sure what you mean by your question. 
Removal of a domain from our list takes effekt immediately.

If you subscribed to our list through a third party service, it might take longer to update depending on the refresh rate of said third party.

Please make sure to update your pihole lists to load the latest version of our list

Greetings

**Comment by 4L3xN3t** [comment]
ok, understand. I get the list from firebog.net and it says "Updated 19FEB24". So, if I understand correctly, after firebog next update I won't see the two urls in the list anymore. right?

**Comment by RPiList** [comment]
I am afraid not.
From what I see was my update on the 20th. (at 1 am CET).

So firebog.net has to update again to catch it.

**Comment by 4L3xN3t** [comment]
ok, this is a good news, it means there isn't "still" anything not working :)
