### ISSUE TITLE
false positive ...kanzleidrive.de^

### ISSUE THREAD

**Issue by fragkp** [RPiList/specials#1476]
Hey,

I've noticed that our internal testing domain (for our saas project) is on the list.
Please remove it :)

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
`||kd-25-app-api.octopus.kanzleidrive.de^`

Apart from that: Why is this domain come up on this list?

**Comment by RPiList** [comment]
Hi,

thx for supporting our project. Domains have been deleted.

Domain was catched by our crawler because of the current -app scam on the internet. Greetings.
