### ISSUE TITLE
false positive: *.jobstream.io

### ISSUE THREAD

**Issue by dnesteryuk** [RPiList/specials#1477]
Hello, a few our hosts with for `jobstream.io` were added to your list https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware. They have nothing to do with malware.

 - dummy-app.jobstream.io
 - fressnapf-sf-app.jobstream.io
 - fressnapf-sf-sandbox-app.jobstream.io
 - gesobau-sandbox-app.jobstream.io
 - hrworks-sandbox-app.jobstream.io
 - perbit-sandbox-app.jobstream.io
 - tepahead-myhr-sandbox-app.jobstream.io
 - talentsconnect-sandbox-app.jobstream.io

**Comment by RPiList** [comment]
Hi,

thx for supporting our project. Domains have been deleted. Greetings.
