### ISSUE TITLE
false positive: obs.line-apps.com gets blocked breaking media sending in LINE

### ISSUE THREAD

**Issue by Helios747** [RPiList/specials#1479]
https://v.firebog.net/hosts/RPiList-Malware.txt blocks obs.line-apps.com which breaks sending images and video in the very popular IM client LINE.

It is not malware, it's just an endpoint for an IM client popular in Asian countries.

![image](https://github.com/RPiList/specials/assets/6785841/21014c0d-280f-4759-9c94-04db10848ce2)

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings

**Comment by tonklaw** [comment]
@RPiList The domains still exist in https://github.com/RPiList/specials/blob/master/Blocklisten/malware

![image](https://github.com/RPiList/specials/assets/16508743/0bb24f5d-e04a-47f8-b4d1-dc12d252eb4d)

These domains are used in LINE messaging app.

**Comment by Raptime** [comment]
seconding this, line-apps.com is too restrictive and prevents (among other features) receiving/sending messages using line in japan.

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
