### ISSUE TITLE
Dailykos

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1483]
https://en.wikipedia.org/wiki/Daily_Kos

News über die Demokraten in den USA. Sehe ich nicht auf "child protection"

**Comment by RPiList** [comment]
Domain wurde vor Tagen schon entfernt. Sorry für's nicht früher Bescheid sagen. Vielen Dank für die Info. Grüße

**Comment by yoshimo** [comment]
`||dailykos.com^`
ist weiterhin Teil von https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection @RPiList
