### ISSUE TITLE
False positive: chatgpt.gold

### ISSUE THREAD

**Issue by mschabhuettl** [RPiList/specials#1489]
Hallo!

`https://chatgpt.gold/`

ist die Plugin- bzw. die Dokumentationswebsite von dem PyCharm/JetBrains Plugin "ChatGPT - EasyCode"

Siehe hier:

https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode
und
https://github.com/obiscr/ChatGPT

Liebe Grüße,
Matthias

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
