### ISSUE TITLE
ckpool.org ist Okay

### ISSUE THREAD

**Issue by vonnull** [RPiList/specials#1491]
Servus.

Wie kommt diese Domain in die LIste?
solo.ckpool.org ist einfach nur für Bitcoin-Solo-Mining und die ckpool.org ist nicht einmal erreichbar.
Auch die anderen Subdomains sehen für mich normal aus.
https://www.nmmapper.com/sys/tools/subdomainfinder/

Beste Grüße

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
