### ISSUE TITLE
okun.shop

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#1492]
Hallo,

`okun.shop`  ist eine unseriöse Müllseite die gerade über Twitter/X per DM von Fakeaccounts dauergespammt wird. Blockt man einen Account tauchen sie direkt mit einem neuen auf.

https://twitter.com/GemmaCarro33871
https://twitter.com/FCarllyle60244
https://twitter.com/RockMadge616526
https://twitter.com/HudsonJudi48446
https://twitter.com/SpencerRic71952

Die Seite ist unseriös. Sie hat nicht mal eine richtige Startseite, kein richtiges Impressum, alles ist nur mit Google Translator übersetzt und die Kontaktseite enthält nicht mal Daten. Die Hauptdomain wirft nur einen Error, den eigendlichen unseriösen Inhalt findet man über `https://meiguo66.okun.shop/` & `https://de.okun.shop/`. Die Preise sind auch nur irgendwie zufällig ausgewürfelt und unrealistisch, die "x Leute sehen es gerade" zufällig generiert.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
