### ISSUE TITLE
False positive: DVB.de

### ISSUE THREAD

**Issue by andrewille** [RPiList/specials#1494]
Hi,
the domain _dvb.de_ belongs to the _Dresdner Verkehrsbetriebe_ and offers (real time) information about local public transport. It is, for some reason, blocked in [VR-PLZ-2](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-2). Please remove the according entry.
Thanks!

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
