### ISSUE TITLE
False Positive in a major Brazilian bank...

### ISSUE THREAD

**Issue by brunocp76** [RPiList/specials#1495]
Greetings from Brazil!

Using RPiLists in Pi-hole, I noticed it was blocking my bank, Bradesco.

It is one of Brazil's major private banks. It is a false positive.

You can verify this in their Investor Relations webpage: https://www.bradescori.com.br/en/
 (even being a slightly different URL [the "ri" at the end refers to "relação com investidores" - Portuguese for "investor relations"])

I have manually whitelisted it on my Pi-hole, but I kindly suggest you to remove ||bradesco.com.br from this blocking list.

Thanks in advance.

**Comment by RPiList** [comment]
Hi,

can you tell me which list it is, that's blocking bradescori.com.br? 

Greetings

**Comment by LizenzFass78851** [comment]
The domain bradesco.com.br has an HTML redirect to the domain banco.bradesco and the domain contains a fake website of the real bradescori.com.br domain.  I also checked, the domain that contains the redirect to the fake website is in the malware and spam emails list.  The domain with the original website (bradescori.com.br) is not present in the RPiLists blocklists and all lists specified in Blocklisten.md.

**Comment by LizenzFass78851** [comment]
> the domain contains a fake website of the real bradescori.com.br domain.

Didn't know: The domain `banco.bradesco` is linked in [Wikipedia](https://de.wikipedia.org/wiki/Banco_Bradesco) so it's probably real.

**Comment by RPiList** [comment]
So I guess all is swell, because @brunocp76 is not responding. Greetings

**Comment by brunocp76** [comment]
Sorry I took too long to reply.

In fact, the URL *bradescori.com.br <http://bradescori.com.br>* was a link
to the investor relations part of the bank, I was just proving the bank
itself is real.

What was blocked was the URL *bradesco.com.br <http://bradesco.com.br>*.

And yes, I don't know why, but they do redirect to banco.bradesco, in which
we can access our internet banking...

Thanks for solving that fast.

Bruno César Pasquini

Em dom., 10 de mar. de 2024 às 21:27, RPiList ***@***.***>
escreveu:
