### ISSUE TITLE
Fake Hermes SMS

### ISSUE THREAD

**Issue by vonnull** [RPiList/specials#1499]
Hallo,

dienst-hermes.com hat leider meine Daten bekommen, weil ich auch auf ein Paket aus dem Ausland warte. War noch nicht ganz wach. Bei den Kreditkartendaten bin ich stutzig geworden.
Einfach hinzugügen bitte.

Beste Grüße

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
