### ISSUE TITLE
Image verfügt in der Konfiguration über eine festgelegte IP --> ändern zu dynamisch (DHCP)

### ISSUE THREAD

**Issue by Tyberhertz** [RPiList/specials#15]
Moin RPiList,

Habe mir euer Image heruntergeladen und festgestellt, dass der Pi dann über eine feste IP angesprochen werden kann. Um dies zu lösen habe ich folgenden Lösungsvorschlag dazu:

1. NetworkManager installieren:
 apt install network-manager

2. Dienst aktivieren:
systemctl enable NetworkManager

3. /etc/dhcpcd.conf bearbeiten:
```
#interface eth0
#        static ip_address=192.168.111.93
#        static routers=192.168.111.1
#        static domain_name_servers=127.0.0.1

```

Pi neustarten

**Comment by DanielRamp** [comment]
Ich denke das mit den Images klappt so eeh nicht, man müsste eine Art Image Generator machen.

Aber wieso nicht ein Installations script wie bei PiHole selbst?

**Comment by Tyberhertz** [comment]
An sich eine gute Idee.. So viel wie ich weiß, muss Beim ersten Start des Pis irgendwie die PiHole installationsroutine laufen.. was dann automatisch das Netzwerk quasi erkennt und die entsprechenden Einstellungen selbst setzt.. Geht ja darum, dass das für jeden so einfach wie möglich ist..

**Comment by AsumYT** [comment]
> Ich denke das mit den Images klappt so eeh nicht, man müsste eine Art Image Generator machen.

So würde ich es jetzt auch nicht sagen. Wenn man es richtig macht, dass solche Dinge wie die Installationsroutine automatisch im Hintergrund durchlaufen, kann das schon funktionieren. Die IP-Konfiguration muss ja eigentlich nur auf DHCP gesetzt sein.

**Comment by DanielRamp** [comment]
Und das wiederum sollte von jedem selbst bestummen werden, da vielleicht die einen es so mögen die anderen so (Beispiel folgt).
'mögliche' lokale IPv4 Adressen für PiHole 's
Mit den Netzwerk *192.168.1.0/24*:

- 192.168.1.1
- 192.168.1.2 (da .1 für x anderes verwende wird)
- 192.168.1.254
- 192.168.1.100 (DHCP aber Router setzt DNS Server auf den hostname. Geht das evt.?!)

Und so weiter

**Comment by AsumYT** [comment]
> Und das wiederum sollte von jedem selbst bestummen werden, da vielleicht die einen es so mögen die anderen so (Beispiel folgt).

Da geb ich dir recht.

> 'mögliche' lokale IPv4 Adressen für PiHole 's
> Mit den Netzwerk _192.168.1.0/24_:
> 
> * 192.168.1.1
> * 192.168.1.2 (da .1 für x anderes verwende wird)
> * 192.168.1.254
> * 192.168.1.100 (DHCP aber Router setzt DNS Server auf den hostname. Geht das evt.?!)
> 
> Und so weiter

Vom Grundsatz her gut, nur...

> * 192.168.1.100 (DHCP aber Router setzt DNS Server auf den hostname. Geht das evt.?!)

Das geht soweit ich weiß bei den meisten Routern nicht. Es gibt sicher einige Modelle, die das haben. Aber dann müsste man nochmal eine extra Auflistung machen für Router, die das unterstützen, was wiederum bedeutet, dass man das mit den hostnames auch erstmal wieder erklären muss... Das nimmt diesen Grundsatz für die Einfachheit etwas raus finde ich.
Aber als "Erweiterte/Benutzerdefinierte Einstellung" oder Sonstiges wäre das sicher sinnvoll.

**Comment by DanielRamp** [comment]
> > * 192.168.1.100 (DHCP aber Router setzt DNS Server auf den hostname. Geht das evt.?!)
> 
> Das geht soweit ich weiß bei den meisten Routern nicht. Es gibt sicher einige Modelle, die das haben. Aber dann müsste man nochmal eine extra Auflistung machen für Router, die das unterstützen, was wiederum bedeutet, dass man das mit den hostnames auch erstmal wieder erklären muss... Das nimmt diesen Grundsatz für die Einfachheit etwas raus finde ich.

Stimmt, die meisten "Standard" Heimnetzrouter (halt diese Multifunktionsgeräte denen ich eigentlich nicht gerne Router sage) haben diese Funktion sicher nicht.

> Aber als "Erweiterte/Benutzerdefinierte Einstellung" oder Sonstiges wäre das sicher sinnvoll.

Das widerspricht aber jetzt auch wieder dem "möglichst einfach, jeder Standard Benutzer soll es können", denn die Wisser, wissen sowieso (bzw. eine kurzes Handout kann man hier ja machen) wie sie dem eine für sie passende IPv4 Adresse zuweisen.

**Comment by AsumYT** [comment]
> Das widerspricht aber jetzt auch wieder dem "möglichst einfach, jeder Standard Benutzer soll es können", denn die Wisser, wissen sowieso (bzw. eine kurzes Handout kann man hier ja machen) wie sie dem eine für sie passende IPv4 Adresse zuweisen.

Stimmt auch wieder

**Comment by Tyberhertz** [comment]
WIe ich oben schon gezeigt habe, ist es nicht schwer dies umzustellen.. allerdings muss PiHole noch darüber bescheid bekommen, dass sich das Netzwerk geändert hat..

Das ist der Inhalt, die dafür sorgt, wie PiHole installiert wird:

/etc/pihole/setupVars.conf:

BLOCKING_ENABLED=true
WEBPASSWORD=
PIHOLE_INTERFACE=enxb827ebe30843
IPV4_ADDRESS=192.168.45.2/20     <--- Genau der Teil muss geändert werden!
IPV6_ADDRESS=
PIHOLE_DNS_1=9.9.9.11
PIHOLE_DNS_2=149.112.112.11
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true

Wenn man es nun irgendwie schaffen könnte diese Datei immer ändern zu lassen, wenn sich das Netzwerk ändert und dann die Installationsroutine ausgeführt wird..
Folgender Befehl wäre dies um PiHole anhand dieser Datei (muss natürlich vorhanden sein!) zu installieren:

`curl -L https://install.pi-hole.net | bash /dev/stdin --unattended`

Quellen:
https://discourse.pi-hole.net/t/pi-hole-as-part-of-a-post-installation-script/3523/5 
https://discourse.pi-hole.net/t/what-is-setupvars-conf-and-how-do-i-use-it/3533
https://github.com/pi-hole/pi-hole/#one-step-automated-install
https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245

**Comment by Tyberhertz** [comment]
Nach weiteren Tests, habe ich herausgefunden, dass es mit folgender Konfiguration funktioniert:

BLOCKING_ENABLED=true
WEBPASSWORD=
PIHOLE_INTERFACE=enxb827ebe30843
IPV4_ADDRESS=127.0.0.1
IPV6_ADDRESS=
PIHOLE_DNS_1=9.9.9.11
PIHOLE_DNS_2=149.112.112.11
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true

Wir sehen, dass es auch mit der IP 127.0.0.1 funktioniert..

**Comment by RPiList** [comment]
> Moin RPiList,
> 
> Habe mir euer Image heruntergeladen und festgestellt, dass der Pi dann über eine feste IP angesprochen werden kann. Um dies zu lösen habe ich folgenden Lösungsvorschlag dazu:
> 
> 1. NetworkManager installieren:
>    apt install network-manager
> 2. Dienst aktivieren:
>    systemctl enable NetworkManager
> 3. /etc/dhcpcd.conf bearbeiten:
> 
> ```
> #interface eth0
> #        static ip_address=192.168.111.93
> #        static routers=192.168.111.1
> #        static domain_name_servers=127.0.0.1
> ```
> 
> Pi neustarten

Vielen Dank für den Hinweis.

Soweit ich das richtig interpretiere, hat Pi-Hole die PI fix hinzugefügt.  Im Netzwerk hier werden alle Rechner (bis auf wenige Ausnahmen) von einem DHCP-Server mit einer IP versorgt. Aber ich werde Ihren Vorschlag auf jeden Fall prüfen.

Viele Grüße.

**Comment by RPiList** [comment]
Das wird in der nächsten Version 1912 geändert werden.

Vielen Dank und viele Grüße.
