### ISSUE TITLE
Falsche Phishing-Listeneinträge

### ISSUE THREAD

**Issue by waffshappen** [RPiList/specials#150]
Die domain `outlook.live.com` wird für Outlook Mail-dienste und die mobile outlook app benötigt, wird aber auf der phishing-liste geblockt.

Ebenso ist die domain `support.apple.com` auf der Liste, was doch ein paar apple-dienste einschränkt.

Klar sind beide fragwürdig, aber die funktionalität sollte doch vorhanden sein da es keine direkten phish-seiten sind.

**Comment by benjaminbenstein** [comment]
t-online.de, www.paypal.me ist auf Phishing-Angriffe
www.welt.de ist auf DDG-TrackerList

**Comment by RPiList** [comment]
Vielen Dank für die Hinweise. URLs wurden entfernt.

**Comment by Ju200** [comment]
Spotify (spotify.com und deren Subdomains) stehen auch vielen Listen. Manche Domains sind u.U. Tracking Dienste von Spotify oder sind anderweitige Phishing Seiten. Aber aktuell werden zu viele Elemente geblockt. Als Beispiel einfach mal spotify.com aufrufen.
