### ISSUE TITLE
spam site casino-ice.fun

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#1500]
Hallo, ich habe eine Spam E-Mail erhalten mit klar fragwürdigen Domains:

```
casino-ice.fun
```
Die Seite leitet weiter über:

```
fortuneadvert.com
lalielynaualish.com
```

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
