### ISSUE TITLE
False positive for portals-app.com

### ISSUE THREAD

**Issue by tomini** [RPiList/specials#1503]
Hi,
I am fairly certain that portals-app.com is a false positive.
![image](https://github.com/RPiList/specials/assets/41676221/ce583598-0171-4517-9990-7f5657fd683b)

Can you look into it?
https://github.com/Ross-Patterson/Portals-Desktop-Organization

Thanks

**Comment by RPiList** [comment]
Thx for supporting us. Domain has been removed. Greetings
