### ISSUE TITLE
Wrong/Unrelated entry on "DatingSites" Blocklist

### ISSUE THREAD

**Issue by DiogoMiguelCunha** [RPiList/specials#1505]
### Discussed in https://github.com/RPiList/specials/discussions/1504

<div type='discussions-op-text'>

<sup>Originally posted by **DiogoMiguelCunha** March 10, 2024</sup>
Hello,

I've been using your "Blocklisten" for a little while now, and I've just had a wrong/unrelated hit/block.

On the list "DatingSites" ("https://github.com/RPiList/specials/blob/master/Blocklisten/DatingSites"), the entry for "||singlelogin.re^" is not a dating website. The website "https://singlelogin.re/" is the for/from "zlibrary - Your gateway to knowledge and culture. Accessible for everyone."

For reference, I leave its VirusTotal URL Analysis link: "https://www.virustotal.com/gui/url/8bf2ae8457714e6a16440d75fbde71d5b69e1728e532b0fe6da3a1d173f53e84"

Thank you for your work, and hope it helps!
Best regards.</div>

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
