### ISSUE TITLE
Verschiedene Probleme mit VM v2003

### ISSUE THREAD

**Issue by szaimen** [RPiList/specials#151]
1. beim Import der .ova Datei im VM-Player ist standardmäßig beim Netzwerkmodus nicht mehr "Bridged" angegeben sondern "NAT"
2. die IP-Adresse scheint sich nach jedem Neustart zu ändern, was ein verwenden als DNS-Server sehr unzuverlässig macht (nachdem man auf Bridged umgestellt hat)
3. in /etc/network/interfaces steht die Schnittstelle inzwischen 4x?
4. die IP-Adresse, die in der pihole-gui angezeigt wird stimmt nicht mit der überein, die die VM wirklich hat. Hängt das evtl. mit der neuen IP-Adresse pro Neustart zusammen? (nachdem man auf Bridged umgestellt hat)

**Comment by RPiList** [comment]
Fixe ich asap und melde mich.

**Comment by RPiList** [comment]
Bitte mal die neue Version unter http://sempervideo.de/svpiholeVM2004.zip runterladen und testen.

Die Version startet sich nicht neu nach 45 Sekunden. Damit dürfte schon mal das Problem mit der "wandernden" IP erledigen.

Vielen Dank für die Mühen. Viele Grüße.

**Comment by szaimen** [comment]
Ich habs getestet, Problem 1 und 3 scheinen behoben zu sein.

Problem 2 und 4 sind aber immer noch vorhanden.

**Comment by RPiList** [comment]
> Ich habs getestet, Problem 1 und 3 scheinen behoben zu sein.
> 
> Problem 2 und 4 sind aber immer noch vorhanden.

Die zwei Probleme müssten zusammen hängen. Die IP stimmt, nicht (Problem), weil die IP nach jedem Neustart der VM wandert.

Aber da die VM wg. uns gar nicht mehr neustartet, verstehe ich das "wandern" nicht. Wer startet die VM neu? Haben Sie die neugestartet.

Das die VM nach jedem Neustart eine neue IP bekommt, ist ein Problem der Deskstation. Wir hatten das hier auch einmal. Hier wird uns nichts anderes übrig bleiben als beim Hersteller der Deskstation nachzufragen.

**Comment by szaimen** [comment]
> Aber da die VM wg. uns gar nicht mehr neustartet, verstehe ich das "wandern" nicht. Wer startet die VM neu? Haben Sie die neugestartet.

Ja, ich starte die VM neu, um zu gucken ob die IP Adresse stabil bleibt, was sie auf jeden fall sein sollte.

> Das die VM nach jedem Neustart eine neue IP bekommt, ist ein Problem der Deskstation. Wir hatten das hier auch einmal. Hier wird uns nichts anderes übrig bleiben als beim Hersteller der Deskstation nachzufragen.

Meinen Sie das Gerät auf dem ich die VM betreibe? Tatsächlich habe ich das Problem unter v2002 nicht. Außerdem verwende ich den VmWare VmPlayer. Da ich auch eine andere VM damit verwende, die das Problem ebenfalls nicht hat würde ich sagen, dass mit dem Image etwas nicht stimmt...

**Comment by Patsch-Soft** [comment]
Hi. Ich habe das mit den vielen IPVx_ADDRESS Einträgen mit einem kleinen Script (basierend auf dem mylanip.sh aus dem Image und einer Datei setupVars.conf ohne die IPVx... für mich lösen können. Ich baue die kleinen Pi-Holes für Freunde und Bekannte - da kenne ich die IP-Adressen meistens nicht. Vielleicht ist das hilfreich.
Gruß Peter

mylanip.sh

#!/bin/sh
# aus dem Image svpihole2004 von Sempervideo
# einfaches Script zum Anpassen der setupVars.conf
# in der Datei /etc/pihole/setupVars.ohne sind keine IP-Adressen
#
ip4=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | head -n 1)
ip6=$(ip -6 addr show dev eth0 | awk '/inet6/{print $2}')
ip2="IPV4_ADDRESS="
ip3="IPV6_ADDRESS="
/etc/init.d/pihole-FTL stop
wait 5
# vorhandene löschen und IP-Adressen eintragen
rm /etc/pihole/setupVars.conf
cp /etc/pihole/setupVars.ohne /etc/pihole/setupVars.conf
printf "$ip2$ip4"  >> /etc/pihole/setupVars.conf
printf "\n"  >> /etc/pihole/setupVars.conf
printf "$ip3$ip6"  >> /etc/pihole/setupVars.conf
printf "\n"  >> /etc/pihole/setupVars.conf
/etc/init.d/pihole-FTL start

/etc/pihole/setupVars.ohne

PIHOLE_INTERFACE=eth0
QUERY_LOGGING=false
INSTALL_WEB_SERVER=false
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
WEBPASSWORD=
DNSMASQ_LISTENING=single
PIHOLE_DNS_1=127.0.0.1#5353
PIHOLE_DNS_2=
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=false
CONDITIONAL_FORWARDING=false
BLOCKING_ENABLED=true
