### ISSUE TITLE
False positive: nzxt-app-beta.nzxt.com

### ISSUE THREAD

**Issue by LucHeart** [RPiList/specials#1510]
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

NZXT Cam ist die offizielle Software von NZXT für ihre Produkte

Die download url (für die beta) ist unter der Domain `nzxt-app-beta.nzxt.com`. Dieses ist in der Malware-Liste, obwohl das die offizielle NZXT Software ist.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
