### ISSUE TITLE
False positive - *.mobilgov.com

### ISSUE THREAD

**Issue by cochcoder** [RPiList/specials#1512]
This false positive is under the malware block list. This site is used in the US to allow citizens to more easily view and manage legal documents and taxes. I have personally conformed that these sub-address are valid and not malware: 6300-app.mobilgov.com, 5900-app.mobilgov.com, 8443-app.mobilgov.com.

**Comment by RPiList** [comment]
Thx for supporting us. Domains have been removed. Greetings.
