### ISSUE TITLE
Check die mal bitte ab!

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1514]
https://sites.google.com/view/awesome-themes?fbclid=IwAR2DRqO8Kw6DRdCmlbt5OV3eYPcopX-F2lmkEZ9xvaCOAFZVgNWFJ51-Fc0

Die haben sehr viel Werbung auf Facebook und ja ich nutze noch Facebook

**Comment by RPiList** [comment]
sites.google.com können wir nicht sperren, ist halt so ein Webspace-Dienst für jeden von Google. Wenn wir das Sperren, heulen 100 Leute, dass ihre Seite nicht mehr funktioniert. Aber evtl. kann man sich bei Google beschweren, wenn die Seite spamt oder schädlich ist...
