### ISSUE TITLE
Nächste Fake Seite wo man iPhone 15 für 200€ bekommen soll

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1517]
https://shop.uubuuhu.shop/ATiPhone15?fbclid=IwAR1xI5xpIaAU7XqooVC3Tnt3CFQqrOMUJl_Zf9PSZ-2K_e4-tltZ_piZgFk

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
