### ISSUE TITLE
Ebay is blocked by streaming list

### ISSUE THREAD

**Issue by WiredLife** [RPiList/specials#1519]
Cant access ebay.com and ebay.de wont load nearly everything

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming:
  ||ebay.com^

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings.

**Comment by Copy05** [comment]
Hello, That was an error on my side when i tried to add all `piratebay` sites inside the Streaming blocklist. It should now be fixed!
