### ISSUE TITLE
Unblock photosync-app.com

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#1521]
Die Domain photosync-app.com steht auf der Malware-Liste, ist aber eine normale (und nützliche) iOS/Android App. Bitte die Domain von der Blocklist entfernen, danke :)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Damit die Änderung bei Ihnen wirksam wird, müssen Sie Ihre Pi-hole Listen aktualisieren. Viele Grüße
