### ISSUE TITLE
app-prod-static.alertswiss-app.ch

### ISSUE THREAD

**Issue by randomusr2** [RPiList/specials#1522]
[Alertswiss app](https://www.alert.swiss/de/app.html) is getting blocked by the malware list:
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  ||alertswiss-app.ch^

Can't judge why it's on the list, but Alertswiss app not working seems like an issue to me.

Best Regards

**Comment by IngmarStein** [comment]
+1 just noticed the same. It's a Swiss federal emergency notification app and certainly not malware.

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. To take effect you have to update your pi-hole lists. Greetings.

**Comment by randomusr2** [comment]
Thanks! Super fast :)
