### ISSUE TITLE
Mis-pasted lines in Blocklisten/malware?

### ISSUE THREAD

**Issue by nreilly** [RPiList/specials#1526]
Hello,

The below to entries in https://github.com/RPiList/specials/blob/master/Blocklisten/malware seem to be an error.

||2.datado7q.comprocessstreaming.agent.datado7q.comproceagentatin.api.agent.datado7q.comproclient.agent.datado7q.comprocessprofiles.agent.datado7q.comcdn-iress.datado7q.comcdn-stitchfix.datado7q.comprocesspage.api.agent.datadoghq.com^
||2.datado7q.comprocessstreaming.agent.datado7q.comproceagentatin.live-us.agent.datado7q.comproclient.agent.datado7q.comprocessprofiles.agent.datado7q.comproduction-iress.datado7q.comproduction-stitchfix.datado7q.comprocesspage.live-us.agent.datadoghq.com^

**Comment by RPiList** [comment]
Hi,

thx for supporting us.

It is possible to have such long domains. 

But the malware list gets completely rebuild on every update. So if these domains are an error, the provider of our data will fix it sooner or later and the entry will be deleted.

Greetings.
