### ISSUE TITLE
Remnants of quell branches from "revert" pull requests still exist

### ISSUE THREAD

**Issue by LizenzFass78851** [RPiList/specials#1527]
This is probably not taken into account, but I wanted to point out that the source branch still exists for following pull request and it would be better to delete the source [branch](https://github.com/RPiList/specials/branches/all) from pull request #523 and #970. The advantage would be that no legacy files from this pull request are cloned when cloning. You can clone the master branch specifically, but the source branch is no longer needed after the merged pull request has been completed, which would reduce the overall space both remotely and locally (if users clone it).

That may sound exaggerated, but I wanted to point it out anyway.
Because why do the branches “[revert-522-patch-22](https://github.com/RPiList/specials/tree/revert-522-patch-22)” and “[revert-968-master](https://github.com/RPiList/specials/tree/revert-968-master)” exist?

![Screenshot_20240407_122949_Chrome-01](https://github.com/RPiList/specials/assets/82592556/5db03126-5221-4271-96bf-64fda1c4b3e0)

**Comment by RPiList** [comment]
Have been deleted. Greetings.
