### ISSUE TITLE
False positive `mdr.esentire.com`

### ISSUE THREAD

**Issue by pauliusmiskinis** [RPiList/specials#1529]
Reporting false positive for domain `mdr.esentire.com` found under RPiList-Malware

**Comment by RPiList** [comment]
Hi, 
thx for supporting us. 

mdr.esentire.com is a tracking domain, so I'm afraid it has to stay on the list.

mdr.esentire.com leads you to go.pardot.com, which leads you to pi.pardot.com, which leads you to pi-ue1.pardot.com which leads you to pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com

![image](https://github.com/RPiList/specials/assets/56664851/b44f8c39-e803-4d13-b7b4-46cede8be541)
