### ISSUE TITLE
False positive for Ameriprise

### ISSUE THREAD

**Issue by nickp85** [RPiList/specials#1531]
I'm using the Ameriprise Financial mobile app and some functionality is being blocked by one of the lists here.

Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  ||financialwellness.ameriprise.com^
  ||ocs.ameriprise.com^
  ||quarp-app-e2.i.ameriprise.com^

While I'm not 100% sure what all of these do, I'm not sure how the 3 domains directly on Ameriprise Financial's domain landed on a Malware list. Can this be reviewed?

Thank you

**Comment by RPiList** [comment]
Hi, thx for supporting our project.

> ||quarp-app-e2.i.ameriprise.com^

This domain has been removed. False positive. To take effect on your pihole, you need to update your lists.

> ||financialwellness.ameriprise.com^
> ||ocs.ameriprise.com^

These two have to stay on the list. They have been flagged as tracking Domains. Please let us know if encounter any problems.

Greetings
