### ISSUE TITLE
FAKE LIDL Seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1532]
https://websharetday.online/click?key=0ab40f24eb3a7b817169&ad_id=120208386503700346&adset_id=120208386503890346&campaign_id=120208386503630346&ad_name=10&adset_name=D1&campaign_name=A+AT&_adviser=897072532150912&placement=Facebook_Desktop_Feed&fbclid=IwAR01BGStia102HBI7xNZXlnNj2bcEomsKviXNnO24QFSlnQhDugPPGaH8NU

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
