### ISSUE TITLE
Angebliche Online Kurse

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1535]
https://onlinecourse.fun/?kw1=Online-Lernplattformen&kw2=kostenlose+Online-Kurse+mit+Zertifikat&kw3=Kostenlose+Zertifizierungskurse+online&kw4=Kostenlose+akkreditierte+Online-Kurse&kw5=Online-Schule&kw6=Online-Abschl%C3%BCsse&pxfb%5Bid%5D=792132115728895&pxfb%5Bec%5D=Purchase&sub1=%7B%7Bclickid%7D%7D&sub2=120208088476490277&sub3=120208088298660277&network=facebook&site=Facebook_Desktop_Feed&adtitle=Online-Kurs-Push&fbclid=IwAR1HIqvgii3xH6vojXD6FzGSJL_vjt_D-SXF2R_LeeBLjGYQ_0zD2N4BvL8_aem_ATDmsaPP_84eUEW9cGjFBryQvEJ-2bmTkMtO0JTvyJF0-G0TAAjsjBFdGqjkR9IUa7XoHOJv7IdNg2LQvkzqd7ck

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
