### ISSUE TITLE
apple.se auf DomainSquatting1

### ISSUE THREAD

**Issue by ulrichwisser** [RPiList/specials#1537]
Hallo!
Ich weiss nicht genau seit wann, aber zur Zeit kann ich apple.se nicht erreichen. Liegt daran, dass es auf eurer Liste [DomainSquatting1](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1) auftaucht.
Die Domain ist die offizielle Apple Domain für Schweden.
Viele Grüße aus Stockholm
/Ulrich

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
