### ISSUE TITLE
Spam SMS

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#1538]
Heute habe ich folgende Spam SMS erhalten:

`Das DHL-Paket ist im Lager eingetroffen und kann aufgrund unvollstandiger Adressangaben nicht zugestellt werden. Bitte bestatigen Sie Ihre Adresse im Link innerhalb von 12 Stunden.

https://dhl-postcd.top/track

(Bitte antworten Sie mit Y, beenden Sie dann die SMS, offnen Sie den SMS-Aktivierungslink erneut oder kopieren Sie den Link in den Safari-Browser und offnen Sie ihn) 

Das Team von DE Postal wunscht Ihnen einen schonen Tag`

Bitte die Domain dhl-postcd.top in eine passende Blocklist aufnehmen.
Danke

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
