### ISSUE TITLE
Inclusion domain mbcmap-dev-app.corpinter.net in https://v.firebog.net/hosts/RPiList-Malware.txt.

### ISSUE THREAD

**Issue by vicenteIbermaticaMercedes** [RPiList/specials#1543]
Hello, 
I am part of the development team of the application hosted in domain mbcmap-dev-app.corpinter.net.
I would like to ask you for information about the reason for the inclusion of this domain in the list.

I am not saying that the inclusion is not correct, but I am not able to identify the reason why it has been included and we would like to have information to try to solve it.

**Comment by RPiList** [comment]
Hi, 

thx for supporting our project. Domain has been removed.

Reason for adding it in the first place was our crawler, searching for domains matching the so called -app scam schema.

Greetings
