### ISSUE TITLE
Inclusion Domain https://michaelfacts.org/

### ISSUE THREAD

**Issue by blackerking** [RPiList/specials#1544]
Another one of AI-Trade Scam:
https://michaelfacts.org/

THis time no Günther Jauch nor Jeff Bezoz.
Michael Mittermeier... 😵‍💫 

https://michaelfacts.org/land/?offer=Wealthy%20Digital%20AI&cep=iSpAYx8wqGgj-1cwufsqB_ApJBST_WFKsB62QWz6MO62hwsrlFtHUzJltxWn0AsfGbbQxycB-ycw6JzEmc_W9eRaAJNDxIW43Z1ZEL97abXwhOtGG0NpCqEbOVsFLHdQ7GDd8F8Bek2XREhWrA_H5wcqx2ug53JI2njShtO8YZIUoSSf0nAlVxcvInJSQlp2qN91u4DTArHGWtl07QK4gdEulkiNANWaJV9AnKbNJeZ7-2o_j1CuDhnVycs56XoOVdCZ7kO-4e1RkrozrS93XEpYAtxEUl96Kuw3wzsnY-WRMzpsDo-W0DAeRsfh_GMH124UEEpX0Iyq0e8N9ydQK2Xh6CX6w4x0aBk4uoaXLsZJpSMQpnzoFi6N5fUIx-xictWBdLY0jdV0eKYuIbapFh4Hyju3kU9IiHZmakeImVD_SShQe8NMaD0-Cg_dgwfF7LzCTSfduIoX_tI3LVwqe2mxb5WFqB-YyHW0oz5_gHSHUbJr2rkB5wTN9NF-tGK3&lptoken=1796134c52a178a19670&eng_click=c62399a0fdb443c394ebf6f7279c9d50&eng_creative_id=1025113833&eng_post_id=1025113833&eng_source=216404&eng_subid=null&eng_website_id=216404&eng_widget_id=230651

Found on MSN Startsite

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
