### ISSUE TITLE
Fake Seite die irgendwlechekurse anbeitet

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1546]
https://free-onlinecourses8.life/?kw1=CNA-Zertifizierung+online&kw2=CNA-Kurse+online&kw3=CNA-Kurse+in+meiner+N%C3%A4he&kw4=4-w%C3%B6chige+CNA-Kurse+online&kw5=CNA-Zertifizierung&kw6=CNA-Kurs+online&pxfb%5Bid%5D=1084313956028901&pxfb%5Bec%5D=Purchase&sub1=%7B%7Bclickid%7D%7D&sub2=120209625068700119&sub3=120209625068670119&network=facebook&site=Facebook_Desktop_Feed&adtitle&fbclid=IwAR1rjseZpu58Xeuz_7wHIERvqZNIUxKWQoV6vXaVmDBSvbYQVZ35Vtx8VSI_aem_AR5PtY4cnJPhYAMZ0Zb-L7V1VUjb9BE30M-0Jrm6lPc04_KThw-SjY-a-kRKkJJJEWDNq4Hh9nqnmZvN4Nkcvukp

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
