### ISSUE TITLE
solo.ckpool.org

### ISSUE THREAD

**Issue by vonnull** [RPiList/specials#1547]
Hallo,

wie schaffen es normale Seiten wie *.ckpool.org oder die österreichische Firma bitpanda, die sogar mit FC Bayern Werbung macht, überhaupt auf die crypto Liste? Ich dachte sie soll mich vor Scamgammel beschützen und nicht legitime Seite sperren,

Grüße

**Comment by RPiList** [comment]
Domains wurden entfernt. Viele Grüße
