### ISSUE TITLE
Clarification of entry in malware list: divesoft-app.foxmedia.cz

### ISSUE THREAD

**Issue by jakubhecko** [RPiList/specials#1548]
Hello,

can you clarify the reason you are listing a "divesoft-app.foxmedia.cz" as a malware site ?
It is a service supporting a website and a smartfone application with absolutely no ties to malware or other stuff.
It may contain some STMP features (I will need to check that with the developers), but definitely not any spam stuff.

Since blocking this website/service essentialy blocks any communication of the DivesoftApp, which makes eg. firmware update in a dive computer impossible.
https://play.google.com/store/apps/details?id=com.divesoft.divesoft_app

Best regards,
Jakub Hecko

**Comment by RPiList** [comment]
Hi, 
thx for supporting our project.

The domain has been removed.

It was catched by our crawler because of the ongoing -app scam on the internet Greetings.
