### ISSUE TITLE
tousanticovid ist staatlich

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1552]
`||tousanticovid.gouv.fr^` , oder präziser ```app-static.tousanticovid.gouv.fr``` wird von der Französischen Corona Tracking App benötigt um im Netz zu prüfen ob Kontakte die man hatte eine Infektion gemeldet haben.

Das zu blockieren ist kontraproduktiv.

**Comment by RPiList** [comment]
Domain wurden von der Liste entfernt. Viele Grüße
