### ISSUE TITLE
Fake Hermes Seite

### ISSUE THREAD

**Issue by Surferr0815** [RPiList/specials#1554]
https://myhermes-sendungs.com/

Dies ist eine Fake Hermes Seite bei der versucht wird mit einem Fake-Paket Zollgebühren zu erheben.

**Comment by iam-py-test** [comment]
I get a 404 response code and an empty response when going to their homepage.
Is there a specific URL used by this phishing website?
Thanks

**Comment by RPiList** [comment]
Thx for reporting. Domain has been added. Greetings

**Comment by Surferr0815** [comment]
@iam-py-test I think some source ips are blocked by them. Tor seems to be blocked aswell

**Comment by iam-py-test** [comment]
I get 404 for that URL too, so probably they are blocking the online sandbox I use.
Thanks anyway
