### ISSUE TITLE
Domain has been reported as spaming. Removal not possible. Greetings

### ISSUE THREAD

**Issue by KundKMC** [RPiList/specials#1555]
We host this domain and I can definitely guarantee that no spam is sent here, only GDPR-compliant mail traffic. I have tried to understand why this domain was declared this way. Where does this message come from? It is definitely a false positive and I need to investigate further. I would like to ask you again to remove it from the list. If the message comes from "external it would be helpful to let me know where from, so I can get to the bottom of it!

              Domain has been reported as spaming. Removal not possible. Greetings

_Originally posted by @RPiList in https://github.com/RPiList/specials/issues/1551#issuecomment-2081219184_

**Comment by RPiList** [comment]
> We host this domain and I can definitely guarantee that no spam is sent here, [...] It is definitely a false positive and I need to investigate further. 

As already stated, domain was reported for spaming, which negates a false positive.

I will check the source of reporting. If this is not conclusive we will do a one time domain removal. If the domain is still spaming, it will most likely be reported again.

Greetings.

**Comment by KundKMC** [comment]
Vielen Dank. Ich finde es sehr wichtig diesen Dingen auf den Grund zu gehen, denn solche "Reportings" können ja auch missbräuchlich verwendet werden. Und dann fragt man sich, warum es Probleme bei der Mailzustellung gibt. Deswegen muss ich solchen Dingen nachgehen. Insbesondere dann, wenn überhaupt dein SPAM vorliegt. 

Ich den verlinkten Datenbanken haben ich Abfragen gemacht, aber ohne Ergebnis. Ich bin auf Updates gespannt.

**Comment by RPiList** [comment]
Eine Falschmeldung können wir ausschließen. Schon alleine, weil es früher oder später auffällt.
Domain wurde entfernt. Viele Grüße
