### ISSUE TITLE
false positive |chatgpt.com^

### ISSUE THREAD

**Issue by thewriteway** [RPiList/specials#1556]
|chatgpt.com^
This is an official redirect address used by OpenAI ChatGPT. 
https://openai.com/

**Comment by p1r473** [comment]
yup, this. had to whitelist it on my end.

**Comment by KundKMC** [comment]
Same in #1555. Any idea where the false postive came from in the first place? I want to investigate, why this happens and where the data is coming from.

**Comment by ikheetjeff** [comment]
yep! Mentioned it also here https://github.com/r0xd4n3t/pihole-adblock-lists/issues/1

this domain seems to have been in the wrong hands at first

https://domaininvesting.com/openai-secures-chatgpt-com/

**Comment by RPiList** [comment]
Domain has been removed. Was on the list because ist was a malware site, like @ikheetjeff said.

If you want to know more, check out:  https://web.archive.org/web/20230310175728/https://chatgpt.com/#/
