### ISSUE TITLE
companisto - False Positive

### ISSUE THREAD

**Issue by muellerfabi** [RPiList/specials#1560]
Hallo zusammen,

companisto.com is wohl fälschlicherweise auf der Liste gelandet.
Es handelt sich um seriöses ein Unternehmen, welches privaten Personen ermöglicht in Startups zu investieren.

https://github.com/RPiList/specials/blob/master/Blocklisten/notserious#L13418
Bitte entfernen

**Comment by KundKMC** [comment]
Hi, ich habe in #1555 genau das gleiche Problem. Ich verstehe nicht, wie solche Domains immer wieder landen können. Unser Projekt wurde aber als SPAM deklariert. Hast Du Info darüber, wo der Eintrag bei euch her kam?

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße

**Comment by RPiList** [comment]
> Ich verstehe nicht, wie solche Domains immer wieder landen können. Unser Projekt wurde aber als SPAM deklariert. Hast Du Info darüber, wo der Eintrag bei euch her kam?

Jede Liste hat "eigene" Quellen warum Domains auf den Listen landen.

Auf der Malware-Liste laden Malware Domains. So wie "chatgpt.com"  (aus Issue #1556) ursprünglich Malware verbreitete und deswegen auf der Liste landete. Es sind fast 2000 Domains in der Malware-Liste, die sich als "chatgpt" ausgeben. Wenn die Betreiber dann merken, dass sie erkannt wurden, richten sie eine Weiterleitung ein. In seltenen Fällen wird eine Domain vom Rechteinhaber übernommen.

Auf der Liste "notserious" landen Domains, die in sog. "Abzocker-Foren" gemeldet werden. Wir erhalten die Domains von den Foren, von Rechtsanwälten, vom Verbraucherschutz u.v.a..

Die Spamliste erhält ihre Einträge von Nutzern die sich hier melden und über Spam beschweren sowie aus entsprechenden Foren im Internet die eine Domain als Spamer melden. Es ist die schwächste Form der Liste. Es ist nur Spam.

Spam-Domains sind nicht immer Malware (sonst wären sie auf der Malware-Liste) oder von Abzockern, sonst wären sie auf der "notserious" Liste.

Viele Grüße
