### ISSUE TITLE
false-positive: inspirationclub.pl

### ISSUE THREAD

**Issue by rotkiW285** [RPiList/specials#1564]
### Domain(s)

```shell
api.inspirationclub.tdy-apps.com
```

### Reason

With this blocked domain, it is not possible to log in to the loyalty program inspirationclub.pl

### Which blocklists

```shell
Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  ||tdy-apps.com^
```

**Comment by RPiList** [comment]
Domain has been removed. Greetings
