### ISSUE TITLE
false-positive: meister.co and meisternote.com

### ISSUE THREAD

**Issue by oanushka** [RPiList/specials#1565]
### Domain(s)

```shell
email.accounts.meister.co
email.staging.meisternote.com
email.meisternote.com
```

### Reason

I'm a security engineer at Meister (productivity tool SaaS company that owns both domains) and there's no reason why the domains should be there. It would be very useful to know the entries got on the list so we can take action if there is a problem on our side. Thank you (also awesome work with the project!) 

meister.co
- https://www.virustotal.com/gui/domain/meister.co

meisternote.com
- https://www.virustotal.com/gui/domain/meisternote.com

### Which blocklists

```shell
All domains match found in https://v.firebog.net/hosts/RPiList-Malware.txt
```

**Comment by RPiList** [comment]
Hi,

Domains are flagged as combined disguised mail trackers, so removal is not possible. Removal will happen automatically when it is no longer flagged as combined disguised mail tracker.

Greetings
