### ISSUE TITLE
false-positive: 

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1569]
### Domain(s)

```shell
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4:
  ||xxxlgroup.com^
```

### Reason

Diese Domian gehört der XXXLutz Gruppe einen Konzern der in Österreich Möbelhäuser betreibt und kein Porn ist, 

PS, die neue Seite zum Domians melden ist echt nicht schön, früher war Sie besser

### Which blocklists

```shell
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4:
  ||xxxlgroup.com^
```

**Comment by RPiList** [comment]
Domain wird gleich entfernt, vielen Dank für den Hinweis.

Die neue Domain-Meldeseite ist noch in der Entwicklung und ehrlich gesagt kenne ich die alte Version nicht. Aber die neue Version sieht auf jeden Fall funktional aus. 

Ansonsten immer Feedback was noch nicht perfekt ist, dann können wir schauen, ob wir das anpassen können. 

Viele Grüße
