### ISSUE TITLE
false-positive: 

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1570]
### Domain(s)

```shell
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1:
  ||all.com^
```

### Reason

Diese Domian wird von der accor.com Hotelkette zuder alle Ibis, Ibis Budget und noch ein paar mehr gehören verwendet, Sie ist kein DomainSquatting da Sie in jeder E-Mail von accor.com verwendet wird um z.b. Bilder einzubetten in der E-Mail

### Which blocklists

```shell
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1:
  ||all.com^
```

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
