### ISSUE TITLE
false-positive: 

### ISSUE THREAD

**Issue by Julian0021** [RPiList/specials#1571]
### Domain(s)

```shell
chatgpt.com
```

### Reason

the legitimate ChatGPT website by openAI

### Which blocklists

```shell
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  ||chatgpt.com^
```

**Comment by RPiList** [comment]
Domain has been already removed a few days ago. Please update your list to take effekt. Greetings.
