### ISSUE TITLE
false-positive: nachdenkseiten.de

### ISSUE THREAD

**Issue by ninagrosse** [RPiList/specials#1572]
### Domain(s)

```shell
nachdenkseiten.de
```

### Reason

Die NachDenkSeiten sind ein Blog, auf dem politische und gesellschaftliche Themen kommentiert werden. Eine legitime Seite, die viele Menschen regelmäßig lesen.

```
~/RPiList/specials/Blocklisten
❯ fgrep nachdenkseiten *
child-protection:||nachdenkseiten.de^
```

### Which blocklists

```shell
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection
```

**Comment by thkoch2001** [comment]
Die nachdenkseiten wurden von Commit [268aea3a466](https://github.com/RPiList/specials/commit/268aea3a466e9f5b40d36ba1baedc2dcc3851794) am 31.3.2024 hinzugefügt. Der Commit fügt allerdings insgesamt acht Domains hinzu:

- 2020news.de
- achgut.com
- apolut.net
- clubderklarenworte.de
- multipolar-magazin.de
- nachdenkseiten.de
- rubikon.news
- uncutnews.ch

Die Domains werden zu zwei Dateien hinzugefügt:

- Blocklisten/child-protection
- DNSMASQ/child-protection

Alle Domains verweisen auf alternative Nachrichtenseiten.

Die Commit-Message lautet "Auto-Update" und ich konnte nicht herausfinden, was die Motivation für die Sperrung war.

**Comment by ninagrosse** [comment]
Gibt sogar ne Diskussion zu dem Thema: https://github.com/RPiList/specials/discussions/1464

**Comment by RPiList** [comment]
Hi, vielen Dank für die Meldung.

Grundlage für die Aufnahme in die Liste war die Quelle https://de.wikipedia.org/wiki/NachDenkSeiten. Demnach liegt hier kein "False Positive" vor.

Danke für den Hinweis von @ninagrosse zu der Diskussion. Insoweit werde ich weitere Infos dort posten.
