### ISSUE TITLE
false-positive: pokerogue.net

### ISSUE THREAD

**Issue by DerMilchmann** [RPiList/specials#1577]
### Domain
`pokerogue.net`

### Reason
Eine RogueLite Mod für Pokemon, warscheinlich automatisch hinzugefügt durch das Teilwort "Poker", also Glücksspiel.

### Blocklist
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
