### ISSUE TITLE
mvg.de is a Transport Company from Munich / FalsePositive

### ISSUE THREAD

**Issue by ArnaudFeld** [RPiList/specials#1578]
Hey,

the Website mvg.de where you can look for traveling in and around Munich is wrong on the two Blocklists:

 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-5-Teil-1:
   ||mvg.de^
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-6:
   ||mvg.de^

thank you

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings
