### ISSUE TITLE
Fake Zahnimplantes Seite angeblich von der Regirung

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1587]
https://implantedteeth-5.online/?kw1=Zahnimplantate%20in%20meiner%20N%C3%A4he&kw2=Implantate%20in%20meiner%20N%C3%A4he&kw3=Zahnimplantologe%20in%20meiner%20N%C3%A4he&kw4=Zahnimplantate&kw5=Zahnimplantate%20und%20Implantate&kw6=ein%20Zahnimplantat&kw7=Zahnimplantat%20mit%20klarer%20Wahl&kw8=erschwingliche%20Implantate%20in%20meiner%20N%C3%A4he&kw9=Zahnersatz&adtitle=Zahnimplantate%20in%20meiner%20N%C3%A4he&sub1=%7B%7Bclickid%7D%7D&sub2=120207625087370133&sub3=120207625087560133&network=facebook&site=Facebook_Desktop_Feed&pxfb%5Bid%5D=817294033470608&pxfb%5Bec%5D=Purchase&fbclid=IwAR2VlN4Z6M84_3H59QpcVlXivtOoqPI9pOEQ02R5hDXlGyB4A0N5WWw1czY_aem_AU_v_U8ehnJ8FqPwoz0HU8OMCAZDTxWy1ADFchgQlBAn9m1TQVAdF-JnjCVF4z06ZEYN0GyP_NDY3TN-b8vgJkS7

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde der entsprechenden Liste hinzugefügt. Viele Grüße
