### ISSUE TITLE
False positive: IHK-Prüfungsportal wird blockiert fw.cic.cc

### ISSUE THREAD

**Issue by HendrikF** [RPiList/specials#1588]
Die IHKs betrieben unter `fw.cic.cc` ihr Online Prüfungsportal. Die URL ist absolut nicht nachvollziehbar und lässt keine Rückschlüsse auf eine Legitimität zu, aber die Adresse wird in offiziellen Briefen der IHK angegeben. In dem Portal werden Prüfungsanträge und -ergebnisse hochgeladen und Termine kommuniziert.

Die Domain `cic.cc` selbst wirkt auch nicht gefährlich, das scheint der Dienstleister zu sein, der das Portal für die IHKs entwickelt und betreibt.

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/CH/CIC:
  ||cic.cc^
```

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
