### ISSUE TITLE
Notepad++ in der 'malware' Liste

### ISSUE THREAD

**Issue by DerBaM** [RPiList/specials#159]
Wie der Titel sagt, steht die Notepad++ Adresse in der 'malware' Liste:

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
   notepad-plus-plus.org
   www.notepad-plus-plus.org

Nichtsdestotrotz, danke für die ganze Arbeit, schöne Listen die ich gerne nutze.

**Comment by RPiList** [comment]
Vielen Dank für Ihre Mühen.

Der Eintrag wurde der Whitelist hinzugefügt und von der Malware Liste entfernt. Vielen Dank und viele Grüße.
