### ISSUE TITLE
Fake Lidl Gewinnspiel

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1590]
https://prizeform.pro/click?key=6c82d21d8f3e48c8e95d&ad_id=120205747605070609&adset_id=120205747605110609&campaign_id=120205747605060609&ad_name=127DimaBU_Cruz_AT_Car_Kris2&adset_name=127DimaBU_Cruz_AT_Car_Kris2&campaign_name=127DimaBU_Cruz_AT_Car_Kris_1&_adviser=1426076468154513&placement=Facebook_Desktop_Feed&utm_medium=paid&utm_source=fb&utm_id=120205747605060609&utm_content=120205747605070609&utm_term=120205747605110609&utm_campaign=120205747605060609&fbclid=IwAR2KYiaOdTgsdf9wvW_0OmnoOaTdQYq7i877fIN7rcJmBgL8nqgLdplNbEc_aem_AXxl6B66VEVMB8QGrWHw26_4SifNaa1_gpZeUDk7WOL9Q70TaXw0eBVWD4mywTxHkDFyRaZNQ1zcyeDPydWF20DS

https://jq.igxrn.shop/R1109hxZ?utm_medium=paid&utm_source=fb&utm_id=120210063569810100&utm_content=120210063570020100&utm_term=120210063569910100&utm_campaign=120210063569810100&fbclid=IwAR30Lv94UxMNHRgFjzWIvJWwiPNf5XlWXRRHBihLgDiRJbzKw1B0clDre2c_aem_Aek6Z_QWU1nj5l-req5iaMw8by9jwQGSJTo2JcCSLehYSQTNgt1ntyIce3wHa7P5v2Zr7SVT_XYfa_fUWkp97zua

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
