### ISSUE TITLE
Fake Hofer Seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1593]
https://shop.kktkkfk.shop/ATSW20?fbclid=IwZXh0bgNhZW0CMTAAAR3Di96ilgN0mKav34wUX8JH1kR-96-cZkoIAa6N9_7_MzMVMDNBpMHCM1E_aem_AelYyrBps7eIyduD-su6Ry8HNy4F_jzQwRd3vFVPZ_v43KwfFw76AKn0iERtIPgEIS228zHc-VpIG9ekwtS-lm4x

https://shop.cccwssd.shop/ATSWAROVSKI19?utm_medium=paid&utm_source=fb&utm_id=120209939537860299&utm_content=120209939538750299&utm_term=120209939540780299&utm_campaign=120209939537860299&fbclid=IwAR3OUuLnVKBZkPqrIenRmiiHno2HU1WALdl5mPpduqWRiO9qPI00QOhTZSw_aem_AemDRHIFdUW8qTk9SN748kcquoubwY18g3cpr41btwl0QIyE3h01p9C38r-jGpJgHV5JwF0kWlG2pLyXJCiPw2Px

**Comment by RPiList** [comment]
Vielen Dank. Domain wurde hinzugefügt. Viele Grüße
