### ISSUE TITLE
Fake Geld verdoemn app

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1595]
Auf Facebook wird damit geworben das Österreich damit sehr schnell Geld machen können
https://shiverion.store/?pixel_id=929942152005349&sub1=%7Bsub1%7D&sub2=AT34&sub3=%7Bsub3%7D&sub4=%7Bsub4%7D&sub5=%7Bsub5%7D&sub6=%7Bsub6%7D&sub7=ATPlinkMe&utm_medium=paid&utm_source=fb&utm_id=6556975881194&utm_content=6557214553994&utm_term=6557214553194&utm_campaign=6556975881194&fbclid=IwAR3YnwaS3Zoo1o4PEJWyMVGAPVjL8VJAOQvKWkh5FOSvmfSxWub_e2328bw_aem_AW12Yk98uypBU6Pb_mPEoIg1bAL2kytc4K0MuEx0PNnV9E46dpIdDU8v4B-b0iwiT0x4MUbvU4ggGxYTkxzq0LY7

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
