### ISSUE TITLE
Possible Issue: "Proxies" Blocklist

### ISSUE THREAD

**Issue by DiogoMiguelCunha** [RPiList/specials#1596]
Hello,

As I'm unsure of your intentions behind the "proxies" Blocklist:
- If it's meant to filter all proxy-like websites, please disregard this issue.
- If it's meant to filter only suspicious/malicious websites, then these 2 entries should be removed, since they're for the official website of the Tor Project/Browser, which isn't malicious:

"torproject.org"
"www.torproject.org"

Thank you for your work and lists.

**Comment by RPiList** [comment]
Hi,

yes, proxy blocklist is meant to block all proxies and proxy like services. Often used by schools or other entities to make sure nobody accesses unwanted websites. 

Greetings
