### ISSUE TITLE
Sparkassen-Phishing

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1597]
Hallo,

aktuell werden die Domains

sparkasse-pushtan2.info
spkreaktivierung2376.xyz

für Phishing auf Sparkassen-Kunden verwendet.

Die erste Domain wird in SMS verwendet.
Von dort wird auf die xyz-Domain weitergeleitet.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
