### ISSUE TITLE
[false-positive]: storage.bunnycdn.com

### ISSUE THREAD

**Issue by LucHeart** [RPiList/specials#1598]
Domain: storage.bunnycdn.com
In liste: malware

Das ist die [API/service domain von BunnyCDN](https://docs.bunny.net/reference/storage-api), das ist keine maleware.

**Comment by mchawk777** [comment]
URL seems to be deleted in any adlist.

**Comment by LucHeart** [comment]
looked it up, fixed in https://github.com/RPiList/specials/commit/2984d55f959f3a5f13caf1fbd2f4c67179b3a9b3

**Comment by RPiList** [comment]
Yeah, it got fixed days ago, but I didn't close the issue. Thx and greetings.
