### ISSUE TITLE
Angebliche Geld Generiren App

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1599]
https://shiverion.store/?pixel_id=929942152005349&sub1=%7Bsub1%7D&sub2=AT44C&sub3=%7Bsub3%7D&sub4=%7Bsub4%7D&sub5=%7Bsub5%7D&sub6=%7Bsub6%7D&sub7=ATPlinkMe&utm_medium=paid&utm_source=fb&utm_id=6556975881194&utm_content=6557744494194&utm_term=6557744493594&utm_campaign=6556975881194&fbclid=IwAR2eJWajejXcnj8Zxklkni1wXKY7BfuatTl-x-jpjtaR4oFv1JgNeYoD5cA_aem_AdbwaKLlSUledXXDeZQlkwOzj9zR_7cIf8tG5U6VdV4wlESwHr-NIs0b410WUzrPwEoIQy5aJhcEQX9giSTU-wya

**Comment by mchawk777** [comment]
URL befindet sich jetzt auf der notserious-Liste.
