### ISSUE TITLE
Was würde passieren wenn der Raspi offline gehen würde?

### ISSUE THREAD

**Issue by arca20** [RPiList/specials#160]
Hallo zusammen,

was würde passieren, wenn mal der Raspi ausgehen würde oder die SD-Karte defekt geht, dann hätte ich ja kein zugriff mehr ins Netz. Früher hatte ich die IP des Raspis via Internetzugang vom Fritzbox eingetragen mit einer alternativen, dort ist das Problem, da ich die IP nicht auflösen konnte,d.h die Clientanzeige zeigt nur denn Router. Kann mal denn Raspi eine alternative IP geben, wenn sie mal ausfallen sollte.

Grüße
arca20

**Comment by RPiList** [comment]
In unseren Anleitungen haben wir gezeigt, wie man den Pi im Netzwerk bekannt macht. Die Schritte einfach Rückgängig machen und im Netz läuft wieder alles. Dauer ca. 2 Minuten.

Wer das nicht möchte, kann eine Backup-Micro-SD-Karte vorrätig halten. Strom raus, neue Karte rein, Strom rein, dauert ca. 60 Sekunden.

Wir arbeiten jetzt seit 7 Jahren mit dem Pi. Noch nie ist ein Pi in den 7 Jahren ausgefallen. 1x ist eine SD-Karte ausgefallen. Es ist klar, dass eine SD-Karte (genauso wie Festplatten oder SSD-Platten) irgendwann ausfallen wird. Das liegt in der Natur der Sache. Also dann entweder direkt ne neue Karte rein oder die Einstellung im Router zurück nehmen.
