### ISSUE TITLE
[false positive] notserious -> ika.com

### ISSUE THREAD

**Issue by Tinsus** [RPiList/specials#1601]
ika.com is a serious manufacturer of laboratory devices.
ika.com.au seems not to belong to ika.com

**Comment by mchawk777** [comment]
Yes - two entries in "notserious":

||ika.com^
||ika.com.au^

ika.com sind jedenfalls die [dt. IKA-Werke](https://de.wikipedia.org/wiki/IKA-Werke).

ika.com.au seems to be gone offline.
achive.org seem a.t.m. to busy got operate my request on this domain. 🤔

**Comment by RPiList** [comment]
Domain has been removed but not put on the whitelist, since it is unclear how it got added in the first place.

Greetings.
