### ISSUE TITLE
email.mg.replit.com

### ISSUE THREAD

**Issue by rotkiW285** [RPiList/specials#1603]
Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  ||email.mg.replit.com^

With this blocked domain I can't reach to password reset site of replit.com

**Comment by RPiList** [comment]
Domain is listed as Malware because it is a disguised mail tracker.

**Comment by RPiList** [comment]
Source is https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_mail_trackers_justdomains.txt

You might want to tell the volks at replit.com to stop tracking or they might want to take it up with the Adguard-Team. 

Greetings.
