### ISSUE TITLE
Irgendwas mit angebliche Apotheken Kurse

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1605]
https://apotheken-coach.de/workshop/?utm_medium=paid&utm_source=fb&utm_id=120210286734990155&utm_content=120211375491110155&utm_term=120211375491080155&utm_campaign=120210286734990155&fbclid=IwAR3ati5ngV3kiGKML04Rs-M732x3wvLWlroXZ6wxp_LQ755SHFw4ZZNirOg_aem_Afpoq8wUWh8pqO3wkgbR0C8V2jiZQq4h-LccNxoTZVStiyYugYorjoe3_E7D_GdWzVxPNseklxDu81l2OE0MZKUE

**Comment by RPiList** [comment]
Passt auf keine Liste. Ist kein Scam, keine Schadware....
