### ISSUE TITLE
Fake News Seite carrollmi.com

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1606]
https://carrollmi.com/blog-julia?utm_campaign=AT+25%2B&fbclid=IwAR1qeGELdQrF8GHnH504ikCjol0ANSKG1o76nISEZi8-AxyYwFEK9-x-mmk_aem_AfoNLfxgMGcfnlUi5LoDpe0s5OwcTHQUHR2mN-5FQPcW_5Lylz_XqqCrOOpL4l32XG864y6eHaRY5Uepa5spCLCs&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120208648544250527&adset_id=120208648544280527&ad_id=120208648544350527&adset_name=Manual+%7C+25%2B+%7C+All+LNG%7C+FB+%7C+Fresh&ad_name=1.1&aff_sub4=784233320501523

**Comment by RPiList** [comment]
Inwieweit ist das Fake-News? 

Finde dort nur irgendwas von wegen "Yoga hat mein Leben gerettet". Nix kritisches...
