### ISSUE TITLE
JWPlayer

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1607]
`ssl.p.jwpcdn.com `
wird von einigen Webseiten für das Abspielen von Videos benutzt und ist auf der ```crypto``` Liste fehl am Platze.

**Comment by RPiList** [comment]
> `ssl.p.jwpcdn.com ` wird von einigen Webseiten für das Abspielen von Videos benutzt und ist auf der `crypto` Liste fehl am Platze.

Definitiv fehl am Platze. Aber ich finde die Domain nicht in der Liste. Vielleicht ein Schreibfehler in der Domain? Finde die Domain in keiner Liste.

**Comment by yoshimo** [comment]
ne, aber es gibt ```||p.jwpcdn.com^``` in der Filterliste.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
