### ISSUE TITLE
Paketdienste Phishing

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1609]
Hallo,

hab gerade gesehen dass Android ein paar SMS als Spam aussortiert hat die Links auf Phishing-Seiten enthalten:

myhermes-versands.com
myhermes-deutschland.com
dhleg.com

aus dem April noch:
o2vertrag.de

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
