### ISSUE TITLE
Fake oder Nicht, das ist hier die Frage

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1611]
https://autorfahrumpler.at/

Laut Google Maps gibt es an der angeben Adresse keine Anzeichen auf eine Fahrschule
Auf der Webseite ist auch der Punkt kaufen Sie einen Führerschein enthalten.

Bitte schau mal ob die Seite echt oder Fake ist
Ich halte sie für Fake

**Comment by RPiList** [comment]
Tricky... aber ich glaube das ist ein Abzocker-Angebot für Ausländer

**Comment by RPiList** [comment]
Also Domain wurde hinzugefügt.
