### ISSUE TITLE
oe24.at on spamlist

### ISSUE THREAD

**Issue by oe3gwu** [RPiList/specials#1614]
You put the news site oe24.at on a spam list. God knows why. Please remove it.

Thanks!

**Comment by RPiList** [comment]
Hi, 
oe24.at is not on the spam list. Maybe you have an old copy of your list or you meant the malware list. A domain of oe24.at is on the malware list. But not on the spam. 

Greetings.

**Comment by oe3gwu** [comment]
you still block the site. Even after an update.

![grafik](https://github.com/RPiList/specials/assets/17622063/6bdafd6f-aa05-4e7a-a35d-3812db82f8d6)
