### ISSUE TITLE
Nächste Fake News Seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1617]
sjunfund.info

https://sjunfund.info/index.php?key=49c8n7c18l6jz1ioavp0&pixel=866492665095097&token=EAAKrlmuoc4EBO42fZCte6cBIRBsYVqjMI0gZChyF2GG4jkXTbTwMhTKyTVfsdOwSXTEg8v6FlIArm7ZBOhy3YkhJHJYs7tC5vkLcPl5kfqn0N1gOXRgoFRGusmowL0szD6g7yRPtPpfZC3ZAznyAnVnJYqw1ZAkHZCBbcHfpDUrOlDOZCgN6UsBZCbZBo8ZAdg6pkwOxwZDZD&site=nonstoprainstorm.com&placement=Facebook_Desktop_Feed&ad_name=6575949576692_2&campaign_name=6575949575492_10202097647513186+%2F+Johann+Lafer+-+AT+%2F+lead+%2F+AT+%2F+0406&adset_name=6575949575692_Oxy0IA775c+%2F+10202097647513186+%2F+all_placements+%2F+All+%2F+45-65+%2F+de+x2&ad_id=6575949576692&utm_content=JohannLafer2345&fbclid=IwAR1Uu5K9S0Vf8_zGmey92FMmLsIDaNgOLml5sosCqaQ8-kwCPBWgcI9NMrw_aem_AbZZ2oBI90yM1xert4VpupKobrMpmtxeRiolA2LC25_JxFqdSoBcbpHRfRjo8hnulpXXxYxM_UbhxsHtlTtAE2wb&domain_id=35297&cl_did=35297&cl_source=glamoroustoothpaste.com&cl_sid=6154&cl_check=b2398f824dfd9ae3a695ac33617765da&cl_data=glamoroustoothpaste.com%7C35297%7C6154%7Cplu&cl_clid=d8ceeffd0a81e4&cl_time=1717587552

![screenshot](https://github.com/RPiList/specials/assets/61678563/ac4e6db8-249a-4f3e-91e9-840d06c7228b)

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
