### ISSUE TITLE
dhm.de auf DomainSquatting1-Liste

### ISSUE THREAD

**Issue by frostieDE** [RPiList/specials#1620]
Hallo zusammen,

die Website vom deutschen historischen Museum (www.dhm.de) ist auf der Blocklist `DomainSquatting1` - ich vermute mal aufgrund der Ähnlichkeit zu dhl.de.

Es handelts ich aber um eine seriöse Internetadresse :wink:

Gruß  
Marcel

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
