### ISSUE TITLE
[Unblock request] vbb.de

### ISSUE THREAD

**Issue by andrewille** [RPiList/specials#1625]
Hello,
the domain [vbb.de](https://www.vbb.de/) is currently blocked in three files:
- `Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-3-Teil-1`
- `Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-6`
- `Blocklisten/DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-8-Teil-1`

It is the official page from the "Verkehrsverbund Berlin-Brandenburg", a union of local public transport companies and I request the removal of the domain.

Kind Regards
André

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
