### ISSUE TITLE
Spam-/Phishing-Domänen, Emails mit angeblichen Gutscheinen, Rewards, etc

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1626]
Hallo,

ich bekomme aktuell Spam-Emails die Links auf diese Domänen enthalten:

kelor.b2bcomunicazionedigitale.co
kelor.b2bconvenienza.de
eighteenb.recouvrement-pro-impayes.com
ninteena.securite-telesurveillance-pro.com
thirteena.fibre-optique-ftto.com
fifteena.geolocalisation-auto-pro.com
aws-track.golfappnow.com
kelor.b2bcrescita.co
kelor.b2bconnessioni.co
eighta.business-path.top
sevena.business-linked.top
seventeena.solution-titre-restaurant.com
ninteena.securite-telesurveillance-pro.com
twentyb.multirisque-pro-entreprise.com
fifteena.geolocalisation-auto-pro.com
thirteenb.fibre-optique-ftto.com
drupal.jaardeen.top
peach.osuk-mail.com
guava.golfapponline.com
sapota.osuk-mail.com
cranberry.hubwebanalytics.com
coconut.golfappweb.com
heldenapotheke.info
metalroofinginnovationspromo.com

Mein Vorschlag: zusätzlich die Hauptdomäne sperren und in die Regex-Liste "kelor", "sevena" und "eighta" aufnehmen.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
