### ISSUE TITLE
Unblock email.account.scribd.com

### ISSUE THREAD

**Issue by Retold3202** [RPiList/specials#1627]
`email.account.scribd.com` appears to be currently blocked in the Malware list [here](https://github.com/RPiList/specials/blob/master/Blocklisten/malware). This is a legitimate domain required for account verification on the [Scribd](https://www.scribd.com) service.

**Comment by RPiList** [comment]
Domain has been reported as disguised mail tracker by the Adgurad Team. Does it break the service?

**Comment by RPiList** [comment]
Thx for clearing this up. Domain has been removed. Greetings.
