### ISSUE TITLE
Dieses mal Fake Kronen Zeitung, wieder über diesen Kyrpot Müll

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1628]
https://krondrziu.com/home?utm_campaign=krondrziu.com+%7C+AT+%7C+kummer1&fbclid=IwAR1FGerXJ6bOdQCql6j8BxanLn6W8kRkGu0DW-TjPaYEEsP2aUY_fKqWjB4_aem_jDIdVJx3BGPlQ_m0JO91ig&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120210716291080581&adset_id=120210716291100581&ad_id=120210716291120581&adset_name=kummer1_v1&aff_sub4=428194552975352&ad_name=ad1&utm_medium=paid&utm_id=120210716291080581&utm_content=120210716291120581&utm_term=120210716291100581#form

**Comment by SGirl-Zockt** [comment]
und noch eine
https://advicominc.com/activities-summer-culture-culin?cost=%7Bcost_per_click%7D&fbclid=IwAR0Rs5P9ssbxEIJppSIdP_yfEbAYYWLEJLuuwhbBFsAFkQ6-STZ_lMWHa1U_aem_AUaOjOQJ9a-uHj9tEvvg-3FdYkhsSYNu3yJMYAzzHD59RrMulMMRok0EdWeu_izfWzIBux4w_v_JfCc_4SCZFJmL&utm_campaign=AT&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120208979294020449&adset_id=120208979294870449&ad_id=120208979437630449&adset_name=Manual+%7C+25%2B+%7C+ALL+LNG+%7C+FB&ad_name=N.3&aff_sub4=784233320501523

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
