### ISSUE TITLE
Spam-/Phishing-Domänen, Emails mit angeblichen Gutscheinen, Rewards, etc

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1630]
Hallo,

wieder eine Domain die in Spam-Emails verwendet wird:

kelor.b2bcomunicazionedigitale.de
warbyparkersource.com
fairegewinne.info
aktien-gpt.de
metalroofinginnovationspromo.com
bradaresgatando-clienteseguro.com
canvasprintsads.com
stkwicoach.com
bitcoin.edition-petitfute.com
promo-resgate.kyiv.ua
nationaldebtupdate.com
redonised.com
egrallive.com
lumedeodorantmail.com
talcpowderovariancanceraffiliate.com
lendcofinance.com.au
eflogistic.com
simpledebtsolutionsnews.com
reichsein.info
talcpowderovariancancerhelp.com
tenndgk.appspot.com
kidsclub4fun.com
karaleekaranavets.com
echte-pillen-rezeptfrei.de
simpledebtsolutionsservices.com
makevconstructora.com
v-xc-cx-cx.appspot.com
pflogdin-bradalivebeneficio.com
click.shpock.com
lumedeodorantnews.com
hellofreshaffiliatepromo.com
simpledebtpartner.com
nationaldebtpartner.com
blissynetwork.com
vanguardhomewarrantysupport.com
healthcarecomobamacare.com
talcpowderovariancancerzone.com
lumedeodorantservices.com
hellofreshpartneroffer.com
simpledebtinfo.com
empiretodayzone.com
easycanvasprintsinfo.com
sonobelloinfo.com
renewalbyandersenhelp.com
stkwiwatch.com
lumepartner.com
talcpowderovariancancerteam.com
leaffilteraffiliatealerts.com
project-333334444445555555556.appspot.com
gekapest.com.au
kelor.b2bcrescita.co
kelor.b2bconnessioni.co
shopmitgarantie.nl
investmentschule.nl
finanztipps24.nl
sicher-versand.nl
keinealtersarmut.nl
ups-services.appspot.com
webversand.nl
bitcoin-goldrausch.nl
etf-reichtum.nl
myawesomeproject-1acba.appspot.com
recover-photos-pro.appspot.com
sicheresinvestieren.nl
allentownvision2030.org
de---hermes-checkout.appspot.com

**Comment by RPiList** [comment]
Vielen Dank für die Mitteilung. Domains wurden hinzugefügt. Viele Grüße
