### ISSUE TITLE
Child-Protection-Probleme mal wieder

### ISSUE THREAD

**Issue by mchawk777** [RPiList/specials#1633]
....und "tichyseinblick.de" ist mal wieder in der Kinderschutzliste. Rein zufällig wieder drüber gestolpert, als ich meine Bookmarks nach toten Links gescannt habe.

Also diese ominöse reddit-Gruppe, aus der diese rpi-Liste gezimmert wird, sollte sich mal besser zusammenreißen und sich politisch möglichst neutral verhalten. Sonst verliert man früher oder später das Vertrauen darauf, dass es diesen Leuten tatsächlich um den Schutz vor Kindern geht - sondern eher um die Verfolgung politischer Interessen zur Beeinflussung von Kindern.
(Das unterstelle ich zwar nicht generell dieser Gruppe - aber anscheinend gibt es diesbezüglich Probleme!)

...oder zumindest wäre es wünschenswert, wenn das RPI-Projekt hinter "ihren" Listen mal eindeutig vermerkt, **aus welcher Quelle** sie stammen - oder diese Liste zumindest eindeutig zu den "Drittanbieterlisten" verschiebt.
Transparenz wird doch sonst so wichtig genommen - warum nicht hier?

Es bringt auch kein Hinweis: "Du musst die Liste ja nicht nutzen!" - Das weis ich selbst.
Es geht mir letztendlich um die Glaubwürdigkeit des Anliegens dieser reddit-basierten Liste, die sie jetzt wiederholt nicht erfüllt. Das wird auch auf das rpi-Projekt zurück fallen.
Zumal der "Volksverpetzer" als Gegenstück zu Tichy nicht geblockt wird. (Ja, ich informiere mich sowohl was die Rechts- UND Linkspopulisten so treiben!) 😐

**Comment by RPiList** [comment]
Hi,

> Also diese ominöse reddit-Gruppe, aus der diese rpi-Liste gezimmert wird, sollte sich mal besser zusammenreißen und sich politisch möglichst neutral verhalten. Sonst verliert man 

Kritik an der Reddit-Gruppe richten Sie am Besten direkt an Reddit.

> ...oder zumindest wäre es wünschenswert, wenn das RPI-Projekt hinter "ihren" Listen mal eindeutig vermerkt, **aus welcher Quelle** sie stammen - oder diese Liste zumindest eindeutig zu den "Drittanbieterlisten" verschiebt. Transparenz wird doch sonst so wichtig genommen - warum nicht hier?

All diese Punkte sind in der (von Ihnen eröffneten) Diskussion vom 12.02.2024 schon ausführlich erläutert worden. Evtl. dort einfach nachlesen.

Viele Grüße
