### ISSUE TITLE
Wie lautet die Reddit-Gruppe für die Child-Protection?

### ISSUE THREAD

**Issue by mchawk777** [RPiList/specials#1634]
Hi rpiList,

Du bist ja schnell dabei unangeheme Topics zu schließen .... Naja... Ist auch eine Nachricht an die Öffentlichkeit... 🤷‍♂️

Anyway:
Du verweist bei der Child-Protection-Liste an eine Reddit-Gruppe, die Du aber bisher auch auf Rückfrage nicht genannt hast - Stichwort: Transparenz.

Also: **Wie lautet die der Name der Gruppe?** Bzw. ein Link dorthin wäre nicht verkehrt, damit ich meine Kritik dort auch anbringen kann.
Ach noch mal die Bitte: Wenn rpiList mit sich inhaltlich nicht mit den Listen gemein machen will - und das ist die Schlussfolgerung aus dem bisher Kommunizierten - dann wäre zumindest so viel Transparenz wünschenswert, dass ihr die Quellen in euren Übersichtslisten auch genau angebt/definiert. (Z. B. Link zu der Reddit-Gruppe, von der ihr Daten übernehmt.)

**Comment by SGirl-Zockt** [comment]
Junge was ist falsch mit dir?

**Comment by RPiList** [comment]
Hi mchawk777,

> Du bist ja schnell dabei unangeheme Topics zu schließen .... Naja... Ist auch eine Nachricht an die Öffentlichkeit... 🤷‍♂️

Du hast ein Issue eröffnet. Ist ein Issue beantwortet, wird es geschlossen.  Wenn Du diskutieren willst, dann müsstest Du das in den Discussions machen. Die werden normalerweise nicht geschlossen.

> Anyway: Du verweist bei der Child-Protection-Liste an eine Reddit-Gruppe, die Du aber bisher auch auf Rückfrage nicht genannt hast - Stichwort: Transparenz.

Ich dachte mir schon durch Deine Fragestellung im letzten Issue, dass Du Dir die Discussion, die Du im Februar selbst eröffnet hast überhaupt nicht durchgelesen hast.

Aber jetzt ist es sicher: Die Mühe die Du Dir nicht machen willst und gleichzeitig von anderen verlangen, sie sollen sich Mühe geben. 

> Also: **Wie lautet die der Name der Gruppe?** Bzw. ein Link dorthin wäre nicht verkehrt, damit ich meine Kritik dort auch anbringen kann. Ach noch mal die Bitte: Wenn rpiList mit 

Gerne nochmal. Gruppe wird in der Diskussion genannt und verlinkt. Am Besten das wirklich alles noch mal lesen. Du scheinst zu glauben, dass uns die Links von diesem Subreddit geliefert werden. Das wurde nirgendwo gesagt. Aber meld' Dich gerne bei denen. Screenshot hänge ich gerne an.

![image](https://github.com/RPiList/specials/assets/56664851/b8c882d4-4ee3-42c5-99e5-8c401eb88c38)

> sich inhaltlich nicht mit den Listen gemein machen will - und das ist die Schlussfolgerung aus dem bisher Kommunizierten - dann wäre zumindest so viel Transparenz wünschenswert, dass ihr die Quellen in euren Übersichtslisten auch genau angebt/definiert. (Z. B. Link zu der Reddit-Gruppe, von der ihr Daten übernehmt.)

Die Punkte wurden in der Diskussion ausführlich erläutert. Wir haben hier nicht die Zeit und die Langeweile das x-mal zu erklären.

Viele Grüße

**Comment by RPiList** [comment]
Noch mal als Ergänzung. Du kannst gerne weitere Fragen stellen, wenn Du etwas nicht verstehst. Aber Fragen die schon beantwortet wurden, werden nicht nochmal beantwortet.
