### ISSUE TITLE
Fake News Seite wiedermal

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1635]
https://timetravelweekly.com/blog-category-austria?utm_campaign=AT+%7C+timetravelweekly.com+%7C+2291&fbclid=IwAR1tgs5Le43vJCeZ8k1gvTCMPwE_hNISQJrXHx2at5GNk3lhUKL7Bj7Ancw_aem_UMDVr0gseQueiRz2N6-3Sg&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120209115620190449&adset_id=120209115620130449&ad_id=120209115620210449&adset_name=25%2B+%7C+All+LNG+%7C+FB&ad_name=N-Creo.02.3&aff_sub4=784233320501523

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
