### ISSUE TITLE
Nächste Fake seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1640]
https://mojeejo.com/blog-best-vienna-blogs-city-ins?utm_campaign=AT+%7C+mojeejo.com+%7C+5945+%7C+DE+%7C+Ft+Creo&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120209662953240323&adset_id=120209662953250323&ad_id=120209663337030323&adset_name=AT+%7C+mojeejo.com+%7C+5945+%7C+DE+%7C+Ft+%7C+N-P+%7C+Ge.01&ad_name=Ft.Creo-Ge+-+Copy&aff_sub4=317417948086616&fbclid=IwAR3l5ZlubGBCdDiVmHP84LKFnB2-UGVJHvDWGS3UTaJBVoNLULm8owBam1o_aem_QJU7BB0NW10VwQQrYKVyIw

**Comment by SGirl-Zockt** [comment]
https://mojeejo.com/blog-best-vienna-blogs-city-ins?utm_campaign=AT+%7C+mojeejo.com+%7C+5945+%7C+DE%2BEN&fbclid=IwAR39fgnVKxll9LMKvFmR8TIOUTW7jt8VqHzE8ItOFlT4Ezoq8mzGkt7OlHc_aem_e6vRCGmBgHgt8cK11l7zyA&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120209636386860323&adset_id=120209636386800323&ad_id=120209636386780323&adset_name=25%2B+%7C+DE+%2B+EN+%7C+FB-+Feed&ad_name=AT.02.2&aff_sub4=817747223274061

**Comment by SGirl-Zockt** [comment]
das ist sogar eine Fake RTL seite
https://inpillole.com/blog-austria?utm_campaign=New+Leads+Campaign&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120208975984720259&adset_id=120208975984850259&ad_id=120208976098080259&adset_name=25%2B+%7C+DE+%2B+EN+%7C+FB-+Feed&ad_name=N.05&aff_sub4=972510307513017&utm_medium=paid&utm_id=120208975984720259&utm_content=120208976098080259&utm_term=120208975984850259&fbclid=IwAR1s0bCvQW_6S55GwbDa9_DtPSQGvaxQaLBaxqy6Ravy_yDO2zu9qtDbhu0_aem_jD2HnVzWgtjWVOhkGO6jiA

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße
