### ISSUE TITLE
False Positive: MyAnimeList(.net) in "Streaming"

### ISSUE THREAD

**Issue by espressoelf** [RPiList/specials#1641]
Hi,

leider ist die bekannte (und legale) Anime-Info- und Community-Seite [MyAnimeList](https://de.wikipedia.org/wiki/MyAnimeList) fälschlicherweise auf der Liste für illegale Streamingseiten gelandet. Zwar werden auf MAL tatsächlich vereinzelt Streams angeboten, diese werden jedoch offiziell über Crunchyroll bereitgestellt.

https://github.com/RPiList/specials/blob/b0ef95c7050ddfdde348fafb3efa814ba80a4c33/Blocklisten/Streaming#L11878 
Müsste also entfernt werden. Vielen Dank!

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
