### ISSUE TITLE
Spam Domains

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1642]
Hallo,

wieder ein paar Domänen aus Phishing-Emails:

grandpare.com
nationaldebtinfo.com
BrinksHomeOffer.com
lumedeodorantupdates.com
150.107.205.92.host.secureserver.net

**Comment by SGirl-Zockt** [comment]
Moin,
Ich hätte auch noch ein paar

survivalprotect.com
healthifyhive.com
interpublicenterprises.com
prerollscartonline.com
aimsitconsulting.com
concealedlab.com
dripemail2.com

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße
