### ISSUE TITLE
Bitte Sperren

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1644]
Hey Sprecher,
Dieses Unternehmen sind dafür bekannt, erst günstige Preise aber nachher Nachrechnungen von über 100€ zusenden

packlink.com
jumingo.com
transglobalexpress.de

Beweißvideo
https://youtu.be/UVuVTgvIEhs?si=wUHqH8vM8uPWXlB_

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße
