### ISSUE TITLE
Fake EU Seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1646]
https://return-law.site/form_register?sub_id_12=1687510181780162&creo=166q&log=42658-Ellie&adset=up3&sub_id_13=15&utm_medium=paid&utm_source=fb&utm_id=120210920755800598&utm_content=120210921073160598&utm_term=120210921073170598&utm_campaign=120210920755800598&fbclid=IwAR3jPeyVKTPSEBO-Fx_VCWFMEIRtn5pkdmVPjcwCo8CLsf-6Jm36fIXFcrE_aem_k-LamV3Gv_tvIoUdu_cMHA

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
