### ISSUE TITLE
UEFA EURO 2024 Spam

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#1647]
Hallo,

wird gerade neu in Spam-Email verwendet mit "UEFA EURO 2024" im Betreff

th.getgolfapp.com
getgolfapp.com

Bei opendns steht die Domäne schon auf der Sperrliste.

edit:
hier auch noch normale Spam-Domänen:
dondard.com
leaffilteraffiliatedirect.com

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
