### ISSUE TITLE
Fake Hofer/Siemns werbung

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1649]
https://ks.ligam.shop/oHxNMN4V?utm_medium=paid&utm_source=fb&utm_id=120210693539350087&utm_content=120210693539230087&utm_term=120210693539190087&utm_campaign=120210693539350087&fbclid=IwAR0tIT4sjhtqO8hJlPG19sCcymLwSpCEzZwXDIfVzrhyfTo52a8auZz0Zog_aem_tqlDkR2kSvVg3RbHxrlcIQ

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
