### ISSUE TITLE
Fake HILTI Seite

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1650]
https://xcommunen.monster/c9rBenX?utm_medium=paid&utm_source=fb&utm_id=120210790842330418&utm_content=120210790896860418&utm_term=120210790896870418&utm_campaign=120210790842330418&fbclid=IwAR2KnCWuk7v0eCgtAOZ3y5CowxfAkoPalbE-G9QsYZXicaa3UViBjmJYNic_aem_Q8Gd0y5KLROyPzTCXCvDhA

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
