### ISSUE TITLE
Fake Kurse angeblich wieder von einen Ministerium

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1651]
https://psychologydegree01.site/?&kw1=online+psychologie+studium&kw2=psychologiestudium+online&kw3=psychologie+kurse+online&kw4=online+psychologie+kurse&kw5=psychologie+studium+privat&kw6=psychologie+studium+fachabi&kw7=psychologie+studium+mit+fachabi&kw8=psychologie+mit+fachabi+studieren&sub1=%7B%7Bclickid%7D%7D&sub2=120209804890940304&sub3=120209804890890304&network=facebook&site=Facebook_Desktop_Feed&pxfb%5Bid%5D=395089550081757&pxfb%5Bec%5D=Purchase&adtitle=Kostenloser+Psychologiekurs+%28Zertifikat+verf%C3%BCgbar%29&utm_medium=paid&utm_source=fb&utm_id=120209804890890304&utm_content=120209804890940304&utm_term=120209804890880304&utm_campaign=120209804890890304&fbclid=IwAR1XPvatKiVC0G3nngcrkOkV3Vg07v6f3wn7U84VdfF9vT9mY9INw55vHDs_aem_fUZWw68PHRy6mJzMveYUSw

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
