### ISSUE TITLE
false-positive: zug.sbb.ch

### ISSUE THREAD

**Issue by higgs01** [RPiList/specials#1653]
`zug.sbb.ch` is being Listed in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware 

This is a legimate domain from the SBB (swiss train company) used by their mobile-app and shouldn't be flagged as maleware.

**Comment by RPiList** [comment]
Hi, 

the domain has been flag as malware by the adware team as combined disguised tracker. So it is malware. Question is, if it breaks the mobile app.

Greetings

**Comment by SGirl-Zockt** [comment]
Its now a Week after you Replay him, so you should clouse this issues

**Comment by higgs01** [comment]
Initially it did stop it from working. But seems like they've fixed that as it works now. Therefore I'll close this issue.
