### ISSUE TITLE
Check mal ob Fake

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1656]
Moin Sprecherino
Ich habe das gefunden und bin mir da echt unsicher ob es echt ist,

https://tegerkelin.shop/?utm_creative=stv&utm_campaign=sky1551&utm_source=QuantumAI&pixel=783737130513789&userId=103&boxId=404&fbclid=IwZXh0bgNhZW0BMAABHfyQMW8Vczdqus64GzQW6Ojkv7fkICKJcSaO2bJHg5CDVJ93ZJoGh4QA1Q_aem_DxyflfueuhNa5Ep3PWJcww

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
