### ISSUE TITLE
de-fianz.online

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#1657]
`https://de-fianz.online/` ist eine Phishing Seite die über SMS verbreitet wird und welches https://www.bzst.de/DE/Service/Behoerdenwegweiser/FinanzverwaltungLaender/finanzverwaltunglaender_node.html nachahmt.

Zur Verifikation muss die Seite mit einem mobilen Client aufgerufen werden, Desktop Clients werden blockiert.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
