### ISSUE TITLE
NoTracking

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#166]
Hallo,

eine kurze Suche hat ergeben, dass die URLs von Notrack nicht in den Blocklisten zu finden sind.
https://github.com/notracking/hosts-blocklists/blob/master/adblock/adblock.txt

Ist der Plan die Liste aufzunehmen?

**Comment by JFronny** [comment]
Nach meinem wissen wird das adblock-format nicht von PiHole unterstützt. Ich habe mir die Repo kurz angeschaut und [diese](https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt) Datei könnte glaube ich eher funktionieren

**Comment by BulldozerPete** [comment]
Stimmt. Sind nach kurzem Überfliegen die gleichen URLs.

**Comment by RPiList** [comment]
Das extrahieren der Datei ist kein Problem. Aber mit der von @JFronny gefunden Liste nicht mehr notwendig.
Die Frage die sich also stellt ist die, ob wir einfach nur von uns aus auf die Liste verlinken oder ob wir die komplett übernehmen.
Ursprünglich dachte ich es würde sich um eine Tracking-Liste handeln. Daher wollte ich sie in die DDG-Brave-DisconnectMe Liste schieben. Die Liste besteht ja schon aus den "Anti-Tracking" Listen von DuckDuckGo, Brave und von DisconnectMe.

Aber wenn man sich die Datei genauer anschaut findet man...

> #################################[INFO]##################################
>  Blocks ads, fake sites, shock sites, malware hosts and trackers

Also eine Misch-Liste. 

Also verlinken oder in unsere Easylist (wg. Werbung) oder in die kommende Tracking-Liste packen.

**Comment by RPiList** [comment]
Schiebe sie in die Easylist. Die ist von den meisten Benutzern abonniert. Damit ist gesichert, dass die meisten Nutzer des SV-Pihole die Domains beim nächsten Update mit drin haben. Danke für den Hinweis.
