### ISSUE TITLE
Ich bekomme diese Domians von Facebook, da werden diese Seiten als Werbung angezeigt

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1662]
https://sjunwhale.info/?key=l4o5kq7cl5toy3e8hksq&fb_action=Lead&pixel=869273707407946&token=EABOaN4S8kfwBO1Ic6dtpTlKRBgEOfTdQgX2JmyK0fYt6ZA6YVCHZCJMJxg9tG0EST88HSp4gRG7K05uOHkDMx0tRTmHZAD8Io1xKtqvLyiVaCYDl0mVlzvxADujhzcwIFzw9E5LvwJ3ytgAxY3JCRRrVa0yV6YZCjUFwegVgBQa59rmuldJCBP6pQT5K9JG3DQZDZD&site=bargainchina.com&adset_name=6589288672745_AT+2&placement=Facebook_Desktop_Feed&ad_id=6589288673745&ad_name=dv-AlexandraWachter3+00.44.39&campaign_name=6589288672545_AT+491476990959447+Alexandra-Wachter&utm_content=Kilfeo92at&utm_medium=paid&utm_source=fb&utm_id=6589288672545&utm_term=6589288672745&utm_campaign=6589288672545&fbclid=IwZXh0bgNhZW0BMAABHTeqWiPHCJ3PToVbPE7F6MEzejTvwyGK1xUd2-l-ZEhKBv-0hkxWRKANvg_aem_T3IMIMPV7m3JwhS0kKPtnw&domain_id=36346&cl_did=36346&cl_source=substantiallift.com&cl_sid=6117&cl_check=c2879d3b19b6b7f7fbb5da940fb43d23&cl_data=substantiallift.com%7C36346%7C6117%7Cplu&cl_clid=a26c60c3a57882&cl_time=1719480413

**Comment by SGirl-Zockt** [comment]
https://patanketvti.com/?utm_creative=c&utm_campaign=l4920&utm_source=VenaSystem&pixel=1634186887395370&userId=103&boxId=307&fbclid=IwZXh0bgNhZW0BMAABHW-sOpmWwhNZMkCbvWfK9uEljwm9DrTXgc5Sc4BiGDjtsezeJtBSjPWKIA_aem_f3o4EcKGfar05K5-6sbaZg

**Comment by SGirl-Zockt** [comment]
https://atofaneha.shop/?acc=%2356214_RAF_186+atp1&adset=120209029397850272&ad=120209029397890272&adname=%D0%9D%D0%BE%D0%B2%D0%BE%D0%B5+%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5+%D1%81+%D1%86%D0%B5%D0%BB%D1%8C%D1%8E+%22%D0%9B%D0%B8%D0%B4%D1%8B%22&placement=Facebook_Desktop_Feed&ev=Lead&pxl=479324391365313&fbclid=IwZXh0bgNhZW0BMAABHdw4L8QqZFdT4RbCzRnOPyzAAvCaPssp2E4WWC7TAprG8r0VXWvd9uYB1w_aem_f3RAX-eKVE67R1kFYNS5CQ

**Comment by SGirl-Zockt** [comment]
https://buy.osepk.shop/Ispsp2cBkX?fbclid=IwZXh0bgNhZW0CMTAAAR3Z6tm2qhAz8oLxdksiZRrRW6PaWbSl1P0bzny5NgPXP5piGn5armYD-Ds_aem_XfKL2_f_nHPYgAI6sA0ePQ

**Comment by SGirl-Zockt** [comment]
http://www.qqqzzzrrr.shop/ATHHHH?fbclid=IwZXh0bgNhZW0CMTAAAR0ydr1gYKrBvVcrXRkb66X_Q477hJ5egqK4zfBvE_46J5z1mkFP762qMYU_aem_RQWMC6G8QM2rSB2UmF9cdQ

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
