### ISSUE TITLE
Wieder Werbung von Facebook wo es nur um Betrug geht

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1668]
https://de4.indivjoinsyst.org/sfs7Gdms?buyer=704&utm_campaign=0333&adset_name=4&ad_name=4&ad_id=120212123864820155&utm_placement=Facebook_Desktop_Feed&pixel=2538144506379716&fbclid=IwZXh0bgNhZW0BMAABHUJA_d_dj0xO8nzZrXtMeeu1TRacWJF5T0l0SU0KV0rS3S_bCE0IPrYo6w_aem_TjEpMqaLaF0qG8CRtptMxQ

**Comment by SGirl-Zockt** [comment]
http://www.ttthhhuuu.shop/ATHHHH24?fbclid=IwZXh0bgNhZW0BMAABHQmLP-spECSJ0x9lC6xnOxUsm6EwQSPuYmaFd0TOOm9l7q8xkiQ8ivFG6w_aem_eqHLMGHKad7fd6xwcLbgvg

**Comment by SGirl-Zockt** [comment]
https://ttestf.lol/?m=Item&a=show&id=120927&fbclid=IwZXh0bgNhZW0BMAABHWeenvJVTv4MJKFcC9-M0p6yc0Rk_mv40-RwreCy1ZNjaMGeEjumshjQ8g_aem_QsdZWwBvucX-D0IDbOlGOA

**Comment by SGirl-Zockt** [comment]
https://de.indivjoinsyst.org/g43WfBms?utm_campaign=1025_3_6_AT&buyer=404&adset_name=1025_2&ad_name=7&ad_id=120210683641260443&utm_placement=Facebook_Desktop_Feed&pixel=312059405276197&utm_medium=paid&utm_source=fb&utm_id=120210683492620443&utm_content=120210683641260443&utm_term=120210683641280443&fbclid=IwZXh0bgNhZW0BMAABHWfUTiUHny9-2wDEAwOcpyrQS0skUfj5UICYPYBGqU8aBkH8SMh90oCrfQ_aem_vCQ4Mnl3zlLBW0spUTAcKA

**Comment by SGirl-Zockt** [comment]
https://busip.best/wuwal/?t10=VA&d=10406&p=k1hg&i=e21n&f=17781682&dm=0406&utm_content=120207956954240553&utm_source=fb-Facebook_Desktop_Feed&utm_medium=1584295322333735&px=1477605799511892&utm_id=120207956857960553&utm_term=120207956954260553&utm_campaign=120207956857960553&fbclid=IwZXh0bgNhZW0BMAABHeicwVnBDDgN1pe-7w-v8OvVxK09NbV7U-JViw1aVY68fb8HWovl0Dx_8A_aem_h82Vd2yuTelrAb0XQcq8NA

**Comment by SGirl-Zockt** [comment]
https://shop.lkjjjuju.online/IqQmtB?fbclid=IwZXh0bgNhZW0BMAABHSgpBI1RbFKD61--qfGUdsr3uNSoPThzSTVrRlB3D5Y5V9eZ-nIBjOvHcw_aem_EJqKAS7sHXZlfVNUwEXWTw

**Comment by SGirl-Zockt** [comment]
https://shop.chushm.online/ZEISS?utm_medium=paid&utm_source=fb&utm_id=120211019491470603&utm_content=120211019491410603&utm_term=120211019491320603&utm_campaign=120211019491470603&fbclid=IwZXh0bgNhZW0BMAABHQ2bLKIhPcD54-I7GD0UormNxEvv_X9MlP1U-65MWI3RfYiyqxK03p4WFQ_aem_2hq3CZnYQZoBvp4hZ01yQg

**Comment by SGirl-Zockt** [comment]
https://kustano.site/?ad_name=AT+aleks+black+green+trag&adset_name=AT+aleks+black+green+trag&campaign_name=AT+aleks+black+green+trag+%E2%80%93+Copy&pixel=3838968336425417&acc=351269444&ad_id=6677984770413&key=vm0vzrs86v9h0p6bm2ao&utm_medium=paid&utm_source=fb&utm_id=6677984770213&utm_content=6677984770413&utm_term=6677984772013&utm_campaign=6677984770213&fbclid=IwZXh0bgNhZW0BMAABHYEekBLiZ3qkkr_LkzvTT8Dbf0hn2mjAqHYOv-3e_es--V5LiH7WYGfqLw_aem_hEIj5VOO-zAn7DN1N5BvRw

**Comment by SGirl-Zockt** [comment]
https://lithaia.com/de-ch-blog-posts-archiv-wp?utm_campaign=0307+lith+AT+GROSZ&fbclid=IwZXh0bgNhZW0BMAABHbBgTwtnm3ZsoerHHxAg9gnvMJy6pWTWzEv7S5TXqWlWlABTgDsPi2wgOw_aem_5VDilcFEGiLVMj_0lBKyYw&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=6592473579779&adset_id=6592473580779&ad_id=6592869010779&adset_name=uno&aff_sub4=894905772380443&ad_name=spexial+lith+%E2%80%93+%D0%BA%D0%BE%D0%BF%D1%96%D1%8F

**Comment by SGirl-Zockt** [comment]
https://attradine.com/fhk-kfnb-nfg?fbclid=IwZXh0bgNhZW0BMAABHaz9IlyJXUWOZcnCCJW5u3QNEI1YMQgbrMHQRSl48x_2CwtN5OIo3gPRHw_aem_4cG2ertodACmQJCi1SRPdw&utm_campaign=0407+at+-+ata-+grosz&utm_source=fb&utm_placement=Facebook_Desktop_Feed&campaign_id=120209947659790111&adset_id=120209947659810111&ad_id=120210111141050111&adset_name=%D0%9D%D0%BE%D0%B2%D0%B8%D0%B9+%D0%BD%D0%B0%D0%B1%D1%96%D1%80+%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B8+%D0%B7+%D1%86%D1%96%D0%BB%D0%BB%D1%8E+%C2%AB%D0%9B%D1%96%D0%B4%D0%B8%C2%BB&aff_sub4=346049978487702&ad_name=grosz

**Comment by SGirl-Zockt** [comment]
https://startdividendpayoutratio.com/products/mould-king-21005-republic-attack-cruiser?fbclid=IwZXh0bgNhZW0BMAABHXxzh2V8JYmGUh6sK65G6De8Bqr3UrTVx2TxIjYs_5rVs7AOmIaIufOZlg_aem__PVtIFb_izbWVS1olC_W1Q&utm_source=facebook&utm_medium=paid&campaign_id=6632866918506&ad_id=6632866910706

**Comment by SGirl-Zockt** [comment]
https://ks.wjjxn.shop/oLLrmHlY?utm_medium=paid&utm_source=fb&utm_id=120210525629910245&utm_content=120210525630010245&utm_term=120210525630020245&utm_campaign=120210525629910245&fbclid=IwZXh0bgNhZW0BMAABHTea2JXzCLre6nuEqDg-PnBYo4dGoycZcIhXIDxy_ZyAhEbu3sjLLYCw_g_aem_KZ9m6EPmJLQPtMCLYY5mng

**Comment by SGirl-Zockt** [comment]
https://psychologydegree-01.online/?campaign=120210932075500425&adset_id=120210932075520425&ad_id=120210932075580425&adtitle=psychologydegree-01.online-AT-0626&placement=Facebook_Desktop_Feed&network=Facebook&source=fb&&kw1=psychologie+bachelor+fernstudium&kw2=berufsbegleitend+psychologie+studieren&kw3=psychologie+fernstudium+bachelor&kw4=ausbildung+coach+psychologie&kw5=psychologischer+coach+ausbildung&kw6=ausbildung+personal+coach+psychologischer+berater&kw7=psychologie+studieren+ohne+nc&kw8=psychologie+nc+frei&kw9=psychologie+bachelor+ohne+nc&kw10=Online+Studium+Ohne+Pr%C3%A4senz&pxfb%5Bid%5D=1054947815522220&sub1=120210932075580425&sub2=120210932075500425&fbclid=IwZXh0bgNhZW0BMAABHTJE1EEdp6jx1n1XvVtdvXI0Tw2vgWJeKMNKMpZDr4IKRFFYY3mNVeoMBw_aem__PKTKwRFiFs9ECTiyHCDsQ

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
