### ISSUE TITLE
Extended polyfill

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#1669]
Wie in #1663 bitte auch die anderen Domains aus diesem Artikel blockieren: https://www.golem.de/news/grossteil-aus-deutschland-fast-400-000-webhosts-verbreiten-malware-via-polyfill-io-2407-186716.html

Zitat: „Aber auch auf die Verwendung von bootcdn.net, bootcss.com, staticfile.net und staticfile.org sollte nach jüngsten Erkenntnissen sicherheitshalber verzichtet werden.“

**Comment by RPiList** [comment]
Vielen Dank für die Info. Alle Domains jetzt auf der Malware-Liste
