### ISSUE TITLE
post.ch auf Phishingliste

### ISSUE THREAD

**Issue by GPSPython** [RPiList/specials#167]
post.ch und www.post.ch befinden sich auf der Phishing-Liste, es handelt sich dabei aber um die offizielle Website der Schweizerischen Post welche garantiert KEINE Phishing Mails verschickt. Daher bitte wieder aus der Liste entfernen.
Es stimmt jedoch das in der Schweiz immer wieder Phishing-Mails im Namen der Post versendet werden, dies aber logischerweise über andere (ähnliche) Domains.

**Comment by Ju200** [comment]
Wenn wir schon mal dabei sind, Spotify (spotify.com und deren Subdomains) stehen auch vielen Listen. Manche Domains sind u.U. Tracking Dienste von Spotify oder anderweitige Phishing Seiten. Aber aktuell werden zu viele Elemente geblockt. Als Beispiel einfach mal spotify.com aufrufen.

**Comment by RPiList** [comment]
> post.ch und [www.post.ch](http://www.post.ch) befinden sich auf der Phishing-Liste, es handelt 

Post.ch und www.post.ch wurden der Whitelist hinzugefügt. Damit ist sicher gestellt, dass der Fehler nicht erneut passiert. Vielen Dank für den Hinweis.

**Comment by RPiList** [comment]
> Wenn wir schon mal dabei sind, Spotify (spotify.com und deren Subdomains) stehen auch vielen 
Das brauchen wir genauer.
Spotify Subdomains und jede Menge Fakedomains befinden sich in der Crypto, Easylist (Werbung), malware und Phishing-Liste.

Da ich Spotify nicht nutze, kann ich nicht sehen, welche Domains davon echt sind und welche nicht.

**Comment by GPSPython** [comment]
Danke für die schnelle Korrektur!
