### ISSUE TITLE
Fake DHL-Zoll-Mail

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#1674]
Hallo Sprecher,

heute habe ich eine Fake DHL-Zoll-Mail erhalten. Der link in der Mail führt auf: https://deuxmois-salaire.com/
Eine automatische Weiterleitung auf: 
https://mein-paket-zoll.de/captcha/captcha.php
erfolgt dann.

Bitte Domains in eine passende Liste aufnehmen. Die Kollegen danken.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
