### ISSUE TITLE
False Positive - learn.cisecurity.org

### ISSUE THREAD

**Issue by TFWol** [RPiList/specials#1676]
That website is the Center for Internet Security.

You can see it mentioned here:
https://www.cisa.gov/resources-tools/services/multi-state-information-sharing-and-analysis-center

**Comment by RPiList** [comment]
Hi, thx for supporting us.

The domain learn.cisecurity.org is flagged as malware, as combined disguised clickthroughs domain by the adguard team.

A "combined disguised clickthroughs domain" (CDCD) is a term used in the context of online advertising and digital marketing. It describes a tactic where an advertiser or a website uses techniques to trick users into clicking on advertisements or links without them being fully aware of it or without clearly recognizing where they are clicking. This practice can be considered deceptive or fraudulent.

So the important question is, does the block break the website?

Greetings

**Comment by TFWol** [comment]
Yes, it breaks the site if you want to register (a requirement) to download the baseline configurations.

**Comment by RPiList** [comment]
Thx for helping us out. Domain has been removed. Greetings.
