### ISSUE TITLE
Disney Plus Video geblockt 

### ISSUE THREAD

**Issue by TheRealFlori** [RPiList/specials#168]
Hi zusammen,

Bei mir wird auf dem Smart TV Disney Plus geblockt. Ich kann mich anmelden, aber sobald ich was schauen will ist dies nicht möglich. Nach dem Deaktivieren vom Pie Hole wars ohne Probleme möglich. Eine spezielle Adresse konnte ich noch nicht ausmachen, irgendeine Idee? :o

Danke und Gruß
Flo

**Comment by AleksCee** [comment]
Was ist den im query log oder im trace zu dem Zeitpunkt wo du ein Video startest zu sehen? So solltest du die Domain sehen die blockiert wird. Die kannst du dann unter Tools/Query Lists Eingeben und dann sagt er die von welcher Liste die Domain geblockt wird.

Liebe Grüße, Alex

**Comment by RPiList** [comment]
@AleksCee vielen Dank für die Domains. Als reine Vorsichtsmaßnahme packe ich die in die Whitelist.

@TheRealFlori Keine der Domains findet sich auf einer unserer Listen. Evtl. einfach mal Listen von anderen Maintainern abschalten. Besser wäre es aber wie von @AleksCee vorgeschlagen, in den Log-Daten des Pi-hole nachzuschauen.
