### ISSUE TITLE
arkhamintelligence.com

### ISSUE THREAD

**Issue by vonnull** [RPiList/specials#1685]
https://www.arkhamintelligence.com/ ist eine ganz normale Seite.

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info.

Grds. sind alle Seiten ganz normale Seiten. Das Problem ist nur, dass arkhamintelligence.com auf seinen Seiten Phishing betreibt.

D.h. nicht, dass die Seite das selbst und mit Absicht macht. Vielleicht ist die Seite gehackt worden und der Code wurde ohne deren Wissen eingespielt. Aber die Verlässlichkeit der Quelle, die das gemeldet hat, ist hoch.

Insoweit muss die Domain, bis sie ihren Server aufgeräumt haben, auf der Liste bleiben. Viele Grüße
