### ISSUE TITLE
Unifi Security Gateway --> DNS einstellen (Für alle Netze, die das Security Gateway als DNS verwenden)

### ISSUE THREAD

**Issue by Tyberhertz** [RPiList/specials#17]
1. Zuerst auf "Settings" im Controller (Zahnrat)
![grafik](https://user-images.githubusercontent.com/26968722/69671190-d5b80580-1095-11ea-81cf-ce3af70a6ad9.png)

2. Dann im Menü auf "Networks"
![grafik](https://user-images.githubusercontent.com/26968722/69671205-d94b8c80-1095-11ea-9e04-51708d4afdcc.png)

3. Die WAN-Schnittstelle auswählen "Edit"
![grafik](https://user-images.githubusercontent.com/26968722/69671247-eec0b680-1095-11ea-851b-8523b2f80e0c.png)

4. DNS-Server ändern, die IP des PiHole eintragen
![grafik](https://user-images.githubusercontent.com/26968722/69671280-013af000-1096-11ea-9e3f-336ed2e6b844.png)

5. Dann auf "Save" klicken. 3-5 Minuten warten, bis das Security Gateway sich provisioniert hat.

**Comment by RPiList** [comment]
Hi,

kenne mich hier noch nicht so gut aus. Aber muss das nicht als Pull-Request erstellt werden, damit ich das direkt importieren kann?

Grüße
