### ISSUE TITLE
Remove nordvpn.com from proxies list

### ISSUE THREAD

**Issue by PinguDEV-original** [RPiList/specials#1704]
In the proxies blocklist, there is nordvpn.com blocked. Is this intentional?

**Comment by SGirl-Zockt** [comment]
A VPN is actually just a proxy server through which I route my traffic, so I think NordVPN is right on the proxy list

**Comment by RPiList** [comment]
> In the proxies blocklist, there is nordvpn.com blocked. Is this intentional?

Yes. The Proxies list is intendet for users that don't want their lan-users "get around", like schools ...

So nordvpn has to stay on the list.

Greetings
