### ISSUE TITLE
facebook phishing

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#1707]
Hallo, ich möchte weiteres Phishing melden. Original issue: https://github.com/uBlockOrigin/uAssets/issues/24719

URLs
```
https://m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app/
https://m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app/
https://m-isist-emai-nmu-ne-qefa68dvbd.vercel.app/
https://thepatrones.blob.core.windows.net/thepatrone/thepatrones.html
https://xyzxyz55.xyz/?api=1&lan=facebooknew&ht=1
```

Domains:

```
m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app
m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app
m-isist-emai-nmu-ne-qefa68dvbd.vercel.app
thepatrones.blob.core.windows.net
xyzxyz55.xyz
```

`xyzxyz55.xyz` enthält den eigendlichen phishing code, `thepatrones.blob.core.windows.net` bindet den Code ein und die vercel domains sind redirector.

**Comment by RPiList** [comment]
Vielen Dank für die Info. vercel.app und xyzxyz555.xyz sind jetzt gesperrt.

Windows.net ist aber eine offizielle Microsoft Domain, richtig? Prüfe ich noch genauer. Viele Grüße

**Comment by RPiList** [comment]
thepatrones.blob.core.windows.net ist jetzt auch in der Phishing Liste. Viele Grüße

**Comment by JobcenterTycoon** [comment]
`vercel.app` erlaubt es wie `blob.core.windows.net` das Nutzer ihre eigene Subdomain haben können daher nur die Subdomains sperren nicht ganz `vercel.app` @RPiList

**Comment by RPiList** [comment]
Ich schlage vor wir lassen dort erst mal die ganze Domain gesperrt. Schauen wir mal ob sich jemand meldet. Denn wenn da jeder seine eigene Sub-Domain erstellen kann und das Muster "m-isist-emai-nmu-ne-qefa68dvbd.vercel.app" symtomatisch ist, dann kriegt man da gar keinen Schutz hin. Das sieht ja fast nach Zufallsgenerator aus...

Es wäre wünschenswert, wenn der Betreiber vercell.app dafür sorgt, dass ihm ein paar schwarze Schafe nicht den Dienst "killen".

Wenn sich jemand meldet, nehme ich es aber auch wieder runter. Viele Grüße

**Comment by JobcenterTycoon** [comment]
```
m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app
m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app
```

wurden schon gesperrt "UNAVAILABLE_FOR_LEGAL_REASONS"

**Comment by TyIsI** [comment]
Hi! I'm one of those legit users.

My dashboard app gets deployed to Vercel automatically through their auto-deploy system:

https://github.com/TyIsI/serenity-dashboard is deployed on https://serenity-dashboard.vercel.app/.

Also, as mentioned in #1712, https://swr.vercel.app/ is a valid site, which hosts the documentation for https://www.npmjs.com/package/swr

@JobcenterTycoon if you find security issues with @Vercel app instances, may I suggest you email their abuse department at abuse@vercel.com. (See https://vercel.com/guides/how-to-get-vercel-support.)

@RPiList vercel.app is a nextjs/cloud hoster. Blocking vercel.app on a whole is like blocking entire aws or fbcdn infrastructure domains. May I also suggest to you that you email their abuse department - or tell reporting parties to do that - if anyone reports issues with Vercel?

They are powerless to fix safety issues if they don't get reported. And I think you will find that they are VERY responsive to this.

Thank you

**Comment by RPiList** [comment]
Domain has been removed. Thx for letting us know. Greetings.
