### ISSUE TITLE
Whitelist für Corona-Blacklist

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#171]
Hier gibt es eine Whitelist für Corona-Updates: https://github.com/covid19cyber/goodlist vielleicht ist die nützlich, um false-positives zu identifizieren.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

Nur kann ich da leider keine Liste finden. Unter dem ersten Link steht, dass die Goodlist umgezogen ist. An der neuen Location gibts dann keine Whitelist... sondern nur eine Liste von Domains in Bezug auf Covid19 "wahrscheinlich" ungefährlich sind.

**Comment by BulldozerPete** [comment]
Bei mir funktioniert die Liste wieder. Ich mache jetzt eine Kopie und erstelle eine Corona-Whitelist im /dev Verzeichns.
Das Issue kannst Du dann bitte schließen.

**Comment by BulldozerPete** [comment]
Hier ist der pull-request: https://github.com/RPiList/specials/pull/174

**Comment by RPiList** [comment]
Mit der Whitelist habe ich noch so meine Probleme. :-)

Eine eigene Whitelist für eine Blacklist ist nicht praktisch. Also wenn die Corona-WL akzeptiert würde, dann würde sie in der Standard-WL landen.

Bei näherer Betrachtung finden sich aber viele falschen URLs. Insoweit sieht es so aus, als wenn die WL genauso schlampig zusammen getackert wurde, wie die BL. :-)

![Unbenannt](https://user-images.githubusercontent.com/56664851/78040570-e9d78080-736f-11ea-92cb-8b7e29449cf1.PNG)

Die Corona-Liste füttert sich derzeit aus eigenen Ergänzungen sowie Ergänzungen die wir von einer anderen Liste erhalten.
Bei allen Corona-URLs die wir finden werden nur die Treffer hinzugefügt, die Corona oder Covid im Domainnamen tragen. Also "covid19-rki.de" würde gefiltert, covid19.rki.de würde nicht gefiltert. Damit wird dem Umstand Rechnung getragen, dass die erste Domain extra jetzt registriert wurde und daher wahrscheinlich fake ist, während die zweite Domain schon vorher bestand und nur eine Subdomain erstellt wurde.

Im Grunde ist es für deutschsprachige Nutzer aber egal, ob eine legitime Covid19 Domain aus Indien gesperrt wurde. Wenn also nur eine handvoll deutscher Domains zu dem Thema wichtig sind, dann kriegen wir das über eine manuelle Einpflege besser hin.

**Comment by RPiList** [comment]
Kleine Statistik:
In der Corona-BL sind derzeit 120.340 Einträge.
Davon sind 294 Einträge mit der TLD .de, .at oder .ch.

In der Corona-WL ist nur eine .de Domain dabei und 5 .ch Domains.

![Unbenannt](https://user-images.githubusercontent.com/56664851/78047106-4474da80-7378-11ea-9d23-149a11be06fd.PNG)

Die "corona.rki.de" Domain nehme ich also in die allgemeine WL auf. Die wird zwar derzeit ebenfalls nicht blockiert, aber dann geschieht das auch künftig nicht. Bei den anderen Domains warten wir einfach ab, bis Nutzer sich melden und diese als "legit" bezeichnen.
