### ISSUE TITLE
 false-positive apple.stackexchange.com

### ISSUE THREAD

**Issue by XnS** [RPiList/specials#1711]
It's a Q&A site for power users of Apple hardware and software. Looks like it's the only stackexchange.com site which has been actively blocked.

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
`||apple.stackexchange.com^`

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
