### ISSUE TITLE
Amazon.eu stört PrimeGaming

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1716]
Wenn man sich auf `https://gaming.amazon.com/home` anmeldet für die monatlichen Spiele.
wird man nach dem Login auf `https://gaming.amazon.de/prime/` verwiesen.
ist ein CNAME von `gaming.amazon.eu `und damit greift die `amazon.eu` wildcard Regel.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Amazon.eu wurde entfernt und ist jetzt auf der Phishing-Whitelist
