### ISSUE TITLE
Phishing List: `rappler.com` false positive

### ISSUE THREAD

**Issue by vincejv** [RPiList/specials#1718]
Wiki page: https://en.wikipedia.org/wiki/Rappler

> Rappler ([portmanteau](https://en.wikipedia.org/wiki/Portmanteau) of the words "rap" and "ripple")[[3]](https://en.wikipedia.org/wiki/Rappler#cite_note-celebratedPhilippineNewsBoss-3) is a [Filipino](https://en.wikipedia.org/wiki/Mass_media_in_the_Philippines) [online news](https://en.wikipedia.org/wiki/Online_news) website based in [Pasig](https://en.wikipedia.org/wiki/Pasig), [Metro Manila](https://en.wikipedia.org/wiki/Metro_Manila), the Philippines. It was founded by [2021 Nobel Peace Prize](https://en.wikipedia.org/wiki/2021_Nobel_Peace_Prize) laureate [Maria Ressa](https://en.wikipedia.org/wiki/Maria_Ressa) along with a group of fellow Filipino journalists as well as technopreneurs. It started as a [Facebook](https://en.wikipedia.org/wiki/Facebook) page named MovePH in August 2011[[4]](https://en.wikipedia.org/wiki/Rappler#cite_note-4) and evolved into a website on January 1, 2012.[[5]](https://en.wikipedia.org/wiki/Rappler#cite_note-aboutrappler-5)

> In 2018, agencies under the [Philippine government](https://en.wikipedia.org/wiki/Government_of_the_Philippines) initiated legal proceedings against Rappler.[[6]](https://en.wikipedia.org/wiki/Rappler#cite_note-6) Rappler and its staff alleged it was being targeted for its revelations of corruption by government and elected officials, the usage of bots and trolls favoring [Rodrigo Duterte](https://en.wikipedia.org/wiki/Rodrigo_Duterte)'s administration,[[7]](https://en.wikipedia.org/wiki/Rappler#cite_note-propagandaWarWeaponizingInternet-7) and documenting the [Philippine drug war](https://en.wikipedia.org/wiki/Philippine_drug_war).[[8]](https://en.wikipedia.org/wiki/Rappler#cite_note-guardianCyberLibel-8)[[9]](https://en.wikipedia.org/wiki/Rappler#cite_note-cnnWhatIsRappler-9)

> In October 2021, Rappler co-founder Ressa, alongside Russian journalist [Dmitry Muratov](https://en.wikipedia.org/wiki/Dmitry_Muratov), was awarded the [Nobel Peace Prize](https://en.wikipedia.org/wiki/Nobel_Peace_Prize) for safeguarding freedom of expression in their homelands.[[10]](https://en.wikipedia.org/wiki/Rappler#cite_note-10)

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
