### ISSUE TITLE
Kein listen updaten

### ISSUE THREAD

**Issue by SickSAM666** [RPiList/specials#172]
Hallo zusammen,

ich hab sämtliche liste einmal gelöscht und mit den list hier geupdatet, bekomme aber bei vielen listen wenn ich sie via Update Gravity (list of blocked domains) update bekomme ich die Meldung 

> 
```
  [i] Target: raw.githubusercontent.com (notserious)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (Streaming)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (Phishing-Angriffe)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (spam.mails)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (Win10Telemetry)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (easylist)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (samsung)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (crypto)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (jugendschutz)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (Fake-Science)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (DisconnectMe)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (Corona-Blocklist)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (malware)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (SmartTV.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (AmazonFireTV.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (W10TelemetryBlocklist)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: gitlab.com (notrack-malware.txt)
  [✓] Status: Retrieval successful

  [i] Target: v.firebog.net (Easyprivacy.txt)
  [✓] Status: Retrieval successful

  [i] Target: gitlab.com (notrack-blocklist.txt)
  [✓] Status: Retrieval successful

  [i] Target: v.firebog.net (Prigent-Ads.txt)
  [✓] Status: No changes detected

  [i] Target: v.firebog.net (AdguardDNS.txt)
  [✓] Status: No changes detected

  [i] Target: hosts-file.net (ad_servers.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: adaway.org (hosts.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (hosts)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [i] Target: raw.githubusercontent.com (no-gez.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 50105
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 45983
  [i] Nothing to whitelist!
  [i] Number of regex filters: 3
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

```
 hab ich irgendwas falsch gemacht ? 
danke für eure hilfe schonmal

**Comment by RPiList** [comment]
Am besten "raw.githubusercontent.com" auf die Whitelist im Pihole setzen. Es schaut so aus, als wenn nur diese Listen nicht geladen werden konnten.

Danach mal prüfen, ob es eine Liste gibt, die "raw.githubusercontent.com" sperrt.

**Comment by SickSAM666** [comment]
Hab ich gemacht und dann nach github gesucht das waren die Ergebnisse
>  Match found in Whitelist
>    raw.githubusercontent.com
>  Match found in https://v.firebog.net/hosts/Easyprivacy.txt:
>    collector-cdn.github.com
>    collector.githubapp.com
>  Match found in https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt:
>    collector.githubapp.com
>  Match found in https://v.firebog.net/hosts/AdguardDNS.txt:
>    prxio.github.io
>    collector-cdn.github.com
>    collector.githubapp.com

aber selbst wenn ich die rausnehme werden die anderen nicht geupdatet.
Habe es auch versucht, das Piehole einfach mal 5 miunten zu deaktivieren und dann die updates zu ziehe, kein erfolg , ebenso wenn ich alle lösche und dann einzeln einfüge. dann werden sie auch nicht nachgeladen.

**Comment by RPiList** [comment]
Es geht nur um "raw.githubusercontent.com", weil da liegen die Listen. Wenn ich das richtig verstehe, haben Sie die Domain inzw. ge-whitelisted, was aber nicht nötig war, weil die Domain in keiner Liste vertreten ist.

D.h. das Problem sind nicht die Listen. Dann stellt sich die Frage, welchen Upstream DNS-Server Sie nutzen. Auf welchem System läuft Pihole? RaspiPi oder VM?

**Comment by SickSAM666** [comment]
Ich nutze unbound also upstream DNS.
Meine Vermutung ist das ich beim Einrichten einen Fehler gemacht habe.
Ich muss heute Abend nochmal in Ruhe schauen und melde mich dann wieder.
Weil wenn ich über shh schaue bekommt das pihole wohl keine Verbindung zu GitHub. Die genaue Fehlermeldung schreibe ich heute Abend dazu. Ich glaub es war no Route to host.

**Comment by RPiList** [comment]
Wenn das Problem bei Unbound vermutet wird, dann einfach den Upstream DNS Server in 1.1.1.1 ändern. Funktioniert Pihole dann wieder, ist Unbound das Problem.

**Comment by ST8FAN** [comment]
Habt ihr da eine Lösung gefunden? ich kann auch keine Listen mehr updaten, wenn unbound aktiv ist.

**Comment by RPiList** [comment]
Das o.g. schon alles durchprobiert? Zeiteinstellungen auf dem Pi geprüft usw...?

**Comment by ST8FAN** [comment]
Also Zeiteinstellung passt laut Ausgabe von putty.
komischerweiße kann ich ganz normal surfen, wenn unbound aktiv ist. aber beim gravity-update bekomme ich die Fehlermeldung: DNS Resolution currently unavalible.

**Comment by ST8FAN** [comment]
Habe das Problem nach längerem Suchen gefunden... Tippfehler... Wahnsinn
