### ISSUE TITLE
Liste: Phishing-Angriffe: Amazon-Images-Seite

### ISSUE THREAD

**Issue by bobbie12** [RPiList/specials#1721]
Wenn man sich auf der Amazon-Seite bewegt, wird u.a. images-eu.ssl-images-amazon.com geblockt und man sieht keine Bilder.

In der Liste "Phishing-Angriffe" steht u.a.:

||ssl-images-amazon.com^

Gehört das denn dort nicht raus, oder verstehe ich die "||"-Bedeutung nicht?

**Comment by RPiList** [comment]
Vielen Dank für die Hilfe. Domains wurden entfernt. Viele Grüße
