### ISSUE TITLE
Blocked stuff from Amazon

### ISSUE THREAD

**Issue by oe3gwu** [RPiList/specials#1727]
Today my Pihole blocks stuff from Amazon, so I cant use the site anymore correct.

I am not sure if this down in the screenshot is everything you block or if there is more. But disabling the pihole makes the site works correct.

![image](https://github.com/user-attachments/assets/15666f50-d498-4351-b3a4-5500bfda2d03)

![image](https://github.com/user-attachments/assets/8cee8c8d-6e0b-45a2-a1ac-48e184b9613f)

**Comment by RPiList** [comment]
Hi,

the issue has been fixed a few days ago. Please update your Pihole lists and everything should work as expected. Greetings.
