### ISSUE TITLE
Whitelist Universität

### ISSUE THREAD

**Issue by TheBlueFireFox** [RPiList/specials#173]
Guten Tag
In der Blockliste Phishing-Angriffe ist die ZHAW.ch Adresse drin, dies ist eine Universität aus der Schweiz (mein Uni). Wäre es möglich diese zu entfernen oder würde dies Umstände machen?
Vielen Dank für diese Listen 
Adrian

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist jetzt gefixt.
