### ISSUE TITLE
Phishing-E-Mails von "zoll-giessen.de", "zoll-bremen.de" und "zoll-iserlohn.de"

### ISSUE THREAD

**Issue by mschabhuettl** [RPiList/specials#1732]
Phishing-E-Mails von

```
zoll-giessen.de
zoll-bremen.de
zoll-iserlohn.de
```

Über die Domains "zoll-giessen.de", "zoll-bremen.de" und "zoll-iserlohn.de" werden aktuell E-Mails mit gefälschten Zahlungsaufforderungen versendet. Denkbar ist, dass auch ähnliche Domains mit dem Namen einer anderen Stadt verwendet werden. Die Zollverwaltung nutzt ausschließlich die E-Mail-Domains "...@zoll.bund.de" und "...@zoll-auktion.de".

Quelle: https://www.zoll-auktion.de/auktion/aktuelle_nachrichten.php

LG, Matthias

**Comment by RPiList** [comment]
Vielen Dank für die Info.

Alle zoll- Domains werden jetzt vom Crawler automatisch den Listen hinzugefügt. Viele Grüße
