### ISSUE TITLE
apple.com.au added to RPiList-Phishing.txt

### ISSUE THREAD

**Issue by kylewintaur** [RPiList/specials#1737]
Hopefully this is the right repo to report this? Obviously this is a legitimate domain.

Looks like it was added in commit [8bd7092c141f8f66ddfe1fa1d25e38ec57957e9f](https://github.com/RPiList/specials/commit/8bd7092c141f8f66ddfe1fa1d25e38ec57957e9f)

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
