### ISSUE TITLE
amazoncognito.com in phishing list

### ISSUE THREAD

**Issue by bsdlp** [RPiList/specials#1738]
amazon cognito is an AWS service that provides an identity platform - https://aws.amazon.com/cognito/
please consider removing it so it does not block legitimate login traffic to legitimate services

**Comment by k4n30** [comment]
And amazonworkspaces.com

**Comment by RPiList** [comment]
Thx for supporting our project. We tried to find and whitelist all official amazon domains but we obviously missed these.

Domains have been removed. Greetings
