### ISSUE TITLE
Wieder mal Spam Domians

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1740]
aurasgo.com
aliqarat.com
oaugweb.info

**Comment by RichardBeisser** [comment]
von mir auch wieder:

abstrately.com
nookquip.com
atomsyl.com
housandre.com
binaryno.com
jointensit.com
metalroofinginnovationshelp.com
mosquire.com
energytismw.com

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
