### ISSUE TITLE
remove rippling.com from malware

### ISSUE THREAD

**Issue by bsdlp** [RPiList/specials#1747]
hey team - i see these entries on the malware list:

  ||email.gh-mail.rippling.com^
  ||link.rippling.com^

these are valid domains and are used by rippling, an hr/it company, to send mail to employees for things like paystubs. could you please remove them? thanks

**Comment by RPiList** [comment]
Hi,
these domains are marked as combined_disguised_clickthroughs and combined_disguised_mail_trackers by the Adguard Team. If they delete the domains, they will be removed from our list automatically.

Greetings.
