### ISSUE TITLE
Shouldn't the Phishing list have only Phishing?

### ISSUE THREAD

**Issue by DanaGoyette** [RPiList/specials#1757]
I keep seeing names get blocked on machines that are set to only have the Phishing list, and many of them seem more like ads or trackers, not phishing.

```
paa-reporting-advertising.amazon
amazon-adsystem.com
ingest.apple-studies.com
x.blueduckredapple.com
```

I had family members get annoyed when I turned on ad blocking network-wide (seriously?), so I have the default set to block just malware and phishing, and I include only some of the machines in stricter filters.

**Comment by SGirl-Zockt** [comment]
then just dont use this list??????

**Comment by RPiList** [comment]
Hi,

thx for supporting our project.

Domains have been removed and partially added to other blocklists.

Greetings.
