### ISSUE TITLE
Span Domians angeblich von Bank

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1758]
Moin Sprecher und Chat

meine Bank war vor Phischung Linkgs mit der Domian bawag.at-stornierung.info
wohl sind auch versionen mit BankXY.at-stornierung.info unterwegs

at-stornierung.info

Libe grüße
Vicky

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
