### ISSUE TITLE
Adguard DNS list

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#176]
Habe die Adguard DNS-Liste gefunden: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
Da sind nur Hostnamen enthalten.
Falls diese Liste automatisiert die Hostnamen in bestehende Filterlisten übernehmen könnte, wäre das super.

Andernfalls ist die Übersicht ganz gut um zu erkennen, dass viele Tracking Hostnamen mit "affiliates/analytics/metrics/pixel/stats/track/tracker/tracking/.irgendwas.de" beginnen. Vorschlag wäre die RegEx-Filter zu ergänzen.

**Comment by RPiList** [comment]
Die Liste wurde jetzt in unsere Easylist geschoben.
