### ISSUE TITLE
unisex-friseure.de ist KEIN Porno, sondern ein Friseurladen

### ISSUE THREAD

**Issue by thomasmerz** [RPiList/specials#1769]
Das ist ein Friseurladen:
>Wellness und Käffchen gibt’s hier nicht, dafür coole Musik, lockere Atmosphäre und eine ehrliche Meinung. Wir wissen, was gerade angesagt ist und bilden uns ständig weiter. Egal ob Spitzenschneiden oder Radikalveränderung - wir lieben Haare und freuen uns auf Dich!

​Bitte aus dem pornblock5 rausnehmen. Oder soll ich kurz einen PR dafür machen?
>Blocklisten/pornblock5
DNSMASQ/pornblock5
Mikrotik-Hosts/IPv4/pornblock5
Mikrotik-Hosts/IPv6/pornblock5

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Werde gleich mal schauen, wie viele false positives vom Crawler mit "unisex" aufgenommen wurden. Es sei denn jemand hat wirklich eine Website... wenn Leute an der Uni Sex haben... :-)

> 
> ​Bitte aus dem pornblock5 rausnehmen. Oder soll ich kurz einen PR dafür machen?
> 

Ne, ist so schon okay. Weil ich dann direkt den Whitelist-Eintrag in der Porn-Whitelist mitsetze. Sonst wird die Domain beim nächsten Cert-Update wieder gefunden.

Viele Grüße
