### ISSUE TITLE
MEmu Webseite geblockt

### ISSUE THREAD

**Issue by Akamaru** [RPiList/specials#177]
Auf der easylist wird xyaz.cn und www.xyaz.cn geblockt. Das ist die offizielle Webseite vom MEmu Android Emulator.
Siehe https://forum.xda-developers.com/wiki/Category:Emulators

**Comment by BulldozerPete** [comment]
Habe ein Pull-Request erstellt.

**Comment by RPiList** [comment]
Ist jetzt gefixt.
