### ISSUE TITLE
false positiv

### ISSUE THREAD

**Issue by derKutsch** [RPiList/specials#1777]
Blocklisten/Corona-Blocklist

epidemic.derkutsch.at^

Keine Ahnung wie eine subdomain, welche auf eine Referal-Seite (von epidemicsound) auf einer Corona-Blockliste landen konnte...

**Comment by derKutsch** [comment]
noch ein false positiv ist:

epidemicsite.com

Vermutlich auch in der Corona Block liste, ist aber das Entwicklerportal von Epidemicsound.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden entfernt.

> epidemic.derkutsch.at^
> 
> Keine Ahnung wie eine subdomain, welche auf eine Referal-Seite (von epidemicsound) auf einer Corona-Blockliste landen konnte...

Weil das in Corona-Zeiten eine ganz beliebte Abzocker-Methode war. Corona, Pandemic, Endemic, Epidemic waren übliche Begriffe die man auf Bullshitt-URLs fand, die dann Wundermittel versprochen haben.

Viele Grüße
