### ISSUE TITLE
Spam Domians aml wieder

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1784]
ssepfoam.info
easuret.pics

**Comment by RichardBeisser** [comment]
auch wieder was von mir:

ventasdevideoscopios.com
auftrag-rezeptfrei.de
mahuranacademy.com
chrysanthemumsad.shop
budloom.com
statoes.com
hybridwow.com

**Comment by RPiList** [comment]
Vielen Dank für die Info, Domains wurden hinzugefügt. Viele Grüße
