### ISSUE TITLE
Check mal ab

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#1785]
https://nova-erlebnis.de/energy-rbsbl/?fbclid=IwY2xjawFqShNleHRuA2FlbQEwAAEdccpZjLLofgdvPO9bsJmSzolHCK5SnWp4FYHUsL_NcrbjrksOHZL7lSjU_aem_SlKzrIkSfoO7Sfq9oKYv4A

Laut Google haben die auch so sachen gemacht wie Fake gewinnspiele mit irgendwelchen Gutscheine für Saturn, da her bin ich mir nicht so sicher ob es echt ist, weil das Impressum stimmt

**Comment by RPiList** [comment]
Vielen Dank für die Info, Domains wurden hinzugefügt. Viele Grüße
