### ISSUE TITLE
Snapchat & Pihole

### ISSUE THREAD

**Issue by blub4747** [RPiList/specials#1790]
Hallo RPiList team,
Ich habe bei jemanden ein Pihole aufgesetzt und alle RPiListen importiert.
Leider können meckernten die   Kinder/Jugentlichen in dieser Anlage das  Snapchat Probleme macht.
Und somit wurde für den Augenblick Pihole wieder abgestellt.
Hoffentlich können wir das Problem lösen, denn die Blockzahlen waren schon sehr positiv.
Fragen:

Welche Liste Liste deckt Snapchat ab ?
Oder ist es überhaupt in einer von den Listen mit inbegriffen ?
Oder gibt es eine externe Liste welche Snapchat abdeckt ?

Danke für alle Antworten oder Ideen,
blub4747

**Comment by RPiList** [comment]
Hi,

es gibt keine Liste von uns, die absichtlich Snapchat blockiert.

Daher ist es das Beste in die Log-Daten des Pihole zu schauen um festzustellen welcher Eintrag dafür sorgt, dass Snapchat nicht ordentlich funktioniert.

Viele Grüße

**Comment by SGirl-Zockt** [comment]
Guten Tag,

Ich benutzte auch die Liste des RpiList Teams und habe keine Probleme mit Snapchat

**Comment by joestr** [comment]
Laut diesem [Snippet](https://gitlab.com/-/snippets/3638594) sind das zumindest ein paar Domains welche Snapchat benutzt:

```
addlive.io
feelinsonice.com
sc-cdn.net
sc-corp.net
sc-gw.com
sc-jpl.com
sc-prod.net
sc-static.net
snapads.com
snapchat.com
snap-dev.net
snapkit.com
snapmap.com
snapmap.org
snapmaps.com
snap-storage-cdn.l.google.com

```

**Comment by RPiList** [comment]
Die sind alle nicht in unseren Listen vertreten. Ich nehme mal an OP hat noch dritte Listen installiert, die die Probleme verursachen. Insoweit kann das hier geschlossen werden. Viele Grüße
