### ISSUE TITLE
Qidi Webshop

### ISSUE THREAD

**Issue by Bara** [RPiList/specials#1791]
Moin,
warum genau ist der Shop von Qidi "qidi3d.com" [gelistet](https://github.com/RPiList/specials/blob/master/Blocklisten/notserious#L60439)? Erscheint zwar "unseriös", aber ist ein bekannter Hersteller von 3D-Druckern, Zubehör und Filamenten. Auch deren Support ist, aus eigener Erfahrung, sehr gut.

**Comment by RPiList** [comment]
Hi,

alle Einträge auf der Liste sind durch entsprechende Meldung bzgl. "Fake-Shop" auf der Liste gelandet.

Wann und über welche Quelle die Domain eingebracht wurde, kann ich auf die Schnelle nicht nachvollziehen.

Aber ich kann sehen, dass sie nicht erneut eingespielt werden würde. Das spricht dafür, dass es entweder von vorne herein ein "False positive" war oder dass sich das Problem erledigt hat.

Insoweit wird die Domain einmalig entfernt aber nicht in die Whitelist aufgenommen. Wenn Sie dann wieder eingespielt wird, ist es leichter nachzuvollziehen, woher die Meldung kommt.

Vielen Dank für den Hinweis. Viele Grüße
