### ISSUE TITLE
www.schiffahoi.de ist ein Reisebüro

### ISSUE THREAD

**Issue by ArnaudFeld** [RPiList/specials#1792]
www.schiffahoi.de ist ein Reisebüro das online wie auch in 3 Reisebüros vor Ort was macht

:)

**Comment by RPiList** [comment]
Ich weiß nicht was ich mit der Meldung machen soll. Soll die Domain geblockt werden oder wird sie geblockt und der Block soll entfernt werden?

**Comment by ArnaudFeld** [comment]
@RPiList sorry 🤦😂 das soll entblockt werden 😁

**Comment by RPiList** [comment]
Adding to the spamlist just happend three days ago.

Please check https://github.com/RPiList/specials/issues/1789 and check back with the user who reported the domain.

I guess the spamed a lot?

**Comment by RichardBeisser** [comment]
Tatsächlich handelt es sich um eine Unachtsamkeit von mir.
Ich erhalte regelmäßig Emails die verschiedene Schiffsreise-Angebote bewerben. Die Links in den Emails lauten  letter.rebellen-news.de. Man wird dann weitergleitet auf www.ahoi-schiff.de

Ich habe bei diesem Anbieter weder jemals etwas gebucht noch dort angefragt.

Daher mein Vorschlag:
schiffahoi.de aus der Blocklist nehmen, dafür dann ahoi-schiff.de aufnehmen

**Comment by RPiList** [comment]
Okay, alles erledigt.
