### ISSUE TITLE
Spam URLs

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1793]
Alle Domians die ich finde aktuell haben das Muster, könnte man eigenlich ein skrip machen das alle Domins mit aaabbbccc.shop bis zzzzzzzzz.shop speert
cccfffbbb.shop
bbbvvvccc.shop
kkqqqccc.shop
bbbeeeppp.shop

Ander Spam Domins
joveannos.club

**Comment by RPiList** [comment]
Hi,

ich habe jetzt erst mal nur die angegebenen Domains geblockt. Sollte das mit dem aaabbbccc.shop öfters vorkommen, blocken wir die alle. 

Viele Grüße
