### ISSUE TITLE
False positive: lacity.org

### ISSUE THREAD

**Issue by Nivl** [RPiList/specials#1795]
`lacity.org` is a legit website from the city of Los Angeles. You can find links to it on their .gov version https://lacity.gov/myla311 and you have to use it to deal with city-related stuff.

From https://lacity.gov/myla311:
> Need to reach us after hours? Submit requests online 24/7 at https://myla311.lacity.org/.

It’s in this list: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails

**Comment by RPiList** [comment]
Thx for supporting our project. Domains have been removed. Greetings.
