### ISSUE TITLE
False positive domains

### ISSUE THREAD

**Issue by devinkuhn** [RPiList/specials#1797]
The following domains appear to have been blacklisted unintentionally.  Not able to find a rhyme or reason.  I am a representative of this organization if more information is needed.

applefcu.aa.exabeam.com
applefcu.biz
applefcu.cc.exabeam.com
applefcu.cloudflaresso.com
applefcu.com
applefcu.dl.exabeam.com
applefcu.info
applefcu.io
applefcu.me
applefcu.net
applefcu.officespacesoftware.com
applefcu.org
applefcu.ourreferralengine.com
applefcu.pages.dev
applefcu.sandboxbanking.com
applefcu.us
applefcu.workers.dev
appleservices.com
appleservices.org
applefcureferral.paragonsolutions.com
howboutthemapples.org
testme4applefcu.org
theotherapple.org

**Comment by RPiList** [comment]
Thx for supporting our project. Domains have been removed. Greetings.
