### ISSUE TITLE
false positive - stamps-app.nl & stamps-app.com

### ISSUE THREAD

**Issue by ikheetjeff** [RPiList/specials#1807]
Hi,

Your malware list includes the domain “stamps-app.nl” and “stamps-app.com”. This seems, as far as I can see, unjustified.

These are domains of a (fairly young) app. It is an app for sick people who can inform and update their loved ones in an easy way, and to which family can then respond. 

Doesn't seem like malware to me. Or do you have other evidence?

Thanks.

**Comment by RPiList** [comment]
Thx for supporting our project. Domains have been removed and whitelisted to prevent future listing. Greetings.
