### ISSUE TITLE
Remove domain www2.internet2.edu from malware block list

### ISSUE THREAD

**Issue by enderqa** [RPiList/specials#1814]
In file: https://raw.githubusercontent.com/RPiList/specials/refs/heads/master/Blocklisten/malware

Please remove domain `www2.internet2.edu^` . [Internet2](https://en.wikipedia.org/wiki/Internet2) is an United States based Research and Education (R&E) networking association. Thanks in advance.

**Comment by RPiList** [comment]
Hi

thx for supporting our project.

Your domain has been flagged by the Adguard Team for being a combined disguised clickthrough domain. This is considered as malware.

As soon as the Adguard Team deletes its flagging, it will be removed in our list as well.

Greetings
