### ISSUE TITLE
[Whitelist Add]: *.vk-apps.com | *.vk-apps.ru

### ISSUE THREAD

**Issue by ramazansancar** [RPiList/specials#1818]
This creates problems in accessing the website. This also prohibits community applications, including official VK applications on mobile devices. I have deployed the banlist in pi-hole.

Pi-Hole Search:
```log
Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  ||vk-apps.com^
Exact match found in exact whitelist
  prod-app7058363-28dd3cc894b5.pages-ac.vk-apps.com
  
  
----
Match found in https://v.firebog.net/hosts/RPiList-Malware.txt:
  ||vk-apps.ru^
```

**Comment by RPiList** [comment]
Thx for supporting our project. Domains have been removed. Greetings.

**Comment by ramazansancar** [comment]
Thanks 🙌

https://github.com/RPiList/specials/commit/a4737783b3fbd42b1567ad4435343c7063cf7dab#diff-e9cfc20c4ddb277c57d70f25456d844fa67c182cd1af2bedefb0fa66371bf502L395130-L395135
