### ISSUE TITLE
False positive apple.se in Phishing-Angriffe list

### ISSUE THREAD

**Issue by hlindqvist** [RPiList/specials#1820]
`apple.se` is a legit Apple domain (for web traffic it seems to redirect to `https://www.apple.com/se`)

With this in mind the following entry in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe causes unnecessary breakage and confusion:

```
||apple.se^
```

**Comment by RPiList** [comment]
Thx for supporting our project. Domain has been removed. Greetings
