### ISSUE TITLE
False Positive: yahoo.de^ in DomainSquatting

### ISSUE THREAD

**Issue by DukeSniper** [RPiList/specials#1821]
Domain ist tatsächlich auf Yahoo registriert, Nameserver der Domain gehören ebenfalls Yahoo und HTTP-Requests werden mit ner sauberen 301 an de.yahoo.com umgeleitet. Und es gibt nachweislich zustellbare eMail-Adressen in dieser Domain
![image](https://github.com/user-attachments/assets/0a849a0e-82cd-4c70-8548-0fa61156addc)
![image](https://github.com/user-attachments/assets/e97beb24-9231-4268-9b45-e6bf15c77b48)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernet. Viele Grüße
