### ISSUE TITLE
AVG Fake-Webseite-Schutz-DNS blockieren

### ISSUE THREAD

**Issue by Naimkr27** [RPiList/specials#1822]
Hallo,

habt Ihr eine Anleitung oder Liste, wie ich bei AVG Internet Security die DNS-Anfragen blockieren kann. Ich habe in meiner Fritzbox, die entsprechenden Ports blockieren, so dass AVG eigentlich keine DNS-Anfragen stellen kann.

Aber die Anfragen laufen über Port 443/tcp. Wenn ich den Port sperre, geht mein ganzes Internet nicht. 

Natürlich kann ich in AVG die funktion deaktivieren, aber die können meine Kinder einfach wieder aktivieren und so gesperrte Webseiten aufrufen.

Habt Ihr eine lösung? ich habe eine PiHole auf meinem Proxmox installiert.

Danke und liebe Grüße

**Comment by RPiList** [comment]
Hi, da wir das Programm selbst nicht nutzen, können wir leider keinen Support geben. Evtl. das Programm anweisen selbst das Pihole als DNS zu nutzen. Aber wie gesagt, keine Ahnung ob das geht.
