### ISSUE TITLE
False positive: aol.de und dlh.de in DomainSquatting

### ISSUE THREAD

**Issue by DukeSniper** [RPiList/specials#1823]
AOL.de gehört zu Yahoo, auch hier sauberer DNS und valide eMail-Adressen in meinem Kundenbestand

![image](https://github.com/user-attachments/assets/b6926a6d-c35c-465c-81ed-2ef17baa8ba3)

**Comment by DukeSniper** [comment]
dlh.de gehört der Deutsche Lufthansa, auch wenn das aus dem DNS nicht so direkt hervorgeht. HTTP-Forwarding stimmt aber
![image](https://github.com/user-attachments/assets/f285985a-6e1b-4748-a069-404470581986)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
