### ISSUE TITLE
Potentieller False Positive in Phishing-Mails: amazonses.com

### ISSUE THREAD

**Issue by DukeSniper** [RPiList/specials#1825]
Amazonses.com ist die Infrastruktur-Domain des [Amazon Simple EMail Service](https://docs.aws.amazon.com/de_de/ses/latest/dg/Welcome.html), da gehen Unmengen legitimer Mails drüber.

Eingetragen am 29.08.2024 mit [Commit 4185602](https://github.com/RPiList/specials/commit/418560253ad629d87f6aa785de34d187c12fbe27).

Würde ich - selbst wenn die Server vereinzelt missbraucht werden - für nen False Positive halten, denn sonst müssten MailChimp, SendGrid und Co auch gelistet werden.

Spannend übrigens auch der Eintrag eine Zeile darunter (amazonses.comxing.comrwth-aachen.degoogle.comoutlook.com), aber das nur am Rande

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Domain wurde entfernt. Die andere URL ist das Ziel der Liste und Overblocking, weil wir nicht alle offiziellen Amazon-URLs kennen, ist dann leider Kollateralschaden.

Soweit ich das sehe kommuniziert Amazon aber auch nicht, wie deren offizielle Domains lauten. Sonst wäre das etwas einfacher...

Viele Grüße
