### ISSUE TITLE
Fakeshop

### ISSUE THREAD

**Issue by nrailuj** [RPiList/specials#1826]
`flippershopde.com` ist ein Fakeshop.

**Comment by RichardBeisser** [comment]
> `flippershopde.com` ist ein Fakeshop.

Du hast scheinbar nicht alle Listen von hier abonniert.
Die Domäne ist bereits in der Liste "notserious" enthalten.

**Comment by RPiList** [comment]
> `flippershopde.com` ist ein Fakeshop.

Thx, Domains was already on the list. But don't worry. Just keep them coming. Our software filters double entries so no harm done. Greetings.
