### ISSUE TITLE
False positive in pornblock5: libe.net ist ein privater Blog

### ISSUE THREAD

**Issue by ArnaudFeld** [RPiList/specials#1829]
libe.net ist ein privater Blog. 
Mir ist nicht ganz klar warum der da drin ist. Falls es mal einen Grund gab, aktuell nicht mehr vorhanden.
Zwar viel Werbung drauf sehe nix von Porn

Daher bitte runternehmen :)

![image](https://github.com/user-attachments/assets/7b69aff5-b78b-4a45-be79-1a68757175a2)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
