### ISSUE TITLE
False positive in 2 Listen: ELV.de ist ein Elektronik Firma

### ISSUE THREAD

**Issue by ArnaudFeld** [RPiList/specials#1831]
elv.de ist (warum auch immer) in die "DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-2" und "DomainSquatting/DE/Volks-und-Raiffeisenbank/VR-PLZ-4" gekommen.

Glaube jetzt weniger das ELV hier was böses macht als bekannte Elektronik Firma.

//EDIT: zweite List nachgetragen + Titel angepasst
grüße,
Arnaud

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
