### ISSUE TITLE
False Positive: banking-app-links.de

### ISSUE THREAD

**Issue by bennokress** [RPiList/specials#1834]
Mir ist in der Malware-Liste ein False Positive aufgefallen: banking-app-links.de

Die Seite ist eine Domain der Atruvia, die der IT Dienstleister mehrerer Banken in Deutschland ist (siehe [Impressum hier](https://vr.banking-app-links.de/service/impressum.html)). Die Seite sollte daher sogar bestenfalls in Whitelists auftauchen 😉

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
