### ISSUE TITLE
False Positive - Malware: bbva.com.ar

### ISSUE THREAD

**Issue by MenosOcho** [RPiList/specials#1835]
bbva.com.ar is the Argentinean website of BBVA Bank, it is valid and not a malware site.
The current locked subdomain block its login page.

**Comment by RPiList** [comment]
Hi,

bbva.com.ar is currently not on our lists.

However, there are a few subdomains of the domain mentioned above on our malware list.

For example:
malware:||img2.bbva.com.ar^
malware:||pages.comunicaciones.bbva.com.ar^
malware:||pages.mail.bbva.com.ar^
malware:||smetrics.bbva.com.ar^
malware:||stmetrics.bbva.com.ar^

Those domains are marked as combined_disguised_tracker domains and combined_disguised_email_tracker domains by the Adguard Team

When the Adguard Team removes their entries, they will be deleted from our list automatically.

Greetings

**Comment by MenosOcho** [comment]
Thank you for your prompt reply.
I don't disagree that these subdomains could be used for tracking, but I do
disagree that they are considered malware subdomains.
They are wrongly classified, that's why i'm reporting it, because they
shouldn't be into RPiList-Malware.txt, same for the other bank portal
bancogalicia.com.ar
Regards

**Comment by RPiList** [comment]
Hi,

thx for replaying to my post.

> I don't disagree that these subdomains could be used for tracking

It's not about "could be used", they are being used.

For example: pages.mail.bbva.com.ar

bbva.com.ar is not being blocked. Even Mail.bbva.com.ar is not blocked. A Website or an eMail has to  open the URL "pages.mail.bbva.com.ar" to block only the access to that single domain. Everything else works.

The problem usually is that companies places so called third party tracking on obscure subdomains.  They have their own tracking on bbva.com.ar... but third party tracking must be placed on subdomains to be working properly.

First party tracking is not being considered as malware, but third party tracking is.

Further: Blocking third party tracking usually doesn't break the website. If it does you can send an appeal to the Adguard Team. But then again, if it does, it's usually first party tracking and a different story.

Alternatively, you can whitelist the entry in question in your pihole.

Sorry I can't be of any help. Greetings.
