### ISSUE TITLE
TheOnion& ChildProtection

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#1839]
Bei spezifischen Filtern wie
```
  ||adbot.theonion.com^
  ||adgraphics.theonion.com^
  ||manuel.theonion.com^
  ||oascentral.theonion.com^
  ||reporting.theonion.com^
  ||videoads.theonion.com^
```
ist 
`  ||theonion.com^`
überflüssig und andersrum.
Ist es wirklich beabsichtigt alle Subdomains dieser Seite zu blockieren?

**Comment by yoshimo** [comment]
Ich hätte eine Seite wie TheOnion jetzt nicht zum vergiften genutzt aber müsst ihr wissen. Ich werde sie whitelisten.

**Comment by RPiList** [comment]
> Ich hätte eine Seite wie TheOnion jetzt nicht zum vergiften genutzt aber müsst ihr wissen. Ich werde sie whitelisten.

Die Quellen zur Verunreinigung waren damals die Phishing und Malware-Liste. Weil wir da sicher waren, dass Kinder darauf auch nicht zugreifen wollen.

Heute würden wir  das anders regeln, z.B. die Liste für DomainSquatting nehmen. Da können wir uns sicher sein, dass da keine "False Positives" dabei sind. Aber die Liste war seinerzeit noch gar nicht vorhanden, insoweit konnten und haben wir sie nicht genutzt.

Das kommt bei unserer gewählten Vorgehensweise aber leider vor. Deswegen gilt dann die Frage, ob es wichtig, dass die "Zielgruppe", die 10 bis 14-jährigen auf diese Seite zugreifen kann? Wenn ja, dann würde die Seite von der Liste entfernt werden. Aber  diese Wichtigkeit sehe ich hier nicht.

Daher ja die Einstufung, dass ein Eintrag in der CP-Liste keine Herabstufung oder Abwertung ist. Es ist nur keine Seite für Kids.

Für Kinder ab einem bestimmten Alter (das Alter bestimmen die Eltern) und Eltern sollten die Liste sowieso nicht einbinden. Daher ist dann das Whitelisting nicht notwendig.

**Comment by RPiList** [comment]
Text wurde zu früh gespeichert... deswegen geht es hier weiter:

In Ihrem Fall würde ich schätzen, dass Sie entweder zu alt für die Liste sind oder ein Elternteil, dass die Liste so eingerichtet hat, dass sie für alle Teilnehmer im LAN gilt. Sie sollte aber so eingerichtet werden, dass Sie nur für die Minderjährigen wirksam ist. 

Viele Grüße
