### ISSUE TITLE
www.googleadservices.com

### ISSUE THREAD

**Issue by frostieDE** [RPiList/specials#1842]
Hallo zusammen,

ist es gewollt, dass die URL `www.googleadservices.com` in der Liste `crypto` enthalten ist? 

Meine (naive) Annahme ist, dass diese Domain für Werbung auf Google genutzt wird (also die ganzen "Gesponsert"-Links) und nicht für Cryptokrams.

Sorgt dafür, dass wir keine "Gesponsert"-Links anklicken können. Als Workaround habe ich die Domain auf die Allowlist gesetzt :-)

Gruß

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
