### ISSUE TITLE
Wie bekomme ich meine Domians?

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1844]
Lieber Sprecher,

mir wurde zugetragen, dass du dich fragst, wie ich an meine Domains gelange.

Ich betreibe einen eigenen E-Mail-Server, der alle eingehenden Nachrichten annimmt. Diese Mails lasse ich mir im HTML-Code anzeigen, um von Hand alle Links zu analysieren.

Dabei kann es gelegentlich passieren, dass ich versehentlich eine falsche Domain herausfiltere. Angesichts der Vielzahl von E-Mails, die täglich bei mir eingehen, ist das bei Hunderten von Domains leider nicht ganz auszuschließen. Ich bitte um Verständis das es da zu Fehlern kommen kann.

Vielen Dank für dein Verständnis!

Mit freundlichen Grüßen
Michelle

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Rückmeldung.

Ja, evtl. hattest Du einen Domain gefangen, die als Absender in den Spam-Mails war. Da Absender aber sehr leicht zu fälschen sind (wenn der Empfänger nicht auf DKIM, SPF und Co. testet), ist dies keine verlässliche Spamerkennung.

Also da einfach drauf achten, künftig nicht mehr den Absender einer Mail mit aufzunehmen.

Vielen Dank für die Unterstützung.

Viele Grüße
