### ISSUE TITLE
hardreset.info

### ISSUE THREAD

**Issue by Akamaru** [RPiList/specials#185]
In der easylist befindet sich hardreset.info und www.hardreset.info.
Das ist meines Wissens nach eine legitime Seite.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für Ihre Information. Die Domain wurde entfernt. Viele Grüße.

Am Mi., 1. Apr. 2020 um 13:51 Uhr schrieb Akamaru <notifications@github.com
