### ISSUE TITLE
Fehler in spam.mails liste

### ISSUE THREAD

**Issue by Timon0586** [RPiList/specials#1855]
||fontawesome.com^

Der Eintrag sollte da nicht sein, es gibt immer noch Projekte / Websiten und anders geartete dinge welche fontawesome nicht  auf ihrem eigenen Server, sondern von der Website z.B. use.fontawesome.com einbinden. Diese Icons fehlen dann plötzlich auf der Website / in dem Projekt und man fängt an zu suchen. 

Zumal es mir neu ist dass fontawesome.com Spammails versendet.

Diesen Eintrag ggf. wieder entfernen

Aus der Pi.Hole suche:

`Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails:
  ||fontawesome.com^`

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
