### ISSUE TITLE
hosts-file.net

### ISSUE THREAD

**Issue by IgneaX** [RPiList/specials#186]
Es hat den Anschein als ob hosts-file.net down ist. Ist die Liste https://hosts-file.net/ad_servers.txt gut gepflegt worden? Gibt es einen guten Ersatz auf den man ausweichen kann?

**Comment by RPiList** [comment]
Hallo,

das ist schon öfters passiert, davon sollten Sie sich nicht irritieren lassen. Diese Liste basiert genau wie unsere "malware" Liste auf den Listen von Malware-Domains.com.

Wenn Ihr Pi-hole keine neue Liste ziehen kann, behält es einfach die alte Liste bei. Ob eine Liste also nicht mehr da ist oder nur nicht mehr gepflegt ist, ist für das Pi-hole das Gleiche. Ob die Liste noch gepflegt wird, kann ich nicht sagen. Ich weiß nur, dass sie schon öfters mal "offline" war.

Deswegen haben wir unsere eigene "malware"-Liste erstellt. Einfach beide nutzen und schon kann nichts mehr passieren.

Viele Grüße
