### ISSUE TITLE
Spam Domians die X

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1863]
brick-zero.info
autoki24handel.com
ubaresodina.com
uunjustlyu.monster
reef-visionary.info
germanfernseher.shop

**Comment by RichardBeisser** [comment]
auch von mir wieder welche:

blueforgehub.com
vicional.com
mapenlce.com
kiddosshop.shop
nonhodgkinsettlement.com

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden hinzugefügt. Viele Grüße
