### ISSUE TITLE
False positive: payment.tle.de

### ISSUE THREAD

**Issue by vonnull** [RPiList/specials#1868]
Hallo,

ich hab gerade was bei Alternate mit Paypal gezahlt und bin an payment.tle.de hängengeblieben. Die Hauptdomain scheint Müll zu sein. An diese Subdomain muss ja irgendwie valid sein, wenn Alternate die benutzt.

Gruß

**Comment by RPiList** [comment]
Hi,
die Domain ist nicht in unseren Listen vertreten. Wenn das bei Ihnen gesichert ist, dass es in unserer Liste war, dann müsste das die Malware-Liste sein. Dort werden Einträge automatisch gelöscht, wenn sich das Problem erledigt hat. In dem Fall bitte die eigenen Listen updaten.

Viele Grüße
