### ISSUE TITLE
libero.it

### ISSUE THREAD

**Issue by WaLLy3K** [RPiList/specials#1870]
Hi team,

I've been DM'ed that https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe contains the false positive libero.it which is apparently a mail hosting provider in Italy.

It'd be great if this could be looked into and potentially removed. Thanks! 🙂

**Comment by RPiList** [comment]
Hi, 

thx for supporting our project. Domain has been removed. Greetings.
