### ISSUE TITLE
Fake Shop Liste

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1871]
Grüße dich, 
watchlist-internet.at beitet mehrer Liste an mit Fake Shops URLs, könnte man ja in die Rpilisten einbauen

https://www.watchlist-internet.at/liste-betruegerischer-shops/
https://www.watchlist-internet.at/liste-problematischer-shops/
https://www.watchlist-internet.at/liste-abo-fallen/
https://www.watchlist-internet.at/liste-jobangebote/

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Listen werden bereits bei uns berücksichtigt. Viele Grüße
