### ISSUE TITLE
ajax.googleapis.com

### ISSUE THREAD

**Issue by beerisgood** [RPiList/specials#188]
Auch eure https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto hat zu schwerwiegende Fehler!:

ajax.googleapis.com

Wer solche Domains blockt, sollte eine Blocklist lieber sein lassen.

**Comment by RPiList** [comment]
Hallo,
vielen Dank für die Info. Domain wurde entfernt. Viele Grüße.
