### ISSUE TITLE
aka.ms

### ISSUE THREAD

**Issue by beerisgood** [RPiList/specials#189]
Eure https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware blockt
aka.ms

Das ist ein Weiterleitungs-Service von Microsoft (daher .ms)
Leider auch ein herber Fehlalarm.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die drei Mails, alle Domains werden auf unsere Whitelist
gesetzt und landen kann künftig nicht mehr auf den Blocklists.

Ihre Annahme, das hier ein "herber Fehlalarm" vorliegt ist aber falsch, es
ist kein Fehlalarm. Genauso verhält es sich bei den anderen beiden von
Ihnen genannten URLs.

Webseiten bieten Schadware an und nutzen einfach den Weiterleitungsservice
von MS um die Schadware zu verschleiern. So landete die Domain dann auch in
diversen Blocklisten. Die Malware-Blocklist, Crypto-Blocklist und auch die
Phishing-Listen basieren auf Einträgen von Dritten. Der Phishing-Angriff
über report-uri.com läuft derzeit immer noch.

Insoweit ist es korrekt, dass die Domains auch in den Filtern landen. Wenn
sich dann Nutzer melden, die die Domains brauchen, werden sie entfernt.
Sollte kein Nutzer die Domain brauchen, bleibt sie drin und schützt die
Nutzer.

Natürlich kann man diskutieren, ob man z.B. einen Weiterleitungs-Dienst
blockiert, weil eine Verlinkung auf eine Schadwareseite dabei war. Quasi
Sippenhaftung für die ganze Domain. Aber man könnte auch diskutieren, warum
MS die verlinkten Seiten nicht prüft sondern einfach auf Schadware verlinkt.

Dass dies Ihnen als Nutzer herzlich egal sein kann, ist dabei
nachvollziehbar. Wenn Sie also mit unseren Listen unzufrieden sind, weil
diese derzeit noch zu "unrein" sind, dann ist die einfache Lösung die
Listen nicht mehr zu benutzten. Einfach in ein oder 2 Jahren noch mal
vorbei schauen. Dann sind die meisten Kinderkrankheiten vielleicht erledigt.

Die Summe der Domains aller Blocklists beläuft sich bei uns auf 4 Millionen
Domains. Die sind nicht alle von Hand geprüft. Es würde auch nichts
bringen, da die Phishing und Malware-Listen sich quasi wöchentlich
aktualisieren. Solange die Dienste nicht aufpassen und es bei Ihnen
Phishing gibt, so lange landen sie bei uns in den Listen.

Trotzdem vielen Dank für die Info. Auch wenn Sie die Listen künftig nicht
nutzen, haben Sie den anderen Nutzern sehr geholfen.

Viele Grüße.


Am Do., 2. Apr. 2020 um 22:08 Uhr schrieb beerisgood <
notifications@github.com>:
