### ISSUE TITLE
report-uri.com

### ISSUE THREAD

**Issue by beerisgood** [RPiList/specials#190]
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe blockt
report-uri.com

Eine legitime Seite die zB vom GrapheneOS Project als auch von zB https://securityheaders.com benutzt wird.

Klingt jetzt hard, aber eure Listen haben in über 1 Jahr bei mir bis jetzt die meisten False Positives gehabt und somit die meisten Probleme bereitet.
Und das obwohl ich fast 80 Listen eingetragen habe.

Ich mag euer Projekt aber die vielen Issues zeigen auch wie sehr ihr an eurer Qualität arbeiten müsst!

**Comment by RPiList** [comment]
Hallo,
vielen Dank für die Info. Domain wurde entfernt. Viele Grüße.
