### ISSUE TITLE
Image zippen?

### ISSUE THREAD

**Issue by ipse-diabolus** [RPiList/specials#20]
Das zippen der Imagedatei kostet zwar fast eine Stunde, bringt aber eine Datei von 3,3 GB hervor.

**Comment by Tyberhertz** [comment]
da muss ich ipse-diabolus zustimmen, auch bei mir (Arch Linux) ist das Images ca. 3,3 GB groß, wenn man es mit .tar.xz komprimiert, dann sind es nur noch 2,7 GB.

**Comment by ipse-diabolus** [comment]
Naja, Zeit ist ja relativ, wenn "in diesem Saftladen offenbar Keiner arbeitet" [(Sprecher in "Geschwätzige IoT-Hardware finden")](https://youtu.be/8ghZhEiFTeI?t=150), zumindest zwischen 8 Uhr und 13 Uhr. Da kann man ja so ein Packen mal anstoßen. 

Die Einstiegshürde ist mit .zip kleiner als mit .tar.xz, vor allem für die Windows-Fraktion oder irre ich?

**Comment by flintstone1409** [comment]
> Die Einstiegshürde ist mit .zip kleiner als mit .tar.xz, vor allem für die Windows-Fraktion oder irre ich?

Der Explorer kann .zip mittlerweile alleine entpacken, .tar.xz setzt wiederum zusätzliche Software voraus.

**Comment by RPiList** [comment]
Derzeit befindet sich das ganze Projekt ja noch im Alpha Stadium. Daher wurde das Image auch unkomprimiert zum Download angeboten. Imho ist es den derzeitigen Nutzern/Testern völlig egal wie groß die Datei ist.

Spätere Versionen werden dann auch komprimiert angeboten. Das sollte kein Problem darstellen. Viele Grüße.
