### ISSUE TITLE
Please whitelist coronavirusdatamap.com and californiacoronavirus.org!

### ISSUE THREAD

**Issue by nchilada** [RPiList/specials#200]
Hi there, coronavirusdatamap.com and californiacoronavirus.org appear to be trustworthy websites owned by @embreinhardt, but they're currently blacklisted. Could you please find a way to whitelist them? Let me know if I can help with that!

**Comment by embreinhardt** [comment]
I'm the developer behind these sites, please let me know if you have any questions about them in order to get them whitelisted! Both are entirely based on vetted historical data from the New York Times, and San Francisco Chronicle

**Comment by joestr** [comment]
Looks trustworthy to me.

**Comment by nchilada** [comment]
@joestr thank you very much!
