### ISSUE TITLE
PI hole via wifi

### ISSUE THREAD

**Issue by Yocker95k** [RPiList/specials#203]
Ich nutze  (will) einen _Raspberry Pi zero w_ als Pi-hole. Muss es also per Wifi betreiben, da der Pi keinen Ethernet Anschluss hat.  Mit einer `wpa_supplicant.conf` gebe ich dem Pi die Wifi-credentials mit und er verbindet sich auch erfolgreich.
Auf der Settings Seite des Pi-holes steht aber trotzdem dass der adapter `eth0 `genutzt wird. Listen updaten etc funktioniert nicht und ich bekomme eine Meldung "keine ip" + ich soll doch mal pihole -r ausführen. Das hat aber auch nichts geändert. 
Der Pi hat eine statische IP-Adresse, aber eben für `wlan0 `und nicht `eth0`. Irgendwie bekomme ich das nicht im Pi-hole umgestellt. Vllt kann mir hier jemand weiter helfen.

**Comment by ich423** [comment]
Warum nutzt du keinen USB-zu-Ethernetadapter? Ethernet ist viel zuverlässiger als Wlan.

**Comment by RPiList** [comment]
Unser Pi-hole Image kann nicht ohne große Umbauten auf einem Pi-zero genutzt werden.

Da ich aus Ihrem Post entnehme, dass Sie keine Probleme mit dem Zugriff über Terminal haben, empfehle ich ein einfaches Raspi-Image zu nehmen und die eine Code-Zeile zur Installation des Pi-hole selbst auszuführen.

Danach funktioniert Pi-hole auf jeden Fall. Sogar über WLAN.

Aber wie @ich423 schon anmerkte, DNS-Resolver (Pi-hole) über WLAN sind absolut nicht zu empfehlen. Daher für 1,50 einen Adapter von Micro-USB auf normales USB anstecken und dann einen USB-to-ETH Netzwerkstecker dran.

**Comment by H4ckZ** [comment]
@Yocker95k Falls es für dich noch von Interesse ist..
Ich stimme zwar den Kommentaren darüber zu, dass Kabel einfach Kabel ist, aber hier hats wohl jemand getestet: https://www.reddit.com/r/pihole/comments/fyyi9t/best_practice_one_or_two_piholes/fn2ppx7?utm_source=share&utm_medium=web2x

> Pps. I’ve measured the latency differences between wired (2b)and wireless (ZW) and it’s about 2-4ms which is not noticeable.

>

**Comment by Yocker95k** [comment]
OK vielen Dank für die Antworten. Werde mich die Tage mal daran setzen 👍
