### ISSUE TITLE
Linkverkürzer

### ISSUE THREAD

**Issue by RPiList** [RPiList/specials#204]
Hi,

das Linkverkürzer (URL-Shortener) ein Problem für die Sicherheit darstellen können, ist allgemein bekannt. Daher kann es sinnvoll sein, den Nutzern die Möglichkeit anzubieten, diese über das Pi-hole im eigenen LAN zu sperren.

Auf der anderen Seite kann man nicht alle Linkverkürzer über einen Kamm scheren. So führt z.B. t1p.de entsprechende Sicherheitsmaßnahmen durch. Damit soll verhindert werden, dass der Link auf Schwadware/Phishing Seiten leitet. Ferner ist t1p.de, laut eigener Aussage, DSVGO-konform, in dem man keiner Speicherung durchführt. Es wird nicht gespeichert wer auf einen Link zugreift. Es wird auch nicht gezählt wie oft ein Link aufgerufen wird.

Ferner gibt es Linkverkürzer die immer nur auf die eigene Domain verweisen. Der Linkverkürzer von Amazon verkürzt nur Links, die auf Amazon verweisen. Da ist der Nutzer ebenfalls sicher.

Zu guter Letzt: Linkverkürzer die einem Internet Dienst zugeordnet werden und welcher ohne den Linkverkürzer kaum benutzbar sind. So z.B. der Twitter-eigene Linkverkürzer. 

Solche Linkverkürzer sollen natürlich nicht gesperrt werden.

Es gibt Linkverkürzer, die den Nutzer nur auf eine eigene Landingpage leiten, wo dem Nutzer dann noch extra Werbung untergeschoben wird, bzw. so viele falsche Download-Buttons angeboten werden, damit der Nutzer auf den falschen DL-Link klickt. Oftmals gibt es unter den falschen DL-Links Abzockerwebseiten oder Schadware.

Solche Linkverkürzer sollen natürlich gesperrt werden.

Eine Liste vieler Linkverkürzer habe ich unter [dev/URL-Shortener](https://github.com/RPiList/specials/blob/master/dev/URL-Shortener) angelegt. Für den Fall das Sie Linkverkürzer kennen, die nicht geblockt werden sollten, bitte entsprechende Pull-Request erstellen oder eine eMail schicken. Gleiches gilt natürlich für Linkverkürzer, die derzeit noch fehlen.

Vielen Dank für die Mühen, viele Grüße

**Comment by beerisgood** [comment]
Meiner Meinung nach macht sowas mehr Probleme als es löst, da man die gesamte Domain DNS seitig blockt.

Da diese Linkkürzer auch nur auf andere Domains verlinken, reicht es doch wenn man diese dann blockt. Dann endet die Weiterleitung nämlich in einem Fehler und Ende, wohingegen legitime Weiterleitungen noch funktionieren

**Comment by joestr** [comment]
Ja, das Problem ist nicht Linkverkürzer sondern die Domain danach. Wenn wir effektiv die Domains blocken ist der Linkverkürzer kein Problem.

**Comment by H4ckZ** [comment]
> 
> 
> Ja, das Problem ist nicht der Linkverkürzer, sondern die Domain danach. Wenn wir effektiv die Domains blocken ist der Linkverkürzer kein Problem.

Da geb ich euch grundsätzlich Recht.
Ich denke aber, dass der Gedanke hinter der Idee mit den Linkverkürzern der ist, dass man auch die "One-Time-Burner" erwischt, die heute auftauchen und morgen verschwinden.. ?
