### ISSUE TITLE
CoinBlockerLists Bitte autoren der Listen bennen/möglichst auf original downloads verweisen....

### ISSUE THREAD

**Issue by ZeroDot1** [RPiList/specials#205]
Die Liste: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto habt ihr ganz sicher nicht erstellt, bitte lest euch mal die Lizenz https://gitlab.com/ZeroDot1/CoinBlockerLists/-/blob/master/LICENSE durch, das ist so nicht okay was ihr da veranstaltet.
Originale Downloads der Listen findet ihr über folgenden Link: https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html
Listen die nicht regelmäßig gepflegt werden sind ein sehr hohes Sicherheitsrisiko.
Ich empfehle daher bitte auf die original Quellen zu verweisen, und möglichst keine Kopien zu machen, die dann nicht mehr aktualisiert werden.
Weiterhin ist der Name "crypto" nicht aussagekräftig und spiegelt nicht das wider, wofür die Liste gedacht ist.
Denn den Ärger hat am Ende immer der Entwickler, bitte berücksichtigt dieses, vielen Dank.

Für Supportanfragen senden Sie bitte eine Mail an: zerodot1@bk.ru

**Comment by joestr** [comment]
Die ursprüngliche Liste wird entfernt und auf Verweis auf das Original wird gesetzt.

**Comment by joestr** [comment]
Jetzt ist die richtige Liste drin.

**Comment by RPiList** [comment]
Hi,

> Die Liste: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto habt ihr ganz sicher nicht erstellt, bitte lest euch mal die Lizenz https://gitlab.com/ZeroDot1/CoinBlockerLists/-/blob/master/LICENSE durch, das ist so nicht okay was ihr da veranstaltet.

ich habe die Lizenz zwar noch nicht gelesen, aber unsere Liste basiert nicht auf der ZeroDot1 Liste. Unsere Liste basiert im wesentlichen auf den Listen der Universität Toulouse 1 Capitole. Auch Malwaredomains hat Listen, die sich mit dem Thema beschäftigen. Diese haben wir in Teilen ebenfalls übernommen.

> Originale Downloads der Listen findet ihr über folgenden Link: https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html

Also hat die Uni Toulouse von Ihnen abgeschrieben?

> Listen die nicht regelmäßig gepflegt werden sind ein sehr hohes Sicherheitsrisiko.
> Ich empfehle daher bitte auf die original Quellen zu verweisen, und möglichst keine Kopien zu machen, die dann nicht mehr aktualisiert werden.
> Weiterhin ist der Name "crypto" nicht aussagekräftig und spiegelt nicht das wider, wofür die Liste gedacht ist.

Der Name der originalen Liste (der Uni Toulouse) ist "cryptojacking", weswegen wir den Namen von dort auch übernommen haben.

Ich schau mir auf jeden Fall die Zerodot1 Liste an.

Viele Grüße.

**Comment by RPiList** [comment]
Hi,

habe mir jetzt die Zerodot1 Listen angeschaut. Habe die Listen "list_optional", "list_browser" und "list" runtergeladen. Meiner Kurzanalyse zufolge sind dort 56.404 unterschiedliche Domains drin. 

Unsere "crypto" Liste hat nur 33.839 unterschiedliche Domains drin. Von diesen 33.839 Domains sind 13.572 Domains NICHT in Ihrer Liste enthalten. Im Umkehrschluss haben wir also 20267 Domains, welche in "Ihrer" und in "unserer" Liste vorhanden sind.

Wie kommen Sie darauf, dass "Ihre" Liste in unserer Liste enthalten sei?  Hätten wir Ihre Liste übernommen, hätten wir alle 56.404 Domains in unserer Liste drin und nicht nur ein Drittel. 

Wenn ich Sie richtig verstanden habe, möchten Sie auch künftig nicht, dass wir Ihre Liste "übernehmen". Das werden wir dann selbstverständlich auch nicht machen.

Wir haben im Umkehrschluss überhaupt kein Problem damit, wenn Sie unsere ca. 13.000 Domains übernehmen, die in Ihrer Liste noch fehlen. Die Domains wurden uns zur Verfügung gestellt, damit Nutzer geschützt werden. Daher haben wir auch kein Problem damit, wenn andere unsere Listen übernehmen und ihre Nutzer damit schützen. Wir machen das nicht aus Fame.

Nicht gepflegte Listen sind für alle ein Problem. Wir haben hunderte Listen gefunden, die alle nicht mehr gepflegt werden. Jeder macht das ohne Bezahlung und irgendwann endet nun mal das Interesse daran. Das wird sicher auch irgendwann bei uns passieren. So wie wir die verwaisten Listen anderer Maintainer weiterführen hoffen wir, dass dann irgendwann jemand unsere Listen aufgreift und dort weiter macht.

Für Fragen stehe ich gerne zur Verfügung. Viele Grüße und viel Erfolg.

**Comment by ZeroDot1** [comment]
Sie können die CoinBlockerLists gerne verwenden. Allerdings sollten sie die Quelle erwähnen, und wenn möglich eine automatische Updateprüfung einrichten (tägliche Prüfung).

Bei der Liste, die ihr verwendet, handelt es sich um eine sehr alte Version der CoinBlockerLists die einfach mit IOCs von neuerern Versionen der CoinBlockerLists vermischt wurde in der sehr viele falsche positive enthalten sind. 
Hier der Nachweis: https://gitlab.com/ZeroDot1/CoinBlockerLists/-/commit/0c4c652f7f0740af3e862a8124eacd8fd8bdad48 
Bei mir haben sich schon über 50 Leute alleine nur wegen diese "crypto" liste von euch beschwert.
Ich empfehle dringend die "crypto" Liste einmal komplett zu prüfen und alle falschen positiven zu entfernen.

Wenn, eine Prüfung zu aufwendig ist verwenden sie die CoinBlockerListen und der Drops ist gelutscht.

Falls möglich nennt mir die Quelle eurer Liste...

Vielen Dank.

**Comment by RPiList** [comment]
> Bei mir haben sich schon über 50 Leute alleine nur wegen diese "crypto" liste von euch beschwert.

Sorry, dass es so dämliche Nutzer gibt, die unsere Liste benutzen, sich aber bei Ihnen beschweren. Ich beschwere mich jetzt auch immer bei Microsoft Word, wenn ich mit LibreOffice ein Problem habe. :-)

Ob unsere Grundlage veraltet ist, kann ich nicht nachprüfen. Aber die Liste wird alle paar Tage aktualisiert. Insoweit gehe ich davon aus, dass sie up-to-date ist.

Wir arbeiten an einer Möglichkeit die Domains auf grds. Gültigkeit zu prüfen. Bis dahin und darüber hinaus, müssen wir uns aber auch darauf verlassen, dass Nutzer "False Positives" melden. Das funktioniert bei den anderen Listen, eigentlich auch ganz hervorragend. 

Viele Grüße.

**Comment by ZeroDot1** [comment]
> Ob unsere Grundlage veraltet ist, kann ich nicht nachprüfen.

Ganz klar, dann könnt ihr auch so ein Projekt nicht führen.
Wenn, man ein Projekt mit Blocklisten betreibt, hat man eine sehr große Verantwortung.
Eine falsche Blockierung kann schon zu finanziellen Schäden für Seitenbetreiber führen, das gilt es unbedingt zu verhindern/vermeiden.
Ich prüfe alle Listen mindestens täglich auf false positives. 

> darauf verlassen, dass Nutzer "False Positives" melden.

Darauf sollte man sich als Blacklist-Betreiber niemals verlassen.

Und noch ein Punkt:
Ihr müsst, wenn ihr fremde Listen verwendet immer den Uhrsprung angeben, sonnst, ist das sehr unseriös.

**Comment by RPiList** [comment]
> > Ob unsere Grundlage veraltet ist, kann ich nicht nachprüfen.
> 
> Ganz klar, dann könnt ihr auch so ein Projekt nicht führen.

Das ich die Grundlage nicht darauf prüfen kann, war eine freundliche Formulierung dafür, dass Ihre Behauptung, dass wir eine veraltete Liste von Ihnen genommen haben, nicht bestätigen kann. 

> Wenn, man ein Projekt mit Blocklisten betreibt, hat man eine sehr große Verantwortung.
> Eine falsche Blockierung kann schon zu finanziellen Schäden für Seitenbetreiber führen, das gilt es unbedingt zu verhindern/vermeiden.

Ja, da haben wir unterschiedliche Auffassungen. Mir geht es nicht um die Nutzer deren Webseiten wir blocken, mir geht es um die Nutzer, die diese Websites evtl. aufrufen. Das ist die Zielgruppe, für die das Projekt gestartet wurde.

> Und noch ein Punkt:
> Ihr müsst, wenn ihr fremde Listen verwendet immer den Uhrsprung angeben, sonnst, ist das sehr unseriös.

Wir benutzen keinen fremden Listen. Würden wir das machen, würden wir die erst gar nicht hosten, dann würden wir auf die jeweilige Liste verlinken. Also wir würden niemals Ihre Liste übernehmen. Es gibt überhaupt keinen Sinn sowas zu tun.

Aber wir haben Listen im Internet als Grundlage herangezogen, weil diese selbst völlig unvollständig und damit untauglich waren. Es wäre viel einfacher für uns nur auf dritte Listen zu verlinken, anstatt sich die Mühe zu machen, die Listen fortzuschreiben. Aber wenn die Grundlagen nun mal Pi-hole untauglich sind, muss man sie entsprechend verändern/fortschreiben.

Mal ein Beispiel:

In einer Liste auf zonefiles.io findet man u.a. "pornhub.com" und "xvideos.com"

Diese zwei Domains wurden von uns als **Grundlage** für unsere Einträge gewählt. In unserer entsprechenden Liste steht dann im Ergebnis:

> `ac.pornhub.com
ad.pornhub.com
ae.pornhub.com
af.pornhub.com
ag.pornhub.com
ai.pornhub.com
al.pornhub.com
am.pornhub.com
an.pornhub.com
ao.pornhub.com
aq.pornhub.com
ar.pornhub.com
as.pornhub.com
at.pornhub.com
au.pornhub.com
aw.pornhub.com
ax.pornhub.com
az.pornhub.com
ba.pornhub.com
bb.pornhub.com
bd.pornhub.com
be.pornhub.com
bf.pornhub.com
bg.pornhub.com
bh.pornhub.com
bi.pornhub.com
bj.pornhub.com
bl.pornhub.com
bm.pornhub.com
bn.pornhub.com
bo.pornhub.com
br.pornhub.com
bq.pornhub.com
bs.pornhub.com
bt.pornhub.com
bv.pornhub.com
bw.pornhub.com
by.pornhub.com
bz.pornhub.com
ca.pornhub.com
cc.pornhub.com
cd.pornhub.com
cf.pornhub.com
cg.pornhub.com
ch.pornhub.com
ci.pornhub.com
ck.pornhub.com
cl.pornhub.com
cm.pornhub.com
cn.pornhub.com
co.pornhub.com
cr.pornhub.com
cs.pornhub.com
cu.pornhub.com
cv.pornhub.com
cw.pornhub.com
cx.pornhub.com
cy.pornhub.com
cz.pornhub.com
dd.pornhub.com
de.pornhub.com
dj.pornhub.com
dk.pornhub.com
dm.pornhub.com
do.pornhub.com
dz.pornhub.com
ec.pornhub.com
ee.pornhub.com
eg.pornhub.com
eh.pornhub.com
er.pornhub.com
es.pornhub.com
et.pornhub.com
eu.pornhub.com
fi.pornhub.com
fj.pornhub.com
fk.pornhub.com
fm.pornhub.com
fo.pornhub.com
fr.pornhub.com
ga.pornhub.com
gb.pornhub.com
gd.pornhub.com
ge.pornhub.com
gf.pornhub.com
gg.pornhub.com
gh.pornhub.com
gi.pornhub.com
gl.pornhub.com
gm.pornhub.com
gn.pornhub.com
gp.pornhub.com
gq.pornhub.com
gr.pornhub.com
gs.pornhub.com
gt.pornhub.com
gu.pornhub.com
gw.pornhub.com
gy.pornhub.com
hk.pornhub.com
hm.pornhub.com
hn.pornhub.com
hr.pornhub.com
ht.pornhub.com
hu.pornhub.com
id.pornhub.com
ie.pornhub.com
il.pornhub.com
im.pornhub.com
in.pornhub.com
io.pornhub.com
iq.pornhub.com
ir.pornhub.com
is.pornhub.com
it.pornhub.com
je.pornhub.com
jm.pornhub.com
jo.pornhub.com
jp.pornhub.com
ke.pornhub.com
kg.pornhub.com
kh.pornhub.com
ki.pornhub.com
km.pornhub.com
kn.pornhub.com
kp.pornhub.com
kr.pornhub.com
kw.pornhub.com
ky.pornhub.com
kz.pornhub.com
la.pornhub.com
lb.pornhub.com
lc.pornhub.com
li.pornhub.com
lk.pornhub.com
lr.pornhub.com
ls.pornhub.com
lt.pornhub.com
lu.pornhub.com
lv.pornhub.com
ly.pornhub.com
ma.pornhub.com
mc.pornhub.com
md.pornhub.com
me.pornhub.com
mf.pornhub.com
mg.pornhub.com
mh.pornhub.com
mk.pornhub.com
ml.pornhub.com
mm.pornhub.com
mn.pornhub.com
mo.pornhub.com
mp.pornhub.com
mq.pornhub.com
mr.pornhub.com
ms.pornhub.com
mt.pornhub.com
mu.pornhub.com
mv.pornhub.com
mw.pornhub.com
mx.pornhub.com
my.pornhub.com
mz.pornhub.com
na.pornhub.com
nc.pornhub.com
ne.pornhub.com
nf.pornhub.com
ng.pornhub.com
ni.pornhub.com
nl.pornhub.com
no.pornhub.com
np.pornhub.com
nr.pornhub.com
nu.pornhub.com
nz.pornhub.com
om.pornhub.com
pa.pornhub.com
pe.pornhub.com
pf.pornhub.com
pg.pornhub.com
ph.pornhub.com
pk.pornhub.com
pl.pornhub.com
pm.pornhub.com
pn.pornhub.com
pr.pornhub.com
ps.pornhub.com
pt.pornhub.com
pw.pornhub.com
py.pornhub.com
qa.pornhub.com
re.pornhub.com
ro.pornhub.com
rs.pornhub.com
ru.pornhub.com
rw.pornhub.com
sa.pornhub.com
sb.pornhub.com
sc.pornhub.com
sd.pornhub.com
se.pornhub.com
sg.pornhub.com
sh.pornhub.com
si.pornhub.com
sj.pornhub.com
sk.pornhub.com
sl.pornhub.com
sm.pornhub.com
sn.pornhub.com
so.pornhub.com
sr.pornhub.com
ss.pornhub.com
st.pornhub.com
su.pornhub.com
sv.pornhub.com
sx.pornhub.com
sy.pornhub.com
sz.pornhub.com
tc.pornhub.com
td.pornhub.com
tf.pornhub.com
tg.pornhub.com
th.pornhub.com
tj.pornhub.com
tk.pornhub.com
tl.pornhub.com
tm.pornhub.com
tn.pornhub.com
to.pornhub.com
tp.pornhub.com
tr.pornhub.com
tt.pornhub.com
tv.pornhub.com
tw.pornhub.com
tz.pornhub.com
ua.pornhub.com
ug.pornhub.com
uk.pornhub.com
um.pornhub.com
us.pornhub.com
uy.pornhub.com
uz.pornhub.com
va.pornhub.com
vc.pornhub.com
ve.pornhub.com
vg.pornhub.com
vi.pornhub.com
vn.pornhub.com
vu.pornhub.com
wf.pornhub.com
ws.pornhub.com
ye.pornhub.com
yt.pornhub.com
yu.pornhub.com
za.pornhub.com
zm.pornhub.com
zr.pornhub.com
zw.pornhub.com
www.pornhub.com
ac.xvideos.com
ad.xvideos.com
ae.xvideos.com
af.xvideos.com
ag.xvideos.com
ai.xvideos.com
al.xvideos.com
am.xvideos.com
an.xvideos.com
ao.xvideos.com
aq.xvideos.com
ar.xvideos.com
as.xvideos.com
at.xvideos.com
au.xvideos.com
aw.xvideos.com
ax.xvideos.com
az.xvideos.com
ba.xvideos.com
bb.xvideos.com
bd.xvideos.com
be.xvideos.com
bf.xvideos.com
bg.xvideos.com
bh.xvideos.com
bi.xvideos.com
bj.xvideos.com
bl.xvideos.com
bm.xvideos.com
bn.xvideos.com
bo.xvideos.com
br.xvideos.com
bq.xvideos.com
bs.xvideos.com
bt.xvideos.com
bv.xvideos.com
bw.xvideos.com
by.xvideos.com
bz.xvideos.com
ca.xvideos.com
cc.xvideos.com
cd.xvideos.com
cf.xvideos.com
cg.xvideos.com
ch.xvideos.com
ci.xvideos.com
ck.xvideos.com
cl.xvideos.com
cm.xvideos.com
cn.xvideos.com
co.xvideos.com
cr.xvideos.com
cs.xvideos.com
cu.xvideos.com
cv.xvideos.com
cw.xvideos.com
cx.xvideos.com
cy.xvideos.com
cz.xvideos.com
dd.xvideos.com
de.xvideos.com
dj.xvideos.com
dk.xvideos.com
dm.xvideos.com
do.xvideos.com
dz.xvideos.com
ec.xvideos.com
ee.xvideos.com
eg.xvideos.com
eh.xvideos.com
er.xvideos.com
es.xvideos.com
et.xvideos.com
eu.xvideos.com
fi.xvideos.com
fj.xvideos.com
fk.xvideos.com
fm.xvideos.com
fo.xvideos.com
fr.xvideos.com
ga.xvideos.com
gb.xvideos.com
gd.xvideos.com
ge.xvideos.com
gf.xvideos.com
gg.xvideos.com
gh.xvideos.com
gi.xvideos.com
gl.xvideos.com
gm.xvideos.com
gn.xvideos.com
gp.xvideos.com
gq.xvideos.com
gr.xvideos.com
gs.xvideos.com
gt.xvideos.com
gu.xvideos.com
gw.xvideos.com
gy.xvideos.com
hk.xvideos.com
hm.xvideos.com
hn.xvideos.com
hr.xvideos.com
ht.xvideos.com
hu.xvideos.com
id.xvideos.com
ie.xvideos.com
il.xvideos.com
im.xvideos.com
in.xvideos.com
io.xvideos.com
iq.xvideos.com
ir.xvideos.com
is.xvideos.com
it.xvideos.com
je.xvideos.com
jm.xvideos.com
jo.xvideos.com
jp.xvideos.com
ke.xvideos.com
kg.xvideos.com
kh.xvideos.com
ki.xvideos.com
km.xvideos.com
kn.xvideos.com
kp.xvideos.com
kr.xvideos.com
kw.xvideos.com
ky.xvideos.com
kz.xvideos.com
la.xvideos.com
lb.xvideos.com
lc.xvideos.com
li.xvideos.com
lk.xvideos.com
lr.xvideos.com
ls.xvideos.com
lt.xvideos.com
lu.xvideos.com
lv.xvideos.com
ly.xvideos.com
ma.xvideos.com
mc.xvideos.com
md.xvideos.com
me.xvideos.com
mf.xvideos.com
mg.xvideos.com
mh.xvideos.com
mk.xvideos.com
ml.xvideos.com
mm.xvideos.com
mn.xvideos.com
mo.xvideos.com
mp.xvideos.com
mq.xvideos.com
mr.xvideos.com
ms.xvideos.com
mt.xvideos.com
mu.xvideos.com
mv.xvideos.com
mw.xvideos.com
mx.xvideos.com
my.xvideos.com
mz.xvideos.com
na.xvideos.com
nc.xvideos.com
ne.xvideos.com
nf.xvideos.com
ng.xvideos.com
ni.xvideos.com
nl.xvideos.com
no.xvideos.com
np.xvideos.com
nr.xvideos.com
nu.xvideos.com
nz.xvideos.com
om.xvideos.com
pa.xvideos.com
pe.xvideos.com
pf.xvideos.com
pg.xvideos.com
ph.xvideos.com
pk.xvideos.com
pl.xvideos.com
pm.xvideos.com
pn.xvideos.com
pr.xvideos.com
ps.xvideos.com
pt.xvideos.com
pw.xvideos.com
py.xvideos.com
qa.xvideos.com
re.xvideos.com
ro.xvideos.com
rs.xvideos.com
ru.xvideos.com
rw.xvideos.com
sa.xvideos.com
sb.xvideos.com
sc.xvideos.com
sd.xvideos.com
se.xvideos.com
sg.xvideos.com
sh.xvideos.com
si.xvideos.com
sj.xvideos.com
sk.xvideos.com
sl.xvideos.com
sm.xvideos.com
sn.xvideos.com
so.xvideos.com
sr.xvideos.com
ss.xvideos.com
st.xvideos.com
su.xvideos.com
sv.xvideos.com
sx.xvideos.com
sy.xvideos.com
sz.xvideos.com
tc.xvideos.com
td.xvideos.com
tf.xvideos.com
tg.xvideos.com
th.xvideos.com
tj.xvideos.com
tk.xvideos.com
tl.xvideos.com
tm.xvideos.com
tn.xvideos.com
to.xvideos.com
tp.xvideos.com
tr.xvideos.com
tt.xvideos.com
tv.xvideos.com
tw.xvideos.com
tz.xvideos.com
ua.xvideos.com
ug.xvideos.com
uk.xvideos.com
um.xvideos.com
us.xvideos.com
uy.xvideos.com
uz.xvideos.com
va.xvideos.com
vc.xvideos.com
ve.xvideos.com
vg.xvideos.com
vi.xvideos.com
vn.xvideos.com
vu.xvideos.com
wf.xvideos.com
ws.xvideos.com
ye.xvideos.com
yt.xvideos.com
yu.xvideos.com
za.xvideos.com
zm.xvideos.com
zr.xvideos.com
zw.xvideos.com
www.xvideos.com`

Insoweit bin ich nicht der Meinung dass wir eine andere Liste übernommen haben, auf die wir verlinken müssten. Bei diesem Verhältnis ist es unsere Liste geworden. Natürlich wird nicht jede Domain mit allen ccTLDs vervollständigt. Aber die Listen geben sich nicht mal die Mühe die www. Subdomain zu blockieren. Das ist in unseren Listen dann immer vervollständigt worden. Insoweit sehe ich da schon eine erhebliche Eigenleistung und nicht eine Übernahme einer dritten Liste.

Und ja... kann sein das es die va.pornhub.com (TLD des Vatikanstaats) gar nicht gibt. Da nehmen wir aber Overblocking billigend in Kauf. Für unsere Zielgruppe ist es wichtig, dass solche Inhalte geblockt werden.

Viele Grüße
