### ISSUE TITLE
Corona Blacklist erweitern

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#209]
Kann die Corona Blacklist um diese URLs ergänzt werden: https://github.com/COVID-19-CTI-LEAGUE/PUBLIC_RELEASE/blob/master/Cyber_threat_Coalition_domain_Blacklist.txt ?

**Comment by RPiList** [comment]
Ich glaube solch einen Vorschlag gab es schon. Jedenfalls haben wir die Domains schon drin.
