### ISSUE TITLE
Phishing-Angriffe - URL Posteo.de FALSCH

### ISSUE THREAD

**Issue by franzaut** [RPiList/specials#214]
Bitte fixen!
- posteo.de
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe

**Comment by H4ckZ** [comment]
Ich nehme mal an mit fixen meinst du von der Liste entfernen?

**Comment by BulldozerPete** [comment]
Vielleicht sollten wir eine neue Liste für E-Mail Betreiber anlegen, damit Oma Erna auch ihre Mails abrufen kann, wenn der SVPihole werkelt.

**Comment by beerisgood** [comment]
Also ich kann "posteo.de" nicht auf der Liste entdecken
@franzaut

**Comment by BulldozerPete** [comment]
Weil diese schon entfernt wurde.

**Comment by RPiList** [comment]
ist gefixt, hatte nur keine Zeit hier eine Rückmeldung zu geben (wg. eines anderen Problems in der Liste).
