### ISSUE TITLE
WER...

### ISSUE THREAD

**Issue by DE8MSH** [RPiList/specials#22]
...zum (/%/§/&%2656357324243wwewe2%%32 erstellt ein Image welches 8GB groß ist? Pi-Hole hat niemals 8GB!

**Comment by joestr** [comment]
Ist vermutlich ein Image von der SD-Karte welche halt 8GB groß war.

**Comment by DE8MSH** [comment]
Und das kann man nicht verkleinern?

**Comment by Tyberhertz** [comment]
Da das ganze noch in einem sehr frühen Stadium ist, denke ich, dass sich die größe des Images noch ändern wird.

**Comment by Tyberhertz** [comment]
Das ist die Ausgabe von "df -h"

Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.0G  4.8G  1.9G  72% /
devtmpfs        484M     0  484M   0% /dev
tmpfs           488M  1.6M  487M   1% /dev/shm
tmpfs           488M  6.8M  482M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           488M     0  488M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   52M  201M  21% /boot
tmpfs            98M     0   98M   0% /run/user/1000
tmpfs            98M     0   98M   0% /run/user/999

Wir sehen also, das Image kann nicht auf 4 GB verkleinert werden..

**Comment by DE8MSH** [comment]
Und weißt Du auch warum? Weil Du das komplette Full Image genommen hast. Wie wäre es mit Raspian Mini? Was soll ich mit Minecraft auf Pihole??? Soll ich während der Werbepausen Minecraft spielen? *lol*

**Comment by joestr** [comment]
> Und weißt Du auch warum? Weil Du das komplette Full Image genommen hast. Wie wäre es mit Raspian Mini? Was soll ich mit Minecraft auf Pihole??? Soll ich während der Werbepausen Minecraft spielen? lol

Warum fragst du das uns? @RPiList Kann dir da sicher mehr dazu sagen.

**Comment by RPiList** [comment]
Ja, das ist richtig, dass man das wohl auch kleiner hinkriegen könnte. Die Frage ist ob die Gründe dafür erheblich sind.

Der Download von 8GB ist natürlich negativ.
Die Möglichkeit dass sich die Nutzer später auch mal über RDP auf den Pi aufschalten (weil wir das dauernd in den Videos zeigen) wäre ein zusätzlicher Nutzen.
Der "Zwang" eine 16 GB Karte nehmen zu müssen, ist unerheblich, da 16 GB Karten inzw. das Gleiche Kosten wie eine 8 GB Karte.

Aber... man könnte natürlich beide Varianten anbieten. die Netto-Variante für Nutzer, die noch mit 14,4k-Modem unterwegs sind. :-)

Machen wir also in einer der späteren Fassung. 

Danke für die Hinweise. Viele Grüße.
