### ISSUE TITLE
Spiegel.de und Spiegel Mobile App / Bild.de

### ISSUE THREAD

**Issue by Zelo72** [RPiList/specials#223]
Hallo,

damit man Spiegel.de und die Spiegel Mobile App nutzen zu können, müssen folgende zwei Domains in die Whitelist:

sourcepoint.mgr.consensu.org
message331-fra.sp-prod.net

Damit Bild.de funktioniert - wer es unbedingt braucht :) -, müssen folgende Domains in die Whitelist:

www.asadcdn.com
code.bildstatic.de
de.ioam.de
json.bild.de
script.ioam.de
tags.tiqcdn.com

Gruß,
Gerd

**Comment by RPiList** [comment]
Ist es durch Drittquellen gesichert, dass die Domains notwendig sind?

Weil schon die erste Domain sieht "seltsam" aus.

![Unbenannt](https://user-images.githubusercontent.com/56664851/79136660-a6d6cd80-7db1-11ea-9461-0369a3ba89f1.PNG)

Sourcepoint.mgr.consensu.org ist "lebenswichtig" für Spiegel.de und trotzdem wird sie auf GoDaddy.com geparkt, so dass sie sich jeder schnappen kann?

**Comment by BulldozerPete** [comment]
Ich kann die URLs gegen andere Listen prüfen.
Wenn diese dort auftauchen, ist die Wahrscheinlichkeit eines false positives gering.

**Comment by RPiList** [comment]
@BulldozerPete 

Vielen Dank für die Mühe. Für die Spiegel App ist das sinnvoll. Aber nicht für einzelne Websites. Wobei man argumentieren kann, dass es sich auch von der Bild eine App gibt.

**Comment by BulldozerPete** [comment]
Die Spiegel iOS App funktioniert hier out-of-the Box mit allen RPi Blocklisten.

**Comment by Zelo72** [comment]
> 
> 
> Die Spiegel iOS App funktioniert hier out-of-the Box mit allen RPi Blocklisten.

Die Spiegel App funktioniert nur wenn man sie vor der Umstellung bei Spiegel.de schon auf dem Gerät hatte. Deinstalliere sie mal und installiere sie neu, dann kommst du über das "AdBlock-Fenster" nicht hinaus. Whitelisten der o.g. URLs hilft, danach kann man sie wieder entfernen und die App funktioniert wie gewünscht.

**Comment by Zelo72** [comment]
> Ich kann die URLs gegen andere Listen prüfen.
> Wenn diese dort auftauchen, ist die Wahrscheinlichkeit eines false positives gering.

sourcepoint.mgr.consensu.org ist bei mir in: 
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

message331-fra.sp-prod.net in: 
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by Zelo72** [comment]
Ich habe das noch mal getestet und geprüft, die Domains werden nur zur Ersteinrichtung der Spiegel App nach Installation benötigt. Danach werden sie laut PiHole Query Log nicht mehr aufgerufen.

**Comment by H4ckZ** [comment]
Ohne jetzt was gecheckt zu haben.. aber wenn man sich eure Beiträge hier so durchliest .. iwie dubios.. :D

**Comment by Zelo72** [comment]
Issue kann weg/zu ...
Wie gesagt, Domains werden nur zur Ersteinrichtung benötigt.
