### ISSUE TITLE
Überprüfung Domains

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#231]
Habe diese Blocklisten gefunden: https://raw.githubusercontent.com/maelcum/pihole_blocklist/master/pihole_blocklist

https://github.com/bloodhunterd/pi-hole-blocklists

https://github.com/Akamaru/Pi-Hole-Lists

Vielleicht können wir da einige sinnvolle URLs entnehmen.

**Comment by RPiList** [comment]
Vielen Dank für die Hinweise,

> Habe diese Blocklisten gefunden: https://raw.githubusercontent.com/maelcum/pihole_blocklist/master/pihole_blocklist

mit der Liste weiß ich noch nichts anzufangen. :-) Ziemliches durcheinander....
> 
> https://github.com/bloodhunterd/pi-hole-blocklists

Das sind fertige Blocklists, die werde ich in unsere Blocklisten.md übernehmen. Kann dann von den Nutzern nach Bedarf selbst "importiert" werden.

> 
> https://github.com/Akamaru/Pi-Hole-Lists
> 
Die Listen sind stark veraltet, insoweit stellt sich die Frage ob die noch übernommen werden sollten. Teilweise gibt es in den Listen IPs anstatt Domains... Der Autor wusste wohl nicht, dass IPs gar nicht erst ans Pihole geschickt werden. :-)

Das hat aber nichts damit zu tun, dass wir uns für die Einsendung bedanken. Schauen wir mal was wir damit machen. Grüße.
