### ISSUE TITLE
Falsche Domains

### ISSUE THREAD

**Issue by Rezoran** [RPiList/specials#232]
Hi,
folgende Domain ist keine Malware:
www.tropen-tango.de 
Es ist die Seite eines kleinen Festivals. 
Außerdem sind in der crypto Liste *.pr0gramm.com enthalten und die haben soweit ich das weiß, seit einiger Zeit nichts mehr mit mining zu tun.
Bitte mal aktualisieren oder mich eines besseren belehren ;)

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Mühen und die Info.

Tropen-Tango wird gelöscht und auf die Whitelist gesetzt, 

pr0gramm.com wird ebenfalls gelöscht aber nicht auf die Whitelist gesetzt. Die Domain hat wohl Mining auf entsprechenden SubDomains betrieben. Insoweit lassen wir die Subdomains drin, entfernen die Domain und die Subdomain www.

Damit müsste die Website wieder benutzbar sein. Ferner können wir dann sehen, ob die Hauptdomain über die anderen Quellen wieder eingespielt wird.

Vielen Dank für den Hinweis. Viele Grüße.

**Comment by Luzifix** [comment]
Die Subdomains
- vid.pr0gramm.com
- app.pr0gramm.com
- img.pr0gramm.com
sowie die root Domain pr0gramm.com müssten ebenfalls wieder freigegeben werden.
