### ISSUE TITLE
7 domains invalid!

### ISSUE THREAD

**Issue by privatehosting** [RPiList/specials#233]
Folgende Meldung erhält man beim Starten vom PiHole

```
https://raw.githubusercontent.com/RPiList/specials/master/notserious
  [i] Status: Pending...
  [✗] Status: Not found
  [✗] List download failed: using previously cached list
  [i] Received 16860 domains, 7 domains invalid!
      Sample of invalid domains:
      - große-marke.de
      - günstighosten.de
      - rayban–brille.de
      - schlüsseldienst-pforzheim-24.de
      - schwarzschnürhalbschuhe.de
```

**Comment by H4ckZ** [comment]
Liegt daran, dass aus Gründen der Übersichtlichkeit vor einer Weile die Blocklisten in einen entsprechenden Ordner verschoben wurden.
Der neue Pfad für die von dir angegebene Datei ist:
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious

**Comment by RPiList** [comment]
@privatehosting Das Problem dürfte dann bei mehreren Listen bestehen. Insoweit, wie @H4ckZ erwähnte, die alten URLs löschen und die neuen einfügen.
