### ISSUE TITLE
doppelte Domains

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#234]
browser.pipe.aria.microsoft.com taucht in Pornblock1, malware und easylist auf.

Vorschlag: Alle eigenen Listen zu einer zusammenfassen und nach doppelten Einträgen und wiederkehrenden Elmenten suchen um dann die RegEx-Filter zu erweitern.

**Comment by H4ckZ** [comment]
>Vorschlag: Alle eigenen Listen zu einer zusammenfassen und nach doppelten Einträgen und wiederkehrenden Elmenten suchen um dann die RegEx-Filter zu erweitern.

Denke, dass das eher gegen denn bisherigen Ansatz geht, wo die Leute nach den eigenen Wünschen Listen aktivieren können. Dadurch kommen Domains die in mehr Listen passen auch gerne mal mehrfach vor.
Sollte aber eigentlich kaum ein Problem darstellen, da PiHole beim Laden der Listen ohnehin Duplikate entfernt.

**Comment by RPiList** [comment]
Ja, wie @H4ckZ schon erwähnte, ist es nicht tragisch, dass es doppelte Domains gibt. So gibt es eben Nutzer, die eine der Listen nicht "abonniert" haben. Warum die genannte Domain in der Pornblock ist, erschließt sich mir aber auch nicht. :-)

Dem Pi-hole ist das egal, wie @H4ckZ ebenfalls erwähnte, filtert Pi-hole Duplikate raus.

**Comment by BulldozerPete** [comment]
Ich weiß dass das PiHole doppelte Domains erkennt.
Aber eine Microsoft URL gehört definitiv nicht in pornblock.

**Comment by H4ckZ** [comment]
Das ist allerdings ne gute Frage, wie die beim pornblock gelandet ist 🤣

**Comment by My1** [comment]
ggf mal commits stöbern. bei so ner mega file geht leider nicht einfach mal blame

**Comment by RPiList** [comment]
Okay... dann habe ich die ursprüngliche Meldung falsch interpretiert. Dachte es ging um doppelte Domains, nicht um False Positives.

Eintrag ist nun aus allen Listen gelöscht und auf die whitelist gesetzt.

**Comment by My1** [comment]
es ging etwas um beides.

zum einen dass halt domains doppelt waren und als idee zum Aufräumen für bessere übersicht eben deduplizierung
