### ISSUE TITLE
Anleitung fork und Github Desktop App benötigt

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#236]
Hallo,
ich komme mit den Forks und der Github Desktop App nicht klar. Kann bitte jemand eine Anleitung erstellen, die (hoffentlch) zu mehr sinnvollen Einsendungen und reduziertem Mehraufwand für den Maintainer führt?

Danke im Voraus.

**Comment by H4ckZ** [comment]
Was genau würdest denn brauchen?

**Comment by BulldozerPete** [comment]
Die Desktop App aheb ich installiert und mich eingeloggt.
Nur kann ich im Browser keine großen Blocklisten editieren. Ich scheitere aber daran den commit zu machen.
Vielleicht wäre eine bebilderte Anleitung wie hier gut: https://github.com/RPiList/specials/blob/master/dev/PullRequest.md

**Comment by RPiList** [comment]
> Hallo,
erstellen, die (hoffentlch) zu mehr sinnvollen Einsendungen und reduziertem Mehraufwand für den Maintainer führt?

Kein Stress wegen uns machen. Von hier aus betrachtet läuft das alles perfekt. Dass man ein Commit reinkommt, den wir nicht übernehmen können (wie letztens mit den zwei falschen URLs) ist völlig egal. Das wird dann von Hand eingepflegt. Das ist keine Arbeit.

Was aber schon öfter passiert ist, ist dass wir eine Änderung durchgeführt haben, die wir nicht hochladen konnte, weil sich die Base online geändert hatte. Dann mussten wir immer erst den online stand ziehen und dann erst unsere Änderungen hochschieben. Glücklicherweise wurde dabei noch nie etwas "überschrieben".

Aber ich könnte es mir als sehr ärgerlich vorstellen, wenn wir beide an einer Datei rumändern... und uns das um die Ohren fliegt. Sicher gibt es Möglichkeiten solche Diff-Konflikte zu lösen. Nur weis ich auch nicht wie. Bisher haben wir damit immer mit dem "Holzhammer" reagiert. Solange wir damit nur "unsere" Arbeit kaputt machen ist das egal. Wäre aber ärgerlich, wenn Sie sich da Mühe machen und wir dann einfach nur alles Löschen, weil wir es nicht gebacken kriegen.

**Comment by BulldozerPete** [comment]
Danke für das Verständnis und die Mühe die Ihr Euch hier macht!

Ich verstehe wie der theoretische Ablauf eines commits und reviews abläuft. Nur habe ich den Anspruch an mich, einen sauberen commit mit der Desktop App zu machen, der ggf. editiert werden kann, wenn ein Fehler enthalten ist.

**Comment by H4ckZ** [comment]
Das ist sowieso gegeben.
Wenn ein Commit von dir z.B. via Pull-Request akzeptiert wird kann daran jeder weiterarbeiten.
Du kannst auch (falls ich mich jetzt nicht irre) beim Erstellen des Pull-Request festlegen, ob dieser von anderen editiert werden kann oder nicht.

**Comment by BulldozerPete** [comment]
Dass es diese Option gibt, wusste ich nicht. Vor ein paar Tagen konnte mein commit laut @RPiList nicht geändert werden, weil dieser nicht editierbar war.

Mein Vorgehen:
- GitHub App starten -> Abgleich mit Repo,
- im Explorer/Finder zu der Datei navigieren, diese anpassen und dann speichern,
- zurück in der App Headline in Beschreibung hinzufügen und in das geforkte Repo committen,
- Im Web-Browser https://github.com/RPiList/specials/ aufrufen und mein geforktes Repo (rechts) mit dem RPiList Repo links abgleichen und pull request erstelln.

**Comment by H4ckZ** [comment]
> Dass es diese Option gibt, wusste ich nicht. Vor ein paar Tagen konnte mein commit laut @RPiList nicht geändert werden, weil dieser nicht editierbar war.

Beim Erstellen eines Pull-Requests gibts unten einen Haken, der angibt ob Änderungen erlaubt sind oder nicht. Wenn der drin is sollte alles gut sein.


![PR-Edits](https://user-images.githubusercontent.com/30937993/79580583-810b3a80-80c9-11ea-9786-a57e59bdace1.png)

**Comment by BulldozerPete** [comment]
Ok danke.
