### ISSUE TITLE
Someonewhocares.org

### ISSUE THREAD

**Issue by Scrat80** [RPiList/specials#240]
The website in question hosts blocklists, but your malware list blocks it.

https://www.someonewhorecares.org

**Comment by RPiList** [comment]
According to my search, "someonewhocares.org" is not on our lists.

Greetings.

**Comment by RPiList** [comment]
Found it in our "malware" list. Strangely it did not show up on a grep-search.

**Comment by RPiList** [comment]
The two domains have been deleted. Thanks vor letting us know. Greetings.
