### ISSUE TITLE
Jugendschutz

### ISSUE THREAD

**Issue by RPiList** [RPiList/specials#241]
Hi,

hier mal ein Gedanke mit der Bitte um Rückmeldung.

Manchmal bin ich ein wenig überrascht, wie schnell sich die Listen des Projekts verbreiten. Mit der Verbreitung werden die Listen mitunter auch Nutzern bekannt, denen sie nicht unbedingt bekannt sein sollen.
Die Jugendschutzliste ist für den Erziehungsberechtigten, der sie in sein Pi-hole laden möchte, NICHT für den 10 Jährigen, der mal etwas "Verbotenes" aufrufen möchte. Natürlich weckt so etwas Begehrlichkeiten. Aber ich möchte natürlich vermeiden, dass die neuesten Websites auf dem Schulhof getauscht werden, weil es irgendwo hipp ist. Google darf solche Seiten nicht auswerfen, aber wir listen die alle fein säuberlich auf? Das ist auch der Grund, warum das Bundesministerium für Jugend usw... die Sperrliste nicht rausgibt, sondern NUR eine Hashwert-Liste.

Insoweit hatte ich mir gedacht, dass die derzeit ca. 2700 Domains einfach zwischen anderen Domains versteckt werden. Ich könnte z.B. alle Domains der "easylist" ebenfalls in die Jugendschutz Liste packen. Dann wären es ca. 320.000 Domains. Natürlich kann man dann immer noch die Liste von Hand durchgehen, aber es ist definitiv aufwendiger. In dem Verhältnis sind dann 99% der "neuen" Jugendschutz-Liste "fake". Das macht das finden schwieriger.

Damit neue Zugänge nicht über die "History" zu sehen sind, würde ich die Liste nur noch vollständig hochladen. 

Sollten sich alte Historien-Einträge nicht löschen lassen, müsste ich die Liste evtl. umbenennen und die alte Liste vollständig löschen. Damit man dort einen Neustart machen könnte.

Natürlich könnten dann die Leute sich beschweren, dass offensichtlich falsche Einträge in einer Liste sind. Und dann wir die Listen nur unnötig "aufblähen". Aber dem Pi-hole ist das egal. Das löscht alle Duplikate und nimmt sich von der 320.000 Einträge-Liste nur die 2700 richtigen Einträge raus.

Oder hat jemand bessere Vorschläge?

**Comment by BulldozerPete** [comment]
Klingt plausibel für mich.
Wie verteilt z.B. das Bundesministerium für Jugend solche Listen mit Hashwert? Wir wären ja nicht die erste Anwendung die jungendgefährdende Inhalte blockieren möchte.

**Comment by RPiList** [comment]
Ja, diejenigen, die das Bundesjugendschutzmodul nutzen wollen (z.B. Routerhersteller) bekommen nur eine Liste mit Hashwerten und die Anleitung wie die Domains zu hashen sind. D.h. Domainabfrage im Router, wird gehasht, verglichen und dann verworfen oder durchgelassen.

**Comment by BulldozerPete** [comment]
Okay. Das würde bedeuten, dass das Pi hole ja so ein Modul out-of-the-box bräuchte.

**Comment by BulldozerPete** [comment]
Irgendwie bieten viele Drittanbieter eine Liste ohne Jugengefährdende Inhalte an und eine mit.
Hier zwei Beispiele:
- [mhhakim](https://github.com/mhhakim/pihole-blocklist)
- [StevenBlack](https://github.com/StevenBlack/hosts)

Wenn wir auch eine Easylist mit und ohne Jugengefährdende Inhalte anbieten, dann brächte ich ja nur beide Listen automatisch vergleichen und die Differenz wären dann diese Inhalte. Ein richter Schutz wäre das auch nicht.

**Comment by RPiList** [comment]
Ja, natürlich ist es möglich mit einem Diff-Vergleich die "versteckten" Einträge wieder zu finden. Aber das wird die Zielgruppe nicht können.

Ich kann aber auch 150.000 Einträge aus der easylist und 150.000 Einträge aus der Malware-List nehmen. Dann wäre es nicht mehr möglich. Der Issue hier könnte gelöscht werden, so dass später nicht mehr nachvollziehbar ist, wie die Datei "verunreinigt" wurde. 

Die Mischung muss halt nur mit Listen geschehen, die fast jeder benutzt. Sonst bekommen wir Beschwerden, dass wir den Leuten was unterschieben, was sie nicht haben wollten. Denke mal bei Werbung und Schadware beschwert sich keiner. Nur die, die sagen, dass die Liste zu viele falsche Einträge hat. :-)

**Comment by RPiList** [comment]
Erledigt. Da ich die alte History nicht gelöscht bekomme, habe ich die Datei umbenannt. Dann ist das ganze auch für internationale Nutzer leichter zu verstehen.
