### ISSUE TITLE
Outlook.com blockiert wenn Phishing-Angriffe aktiv

### ISSUE THREAD

**Issue by xlimit91** [RPiList/specials#242]
Sobald die Liste Phishing-Angriffe in PiHole aktiviert ist, kann ich Outlook.com nicht mehr aufrufen. Ist das beabsichtigt?
URL: www.outlook.com

![image](https://user-images.githubusercontent.com/24847824/79633112-aea4c200-8163-11ea-85c0-93b3d8f66188.png)

**Comment by BulldozerPete** [comment]
Sicherlich nicht.

**Comment by BulldozerPete** [comment]
Siebe pull request #243

**Comment by RPiList** [comment]
Eintrag wurde entfernt. 

Vielen Dank für den Hinweis.
