### ISSUE TITLE
Whitelist covidkashmir.org

### ISSUE THREAD

**Issue by haideralipunjabi** [RPiList/specials#248]
Hi,
Developer of covidkashmir.org here, couldn't understand why you have blocked my website. It just keeps a record of Covid Patients in my state.
If you have any questions, feel free to ask.

[Repository of Website Source Code](https://github.com/haideralipunjabi/covid19kashmir)

**Comment by BulldozerPete** [comment]
Your domain is a false positve.
See #249

**Comment by BulldozerPete** [comment]
@haideralipunjabi https://covidkashmir.org/ is now whitelisted.
How did you found this repo?

Would you like to share with us other fake COVID19 blacklists?

**Comment by haideralipunjabi** [comment]
My website is getting some media attention and we try to add those to the press section. I was looking if any other site mentioned us, and found this repo

**Comment by BulldozerPete** [comment]
Okay.

**Comment by RPiList** [comment]
Domains have been deleted. Greetings.
