### ISSUE TITLE
VMware Player & QNAP NAS Image

### ISSUE THREAD

**Issue by west89** [RPiList/specials#25]
Ich habe mal geguckt und sehen das dass VMware Player & QNAP NAS Image über 2,35GB groß ist und auf Ubuntu bassiert und man nicht den Weg und baut es auf ein
Debian 10 Xfce CD Version auf wo das Rohimage nur 639MB ist.
Ein bisschen aufschlagen kann man beide bestimmt noch.
https://www.debian.org/CD/http-ftp/

**Comment by RPiList** [comment]
Ja, das Image wurde absichtlich von uns auf Ubuntu aufgebaut. Hatten wir auch schon im Video kommentiert. Vielleicht klickt der ein oder andere ja mal herein und lernt Linux/Ubuntu kennen.
