### ISSUE TITLE
Die verdammmten links nach sempervideo.de auf Github sind Tot.

### ISSUE THREAD

**Issue by blub4747** [RPiList/specials#26]

**Comment by blub4747** [comment]
Allerdings habe ich nach durchgraben der Kommentare von unter folgenden Vide noch zwei andere links gefunden.

http://www.mediafire.com/file/holvn19exyte9rc/svpihole1911.img/file

https://mega.nz/#!aJ5DgKqR!sKYPoTlftVpGKepWn358yEsZEAU8ShFfcpeMM2eW71s

Viell Spass damit

**Comment by H4ckZ** [comment]
Links funktionieren bei mir eigentlich alle.
Welche genau meinst du denn?

**Comment by Muchato** [comment]
Ich biete sonst noch den hier:
https://my.hidrive.com/share/8j1983rkj7
Grüße

**Comment by cromefire** [comment]
Die sempervideo Seite scheint down zu sein

**Comment by H4ckZ** [comment]
> 
> 
> Die sempervideo Seite scheint down zu sein

Grade nochmal probiert. Bei mir funktioniert der Download.
Aber ggf. einfach einen der anderen Links oder den Torrent oben verwenden :)

**Comment by cromefire** [comment]
> > Die sempervideo Seite scheint down zu sein
> 
> Grade nochmal probiert. Bei mir funktioniert der Download.
> Aber ggf. einfach einen der anderen Links oder den Torrent oben verwenden :)

Es scheint das https down zu sein

**Comment by H4ckZ** [comment]
> Und die http Seite redirected auf `http://www.youtube.com/sempervideo`

Das ist schon ne Weile so.

**Comment by blub4747** [comment]
Danke an alle für anderen Download optionen!
