### ISSUE TITLE
Legitime URL in Phisingliste vorhanden

### ISSUE THREAD

**Issue by psollberger** [RPiList/specials#269]
Die URLs postfinance.ch und www.postfinance.ch ist das offizielle E-Banking der Schweizer Post und gehört da nicht in die Liste.

Die anderen Einträge dürften Phishing eben dieses Angebotes sein und damit legitim auf der Liste sein.

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
   postfinance.ch
   postfinance.ch.nnpkphc.87tb5dtrt.top
   sec3d.postfinance.ch.webscr.sarassales.com
   vpas.postfinance.ch.viscaones.info
   www.postfinance.ch
```

**Comment by RPiList** [comment]
Erledigt.
