### ISSUE TITLE
hinzugefügte Block Listen in Pihole

### ISSUE THREAD

**Issue by blub4747** [RPiList/specials#27]
Kann bitte jemand die hinzugefügten Listen aus den Video
https://www.youtube.com/watch?v=RVA1PLhAlTs

> Um Mitarbeit wird gebeten (Teil 2)

Hier in die Kommentare hier hineinschreiben, damit andere diese in Ihre bestehende Pihole Instanz hinzufügen können?

Wäre super

Danke!

**Comment by H4ckZ** [comment]
https://v.firebog.net/hosts/Easylist.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_all.list
https://raw.githubusercontent.com/RPiList/specials/master/easylist
https://raw.githubusercontent.com/RPiList/specials/master/Win10Telemetry
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt

glaub da sollte halbwegs alles dabei sein.

**Comment by blub4747** [comment]
Super dann muss man sich Video nicht Xmal anschauen. TOP!

**Comment by H4ckZ** [comment]
Der Issue kann damit glaubich auch geschlossen werden.

**Comment by RPiList** [comment]
Danke für die Mithilfe. Grüße.
