### ISSUE TITLE
Adler Mode

### ISSUE THREAD

**Issue by l-uuz** [RPiList/specials#271]
[www.adlermode.com](https://www.adlermode.com/) und [adlermode.com](https://adlermode.com/) sind fälschlicherweise in der easylist. Das ist ein seriöser Shop.

**Comment by Zelo72** [comment]
Wieso landennormale" Domains in die RPi EasyList? In der offiziellen Liste von easylist.to ist die Domain nicht enthalten.

**Comment by RPiList** [comment]
> [www.adlermode.com](https://www.adlermode.com/) und [adlermode.com](https://adlermode.com/) sind fälschlicherweise in der easylist. Das ist ein seriöser Shop.

Vielen Dank für den Hinweis. Ist gefixt. Viele Grüße.

**Comment by RPiList** [comment]
> Wieso landen normale" Domains in die RPi EasyList? In der offiziellen Liste von easylist.to ist die Domain nicht enthalten.

Ich hab jetzt noch nicht nachgeschaut. Kann mir aber gut vorstellen, dass sie drauf ist. Die EasyList unterscheidet zw. First- und Third-Party Adservern. In der ersten Kategorie wird Werbung geblockt, die direkt auf dem gleichen Server ist. Diese Domains dürfen natürlich nicht in unserer Blockerliste landen, weil bei DNS halt alles blockiert wird.

**Comment by RPiList** [comment]
Ja, in unseren Easylist Quellen war adlermode auch NICHT vertreten. Insoweit weiß ich auch nicht, wie die Domain da rein kommt.
