### ISSUE TITLE
paypal.com wird von "Phishing-Angriffe" blockiert

### ISSUE THREAD

**Issue by EneOli** [RPiList/specials#272]
Die Liste "Phishing-Angriffe" blockiert paypal.com

In der Liste steht unter anderem 

.paypal.com

Eventuell ist das der Schuldige?

**Comment by RPiList** [comment]
Dürfte eigentlich nicht. Pi-hole selbst findet die Domain nicht in der eigenen Liste, weil es keine gültige Domain ist. 

Aber es ist natürlich auf keinen Fall sinnvoll, das solch ungültige Domains in der Liste stehen. Und wenn Sie von Problemen reden, dann dürften die daher kommen. Daher habe ich gerade mal den Scanning-Prozess dahingehend angepasst und 181 Domains (über 3 Listen verteilt) gefunden, die alle mit einem Dot beginnen. Sind jetzt entfernt und werden künftig direkt gelöscht.

Kommt also nicht mehr vor. Insoweit auf jeden Fall vielen Dank für die Meldung.
