### ISSUE TITLE
Blocklists auf URLs durchsuchen?

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#275]
Gibt es eine Funktion mehrere URLs zu überprüfen ob diese durch den Pi Hole geblockt werden? Copy5paste im Browser ist bei merh als einer etwas umständlich.

**Comment by AleksCee** [comment]
```
pihole -q --help
Usage: pihole -q [option] <domain>
Example: 'pihole -q -exact domain.com'
Query the adlists for a specified domain
Options:
  -adlist             Print the name of the block list URL
  -exact              Search the block lists for exact domain matches
  -all                Return all query matches within a block list
  -h, --help          Show this help dialog
```

Also z.b.

`for i in heise.de bild.de test.de;do pihole -q -all ${i};done`
Ergibt:

 Match found in list.0.raw.githubusercontent.com.domains:
   oas.heise.de
 Match found in list.7.blocklist.site.domains:
   prophet.heise.de
   rl.heise.de
   advert.heise.de
 Match found in list.16.blocklist.site.domains:
   prophet.heise.de
 Match found in list.22.raw.githubusercontent.com.domains:
   oas.heise.de
   oas.wwwheise.de
   prophet.heise.de


Kannst auch eine Datei erstellen in der alle zu suchenden Domains drin sind Jede in einer Zeile und dann:

`cat meineDomains.txt | while read line;do pihole -q -all ${line};done`
