### ISSUE TITLE
Logoverwendung

### ISSUE THREAD

**Issue by DL6ER** [RPiList/specials#278]
Ein Benutzer hat uns kürzlich benachrichtigt, dass hier Betriebssystem-Images mit Pi-hole angeboten werden. Ich sehe, dass Sie das Pi-Hole "Vortex" -Logo ohne Attribution verwenden.

Aufgrund einer anhaltenden Situation, in der ein Dritter unsere Arbeiten und Logos derzeit ohne Erlaubnis anbietet (und gegen Geld verkauft), müssen wir Sie bitten, unser Logo nicht mehr für Ihr Projekt zu verwenden. Aktualisieren Sie außerdem Ihr GitHub-Repository und Ihre README-Dateien mit den richtigen Zuordnungen. Unter https://pi-hole.net/trademark-rules-and-brand-guidelines/ finden Sie eine Anleitung, in der erläutert wird, was verwendet werden kann und was nicht.

Dies ist keine feindliche E-Mail oder Handlungsaufforderung. Ich bitte Sie als Pi-Hole-Entwickler lediglich, Rücksicht auf unsere Arbeit zu nehmen. Wir gehen nicht davon aus, dass hier zu irgendeiner Zeit irgendeine böswillige Absicht bestand.

Wir können gerne hierüber diskutieren, bevorzugt (dann bitte auf Englisch) über adblock@pi-hole.net, sodass das ganze Team eingebunden werden kann.

Vielen Dank!
Dominik

**Comment by RPiList** [comment]
Hallo Dominik,

vielen Dank für Deine eMail. 

Vorab erläutert der Kontext der Situation: Mein Name ist Andreas und ich "promote" Pi-hole seit über 3 Jahren auf dem YouTube Kanal SemperVideo (youtube.com/sempervideo). Diese Videos werden traditionell auch von Zuschauern gesehen, die unerfahren im Umgang mit Linux und dem Raspberry-Pi sind. In den Kommentaren haben wir dann immer entsprechende Bitten erhalten, eine "Fire&Forget"-Lösung anzubieten. Also ein fertiges Image mit einem fertig installierten Pi-hole.

In einem Community-Projekt haben wir uns dann mit Zuschauern dazu entschlossen solche ein Version zu erstellen und entsprechende Blocklisten für die Zuschauer zu erstellen. Selbstverständlich ist das alles kostenlos.

Es ist nicht unsere Intension die Pi-hole Software zu verteilen und dabei den Eindrück zu erwecken, dass wir die Software erstellt hätten. Dies wird auch überall klar zum Ausdruck gebracht. Wir haben nur die Möglichkeit geschaffen, dass Nutzer sich ein Image auf eine SD-Karte kopieren können und dann eine fertige Installation vorfinden. D.h. die eigentliche Installation des Pi-hole entfällt.

Diese Art der Nutzung wird unter der von Dir genannten Seite  https://pi-hole.net/trademark-rules-and-brand-guidelines/ ausdrücklich als Fair-Use erlaubt. 1.: "No commercial purpose" und 2.: "no suggestion that you are the creator or source of Pi-hole, or that your project is approved, sponsored, or affiliated with us or the community".

Solltest Ihr das anders sehen oder wünschen, entfernen wir selbstverständlich trotzdem alle Logos aus unseren Images. Wobei dann - zumindest meiner Meinung nach - wirklich der Eindruck entstehen würde, dass wir die Software erstellt hätten und uns mit "fremden Federn" schmücken würden.

Viele Grüße,

Andreas

**Comment by RPiList** [comment]
> Wir können gerne hierüber diskutieren, bevorzugt (dann bitte auf Englisch) über [adblock@pi-hole.net](mailto:adblock@pi-hole.net), sodass das ganze Team eingebunden werden kann.
> 

wie gewünscht habe ich eine inhaltsgleiche Mail auch an adblock@pi-hole.net geschrieben. Allerdings kam eine Fehlermeldung zurück, dass ich keine Berechtigung hätte, diese eMail-Adresse anzuschreiben. 

![Unbenannt](https://user-images.githubusercontent.com/56664851/80988042-39a7dc80-8e33-11ea-96c2-1e5cc6f6f6c7.PNG)

**Comment by dschaper** [comment]
I've emailed you from dan.schaper@pi-hole.net. But it looks like you have updated your logo, so everything looks fine to me.
