### ISSUE TITLE
vlc.de in die Liste aufnehmen

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#28]
[vlc.de](http://vlc.de) scheint auch eine Crapware Seite zu sein.

**Comment by hammermaps** [comment]
Müsste man sich die Pakete von vlc anschauen ob die mit viel Werbung usw.
Ausgeliefert werden, also deutlich mehr als von der offiziellen Seite des vlc.
Ich bin jetzt nicht wirklich über viel Werbung oder Crapware gestolpert.

**Comment by H4ckZ** [comment]
Also ublock origin warnt bei vlc.de sofort mit der Kategorie "Badware" ^^

**Comment by RPiList** [comment]
Erledigt. Danke für die Mithilfe.
