### ISSUE TITLE
Blacklist removal of an academic interactive tool for COVID-19 outbreak detection

### ISSUE THREAD

**Issue by gilcaspi** [RPiList/specials#282]
Hi, 
We have an academic interactive tool for COVID-19 outbreak detection that is being used by policymakers and researchers all around the world. 
To our dismay, we found out that some of our users are having issues using this tool due to this automatic addition of our domain to  your blacklist. 
Can you please make sure that our domain is excluded from your blacklist? 

The domain: 
covid19maps.org
https://www.covid19maps.org

Best regards, 
Gil Caspi 
<gilcaspi@gmail.com>
on behalf of COVID-19 Research Team

**Comment by BulldozerPete** [comment]
Added to covid19 whitelist.

**Comment by RPiList** [comment]
Hi,

thanks for emailing us about your domain. Your domain has been removed.

Greetings.

**Comment by gilcaspi** [comment]
Thanks for the fast response.
