### ISSUE TITLE
self.events.data.microsoft.com auf Malwareliste

### ISSUE THREAD

**Issue by Zelo72** [RPiList/specials#284]
self.events.data.microsoft.com auf der Malwareliste? Ich glaube die ist da aus versehen rein gerutscht.

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
   self.events.data.microsoft.com

```
Meine WIndows-Rechner fluten den pi-hole mit Aufrufen weil die Domain nicht erreichbr ist,

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

> The following endpoints are used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. For more info, see Office 365 URLs and IP address ranges. You can turn this off by removing all Microsoft Office apps and the Mail and Calendar apps. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.

**Comment by Zelo72** [comment]
Auf der Liste sind noch mehr Microsoft Domains, die m. E. nichts auf einer Malwarliste zu suchen haben, ja es sind Telemetrie Domains dabie, aber die gehören m. E. auf eine Telemetrie-Liste:

 `cat malware | grep [.]microsoft[.]com$`

```
advertise.bingads.microsoft.com
advertising.microsoft.com
alpha.telemetry.microsoft.com
bingads.microsoft.com
browser.events.data.microsoft.com
choice.microsoft.com
continuum.dds.microsoft.com
corpext.msitadfs.glbdns2.microsoft.com
corp.sts.microsoft.com
df.telemetry.microsoft.com
diagnostics.support.microsoft.com
eu.vortex-win.data.microsoft.com
events.data.microsoft.com
ieonline.microsoft.com
ieonlinews.microsoft.com
mobile.events.data.microsoft.com
mobile.pipe.aria.microsoft.com
oca.telemetry.microsoft.com
redir.metaservices.microsoft.com
reports.wes.df.telemetry.microsoft.com
self.events.data.microsoft.com
services.wes.df.telemetry.microsoft.com
settings.data.glbdns2.microsoft.com
settings-sandbox.data.microsoft.com
settings-win.data.microsoft.com
settings-win-ppe.data.microsoft.com
spynet2.microsoft.com
spynetalt.microsoft.com
sqm.df.telemetry.microsoft.com
sqm.telemetry.microsoft.com
statsfe2.ws.microsoft.com
survey.watson.microsoft.com
telecommand.telemetry.microsoft.com
telemetry.microsoft.com
telemetry.urs.microsoft.com
umwatsonc.events.data.microsoft.com
us.vortex-win.data.microsoft.com
v10c.events.data.microsoft.com
vortex.data.microsoft.com
vortex-sandbox.data.microsoft.com
vortex-win-sandbox.data.microsoft.com
watson.microsoft.com
watson.ppe.telemetry.microsoft.com
watson.telemetry.microsoft.com
web.vortex.data.microsoft.com
wes.df.telemetry.microsoft.com
www.bingads.microsoft.com
```

**Comment by RPiList** [comment]
Die Meinung, dass Domains gem. der Zugehörigkeit in verschiedene Listen gehören, wird leider nicht oft geteilt. Im Grunde macht das keiner, bis auf die recht junge Pi-hole Community.  Klar gibt es Maintainer, die der Meinung sind, Tracking sei Schadware. Genauso wie Crypto oder Phishing dem Nutzer "Schaden" zufügen und damit zu "Schadware" gehören.

Die andere Fraktion gehört zu den Maintainern von Proxy- bzw. Hostlisten, welche bauartbedingt immer nur eine Liste akzeptieren. Also wird alles in die eine Liste gepackt, eine Unterscheidung kann nicht stattfinden.

Daher sind viele Listen da draußen recht umfänglich und beinhalten diese Domains. Da unsere Listen gem. den Quellenhinweisen auf einigen dieser Listen aufbauen, importieren wir die jedesmal aufs Neue.

Die Domains auf die Whitelist setzen geht auch nicht, da diese dafür sorgt, dass die Domains in allen Listen gelöscht würden werde. Auch in den Tracking-Listen.

Die ursprünglich genannte Domain "self.events.data.microsoft.com" wandert natürlich auf die Whitelist, da diese für den Dienst zwingend notwendig ist. In dem Punkt wundert mich, dass das nicht von Microsoft offen kommuniziert wird. Wir haben ja in dem Verzeichnis "Internet Services" eine Lauflistung aller benötigten Domains. Da sollte diese dann eigentlich schon vertreten sein.

Grüße.

**Comment by Zelo72** [comment]
OK, danke, sowas dachte ich mir schon und ich verstehe das dies nicht so einfach zu trennen ist.
