### ISSUE TITLE
Ungültige Einträge

### ISSUE THREAD

**Issue by whoot** [RPiList/specials#286]
Hallo,

beim Update der Liste in Pihole wird folgende Meldung ausgegeben:

```
  [i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  [✓] Status: Retrieval successful
  [i] Received 23147 domains, 2 domains invalid!
      Sample of invalid domains:
      - vinlu.de​
      - www.vinlu.de​
```

Die Einträge scheinen ungültig zu sein, da es die Webseite nicht mehr gibt.
Sie können vermutlich gelöscht werden.

Grüße

**Comment by lastsamurai26** [comment]
same here 


  [i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock1
  [✓] Status: Retrieval successful
  [i] Received 999990 domains, 1 domains invalid!
      Sample of invalid domains:
      - bigebony%20tit.com

**Comment by RPiList** [comment]
>   [i] Received 23147 domains, 2 domains invalid!
>       Sample of invalid domains:
>       - vinlu.de​
>       - www.vinlu.de​
> ```
> 
> Die Einträge scheinen ungültig zu sein, da es die Webseite nicht mehr gibt.
> Sie können vermutlich gelöscht werden.

Das sind Punycode Domains. Die beiden Domains sind zweimal in der Liste vertreten. Einmal als Punycode und einmal ohne. Ich weiß nur noch nicht, wie ich feststelle, welche die Punycode Domain ist.

Aber ja, im Notfall lösche ich alle 4.


> 
> Grüße

**Comment by whoot** [comment]
Danke fürs Aufklären! Scheint wohl ein Fehler bei der Verarbeitung der Einträge in pi.hole zu sein.

**Comment by beerisgood** [comment]
Die Einträge sind immer noch in der Liste enthalten!

>   [i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  [✓] Status: Retrieval successful
  [i] Received 23147 domains, 2 domains invalid!
      Sample of invalid domains:
      - vinlu.de​
      - www.vinlu.de​

**Comment by RPiList** [comment]
> Die Einträge sind immer noch in der Liste enthalten!

Bis auf Weiteres werden sie wohl in der Liste verbleiben. Unser Crawler greift diverse Internet-Foren ab. Dort hat z.B. jemand diese URL gepostet, einmal als Puny-Code und einmal als Nicht-Puny-Code. Deswegen hat der Crawler beide Versionen abgegriffen.

Wie schon zuvor erwähnt könnte ich alle 4 Domains löschen. Aber der Crawler würde die Domain wieder einsammeln. Danach mit der bestehenden Liste vergleichen und sehen, dass die Domain noch nicht in der Liste ist und sie dann wieder hinzufügen.  Gewinnen würden wir da also nichts.
