### ISSUE TITLE
updatepihole script 

### ISSUE THREAD

**Issue by Abcboy1** [RPiList/specials#287]
das neue Update script aktualisiert bei mir die blocklisten nicht mehr mach ich was falsch?

**Comment by BulldozerPete** [comment]
Lade mal Version 1.0.8: https://github.com/Zelo72/rpi/blob/master/pihole/updatePihole.sh

**Comment by Abcboy1** [comment]
das Problem ist das pihole findet die blocklisten nicht mehr seit pihole 5

**Comment by Abcboy1** [comment]
Domains Gravitylist: 5601305
grep: /etc/pihole/blacklist.txt: Datei oder Verzeichnis nicht gefunden
Domains Blacklist:
grep: /etc/pihole/regex.list: Datei oder Verzeichnis nicht gefunden
RegEx Blacklist:
grep: /etc/pihole/whitelist.txt: Datei oder Verzeichnis nicht gefunden
Domains Whitelist:
grep: /etc/pihole/adlists.list: Datei oder Verzeichnis nicht gefunden
Aktive Blocklisten:

**Comment by Zelo72** [comment]
Pihole 5 verwendet die Datenbank anstelle der Files in /etc/pihole. Das verlinkte Script von @BulldozerPete ist Pihole 4 und 5 kompatibel. Damit funktionert alles wieder.

**Comment by Abcboy1** [comment]
sorry das ich so blöd frage aber kann ich da im pihole die URLs eintragen

**Comment by Abcboy1** [comment]
weil ich habe das neue script aber die blocklisten wird nicht mehr aktualisiert

**Comment by AleksCee** [comment]
@Abcboy1 etwas genauer. Was passiert wenn du das Script startest, schick die Ausgabe bitte mal.

**Comment by Abcboy1** [comment]
Wenn ich das Script starte kommt die Meldung

-e [2020.05.16-23:42:02] [I] Pi-hole Gravity Update exitcode: 0
-e [2020.05.16-23:42:02] [I] Teste DNS Namensaufloesung ...
-e [2020.05.16-23:42:02] [I] DNS Namensaufloesung erfolgreich.
-e [2020.05.16-23:42:02] [I] Erstelle Aenderungs-Gravityliste /tmp/pihole/gravit                y_diff.list ...
-e [2020.05.16-23:42:02] [I] Exportiere Domains aus /etc/pihole/gravity.db nach                 /tmp/pihole/gravity.list ...
-e [2020.05.16-23:42:02] [I] Aenderungs-Gravityliste mit 0 Eintraegen erstellt.
./updatePihole.sh: 250: ./updatePihole.sh: [[: not found
-e [2020.05.16-23:42:02] [I] Exportiere Blacklist, RegExlisten, Whitelist und Ad                lists aus /etc/pihole/gravity.db nach /tmp/pihole ...
-e [2020.05.16-23:42:02] [I] Erstelle Pi-hole Gravity Update Bericht/Statistik 2                020.05.16-234202 ...

./updatePihole.sh: 282: ./updatePihole.sh: Syntax error: "(" unexpected

**Comment by AleksCee** [comment]
Das sieht sehr komisch aus. Wird der auch mit der bash ausgeführt? 
Wie rufst du das script auf? Wie hast du es geladen? Wo kommen die -e her?
Was sagt:
echo $0
echo $SHELL

Mir sieht das -e so aus als würde das Script mit sh und nicht bash laufen.

**Comment by AleksCee** [comment]
Kann es sein das du: sh ./updatePihole.sh aufrufst oder sowas? Oder das die default shell von root auf sh eingestellt ist? Oder du bash nicht installiert hast?

**Comment by Abcboy1** [comment]
ja ich hab es mit sh aufgerufen jetzt klappt alles danke
