### ISSUE TITLE
einfacher Import von mehr als einer Blocklist i Pihole 5

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#288]
Wie importiert Ihr mehrere Blocklisten im Pihole?
Bis Version 4 habe ich z.B. alle RPiLists per Copy-and-paste im Webinrerface eingetragen. Ab Version 5 bekomme ich immer einen Fehler. Gibt es einen anderen Weg die Listen z.B. per Konsole einzugeben?

**Comment by PascalHonegger** [comment]
In Version 5 müssen die Domains mit einem Leerzeichen getrennt sein. Ich habe als Workaround die Listen per Copy-Paste in mein Visual Studio kopiert und dort per Suchen-Und-Ersetzen die Zeilenumbrüche und überflüssige Leerzeichen entfernt (Suche mit Regex "\n    " -> ersetze durch "").

**Comment by RPiList** [comment]
> In Version 5 müssen die Domains mit einem Leerzeichen getrennt sein.

Danke für den Hinweis. Das ist dann aber ein blöder Bug, denn die "Anleitung" im Pi-hole 5 sagt deutlich, dass die Listen mit einem Komma und Leerzeichen zu trennen sind.

![Unbenannt](https://user-images.githubusercontent.com/56664851/81856051-817be180-9560-11ea-841f-6ff8d5ad7795.PNG)

Dies hatte bei mir nicht funktioniert... insoweit hatte ich auf ein Update des Pi-hole gewartet...

**Comment by BulldozerPete** [comment]
Selbst das Leerzeichen funktioniert bei mir nicht. Version 5 ist da ein deutlicher Rückschritt.

**Comment by BulldozerPete** [comment]
Gibt es kein Zugriff auf eine Datei in der ich die URLs manuell eintragen kann?

**Comment by RPiList** [comment]
Derzeit ist mir keine Möglichkeit bekannt. 
Ich gehe davon aus, dass das Bugs in der neuen Version 5 sind, die kurzfristig gepatcht werden. Solche Probleme gibt es bei jeder Software, so auch bei Pi-hole. Deswegen sagte ich in einem anderen Issue, dass Pi-hole 4 nicht sicherer/unsicherer sei als Pi-hole 5. Aus solchen Gründen hieß es früher immer, dass jedes Windows vor dem ersten ServicePack unbenutzbar ist. :-)

So auch hier, die early Adopter müssen sich mit sowas rumschlagen. Einfach mit dem Update warten.

**Comment by AleksCee** [comment]
@BulldozerPete Die Datei ist ja jetzt eine Datenbank, wenn du da rumfummelst und was falsch machst, geht mehr kaputt als du nutzen davon hast. Und so oft macht man doch keine Massen hinzufügen von URLs?

Letztendlich kannst du so gucken was für Listen in der dB stehen:

```
sqlite3 /etc/pihole/gravity.db 
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.

sqlite> select * from adlist;
```

Und mit einem insert oder Import könnte man auch Zeilen über eine Datei hinzufügen, aber will man das.

Evtl. Würde es auch gehen, habe den Code aber nur überflogen. Wenn du eine adlist.list unter /etc/pihole anlegst, dann versucht er die bei nem Update wieder zu migrieren. Aber alles ohne Gewähr und auf eigenes Risiko. Ist nichts was man jetzt auf dem produktiven System ausprobieren sollte.

Liebe Grüße, Alex

**Comment by RPiList** [comment]
Ich glaube das mit der Datenbank würde ich lassen. Der Unterschied zw. pihole4 und pihole5 ist die sog. Tree-Indizierung die dafür sorgen soll, dass blockierte Domains schneller gefunden werden. Wenn man das nicht hinkriegt, funktioniert auch das Ändern der Datenbank nicht.

Update der Blocklisten geschieht über pihole -g

Die Frage ist nur, wo die Blocklisten vorher liegen müssen, damit diese durch pihole -g mit "eingesaugt" werden.

**Comment by RPiList** [comment]
Aber um die Jungs mal zu loben. Das neue Blocking über CNAME Domains scheint sehr gut zu funktionieren.
![Unbenannt](https://user-images.githubusercontent.com/56664851/81984686-78107900-9635-11ea-80c9-55eae9d8736c.PNG)

**Comment by AleksCee** [comment]
Der Update Script scheint jedes Mal zu gucken ob es eine alte Liste gibt:

```
pi@pihole:/opt/pihole $ grep adlists.list gravity.sh 
adListFile="${piholeDir}/adlists.list"
Update domains from blocklists specified in adlists.list
```

piholeDir ist /etc/pihole 

Also wenn da ein adlists.list liegt wird die eingelesen und danach gelöscht.

Wobei eine haken gibt es da, passiert wohl nur wenn es vorher keine dB gab:

```
# Migrate pre-v5.0 list files to database-based Pi-hole versions
migrate_to_database() {
  # Create database file only if not present
  if [ ! -e "${gravityDBfile}" ]; then
```

Und wegen des trees, der wird für die zu blockenden Domains erzeugt, nicht für die Liste der Adblock-Listen URLs. Das sind ja nur ein Hand voll. Ich denke schon, dass man sie per insert dazu packen könnte. Aber wann, als bei der Initialen Einrichtung würde man mehr als 1-5 Listen hinterlegen und das kann man ja per gui machen.

Beim ersten Start könnte man aber den Weg über die Migration gehen.

Liebe Grüße, Alex

**Comment by Zelo72** [comment]
Ich habe ein Python-Script geschrieben um Blocklisten-URLs aus der "alten" adlists.list von Pihole 4 in die Pihole 5 Datenbank zu übernehmen:

https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/migratePiholeAdlists.py

Beschreibung:

```
# Python-Script: migratePiholeAdlists.py - https://github.com/Zelo72/rpi (/pihole/)
#
# Beschreibung:  Migriert die Blocklisten-URLs aus adlists.list von Pihole 4 in die adlist
#                Tabelle der gravity DB von von Pihole 5.
#                URLs aus adlists.list werden nur hinzugefügt, wenn sie in der Tabelle
#                adlist noch nicht vorhanden sind.
#               
#                Damit die Blocklisten migriert werden, müssen die zu migrierenen URLs in 
#                der Datei /etc/pihole/adlists.list gespeichert werden.
#                
#                Um z.B. die aktuellen Firebog Ticked Blocklisten nach Pihole 5 zu übernehmen,
#                könnte man folgende Befehle nutzen:
#               
#                sudo wget -O /etc/pihole/adlists.list https://v.firebog.net/hosts/lists.php?type=tick
#                sudo python3 migratePiholeAdlists.py
#                sudo pihole -g
#
# Aufruf:        sudo python3 migratePiholeAdlists.py
#
# Versionshistorie:
# Version 1.0.0 - [Zelo72] - initiale Version
```
