### ISSUE TITLE
Domain zum hinzufügen

### ISSUE THREAD

**Issue by ich423** [RPiList/specials#294]
Hallo, 

könnte man bitte vurf.pw in eine Blacklist hinzufügen. Die Domain war in einer Spammail.
Am besten würde sie in die notserious-liste passen.

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Die Domain wurde hinzugefügt. Viele Grüße

Am Mo., 18. Mai 2020 um 08:36 Uhr schrieb ich423 <notifications@github.com>:

**Comment by ich423** [comment]
Danke
