### ISSUE TITLE
Domains ohne "www." funktionieren weiterhin

### ISSUE THREAD

**Issue by m00sfett** [RPiList/specials#295]
Beispiel kinos.to:

https://kinos.to/
funktioniert weiterhin

http://www.kinos.to/
wird geblockt

Bitte die Domains (auch) ohne www-Subdomain eintragen, Danke :)

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Die Domain wurde hinzugefügt. Viele Grüße

Am Mo., 18. Mai 2020 um 12:00 Uhr schrieb m00sfett <notifications@github.com
