### ISSUE TITLE
Wie fügt mein eine Whitelist bei Pihole ein?

### ISSUE THREAD

**Issue by ovz93br43v7** [RPiList/specials#296]
Danke für eure Sammlung an Whitelists. Aber könntet ihr noch einen Hinweis einfügen wie man diese zu Pihole hinzufügt? Ich habe es bisher nur hinbekommen die einzelnen Domains hinzuzufügen, aber nicht die komplette Liste wie z.B. https://raw.githubusercontent.com/RPiList/specials/master/Internet%20Services/Amazon%20Video

Danke!

**Comment by RPiList** [comment]
Hi,

also für die Internet Services habe ich jetzt einfach die von Ihnen
verlinkte Seite aufgerufen. Dann alle mit der Maus markieren und kopieren.
Dann im neuen Pi-hole 5 unter Whitelist in die Textbox einfügen und "add to
Whitelist" klicken.

Dann werden die alle eingefügt. Viele Grüße

Am Mo., 18. Mai 2020 um 16:29 Uhr schrieb ovz93br43v7 <
notifications@github.com>:

**Comment by ovz93br43v7** [comment]
Ok danke, ich dachte man kann eine Whitelist wie eine Blacklist abonnieren.

Was mich noch wundert dass eure Whitelist für Xbox Live sehr viele Domains enthält, die ich in der Anzahl bisher nicht im Pihole Forum / Firebog gesehen habe.
Sind die wirklich alle für die Grundfunktionen notwendig?

Am 18. Mai 2020 18:00:43 MESZ schrieb RPiList <notifications@github.com>:

**Comment by RPiList** [comment]
> Ok danke, ich dachte man kann eine Whitelist wie eine Blacklist abonnieren. Was mich noch wundert dass eure Whitelist für Xbox Live sehr viele Domains enthält, die ich in der Anzahl bisher 

Die Whitelist-Einträge im Verzeichnis Internet-Services sind nicht als "Mindestdomains" zu sehen. Die Domains dort sind aus verschiedenen Adminforen zusammengetragen, die dann ihre Firewalls entsprechend konfigurieren, damit die Dienste funktionieren. Diesen Admins gehts dabei nicht unbedingt um Tracking, Werbung oder Ähnliches. Es ist also gut möglich, dass man "zuviel" freischaltet.

Deswegen steht bei uns in der "Anleitung" dazu auch, dass die Domains nur importiert werden sollen, wenn man feststellt, dass ein Dienst aus dem eigenen Netz heraus nicht funktioniert und man nicht die Pi-hole-eigene Loggingseite bemühen will.

**Comment by ovz93br43v7** [comment]
Ok danke für die Aufklärung!
