### ISSUE TITLE
login.yahoo.com in der malware liste

### ISSUE THREAD

**Issue by AMS21** [RPiList/specials#297]
login.yahoo.com ist die URL die zum Beispiel von Thunderbird benötigt wird um auf seine Email auf Yahoo zugreifen zu können. Die website hostet meines Wissens nach keine Malware aber ich lasse mich da gerne vom Gegenteil überzeugen.

**Comment by BulldozerPete** [comment]
Pull Requests wurden erstellt.

**Comment by AMS21** [comment]
Wow das ging schnell. Danke :)

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis, die Domain wurde jetzt auch aus der Malware-List entfernt. Viele Grüße.
