### ISSUE TITLE
Vorschlag von Torrent und IPFS, um den Server zu entlasten.

### ISSUE THREAD

**Issue by JanisPlayer** [RPiList/specials#30]
Ich wollte dieses Projekt unterstützen, indem ich euren Server entlaste.
Vielleicht schlissen sich ja noch andre an oder ihr macht selbst einen Knoten (IPFS oder Torrent).
Mein Interface doluge-web unterstützt leider keine Erstellung von .torrent Dateien sonst hätte ich eine .torrent hinzugefügt.

IPFS:
https://ipfs.io/ipfs/QmVNA5CMZw9ZFvy6tovQFaEPfbWwxefDpgKXjpakNYUZ8D svPihole1911.zip
https://ipfs.io/ipfs/QmQFCTjh545CxENFLc62KhipTXVQ3q8dEzuotPfTXZEdur  svpihole1911.img.zip

Falls IPFS wieder versagt und die Konfiguration gegen fremde Dateien nicht funktioniert ein direkter Link:
http://download.heldendesbildschirms.dynv6.net/svpihole1911.img.zip (6Tage verfügbar)
http://download.heldendesbildschirms.dynv6.net/svPihole1911.zip (6Tage verfügbar)
Bis zu 1 Gbit/s Download

Gibt es schon einen PiHole Server von euch den man als DNS-Server eintragen kann?
Wenn ja kann man diesen auch benutzerdefiniert konfigurieren für seine IPv4 & IPv6?

IPFS Konfiguration gegen fremde Dateien:
  "Reprovider": {
    "Interval": "0h",
    "Strategy": "pinned"
  },

**Comment by Tyberhertz** [comment]
Ich sage auch mal bescheid, dass die beiden Dateien / Images nun auch von einen 2ten Node abrufbar sind.
svPihole1911.zip: Ist bereits auf meinen Note verfügbar :-)
svpihole1911.img.zip ist nun auchg über meinen Note verfügbar

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Unterstützung.
