### ISSUE TITLE
Doppelte domains in notserious

### ISSUE THREAD

**Issue by voqeIfrei** [RPiList/specials#301]
Die Domains vinlu.de und www.vinlu.de sind in der notserious Liste doppelt vorhanden und werfen in pihole v5.0 diesen Fehler aus.

```
[i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  [✓] Status: Retrieval successful
  [i] Received 23503 domains, 2 domains invalid!
      Sample of invalid domains:
      - vinlu.de​
      - www.vinlu.de​
```

**Comment by RPiList** [comment]
Hi,

die Fehlermeldung wird ausgegeben, weil es "ungültige" Domains sind. Das Ganze haben wir hier schon mal ausführlicher dargestellt: https://github.com/RPiList/specials/issues/286

Unsere Programm-Routinen filtern bereits Punycodes. Aber den konnten wir noch nicht "catchen". :-)

Dem Pi-hole ist das aber egal. Das ignoriert die ungültige Domain einfach.

Viele Grüße

**Comment by voqeIfrei** [comment]
Ah verstehe. Vielen Dank für die Erklärung.

Viele Grüße
