### ISSUE TITLE
Mal wieder Domains zum hinzufügen

### ISSUE THREAD

**Issue by ich423** [RPiList/specials#302]
Hallo,

zum hinzufügen in die Spammail-liste:

tpnq.site
tafsirejavan.com
bieb.website
veix.host
likolehua.com
manganos.gr
serviaireecuador.com
versoixathle.ch
radiolaautintica.com
smallblue.pl
wubj.host
Frevistacorposano.com
ddxt.fun
Fhominsbc.ddns.net

Waren alle in Spammails, die in der letzten Woche gekommen sind.

Viele  Grüße

**Comment by RPiList** [comment]
Hi,
vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße
