### ISSUE TITLE
Falscher Eintrag in Gambling liste

### ISSUE THREAD

**Issue by Howlingmad1978** [RPiList/specials#304]
Hallo,
mich wundert, dass in der Liste https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling

die Webseite der Stadt Gelnhausen  www.gelnhausen.de geblockt wird.

Gruß Howlingmad1978

**Comment by RPiList** [comment]
Hallo,

vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
