### ISSUE TITLE
svPihole2004 Support und svPihole2005 Webinterface

### ISSUE THREAD

**Issue by BugBandit79** [RPiList/specials#305]
Hallo zusammen,

die zwei folgenden Fragen gelten für euer Pihole (.ova) auf einer virtuellen Maschine (Synology).
Wäre klasse, wenn ihr mir diese beantworten könntet. Vielen Dank vorab.

1) Unterstützt ihr auch weiterhin eure Pihole-Version svPihole2004 (nicht mehr im Download)?

2) In der (neuen) Version svPihole2005, werden im Webinterface / Administratorpanel, weder die ipv4, noch ipv6 Adresse des Pihole angezeigt. Ist das momentan noch normal / ein Anzeigebug?

**Comment by BugBandit79** [comment]
...und noch etwas:
Sollte man (egal in welcher Version) bei aktivierter ipv6-Unterstützung (Dual-Stack) im Router, die Kommunikation mit Unbound nur über ipv4 = 127.0.0.1#5353, oder auch über ipv6 = ::1#5353 erfolgen lassen? Ist ein Eintrag im Punkt "Rebind-Schutz" des Routers nötig (der eine sagt so, der andere anders. Was ist richtig?) Danke schonmal.

**Comment by RPiList** [comment]
> 1. Unterstützt ihr auch weiterhin eure Pihole-Version svPihole2004 (nicht mehr im Download)?

Wenn Sie die Version 2004 mit Pihole 4 weiter benutzen möchte, so steht dem natürlich nichts im Wege. "Unser" Teil besteht ja nur in Form von Blocklisten. Solange die nicht ihre URL ändern, können auch ältere Pi-holes immer darauf zugreifen. 

> 2. In der (neuen) Version svPihole2005, werden im Webinterface / Administratorpanel, weder die ipv4, noch ipv6 Adresse des Pihole angezeigt. Ist das momentan noch normal / ein Anzeigebug?

Die Version 2005 braucht natürlich auch die IP-Adressen im Webinterface. Die älteren Versionen haben dazu neugestartet. Das macht die neue Version 2005 nicht. Die Version 2005 geht nach ca. 30 Sekunden erst hin und schreibt die IP in die Configdatei und startet dann nur den "Pi-hole-Dienst" neu.

D.h. wenn Sie zu schnell nach dem Neustart in die Config-Datei geschaut haben, dann war die Einstellung noch nicht vorgenommen. Nach einer Minute muss die Einstellung aber da sein.

**Comment by RPiList** [comment]
im Router, die Kommunikation mit Unbound nur über ipv4 = 127.0.0.1#5353, oder auch über ipv6 = ::1#5353 erfolgen lassen? Ist ein Eintrag im Punkt "Rebind-Schutz" des Routers nötig (der eine sagt so, der andere anders. Was ist richtig?) Danke schonmal.

Das entscheiden Sie am besten nach Bedarf.  Ich weiß jetzt aus dem Kopf nicht mehr wie Unbound in dem entsprechenden Video konfiguriert wurde.  Wenns also keine Probleme mit ::1#5353 gibt, würde ich es anschalten.

Bzgl. Rebind-Schutz gehen wir davon aus, dass im eigenen Netz kein Angreifer sitzt. Für das normale LAN Zuhause ist das auch sicher richtig. Wer aber ein Pi-hole im Restaurant oder ähnliches anbietet, in dem dann Fremde sind, der kann den Schutz evtl. gebrauchen. Da gilt ebenfalls; entscheiden Sie nach bedarf.

**Comment by BugBandit79** [comment]
Vielen Dank für die schnellen und ausführlichen Antworten (Daumen hoch).
Ich werde die Version svPihole2005 noch einmal installieren.
Sollte es noch irgendwie "haken", darf ich hoffentlich nochmal schreiben, gem.  dem Slogan:
Bei Fragen, fragen ;-)
