### ISSUE TITLE
RE: svPihole2005 Webinterface IP-Adressen

### ISSUE THREAD

**Issue by BugBandit79** [RPiList/specials#306]
Auch nach diverser Wartezeit und Neustarts werden keine IP-Adressen (ipv4 + ipv6)          des Pi-Hole im Webinterface angezeigt. Pi-hole IPv4 address: 	und
Pi-hole IPv6 address:   bleiben leer.

Wie gesagt, alles auf einer VM auf dem NAS (.ova der svPihole2005).
Hat jemand das "Problem" auch, bzw. kann das bitte mal testen?

Bei der svPihole2004 keine Probleme.

Danke vorab.

Vielen Dank für die schnellen und ausführlichen Antworten (Daumen hoch).
Ich werde die Version svPihole2005 noch einmal installieren.
Sollte es noch irgendwie "haken", darf ich hoffentlich nochmal schreiben, gem.  dem Slogan:
Bei Fragen, fragen ;-)

_Originally posted by @BugBandit79 in https://github.com/RPiList/specials/issues/305#issuecomment-634404994_

Die Version 2005 braucht natürlich auch die IP-Adressen im Webinterface. Die älteren Versionen haben dazu neugestartet. Das macht die neue Version 2005 nicht. Die Version 2005 geht nach ca. 30 Sekunden erst hin und schreibt die IP in die Configdatei und startet dann nur den "Pi-hole-Dienst" neu.

D.h. wenn Sie zu schnell nach dem Neustart in die Config-Datei geschaut haben, dann war die Einstellung noch nicht vorgenommen. Nach einer Minute muss die Einstellung aber da sein.

**Comment by RPiList** [comment]
> Auch nach diverser Wartezeit und Neustarts werden keine IP-Adressen (ipv4 + ipv6) des Pi-Hole im Webinterface angezeigt. Pi-hole IPv4 address: und
> Pi-hole IPv6 address: bleiben leer.
> 
> Wie gesagt, alles auf einer VM auf dem NAS (.ova der svPihole2005).
> Hat jemand das "Problem" auch, bzw. kann das bitte mal testen?
> 
Hab die VM hier auch noch mal getestet und hier funktioniert alles so wie es soll.

Können Sie sich über Terminal auf der VM anmelden (Login: pi PW: 123456) und schauen, ob die Datei (/home/pi/1.info) erstellt wurde?

Viele Grüße

**Comment by BugBandit79** [comment]
Hi, da bin ich wieder.

die Datei 1.info wurde erstellt.
Ich weiß aber leider nicht, wie ich mir den Inhalt (Text) ansehen kann. :-(

**Comment by RPiList** [comment]
Habe die VM jetzt noch mehrmals getestet und ja es gibt ein Problem. Ich weiß nur noch nicht warum.

Die VM funktioniert in der VMware Umgebung genau so wie gewollt.

Im zweiten Test habe ich die OVA-Datei ebenfalls in mein NAS importiert. Und hier sehe ich das gleiche Problem, dass IPv4 und IPv6 nicht extrahiert werden kann.

Bin mir aber noch nicht sicher, ob die Pi-holeVM-Datei (*.ova) das Problem ist. Denn wenn ich in der VM auf dem NAS ein "sudo ifconfig" im Terminal eingebe, bekomme ich auch keine IPs angezeigt.

![Unbenannt](https://user-images.githubusercontent.com/56664851/83041349-ac763300-a040-11ea-9a1a-8a9539b14650.PNG)

Bis jetzt sieht das so aus, als wenn die VM im NAS nicht ins Internet darf. Dann kann das Pi-hole natürlich nicht funktionieren... 

Ich melde mich...

**Comment by BugBandit79** [comment]
Hallo und danke.
Ich bin leider nur „einfacher User“ und von daher mit den Befehlen im Terminal nicht so fit. Werde mich aber einlesen.
Noch etwas zum Verhalten der Version 2005: Nach dem ersten Start wurde dem Pihole keine IP im Router zugewiesen. Nach einem Neustart schon. Jedoch bleibt der Sachverhalt gem. Thema bestehen.
Ist mit den neuen / frischen Versionen Anfangs immer etwas frickelig. Schön ist, dass ihr sowas auf die Beine stellt und euch der Sache annehmt. Wird bald hoffentlich rockstable wie die 2004er. Hut ab und besten Gruß.

**Comment by RPiList** [comment]
> Noch etwas zum Verhalten der Version 2005: Nach dem ersten Start wurde dem Pihole keine IP im Router zugewiesen. Nach einem Neustart schon. Jedoch bleibt der Sachverhalt gem.

Vielen Dank für den Hinweis. Genau das selbe Verhalten sehen wir hier auch. Die VM bekommt vom NAS keine IP und schreibt Leerwerte in die Config. Nach einem Reboot bekommt die VM eine IP.

Verstehe noch nicht, warum die VM keine IP bekommt, denn die VM unserer Version 2005 ist die frühere Version 2004 (mit dem Pi-hole4), die wir nur aktualisiert haben und dann wieder exportiert.

**Comment by BugBandit79** [comment]
Hallo,
arbeiten Sie noch der Problemlösung und ist es nicht besser, vorübergehend, die 2005er-VM-Version aus dem Downloadbereich zu entfernen?
Sofern die 2004-Version, inkl. aller Listen, weiterhin noch funktioniert und auch supported wird, könnten Sie diese auch wieder zum Download anbieten.

**Comment by BugBandit79** [comment]
Hallo,
da hier nichts mehr passiert: CLOSED
