### ISSUE TITLE
updatePihole.sh funktioniert wohl nicht mehr mit pihole5

### ISSUE THREAD

**Issue by Plage1984** [RPiList/specials#307]
Guten Tag,

Ich wollte eigentlich nur mitteilen, dass das Update Script "updatePihole.sh" mit dem neuen Pihole 5 wohl nicht mehr so funktionieren wird, bzw. es auch nicht mehr funktioniert. Schuld ist wohl die Veränderung am Listen System

"gravity.list" is dead. Long live "gravity.db"

Auch die anderen Listen werden nicht mehr gefunden, wenn ich das Terminal richtig verstanden habe:

------------------------------------------------------------------------------------

[2020.05.27-16:52:10] [I] Erstelle Pi-hole Gravity Update Bericht/Statistik 2020.05.27-165210 ...
# Raspberry Info #

Hostname: 
CPU Temperatur: 36 Grad
RAM Nutzung: 8.68%
HDD Nutzung: 12%
Reboot erforderlich?: NEIN

# Pi-hole Info #

Pi-hole Status: AKTIV
Internet: OK
DNS-Test: FEHLER #Exitcode:1
Update: NICHT DURCHGEFUEHRT
Gravity Update: FEHLER #Exitcode:1

# Pi-hole Statistik #

grep: /etc/pihole/gravity.list: Datei oder Verzeichnis nicht gefunden
Domains Gravitylist:
grep: /etc/pihole/blacklist.txt: Datei oder Verzeichnis nicht gefunden
Domains Blacklist:
grep: /etc/pihole/regex.list: Datei oder Verzeichnis nicht gefunden
RegEx Blacklist:
grep: /etc/pihole/whitelist.txt: Datei oder Verzeichnis nicht gefunden
Domains Whitelist:
Aktive Blocklisten: 4

# Pi-hole Gravity Updatestatistik #

(+): 0 Domains hinzugefuegt
(-): 0 Domains geloescht
(S): 0 Domains geaendert

------------------------------------------------------------------------------------

Man kann das Pihole 5 wohl nur noch über "pihole -g" update oder?

Gruss

Plage

**Comment by BulldozerPete** [comment]
Pull Request #308 erstellt.
Danach geht auch Pihole 5.
