### ISSUE TITLE
All-in-One Liste wird von PiHole nicht akzeptiert

### ISSUE THREAD

**Issue by zocker-160** [RPiList/specials#309]
Bei den [All-in-One Listen](https://github.com/RPiList/specials/blob/master/Blocklisten.md#diverse---all-in-one-listen) ist auch `https://dbl.oisd.nl/` gelistet, was allerdings vom PiHole nicht akzeptiert wird:

```
pi@raspberrypi:~ $ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Target: https://abp.oisd.nl
  [✓] Status: Retrieval successful
  [i] Received 376720 domains, 376720 domains invalid!
      Sample of invalid domains:
      - ||0--e.info^
      - ||0-0-----------------------------------------------------------0.com^
      - ||0-0-0-0-0-0-0-0-0-0-0-0-0-18-0-0-0-0-0-0-0-0-0-0-0-0-0.info^
      - ||0-0-0-0-0-0-0-0-0-0-0-0-0-33-0-0-0-0-0-0-0-0-0-0-0-0-0.info^
      - ||0-168.com^

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
```
Vorschlag:

Es wäre besser, wenn man die entsprechende Liste in Hosts-Format verlinken würde: `https://hosts.oisd.nl/`
Diese funktioniert nämlich.

**Comment by Faydz** [comment]
Hey @zocker-160 in deiner blocklist hast du aber die `https://abp.oisd.nl` (die ist für Adguard Home etc) und nicht die `https://dbl.oisd.nl/` diese link automatisch auf die `https://hosts.oisd.nl/`

**Comment by zocker-160** [comment]
oof :facepalm: :facepalm: 
sry das tut mir Leid für die Fehlmeldung
