### ISSUE TITLE
svpihole1911.img als BerryBoot als Image

### ISSUE THREAD

**Issue by blub4747** [RPiList/specials#31]
Wer kennt schon BerryBoot?

Damit kann man auf einer 16GB MicroSD Karte zirca 4 Images draufspielen und kann immer wieder neue bzw andere Images aus probieren.

Somit kann jemand der schon einen Pi hat, aber nicht sofort noch einen weiteren Pihole holen möchte. Sich dieses Projekt 'eben mal' anschauen.

Wenn interesesse besteht.

BerryBoot bekommt man hier.

https://berryterminal.com/doku.php/berryboot

Und images von hier
https://berryboot.alexgoldcheidt.com/images/

Wenn also interesse besteht, könnte ich den BerryBoot images 'Bauer' bitten das Image hier für BerryBoot anzupassen.

**Comment by blub4747** [comment]
> 
Hello there Alexander,

Cloud you please process this images of Raspbian with Pihole on top of it.

https://mega.nz/#!aJ5DgKqR!sKYPoTlftVpGKepWn358yEsZEAU8ShFfcpeMM2eW71s

http://www.mediafire.com/file/holvn19exyte9rc/svpihole1911.img/file

Hashes of the Original image are provided here

https://github.com/RPiList/specials

The content of the image is just a normal full Desktop verson of Raspbian 10 Buster with Pihole installed on top of it.

And one or two additional list added to it.
You can see all of the lists on here
https://github.com/RPiList/specials/issues/27

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Vorschlag.

Ziel der Aktion ist es, das Pi-Hole so einfach wie möglich an den Nutzer zu bringen. Das wir die Zielgruppe dazu erwärmen können, neben dem Pi-hole auch andere Images zu nutzen, sehe ich in diesem Stadium noch nicht. Insoweit halten wir es lieber einfacher.

Viele Grüße.
