### ISSUE TITLE
Invalid domains in Blocklist notserious (dublications)

### ISSUE THREAD

**Issue by hduelme** [RPiList/specials#310]
In der Blocklist [notserious](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious) sind zwei Domains für das Pi-hole fehlerhaft:
![Bildschirmfoto vom 2020-05-30 17-33-24](https://user-images.githubusercontent.com/46139144/83332512-e0996000-a29b-11ea-8ed0-7d3f2b2223aa.png)
In der neusten Version des Pi-holes werden Fehler beim Importieren angezeigt. Hierbei ergab sich, dass zwei Domains ([vinlu.de​](vinlu.de​) und [www.vinlu.de​](www.vinlu.de)) nicht importiert werden konnten.

Ich habe mir die Blocklist angeschaut und festgestellt, dass die Domains doppelt eingetragen sind.
![Bildschirmfoto vom 2020-05-30 17-37-40](https://user-images.githubusercontent.com/46139144/83332595-5ef60200-a29c-11ea-9996-8b11e7ac9257.png)
Um die Fehler beim Importieren zu vermeiden, sollten die doppelten Domains entfernt werden.

**Comment by RPiList** [comment]
Hi,

den Umstand habe ich hier bereits erläutert: https://github.com/RPiList/specials/issues/286
