### ISSUE TITLE
Domains fuer die Whitelist

### ISSUE THREAD

**Issue by ich423** [RPiList/specials#312]
Wäre es möglich, dass man banggood.com und aliexpress.com auf eine der Whitelisten setzen könnte, weil die beiden Domains af einer Blackliste stehen.

Viele Grüße

**Comment by BulldozerPete** [comment]
Was ist denn banggood.com?

**Comment by RPiList** [comment]
> Wäre es möglich, dass man banggood.com und aliexpress.com auf eine der Whitelisten setzen könnte, weil die beiden Domains af einer Blackliste stehen.
> 
> Viele Grüße

Vielen Dank für den Hinweis. Sind jetzt beide Domains drauf und aus den entsprechenden Listen gelöscht.

**Comment by RPiList** [comment]
> Was ist denn banggood.com?

Website für Technik-Kram vornehmlich aus China.

**Comment by ich423** [comment]
Danke
