### ISSUE TITLE
Xbox One Youtube App

### ISSUE THREAD

**Issue by ovz93br43v7** [RPiList/specials#313]
Seit kurzem (ich nehme mal an durch irgendein Update der Xbox) funktionieren bestimmte Videos in der offiziellen Youtube App meiner Xbox One nur noch wenn ich folgende Domain erlaube:
googleads.g.doubleclick.net 

Ich meine ich kann mich auch irren, weil andere Geräte (Laptop, Android Smartphone mit NewPipe [alternative Youtube App]) brauchen diese Domain nicht. Deswegen wollt eich das erst selber nicht glauben, aber in einigen Versuchen mit der Xbox habe ich dann festgestellt das z.B. Videos wie die Tagesschau auch funktionieren ohne die oben genannte Domain. Aber einige Fitnessvideos (welche in irgendeiner Form Werbung für Produkte enthält) sind nur mit der obengenannten Domain abspielbar ansonsten hing die Xbox im Ladebildschirm für das Video fest.

Vielleicht kann das einer mit einer Xbox One mal gegenprüfen. Aber ich habe es gestern mehrfach probiert und es funktioniert leider reproduzierbar nur mit der Domain. Zum Glück kann man durch das Pihole v5 Gruppenmanagement die Freigabe auf nur ein Gerät beschränken.

**Comment by RPiList** [comment]
Die Domain wurde in dem Bereich "Internet Services" bei XBOX eingetragen. Die muss damit aber von jedem Nutzer - wenn notwendig - von Hand in die Whitelist des Pi-hole eingetragen werden.
