### ISSUE TITLE
analytics.twitter.com als malware

### ISSUE THREAD

**Issue by OberstVonGatow** [RPiList/specials#316]
Hi hab gerade festgestellt das analytics.twitter.com in der Malware Liste enthalten ist.
Dadurch lässt sich leider kein Link mehr aus Twitter aufrufen.
In einer Ad- oder Trackingliste macht die Domain denk ich Sinn aber Malware kann man bei twitter.com denk ich ausschließen.

**Comment by RPiList** [comment]
Hi,

es liegt (wahrscheinlich) nicht an der analytics Subdomain. Jedenfall kann ich das nicht nachvollziehen. Hier läuft alles. Kann es nicht eher daran liegen, dass der aufgerufene Link über einen Linkverkürzer arbeitet? Oder der Twitter-eigene Link-Verkürzer t.co, welcher z.B. auch von unseren RegEx gekillt werden kann.

**Comment by OberstVonGatow** [comment]
Oha das kann sein werde das nochmal checken. Danke
