### ISSUE TITLE
ext-sq.squarespace.com auf Malware List - false positive?

### ISSUE THREAD

**Issue by asmod3us** [RPiList/specials#319]
`ext-sq.squarespace.com` ist ein CNAME alias von [squarespace.com](https://www.squarespace.com/) auf die [sehr viele Domains](https://securitytrails.com/list/cname/ext-sq.squarespace.com) (Millionen wenn man der Seite glaubt) verweisen.

False positive bei mir: www.classicalguitartones.com

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde der Whitelist hinzugefügt. Viele Grüße
