### ISSUE TITLE
forms.gle

### ISSUE THREAD

**Issue by asmod3us** [RPiList/specials#321]
In #138 wurde bereits ueber forms.gle diskutiert und der Hinweis gegeben dass es auf der Whitelist sei. Stand heute (23.6.2020) sind `forms.gle` und `www.forms.gle` aber in der Liste Phishing-Angriffe vorhanden.

**Comment by RPiList** [comment]
Hi,

ja, dass verstehe ich auch nicht. Kann mich auch an das Thema erinnern.
Habe es erneut in die Whitelist aufgenommen und die Domains aus allen
Listen entfernt.

Viele Grüße und Dank für den Hinweis.

Am Di., 23. Juni 2020 um 16:39 Uhr schrieb Achim Staebler <
notifications@github.com>:
