### ISSUE TITLE
Warum ist Audacity auf der Liste?

### ISSUE THREAD

**Issue by NikoHD203** [RPiList/specials#322]
Es is doch nur für Audiobearbeitung, oder?

**Comment by NikoHD203** [comment]
Ok, hat sich erledigt, audacity.de is geblockt, aber die offizielle Webseite audacityteam.org nicht.

**Comment by RPiList** [comment]
Its more like domain squatting, where an almost identical domain name
offers almost the same content, waiting for inexperienced users to download
manipulated files...

Am So., 28. Juni 2020 um 20:05 Uhr schrieb NikoHD203 <
notifications@github.com>:
