### ISSUE TITLE
Probleme mit dem Unbound Cron

### ISSUE THREAD

**Issue by luckyheiko** [RPiList/specials#323]
Vielen Dank erst mal für die Super Videos usw.
leider habe ich nun herausgefunden das irgendwas nicht stimmt :(
/root/rootlist: line 6: service: command not found

wenn ich mit im Crontab nen 'Log' (18(nur zum test) * * * * /root/rootlist >> /var/log/private/cron.log 2>&1)
erstellen lassen, bekomme ich immer diese Fehlermeldung (/root/rootlist: line 6: service: command not found)
die auf die Zeile: service unbound restart deutet. 
was könnte hier der Fehler sein?
ist das bei Euch/Dir auch nachvorllziehbar?

würde mich über eine kurze Info sehr freuen

**Comment by Zelo72** [comment]
Hallo,

über cron findet er service nicht, du musst die Zeile wie folgt ändern:
/usr/sbin/service unbound restart

Gruß,
Gerd

**Comment by luckyheiko** [comment]
Hallo 
Vielen Dank für die schnelle Hilfe. 
ist dann die  specials/Unbound.md  generell falsch?
oder ist das dann nur bei meinem Pi so?
