### ISSUE TITLE
Deutsche Schund Gazetten 

### ISSUE THREAD

**Issue by grapefruit89** [RPiList/specials#324]
Dieses Projekt ist ja vom User für den User, 
ich hab zwar nicht sooo große IT Kentnisse und Fähigkeiten aber hier ist mein kleiner Beitrag... 
Vielleicht ist ja was dabei, ich würde mich freuen 
https://github.com/grapefruit89/Deutsche-Schund-Gazetten

**Comment by BulldozerPete** [comment]
Echt jetzt?
Nimm bitte noch wikipedia, russiatoday und breitbartnews auf. Dann ist die Liste vollständig.^^
Wie erfolgreich solche Versuche in der Vergangenheit waren ist hier nachzulesen #117 .

**Comment by grapefruit89** [comment]
> Echt jetzt?
> Nimm bitte noch wikipedia, russiatoday und breitbartnews auf. Dann ist die Liste vollständig.^^
> Wie erfolgreich solche Versuche in der Vergangenheit waren ist hier nachzulesen #117 .

Ach der Name ist hier wohl Programm, zum Glück sind nicht alle IT Bewanderten Menschen so Narzisstisch wie Sie... 
Getreu dem Motto wehe dem der weniger Ahnung hat von der Materie als man selbst, jeder fängt mal klein an.
Ich hab dazugeschrieben, dass es eher weniger für den Pi-Hole ist, trotzdem sind ausschließlich links dabei die Journalistisch fragwürdige Methoden verwenden. Die GEZ mag ich auch nicht aber das ist wohl ein anderes Fass..

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. 

Der Name ist evtl. etwas unglücklich gewählt, mit den "Schund-Gazetten". Da kommt dann direkt eine Wertung mit rüber, die (s.o.) bei dem ein oder anderen übel aufstößt.

Während auch ich der Meinung bin, dass die Bild-Zeitung absoluter Schund ist, sehe ich keinen Grund warum man z.B. 11freunde.de sperren sollte. Das ist (afaik) ein Fussball-Magazin. Keine Ahnung ob gut oder schlecht. Das Gleiche gilt für die Computer-Bild. Journalistisch gesehen, sicher der Bodensatz dessen was möglich ist. Aber eben nicht so ein Hetzblatt wie die Bild-Zeitung. Schon alleine weil es eine andere Zielgruppe hat.

Insoweit scheint das Ziel eher ein Anti-Springer-Verlag zu sein und die Diskussion hatten wir schon mal.

Ferner ist da die AFD in der Liste. Immer wert, dass man sie blockiert... aber eine Schund-Gazette haben sie nicht. :-) 

Bisher sind die Grundpfeiler der Listen "Werbung", "Phishing/Malware" und "Jugendschutz".  Jede Liste lässt sich direkt oder indirekt diesen Punkten zuordnen. Für den Nutzer sollte anhand des Namens ersichtlich sein, was das Ziel der Blockliste ist.

Viele Grüße,

P.S.: die AFD ist bei uns (afaik) in der Jugendschutz-Liste drin.
