### ISSUE TITLE
magiskmanager.com

### ISSUE THREAD

**Issue by DiamantTh** [RPiList/specials#326]
Macht es sinn magiskmanager.com plus die www. von den Blacklisten hier zu entfernen??

Folgende haben diese drinne malware und child-protection

MfG

**Comment by RPiList** [comment]
Domains entfernt aber nicht der Whitelist hinzugefügt. D.h. wenn die Domain immer noch Probleme hat, dann landet sie beim nächsten Update der Liste automatisch wieder in der Liste.

Viele Grüße.
