### ISSUE TITLE
Remove disq.us

### ISSUE THREAD

**Issue by DiamantTh** [RPiList/specials#328]
Evtl auch die www. Subdomain..
Einige Seiten benutzen ja dieses System für Kommentare, da Links in diesen Kommentaren nicht direkt aufgerufen werden sondern durch disq.us gekürzt werden.
Frage ist ob es Sinn macht diesen aus der Blacklist zu entfernen.

Befindet sich in Phishing-Angriffe

MfG
Thomas

**Comment by BulldozerPete** [comment]
Ich sehe mir das mal an, ob die URL auch in anderen Blocklisten auftaucht.

**Comment by BulldozerPete** [comment]
Taucht in keiner meiner Blocklisten auf.
Daher PullRequest für whitelist erstellt.

**Comment by DiamantTh** [comment]
> Ich sehe mir das mal an, ob die URL auch in anderen Blocklisten auftaucht.
> 
> Welche Webseiten funktionieren denn nicht?


Man könnte von jeden Link ausgehen der über disqus gepostet wird

MfG

**Comment by RPiList** [comment]
Domains wurden entfernt. Vielen Dank für den Hinweis. Viele Grüße.
