### ISSUE TITLE
Mal wieder Domains zum hinzufügen

### ISSUE THREAD

**Issue by ich423** [RPiList/specials#330]
Hallo,

könntet ihr bitte adserver.funkhaus.net zu einer Blacklist hinzufügen. Über die Domain wird Werbung verteilt (z.B.: https://www.gong971.de/non_cms/webradio/live/#)

Und für die NotSerious noch etwas:

drwilliamkuehnling.info
hotelparatimaringa.com
miktaldonmegor18.live

**Comment by RPiList** [comment]
Vielen Dank für die Info.

Alle Domains wurden den entsprechenden Listen hinzugefügt. Viele Grüße

**Comment by ich423** [comment]
Vielen Dank!
