### ISSUE TITLE
Whitelist iOS jailbreak Cydia Domain

### ISSUE THREAD

**Issue by pali768** [RPiList/specials#331]
Domain to be Whitlisted: cydia.saurik.com.cdngc.net 

Affected Lists: Child-protection and Malware

Details: The Domain cydia.saurik.com.cdngc.net is importent for the Cydia Homepage. Without Whitlisting it the Homepage is blank. This issue was also fixed in blocklist Project "Energized Protection".
Link: https://github.com/EnergizedProtection/block/issues/489

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden entfernt. Viele Grüße
