### ISSUE TITLE
Anchor_dns malware domains

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#332]
Anchor_dns malware Command & Control server domains:
Die Domain(s) `*.biillpi.com`
Die IP-Adresse ~~`23.95.97.59`~~

Entnommen aus diesem Artikel: [https://medium.com/stage-2-security/anchor-dns-malware-family-goes-cross-platform-d807ba13ca30](https://medium.com/stage-2-security/anchor-dns-malware-family-goes-cross-platform-d807ba13ca30)

Edit: Ich merke gerade IP-Adressen bei einem DNS-basiertem System zu blockieren macht wenig Sinn, zumindest die Domain kann man ja aufnehmen...

**Comment by RPiList** [comment]
alle Subdomains von biillpi.com zu sperren, ist nicht über die Blocklisten des Pi-hole möglich. Das müsste man über die RegEx Einträge von Pi-hole erledigen.
