### ISSUE TITLE
userbenchmark.com auf der malware liste

### ISSUE THREAD

**Issue by voqeIfrei** [RPiList/specials#334]
Hallo!

`www.userbenchmark.com`und `userbenchmark.com` befinden sich auf der malware Liste und sind meines Wissens nach keine bedenklichen Domains.

https://www.virustotal.com/gui/url/e1f7ffcb63e0150869656d7807973febff7690a4e1c7080157de5b4000b0715a/detection

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Domains wurden entfernt. Viele Grüße
