### ISSUE TITLE
MMoga.de not serious ?

### ISSUE THREAD

**Issue by Duell10111** [RPiList/specials#34]
Is it a mistake that mmoga.de is in the list of not serious sites, because it is a keyseller marketplace mit different sellers.

**Comment by RPiList** [comment]
Ja, ist ein Fehler.

Den Grundstock der Daten haben wir von anderen Quellen erhalten und dort war die Domain dabei. Bin auch nicht der Meinung, dass MMOGA hier hin gehört.

Vielen Dank für den Hinweis und viele Grüße.
