### ISSUE TITLE
media.graphcms.com ist keine Phishing-Domain

### ISSUE THREAD

**Issue by svewag** [RPiList/specials#343]
GraphCMS ist der Anbieter eines Headless-CMS und ist daher per se keine Phishing-Seite.
Die Domain sollte aus der Blockliste entfernt werden.

Ist bekannt wie die eigentliche Phishing-Seite lautet, die Content über media.graphcms.com verbreitet?

**Comment by belazer** [comment]
Danke @svewag für den Report! 
Ich arbeite bei GraphCMS und uns würde sehr interessieren welche Seite es geschafft hat unsere media domain auf die Phishing-Liste zu setzen. Wenn ihr diese Info noch habt, würden wir uns sehr über Tipps freuen!

**Comment by RPiList** [comment]
Phishtank.com meldet als Eintrag 6709315
![image](https://user-images.githubusercontent.com/56664851/90283423-8195c100-de70-11ea-9529-c80d030129e5.png)

**Comment by RPiList** [comment]
> GraphCMS ist der Anbieter eines Headless-CMS und ist daher per se keine Phishing-Seite.
> Die Domain sollte aus der Blockliste entfernt werden.
> 
> Ist bekannt wie die eigentliche Phishing-Seite lautet, die Content über media.graphcms.com verbreitet?
Uns ist nicht bekannt, von welchen Seiten auf die Phishing-Seite verlinkt wird. Das ist aber auch nicht wichtig. Wichtig ist, dass der Nutzer am Ende den Phishing-Link nicht aufrufen kann.

**Comment by RPiList** [comment]
Der "Phishing"-Inhalt ist derzeit auf der Domain nicht mehr verfügbar. Insoweit wird die Domain wieder aus der Liste entfernt. Da die URL aber zurecht "geflagt" wurde, kann ich die Domain nicht auf die Whitelist setzen.
