### ISSUE TITLE
www.fontawesome.io

### ISSUE THREAD

**Issue by svewag** [RPiList/specials#344]
Ich denke nicht, dass `fontawesome` auf die pornblock-list gehört.

Unter www.fontawesome.io werden Fonts ausgeliefert.

![image](https://user-images.githubusercontent.com/155578/90277611-38407400-de66-11ea-8203-d81ce5642bbb.png)

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Wurde gefixt.
