### ISSUE TITLE
Mal wieder Domains zum hinzufügen

### ISSUE THREAD

**Issue by 10k-resistor** [RPiList/specials#346]
Hallo,
könntet ihr bitte folgende Domains aus einer Spam-mail in eine der Filterlisten hinzufügen:

casualfrugal.de
maioresvvjo.casualfrugal.de
honest-digi.com
clickittee.com
winnerwinner.net

Vielen Dank

**Comment by BulldozerPete** [comment]
Pull-request wurde erstellt.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße.
