### ISSUE TITLE
Schon wieder Domains zum hinzufügen

### ISSUE THREAD

**Issue by 10k-resistor** [RPiList/specials#349]
Hallo,

könntet ihr diese Domains aus einer Spammail bitte in eine der Filterlisten hinzufügen.

voluptatibusgjca.pulsegrid.de
meetsap.com
aliasudoe.pulsegrid.de
racingventured.com
soltesperanza.com

Vielen Dank!

**Comment by 10k-resistor** [comment]
Noch eine zum hinzufügen: hetisgeengeheim6.live

**Comment by RPiList** [comment]
Alle Domains hinzugefügt. Vielen Dank für die Mühen.
