### ISSUE TITLE
ssh login?

### ISSUE THREAD

**Issue by infiSTAR** [RPiList/specials#35]
pi and raspberry doesn't seem to work.

what is the login?

**Comment by H4ckZ** [comment]
tried pi:123456?

**Comment by RPiList** [comment]
Das derzeitig angebotene Image ist nur für die Nutzer bestimmt, die a.) wissen was sie tun und b.) die Videos auf SemperVideo.de verfolgen bzw. kennen. Dieser Nutzergruppe ist dann auch das PW bekannt.

@H4ckZ hat es aber auch schon geschrieben. Vielen Dank und viele Grüße.

**Comment by infiSTAR** [comment]
Jap, sorry hatte es Minuten später selbst im Video gehört und hier nicht mehr drauf reagiert *shame* *shame* *shame*
