### ISSUE TITLE
Übersicht der Blocklisten sieht kaputt aus

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#350]
Wenn ich die Übersicht aufrufe `https://github.com/RPiList/specials/blob/master/Blocklisten.md` fehlen oben die Punkte zur gliederung so das alles in einer reihe ist. Wäre nett wenn man das anpassen könnte.
<img width="867" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/91661658-c4e16800-eadd-11ea-99cc-47db9cfc3092.PNG">

**Comment by RPiList** [comment]
Ja, sieht strange aus, aber ist absichtlich so. In der Form können die Listen alle in einem Copy und Paste dem Pi-hole hinzugefügt werden. Mit der alten Auflistung ging das nicht.

**Comment by JobcenterTycoon** [comment]
ach so ok
