### ISSUE TITLE
Blockliste notserious und fewo-direkt.de

### ISSUE THREAD

**Issue by brokfeld** [RPiList/specials#358]
In der Blockliste **notserious** ist mir aufgefallen, dass folgende Seiten aufgeführt sind:

**www.fewo-direkt.de**
**fewo-direkt.de**

Ich selbst habe noch nie über diese Seite eine Ferienwohnung gebucht,
dachte aber immer die Seite sei seriös.

Ich würde mich hier mal über Feedback freuen und dann ggf. die Löschung dieser Domain veranlassen.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Info. Auf die Schnelle konnte ich jetzt nicht ermitteln, woher dieser Eintrag auf der Liste stammt. Insoweit habe ich die zwei Domains einmalig entfernt. Schauen wir mal, ob die Domain wieder eingespielt wird.

Evtl. war es mal eine Fake-Shop Website, die nach dem allgemeinen Blocklisting verkauft wurde.

Viele Grüße
