### ISSUE TITLE
FritzBox Konfiguration mit ipv6

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#359]
In der Anleitung: https://github.com/RPiList/specials/tree/master/RouterKonfiguration/Fritz!Box%207590 wird lediglich die ipv4 Adresse des Pi-Hole eingetragen. Müsste hier nicht bei einem reinen dual-stack Anschluss (nicht ds-lite!) auch die ipv6 Adresse eingetragen werden? Und diese sollte mit fd00 beginnen. 

Funktioniert diese Kombination denn auch mit https://www.youtube.com/watch?v=AIwK4URbSv8&t=320s ?

**Comment by RPiList** [comment]
> In der Anleitung: https://github.com/RPiList/specials/tree/master/RouterKonfiguration/Fritz!Box%207590 wird lediglich die ipv4 Adresse des Pi-Hole eingetragen. Müsste hier nicht bei einem reinen dual-stack Anschluss (nicht ds-lite!) auch die ipv6 Adresse eingetragen werden? Und diese sollte mit fd00 beginnen.

Die Einsendungen der Routerkonfigurationen sind uns von Nutzern zugeschickt worden. Bei IPv6 sollte man die dortigen Einstellungen ebenfalls vornehmen. Sonst gehen "IPv6-Geräte" evtl. über einen anderen DNS-Server, weil nur die IPv4 Geräte die Pi-IP vom Router erhalten.
> 
> Funktioniert diese Kombination denn auch mit https://www.youtube.com/watch?v=AIwK4URbSv8&t=320s ?

Ja, da gibt es bei IPv4 vs. IPv6 keinen Unterschied, denn dort geht es ja um die Ports auf die zugegriffen werden soll.
