### ISSUE TITLE
Vorschlag für die Connect-Box + Bild von DHCP Horizon Box im Router Modus + Bilder von DNS Einstellungen für verschiedene Systeme.

### ISSUE THREAD

**Issue by JanisPlayer** [RPiList/specials#36]
Da es sicher viele nervt den DNS Server bei jedem Gerät einzelnen zu verändern hätte ich eine Idee.
Wie wäre es einfach auf dem Pi einen DHCP-Server zu hosten?
Das ist natürlich nur eine Lösung für die Leute die ihn bei sich Zuhause haben im Netzwerk.

Braucht es eigentlich noch Bilder wie man den DNS Server einzelnen ändert(Windows, Linux, Android) oder sollte das klar sein?

**Comment by RPiList** [comment]
Hi,

niemand muss auf jedem Gerät den DNS ändern. Schon alleine, weil es bei vielen Geräten gar nicht möglich ist den DNS-Server zu ändern.

Der Pi (bzw. Pi-hole) ist der DNS-Resolver. 

Damit die einzelnen Geräte auf den Pi zugreifen, gibt es zwei Möglichkeiten. Der Router sagt den Clients sie sollen auf den Pi zu DNS-Zwecken zugreifen oder der Router, sagt den Clients sie sollen weiter auf ihn zugreifen, während der Router selbst auf den Pi zugreift. Das sind die zwei Standardvorgehensweisen, dafür haben wir hier entsprechende Anleitungen im Ordner Router-Konfiguration.

Ausnahme ist, dass der Router die o.g. Einstellungsmöglichkeiten nicht zulässt.

**Comment by JanisPlayer** [comment]
> Ausnahme ist, dass der Router die o.g. Einstellungsmöglichkeiten nicht zulässt.
Genau darauf war mein Vorschlag bezogen.
Der RPI Soll die rolle des DHCP im Heimnetzwerk übernehmen.
Bei solchen Routern kann man ironischerweise den DHCP anschalten.
Das PRI IMG muss dann eigentlich nur mit einem DHCP-Server und ein Standart DHCP Config-Datei für die Connect-Box ausgelifert werden.
Das sollte man dann einfach per Script starten können.
So kann der DHCP vom RPI sich selbst als DNS-Server bei den Geräten im Heimnetzwerk eintragen.

Connect Box:
![Connect-Box](https://user-images.githubusercontent.com/54918417/70638033-7979e780-1c38-11ea-9f3d-af25651b791b.png)

[RPI als DHCP-SERVER](https://www.google.com/search?q=rpi+dhcp)

Horizon Box:
![](http://www.technik-tipps-und-tricks.de/wp-content/uploads/2016/08/UPC-Webapp1.png)

DNS-Server manuell verändern für Windows, Android, Ubuntu, Debian, Mint, IOS, macOS:

Windows:
![Windows 1](https://user-images.githubusercontent.com/54918417/70638361-091f9600-1c39-11ea-947b-edaeac1c3723.png)
![Windows 01](https://user-images.githubusercontent.com/54918417/70638098-91ea0200-1c38-11ea-8204-7b2f167aaccd.png)
![Windows 2](https://user-images.githubusercontent.com/54918417/70638105-944c5c00-1c38-11ea-9d48-3a64836c4482.png)
![Windows 3](https://user-images.githubusercontent.com/54918417/70638111-957d8900-1c38-11ea-8068-c2af9bd1bdce.png)
![Windows 4](https://user-images.githubusercontent.com/54918417/70638347-0329b500-1c39-11ea-8c66-78c145af65eb.png)

Android:
![Android 1](https://user-images.githubusercontent.com/54918417/70641070-59005c00-1c3d-11ea-89ef-a73e60d2a399.jpg)
![Android 2](https://user-images.githubusercontent.com/54918417/70641083-5bfb4c80-1c3d-11ea-8905-1528d764d537.jpg)
![Android 3](https://user-images.githubusercontent.com/54918417/70641100-5f8ed380-1c3d-11ea-9d8c-ff48b21ce0e8.jpg)
![Android 4](https://user-images.githubusercontent.com/54918417/70641110-63225a80-1c3d-11ea-8987-fe328c6db5c1.jpg)

Ubuntu, Debian, Mint:
https://wiki.ubuntuusers.de/DNS-Konfiguration/

IOS:
https://tekkie.eu/2018/04/02/ios-dns-server-aendern/

macOS:
https://praxistipps.chip.de/mac-dns-server-aendern_34740

**Comment by RPiList** [comment]
Also irgendwie verstehe ich das noch nicht ganz.

Okay, in der Connect-Box könnte man den DHCP-Server abschalten. Aber das würde imho gar nichts bringen, selbst wenn der Pi auch einen DHCP-Server anbieten würde. Und wenn die Clients die DNS-IPs nicht von der Connect-Box bekommen, muss man immer auf den Clients die IP und den DNS von Hand eintragen. Also ein Pi bringt in dem Szenario keine Vorteile.

Das einzige was theoretisch funktionieren würde ist wenn der Pi ein eigenes Subnetz aufmacht. Die Fritzbox hat als Netz die 192.168.1.1 und der Pi macht ein eigenes Netz auf in der er die 192.168.111.1 hat. Dann melden sich alle Clients über WLAN am Pi an. Dann bekommen alle Clients die IP und den DNS vom Pi übermittelt.

Im Netz der Fritzbox sieht es dann so aus, als wenn nur ein Client da wäre, namentlich der Pi. Der Pi sieht dann alle Clients und leitet den Traffic nur an die FB weiter. Solch ein Szenario haben wir hier auch schon mal durchgespielt. Wäre für nur WLAN Clients auch sehr einfach, weil der Pi WLAN mitbringt. Aber kabelgebundene Clients (PCs) könnten da nicht rein. Ausserdem würde dann wirklich der komplette Traffic über den Pi laufen. Das wäre beim Pi4 kein Problem, da er eine echte Gigabit-Netzwerkkarte hat.

ABER: Das Projekt richtet sich an eine Zielgruppe, die es "Einfach" braucht. Das gesamte o.g. Szenario ist viel zu komplex für die Zielgruppe. Das schaffen die nicht. Oder anders rum, die wollen nicht, wenn es mehr als 2 Mausklicks bedarf.

**Comment by JanisPlayer** [comment]
>  Okay, in der Connect-Box könnte man den DHCP-Server abschalten. Aber das würde imho gar nichts bringen, selbst wenn der Pi auch einen DHCP-Server anbieten würde. Und wenn die Clients die DNS-IPs nicht von der Connect-Box bekommen, muss man immer auf den Clients die IP und den DNS von Hand eintragen. Also ein Pi bringt in dem Szenario keine Vorteile.

Ja das war ein bisschen blöd verbunden von mir.
Die Anleitung wie man das Manuell einstellt, war nur für die gedacht die es unbedingt wollen.(Hatte nichts mit dem DHCP zu tun.)
Es ging mit mehr um den DHCP-Server auf dem RPI-4.
Dieser stellt ja nicht nur den DNS-Server auf den Geräten im Netzwerk ein, sondern legt auch eine IP-Adresse und noch viel mehr fest.
Ich bin auf die Idee gekommen, weil mich meine Horizon-Box auf die Nerven geht.
Diese hatte einen DHCP aktiviert, weil sie einen Softwarefehler hatte und sich selbstständig in den Router-Modus geschaltete.
Der Effekt war folgender, ich hatte plötzlich eine andere IP-Adresse einen anderen DNS-Server usw.
Diesen Effekt könnte man doch auch mit einem RPI erreichen, wenn dieser einen IPv4 DHCP nutzt.
Die Frage ist dann nur, ob man dann IPv6 DHCP auch hosten kann.

Mein Test hat funktioniert:
Ich habe es auf einer Virtuellen Box gehostet und den DHCP abgestellt.
Das ist meine Konfiguration Datei.
https://pastebin.com/7TTbw2cB
sudo apt-get install isc-dhcp-server
[dhcpd.conf](https://pastebin.com/XXPFdTdZ)
[isc-dhcp-server](https://pastebin.com/7TTbw2cB)
service isc-dhcp-server start
Meine Geräte verbinden sich erfolgreich mit dem Router und ich habe einen anderen IPv4 DNS-Server.
Die Config sollte nur halt noch angepasst werden, der RPI sollte die IP 192.168.0.2 erhalten und der DNS muss natürlich gleich sein.

Also ja das ist eine Art "Subnetz", aber eins was funktioniert, auch wenn man sich mit dem Router normal verbindet.
