### ISSUE TITLE
False positive: coronacalc.org

### ISSUE THREAD

**Issue by chdh** [RPiList/specials#361]
Coronacalc.org ist eine seriöse Web-App, die ich selber programmiert habe. Sie ist Open-Source: https://github.com/chdh/corona-calc

Wie kommt Coronacalc.org auf eure Liste? Was sind die Kriterien? Sind diese Kriterien irgendwo dokumentiert? Wer überprüft, ob eine Website die Kriterien erfüllt und wo wird das protokolliert und dokumentiert? Gibt es irgendeine Qualitätssicherung?

Eure Block-Liste scheint selber unseriös zu sein.

**Comment by RPiList** [comment]
Hallo,

> Wie kommt Coronacalc.org auf eure Liste? 

Es gibt mehrere Möglichkeiten wie die Domain auf unsere Liste gekommen ist. Wir sind nicht die einzigen, die das Internet nach Fake-Corona-Seiten/Abzockern durchsuchen. Insoweit kann es sein, dass ein Dritt-Crawler die von Ihnen genannte Seite gefunden und aufgenommen hat.

> Was sind die Kriterien? Sind diese Kriterien irgendwo dokumentiert? Wer überprüft, ob eine Website die Kriterien erfüllt und wo wird das protokolliert und dokumentiert? 

Unser Crawler sucht u.a. nach "Corona", "Covid19" und einigen anderen Begriffen in Domain, nicht in der Subdomain.

D.h. die Domain Covid19.rki.de geht durch, weil es nur eine Subdomain ist. die eigentliche Domain hat nichts mit den Suchbegriffen zu tun. Daher ist die eigentliche Domain NICHT zu "Corona-Zwecken" registriert worden.

Dagegen wurde die Domain "copperkillscovid.org" von Abzockern registriert und landet in der Blockliste.

>Gibt es irgendeine Qualitätssicherung?

Nope. Jeden Tag werden mehrere tausend neue Domains zu dem Thema registriert. Diese werden nach o.g. Muster gescannt und dann evtl. aufgenommen. Die Liste umfasst derzeit über 260.000 Domains. Eine manuelle Sichtung ist aus Zeit- und Kostengründen nicht möglich.

Natürlich ist es möglich, dass sog. False-Positives in die Liste aufgenommen werden. Das passiert vor allem in der Phishing-Liste/Malware-Liste. Das hängt u.a. mit der Arbeitsweise des Pi-hole zusammen. Das wird aber billigend in Kauf genommen, da es dem Ziel der Liste bzw. dem Einsatzzweck nicht entgegen steht. Sprich den Nutzern der Liste es ist egal, ob ein False-Positive geblockt wird. Den Nutzern ist es dagegen sehr wichtig, dass unerfahrenen Internet-Nutzer (z.B. Eltern/Kids...) im eigenen LAN nicht auf irgendwelche Abzocker hereinfallen.


> Eure Block-Liste scheint selber unseriös zu sein.

Gut gebrüllt Tiger. 
Dann scheint ja alles geklärt zu sein. Sie blocken dann am besten diese Seite und schon ist die Welt wieder in Ordnung.

**Comment by chdh** [comment]
Also zusammenfassend heisst das: Weil meine Web-App [coronacalc.org](http://coronacalc.org) das Wort "corona" im Domainnamen enthält, wird sie von euch als Fake/Abzocke geblockt, ohne dass dies jemand überprüft. Und diesen False-Positive manuell entfernen macht ihr auch nicht?

**Comment by RPiList** [comment]
> Also zusammenfassend heisst das: Nur weil meine Web-App [coronacalc.org](http://coronacalc.org) das Wort "corona" im Domainnamen enthält, wird sie von euch als Fake/Abzocke geblockt, ohne dass dies jemand überprüft? 

Korrekt. 

Wie bereits erläutert. Jeden Tag werden 1000 Domains mit "Coronoa/Covid & Co" im Domainnamen oder Subdomain angemeldet. Die Erfahrung zeigt, dass 95% dieser Domains als Abzocke benutzt werden.

Dazu kommen hunderte Gambling-Domains, tausende Porn-Domains, Phishing und und und...  Manuelle Prüfung zu Beginn ist nicht möglich. Das ist ein Community-Projekt ohne Einnahmen.

Natürlich verfangen sich auch legitime Seiten im Crawler. Das ist ein akzeptierter Collateral-Schaden. Ist leicht nachvollziehbar, wenn man sich die Nutzer der Listen anschaut. Die Nutzer wollen keine Liste die einen Corona-Abzocker durch lässt. Mit einer Liste die eine Legit-Website blockt, können Sie leben. Hier hat der Nutzer zwei Möglichkeiten. Er meldet uns die Seite und sie wird entfernt. Zweite Möglichkeit er "Whitelistet" die Seite in seinem Pi-hole und damit kann er sie nutzen.

Für den Nutzer ist nur wichtig, dass für Ihn kein Schaden entsteht. Mit der Methode entsteht kein Schaden.

Sie haben die Seite gemeldet und damit wurde die Seite aus der Liste entfernt. Ferner kommt die Domain auf die sog. Whitelist, welche dafür sorgt, dass die Domain nicht ein zweites Mal auf in der Blocklist landet.

> Wie soll der Domainname für eine seriöse Web-App für Corona-Statistik denn sonst gewählt werden?

Es geht nicht darum einen Namen zu wählen, der nicht von unserem Crawler erwischt wird. Es ist wichtig, dass die Domain nach der Listung schnell genug wieder gelöscht wird. Insoweit wählen Sie den Namen, der für Sie und Ihre Nutzer am Besten erscheint.

Unser Crawler geht bei der Erkennung mit ähnlicher Heuristik vor, die auch Antiviren-Programme nutzen. Nur nutzen die natürlich mehrere Faktoren der Erkennung. Wir ziehen nur die Domain ran.

Mal als Beispiel: 
- covid19wikipedia.com wird geblockt.
- covid19.wikipedia.com wird NICHT geblockt. 

Warum? Ganz einfach. Die Zweite Domain existierte schon vor Corona und der Betreiber will nur Infos/Ähnliches auf einer Subdomain anbieten. Die erste Domain will nur bei einer Suche gefunden werden, damit sich Opfer auf ihr verlaufen.

Zweites Beispiel: Robert-Koch-Institut.
Die sind unter rki.de erreichbar. Jetzt kommt Corona und was machen die? Registrieren die corona-rki.de?? Sehr unwahrscheinlich... weswegen die corona.rki.de registriert haben. Aber auch wenn das RKI corona-rki.de registriert hätte, dann wären sie in der Blockliste gelandet. Eben weil Methoden anwenden, die von 100% der Abzocker genutzt werden.

Drittes Beispiel:
Vor wenigen Tagen wurde uns mitgeteilt, dass sich ein Unternehmen namens XXXLutz in der Porn-Liste befindet. Sie werden sicher keine Probleme damit haben, die Buchstabenkombination zu finden, bei denen unser Crawler angeschlagen hat. Wer sich solch einen Namen vergibt, dem muss klar sein, dass er im Porn-Blocker überall auf der Erde landet. Ist deren Aufgabe diese davon zu überzeugen, dass sie dort fälschlich drauf gelandet sind.

Für uns stellt sich hier nur die eine Frage: Was wollen die Eltern, die für Ihre Kids die Pornblock-Listen eingerichtet haben. Ist das für die Kids ein Schaden, wenn die Kids nicht auf das Möbelhaus zugreifen können? Wohl kaum. Overblocking ist denen in dem Fall egal.

False Positives sind ein tägliches Vorkommen und nichts Tragisches. Die Listen werden soweit wie möglich aktuell gehalten und alle sind happy.

> Danke für das manuelle entfernen. Ist das neue [do-not-use](https://github.com/RPiList/specials/blob/master/dev/do-not-use)-File für solche Fälle gedacht (damit die Website nicht wieder von neuem in die Liste kommt)?
> 
Nein, dass ist eine interne Liste für die Entwicklungsabteilung. Quasi zu Testzwecken.

Die "Whitelist" im Dev-Ordner listet die Domains auf, die auch bei Neuerkennung direkt wieder von den Blocklisten gelöscht werden sollen.

**Comment by chdh** [comment]
Danke für die Infos und das Hinzufügen zur Whitelist.
