### ISSUE TITLE
Blacklist Streaming

### ISSUE THREAD

**Issue by pali768** [RPiList/specials#365]
Domains to Blacklist: 

- "vivo.sx" / "www.vivo.sx"

- "jetload.net" / "www.jetload.net"

- "gounlimited.to" / "www.gounlimited.to"

- "streamtape.com" / "www.streamtape.com"

- "mixdrop.co" / "www.mixdrop.co" / "mixdrop.to" / "www.mixdrop.to"

- "voe.sx" / "www.voe.sx"

For this List: Streaming

Source: "bs.to" Streaming Provider Links

**Comment by RPiList** [comment]
Hallo,

vielen Dank für den Hinweis. Domains wurden der Liste hinzugefügt. Viele Grüße
