### ISSUE TITLE
Legitimate pr0n website in malware AdList

### ISSUE THREAD

**Issue by kollege-anonym** [RPiList/specials#368]
`www.pornhub.com` ist wohl versehentlich von der pornblock Liste in die Malware Liste gerutscht.
Malware ist mir dort bei meiner ganzen *Recherche* noch nicht untergekommen.

Grüße von den versauten Kollegen
(Ich wollte dann doch nicht meinen auf Xing verlinkten Github Account  für dieses Issue nutzen, auch wenn es beweist, dass ich mich gerne in Open Source Projekten einbringe) ;)

**Comment by RPiList** [comment]
Es gibt in der Tat derzeit Schadware auf Pornsites. Siehe dazu https://blog.malwarebytes.com/social-engineering/2020/09/malvertising-campaigns-come-back-in-full-swing/

Wir lassen den Eintrag deswegen erst mal dauf. Wird dann aber demnächst wieder entfernt.

Viele Grüße
