### ISSUE TITLE
notion.so

### ISSUE THREAD

**Issue by bermeitinger-b** [RPiList/specials#369]
Vielen Dank für die ganzen Listen!

Ich benutze notion.so als Notizverwaltung, leider ist diese Seite auf der Blockliste für Phishing. Woher habt ihr diese Adresse zum Blockieren?

Könnt ihr die bitte von der Liste entfernen?

**Comment by RPiList** [comment]
Hi,

der Eintrag (der Domain auf der Liste) scheint älter als 30 Tage zu sein und dann können wir nicht mehr genau sagen, welche der Quellen den Eintrag auf die Liste gesetzt hat.

Die Quellen der Liste sind phishing.army, openfish.com und phishstats.info

Viele Grüße
