### ISSUE TITLE
Router Konfiguration Speedport W 921V

### ISSUE THREAD

**Issue by Fabunator** [RPiList/specials#37]
Das Problem bei der Konfiguration eines Telekom Routers ist meines Wissens nach IPv6, dass die Telekom immer ein IPv6 DNS Server bereit stellt. Dieser lässt sich im Menü des Routers nicht ausschalten.
Verbinden sich Geräte mit dem Router wird vermutlich auch IPv6 aktiviert.
Die Geräte greifen dann auf den IPv6 DNS Server der Telekom zu und nicht auf den manuell eingestellten IPv4 DNS Server im PiHole.
Um das PiHole zu nutzen müsste man IPv6 auf allen Geräten deaktivieren. Dann ist aber der Vorteil eines Zentralen Blockers verloren.

**Comment by H4ckZ** [comment]
> Verbinden sich Geräte mit dem Router wird vermutlich auch IPv6 aktiviert.
Lässt sich IPv6 im DHCP vom Router nicht deaktivieren? Dass dieser nur noch IPv4 Adressen verteilt?

**Comment by RPiList** [comment]
Das dürfte von Router zu Router unterschiedlich sein. In der FB läßt sich IPv6 unterbinden.

**Comment by RPiList** [comment]
Problem sollte sich mit der neuesten Version 2001 erledigt haben. Wenn möglich bitte testen. Danke.
