### ISSUE TITLE
fasterloader.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#370]
`fasterloader.com` will angeblich ein "update" des flash players installieren. auf diese Seite wird man manchmal geleitet wenn man `gegenhartz.de` aufruft welches wohl mit einem domain parker system geparkt wurde. Wenn man direkt die fasterloader Seite aufruft wird man zu anderen müll seiten geleitet.
<img width="782" alt="Unbenannt2" src="https://user-images.githubusercontent.com/48647394/94726320-5e11d180-035d-11eb-9b83-b70b09a42b18.PNG">

**Comment by RPiList** [comment]
Hi,

fasterloader.com wird der schadware-Liste hinzugefügt.

Vielen Dank und viele Grüße
