### ISSUE TITLE
icanhazip.com

### ISSUE THREAD

**Issue by bermeitinger-b** [RPiList/specials#371]
Fügt entfernt **icanhazip.com** von der malware-Blockliste. Das einzige was die Seite zurück gibt, ist die IP von der die Anfrage auf die Seite kommt.

Ich kann also damit meine echte öffentliche IP (v4 oder v6) herausfinden. Das geht auch über Proxy oder VPN, sodass ich testen kann ob die Seite tatsächlich darüber aufgerufen wird.

(Außer natürlich, es gibt einen Grund warum die Seite auf der Liste ist.)

**Comment by RPiList** [comment]
Hi,

Domain wurde entfernt. Nach Augenscheinnahme konnte ich da auch nichts tragisches erkennen.

Aber die Domain wurde über "zonefiles" eingespielt und ist immer noch auf deren Schadware-Liste. Beobachte das also weiter.

Viele Grüße
