### ISSUE TITLE
launchpadlibrarian.net

### ISSUE THREAD

**Issue by phil0x2e** [RPiList/specials#373]
Die domain `launchpadlibrarian.net` steht auf der Phishing Liste und auf der Malware Liste.
Darunter findet sich jedoch bloß ein Repository für auf [Launchpad](https://launchpad.net/) gehostete Dateien.
Diese Domain wurde z.B. von meinem Arch System benötigt, um den Source Code eines *aur* Paketes zu ziehen.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Info. Domain wurde entfernt.

**Comment by phil0x2e** [comment]
@RPiList Super, danke.
Die Domain befindet sich jedoch auch auf der Malware Liste, wo sie noch nicht entfernt wurde.

**Comment by RPiList** [comment]
Vielen Dank, ist jetzt gefixt. Grüße.
