### ISSUE TITLE
Kartenluchs eats my soul

### ISSUE THREAD

**Issue by Klebestreifen** [RPiList/specials#375]
In numerous YouTube comments, pages are constantly spammed, which allegedly provide free coupons. Thereby a liable to pay the costs subscription is agreed upon however one does not get a coupon nevertheless.

#### Found URLs
* https://ytmeister.com/
* https://kartenluchs.com/ (Probably the origin of all evil.)

Edit:
like #354 **#327**

**Comment by RPiList** [comment]
Vielen Dank für die Info, Domains wurden der spam.mails Liste hinzugefügt.

Viele Grüße
