### ISSUE TITLE
malware Blocklist contains official Microsoft URLs

### ISSUE THREAD

**Issue by echtvitalkg** [RPiList/specials#379]
Ich weiß nicht, ob das Absicht ist, aber es sind einige Microsoft-Domains in der malware Blocklist drin.

Beispielsweise:
`watson.telemetry.microsoft.com`
`settings-win.data.microsoft.com`

und viele, viele mehr. Ich möchte im Büro die Liste nur dazu einsetzen, um Mitarbeiter*innen es schwerer zu machen, sich auf den Rechnern etwas einzufangen. Synchronisationen blockieren o.Ä. will ich nicht. Telemetrie ist in dem Fall egal.

Absicht oder Fehlerhaft?

**Comment by RPiList** [comment]
Einige unsere Quellen betrachten Tracking-Domains als Schadware/Malware und packen diese mit auf Ihre Listen. Diese werden dann von unserem Crawler mit eingezogen....

Insoweit ist das also Absicht. Die zwei Domains sind mir auch von der Blockliste des Bundesamt für Sicherheit in der Informationstechnologie (BSI) bekannt.

Das Blocken dieser dürfte aber keine Funktionsbeeinträchtigung mit sich bringen.  Ohne diese würde ich die Domains drauf lassen.

Sollte es bei der Nutzung einiger Dienste Probleme geben, könnte ich sie wieder entfernen.

**Comment by echtvitalkg** [comment]
Alles klar, das klingt soweit schlüssig. Einige Mitarbeiter*innen hatten in den letzten Tagen Schwierigkeiten beim Zugriff auf OneDrive und SharePoint. Das würde sich zeitlich mit der Implementierung der Pi-Hole VM decken, **kann aber auch Zufall sein.**

Ich habe die Repo geforkt und *.microsoft.com sowie *.microsoft.com.akadns.net aus der Liste entfernt: https://github.com/echtvitalkg/specials/blob/master/Blocklisten/malware-no-ms

Ich werde mit "meiner" Liste ab Montag mal prüfen, ob die Probleme persistieren oder das es behoben hat.

**Comment by RPiList** [comment]
Wir haben unter https://github.com/RPiList/specials/tree/master/Internet%20Services eine Vielzahl an Dienste-Domains aufgelistet, die freigeschaltet werden können (über die Whitelist-Funktion des Pi), wenn es Aufgrund unserer oder fremder Listen zu Problemen kommt.

**Comment by echtvitalkg** [comment]
Ich habe die Whitelists plus noch ein paar weitere Einträge mal implementiert, damit sollten Probleme nun vermieden werden. Ich werde das noch etwas beobachten, denke aber, dass es damit getan sein sollte.
