### ISSUE TITLE
Anleitung Unbound aktualisieren

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#382]
Die Installationsanleitung für Unbound wurde aktualisiert.
Jetzt müssen die Root-Server nicht mehr per crontab aktualisiert werden.

Zitat: 
`Optional: Download the current root hints file (the list of primary root servers which are serving the domain "." - the root domain). Update it roughly every six months. Note that this file changes infrequently. This is only necessary if you are not installing unbound from a package manager. If you do this optional step, you will need to uncomment the root-hints: configuration line in the suggested config file.`

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

**Comment by bussio** [comment]
Heißt das, dass alles was in "https://github.com/RPiList/specials/commit/849582ff16112f9fad5e6200524721443e4265f3#diff-55876764283fe0c312eea0c70b4d455e06eab27cc39aa2263c81f84904dc0426!" aufgeführt ist, jetzt nicht mehr gilt und die Datei "updateroot" sowie der Eintrag in der Cronjob Datei entfernt werden muß?

**Comment by RPiList** [comment]
Ja und nein.

Das Update, dass in unserer Anleitung 1x alle 6 Monate durchgeführt wird, wird jetzt automatisch mit APT durchgeführt. D.h. wer seinen Pi aktuell hält, brauch unsere Datei nicht.

Wenn Sie unsere Datei und den Cronjob aber schon eingerichtet haben, schadet es auch nicht. Dann updaten Sie trotzdem am 01.01. und am 01.07.
