### ISSUE TITLE
IPFS Download hinzugefügt

### ISSUE THREAD

**Issue by JanisPlayer** [RPiList/specials#383]
Ich weiß nicht ob ihr IPFS noch nutzt, es gibt ja dazu kaum noch Updates von euch.
Ich habe die neusten Versionen zu IPFS hinzugefügt.
Wenn ihr es auch zu IPFS hochladet und hier verlinkt in einer Update-Datei, dann kann ich es auch bei mir im Server automatisch anpinnen lassen(, auch wenn das noch experimentell ist).
Also falls ihr noch an IPFS interessiert seid, hier die Links:

svpihole2010.zip:
https://ipfs.io/ipfs/QmUKAPG1MNwoJ79kXbZrLRSNtPZkivS9hFg86tgREgoW53?filename=svpihole2010.zip
https://heldendesbildschirms.dynv6.net/download/software/betriebssysteme/svpihole2010/

svpihole2008.zip:
https://ipfs.io/ipfs/Qman5EqMB2kFWQdGNGwjH3cghXDQfEG5nkKqpfnELfcSZQ?filename=svpihole2008.zip
https://heldendesbildschirms.dynv6.net/download/software/betriebssysteme/svpihole2008/

svPiholeVM2008.zip:
https://ipfs.io/ipfs/QmSsRcmma1bbcPKNvqwu8E4iW6S4uJwDtzM8X4y3W2tD54?filename=svPiholeVM2008.zip
https://heldendesbildschirms.dynv6.net/download/software/betriebssysteme/svPiholeVM2008/

Ich habe auch euere Dateien auf meinem Download Server hinzugefügt.
Ich hoffe das ist für euch in Ordnung, wenn nicht dann bitte einfach anschreiben, dann lösche ich die Vorlage und die Seite.

Für die Nutzer:
Die Echtheit der Dateien sollte man natürlich immer prüfen mit dem Hash, weil 51% Attacken ja nicht ausgeschlossen werden können, auch wenn sie unwahrscheinlich sind.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Links wurden hinzugefügt.
