### ISSUE TITLE
static.parastorage.com

### ISSUE THREAD

**Issue by phil0x2e** [RPiList/specials#391]
Die Domain `static.parastorage.com` befindet sich auf der malware Liste.
Diese wird jedoch scheinbar von Seiten gebraucht, die mit Wix erstellt wurden.
[Deviantart](https://www.deviantart.com) beispielsweise funktioniert ohne diese Domain überhaupt nicht.
LG

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

Ist jetzt gefixt. Viele Grüße
