### ISSUE TITLE
Remove norma24.de

### ISSUE THREAD

**Issue by DiamantTh** [RPiList/specials#396]
Ich denke mal das Norma genug Seriös ist, auch eine verlinkung von norma-online.de führ zu norma24.de
Inklusive natürlich der www. Subdomain
Gefunden in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
MfG

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Info. Die Domain wurde aus der Liste entfernt. Vielen Dank für die Mühen und viele Grüße.
