### ISSUE TITLE
Nachrichtenseiten in der Blockliste

### ISSUE THREAD

**Issue by nowakommunikation** [RPiList/specials#397]
Gibt es einen Grund, weshalb z. B. cbsnews.com in der Blockliste ist?

Is there a reason why cbsnews.com is in the blocklist?

**Comment by RPiList** [comment]
Hi,

ist jetzt gefixt. Die Easylist wird von uns nur "übernommen", insoweit kann ich nicht sagen, warum die Domain dort gelistet ist.

Viele Grüße und Dank für die Info.

**Comment by pali768** [comment]
Hier weiter Domains:

- abcnews.go.com - Affected list: p0rnblock1
- msnbc.com / www.msnbc.com - Affected List: child-protection

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

Die Domains wurden aus den Listen entfernt. Viele Grüße
