### ISSUE TITLE
Freiewelt.net von der Liste nehmen 

### ISSUE THREAD

**Issue by Naimkr27** [RPiList/specials#406]
Könnt ihr bitte die Freiewelt.net und andere Alternative Medien von der Liste streichen, oder dafür eine eigene Liste erstellen. Danke

**Comment by RPiList** [comment]
Hi,

freiewelt.net wurde von phishing.army als Feindlich gemeldet und verbleibt somit bis auf Weiteres auf der Phishing-Liste. Zu den anderen Alternativen Medien kann ich nichts sagen, weil ich hier nicht weiß, welche Domains das sein sollen und auf welchen Listen sie vertreten sind.
