### ISSUE TITLE
Probably wrong domain on maleware List.

### ISSUE THREAD

**Issue by sburgh01** [RPiList/specials#414]
Hi, 
The maleware blocklist is blocking some seriouse Domains and Subdomains from the American Football leage NFL.
e.g. needed for the Iphone and Android Apps.
> api.nfl.com

Is there a reason for this perticular Block?
Geetings

**Comment by RPiList** [comment]
Hi,

thankx for letting us know. Domain has been removed.

Our malware list is a product of multiple online services (like Zonefiles.io, Malware-Domains, Cybercrime-Tracker...). Which one of these services lists this domain, I am not sure. 

Greetings.
