### ISSUE TITLE
Unable to access iHeartRadio

### ISSUE THREAD

**Issue by princepjamie06832** [RPiList/specials#415]
Hi,

I cannot open iHeartRadio (iheart.com). Can you please remove 'iheart.com' including subdomain from 'Easylist' so I can listen radio. This site is clean.

**Comment by BulldozerPete** [comment]
check PR #416

**Comment by RPiList** [comment]
Thx for letting us know. Domain iheart.com and www.iheart.com were removed.

Greetings

**Comment by princepjamie06832** [comment]
Perfect! This domain and subdomain is not on this blocklist anymore. Thank you so much.
