### ISSUE TITLE
Amazon Seller Central zu Unrecht geblockt

### ISSUE THREAD

**Issue by Deutschi** [RPiList/specials#418]
Die deutsche Seite der Amazon Seller Central, sellercentral.amazon.de, steht auf der Liste der Phishing Angriffe, obwohl sie legitim ist. Wir nutzen diese schon seit Jahren und waren überrascht, als sie nach der Einführung des Pi-Hole plötzlich nicht mehr ging.

**Comment by RPiList** [comment]
Vielen Dank für die Info.

Domain wurde entfernt.

Viele Grüße
