### ISSUE TITLE
dx.doi.org is blocked

### ISSUE THREAD

**Issue by Deusjovult** [RPiList/specials#423]
Hi,

die Domain dx.doi.org ist fälschlicherweise auf der Blocklist fake-science.
Hierbei handelt es sich um den DOI-Resolver der IDF (https://dx.doi.org/ oder https://doi.org/)
siehe: https://de.wikipedia.org/wiki/Digital_Object_Identifier

Er wird nicht nur für fake, sondern für jede Art von Science benötigt. ;-)

Danke und VG

**Comment by RPiList** [comment]
Ist gefixt, Domain wurde entfernt. Vielen Dank für die Info. Grüße

**Comment by bermeitinger-b** [comment]
Es ist wieder auf der Liste gelandet.

**Comment by RPiList** [comment]
und wieder entfernt.

die dx. Subdomain wurde damals nicht in Whitelist aufgenommen. Jetzt steht sie auch drin.
