### ISSUE TITLE
Website der EU

### ISSUE THREAD

**Issue by bautim** [RPiList/specials#424]
Hallo,

mehrere Seiten der Europäischen Union werden geblockt.

notserious:
- ec.europa.eu (Europäische Kommission)
- webgate.ec.europa.eu

child-protection:
- consultations.berec.europa.eu 

Corona-Blocklist:
- covid-statistics.jrc.ec.europa.eu

malware:
- consultations.berec.europa.eu

Alle Domains unter der Second-Level-Domain "europa.eu" gehören zur Europäischen Union (siehe SSL-Zertifikate).

Viele Grüße

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis und den Hinweis mit der Second-Level-Domain "europa.eu". Habe diese jetzt in einen internen Filter aufgenommen, dass diese Domains künftig nicht mehr auf der Liste landen, selbst wenn die Domain nicht auf der Whitelist steht.

Viele Grüße.
