### ISSUE TITLE
Liste für Web-Proxies?

### ISSUE THREAD

**Issue by jens1205** [RPiList/specials#427]
Hallo zusammen,

ich möchte pihole gerne als Jugendschutz-Filter verwenden. Dazu gibts ja auch hier wunderbar viele Listen, die den größten Schmutz wegfiltern. Ich habe pihole auch so konfiguriert, dass man bei google, bing etc. immer auf die safesearch Variante geleitet wird.

Das ganze lässt sich im Moment aber (viel zu) kinderleicht umgehen. Einfach in google (auch in Safesearch möglich) nach "free web proxy" googlen, z.b. den ersten Treffer nehmen (https://www.proxysite.com/) und dann dort zur Schmuddelseite meiner Wahl surfen.

Ich habe bisher keine Liste für den pihole gefunden, die solche Proxyseiten umfasst. Hat da jemand einen Tipp? Sollte sowas hier nicht auch aufgenommen werden?

VG
Jens

**Comment by AleksCee** [comment]
Eine richtigen zuverlässigen Schutz für Leute due das umgehen wollen, wirst du mit einem DNS auch nie hinbekommen. 
Der Gedanke von Pi-hole ist mehr Leute zu schützen, die sich beschützen lassen wollen. Für Leute die das umgehen wollen musst du etwas wie einen transparenten Proxy wo du schön akribisch alles pflegst und ohne den es nicht ins Internet geht, oder eine sperrliste auf dem Router wie z.b. https://avm.de/service/fritzbox/fritzbox-7590/wissensdatenbank/publication/show/3395_Filterlisten-fur-Internetseiten-erstellen/ oder mit den betreffenden Leuten ein Gespräch führen. Man erklärt denen ja auch, dass sie nicht bei rot über die Straße gehen sollen. Denn außerhalb deines Netzes kannst du eh nicht verhindern was sie sich ansehen, z.b. am Handy oder bei Freunden.

Liebe Grüße, Alex

**Comment by jens1205** [comment]
Mir ist schon klar dass es immer Möglichkeiten gibt, alles zu umgehen. Trotzdem kann man es ja möglichst schwer machen. Im Supermarkt soll ja auch kein Alkohol an Jugendliche abgegeben werden - und natürlich kommt man als Jugendlicher trotzdem dran wenn man will. 

Wenn die Kinder schlau genug sind die aufgestellten Hürden zu umgehen, dann sind sie hoffentlich auch alt genug damit umzugehen was sie dann da so finden... Die ganze Zeit bei der Internetnutzung dabei zu sein ist total unrealistisch und lebensfremd.

Und natürlich wollte ich es nicht zu meinem Lebenswerk machen, alles manuell nachzupflegen. Mich haben bisher bloß keine der anderen Jugendschutzmaßnahmen überzeugt. Am meisten hat mich noch JusProg enttäuscht - das Windows-Programm ist dauernd abgestürzt, der DNS-Server ist instabil und liefert manchmal keine Antworten für Domains wie rewe.de oder lichess.org. Die Android-App hat in Zeiten von HomeSchooling den Zugriff auf Microsoft Teams abgewürgt.

**Comment by AleksCee** [comment]
Aber der pihole ist echt für 10 jährige zu umgehen. Siehe die Stoppschild Diskussion vor ein paar Jahren dank Frau von der Leyen https://www.pro-medienmagazin.de/politik/2009/06/25/von-der-leyen-verteidigt-internet-stoppschild/ . Selbst die Kindersicherung der firtzbox wird bei YouTube von einem 8 jährigen erklärt wie man die aushebet.... ;)

**Comment by jens1205** [comment]
Ich gebe zu ich bin verwirrt. In diesem github Projekt werden Listen für den Jugendschutz angeboten. Aber du erklärst mir, dass deiner Meinung nach schon 8 Jährige den Pihole umgehen können. Ich bin ja bei dir was die Web Proxies angeht total bei dir - deswegen hatte ich ja auch das Ticket aufgemacht. Ich habe auch mal normale HTTP / HTTPS / SOCKS-Proxy die angeblich frei im Internet zugänglich sind, ausprobiert - interessanterweise hatte ich da keinen brauchbaren gefunden (ich zweifele schon an mir selbst, wieso das nicht funktioniert...)

Ich bin mir auch noch nicht sicher, ob Pi-Hole jetzt die beste aller schlechten Möglichkeiten ist, oder ich doch noch auf andere Lösungen wie squid / squidgard umschwenke. Aber auch dort braucht es m.E. irgendwelche Blacklists.... Und nein, ich will nicht anfangen nur Whitelists zuzulassen, ich habe noch ein Leben nebenher :-)

**Comment by AleksCee** [comment]
Naja, wie gesagt. Ein PiHole ist für Leute die sich schützen lassen wollen. Du kannst auch hinter einem Pi-hole einen externen DNS eintragen und umgehst damit die „Sperre“. Oder du nutzt vpn, oder proxies... wenn du das nicht willst musst du im Router sperren dass keiner DNS Anfragen am Pi-hole vorbei ausführen kann. Das würde aber auch ein VPN Tunnel nicht verhindern.
Der pihole ist ein Werbeblocker für dad Netz für Leute die bewusst und einvernehmlich bestimmte Seiten nicht aufrufen wollen. Als wirksamer Schutz als „Verbot“ ist es nicht geeignet. Selbst wenn ein Webebanner sicher direkt via IP nachladen würde, also keinen DNS benötigt, sperrst du das damit auch nicht. Dazu braucht man wirklich schon einen echten Filter - was der Pihole nicht ist. Er antwortet bei ungewünschten „Telefonbuch-Einträgen“ einfach nur mit der flachen Nummer hinter der kein Anschluss ist, wenn ich mir die Nummer aber auf anderem Wege beschaffe, kann ich da auch wieder „Anrufen“.

**Comment by RPiList** [comment]
Eine Liste für Proxies zu erstellen sollte kein Problem sein. 

Es wird klar kommuniziert, dass die Liste nur als Ergänzung für die Porn-Liste gedacht ist, um eine all zu einfache Umgehung zu erschweren.

**Comment by jens1205** [comment]
@AleksCee : Wie gesagt, ich weiß dass es keinen 100%igen Schutz gibt - gibts wahrscheinlich auch in China mit der Great Firewall nicht, und die haben einfach mehr Manpower als ein einfacher Familienvater :-) Tatsächlich habeng ich in meiner Fritzbox für alle außer dem Pi-Hole den DNS-Port nach außen abgeklemmt. Web-Zugriffe auf IP-Adressen sind auch nicht erlaubt - aber ich zweifele an der Umsetzug, ich habe die Vermutung dass die Fritzbox da eine komische Useragent Erkennung macht. Mit curl bekomme ich bei Angabe einer IP jedenfalls keine Fritzbox-Fehlerseite zu sehen, im Browser schon...

@RPiList : Fände ich im Sinne von "wer A sagt muss auch B sagen" gut :+1:

**Comment by RPiList** [comment]
Liste ist online.
