### ISSUE TITLE
web.vortex.data.microsoft.com für Microsoft Family benötigt

### ISSUE THREAD

**Issue by jens1205** [RPiList/specials#428]
Ich musste gerade web.vortex.data.microsoft.com auf die Whitelist setzen, damit die Microsoft Family App funktioniert (um die zeitlichen Limits zu bearbeiten). Ich habe keine Ahnung aus welchen (guten?) Gründen die Domain auf verschiedenen Listen ist:
```
Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   web.vortex.data.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4:
   web.vortex.data.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
   web.vortex.data.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   web.vortex.data.microsoft.com
```
Ich vermute eigentlich eher, dass der Grund für das blacklisten der Domain eher Privacy-Aspekte eine Rolle spielen als Jugendschutz / Porno? Sollte die Domain nicht zumindest aus diesen LIsten entfernt werden?

**Comment by RPiList** [comment]
Hi,

ich weiß jetzt nicht welche Art von Content auf der URL angeboten wird, aber wenn das Nutzer-generierter Content angezeigt werden kann, ist das Anbieten von Schadware unter der Domain (inkl. Unterverzeichnisse) durchaus möglich (gewesen).

Ich gehe auch davon aus, dass es so gewesen ist, weil der Eintrag sich in mehreren Listen befindet, die alle unterschiedlich gefüttert werden.

Ein Löschen des Eintrags in unseren Listen reicht aber nicht aus, da auch Steven den Eintrag in seiner Liste hat.

In Ihrem Fall hilft da also nur "whitelisten", oder Steven auch ansprechen. :-)

Viele Grüße

**Comment by RPiList** [comment]
Domain habe ich jetzt "einmalig" aus unseren Listen gelöscht.
Aber nicht auf die Whitelist gesetzt. Wenn die Domain durch Dritte wieder eingespült wird, scheint es da wirklich ein Problem zu geben.

Ferner habe ich die Domain in die Microsoft Internet Services Liste aufgenommen.

Viele Grüße

**Comment by jens1205** [comment]
Danke, ich habe die Domain bei mir auch auf die Whitelist gesetzt.
