### ISSUE TITLE
Pi-hole Umgehung durch DNS over HTTPS

### ISSUE THREAD

**Issue by pali768** [RPiList/specials#432]
Wie bei diesem Issue #427 beschrieben, lässt sich Pi-hole ganz leicht umgehen. Eine weiter möglich ist das Protokoll „DNS over HTTPS“ (DoH) zu verwenden. Anders als das Protokoll „DNS over TLS“ (DoT) mit dem Port 853, lässt sich DoH nicht in der Fritz.box blockieren, weil es den Port 443 benutzt, welcher auch für andere Zwecke benötigt wird. Das Protokoll lässt sich auch ganz einfach über den Browser einschalten, wie hier gezeigt: https://www.youtube.com/watch?v=3EuP1fZ3GMc. Man bräuchte aus diesen Gründen wie bei den Proxies eine Liste von DoH Servern, um das Umgehen zu verhindern.

**Comment by RPiList** [comment]
Ich glaube das ist noch mal eine ganze andere Dimension. Issue #427 beschreibt ja nicht das Umgehen des Pi-hole sondern nur der Pornblock-Liste.

Aber die Gefahr, das jede Ranz-App auf dem Handy DoH benutzt um Werbung durchzuschleifen ist real. Ich befürchte nur, dass dann jede App seinen eigenen DoH-Server nutzt

Wenn es aber irgendwo ne Liste gibt, können wir die hier gerne Pflegen. Wie sich das Thema dann mit der Zeit entwickelt, werden wir sehen.

**Comment by jens1205** [comment]
Ich glaube die Liste täte wirklich not - habe gerade gelernt dass Firefox schon DNS over HTTPS unterstützung eingebaut hat und man mit einem Klick zwischen Cloudflare oder NextDNS aussuchen kann (und man kann natürlich auch noch benutzerdefinierte DNS Server eintragen).
