### ISSUE TITLE
Listen von Drittanbietern

### ISSUE THREAD

**Issue by bussio** [RPiList/specials#433]
Moin, 
der Link der Justdomains-Liste geht ins Leere (https://mirror1.malwaredomains.com/files/justdomains).

**Comment by pali768** [comment]
Die Liste wird nicht mehr betrieben.

Laut den betreibern: 

"As of November 30th, 2020, both AutoShun and Malware Domains feeds will be shut off, and subscribers will no longer receive intel from those sources. 
We will continue to make a free, non-commercial version of our threat intel, ShadowNet, while the enhanced full-threat intel feed will be licensed to our commercial partners."

Source: https://riskanalytics.com/community/

**Comment by RPiList** [comment]
URL wurde aus unserer Blocklistenübersicht entfernt. Vielen Dank für die Info.
