### ISSUE TITLE
XXXLutz noch immer in der Blocklist

### ISSUE THREAD

**Issue by IT-VBFK** [RPiList/specials#436]
Wie auch in #398 
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/49762557/103367649-eec78d00-4ac5-11eb-85b9-ceb63179cd68.png">

**Comment by RPiList** [comment]
Hallo,

vielen Dank für den Hinweis. Nachgestellte Leerzeichen in der Whitelist haben dafür gesorgt, dass der Parser die Einträge nicht gefunden hat und sie deswegen auch nicht gelöscht. Der Teil ist gefixt.

Allerdings erstellt XXXLutz aber auch Subdomains, als wenn die Jungs auf Drogen wären.

ijzmpz.xxxlutz.de
iztptg.xxxlutz.de
jtsp.xxxlutz.de
jts.xxxlutz.de

sind nur einige Domains, die noch gar nicht auf der Whitelist vertreten waren.

Viele Grüße

**Comment by IT-VBFK** [comment]
Wow, das ging ja fix 👍 

Herzlichen Dank

**Comment by RPiList** [comment]
Damit die Änderung gültig wird, müssen Sie Ihre Listen auf dem Pi-hole aber noch aktualisieren. Viele Grüße und einen guten Rutsch.

**Comment by IT-VBFK** [comment]
Schon erledigt, funktioniert!

Danke gleichfalls
