### ISSUE TITLE
Raspberry Pi zero 

### ISSUE THREAD

**Issue by Yocker95k** [RPiList/specials#44]
Angenommen jemand war zu blöd um auf die Benötigte Hardware.md zu klicken und sie zu lesen und dieser jemand hat _**zwei Raspberry Pi Zero W**_ gekauft. Kann man die auch als Pi hole betreiben ? Bzw was sind die Hardwareanforderungen von Pi hole ?

Frage für einen Freund :sweat_smile:

**Comment by joestr** [comment]
Hi,

Sollte eigentlich auf reibunglos auf RPi Zero/Zero W klappen. Laut https://discourse.pi-hole.net/t/hardware-software-requirements/273 sind die Hardwareanforderungen erfüllt.

**Comment by H4ckZ** [comment]
> 
> 
> Hi,
> 
> Sollte eigentlich auch reibunglos auf RPi Zero/Zero W klappen. Laut https://discourse.pi-hole.net/t/hardware-software-requirements/273 sind die Hardwareanforderungen erfüllt.

Seh ich auch so, sollte problemlos laufen.
Wenn dus nicht allzu eilig hast kann ichs dir am Wochenende aber mal testen, hab nen Zero rumliegen.

**Comment by Yocker95k** [comment]
Danke für die schnellen Antworten 👍 
@H4ckZ meine sind schon geliefert worden. Ich werde es dann einfach selbst testen. Danke für die Hilfsbereitschaft.

Wünsch euch frohe Weihnachten
