### ISSUE TITLE
ytkode.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#444]
`ytkode.com` ist eine fake seite wie die anderen Seiten die ich bisher gemeldet habe.

**Comment by BulldozerPete** [comment]
Ich habe einen PR erstellt: #445 

@RPiList Ich habe die "Betrugsseite" in die Blocklist "Spam Mails" aufgenommen. Die anderen Listen pflegst Du doch automatisiert und bevor da die o.g. URL verloren geht, haben ich die in die manuelle Liste aufgenommen.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde unseren Listen hinzugefügt. Viele Grüße
