### ISSUE TITLE
New Blacklist Domains

### ISSUE THREAD

**Issue by pali768** [RPiList/specials#447]
Blacklist for:

p0rnblock:

- erotischesexgeschichten.club / www.erotischesexgeschichten.club

- nursexfilme.com / www.nursexfilme.com / static.nursexfilme.com / images1.nursexfilme.com / images2.nursexfilme.com / poster.nursexfilme.com

- amorelie.de / www.amorelie.de / magazin.amorelie.de

- index-markets.club / www.index-markets.club

Easylist:

- pcon.space / www.pcon.space / delivery.pcon.space / deliver-adn.pcon.space

- whippedfreezerbegun.com / www.whippedfreezerbegun.com

- feministascertained.com / www.feministascertained.com

- inflationbreedinghoax.com / www.inflationbreedinghoax.com

- plannerladyreality.com / www.plannerladyreality.com

- edgyconnaterag.com / www.edgyconnaterag.com

- tightsaturdayi.com / www.tightsaturdayi.com

- arminius.io / www.arminius.io / go.arminius.io

- rookmemorizevoluntary.com / www.rookmemorizevoluntary.com

- xu2.com / www.xu2.com

- faithfulfacultativeladder.com / www.faithfulfacultativeladder.com

- tilltucked.com / www.tilltucked.com

- nationsflushedoccasionally.com / www.nationsflushedoccasionally.com

- splittingpick.com / www.splittingpick.com

- dividedscientific.com / www.dividedscientific.com

- galacticmenueasier.com / www.galacticmenueasier.com

- franticallyseptember.com / www.franticallyseptember.com

- flashpvideo.com / www.flashpvideo.com

- districtbaloneywhiskers.com / www.districtbaloneywhiskers.com

- knockoutwithdrawal.com / www.knockoutwithdrawal.com

**Comment by RPiList** [comment]
Vielen Dank für die Info, die Domains wurden den genannten Listen hinzugefügt. Viele Grüße.
