### ISSUE TITLE
c.paypal.com on malware list

### ISSUE THREAD

**Issue by phil0x2e** [RPiList/specials#449]
Hallo, ich habe mal wieder ein false positive auf  der malware Liste gefunden.
Undzwar befindet sich die Domain `c.paypal.com` auf der Malware Liste.
Diese Domain wird jedoch beispielsweise benötigt, wenn man bei Patreon etwas mit Paypal bezahlen möchte.
LG

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist jetzt gefixt.
