### ISSUE TITLE
Domain covid-19-mobility.org should not be on corona block-list

### ISSUE THREAD

**Issue by jwesemann** [RPiList/specials#450]
While reading an [article ](https://www.spiegel.de/wissenschaft/medizin/corona-warum-sachsen-besonders-betroffen-ist-und-welche-neuen-hotspots-sich-ankuendigen-a-2a1bcdc9-a6a4-44b3-adf7-c65ed33a4741?utm_source=pocket-newtab-global-de-DE )in Spiegel.de I got a link to mobility data analysis  from domain "covid-19-mobility.org". This seems to be a well known address and shows as contact 

Computational Epidemiology Group

Prof. Dirk Brockmann
Robert Koch-Institute
Nordufer 20
D-13353 Berlin

I think it is safe to remove it from blocking linst

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.
