### ISSUE TITLE
Overblocking: Covid Dunkelzifferradar

### ISSUE THREAD

**Issue by HorayNarea** [RPiList/specials#453]
Heyho,
die Corona Blocklist beinhaltet die Domain

covid19.dunkelzifferradar.de

sowie mehrere Subdomains

dabei handelt es sich nicht um komische Verschwörer und Fakenews sondern Leute die versuchen die Dunkelziffer zu schätzen, bitte whitelisten …dankeschön und viele Grüße! :D

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Mühen und die Domains. Alle Domains wurden aus der entsprechenden Liste entfernt. Viele Grüße
