### ISSUE TITLE
bag-coronavirus.ch überblockiert

### ISSUE THREAD

**Issue by bermeitinger-b** [RPiList/specials#454]
Die Domain `bag-coronavirus.ch` ist auf der Corona-Blockliste. Die Seite ist eine offizielle Seite des Schweizers Bundesamts für Gesundheit und sollte demnach nicht blockiert werden.

**Comment by BulldozerPete** [comment]
#455 PR für whitelist erstellt.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
