### ISSUE TITLE
Serious Domain on Blocklist

### ISSUE THREAD

**Issue by Klami** [RPiList/specials#456]
Die Domain www.dpd.com ist in der Phishing Blocklist enthalten gehört aber zum Verbandsdienstleister DPD

**Comment by RPiList** [comment]
Hi,

die Domain landete über Phish-Stats auf der Liste, was bedeutet, dass dort eine XSS-Lücke in der Website vorlag/vorliegt. 

Hoffen wir mal dass DPD die Lücke gefixt hat.

Viele Grüße
