### ISSUE TITLE
Fake Website: http://www.firefox.de/

### ISSUE THREAD

**Issue by ovz93br43v7** [RPiList/specials#457]
Vielleicht ergänzen als Fake-Website: http://www.firefox.de/

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info.

Blocken dürfte aber nicht notwendig sein, da die Website nicht vorgibt "der Firefox" zu sein.

![image](https://user-images.githubusercontent.com/56664851/106469599-c7d2f100-649f-11eb-8e22-9d555c0cb874.png)

In der oberen Zeile wird klar gesagt, dass man nicht die Website für den Browser ist. Einzig das große grüne Download-Button ist tricky. Der verweist auf Foxload.com, welche aber schon über die Malware-Liste geblockt ist.

Viele Grüße

**Comment by ovz93br43v7** [comment]
Schon allein für den Downloadbutton in Kombination mit der irreführenden Domain sollte sie trotzdem gesperrt sein.
