### ISSUE TITLE
lm.licenses.adobe.com

### ISSUE THREAD

**Issue by Deutschi** [RPiList/specials#459]
Bei uns im Unternehmen hat Adobe Cloud rumgemeckert, dass es die Adobe Lizenz nicht mehr überprüfen kann. Das liegt vermutlich am Block von "lm.licenses.adobe.com" in der Crypto Liste. Da sind auch insgesamt 20 Subdomains von adobe.com drin. Hier frag ich mich auch ob das auf der Liste überhaupt legit ist.

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Ist jetzt in allen Listen außer der Malware-Liste entfernt worden.

Weil in den Malware-Listen ist auch Tracking drin und das ist bei den Domains durchaus möglich. Dass würde ich erst entfernen wollen, wenn gesichert ist, dass das Blocking noch Probleme verursacht.

Vielen Dank für die Mühen.

Viele Grüße
