### ISSUE TITLE
naspise.com

### ISSUE THREAD

**Issue by StevenSeifried** [RPiList/specials#461]
`naspise.com` ist ein Ad-Server über welchen dieselben Seiten wie die im Video "[Bitcoin Abzocke](https://youtu.be/64C30gpzBvU)" gezeigten verteilt werden.

**Comment by H4ckZ** [comment]
PR ist erstellt.

**Comment by StevenSeifried** [comment]
Danke dir. War unschlüssig auf welcher Liste die Domain am besten passt, sonst hätte ich selbst einen PR erstellt

**Comment by RPiList** [comment]
Hatte es auch schon - weil nicht genau wusste wohin - auf die Spam-Liste gesetzt. Hatte auch per eMail darauf geantwortet, aber seltsamerweise ist die Antwort hier nicht gelandet. Grüße
