### ISSUE TITLE
corona-ausschuss.de aus Blocklisten entfernen

### ISSUE THREAD

**Issue by DConan123** [RPiList/specials#464]
Kann mir jemand sachliche Argumente liefern, warum die Domain und Subs von "corona-ausschuss.de" geblockt werden sollen, vor allem in der "child-protection"?
- https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection
- https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist

Beste Grüße
DConan123

**Comment by RPiList** [comment]
Die Domain wurde von verschiedenen Quellen als Fake-News eingestuft. Denke dass ist dann auch der Grund warum die Domain in der Liste "Jugendschutz" gelandet ist.

Normalerweise findet man in der Corona-Liste nur die üblichen Abzocker.

Viele Grüße
