### ISSUE TITLE
duckdns.org

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#466]
Habe die bestehenden Blocklisten mal nach "duckdns.org" durchsucht.
Anscheinend wird diese URL häufig für scam, etc. verwendet.

Wäre es daher nicht besser, diese in die Regel-Liste aufzunehmen, falls es keine vertrauenswürdigen Angebote bei "duckdns.org" gibt?

**Comment by BulldozerPete** [comment]
Siehe z.B. https://www.polizei-praevention.de/aktuelles/sms-mit-paketbenachrichtigungslink-verursacht-massenhafte-sms.html

**Comment by BulldozerPete** [comment]
Habe den einen PR erstellt, falls die Idee auf Zustimmung trifft.
#470

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Ursprünglich wahr ich eher dagegen, weil es ein wenig die das Blockieren der Proxy-Dienste ist.
Aber wenn es da gerade eine Abzock-Aktion gefahren wird, müsste duckdns.org da auch mal reagieren und die Schwarzen-Schafe kicken.

Deswegen hab ich das doch importiert und werde beim Entwickler noch mal Werbung dafür machen, dass er das Feature von "abonnierten RegEx" einbauen soll. Denn da die RegEx-Einträge von Hand erstellt werden müssen, wird das kaum einer machen.

**Comment by BulldozerPete** [comment]
@RPiList Hast Du einen link, wo das Abonnieren von regex diskutiert wird?

**Comment by RPiList** [comment]
https://discourse.pi-hole.net/t/add-feature-to-import-publicly-maintained-regex-lists/27161
