### ISSUE TITLE
excryptobit.com

### ISSUE THREAD

**Issue by YusufBilgin** [RPiList/specials#471]
Über discord habe ich so eine Nachricht erhalten. 

> 
> The ExCryptoBit GIVEAWAY
> 
> Congratulations!!!!
> 
> You became a random winner in our giveaway
> In order to help in this easy time, our company decided to make a huge raffle of funds. ExCryptoBit  -  Professional digital asset trading platform and our partners decided to make a mass draw and give cryptocurrency from 0.001 to 0.9 BTC to random users
> 
>  You WON 0.55 BTC (27132$)
>   Your promocode: CYT7U9LOUB1H 
> 
> How to start using the site?
> Register an account on the site. https://excryptobit .com/
> Go on Page "Profile".
> Activate promotional code
> Receive BTC on your account. 
> Verify your account. (You have 2 days for it)
> Withdraw your funds.
> Go to the "Wallet/Balance" tab and click "Withdraw", enter the address of your external cryptocurrency wallet BTC (or other coin) and the amount.
> 
> Where you can withdraw crypto? Blockchain.com / exodus.io / trust wallet.
> 
> Where you can buy crypto: localbitcoins.net / paybis.com / bitcoin.org/en/buy / moonpay.com
> 
> If you have any questions, contact us in online support
> 
> ONLY 18+
> 
>  IF YOU DONT KNOW WHAT IS CRYPTO AND HOW TO USE IT (PLEASE IGNORE THIS MESSAGE
> 
>  2021 The ExCryptoBit crypto exchange platform.  All rights reserved
> 
> Nachricht an @Clear

Ich denke (bin mir aber nicht ganz sicher weil ich die url nicht besucht habe) dass diese url eine abzocker Domain ist.  `excryptobit.com`

**Comment by RPiList** [comment]
Wurde hinzugefügt. Vielen Dank für die Mühen. Viele Grüße
