### ISSUE TITLE
Please whitelist/remove "plausible.io"

### ISSUE THREAD

**Issue by irgendwr** [RPiList/specials#473]
`plausible.io` und `www.plausible.io` sind in der malware und pornblock3 Blockliste enthalten.
Bei [plausible](https://github.com/plausible/analytics) handelt es sich jedoch um eine nicht schädliche, datensparsame open-source analytics Plattform. Pornografisch ist die Seite höchstens weil die Software geil ist ;p

**Comment by RPiList** [comment]
Hi,

viele Seiten im Internet, die als Quelle für unsere Listen herangezogen werden, interpretieren Analytics als Tracking und damit als Malware.

D.h. selbst wenn wir das aus den Listen entfernen ist es beim nächsten Update wahrscheinlich wieder drin. Es würde nur funktionieren, wenn man es in die Whitelist aufnimmt.

Ich bin mir nicht sicher, ob Tracking mit Malware gleichzusetzen ist, aber imho ist Analytics mit Tracking gleichzusetzen. Oder ist es unbestritten das die Seite zur "guten" Seite gehört? Weil ich selbst kenne die Seite nicht. 

Bräuchte da noch eine zweite Meinung.

**Comment by irgendwr** [comment]
Also Porn ist es zumindest nicht :smile: 

> Ich bin mir nicht sicher, ob Tracking mit Malware gleichzusetzen ist

Tracking und Malware sind für mich sehr verschiedene Dinge. Ich konnte auf Anhieb keine Definition finden, die Analytics beinhalten würde. Selbst die Beschreibung dieser repo ("Malware: Domains die Schadware verbreiten") trifft nicht auf den Dienst zu.

> aber imho ist Analytics mit Tracking gleichzusetzen

Auch wenn es sich bei Analytics in den meisten Fällen um Tracking handelt, würde ich die Begriffe nicht gleichsetzen.
"Tracking" ist für mich, wenn Daten über den Benutzer gesammelt werden. Tracking der am häufigsten aufgerufenen Seiten ist für mich etwas anderes.

> Oder ist es unbestritten das die Seite zur "guten" Seite gehört?

Plausible Analytics sind imo kein Tracking, da keine personenbezogene Daten (auch nicht die IP-Adresse) gespeichert werden. Es werden keine Cookies gesetzt und es wird auch nicht cross-site getrackt. Die Seite bzw. Software dient primär der Traffic Analyse, ohne dabei Benutzerprofile zu erstellen und ist ähnlich wie die Analyse von Webserver-Logs (mit dem Vorteil, dass die IP-Adresse nicht gespeichert wird). Details können [hier](https://plausible.io/data-policy) nachgelesen werden.

---

Interessanterweise ist `googleanalytics.com` auch auf pornblock und malware Blocklisten zu finden.
Google Analytics sind im Gegensatz zu Plausible zwar personenbezogen (und definitiv Tracking im negativen Sinne), aber Porn ist es sicher nicht und auch diese Domain würde ich nicht als Malware einstufen.

Am sinnvollsten fände ich es, wenn eine separate Liste für Tracking erstellt werden würde. Als Benutzer der Malware Liste erwarte ich zumindest, dass diese nur Seiten blockt, die Schadware verbreitet. Genau so wird diese Liste ja auch [hier](https://github.com/RPiList/specials/blob/master/Blocklisten/readme.md) beschrieben. Andernfalls sollte die Dokumentation klarstellen, dass auch Tracker darunter fallen.

**Comment by RPiList** [comment]
> 
> > aber imho ist Analytics mit Tracking gleichzusetzen
> 
> Auch wenn es sich bei Analytics in den meisten Fällen um Tracking handelt, würde ich die Begriffe nicht gleichsetzen.

Genau das ist ja das Problem. Meistens ist es Tracking und die Meisten setzen es gleich. 

Ist ein wenig so, wie beim "Quantensprung" welches lt. offizieller Definition ein kleiner Sprung ist, aber von praktisch allen Menschen als "großer" Sprung verstanden wird.

Jetzt kann man sagen, alle haben unrecht... aber bekehren wird man sie deswegen nicht.

Am Ende ist diese Liste dann die "einzige" Liste, die eine schützende Hand über eine Analytics-Seite hält, die von allen als Tracking/Malware/Böse interpretiert wird. Denn genau deswegen, ist die Domain ja überhaupt erst in unserer Liste gelandet.

Die Nutzer werden sich dann über kurz oder lang fragen, über welche Domains wir ebenfalls die schützende Hand halten. Die Kritik hat es ja schon öfters bei anderen Anbietern gegeben, die dann anfangen bestimmte Werbung durchzulassen; weil sie von denen bezahlt werden.

Für den Nutzer ist nur interessant, ob "seine" App noch funktioniert, wenn die Domain gesperrt ist.

> Interessanterweise ist `googleanalytics.com` auch auf pornblock und malware Blocklisten zu finden.

Wie schon mehrfach erwähnt. Im Real-Life unterscheiden die meisten Blocklist-Betreiber nicht zw. Malware und Tracking. Sind verschiedene Äste des gleichen Baumes.

> Google Analytics sind im Gegensatz zu Plausible zwar personenbezogen (und definitiv Tracking im negativen Sinne), aber Porn ist es sicher nicht und auch diese Domain würde ich nicht als Malware einstufen.
> 

Aufgrund der ersten vier Buchstaben bei "Analytics" schlägt der Bot recht zügig an.

> Am sinnvollsten fände ich es, wenn eine separate Liste für Tracking erstellt werden würde. Als 

Wir hatten das auch ursprünglich mal vor. Da das aber außer uns kaum einer macht, lohnt der Aufwand nicht. Wir haben dann 50.000 Einträge in der Tracking-Liste, während die Malware-Liste (die von anderen Listen zusammengetragen wird, die gleichen Einträge auch schon enthält, weil die anderen Maintainer diese Trennung nicht vornehmen.

Deswegen hier noch mal der Aufruf an andere Mitlesende. Was erwartet Ihr von den Blocklisten. Ist Tracking = Tracking = Schadware... oder würdest Ihr da auch unterscheiden wollen? Würde es die Glaubwürdigkeit des Projekts beschädigen, wenn man bestimmte Tracking-Seiten ausnimmt? Würde es überhaupt einen unterschied machen, wenn die Domain am Ende von anderen Blocklists im Pi sowieso geblockt wird? Neben unseren Listen dürften die Nutzer ja noch andere Listen benutzen.

Grüße

**Comment by bytesortierer** [comment]
Hallo zusammen,

Für mich kann ich die u.a. Frage beantworten. Ich benötige keine Splitting in Malware / Tracking Listen.
Ist für mich beides unerwünscht und somit Schadware. Sollte ich die ein oder andere Domain dennoch mal benötigen, würde ich sie in meinem Pi-Hole whitelisten.

Mit freundlichen Grüßen
Marc Krüger


Auf Twitter folgen:
https://twitter.de/marc_krueger
Am 18. Feb. 2021, 20:57 +0100 schrieb RPiList <notifications@github.com>:

**Comment by irgendwr** [comment]
Zur generellen Diskussion über Tracker:

Ich kann die Gegenargumente nachvollziehen. Versteht mich nicht falsch: Mich stört es nicht, wenn Tracker geblockt werden, aber dann sollte das zumindest erwähnt werden. Ich habe jedenfalls nicht damit gerechnet.

Relevant ist die Unterscheidung z.B. wenn
- man Statistiken über die geblockten Seiten erstellt
- diese Liste für Monitoring / Alert Systeme genutzt wird (bei Malware möchte man ggf. Alerts bekommen, für Tracker jedoch nicht)

---

Zu Plausible:

Dass der Analytics Dienst gesperrt wird, ist mir auch hier eigentlich egal. In diesem Fall interessierte mich allerdings die Dokumentation zu dem Dienst, die leider auf der selben Domain liegt wie das Analytics Script.
