### ISSUE TITLE
insidecorona.net

### ISSUE THREAD

**Issue by irgendwr** [RPiList/specials#475]
Hallo, ich nehme an die "Corona-Blocklist" soll Fake-Science&co blocken und nicht tatsächliche Wissenschaft.

"insidecorona.net" ist die Seite eines Forschungsteams an der Universität Hamburg. Die "Coronavirus Structural Task Force" wird durch das Bundesministerium für Bildung und Forschung gefördert.

- https://github.com/thorn-lab/coronavirus_structural_task_force
- https://insidecorona.net/about/
- https://twitter.com/ThornLab

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist bereits gefixt.

Viele Grüße
