### ISSUE TITLE
Blacklist Domains for Streaming

### ISSUE THREAD

**Issue by pali768** [RPiList/specials#479]
**Streaming:**

tarnkappe.info / www.tarnkappe.info

Watched.com / www.Watched.com / addons.watched.com

rokkr.net / www.rokkr.net

onionplay.co / www.onionplay.co

onionplay.is / www.onionplay.is

lookmovie.io / www.lookmovie.io

watch-series.la / www1.watch-series.la

watchepisodes4.com / www.watchepisodes4.com

trailers.to / www.trailers.to

best-series.me / www.best-series.me

mywatchseries.stream / www.mywatchseries.stream

soapgate.org / www.soapgate.org

5movies.to / www.5movies.to

filmheaven.com / www.filmheaven.com

watchgameofthrones.tv / www.watchgameofthrones.tv

123movie.uno / www.123movie.uno

flixpad.net / www.flixpad.net

smflix.cc / www.smflix.cc

c1ne.co / www.c1ne.co

layarkacaxxi.biz / www.layarkacaxxi.biz

lookmovie.ag / www.lookmovie.ag

flixgo.biz / www.flixgo.biz

himovies.to / www3.himovies.to

gophie.cam / www.gophie.cam

vmovee.watch / www.vmovee.watch

gomovies.uno / www.gomovies.uno

smilestv.net / www2.smilestv.net

series9.ac / www3.series9.ac

series9.ac / www4.series9.ac

onionplay.to / www.onionplay.to

fmovies.name / www.fmovies.name

putlocker123.to / ww2.putlocker123.to

hdbest.net / www.hdbest.net

movieminions.co / www.movieminions.co

247movies.xyz / www.247movies.xyz

myflixer.to / www.myflixer.to

supernova.to / www.supernova.to

kisscartoon.love / www7.kisscartoon.love

kisscartoon.org / www.kisscartoon.org

movieforfree.co / www.movieforfree.co

moviestube.icu / www.moviestube.icu

123moviesme.org / www.123moviesme.org

moviesjoy.to / www.moviesjoy.to

uwatchfree.mx / www.uwatchfree.mx

teatv.xyz / www.teatv.xyz

seehd.nl / www.seehd.nl

4k-hd.club / www.4k-hd.club

seehd.nlhome / www.seehd.nlhome

moviecracker.net / www.moviecracker.net

gustatv.to / www2.gustatv.to

vmovee.watch / www.vmovee.watch

fmovieshd.vip / www.fmovieshd.vip

filmheaven.com / www.filmheaven.com

watchserieshd.tv / www3.watchserieshd.tv

quitt.net / www.quitt.net

snahp.it / www.snahp.it

wcostream.com / www.wcostream.com

6movies.net / www.6movies.net

ligaxxi.xyz / www.ligaxxi.xyz

movierot.com / www.movierot.com

freshmoviestreams.net / www.freshmoviestreams.net

tikmovies.com / www.tikmovies.com

vidnext.net / www.vidnext.net

tinyzone.tv / www.tinyzone.tv

cineb.net / www.cineb.net

pubfilms.club / www.pubfilms.club / old.pubfilms.club

movieorca.com / www1.movieorca.com

movierot.com / www1.movierot.com

myflixer.to / www.myflixer.to

f5movies.co / www.f5movies.co

ainiesta.com / www.ainiesta.com

minionstream.com / www.minionstream.com

wwatchseries.com / www.wwatchseries.com

f2movies.to / www.f2movies.to / www2.f2movies.to / www3.f2movies.to

myflixer.com / www.myflixer.com

actvid.com / www.actvid.com

ev01.net / www.ev01.net

ev01.to / www.ev01.to

zoechip.com / www.zoechip.com / www1.zoechip.com

myflixerhd.ru / www.myflixerhd.ru

myflixer.link / www.myflixer.link

123moviesx.tv / www.123moviesx.tv

attacker.tv / www.attacker.tv /www1.attacker.tv

seeingblind.net / www.seeingblind.net / www1.seeingblind.net

watch0123movies.org / www.watch0123movies.org

klimtthemovie.com / www.klimtthemovie.com

afdah.info / www.afdah.info

moviesjoy.net / www.moviesjoy.net / www1.moviesjoy.net

filmlicious.net / www.filmlicious.net / www1.filmlicious.net

ladresstina.com / www.ladresstina.com

vidcloud9.com / www.vidcloud9.com

www.redbeltmovie.com / www.redbeltmovie.com

1watch-free.cc / www.1watch-free.cc

fullmoviehd4k.com / www.fullmoviehd4k.com

cataz.net / www.cataz.net

tinyzonetv.to / www.tinyzonetv.to

showboxmovies.net / www.showboxmovies.net

watch4freemovies.com / www.watch4freemovies.com

musichq.net / www.musichq.net / www3.musichq.net

123moviesfree.net / www.123moviesfree.net

filmlicious.net / www.filmlicious.net / www2.filmlicious.net

fullmoviefilm.org / www.fullmoviefilm.org / www.fullmoviefilm.org

moviekids.tv / www.moviekids.tv

ummagurau.com / www.ummagurau.com / www1.ummagurau.com

freemovies360.com / www.freemovies360.com

put-locker.com / www.put-locker.com / ww1.put-locker.com

123moviesgo.tv / www.123moviesgo.tv / www2.123moviesgo.tv / www6.123moviesgo.tv

akotv.me / www.akotv.me

bflix.to / www.bflix.to

thewebflicks.com / www.thewebflicks.com

fmovies.to / www.fmovies.to

fsharetv.co / www.fsharetv.co

lunchflix.org / www.lunchflix.org

uniquestream.vip / www.uniquestream.vip

olamovies.top / www.olamovies.top

hdfull.lv / www.hdfull.lv

ohh.io / www.ohh.io

europixhd.net / www.europixhd.net

orej.net / www.orej.net

emovies.io / www.emovies.io

movie-forum.co / www.movie-forum.co

cinebloom.org / www.cinebloom.org

topeuropix.site / www.topeuropix.site

movies123.email / www.movies123.email

icefilms-info.com / www.icefilms-info.com

primewire.li / www.primewire.li

flixseries.club / www.flixseries.club

iwatchfreestreams.to / www.iwatchfreestreams.to

uwatchfree.vg / www.uwatchfree.vg

cinevood.cyou / www.cinevood.cyou

dutafilm.network / www.dutafilm.network

vumoo.to / www.vumoo.to

ymovies.se / www.ymovies.se

downloads-anymovies.com / www.downloads-anymovies.com

losmovies.live / www.losmovies.live

hoodlux.ml / www.hoodlux.ml

watchsomuch.tv / www.watchsomuch.tv

cmovies.ac / www.cmovies.ac

yesmovies.sh / www.yesmovies.sh

azm.to / www.azm.to

noxx.is / www.noxx.is

allmoviesforyou.co / www.allmoviesforyou.co

new-primewire.com / www.new-primewire.com / ww1.new-primewire.com

classiccinemaonline.com / www.classiccinemaonline.com

retrovisionmedia.com / www.retrovisionmedia.com

rainierland.to / www.rainierland.to

sflix.to / www.sflix.to

primewire.li / www.primewire.li

cinehub.wtf / www.cinehub.wtf

rarefilmm.com / www.rarefilmm.com

6movies.net / www.6movies.net / www2.6movies.net

flenix.net / www.flenix.net

hdonline.eu / www.hdonline.eu / w9.hdonline.eu

fzmovies.net / www.fzmovies.net

ok.ru / www.ok.ru

moviesverse.net / www.moviesverse.net

crackstreams.com / www.crackstreams.com

nbastreams.xyz / www.nbastreams.xyz

the.crichd.com / www.the.crichd.com 

stream2watch.is / www.stream2watch.is 

nflbite.com / www.nflbite.com 

nbastreams.to / www.nbastreams.to

mlbstreams.to / www.mlbstreams.to

cricfree.sc / www.cricfree.sc 

watchwrestling.la / www.watchwrestling.la 

livesoccertv.com / www.livesoccertv.com 

f1fullraces.com / www.f1fullraces.com 

fullmatchfk.com / www.fullmatchfk.com

racinghd.net / www.racinghd.net

vipleague.lc / www.vipleague.lc

live-sport.online / www.live-sport.online

iplhd.online / www.iplhd.online 

enamyworld.xyz / www.enamyworld.xyz

sportsbay.org / www.sportsbay.org

livesoccertv.com / m.livesoccertv.com / www.livesoccertv.com

bilasport.net / www.bilasport.net

ripple.stream / www.ripple.stream

topstreams.info / www.topstreams.info

ustvgo.tv / www.ustvgo.tv 

soccerstreams.net / www.soccerstreams.net / reditt.soccerstreams.net 

formula1-live.stream / www.formula1-live.stream

live-nfl.stream / www.live-nfl.stream

live-nba.stream / www.live-nba.stream

live-nhl.stream / www.live-nhl.stream 

mlb-live.stream / www.mlb-live.stream

ncaa-live.stream / www.ncaa-live.stream

mls-live.stream / www.mls-live.stream

epl-live.stream / www.epl-live.stream 

bundesliga-live.stream / www.bundesliga-live.stream

ligue1-live.stream / www.ligue1-live.stream 

calcio-live.stream / www.calcio-live.stream

barcelona-live.stream / www.barcelona-live.stream

football-live.stream / www.football-live.stream

futebolaovivo.stream / www.futebolaovivo.stream

live-tennis.stream / www.live-tennis.stream

ufc-live.stream / www.ufc-live.stream

wwe-live.stream / www.wwe-live.stream 

cricket-live.stream / www.cricket-live.stream

motogp-live.stream / www.motogp-live.stream

nascar-live.stream / www.nascar-live.stream

football-live.stream / www.football-live.stream

livetv.sx / www.livetv.sx

fromhot.to / www.fromhot.to

streamonsport.club / www.streamonsport.club

sportsurge.net / www.sportsurge.net

freestreams-live1.com / www.freestreams-live1.com

kooora4live.tv / www.kooora4live.tv

streamwoop.live / www.streamwoop.live

streameast.live / www.streameast.live

channelstream.me / www.channelstream.me

mygoodstream.pw / www.mygoodstream.pw

sportzonline.to / www.sportzonline.to

streamwoop.live / www.streamwoop.live

nbastream.nu / www.nbastream.nu 

nflstream.io / www.nflstream.io

nhlstream.nu / www.nhlstream.nu

mlbstream.me / www.mlbstream.me

nflstream.io / www.nflstream.io

nbastream.nu / www.nbastream.nu

tennisstreams.me / www.tennisstreams.me

rugbystreams.me / www.rugbystreams.me

boxingstreams.me / www.boxingstreams.me

socceronline.me / www.socceronline.me

ufcstream.me / www.ufcstream.me

motogpstream.me / www.motogpstream.me

f1stream.me / www.f1stream.me

cricstream.me / www.cricstream.me

blacktiesports.net / www.blacktiesports.net

nflfullhd.com / www.nflfullhd.com

anime1.com / www.anime1.com 

anime8.ru / www.anime8.ru 

animebam.se / www.animebam.se 

animedaisuki.moe / www.animedaisuki.moe 

animedao.to / www.animedao.to

animefever.tv / www.animefever.tv

animefreak.tv / www.animefreak.tv

animeflix.io / www.animeflix.io

animefrenzy.net / www.animefrenzy.net

animehub.ac / www.animehub.ac

animekisa.tv / www.animekisa.tv

animelon.com / www.animelon.com

anilinkz.to / www.anilinkz.to

anime-loads.org  / www.anime-loads.org

animepahe.com / www.animepahe.com 

anime-planet.com / www.anime-planet.com

animepill.com / www.animepill.com

animeram.cc / www.animeram.cc

animered.me / www.animered.me

animereborn.net / www.animereborn.net

animerush.tv / www.animerush.tv

animesa.ga / www.animesa.ga

animeseries.io / www.animeseries.io

animeshow.tv / www.animeshow.tv

animesimple.com / www.animesimple.com

animetake.tv / www.animetake.tv

anitube.site / www.anitube.site

animeultima.to / www.animeultima.to

animevibe.tv / www.animevibe.tv

animixplay.to / www.animixplay.to

aniwatch.me / www.aniwatch.me

cartooncrazy.net / www.cartooncrazy.net

chia-anime.tv / www.chia-anime.tv

chihiro-subs.com / www.chihiro-subs.com

darkanime.stream / www.darkanime.stream

dubbedtv.tv / www.dubbedtv.tv

gogoanime.io / www.gogoanime.io

justdubs.org / www.justdubs.org

kawaiifu.com / www.kawaiifu.com

kaa.si / www.kaa.si

kimcartoon.to / www.kimcartoon.to 

proxer.me / www.proxer.me

ryuanime.com / www.ryuanime.com

sganime.org / www.sganime.org

simpleyaweeb.com / www.simpleyaweeb.com

otaku-streamers.com / www.otaku-streamers.com

watchcartoononline.io / www.watchcartoononline.io

tranimeizle.net / www.tranimeizle.net

turkanime.net / www.turkanime.net

twist.moe / www.twist.moe

www7.kisscartoon.love / www7.kisscartoon.love

12canime.cc / www.12canime.cc 

kimanime.ru / www.kimanime.ru

netanime.tv / www.netanime.tv

yugenani.me / www.yugenani.me 

4anime.to / www.4anime.to

animetribes.ru / www.animetribes.ru

losmovies.live / www.losmovies.live 

watchsomuch.tv / www.watchsomuch.tv

flenix.net / www.flenix.net

picotube.online / www.picotube.online

animepahe.com / www.animepahe.com

anime-tv.fun / www.anime-tv.fun

hdonline.eu  / w9.hdonline.eu / www.hdonline.eu

**Comment by RPiList** [comment]
Vielen Dank für die Mühen.

Alle Domains sind der entsprechenden Liste hinzugefügt worden. Viele Grüße.

**Comment by dtrhzhrhrgf435** [comment]
Zu Tarnkappe.info:
diese tätigen lediiglich Berichterstattung über Streaming-related Themen.
Ich  weiß nicht, ob ihr das auch in der Liste haben wollt.

**Comment by RPiList** [comment]
> Zu Tarnkappe.info:
> diese tätigen lediiglich Berichterstattung über Streaming-related Themen.

Domain ist deswegen auch nicht auf der Blockliste gelandet. Die Domain bietet selbst kein Streaming an. Nur Berichterstattung. Grüße.
