### ISSUE TITLE
Ethermine

### ISSUE THREAD

**Issue by dtrhzhrhrgf435** [RPiList/specials#484]
Moin,
Ethermine.org (und einige Subdomains) ist fälschlicherweise auf der malware Blocklist von euch.
Ethermine ist schlichtweg ein Mining-Pool für Ethereum (u.a.) Mining.

Eine Entfernung wäre gut.

Gruß

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Habe ich jetzt erst mal "von Hand" entfernt ohne es auf die Whitelist zu setzen. Mal schauen ob es wieder eingespielt wird. Wäre ja möglich, dass es trotzdem auf dieser Website Schadware/Crypto gegeben hat.

Viele Grüße.
