### ISSUE TITLE
Login Name und passwort unbekannt

### ISSUE THREAD

**Issue by Hamm3rhart** [RPiList/specials#49]
Guten Tag,
habe eben das Image auf meinen PI geladen kann mich aber jetzt nicht anmelden da mir der Benutzername sowie das Passwort fehlen.

Kann mir da einer weiterhelfen?
Danke im vorraus

**Comment by H4ckZ** [comment]
pi:123456

**Comment by Hamm3rhart** [comment]
Ty

**Comment by Hamm3rhart** [comment]
Nur so. Warum kann man sich nicht als root anmelden auch wenn man das Passwort ändert?

**Comment by joestr** [comment]
Bei Raspbian ist es standardmäßig so, dass in der SSH-Konfiguration unter `/etc/ssh/sshd_config` die Zeile `PermitRootLogin no` gesetzt, was es nicht ermöglicht sich mit dem Benutzer `root` über SSH am System anzumelden.

**Comment by blub4747** [comment]
Hier noch ein paar empfehlungen bzw immer brauchbare schritte.

Welche anderen user gibt es noch ?

Mal in die passwd schauen.
cat /etc/passwd
welche anderen home verzeichnisse gibt es noch ?
ls /home

Und bei der gelgenheit können wir noch gleich den ganzen TimeZone und locales kram gleich mit anpassen. Also

sudo dpkg-reconfigure tzdata

für die Zeitzone

und für die locales

sudo dpkg-reconfigure locales

**Comment by H4ckZ** [comment]
Ich glaub das artet hier grade etwas aus.. sollte noch kein Beginners-Guide sein, oder? :D
