### ISSUE TITLE
Eventuell fehlerhaft gesperrte Domains?

### ISSUE THREAD

**Issue by Xedon420** [RPiList/specials#492]
Mir sind kürzlich zwei Domains aufgefallen bei denen ich den Blacklist Eintrag nicht verstehen kann.
Eventuell liegt hierbei ein Fehler vor:

 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4:
   www.17juni53.de 
(Definitiv kein porn)

 Match found in https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Xiaomi.txt:
   account.jetbrains.com 
(was hat Jetbrains mit Xiaomi zu tun? Jetbrains ist meines Wissens nach ein Entwickler von sehr guten IDEA's ^^ ) 
Ist der Ersteller der Liste hier auch aktiv? Sonst erstelle ich dort im Repo nochmal ein Issue.

Vielen Dank für die großartige Arbeit die Ihr in die Listen investiert. Keine tracker, keine ads, kein scam mehr im Netzwerk dank euerer Arbeit!

**Comment by RPiList** [comment]
> Mir sind kürzlich zwei Domains aufgefallen bei denen ich den Blacklist Eintrag nicht verstehen kann.
> Eventuell liegt hierbei ein Fehler vor:

Ja, ist ein Fehler und wird umgehend entfernt.

> Match found in https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Xiaomi.txt:
> account.jetbrains.com
> (was hat Jetbrains mit Xiaomi zu tun? Jetbrains ist meines Wissens nach ein Entwickler von sehr guten IDEA's ^^ )
> Ist der Ersteller der Liste hier auch aktiv? Sonst erstelle ich dort im Repo nochmal ein Issue.

Das ist keine Liste, die von uns gepflegt wird, insoweit können wir den Eintrag nicht löschen.
> 
> Vielen Dank für die großartige Arbeit die Ihr in die Listen investiert. Keine tracker, keine ads, kein scam mehr im Netzwerk dank euerer Arbeit!

Vielen Dank für die Meldung und viele Grüße

**Comment by Xedon420** [comment]
Vielen Dank für die schnelle Antwort,

Habe gerade eben eine verdächtige Domain geschickt bekommen, könntet ihr die bitte in die Liste aufnehmen?
"adidastore.xyz" (scam)

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Fixed. Viele Grüße
