### ISSUE TITLE
Fehler in notserious-Liste

### ISSUE THREAD

**Issue by bones78** [RPiList/specials#496]
Hallo!
In der Liste: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
ist der Begriff "schuhe" (ohne TLD) enthalten. Das führt dazu, dass bei Adguard home alles mit dem Wort schuhe in der Domain geblockt wird. 
Bitte nur den Begriff schuhe entfernen.
Vielen Dank

Auszug:
schuhdemarkt.de
schuhe
schuhe.alluckys.com

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist jetzt gefixt. Viele Grüße.
