### ISSUE TITLE
[Easylist] - Received 55635 domains, 5 domains invalid!

### ISSUE THREAD

**Issue by ITaluone** [RPiList/specials#499]
![image](https://user-images.githubusercontent.com/44049228/110610585-aba52c80-818e-11eb-9b40-2c1acbeed2ce.png)

**Comment by ITaluone** [comment]
I think just ignoring is not a good idea, because the domains are valid (until the first occurrence of `$ ~ | @`). 

Instead I would remove everything behind the $-sign (and the $-sign of course :D)

**Comment by RPiList** [comment]
Hi, thx for letting us know. It's fixed now. Don't know how they could slip through our filtering since they did not do it in earlier scans...

Greetings.
