### ISSUE TITLE
Pihole blockt nicht

### ISSUE THREAD

**Issue by Hamm3rhart** [RPiList/specials#50]
Guten Abend,
das eben frisch über das fertige Image installierte piHole blockiert keine Werbund noch irgend eine andere Seite in der Blockliste was kann ich da tun? Es erkennt die Geräte im Netzwerk aber ich bin mir unsicher ob er sich auch als DNS Server dazwischen schaltet.
![2a0b95a4](https://user-images.githubusercontent.com/50116721/71311061-07fe1e00-241c-11ea-9044-fbe52618bbe4.png)

![cabdd8ba](https://user-images.githubusercontent.com/50116721/71311068-282ddd00-241c-11ea-9515-0635c211a506.png)

![813c8318](https://user-images.githubusercontent.com/50116721/71311075-4398e800-241c-11ea-8deb-af951571de9e.png)

![41528a48](https://user-images.githubusercontent.com/50116721/71311084-57444e80-241c-11ea-8036-0e893a2f6b89.png)

Kann mir da vielleicht einer weiterhelfen, ginge auch per Teamviewer oder Anydesk wenn das einfacher wäre.

Danke im vorraus.

**Comment by H4ckZ** [comment]
Hast du die Blocklisten in pihole aktiviert? 
Unter Settings/Blocklists anhaken und dann auf "Save and Update" drücken

**Comment by Hamm3rhart** [comment]
Ja,
![cb23b792](https://user-images.githubusercontent.com/50116721/71312002-5d3f2d00-2426-11ea-93d2-3a9708498204.png)

**Comment by H4ckZ** [comment]
Hat der PI ne aktive Internetverbindung?

**Comment by Hamm3rhart** [comment]
Ja, habe auch gerade mal pihole -r gemacht und ihn reconfiguriert. Jetzt hat er auch eine IP bekommen die er vorher ja nicht hatte.

Vorher:
![41528a48](https://user-images.githubusercontent.com/50116721/71312381-6a5e1b00-242a-11ea-8049-a747da127acb.png)

Nachher:
![363adebd](https://user-images.githubusercontent.com/50116721/71312384-7053fc00-242a-11ea-807d-bf81a04a676b.png)

Aber blockt immer noch keine Werbung. Fritzbox ist so eingestellt:

![418855e7](https://user-images.githubusercontent.com/50116721/71312410-dfc9eb80-242a-11ea-8cac-16b95bc91f93.png)
-----------------------------------------------
![7d4c7c3c](https://user-images.githubusercontent.com/50116721/71312411-e2c4dc00-242a-11ea-926e-cdf9f2a6e1df.png)
-----------------------------------------------
![84ebdd1d](https://user-images.githubusercontent.com/50116721/71312412-e5273600-242a-11ea-9d28-dfc85c077973.png)
-----------------------------------------------

Hoffe das hilft

**Comment by H4ckZ** [comment]
Nachdem er jetzt ne IP hat solltest du nochmal mit "Save and Update" die Listen neu laden.
Dann kannst du auf nem Client den DNS-Cache löschen und kontrollieren, ob der Client auch den PI als DNS Server eingetragen hat.
Dann sollte das Ganze eigentlich laufen..

**Comment by Hamm3rhart** [comment]
Funktioniert jetzt alles. Vielen Danke
