### ISSUE TITLE
[Question] Xbox One X Login Probleme

### ISSUE THREAD

**Issue by ovz93br43v7** [RPiList/specials#507]
Meine Xbox One X braucht oft beim Starten relativ lange zum Einloggen. Die einzigen beiden Domains die laut Pihole oft angefragt werden und blockiert werden sind:
```
uk.at.atwola.com
watson.telemetry.microsoft.com
```

Ich konnte nirgendwo online einen Hinweis finden das diese Domains für Xbox / MS / Xbox Live benötigt werden.

Hat einer von euch ähnliche Probleme aktuell?

**Comment by RPiList** [comment]
Hi,

ich habe beide Domains erstmal überall entfernt. Die waren teilweise in Listen vertreten in denen sie nichts zu suchen hatten. Also entweder werden die Quellen die wir heranziehen, immer schlampiger oder wir haben mal Fehler beim Import gemacht.

Bei der Microsoft.com Domain wundert mich, dass die nicht in der MS-Blocking-Liste drin ist. Aber das kann daran liegen, dass wir mit unserer Liste nur der offiziellen BSI-Liste folgen.

Also einfach das Pi updaten. Bzgl. der Microsoft.com Domain, kann es sein, dass die in die MS-Liste wandert. 

Viele Dank für den Hinweis.
