### ISSUE TITLE
Microsoft OneNote Mobile App Probleme

### ISSUE THREAD

**Issue by strausmann** [RPiList/specials#508]
Guten Tag,

ich habe nach dem Import der Child Protection List ein Problem mit dem Login der OneNote App auf dem Samsung Galaxy gehabt.
Ich habe dann die Logs geprüft und dort die URL mobile.pipe.aria.microsoft.com gefunden.

Nach dem ich die mobile.pipe.aria.microsoft.com in die Whitelist aufgenommen habe, konnte ich mich wieder erfolgreich einloggen mit meinem Live Account.

Ihr wart allerdings nicht die einzigen, die diese Subdomain in der Blocklist drinnen haben.

>  Match found in exact whitelist
   mobile.pipe.aria.microsoft.com
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   mobile.pipe.aria.microsoft.com 
 Match found in https://adaway.org/hosts.txt:
   mobile.pipe.aria.microsoft.com 
 Match found in https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt:
   mobile.pipe.aria.microsoft.com 
 Match found in https://raw.githubusercontent.com/CamelCase11/UnifiedHosts/master/hosts.all:
   mobile.pipe.aria.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   mobile.pipe.aria.microsoft.com 

Gruß

Björn

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Habe es auf jeden Fall mal aus der CP Liste gelöscht. Viele Grüße
