### ISSUE TITLE
Seiten von Listen entfernen

### ISSUE THREAD

**Issue by Naimkr27** [RPiList/specials#509]
Hallo zusammen, 

könnt ihr bitte folgende Seiten von den Listen entfernen.
https://www.marschfuersleben.de/
Beim Marschfuersleben.de handelt es sich um eine Lebensschutzbewegung, davon geht keine Gefahr aus
Proktologie-Bogenhausen.de
bei der Proktologie handelt es sich um eine Arztpraxis in München, ich glaube nicht das davon eine Gefahr ausgeht.

Mein PiHole sperrt beide Seiten. Oder gibt es eine Funktion, außer Whitelist, wie man die Sperre deaktiviert, falls die Seiten nicht auf der Liste sind?

**Comment by RPiList** [comment]
Hi,

soweit ich das erkennen kann sind die zwei Domains in keiner unserer Listen vertreten. Insoweit kann ich die nicht löschen. Viele Grüße
