### ISSUE TITLE
Lokaler DNS Server bei FRITZ!Box 7590

### ISSUE THREAD

**Issue by 00DanielXX** [RPiList/specials#51]
Währe ich nicht besser das Pi-hole unter "Heimnetz > Netzwerk > IPv4-Adressen > Lokaler DNS Server" einzutragen als in der Anleitung gezeigt unter "Internet > Zugangsdaten > DNS-Server"? So wird den Geräten gesagt das sie direkt beim Pi-hole nachfragen sollen und nicht das die Geräte bei der FRITZ!Box nachfragen und die Fritzbox dann beim Pi-hole. Dann ist es auch möglich dem Pi-hole die Anfragen weiter an die FRITZ!Box weiterleiten zu lassen. Diese kann dann bald (jetzt auch schon im FRITZ!Labor) die DNS verschlüsselt mit DNS over TSL ins intenet schicken, oder einfach die DNS Server des Providers nutzen.

**Comment by H4ckZ** [comment]
Ja ist meiner Meinung nach besser wenn man das unter Heimnetzwerk einstellt.
Ist bei der Anleitung der 7490 auch so drinnen von mir
