### ISSUE TITLE
ssh PW

### ISSUE THREAD

**Issue by regs1980** [RPiList/specials#510]
Schön wäre es mal zu wissen wie das ssh Passwort ist, wenn man so was schon kostenlos anbietet, kann man das auch in der Readme vermerken, nur mal so als kleiner Hinweis.

**Comment by joestr** [comment]
Bitte mal bei Issue #49 vorbeischauen.

**Comment by regs1980** [comment]
Danke

**Comment by RPiList** [comment]
Ist richtig... die sonst beiliegende Datei info.txt wurde in der neuesten Version vergessen. Wird gleich geändert. Viele Grüße
