### ISSUE TITLE
www.techradar.com

### ISSUE THREAD

**Issue by irgendwr** [RPiList/specials#511]
`www.techradar.com` ist in der malware liste obwohl es bereits in der whitelist steht

**Comment by irgendwr** [comment]
Ich glaube ich werde die Liste aufgeben und nicht weiter nutzen, das overblocking ist mir zu stark. Keine andere Liste hatte bis jetzt so viele false positives.

Ist nicht abwertend gemeint, bei über einer Millionen Domains auf der malware Liste kommen natürlich Fehler vor, egal wie gründlich geprüft wird. Aber dann nehm' ich lieber eine oder mehrere kleinere Listen die dafür präzieser sind (insbesondere in deren Ziel was überhaupt unerwünscht ist).

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist jetzt gefixt. Viele Grüße.

**Comment by RPiList** [comment]
> Ich glaube ich werde die malware Liste aufgeben und nicht weiter nutzen, das overblocking ist mir zu stark. Keine andere Liste hatte bis jetzt so viele false positives.
> 
ist richtig und würde ich ebenfalls genauso machen. Es ist normal, dass die Listen overblocking haben, bis nach einer gewissen Zeit eine ordentliche Whitelist vorhanden ist. Da es solche Whitelists aber nicht gibt, muss die selbst aufgebaut werden.

P.S.: Natürlich gibt es Whitelists im Internet, aber die sind nicht fürs Pihole geeignet, weil die sonst auch jegliche Werbung usw... durchlassen würden.

Viele Grüße.
