### ISSUE TITLE
Domains für eine der Blacklisten

### ISSUE THREAD

**Issue by 10k-resistor** [RPiList/specials#512]
Hallo,

ich bin auf zwei Domains gestossen, über welche Werbung ausgeliefert wird:

cdn.audio-ads.io
api.audio-ads.io

Viele Grüße
10k-resistor

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden in die Easylist geschoben. Viele Grüße

**Comment by 10k-resistor** [comment]
Vielen Dank
