### ISSUE TITLE
remove perfect-privacy.com & codecademy.com

### ISSUE THREAD

**Issue by DanielIsTaken** [RPiList/specials#513]
perfect-privacy.com, ein VPN-Anbieter, ist in der [Malware Liste](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware) und der [easylist](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist) geblockt.
Des weiteren scheint codecademy.com fälschlicherweise in der [Phishing Angriffs Liste](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe) blockiert zu sein.

**Comment by BulldozerPete** [comment]
codecademy.com konnte ich in keiner Blocklist finden, perfect-privacy.com wurde zur whitelist hinzugefügt. 
Siehe #514

**Comment by RPiList** [comment]
Mein Fehler, hatte ich gelöscht aus den Listen ohne hier Bescheid zu sagen. 

Vielen Dank an @DanielIsTaken für den Hinweis. Viele Grüße
