### ISSUE TITLE
Müll Domains und Malware

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#515]
`supra.dns-cloud.net` (Malware download)

`mediazlez.pp.ua/d/5GwglGmESD` und `failsame.ru/file/24f420` (Sieht zwar nur so aus wie ein normaler file hoster aber jeder link leitet nur zu täglich wechselnden malware Seiten weiter)

`https://tophacks.pro/fortnite` (Sieht aus wie ein normaler link shortener aber jeder link leitet nur zu fast täglich wechselnden file hostern mit malware dateien weiter. Bringt also nichts sich bei den file hostern direkt zu beschweren weil täglich eh ein anderer link kommt)

`walhalagame.fun` und `walhalagames.pw` sind unseriös und leiten ebenfalls zu täglich wechselnden malware domains weiter

`fortniteswapper.fun` der angebotene Download besteht ebenfalls nur aus wechselnden file hostern mit malware dateien (reporten bei den file hostern bringt also nichts weil die tauschen den link direkt aus)

Oft wird die Zip mit einem Passwort versehen (so einfache wie 1234, 12345, 1111, 11111) damit Antivirenprogramme das nicht erkennen können. Das Passwort für den ach so geilen download wird aber "netterweise" direkt dazu gepackt.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Mühen und die Domains. Diese sind jetzt in die jeweiligen Listen eingebaut. Viele Grüße.
