### ISSUE TITLE
Nachtrag zum Pi-hole mit OpenVPN auf einem V-Server

### ISSUE THREAD

**Issue by 00DanielXX** [RPiList/specials#52]
Ich habe noch einen Nachtrag zum Pi-Hole und OpenVPN auf einem V-Server:
Ich konnte nich einfach nicht mit dem Pi-Hole verbinden obwohl OpenVPN verbunden war und richtig konfiguriert war. Die Lösung war schlussendlich den Port 53 (mit UFW) freizuschalten. Dann dachte ich aber, ich hätte das Pi-Hole jetzt offen im Internet. Die Verbindung über OpenVPN hat schließlich auf jeden Fall funktioniert. Da der Port 53 offen war hab ich die IP mal im Router eingeben um zu testen ob sich jetzt jeder damit verbinden könnte. Und der Router konnte keine Verbindung aufbauen. Das Pi-Hole hat also einen eingebauten Schutz. Als ich dann auf dem Pi-Hole unter Settings > DNS > Interface listing behavior den Punkt dann bei "**Listen on all interfaces, permit all origins**" gesetzt habe konnte mein Router sich auch verbinden. Somit war es möglich jeden, auch meiner Oma Zugang zum Pi-Hole mit einem Eintrag im Router zu ermöglicht. Aber ohne irgendwelche Einschränkungen die regulieren wer sich verbinden kann ist das ganze aber noch ziemlich unsicher, nach 20 minuten Testlauf war schon ein Eintrag von einem Server aus Tokio auf dem Pi-Hole. Jetzt währe es doch genial wenn man mit einem Hostname der zur Dynamischen IP Adresse des Routers gehört in der Firewall einschränken könnte wer sich alles über Port 53 verbinden darf! Dann währen die Omas der Welt geschützt! Und das währe dann auch noch gut für den Geldbeutel, da das ganze dann auch auf einen 1 Euro VPS von Strato laufen könnte. Vielleicht währe es irgendwie möglich das zu realisieren. Ich hoffe das kann hier einige zum denken anregen, auch den Herrn Sprecher 😅!

**Comment by RPiList** [comment]
Wir nehmen das als Vorschlag an. Aber zuerst versuchen wir mal nur das Pi-hole ans Laufen zu bekommen. Wenn dass dann überall läuft... wir also ein fertiges Image haben, dass im Grund nur noch um weitere Listen erweitert wird, dann können wir uns das Thema neue Funktionen anschauen.
