### ISSUE TITLE
apps.corel.com entfernen

### ISSUE THREAD

**Issue by Time-to-go** [RPiList/specials#520]
Wenn ich mich nicht täusche handelt es sich bei apps.corel.com um eine Subdomain von Corel.com die in den Corel Grafikprogrammen verwendet wird u.a. wenn man die Hilfe öffnen will. (Bei z.B. Coreldraw)
Falls es ein Fehler ist, ist die Subdomain in den Listen:
Block1, Child-Protection, malware, hostnames.txt (doppelnennung)
was mit den anderen Subdomains ist weiß ich nicht aber ich glaube das corel.com keine Fakewebsite ist, da sie bei Bing auch als offizielle Website eingetragen wurde

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt, bis auf die letzte Liste (hostnames.txt), die ist nicht von uns.

Viele Grüße
