### ISSUE TITLE
Youtube-Content blockiert

### ISSUE THREAD

**Issue by JDThralls** [RPiList/specials#525]
Die Liste

> **[https://www.sunshine.it/blacklist.txt](https://www.sunshine.it/blacklist.txt)**

blockiert einige Sub-Domains der Domain

> **googlevideo.com**

die für tatsächlichen (regulären) Youtube-Content verwendet werden.

Hierfür kann eine RegEx-Ausnahme Abhilfe schaffen:

`^[a-z0-9]{2}---[a-z0-9][a-z0-9\-]{10}\.googlevideo\.com$`

**Comment by RPiList** [comment]
Die Liste ist nicht von uns, insoweit können wir da leider nichts dran ändern. Dass man googlevideo Domains nicht sperren sollte, sollte sich inzw. rumgesprochen haben.
