### ISSUE TITLE
YouTube Problem mit einer Blockliste

### ISSUE THREAD

**Issue by Mannamsken123** [RPiList/specials#529]
Hallo hier nur einmal ganz kurz,

ich habe letztens meine Blocklisten auf den neusten Stand gebracht und mir ist aufgefallen, dass die Liste **https://www.sunshine.it/blacklist.txt** die YouTube Videos komplett blockt.
Also sprich man kann die Videos nicht abspielen.
Es handelt sich um den folgenden Domaintyp: **r11---sn--25ge7nl6.googlevideo.com**
Also bitte entfernen. Man könnte theoretisch eine RegEx-Whitelist erstellen, jedoch frage ich mich dann, ob die richtigen Ad-Domains ähnlich aufgebaut sind und ich somit die Werbung auch durchlasse.

Okay - LG und danke für alles!

**Comment by BulldozerPete** [comment]
Was hat die Sunshine Blocklist mit diesem Projekt zu tun?
Wie in der Blocklist am Anfang steht:
"Project home page: https://www.sunshine.it
# Title: sunshine.it - pi-hole - Black-List"
würde ich mal auf diese Kollegen zugehen.

**Comment by RPiList** [comment]
Wie @BulldozerPete bereits sagte, ist die von Ihnen genannte Liste keine Liste die wir erstellt haben. Insoweit können wir die Liste auch nicht ändern. Dazu wenden Sie sich bitte an sunshine.it.

Viele Grüße
