### ISSUE TITLE
Weitere Quelle für notserious-Blocklist

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#533]
@Zelo72 hat auch eine Blocklist für Fake-Webseiten erstellt: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/fake.txt

Sind die in der Blocklist aufgeführten Quellen auch in der notserious Blocklist integriert? Wenn nicht, dann können die ja übernommen werden oder die Quellen auch in der notserious Blocklist aufgeführt werden.

Nur ein Vorschlag.
@RPiList vielen dank für die Arbeit hier!

**Comment by RPiList** [comment]
ja, beide Listen bedienen sich im Grunde der gleichen Quellen. Mit dem Unterschied dass wir die Streaming-Abzocker in einer eigenen Liste "Streaming" haben.

Viele Grüße
