### ISSUE TITLE
Fehlerhafter Eintrag in easylist? – bp.blogspot.com

### ISSUE THREAD

**Issue by EngelPika32** [RPiList/specials#539]
Hallo RPiList Team, 

warum ist denn bp.blogspot.com auf der easylist-Blockliste? 

Soweit ich mitbekomme werden viele Bilder (von Blogs) dort gehostet. 
Zur Seite selbst kann ich nichts sagen. Es ist nur etwas seltsam einige Blogs gänzlich ohne Bilder zu lesen.
Die Domain blogspot.com selbst wird hingegen nicht blockiert (thinking)…

LG,
engel

**Comment by RPiList** [comment]
Die Easylist wird von uns nicht erstellt sondern zieht verschiedene andere "Easylists" als Quelle heran. Da das Ziel der Easylist Werbung ist, gehe ich mal davon aus, dass die Website Werbung ausgespielt hat.

Werde ich also von Hand entfernen. Viele Grüße
