### ISSUE TITLE
Die VM kann selbst nicht ins Internet, um z.B. Updates zu laden: DNS-Auflösungsfehler?

### ISSUE THREAD

**Issue by szaimen** [RPiList/specials#54]
Wenn ich versuche updates zu installieren, klappts nicht, da die VM scheinbar die DNS-Auflösung für sich selbst blockt.

**Comment by RPiList** [comment]
Sicher, dass es ein DNS-Fehler ist?

Habe die VM gerade noch mal getestet und da beschwert sich der Update-Prozess darüber, dass es Mittwoch der 25. Dez. 19:54 Uhr wäre. Eigentlich ist es gerade aber der 30.12. 23:59 Uhr.

Ein Reboot fixed das Problem automatisch.

**Comment by szaimen** [comment]
Oh,, der Neustart hat das Problem leider nicht behoben.
![image](https://user-images.githubusercontent.com/42591237/71605256-d39b0800-2b67-11ea-82b7-49fe9f222742.png)
Ich hab das Image hier runtergeladen
http://35.246.185.46/svPiholeVM.zip
und wenn ich 'sudo apt update' eingebe, kommt dieser Fehler.

**Comment by szaimen** [comment]
könnte es möglicherweise sein, dass es ein Problem ist, dass ich in der fritzbox manuell die ipv6-konnektivtität ausgeschaltet habe und damit kein Heimnetzgerät über IPv6 eine Internetverbindung nach außen aufbauen kann?

**Comment by RPiList** [comment]
Kann es was damit zu tun, haben, dass Sie evtl. in Ihrer Fritzbox jegliche DNS-Anfrage verbieten, wenn diese NICHT an das Pi-hole gerichtet sind?

**Comment by szaimen** [comment]
> Kann es was damit zu tun, haben, dass Sie evtl. in Ihrer Fritzbox jegliche DNS-Anfrage verbieten, wenn diese NICHT an das Pi-hole gerichtet sind?

Wie stellt man das ein?
Ich hab aktuell die vm noch gar nicht in der fritzbox als dns-server eingetragen. Angeheben ist ein externer dns-server. Alle anderen geräte im Netzwerk funktionieren außerdem problemlos...

**Comment by RPiList** [comment]
Das ist ne Einstellung die Sie hätten vornehmen müssen. Wenn Sie davon nichts wissen, dann haben Sie das auch auch nicht eingetragen. Das ist dann auch gut so. Dann muss der Fehler irgendwo bei uns liegen.

**Comment by szaimen** [comment]
@RPiList wurde der Fehler behoben?

**Comment by szaimen** [comment]
@RPiList oder warum wurde das Ticket geschlossen, wenn der Fehler noch nicht behoben wurde?

**Comment by RPiList** [comment]
Der Fehler tritt bei uns nicht mehr auf. Ich gehe davon aus, dass er
behoben ist.

Am Mo., 20. Jan. 2020 um 22:57 Uhr schrieb szaimen <notifications@github.com

**Comment by szaimen** [comment]
Also, bei mir trat er jetzt wieder erneut auf. 
ich habe ihn aber lösen können, indem ich folgendes zur` /etc/network/interfaces` Datei hinzugefügt habe:
```
auto eth0
iface eth0 inet dhcp
```

Nach einem reboot funktionierte es. Wäre schön, wenn ihr das übernehmen würdet.

**Comment by RPiList** [comment]
Das ist interessant.

Auf welchem Gerät testen Sie das Image?

Weil in einer vmware Workstation VM heißt die Internet Schnittstelle in der
VM nicht eth0. Die lautet "ens33". Auf der getesteten Synology Diskstation
lautet die Schnittstelle "ens3".

Daher meine Frage.

Am Mo., 3. Feb. 2020 um 16:56 Uhr schrieb szaimen <notifications@github.com

**Comment by szaimen** [comment]
Tatsächlich heißt die Schnittestelle auch bei mir ens33:
![image](https://user-images.githubusercontent.com/42591237/73673848-a6360280-46af-11ea-8ff0-3598389d71a1.png)
und es funktioniert auch wenn man 
```
auto ens33
iface ens33 inet dhcp
```
zur erwähnten Datei hinzufügt aber eben nicht wenn sie komplett leer ist (wie das bei dem aktuellen Image standardmäßig der Fall ist).

**Comment by RPiList** [comment]
Das ist strange.

Sie nutzen offenbar VMware Workstation oder den Player und sitzen hinter
einer Fritzbox. Das ist im Grunde die Entwicklungsumgebung hier. Nur dass
unsere Fritzbox(en) im IP-Client-Modus arbeitet(en). Sie haben
wahrscheinlich nur eine FB, weswegen man den IP-Client Modus gar nicht
braucht.

Aber 90% der Umgebung ist gleich. Und trotzdem hängt sich die VM schon
auf???

Werde das 1-Load-Script dahingehend anpassen, dass die o.g. Daten
reingeschrieben werden. Schaden wird es nicht.

Grüße.

Am Mo., 3. Feb. 2020 um 18:05 Uhr schrieb szaimen <notifications@github.com

**Comment by szaimen** [comment]
Vielen Dank!

**Comment by RPiList** [comment]
oder vielleicht doch nicht.

Das die Datei leer ist, liegt daran dass in Ubuntu 18.04 LTS (das hier
benutzt wird) der Netzwerk-Manager, der die Datei früher genutzt hat
rausgeflogen ist.

D.h. die Datei wird nicht mehr gebraucht und alle Daten vom aktuellen
Netzwerk-Manager ignoriert.

Wir brauchen also eine etwas aufwändigere Lösung... :-)

Am Mo., 3. Feb. 2020 um 18:29 Uhr schrieb B. Trug <rpilist@gmail.com>:

**Comment by szaimen** [comment]
Also, solange die aufwendige Lösung noch nicht da ist, würde ich übergangsweise diese Lösung empfehlen, da sie zumindest bei mir funktioniert hat.

**Comment by sateffen** [comment]
Ich hab kein Ubuntu 18.04 hier, aber Ubuntu 18.04 Server nutzt normalerweise systemd-networkd. Prüfen kann man das, indem man einfach mal `networkctl` eingibt in der Shell. Das teilt einem dann mit, ob die Netzwerkinterfaces von systemd-networkd konfiguriert sind, oder nicht.

Am Desktop nutzt Ubuntu aber noch immer den NetworkManager, wegen der UI-Integration. Weil damit aber 2 Netzwerktools konfiguriert werden müssten, haben sie *netplan* entwickelt. Details sind im Ubuntuusers Wiki zu finden: https://wiki.ubuntuusers.de/Netplan/ Das Tool generiert die jeweiligen Konfigurationen in /etc/network/interfaces oder eben /etc/systemd/network automatisch, sodass alles fertig ist und die Config über mehrere Systeme geshared werden kann.

Wenn ich also richtig liege, solltet ihr mit einer einfachen netplan-Config das Problem so erschlagen können, dass alles automatisch richtig zusammenkonfiguriert wird beim boot, für den jeweils richtigen Manager. Das wäre auch der Fall, wenn jemand auf der VM plötzlich eine Desktop-Umgebung installiert, und damit auch den NetworkManager wieder mitinstalliert, weil netplan das alles automatisch richtig machen sollte, bei jedem boot.

**Comment by RPiList** [comment]
Alles richtig. Aber das Problem ist ja, dass genau das bei szaimen nicht
funktioniert.

Am Mo., 3. Feb. 2020 um 23:27 Uhr schrieb Steffen W. <
notifications@github.com>:

**Comment by RPiList** [comment]
bitte mal die Version unter http://sempervideo.de/piholeVM2002-2.zip testen.

Jetzt werden die Einträge in die Interfaces Datei geschrieben. Die Lösung
gefällt mir zwar nicht, aber schauen wir mal.

Am Mo., 3. Feb. 2020 um 19:05 Uhr schrieb szaimen <notifications@github.com

**Comment by szaimen** [comment]
Den Link kann ich leider nicht abrufen... bzw. es wird keine Datei gedownloaded.

**Comment by RPiList** [comment]
es muss http://sempervideo.de/svpiholeVM2002-2.zip  heißen. Grüße und Danke

Am Di., 4. Feb. 2020 um 00:46 Uhr schrieb szaimen <notifications@github.com

**Comment by szaimen** [comment]
Habs getestet. Es klappt jetzt ohne Probleme, vielen Dank!
Allerdings steht in der Datei die Information jetzt komischerweise standardmäßig 2x drin anstatt keinmal wies davor der Fall war.
![image](https://user-images.githubusercontent.com/42591237/73789938-fd1b0500-479f-11ea-9ecd-872ec6f10b2a.png)

**Comment by RPiList** [comment]
Fixed und updated. Danke für den Hinweis.

Am Di., 4. Feb. 2020 um 22:45 Uhr schrieb szaimen <notifications@github.com
