### ISSUE TITLE
Child-Protection Einträge?

### ISSUE THREAD

**Issue by servas089** [RPiList/specials#540]
Liebe Admin(s), 

ich nutze Eure Listen intensiv und bin äußerst happy mit Eurem Serivce und meinem eigenen Setup zu Hause. Für Homeoffice und Homeschooling lässt sich damit der aufgebaute IT Zoo erheblich besser managen. 

Mir sind jetzt in der Liste Child Protection 3 Websites aufgefallen. 
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection

Diese sind:
- kenfm
- corona-ausschuss
- epochtimes

Ich möchte klar sagen, dass ich nicht alles glaube und für richtig halte, was da steht. Aber meiner Meinung nach macht es Sinn, unterschiedliche Betrachtungswinkel auf die Dinge zu bekommen, um sich eine eigene und differenzierte Meinung bilden zu können. Und diese 3 Seiten leisten hierfür einen Wertbeitrag und sind nicht nur Content-Kopierer sondern sind journalistisch selbständig tätig. 

Bitte seht es mir nach, ich kenne hier nicht die Nettikett nach der man hier seine Wünsche für jeden einzelne Domain reinbringt. Meiner Ansicht nach gehören diese 3 Domains aus der Liste entfernt. 

Viele Grüße

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Nachricht. Grundsätzlich haben Sie sicher recht. Aber bei der Liste geht es ja um die Liste zum Schutz von Kindern und Jugendlichen. Daher auch der Name Child-Protection.

D.h. Sie - als offenkundig volljähriger Nutzer - betrifft die Sperrung nicht. Die Liste ist primär für Eltern gedacht, die nicht wollen dass Ihre Kinder auf solche Seiten zugreifen. Eltern die wollen dass ihre Kinder (weil z.B. 16+ Jahre) die von Ihnen angesprochenen verschiedenen Blickwinkel ebenfalls kennenlernen, können die Liste dann deaktivieren oder die Domains "whitelisten".

Die gleiche zugrundeliegende Problematik haben wir ja auch bei den Pornblock-Listen. Da befinden sich auch "Blümchen-Sex" (a.k.a. nicht Hardcore-Sex) Seiten drauf vertreten. Auch wenn man hier argumentieren könnte, dass die Kinder in der 8-9 Klassen in der Schule Sexualunterricht erhalten und daher grds. wissen "wie der Hase läuft".

Eine starre Liste kann beide Bereiche nicht für jede Zielgruppe perfekt abdecken. Insoweit liegt es in beiden Fällen im Ermessen der Eltern, wann sie Listen deaktivieren oder Domains freischalten. Imho wird damit dem Problem perfekt Rechnung getragen. 

Viele Grüße
