### ISSUE TITLE
Robustheit?

### ISSUE THREAD

**Issue by szaimen** [RPiList/specials#55]
An sich ist das ne super Idee mit der Pi-hole!
Aber Frage bzgl. der Robustheit:
wenn ich das Pi-Hole in der Fritzbox als lokalen DNS-Server angebe und das Pi-Hole mal neustartet wegen Updates o.ä., klappt dann die Namensauflösung nicht mehr?
Also kann ich in so einem Moment mit keinem Gerät mehr aufs Internet zugreifen aus Heimnetz heraus?

Bzw: wenn ich die Option in den Heimnetz-Einstellungen wähle, werden dann nur die lokalen Anfragen zum pihole weitergeleitet? Das hatte jetzt für mich so den Anschein.

**Comment by H4ckZ** [comment]
Also dass die DNS-Auflösung weiter funktioniert, obwohl der DNS-Server grade rebootet wirst du nicht sicherstellen können. Dafür müsstest du bei den Clients einen alternativen DNS-Server hinterlegen denke ich...

Wenn du bei der Fritzbox in den Heimnetzeinstellungen den PI hinterlegst wir die IP per DHCP an alle Clients ausgegeben. Die  lösen damit dann auch alles Namen auf. Nicht nur die lokalen.

**Comment by sateffen** [comment]
Für die Zeit des Reboot funktioniert die DNS-Namensauflösung über den Pi natürlich nicht mehr. Was du allerdings machen kannst (vorausgesetzt du weißt ungefähr, was du tust) ist, den Neustart zu planen, an einem Zeitpunkt, wo der DNS (höchstwahrscheinlich) nicht gebraucht wird.

Der Befehl `shutdown` ermöglicht das Planen eines Neustarts zu einem späteren Zeitpunkt. Du kannst mit `shutdown -r 04:00` einen Reboot für 4Uhr morgens (Raspi-Zeit) planen. `-r` bewirkt einen Reboot, das darfst du nicht vergessen, weil sonst fährt das Device einfach runter. Falls du dich vertan hast, oder den Reboot doch nicht willst, kannst du mit `shutdown -c` den Reboot auch "canceln".

Für mehr Details zum `shutdown` Befehl kannst du [hier schauen](https://linux.die.net/man/8/shutdown).

**Comment by AleksCee** [comment]
Wieso willst du ihn denn rebooted? Meistens stört ein einfacher reboot nicht mal, ich mache das ab und an mal wenn durch Pakete Updates auch ein neuer Kernel drauf kommt. Der reboot läuft so schnell, dass wohl lokale caches noch ziehen. Zumindest kann man sogar unterbrechungsfrei streamen während so einem reboot. Es ist ja auch nicht so, dass der Client gleich stirbt nur weil er mal 2-3 Sekunden keine Antwort vom DNS bekommt.
Will sagen, ein einfacher reboot hat bei mir noch nie zu einer Störung geführt und ich nutze ausschließlich den pihole als DNS, da die fritzbox keinen alternativen DNS per DHCP verteilen kann und ich den pihole nicht als DHCP Server umbauen wollte.

**Comment by RPiList** [comment]
> wenn ich das Pi-Hole in der Fritzbox als lokalen DNS-Server angebe und das Pi-Hole mal neustartet wegen Updates o.ä., klappt dann die Namensauflösung nicht mehr?

Selbstverständlich verhält sich das Pi-hole wie jeder andere Rechner/Dienst im Lan/Internet. Wenn man ihn abschaltet, stellt er seine Dienstleistung nicht mehr zur Verfügung. Bei einem normalen Bootvorgang. Der normale Bootvorgang ist jedoch so zügig, dass kein Gerät die Downtime merken wird. Es ist ja nicht so, dass alle Geräte ständig auf den Pi zugreifen. Sie greifen "nur" darauf zu, wenn Sie zum ersten Mal ne Verbindung zu einem neuen Server aufbauen. Eben dann, weil die Geräte dann die IP brauchen. Darum braucht man sich also keine Sorgen zu machen. 

> Also kann ich in so einem Moment mit keinem Gerät mehr aufs Internet zugreifen aus Heimnetz heraus?

Noch alle Geräte können problemlos auf das Internet zugreifen. Sie bekommen halt nur keine IP auf die sie zugreifen sollen.

Während das "Problem" des Bootens vernachlässigt werden kann, sollte man sich darüber im Klaren sein, dass es aber früher oder später Probleme mit der SD-Karte geben kann. Oder dem Pi selbst. Kram geht kaputt. Nicht weil der Pi schlecht ist, sondern weil viele Nutzer an der SD-Karte sparen oder ein mieses Netzteil benutzen.

Also was tun, wenn der Pi ausfällt. Kein Problem, in 60 Sekunden sind die Einstellungen in der Fritzbox wieder zurückgestellt und dann läuft alles wie früher. Mit all der schönen Werbung. :-)

Wer hier mehr Sicherheit braucht, kauft hochwertigen Kram oder einfach 2 SD-Karten. Die zweite Karte von der Ersten geclont. Gibts Probleme wird die Karte ausgetauscht und schon läuft wieder alles.

"Problem" ist eher, dass man selbst einige Minuten braucht um den Fehler zu lokalisieren. D.h. es sieht so aus, als wenn es kein Internet mehr gibt. Dann muss man zu allererst die Fritzbox/den Router anpingen. Bekommt man ne Antwort setzt man danach einen Ping auf 8.8.8.8 ab. Bekommt man Antwort, steht die Leitung zum Internet. Evtl. gibt einem aber auch die Router-GUI Feedback ob die Leitung noch steht. Steht also die Leitung, ist der Pi Schuld.

**Comment by szaimen** [comment]
@RPiList Wieso empfehlt ihr nicht es folgendermaßen einzurichten:
![image](https://user-images.githubusercontent.com/42591237/73671495-581f0000-46ab-11ea-870f-f24c43b04494.png)
Das hätte den großen Vorteil, dass wenn der lokale Pi online ist, dieser die Suchanfragen bekommt und falls er es nicht ist, wird es an den alternativen (einen öffentlichen weitergeleitet.) Damit hätte man die Probleme gelöst, wenn der Pi offline ist.

**Comment by AleksCee** [comment]
Ja, und für jede Anfrage die der pihole nicht beantworten will wird dann einfach der Alternative gefragt. Außerdem wechselt die Fritzbox den Standard DNS immer mal wieder zwischen den beiden hin und her. Da hast du dann Russisch Roulette mit der Werbung.

**Comment by szaimen** [comment]
> Ja, und für jede Anfrage die der pihole nicht beantworten will wird dann einfach der Alternative gefragt. Außerdem wechselt die Fritzbox den Standard DNS immer mal wieder zwischen den beiden hin und her. Da hast du dann Russisch Roulette mit der Werbung.

Das wäre aber sehr unlogisch. Ich frage mal beim AVM-Support nach.

**Comment by RPiList** [comment]
Ich nehme mal an, dass Sie in den LAN Einstellungen der Fritzbox nicht das
Pi-hole eingetragen haben. Dann wäre das Pi-hole unnütz, da Ihre
angebotenen Einstellungen den Geräten im Netzwerk regelmäßig den 1.1.1.1
DNS-Server anbieten würden. Es ist nicht so, dass immer der Primäre
angeboten wird und nur bei Ausfall der zweite Eintrag genutzt wird.

Es ist aber sicher richtig, dass wir die Nutzer in einem Video dafür
sensibilisieren sollten. Ich hatte es zwar noch nie, dass ein Pi einen
Hardware-Fehler hatte, aber die Karten sind schon mal nach Jahren
ausgefallen. Eine Backup-Karte zu haben ist also sinnvoll. Ferner braucht
der Anwender einen Plan, wie er einen DNS-Server/Pi-hole Ausfall
feststellen kann.



Am Mo., 3. Feb. 2020 um 17:38 Uhr schrieb Alexander Palm <
notifications@github.com>:

**Comment by AleksCee** [comment]
> Das wäre aber sehr unlogisch. Ich frage mal beim AVM-Support nach.

Dann guck mal unter Internet/Online-Monitor

![8D8B6D94-253C-45DF-8A21-0A57A39A1A9A](https://user-images.githubusercontent.com/2960655/73673928-ccf43900-46af-11ea-859f-9e3bc4f3fc71.jpeg)

Da wo (derzeit genutzt...) steht, das wechselt über alle 4 DNS.

**Comment by szaimen** [comment]
Wiegesagt, ich finde es unlogisch und habe beim Support nachgefragt. Vielleicht kann AVM das ja ansonsten evtl als Verbesserungsvorschlag aufnehmen...

**Comment by szaimen** [comment]
Also ich habs ein bisschen getestet:
wenn beide DNS-Server online sind, wird der Bevorzugte genutzt.
Wenn der Bevorzugte offline geht, wird der Alternative genutzt.
Wenn der bevorzugte wieder online geht, braucht es eine Weile, bis der wieder genutzt wird, aber die Fritzbox wechselt nach einer Weile definitiv wieder zum Bevorzugten.

Leider habe ich noch keine Langzeitbeobachtung zu dem Thema durchführen können aber mal schauen was der AVM-Support sagt.

**Comment by szaimen** [comment]
Und auch jetzt wird immer noch der bevorzugte genutzt.... keine Ahnung wie lange man das beobachten müsste, damit es repräsentiv ist...
Jedenfalls solange das pihole der standard-DNS-Server ist, wird Werbung zuverlässig geblockt.

Es scheint daher genau so zu funktionieren, wie ich es mir vogestellt habe. Aber wiegesagt: mal gucken was der Support sagt.

**Comment by sateffen** [comment]
Ich glaube hier geht was grundsätzlich schief :-D

Das Bild, welches oben gezeigt wird, ist **nicht** der DNS Server, welcher im Netzwerk verteilt wird, er ist der DNS-Server, welchen die Fritzbox **selbst** verwendet. Die Fritzbox selbst entscheidet gefühlt nach dem Zufallsprinzip, welchen der DNS Server es wählt. Die IP ist jedoch **nicht** die, welche im Netzwerk verteilt wird. Im Netzwerk verteilt wird die IP der Fritzbox selbst (in der Standard Config).

Übrigens: Bei meiner Fritzbox zumindest muss ich zwei unterschiedliche IPs hinterlegen. Wenn man faul ist, kann man den Raspi via LAN und WLAN mit der Box verbinden, dann hat man 2 NICs dran mit 2 getrennten IP Adressen (man kann auch virtuelle NICs nehmen, jadajadajada, aber das versteht potenziell nicht jeder).

Der DNS, welcher im Netzwerk verteilt wird, wird unter: Heimnetz -> Netzwerk -> Netzwerkeinstellungen, dann runterscrollen zu dieser Option: 
![grafik](https://user-images.githubusercontent.com/2326181/73692030-d0012080-46d3-11ea-80f1-cf5aef35f8f1.png) und dort kann für IPv4 und IPv6 jeweils der verteilte DNS eingestellt werden, für IPv4 sieht das dann so aus 
![grafik](https://user-images.githubusercontent.com/2326181/73692222-38500200-46d4-11ea-9ea9-21da6d4154c8.png)
Dort stellt ihr dann für den lokalen DNS die IP ein, welche euer Raspi hat. Es empfiehlt sich dem ne feste IP im Netzwerk zu geben, aber wenn das Ding sowieso immer an ist, sollte der DHCP-Lease bestehen bleiben (per Default wird eine IP erst nach 10 Tagen offline sein eines Gerätes auch einem neuen Gerät zugewiesen)
Da Netzwerke mittlerweile eigentlich immer IPv6 unterstützen, muss das logischerweise auch für IPv6 konfiguriert werden, was etwas komplizierter ist, aber machbar. Warum auch IPv6? Windows10 löst beispielsweise bevorzugt über IPv6 auf, soweit ich weiß.

Wenn ihr Windows habt, und wissen wollt, was der verteilte DNS-Server ist, könnt ihr einfach eine CMD öffnen und dort `ipconfig /all` eingeben. Ganz unten stehen dann die DNS-Server, welche verwendet werden. Dort wird in der Regel eure Fritzbox IP drinne stehen, und die leitet dann die Anfragen an ihre eigenen DNS-Server weiter.

@RPiList ihr könntet evtl diesen "alternativen" Weg auch mit in die Doku aufnehmen. Eventuell lohnt sich sogar ein Video dazu. Eventuell würde das einigen Leuten helfen. Die AVM Hilfe ist da nicht sooo dolle.

@szaimen Warum wird dieser Weg nicht als "Standardweg" erklärt, obwohls der "richtige" Weg scheint? Man muss plötzlich mit IPv6 rumspielen, weil das quasi in jedem Netzwerk aktiv ist. Wenn die Fritzbox den DNS-Relay übernimmt, konfiguriert man immer IPv4, weil die Box (noch) nicht mehr kann (zumindest soweit ich weiß). Daher ist es in der Regel einfacher nur den Box-DNS-Server zu ändern. Der von mir gezeigt Weg greift in dein Netzwerk ein. Wenn du nicht weißt was du tust, funktioniert danach potenziell gar nichts mehr. Um die Gefahr zu mindern ist dieser Weg sicherlich der nicht so bevorzugte Weg. Außerdem muss man bei dem Weg, den ich gezeigt habe, IPv6 selbst konfigurieren. Manche wissen, wie IPv6 funktioniert, aber der normale Nutzer weiß das nicht. Daher ist der Weg eben noch viel gefährlicher.

Und nein, IPv6 ist nicht einfach IPv4 mit längeren Adressen, es funktioniert wirklich anders.

**Comment by RPiList** [comment]
Am Mo., 3. Feb. 2020 um 22:48 Uhr schrieb Steffen W. <
notifications@github.com>:

> @RPiList <https://github.com/RPiList> ihr könntet evtl diesen
> "alternativen" Weg auch mit in die Doku aufnehmen. Eventuell lohnt sich
> sogar ein Video dazu. Eventuell würde das einigen Leuten helfen. Die AVM
> Hilfe ist da nicht sooo dolle.
>
Haben wir schon.

Wir und viele andere Nutzer haben Ihre Anleitungen nach dem Muster
erstellt.

>

**Comment by szaimen** [comment]
Also, ich hatte mit dem AVM-Support geschrieben und dieser hat zunächst noch einmal deutlich davon abgeraten den lokalen DNS-Server bei den DNS-Servern der Fritz!Box einzutragen. Der richtige Weg ist tatsächlich den lokalen DNS-Server auch dort in der Fritz!Box einzutragen.

Allerdings verhält sich die Option wenn man den lokalen DNS-Server als DNS-Server der Fritz!Box einträgt genauso wie ich es mir gedacht hatte: er verwendet standardmäßig den bevorzugten DNS-Server solange dieser erreichbar ist. Falls er es nicht mehr ist, wechselt die Fritzbox automatisch zum alternativen DNS-Server und nach einem undefinierten Zeitraum auch wieder zum bevorzugten zurück, falls dieser bis dahin wieder online ist. Allerdings ist die Option wiegesagt eigentlich nur für öffentliche DNS-Server gedacht, und soll angeblich nicht mit einem lokalen DNS-Server funktionieren, was ich aber nicht bestätigen konnte; es funktioniert in meinen Tests.

Was mich eigentlich dazu getrieben hatte den lokalen DNS-Server als bevorzugten DNS-Server der Fritz!Box einzutragen war jedoch, dass wenn der lokale DNS-server offline ist, Anfragen im Heimnetz überhaupt nicht mehr funktionieren, was ich auch dem Support mitgeteilt habe und dieser den Verbesserungsvorschlag, dass im Fall, dass der lokale DNS-Server offline ist doch bitte der DNS-Server der Fritz!Box verwendet werden soll, sodass Anfragen dann auch in dem Fall funktionieren, freundlicherweise an das Entwicklerteam weitergeleitet hat.

Als kurze Zusammenfassung: Also bitte weiterhin den lokalen DNS-Server auch als lokalen DNS-Server in der Fritzbox eintragen und hoffen, dass demnächst ein Softwareupdate kommt, was die Option failproof macht.
