### ISSUE TITLE
svpiHole als Proxmox Container?

### ISSUE THREAD

**Issue by bussio** [RPiList/specials#557]
Moin,
was hältst Du davon, svpiHole auch als Proxmox Container oder VM anzubieten?
Ich schätze, dass da sicherlich Interesse bestehen würde.

**Comment by RPiList** [comment]
Bin im Twitch-Stream auch schon danach gefragt worden. Bin mir nicht sicher, ob ein Proxmox-Container notwendig ist. Wer es schafft Proxmox zu installieren, schafft es sicher auch die Installation-Zeile (für Pi-hole) im Terminal einzugeben. :-)
