### ISSUE TITLE
Beim erstmaligen Starten nach Passwortwechsel fragen?

### ISSUE THREAD

**Issue by szaimen** [RPiList/specials#56]
Hallo,

ich weiß nicht ob es eine Option wäre, aber 123456 als Passwort ist doch ein bisschen zu einfach. Wäre es möglich, wenn man nach dem erstmaligen Starten der VM nach einem Passwortwechsel gefragt werden könnte? Wäre ne super Option. 

Alternativ wäre ein besseres Standardpasswort denke ich ganz sinnvoll. 

Zudem wäre es denke ich gut, wenn das Passwort auch in der Pi-Hole Benutzeroberfläche gesetzt wäre, um von vorneherein unerwünschte Einblicke zu verhindern.

Außerdem wäre es super, wenn diese Infos am besten auch in der read.me Datei erwähnt werden könnten.

**Comment by H4ckZ** [comment]
> ich weiß nicht ob es eine Option wäre, aber 123456 als Passwort ist doch ein bisschen zu einfach. Wäre es möglich, wenn man nach dem erstmaligen Starten der VM nach einem Passwortwechsel gefragt werden könnte? Wäre ne super Option.
>

Damit hast du grundsätzlich zwar recht, derzeit ist das Ganze aber ohnehin eigentlich nur zum Testen und eben noch nicht für unerfahrene Benutzer gedacht. Somit ist das derzeit meiner Meinung nach noch unnötig.
 
> Alternativ wäre ein besseres Standardpasswort denke ich ganz sinnvoll.
>
> Außerdem wäre es super, wenn diese Infos am besten auch in der read.me Datei erwähnt werden könnten.

Ein besseres Passwort ist natürlich ratsam, wenn man den PI als DNS-Server betreibt. Wenn man das allerdings im Image ändert und dann in die Readme schreibt ist das neue Passwort gleich wieder für die Katz

**Comment by RPiList** [comment]
Das Passwort zu ändern ist derzeit nicht in Planung.

Auf die Schnelle will mir da auch kein Bedrohungsszenario einfallen. Das ist ein Linux Rechner. Im LAN sind sonst wohl nur noch Windows Rechner und Android/IOS Geräte.

Wer schon selbst Linux-Rechner im LAN hat, lädt nicht unser Pi-hole runter. Der macht dass dann alleine.

Von Windows Rechnern bzw. Android/IOS wird der Pi nicht angegriffen. Da wird es auch keine Schadware geben, die in solch einem diversifizierten Netzwerk ausbreiten will. Habe noch nie von einer Schadware gehört, sie sich nach der Windows-Infektion noch nach Linux-Rechnern umschaut.

Aus dem Grund haben wir auch das Passwort aus dem Pi-hole rausgenommen.

Unabhängig davon ist es aber natürlich möglich, dass es Nutzern lieber ist, das PW zu ändern bzw. zu vergeben. Wenn wir soweit sind, wird es entsprechende Videos geben, die dann zeigen, wie der Nutzer das einfach machen kann.
