### ISSUE TITLE
"Richard Stallman's Personal Site" in pornblock3

### ISSUE THREAD

**Issue by zocker-160** [RPiList/specials#562]
Ich denke `stallman.org` hat nichts in `pornblock3` verloren oder hasst ihr ihn wirklich so sehr? ;) :P

**Comment by RPiList** [comment]
Ist nicht über unseren Crawler der Liste hinzugefügt worden. Kam von einer Dritt-Quelle. Viele Grüße und ist jetzt gefixt.
