### ISSUE TITLE
Over Blocking

### ISSUE THREAD

**Issue by Kenny2k8** [RPiList/specials#563]
Hallo,

mir ist aufgefallen das einige Einträge in mehreren Listen befindet.

 **0.r.msn.com**
 ```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock1:
   0.r.msn.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto:
   0.r.msn.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   0.r.msn.com
```
**telemetry.urs.microsoft.com**
 ```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto:
   telemetry.urs.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
   telemetry.urs.microsoft.com
```
**watson.microsoft.com**
 ```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto:
   survey.watson.microsoft.com 
   watson.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   survey.watson.microsoft.com 
   watson.microsoft.com 
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
   survey.watson.microsoft.com 
   watson.microsoft.com 
```

Mfg

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Meldung. Aber das Problem lässt sich nicht immer vermeiden. 
Die falschen Einträge in der Child-Protection Liste wurden absichtlich von uns eingetragen, um die Liste für "Sucher" uninteressant zu machen.

"Falsche" Einträge in der Malware Liste entstehen dadurch, dass Dritte Maintainer Tracking-Domains als Malware interpretieren und diese dann dort mit reinschreiben. Unser Crawler nimmt dann die Malware-Listen und fügt sie der Malware-Liste hinzu. 

Glücklicherweise ist das dem Pi-hole egal, weil es doppelte Einträge ignoriert bzw. löscht.

Viele Grüße
