### ISSUE TITLE
endcoronavirus.org

### ISSUE THREAD

**Issue by irgendwr** [RPiList/specials#565]
please remove `endcoronavirus.org`, this is also not fake science

**Comment by RPiList** [comment]
its not us placing it on the blocklist. You would have to fix that with our source for Corona-Blocklist. Greetings.

**Comment by irgendwr** [comment]
Moin,
ich verstehe nicht warum das Korrigieren von false-positives in diesem Fall plötzlich nicht zu eurer Verantwortung gehört.
Desweiteren kann ich die Domain nicht in den angegebenen Quellen finden. Einige davon lassen sich allerdings schwer oder gar nicht durchsuchen, bzw. zeigen nicht auf eine Liste.

**Comment by irgendwr** [comment]
Hi,
danke für die Antwort. Ich werde auch gern geduzt ;)
Die Liste scheint mir nicht besonders aktiv gepflegt zu sein (fast ein Jahr keine Updates und auf >1 Jahr alte issues nicht reagiert).

Issue habe ich erstellt: swimlane/deepdive-domain-data#3

> `endcoronavirus.org` [is] a global volunteer network, to provide information and guidelines for action to fight the COVID-19 pandemic. EndCoronavirus.org was among the first organizations in the United States to offer specific guidelines for policymakers, businesses, and individuals.

siehe:
- https://en.wikipedia.org/wiki/Yaneer_Bar-Yam#COVID-19
- https://en.wikipedia.org/wiki/New_England_Complex_Systems_Institute#Early_Warning_on_the_COVID-19_Coronavirus_Pandemic
- https://endcoronavirus.necsi.edu/ (verlinkt/leitet weiter auf `endcoronavirus.org`)
- https://twitter.com/endCOVID19

**Comment by irgendwr** [comment]
Hey, wie wär's, wenn man den Fehler in der Zwischenzeit in der Liste hier behebt?

Offensichtlich ist die angegebene Quelle seit einem Jahr nicht mehr maintained.

**Comment by RPiList** [comment]
erledigt. Grüße.
