### ISSUE TITLE
Outlook 365 Safelink Domain auf Blockliste

### ISSUE THREAD

**Issue by Zapfenechse** [RPiList/specials#567]
Die Domain: **_na01.safelinks.protection.outlook.com_** von der Blockliste **_Maleware_** ist meiner Ansicht nach falsch auf dieser Liste, da diese Bestandteil eines Sicherheitsfeatures von Outlook 365 ist.

Zitat von support.microsoft.com:
"Warum sehen die Links in meinen Nachrichten anders aus?

Nachdem Sie die erweiterten Sicherheitsfeatures aktiviert haben, sehen die Links in Ihren E-Mails eventuell anders aus. So sind beispielsweise die Links in einigen Nachrichten länger als gewohnt und enthalten Text wie **"na01.safelinks.protection.outlook.com"**. Dies steht im Zusammenhang mit den Prüfungen, die wir durchführen, um Sie vor Phishing-Angriffen zu schützen."

Quelle: https://support.microsoft.com/de-de/office/erweiterte-outlook-com-sicherheit-f%c3%bcr-office-365-abonnenten-882d2243-eab9-4545-a58a-b36fee4a46e2?ui=de-de&rs=de-de&ad=de

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Domain wurde von der Malware-Liste entfernt. Viele Grüße
