### ISSUE TITLE
crypto Liste - valide Crypto Domains geblockt?

### ISSUE THREAD

**Issue by EneOli** [RPiList/specials#571]
Ist es gewünscht, dass auch seriöse Domains wie z.B. bitcoin.org geblockt werden?
Also quasi alles zum Thema Cryptowährungen?

**Comment by RPiList** [comment]
Die Liste füttert sich aus mehreren Quellen die jeweils unterschiedliche Auffassungen über Crypto haben. Bitcoin habe ich mal gelöscht.

Viele Grüße
