### ISSUE TITLE
Blockliste Phishing-Angriffe blockiert Zugang zu Vodafone E-Mail

### ISSUE THREAD

**Issue by knispl** [RPiList/specials#574]
Die Blockliste Phishing-Angriffe enthält den Eintrag "www.vodafonemail.de", der den Zugang auf Vodafone E-Mail-Konten blockiert. Nach dem Login unter https://login.vodafonemail.de/ leitet Vodafone auf https://www.vodafonemail.de/ weiter. Der Zugriff auf das E-Mail-Konto funktioniert erst, wenn man im Pi-hole den Eintrag "www.vodafonemail.de" auf die Whitelist setzt.

**Comment by RPiList** [comment]
Vielen Dank für die Info.

www.vodafonemail.de wurde der Blocklist hinzugefügt und von der Phishingliste entfernt. Viele Grüße
