### ISSUE TITLE
https://www.sunshine.it/blacklist.txt sollte nicht mehr übereifrig sein

### ISSUE THREAD

**Issue by ckorn** [RPiList/specials#575]
In https://github.com/RPiList/specials/issues/570 wurde die Blockliste https://www.sunshine.it/blacklist.txt entfernt, weil sie zu übereifrig auch apple.com und twitter.com blockiert hat.

Habe unter info@sunshine.it den Kontakt angeschrieben und die Domains wurden aus der Liste entfernt.

Die Blockliste sollte also wieder sauber sein und kann aufgenommen werden.

**Comment by Zelo72** [comment]
Die Liste enthält Unmengen an *.googlevideo.com Domains. Wohl ein Versuch Youtube-Videowerbung mit DNS zu blocken, was nicht funktioniert. Mit dieser Liste starten die meisten Youtube-Videos nicht mehr. Auch sonst sind dort Domains auf der Liste, die man nicht blocken sollte. Aus meiner Sicht absolut nicht zu empfehlen.

**Comment by RPiList** [comment]
Ja, denke auch, wir lassen die Liste erst mal raus. Viele Grüße.
