### ISSUE TITLE
Invalid entries

### ISSUE THREAD

**Issue by sateffen** [RPiList/specials#58]
Hey,

ich benutze diese Listen als Basis für meinen DNSCrypt-Proxy und merge die Listen mit meinem eigenen [Merger](https://github.com/sateffen/dnscrypt-proxy-blacklist-generator), der nebenbei noch die URLs validiert und die Listen vereinfacht (ich benutze den DNSCrypt-Proxy aufn Pi als zentralen DNS fürs Netzwerk statt dem PiHole).

Dabei sind folgende Domains durch die Validierung gefallen und könnten von [der notserious](https://github.com/RPiList/specials/blob/master/notserious) Liste entfernt werden. Eventuell müssen die Domains auch nur normalisiert werden, das kann ich nicht einschätzen.

```
cpgtstream4.com/s26r/
www.cpgtstream4.com/s26r/
dailymetcon.it/M/
www.dailymetcon.it/M/
dandridgefumc.org- Bekleidung
lightminds-shop. de
mincil.de/shopserver/shops/s008349/
www.mincil.de/shopserver/shops/s008349/
mincil.deshopservershopss008349 (spuckt mein Skript nicht aus, hat aber eine invalide Top-Level-Domain)
moyucubeshop.com/de/
www.moyucubeshop.com/de/
rg-kegler@t-online.de
Sbz-Badguide. De
vitrogarten de
```

**Comment by RPiList** [comment]
Vielen Dank für die Mühen.

Einträge wurden korrigiert.

Glücklicherweise haben diese Fehler nicht zu großen Fehlfunktionen geführt. Da Pi-hole einmal pro Woche selbst Updates zieht, bekommen alle Nutzer die korrigierte Version in den nächsten Tagen automatisch mit.

Vielen Dank und viele Grüße
