### ISSUE TITLE
www.cell.com (scientific press/journal) in pornblock3 list

### ISSUE THREAD

**Issue by fallmake** [RPiList/specials#580]
RPiList/specials/master/Blocklisten/pornblock3 contains an entry for "www.cell.com" which isn't a porn site, but a publisher of the renowned scientific journal "Cell". It should be removed from the blocklist.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für den Hinweis. Domain wurde von der Liste entfernt.

Viele Grüße
