### ISSUE TITLE
Weitere Domains für die Blocklisten

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#582]
Hallo, hier weitere Domains für die Blocklist:

`ytbgamer.space` leitet nur zu viren seiten weiter. Beispiel link: `https://ytbgamer.space/HackCheat`

`mfilecloud.com` fake filehoster. Beispiel: `https://mfilecloud.com/bWZoYWp1bWlfaHlheGE%3D`
`xsharenode.com` fake filehoster. Beispiel: `https://xsharenode.com/dl/9q890r6o980n3956o82r1p2r45orp3sn`
`d00wnl0ads.ru` fake filehoster mit virus
`uh417.pro` Virus. Beispiel: `https://uh417.pro/21V9G6?extra_param_1=fortnite`

Fake Foren (Jedes anklickbare Element leitet nur zu weiteren unseriösen Seiten weiter) :
`krylovo-osa.ru` 
`taxibc.ru`
`vovfashion.ru`
`acersupport.ru`
`tattookirov.ru`
`doctoraaa.ru`
`reverancedc.ru`
`bestbonda.ru`
`n-fisher.ru`

Leitet nur zu müll seiten weiter:
`g20-publications.org`
`maxhacks.pro` Beispiel: `https://maxhacks.pro/fortnite`

Fake Flash update:
`online-protection.net`

unseriös:
`stunapps.com`
`fortniteaim.win`

**Comment by RPiList** [comment]
Vielen Dank für die Info... Domains wurden in die entsprechenden Listen geschoben. Viele Grüße
