### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#587]
planitpoker.com
www.planitpoker.com
planitpoker.app
www.planitpoker.app

sind keine Gambling Seiten, ist die digitale Version des Planning Poker: https://www.mountaingoatsoftware.com/agile/planning-poker

Siehe auch #585

**Comment by RPiList** [comment]
Vielen Dank, ist jetzt auf der Whitelist und Gambling wurde gefiltert.
