### ISSUE TITLE
pr0gramm.com in der crypto liste

### ISSUE THREAD

**Issue by Luzifix** [RPiList/specials#588]
Hi,

in der crypto Liste sind die Domains:
- pr0gramm.com
- www.pr0gramm.com
- app.pr0gramm.com
- img.pr0gramm.com
- thumb.pr0gramm.com
- vid.pr0gramm.com
- m.pr0gramm.com

das pr0gramm hat schon seit einiger Zeit nichts mehr mit mining am Hut und wenn war dies nur über die Domain miner.pr0gramm.com erreichbar. Weshalb ich darum bitten würde diese Domains wieder aus der liste zu nehmen. 

Siehe auch #232

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden von der Liste entfernt. Viele Grüße
