### ISSUE TITLE
vortex-win.data.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [RPiList/specials#59]
Es werden
- v10.vortex-win.data.microsoft.com
- us.vortex-win.data.microsoft.com
- eu.vortex-win.data.microsoft.com

geblockt, jedoch ist davon nur die erste für Telemetrie zuständig.
Die us. sowie eu. Domain ist länderspezifisch für **Microsoft Defender Advanced Threat Protection** und sollte daher nicht geblockt werden.

Quelle: https://docs.microsoft.com/de-de/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpunkte

**Comment by RPiList** [comment]
Wir sind mit der Liste der Empfehlung des BSI gefolgt.

Ich schätze der MS-Defender funktioniert trotzdem? Würde mich wundern, wenn das dem BSI entgangen wäre.

Gibt es denn schon Berichte, nachdem sich das Blocking negativ auf den MS-Defender auswirkt?

**Comment by beerisgood** [comment]
Der normale Defender wird davon nicht betroffen sein, da dies das eigentliche Programm ist. Hier geht es um den erweiterten Schutz.

Das BSI listet die Domain nur auf. Sie schreiben nicht was eine Blockade bewirkt oder was für Daten über die Domain gehen.

Ich vertraue daher der Microsoft Dokumentation das es gebraucht wird.

**Comment by beerisgood** [comment]
@RPiList

**Comment by RPiList** [comment]
Wir lassen die Domain erst mal drin und berufen uns - mangels eigener Erfahrung - erstmal aufs BSI. Das MS die Domain für "benötigt" hält ist klar. Das sagen sie auch von allen anderen Domains die hier geblockt werden.
