### ISSUE TITLE
Remove stats.lineageos.org

### ISSUE THREAD

**Issue by DiamantTh** [RPiList/specials#591]
kA ob LOS da was hinschickt..
Beschreibung der Seite: mehr oder weniger eben ne Statistik aus Welchen Ländern/Welche Geräte eben häufig genutzt werden hierfür..
Ob die Domain in Maleware Sinn mach denke ich nicht, wenn dann eher was für ne Telemetrieliste..

PR erstellt, siehe https://github.com/RPiList/specials/pull/590

MfG

**Comment by RPiList** [comment]
Ist nicht von uns auf die Malware Liste gesetzt worden.
