### ISSUE TITLE
Proofpoint urldefense are not Phishing

### ISSUE THREAD

**Issue by madzodiac** [RPiList/specials#593]
I was wondering why urldefense.com , urldefense.proofpoint.com and www.urldefense.com are on the phishing list.
These URLs are malware and phishing countermeasures and not phishing itself.
URLdefense is part of the Proofpoint corporate-grade TAP offering https://www.proofpoint.com/us/products/advanced-threat-protection/targeted-attack-protection.
I strongly suggest to remove these from the phishing list.

**Comment by RPiList** [comment]
Hi madzodiac,

thankx for letting us know. Domains are removed from our Phishing-List. But be advised: Our list is just an aggregation of public internet services, that list these domains as phishing. So there are most likely lots of other lists like our, still listing these domains.

Greetings
