### ISSUE TITLE
Overblocking auf Phishingliste

### ISSUE THREAD

**Issue by HorayNarea** [RPiList/specials#596]
`p17.zdusercontent.com` ist eine Domain die von [Zendesk](https://www.zendesk.de/) unter Anderem für die hochgeladenen Anhänge verwendet wird, sie steht aktuell auf der Phishingliste. Das bricht z.B. die Support-Seite von Sipgate so dass man seine eigenen einmal hochgeladenen Anhänge nicht mehr runterladen kann weil sie auf dieser Domain liegen…

Ich denke das ist overblocking und bitte um Entfernung :D

**Comment by RPiList** [comment]
Vielen Dank für die Info. Sollte jetzt gefixt sein. Viele Grüße
