### ISSUE TITLE
Real-Markt.de wird geblockt

### ISSUE THREAD

**Issue by taker218** [RPiList/specials#600]
Hab heute festgestellt, dass die Seite real-markt.de geblockt wird.
Das ist die neue Seite der noch vorhandene Real Ladengeschäfte nach der Übernahme durch Kaufland von real.de

Die wird auf der Liste malware und Phishing-Angriffe geblockt:

> Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
> real-markt.de
> www.real-markt.de
> Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
> www.real-markt.de

**Comment by RPiList** [comment]
vielen Dank für den Hinweis. Ist jetzt gefixt.
