### ISSUE TITLE
go.fluidigm.com in maleware

### ISSUE THREAD

**Issue by IC-Fumasu-DEU** [RPiList/specials#601]
Fluidigm ist ein international agierendes Biotech-Unternehmen aus Übersee und steht wahrscheinlich zu Unrecht auf der Maleware-Liste.

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  go.fluidigm.com
```

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt. Viele Grüße
