### ISSUE TITLE
notebooksbilliger.de

### ISSUE THREAD

**Issue by LeHoangDev** [RPiList/specials#602]
Hallo,
warum ist den notebooksbilliger.de / www.notebooksbilliger.de auf der notserious Liste?

**Comment by RPiList** [comment]
Hi, vielen Dank für den Hinweis.

Ist ein false positive und wird umgehend entfernt. Viele Grüße

**Comment by KastenKlicker** [comment]
Steht immer noch drinnen. Habe die Listen zu einem bereits existierendem Pi Hole heute hinzugefügt.
Das Problem lässt sich für jeden einfach beheben indem man notebooksbilliger.de unter RegEx whitelistet.
