### ISSUE TITLE
Switch to a different code hosting solution.

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#606]
With the buy out of GitHub from Microsoft, and the recent [controversy](https://mstdn.social/@foreverxml/106534142484955195) regarding [GitHub Copilot](https://cybre.space/@tindall/106539167944483388) it would be great to move the project to a different provider. 
Something like [Codeberg](https://codeberg.org), that is built using open source software and is [backed by a non-profit](https://join.codeberg.org/).
Or [git.stuxhost.com](https://git.stuxhost.com/) (operated by [@stux](https://mstdn.social/@stux)) and not Github who is owned by a multi billion dollar company that makes money analyzing your data.

The (then invalid) links in the block list settings could be updated with an update of the image.

**Comment by benjaminwolkchen** [comment]
The official GitHub copilot website is: [copilot.github.com](https://copilot.github.com/)

**Comment by RPiList** [comment]
Switching to a different plattform would be a difficult task, which should not be done hastily. 

Let's see how this 'Copilot' turns out... I don't want to jump to a different plattform, and minutes later Microsoft reverses course. Wouldn't be the first time...

Further I will check if there is a possibility to inform users of changing URLs. Otherwise nobody will notice us moving...

So I will look out for valid alternatives and copy this project to them - as backup.

If Copilot is the problem it appears right now, we could switch easily.

Hopefully, we can learn from other projects, if they are switching as well. Greetings.

**Comment by ITaluone** [comment]
Why not just move to gitlab.com?

gitlab is fully FOSS..

**Comment by benjaminwolkchen** [comment]
My concern is, because Gitlab.com is a profit-oriented company that somehow has to make money, the possiblyis there, that they also develop a "rival" to GitHub Copilot to stay competitive.

Codeberg doesn't have to stay competitive with anyone, because it is backed by a non-profit.

**Comment by ITaluone** [comment]
Would possibly fit into this series: [SemperVideo Proxmox](https://www.youtube.com/playlist?list=PL3-bM7Aq1pUpSTIQiffrCiR29Z-SCS9wd)

Wäre eine eigene Gitlab-Instanz nur für die PiHole-Listen eine Option? :)

**Comment by benjaminwolkchen** [comment]
GitHub also makes money by charging you:
[![Screenshot 2021-08-11 at 10-23-10 Pricing · Plans for every developer](https://user-images.githubusercontent.com/42138517/128995677-88fd9027-ff35-45c4-801d-111f922bce74.png)](https://github.com/pricing)

That was not my point.
GitLab can stay profitable, but with the developer experience that GitHub offers with Copilot, they somehow have to stay competetive.

They could very well survive without it, but I don't think they won't do anything.

> Would a separate Gitlab instance only be an option for the PiHole lists? :)

That would be great, but I don't think that it is the best option now, because someone has to start paying for it.

**Comment by RPiList** [comment]
Hi,

also hier noch mal eigentliche Problem dargestellt.

Das Github und andere Geld verdienen müssen und wollen ist nicht das Problem. Sollen sie auch, da sie Freeloader wie uns mit durchschleifen.

Wenn Copilot jetzt ein Weg ist, das Projekt kostenlos zu halten, dann ist es nicht verwerflich. Zumal der "Code" den wir zu dem Projekt beisteuern, für das Projekt wertlos ist. Es ist ja überhaupt kein Code sondern nur eine Auflistung von Domains.

Die Community ist aber wohl wg. der rechtlichen Komplikationen zerstritten. Die einen sagen... "Ja, jeder soll meinen Code nutzen, deswegen ist er ja OSS" und andere sagen... "ja, jeder soll meinen Code nutzen aber nur so wie ich es will..."

Wenn Copilot so strittig ist, wird die FSF sicher auch Klage erheben. 

Deswegen aber die Plattform zu wechseln löst das Problem überhaupt nicht. Dann wandern jetzt alle Projekte zu Gitlab, welche in 3 Jahren das Gleiche machen, weil sie dem Ansturm nicht standhalten können.

Mein "Hauptproblem" besteht in der wechselnden URL. Von Erzählungen (in den Kommentaren) weiß ich, dass viele Zuschauer/Nutzer z.B. ein Pi-hole bei Family/Oma/Bekannten installiert haben. Die müssen dort überall hinrennen und dann die neuen URLs einpflegen. D.h. wenn wir "wandern" müssen die Listen irgendwo liegen, wo sie nie wieder wandern müssen. Oder im Pi-hole gibt's 'ne Möglichkeit die URLs der Listen remote zu importieren. Aber das wird nicht vor Pi-hole 6 passieren.

Insoweit werden wir das einfach noch etwas beobachten. Viele Grüße

**Comment by DanielRamp** [comment]
> Mein "Hauptproblem" besteht in der wechselnden URL. Von Erzählungen (in den Kommentaren) weiß ich, dass viele Zuschauer/Nutzer z.B. ein Pi-hole bei Family/Oma/Bekannten installiert haben. Die müssen dort überall hinrennen und dann die neuen URLs einpflegen. D.h. wenn wir "wandern" müssen die Listen irgendwo liegen, wo sie nie wieder wandern müssen. Oder im Pi-hole gibt's 'ne Möglichkeit die URLs der Listen remote zu importieren. Aber das wird nicht vor Pi-hole 6 passieren.

1. For me this looks as a reason to start (a mirror) on another platform as early as possible, so people can update the list over time.

2. Also a service (for other people) like this should be somewhat remote controllable, here e.g. over vpn, ssh or even the pi-hole webui (probably worst solution)

**Comment by RPiList** [comment]
Ein Umzug wird erst mal verschoben. Die Befürchtungen haben sich noch nicht bewahrheitet. Sollte es dazu noch kommen, steht die Frage des Umzugs aber automatisch auf der Matte. Viele Grüße
