### ISSUE TITLE
liznufmiti.duckdns.org

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#619]
The website downloads an APK file that is probably malicious.

![Screenshot_20210729-125008](https://user-images.githubusercontent.com/42138517/127479393-a8fbfdee-d448-412a-8010-0538b60d893e.png)

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde der Spam-Liste hinzugefügt. Viele Grüße
