### ISSUE TITLE
Ein server mit Crypto Spam Adressen 

### ISSUE THREAD

**Issue by cookiegruemel** [RPiList/specials#621]
KA ob das in die Issures gepostet werden soll aber ich poste es Mal hör hin. wenn das falsch ist sagst mir einfach.

https://lombardofinanci.com/nw89etys6/?pname=Bitcoin%20Advance&reduri=track.francoreviews.com&cep=f0Wsam4gPR65Ff4dgqIswcTd_zFpTl4rXTIRNdL34Nz-ilkym_2jQlhIG1YKbtbGrwVR21Vwx6JXN1lB4isuXZ65CcaijKw-SXggyhYsFYud9OCJ0dMJW1laWUPFT9YkZPAbUV4ODCzs-ldgSmnOnQQxXJMdTYYBA5KEWpbtKusYTrxHFKfikO8OHMr4YnFdtuHu0l6dEdeVtTUDrwrU_HnxBScEB5akpP9PWBCVvNmIkMeewgE0cuqBK-D9-WuZ-MC7b13wdz4NJGRw5LvflIDFaF93ZEWte1IjIYJF2gSIXbot4vRK8m-BWBdiLjz3zrXU24kQo7M5ZuI3clsLfSJIAfnncuTTxKaXGwEXT1FgUItB1YGH5XmIxp7jUwDFGVXG2_jZjHDAQLRVwo2aZPCuTdfinVsfM1KydsS0L_qqgppjZpWZOalwm7aXPOPQnUCffr4W6uqaeHOoMpaVNu6K5_CGpuNPBMqtQ9svZVhzj0ZcvI__GmImS3V7CI_1Gio9CKDTNzTlau5weKUIa81W0O9r3H2SkrunVn1PEKg&lptoken=16b127c5822c38de0283&zoneid=D5J8OGM86A&campaignid=179577&geo=DE&Name=Omri_MOB_DE_China_launches_Crypto_DE_BTC_AdvanceHillTop_POP_BK&price=0.003000&token=is1a2detcetxdftzossh

bzw die domain lombardofinanci.com

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Beide Domains wurden hinzugefügt. Viele Grüße
