### ISSUE TITLE
Mal wieder domains zum hinzufügen

### ISSUE THREAD

**Issue by 10k-resistor** [RPiList/specials#624]
Hallo,

ich bin durch zufall (oder ich bin zu blöd google.de einzutippen ,da bin ich mir nicht ganz sicher 😜) auf folgende Domains gestossen:

_newswireglobals.com
ggogle.de
ggogle.com
explorr.net_

Könntet ihr die bitte hinzufügen

Vielen Dank und Viele Grüße
10k-resistor

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis. Domains wurden der Liste hinzugefügt. Viele Grüße
