### ISSUE TITLE
Pi-hole funktioniert nicht (Fritzbox 6490)

### ISSUE THREAD

**Issue by arca20** [RPiList/specials#63]
Leider funktioniert der pi-hole nicht richtig bzw. nur über andere Einstellungen.

Mit dem lokale DNS Einstellungen läuft es nicht,man muss statt dessen via Internet -> Zugangsdaten -> DNS -> Andere DNSv4-Server verwenden.

Oder muss man zusätzlich auch was beim Pi-Hole einstellen.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für das Feedback.

Ob man den Pi über die "lokalen DNS-Einstellungen" oder über die
Internet-DNS-Einstellungen anspricht, ist dem Pi eigentlich egal. Er sollte
immer gleich reagieren.

Sicher, dass Sie die neueste Version benutzt haben und dass Sie den ersten
Reboot abgewartet haben?

Da würde mich interessieren, wie die IP-Einstellungen im Pi-Hole aussehen.

Vielen Dank und viele Grüße.

Am Do., 2. Jan. 2020 um 18:44 Uhr schrieb arca20 <notifications@github.com>:

**Comment by arca20** [comment]
Image ist die 2001 und die Fritzbox Einstellungen sehen genau, wie bei den Screenshots aus.

Hier noch mals die Einstellungen vom PiHole 

![image](https://user-images.githubusercontent.com/33495437/72220268-35d40f80-354f-11ea-8c88-4af91585206a.png)

**Comment by RPiList** [comment]
Also aus den Screenshots lässt sich leider nichts erkennen.

**Comment by arca20** [comment]
Nach einem Neustart des Routers ging alles von selber.

**Comment by arca20** [comment]
Erledigt
