### ISSUE TITLE
mrgugu.com / false positive in "malware" category

### ISSUE THREAD

**Issue by andreasbrett** [RPiList/specials#631]
Please remove mrgugu.com from the malware category (https://github.com/RPiList/specials/blob/master/Blocklisten/malware). It is an online shop for (extraordinary/weird) clothing and doesn't host malware.

**Comment by RPiList** [comment]
Domain has been reported as a bad player for tracking. Thats the reason it is still listed. Some lists one the internet regard tracking as malware... so it eventually lands in our list.
