### ISSUE TITLE
Remove(2.bp.blogspot.com)

### ISSUE THREAD

**Issue by DiamantTh** [RPiList/specials#632]
Ob man die bedenkenlos Entfernen kann?
Domain: 2.bp.blogspot.com(Blogger,Google)

Brauchst noch nen Allgemeinen Grund?

MfG

**Comment by RPiList** [comment]
Wird von ZoneFiles (https://zonefiles.io/f/compromised/domains/full/) immer noch als kompromitiert geführt. Viele Grüße
