### ISSUE TITLE
False positive www.strato.de

### ISSUE THREAD

**Issue by FibreFoX** [RPiList/specials#635]
Der Commit https://github.com/RPiList/specials/commit/b3c706e7efc1796df04559deeeeee53f6c33fa1b enthält für die Blockliste `malware` (https://github.com/RPiList/specials/blob/master/Blocklisten/malware) leider die gewerblich genutzte normale Domain `www.strato.de`. Vermutlich ist diese durch das Auto-Update dazugekommen, obwohl diese nicht auf der Liste hätte stehen dürfen.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.

Domain wurde entfernt.
