### ISSUE TITLE
False Positive accounts.binance.com

### ISSUE THREAD

**Issue by madebyTimo** [RPiList/specials#638]
Die Blockliste malware (https://github.com/RPiList/specials/blob/master/Blocklisten/malware) enthält die Domain accounts.binance.com, obwohl diese zu Binance gehört und Binance meines Wissens nach keine Malware verbreitet.

**Comment by f0o** [comment]
More than 5k `.binance.com` addresses are listed in the malware list; How is one of the leading crypto exchanges a malware host?

**Comment by RPiList** [comment]
I don't know binance.com but there might be source lists, that treat any kind of crypto as malware. Will delete them and we will see if they got listed again. Greetings
