### ISSUE TITLE
False positive nanopool.org

### ISSUE THREAD

**Issue by FibreFoX** [RPiList/specials#639]
Hi,

erneut ist eine nicht-malware Domain auf die Blockliste "malware" gelangt. Bei der Domain "nanopool.org" handelt es sich um eine Crypto-Mining-Seite, welche die Übersicht verfügbarer Mining-Pools auflistet.

Wenn ich mir aber mal die Einträge etwas genauer anschaue, scheint hier irgendein Programm diese Domains zu generieren, was zu einem hohen Grad an false-positives führt.
![grafik](https://user-images.githubusercontent.com/1042579/131389251-b96f4e03-4149-4ccf-9f36-83cccdbc553b.png)

Vielleicht wäre es notwendig hier die Qualität der Quelle für Malware-Domains nochmal zu überprüfen.

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. 

Zonefiles.io führt eine Liste kompromitierter Domains, welche in unsere Malware-Liste einfließt. 

Wenn es "nur" ein Programm wäre, dass fake Subdomains generiert, wäre das nicht so tragisch. Das wären dann ungültige Domains die nie von einem Benutzer aufgerufen werden.

Ferner ist seltsam, dass Zonefiles.io derzeit nur eine Domain, "xmr-eu1.nanopool.org" als schädlich listet.

Das kann bedeuten, dass die anderen Einträge historisch sind oder von einer anderen Lieferliste stammen. Das alte Schadware Domains in unseren Listen verbleiben ist aber durchaus (von uns) gewollt, da einige Player im Internet diese Schadware-Subdomains nur routieren.

Wie dem auch sei: Alle nanopool.org Domains werden erst mal entfernt. Alle bis auf die o.g. weil die derzeit noch als schädlich gelistet ist. Viele Grüße

**Comment by FibreFoX** [comment]
Mir war nicht bewusst, woher die Domains kommen ;) steht bestimmt irgendwo, wo ich das überlesen hab.

Vielen Dank für die schnelle Reaktion 😸

**Comment by RPiList** [comment]
Unsere Quellen stehen auf der entsprechenden Infoseite hier. Aber welche von diesen Quellen "nanopool.org" blockiert hat, steht nirgends. Das konnte ich nur sehen, weil ich dann einfach hingehe und alle Drittlisten laden lasse und dann mit Grep durchsuche. Viele Grüße
