### ISSUE TITLE
CBN/Compal/ConnectBox (Vodafone/Unitymedia) 

### ISSUE THREAD

**Issue by PsyEng** [RPiList/specials#64]
Die Compal Router lassen sich wunderbar über die WebAPI verwalten und einstellen. DHCP kann man bei der ConnectBox so wunderbar deaktivieren, sollte genauso für die VodafoneBox gehen. Falls gewünscht, könnte ich ein Python Script bereitstellen, welches dann über die VM ausgeführt werden könnte, um so den Pi als DHCP Server zu verwenden. Der DNS lässt sich meines Wissens dadurch leider nicht einstellen, bzw. habe ich dies noch nicht geschafft.

**Comment by RPiList** [comment]
Es dürfte für uns problematisch sein, wenn wir Skripte anbieten, die wir
nicht selbst getestet haben und für die wir auch kein Video anbieten können.

Insoweit nehmen wir lieber Screenshots soweit möglich.

Vielen Dank und viele Grüße.

Am Fr., 3. Jan. 2020 um 23:38 Uhr schrieb PsyEng <notifications@github.com>:

**Comment by PsyEng** [comment]
Danke für die Antwort. Etwas ähnliches hatte ich erwartet und vollstes Verständnis. Falls du/ihr dennoch an einen der Router kommen solltet, um das Skript nachzuvollziehen, kann ich es dir/euch gerne zur Verfügung stellen, einige Zuschauer hatten hieran nämlich Interesse, aber ich bin da voll deiner/eurer Meinung.

Schöne Grüße und danke für das Projekt.
