### ISSUE TITLE
False positive www.flexpool.io

### ISSUE THREAD

**Issue by madebyTimo** [RPiList/specials#640]
Hey, die Blockliste malware (https://github.com/RPiList/specials/blob/master/Blocklisten/malware) enthält die Domain  www.flexpool.io, welche zu einem Mining-Pool gehört. Meines wissens nach wird darüber keine Malware verbreitet.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
