### ISSUE TITLE
office.org

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#644]
Office.org verbreitet modifizierte Installationsdateien für Apache Openoffice.

Die Originalinstallationsdatei hat folgenden SHA256-Hash: `CFC7DFBBE8AB6F4ED8A1E6CE3759D26536CD5A8A200508F5C64E7838E7CC088D`

Die Datei von Office.org (selbe Version und Dateiname) hat hingegen folgenden SHA256-Hash: `1045EB8B64F0040E6659EE760D4F778E47B4A60A3E5DFB7F7544AC9C0B6F9E7C`

Die Datei wurde so verändert, dass der Installer nach einer E-Mail Adresse fragt. (Siehe Bild)
Außerdem wurde bei meinem Test nach der Installation in einer VM der Firefox Updater vom Setup gestartet.

![prompt1](https://user-images.githubusercontent.com/42138517/132665879-668f96f2-a846-47fb-8799-7918d673a48a.png)

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde hinzugefügt. Viele Grüße
