### ISSUE TITLE
False positive bugmenot.com

### ISSUE THREAD

**Issue by ckorn** [RPiList/specials#645]
Hallo,

seit dem commit e34c256126948f86a4921f5f6245adbadae7b6e8 wird bugmenot.com blockiert.
Ich hatte die Seite bisher immer genutzt um mich mal schnell bei Seiten anzumelden und keinen eigenen Account erstllen zu müssen.

Hat die Seite wirklich Schadware verteilt? Dann ist der Block natürlich ok.

Kennt in dem Fall jemand ein gute Alternative?

**Comment by RPiList** [comment]
Bugmenot hatte wohl Probleme, die aber inzw. erledigt sind. Insoweit wird die Domain bei den entsprechenden Diensten auch nicht mehr geführt. Wurde jetzt auch bei uns gelöscht. Vielen Dank für die Info. Viele Grüße
