### ISSUE TITLE
Pihole problem

### ISSUE THREAD

**Issue by Stenafo** [RPiList/specials#646]
Hi, a moment ago I did the gravity update on my pihole, I am given this error:
```
  [i] Target: https://github.com/RPiList/specials/blob/master/Blocklisten/Win10Telemetry
  [✓] Status: Retrieval successful
  [i] Analyzed 13 domains, 13 domains invalid!
      Sample of invalid domains:
      - content="github.com">
      - content="github.com">
      - data-target="input-demux.source"
      - data-targets="input-demux.sinks"
      - cache-key="v0:1617947252.3749518"
  [i] List stayed unchanged
```
I don't understand if it's a list or pihole problem

**Comment by AleksCee** [comment]
Hi, it‘s a layer 8 (User) Problem. You have use the „html“ version of the list but you have to use the raw Version of the Target url  like: https://github.com/RPiList/specials/raw/master/Blocklisten/Win10Telemetry in you’re case.

**Comment by RPiList** [comment]
Wie @AleksCee sagte, benutzen Sie den falschen Link im Pihole. Die Liste selbst ist sauber. Viele Grüße
