### ISSUE TITLE
false positive: textnow.com in notserious list

### ISSUE THREAD

**Issue by espressoelf** [RPiList/specials#651]
Listed on [notserious](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious) but is neither a fake shop, nor does it use predatory tactics. Basic usage of the service is free and doesn't require payment information. Non-free options are clearly marked as such with a price (see "How It Works" at the bottom). They also provide proper contact information (see "Contact"; address also listed in their ToS and Privacy Policy).

**Comment by RPiList** [comment]
Thx for letting us know. Its fixed now. Greetings
