### ISSUE TITLE
false positive: get.atmos.phe.re in malware list

### ISSUE THREAD

**Issue by ch4d1** [RPiList/specials#652]
Just a redirect URL for the Nintendo Switch Open Source custom firmware Atmosphère. More Information here: https://www.heise.de/ratgeber/Alternative-Firmware-auf-Nintendos-Switch-installieren-4857455.html

**Comment by RPiList** [comment]
I can't find get.atmos.phe.re in our malware list. Is it possible you are using another malware list from a different maintainer?

I put the domain you mentioned on the whitelist but did not get a "delete"-message after running it on the malware-list. I checked an old (backup) list and it was not on it either.

So either you have a different list or the domain is incorrect. Greetings

**Comment by ch4d1** [comment]
I found the problem. The url in question uses a cname for "webredir.vip.gandi.net".

Gandi.net it self seems to be a webhoster. So not sure why this domain is on the list.

**Comment by RPiList** [comment]
yeah... they got hacked.

check https://www.heise.de/security/meldung/Gandi-net-Angreifer-klaut-interne-Login-Daten-und-leitet-Domains-auf-Malware-um-3772259.html

**Comment by ch4d1** [comment]
Yeah but this was in 2017 and maybe the reason why they are on the list. But I do not think this is still the case today.

**Comment by RPiList** [comment]
thanks for adding this. It missed that part. Now I am puzzled why its still on the zonefile list. I will delete it now. Greetings
