### ISSUE TITLE
false positiv: webredir.vip.gandi.net

### ISSUE THREAD

**Issue by ch4d1** [RPiList/specials#653]
I found the problem for Issue #652.
The url in question uses a cname for "webredir.vip.gandi.net" (line 1030308 malware list).

Gandi.net it self seems to be a webhoster. So not sure why this domain is on the list.

_created a new Issue as the old one was closed and there is no option to reopen it._

**Comment by ch4d1** [comment]
"mail.gandi.net" seems to be a false positiv as well (line 618486 malware list)
May be releated to this topic: https://www.heise.de/security/meldung/Gandi-net-Angreifer-klaut-interne-Login-Daten-und-leitet-Domains-auf-Malware-um-3772259.html

**Comment by RPiList** [comment]
So it is not a false positive. The topic on heise.de explicitly describes the DNS rerouting to malware servers. Thats the reason why the domains are on the list.

Zonefiles still lists 5 domains from gandi.net as offensive. We will delete the domains from our list when Zonefiles says they are clear.
