### ISSUE TITLE
false positive: morguefile.com

### ISSUE THREAD

**Issue by Thekenkraft** [RPiList/specials#657]
Bei morguefile.com handelt es sich um eine Seite, auf der man kostenlose Stockfotos anbieten und/oder herunterladen kann.

**Comment by Thekenkraft** [comment]
Bin gerade etwas verwirrt, denn die Seite scheint aktuell immer noch (oder schon wieder?) auf der Malware-Liste zu sein. Einmal mit und einmal ohne www

**Comment by RPiList** [comment]
Ja, die Website hat wohl noch Probleme. Ich weiß nur noch nicht wo sie gelistet wird. Habe es testweise jetzt noch mal entfernt und dann direkt noch ein Update durchführt. Dabei wurde sie schon wieder eingespielt.

**Comment by RPiList** [comment]
https://blocklist.site listet die URL noch als schädlich.

**Comment by Thekenkraft** [comment]
Alles klar, vielleicht verschwindet sie dort ja noch irgendwann. Sonst könnte ich dort auch mal nachfragen. Ich habe sie jetzt aber eh erstmal auf meine Whitelist gesetzt. Vielen Dank für die Rückmeldung.
