### ISSUE TITLE
 image.ard.de blockiert

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#659]
image.ard.de wird von den u.a. Blocklisten geblockt:

-  https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist
- Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling
- Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

Ist das wirklich eine Tracking-/ Werbedomain?

**Comment by RPiList** [comment]
Wurden negative Auswirkungen bei der Nutzung von ARD.de beobachtet?
Das Vorhandensein in gambling dürfte falsch sein... 
Aber einige Quelllisten betrachten Tracking/Werbung als Malware... weswegen sowas da auftauchen könnte.

Und die Easylist ist Werbung. Das also die ARD Werbung unter dieser Domain hält ist nicht ausgeschlossen.

Daher die Frage, ob jemand ARD.de genutzt hat und z.B. keine Bilder angezeigt bekommen hat.

**Comment by BulldozerPete** [comment]
Die iOS App ARD-Mediathek funktioniert bei mir.
Andere Betriebssysteme kann ich nicht ausprobieren. Ebenfalls nicht den Webplayer.

**Comment by RPiList** [comment]
Domain wird entfernt. Viele Grüße und vielen Dank für den Hinweis.
