### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by arca20** [RPiList/specials#66]
Hallo zusammen,

es gibt Dienste, die wiederum auf bestimmte Seiten zu greifen, die vermutlich durch Blocklist gesperrt sind. Meine Idee wäre, dass man ein Whiteliste erstellt. 

z.B. hier sind einige hilfreiche 

https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212 
https://firebog.net/

Grüße

arca20

**Comment by RPiList** [comment]
Welche Dienste sollten das sein?
