### ISSUE TITLE
st.bahn.de - False Positive

### ISSUE THREAD

**Issue by Zocker1999NET** [RPiList/specials#666]
Die "DB Navigator" Android App der Deutschen Bahn benötigt, dass diese Domain erreichbar ist. Anderenfalls ist es leider nicht möglich, in der App ein Ticket zu kaufen. Beim Laden der Buchungsseite zur Auswahl der möglichen Tickets taucht folgende Meldung auf (bei mir auf Englisch): "There is no valid certificate on the device to establish a secure connection. Please check your system settings or update your operating system.". Das Android-System ist auf dem neusten Stand (LineageOS 18.1 / Android 11). Nach dem Freischalten der Domain kann ohne Probleme ein Ticket ausgewählt und bestellt werden.

Es wäre gut, wenn die Domain aus der Liste entfernt werden könnte, sofern keine anderen Gründe dagegen sprechen.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis, ist jetzt gefixt. Viele Grüße
