### ISSUE TITLE
False-positive "apk.support"

### ISSUE THREAD

**Issue by HorayNarea** [RPiList/specials#673]
Die Liste [Phishing-Angriffe](https://github.com/RPiList/specials/blob/master/Blocklisten/Phishing-Angriffe) enthält `apk.support`, dies ist eine Website zum direkten Download von APKs aus dem Google Play Store, kein Phishing. Daher bitte entfernen! :)

**Comment by RPiList** [comment]
Ja, die Apps die dort verteilt werden, die "phishen"... die Seite selbst nicht.

https://apk.support/download-app-es/com.bisa.bisaseguros wird von Phish-Stats gemeldet...
