### ISSUE TITLE
Fehler in Blockliste

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#675]
Hallo,

ein Blocklist-Update zeigt folgenden Fehler für Pornblock4 an:

![Bildschirmfoto 2021-10-27 um 15 35 31](https://user-images.githubusercontent.com/61943052/139076751-5a94be11-b40c-43cb-9962-1de5e4ca17d7.png)

**Comment by DiamantTh** [comment]
Das Teil mag wohl keine IDN Domain.

Schreibweise für den PI wäre wohl `www.xn--xvideos-espaol-1nb.com`

**Comment by RPiList** [comment]
Problem hat sich erledigt. Hatte ich hier aber nicht gesagt. Ein "Domain-Lieferant" hat geschlampt und diese Punydomain drin.

Viele Grüße
