### ISSUE TITLE
Typosquatting Seiten

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#677]
Hallo, mir ist die neue DomainSquatting liste und ich kenne noch ein paar nicht blockierte Domains:

Original Seite: `vancedapp.com`
Typosquatting:

```
vancedap.com
vancedappp.com
vancedaap.com
vncedapp.com
vancdapp.com
vacedapp.com
vanedapp.com
vanceapp.com
vancedapp.co
```

Original Seite: `gegen-hartz.de`
Typosquatting:

`gegenhartz.de`

**Comment by RPiList** [comment]
vielen Dank...

beide Domains wurden hinzugefügt. Bei den Typosquatting brauche ich nur die eigentliche Domain. Ein Skript erstellt dann die Typo-Domains automatisch. Grüße
