### ISSUE TITLE
notserious

### ISSUE THREAD

**Issue by bussio** [RPiList/specials#68]
Vielleicht verstehe ich diese Liste nicht ganz. Ich dachte, das die dort aufgeführten URLs nicht aufgerufen werden können. Dem ist aber nicht so ... z.B. https://www.adidascontinental.de wird ganz normal angezeigt?! Die Liste ist eingetragen und auch aktiviert.

![2020-01-14_21-46-36](https://user-images.githubusercontent.com/48105172/72381331-8b5b1880-3717-11ea-89d9-c3d7faf8b10a.jpg)

**Comment by joestr** [comment]
Ich weiß zwar nicht genau _wie_ die Filter bei Pi-Hole arbeiten aber eventuell war die Domain `www.adidascontinental.de` noch in der Pi-Hole Software gecachet und wird erst nach einem gewissen Zeitraum invalidiert.

**Comment by bussio** [comment]
> ...  noch in der Pi-Hole Software gecachet und wird erst nach einem gewissen Zeitraum invalidiert.

Das ist es nicht gewesen?! Danke

**Comment by bussio** [comment]
> .... Kann es sein, dass Ihr Rechner/Netzwerk so konfiguriert ist, dass der Pi gar nicht genutzt wird?

Ich habe als Router die FB 6590. Diese ist lt. Anleitung FB 6591 konfiguriert. Egal ob ich es vom Mac, iPad per Wlan versuche, überall erfolgt keine Blockierung?!

**Comment by HorayNarea** [comment]
> Egal ob ich es vom Mac, iPad per Wlan versuche, überall erfolgt keine Blockierung?!

Tauchen denn Queries im Log vom Pihole auf?
Und wenn ja: stimmen die IP-Adressen im Log mit den getesteten Geräten überein?

**Comment by bussio** [comment]
> Und wenn ja: stimmen die IP-Adressen im Log mit den getesteten Geräten überein?

Die Links tauchen mit dem richtigen Gerätin den Queries auf. Hier mal 3 Beispiele:

![2020-01-18_11-54-16](https://user-images.githubusercontent.com/48105172/72662689-46223980-39ea-11ea-8559-9cb4b70c8da0.jpg)

![2020-01-18_11-56-11](https://user-images.githubusercontent.com/48105172/72662696-520dfb80-39ea-11ea-9a41-319e8ffc97bb.jpg)

![2020-01-18_11-58-02](https://user-images.githubusercontent.com/48105172/72662698-56d2af80-39ea-11ea-8b3a-bba9e59efb9f.jpg)

Ich könnte jetzt zwar beigeben und die einzeln blocken, aber das kann ja nicht der Sinn sein?!

**Comment by HorayNarea** [comment]
Hm, dann könntest du noch mal probieren die Listen zu aktualisieren unter Tools -> Update gravity

**Comment by bussio** [comment]
Das mache ich täglich, daran kann es eigentlich nicht liegen.

**Comment by RPiList** [comment]
Das Pi-hole updated seine Listen einmal pro Woche automatisch. Das Update
von Hand ist wohl nur gedacht für den Fall, dass man selbst etwas
hinzugefügt hat.

Wir können festhalten, dass das Pi-hole läuft, denn in dem Screenshot ist
zu sehen, dass der Rechner Wolfgangs-mbp den Pi nutzt.

Ich hab das bei mir jetzt mit adidascontinental.de durchgespielt und
Pi-hole schlägt an. Screenshot habe ich beigefügt. Ist die Liste evtl.
nicht aktiviert?



Am Sa., 18. Jan. 2020 um 12:59 Uhr schrieb bussio <notifications@github.com

**Comment by bussio** [comment]
> Screenshot habe ich beigefügt. Ist die Liste evtl. nicht aktiviert? 
Hab den Screenshot von Dir zwar nicht gesehen, bei mir allerdings wird die Seite dargestellt. Anbei ein Screenshot des Querylogs und die Blocklisteinstellungen.

![2020-01-18_21-13-46](https://user-images.githubusercontent.com/48105172/72669968-4812e980-3a38-11ea-8b6b-6cba21755963.jpg)

![2020-01-18_21-14-49](https://user-images.githubusercontent.com/48105172/72669983-5f51d700-3a38-11ea-8590-f9edb1d4aea7.jpg)

**Comment by mroxso** [comment]
Bei mir wird die Seite wie gewollt geblockt.
![Auswahl_044](https://user-images.githubusercontent.com/24775431/72678683-919b1d00-3aa8-11ea-8eb1-8c7bd6f18b05.png)

**Comment by Sakkade** [comment]
> Vielleicht verstehe ich diese Liste nicht ganz. Ich dachte, das die dort aufgeführten URLs nicht aufgerufen werden können. Dem ist aber nicht so ... z.B. https://www.adidascontinental.de wird ganz normal angezeigt?! Die Liste ist eingetragen und auch aktiviert.
> 

Dann versuchen wir mal ein bisschen was.
Erst mal sicherheitshalber den DNS Cache leeren nur um sauber anzufangen.

1. Im Adminpanel beim PiHole unter
**Tools->Query Lists**
deine URL einfügen und das Ergebnis von **Search partial match**
anzeigen (https:// muss dabei entfertn werden)
_damit wollen wir ausschließen, dass die URL nicht auf der Whitelist steht, wie auch immer sie dahin kam. Im Querylog findet man keine Info, dass es gewhitelistet ist _

2. Wieder im Adminpanel unter 
**Settings->DNS** unter **Upstream DNS Servers**
mal ausschließlich auf Cloudflare stellen alle 4 Checkboxen. Auch keine eigenen aktivieren.
**[Siehe Bilder im Anhang]**

Danach auf die Seite _http://www.whatsmydnsserver.com/_ gehen und auf den Button
**What's my DNS Server?** klicken.
Gern auch 2 oder 3 mal wiederholen.
In der Tabelle sollte überall unter **Owner of this server** _Cloudflare, Inc._ stehen.
Sollte das bei einem Eintrag nicht der Fall sein gehen evtl. IPv6 Anfragen nicht über das PiHole bzw.
ist in der Fritzbox als Ipv6 DNS Server was anderes eingetragen.


![20200124-160220 001](https://user-images.githubusercontent.com/2452323/73078710-07492380-3ec3-11ea-9627-5b50f6c40d48.png)

![20200124-160411 001](https://user-images.githubusercontent.com/2452323/73078769-2d6ec380-3ec3-11ea-85c8-94ce2ab07c74.png)

**Comment by bussio** [comment]
@RPiList Habe nochmal die akt. Version des Pakets installiert ... jetzt läuft das Ganze wie es soll.
@Sakkade Nach der Neuinstallation des Paketes hab ich Obiges ausgeführt und das Ergebnis ist so wie in Deinem Screenshot aufgeführt.
Danke Euch Beiden für die Unterstützung!
