### ISSUE TITLE
Phishing: bitleast.com

### ISSUE THREAD

**Issue by benjaminwolkchen** [RPiList/specials#680]
Ich habe eine E-Mail bekommen, die die Volksbanken imitieren soll.

![phishing](https://user-images.githubusercontent.com/42138517/140521427-5d6b4b41-20af-49f1-b123-e857d01108e8.png)

Der Link in der E-Mail führt zu https://bitleast.com/about-eu/.
Bitleast.com selbst sieht nach einer Crypto-Mining Website mit 🥦 (?) aus - also auch nicht gerade seriös.

Ergänzung: Die E-Mail wurde von der Domain `wearcenta.com` gesendet.

**Comment by RPiList** [comment]
Vielen Dank für die Info, Domain wurde hinzugefügt. Viele Grüße.
