### ISSUE TITLE
malware list with domain tolpeit.it

### ISSUE THREAD

**Issue by DanielOberlechner** [RPiList/specials#684]
Ihr seit mir aber lustige Leute.
Wie kommt ihr dazu, die Adresse https://www.tolpeit.it auf die malware Liste zu packen?

Kennt ihr die Website oder Person dahinter eigentlich?
Ich schon, ich habe mit dieser zusammen gearbeitet, und verstehe nicht, wer auf die Idee kam, diese auf die Malware Liste zu packen.

Ich bitte darum, diese schnellst möglichst von dieser Liste verschwinden zu lassen.
Hier sieht man wieder einmal, auch wenn die Liste einem helfen wollen, was sie im Endeffekt tun ist Websiten von Privatpersonen sperren. Sowas ist echt peinlich für euch, dass sage ich.

Geht mal auf die Website rauf, und zeigt mir wo da Malware sein soll.

https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
Hier habe ich die Domain gefunden, und ich wundere mich noch, warum die Website von meinem Kollegen nicht funktionieren tut. Peinlich! (von euch aus)

Mit freundlichen Grüßen
Daniel Oberlechner

**Comment by RPiList** [comment]
> Ihr seit mir aber lustige Leute. Wie kommt ihr dazu, die Adresse https://www.tolpeit.it auf die malware Liste zu packen?
> 

Hallo Daniel. Ja, wir sind wirklich lustige Leute. Weil ist doch langweilig, wenn man nur ernst ist.

Aber wir haben die von Dir genannte URL nicht auf die Liste gepackt. Das hat unser Crawler für uns ganz automatisch erledigt. Der geht regelmäßig hin und sucht diverse Quellen nach Schadware-Listen ab. Die dortigen Domains landen dann in unserer Liste. Quellen sind z.B. von Phish-Stats, Openphish, dem Cybercrime-Tracker, DuckDuckgo, Zonefiles und vielen anderen.

> Kennt ihr die Website oder Person dahinter eigentlich? Ich schon, ich habe mit

Nein, die Website und die Personen dahinter kennen wir eigentlich nicht. Das ist aber nicht schlimm. Denn die Websites und die Personen hinter den anderen 7 Millionen URLs auf den Blocklisten kennen wir ja auch nicht. Wir wollen da niemanden ausgrenzen.

Meine Kollegen arbeiten derzeit noch an der Porn-Liste... also dort jede Seite von Hand prüfen und die Leute dahinter kennenzulernen. Ich befürchte die sind da auch noch einige Zeit schwer beschäftigt...

> 
> Ich bitte darum, diese schnellst möglichst von dieser Liste verschwinden zu lassen.

Neee lass' mal. Die von Dir genannte URL wird derzeit von Zonefiles.io als schädlich gemeldet.

Wenn Zonefiles die Domain auslistet, fliegt sie auch automatisch von unserer Liste. Das ist das schöne an Crawlern. Der updatet die Liste ganz automatisch. Ist ne praktische Sache.

 Hier sieht man wieder einmal, auch wenn die Liste einem helfen wollen, was sie im Endeffekt tun ist Websiten von Privatpersonen sperren. Sowas ist echt peinlich für euch, dass sage ich.
> 

Daniel, glaub mir jetzt einfach mal. Uns ist nichts peinlich. Aber ich sag Dir auch mal was. Nur weil die Schadware Dir nicht direkt ins Auge springt, heißt es nicht, dass da nicht Schadware auf dem Server ist.

Lass' mich raten. Es gibt ein CMS (Wordpress?) auf der Website und dort hat der Admin evtl. ein Addon installiert, dass eine Schwachstelle drin hat. Dann brechen andere in dieses CMS ein und hinterlegen irgendwo auf dem Server Schadware. Dann verlinken wieder andere auf diese Schadware. Das fällt früher oder später auf und die Domain bzw. der Link landet in den Blocklisten.

> Geht mal auf die Website rauf, und zeigt mir wo da Malware sein soll.

Ne, dazu habe ich leider keine Zeit. Ich muss nachher noch den Kollegen mit deren Liste tatkräftig unterstützen. Aber Du kannst gerne bei Zonefiles.io nachfragen. Deren Crawler hatte die Schadware gefunden.

> https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware Hier habe ich die Domain gefunden, und ich wundere mich noch, warum die Website von meinem Kollegen nicht funktionieren tut. Peinlich! (von euch aus)
> 

Also wenn Du Dich jetzt immer noch wunderst; Die Website/Der Server von Deinem Kollegen hat wahrscheinlich Schadware auf dem Rechner. Das o.g. Beispiel trifft auf gut 70% aller Schadware-Rechner zu. Die anderen 30% sind absolut schlampig konfigurierte Webserver, die dann XSS und so'n Shit zulassen.

Könnt natürlich auch sein, dass anderen den Kollegen-Server als Open-Relay benutzen. Dann ist der Server vom Kollegen everybody's Bitch. Wird auch immer gerne genommen.

> Mit freundlichen Grüßen Daniel Oberlechner

Mit freundlichen Grüßen zurück.

**Comment by DanielOberlechner** [comment]
Hallo nochmals,
> Aber wir haben die von Dir genannte URL nicht auf die Liste gepackt. Das hat unser Crawler für uns ganz automatisch erledigt. Der geht regelmäßig hin und sucht diverse Quellen nach Schadware-Listen ab. Die dortigen Domains landen dann in unserer Liste. Quellen sind z.B. von Phish-Stats, Openphish, dem Cybercrime-Tracker, DuckDuckgo, Zonefiles und vielen anderen.

Das mag schon sein, ich behaupte aber zonefiles.io Crawler hat hier bestimmt einen Fehler gemacht, soweit lehne ich mich in diesem Fall gerne aus dem Fenster.

> Nein, die Website und die Personen dahinter kennen wir eigentlich nicht. Das ist aber nicht schlimm. Denn die Websites und die Personen hinter den anderen 7 Millionen URLs auf den Blocklisten kennen wir ja auch nicht. Wir wollen da niemanden ausgrenzen.
> 
> Neee lass' mal. Die von Dir genannte URL wird derzeit von Zonefiles.io als schädlich gemeldet.

Verstehe ich leider nicht. Die Website gibt mir keine Möglichkeiten, andere Websites zu testen, kannst du mir erklären wie das genau funktionieren tut? Ich habe mich versucht eben schnell schlau zu machen, bins aber leider nicht geworden.

> Daniel, glaub mir jetzt einfach mal. Uns ist nichts peinlich. Aber ich sag Dir auch mal was. Nur weil die Schadware Dir nicht direkt ins Auge springt, heißt es nicht, dass da nicht Schadware auf dem Server ist.
> 
> Lass' mich raten. Es gibt ein CMS (Wordpress?) auf der Website und dort hat der Admin evtl. ein Addon installiert, dass eine Schwachstelle drin hat. Dann brechen andere in dieses CMS ein und hinterlegen irgendwo auf dem Server Schadware. Dann verlinken wieder andere auf diese Schadware. Das fällt früher oder später auf und die Domain bzw. der Link landet in den Blocklisten.

Ja es gibt ein CMS. UmbracoCMS welches auf MS IIS laufen tut. Das ist alleine schon so exotisch, dass ich mir kaum vorstellen kann, dass dies sehr stark angegriffen wird. Wäre es Wordpress würde ich dir recht geben, aber ein kurzer Ausflug auf die Website und dann mit Wappalayzer die Software anschauen, haette dir bestimmt gut getan.

> Also wenn Du Dich jetzt immer noch wunderst; Die Website/Der Server von Deinem Kollegen hat wahrscheinlich Schadware auf dem Rechner. Das o.g. Beispiel trifft auf gut 70% aller Schadware-Rechner zu. Die anderen 30% sind absolut schlampig konfigurierte Webserver, die dann XSS und so'n Shit zulassen.

> Könnt natürlich auch sein, dass Andere den Kollegen-Server als Open-Relay benutzen. Dann ist der Server vom Kollegen everybody's Bitch. Wird auch immer gerne genommen.

Open Relay kann ich jetzt ausschliessen, Mail Ports sind geschlossen, von daher sollte das in Ordnung sein. Habe nen Zenmap Scan gemacht, nur Standard Dinger wie FTP, HTTP, HTTPS und Remote Access via VNC or whatever ist erlaubt.

Schreibe ich hier eigentlich mit Andreas von SemperVideo, oder einem seiner Youtube Gläubigern die ihn vergoettern?
Falls es du bist Andreas, entschuldige bitte meine Ton, wir hatte schon mal Skype Kontakt. Falls der andere Fall eintritt, dann nicht xD

**Comment by RPiList** [comment]
> Hallo nochmals,

Hi,
> 
> Das mag schon sein, ich behaupte aber zonefiles.io Crawler hat hier bestimmt einen Fehler gemacht, soweit lehne ich mich in diesem Fall gerne aus dem Fenster.
> 

So so. Also Aufgrund Deiner Kommentare behaupte ich jetzt mal, dass Du keine große Ahnung von dem Thema hast. Ist auch okay, kann ja nicht jeder. Aber Du lehnst Dich aus dem Fenster und sagst die Anderen machen Fehler?

Nur so unter uns: Das ist nicht das erste Mal, dass die Domain in Blocklisten gelandet ist, richtig? Wusstest Du davon? Oder hast Du Dich damals auch aus dem Fenster gelehnt? 

> > Neee lass' mal. Die von Dir genannte URL wird derzeit von Zonefiles.io als schädlich gemeldet.
> 
> Verstehe ich leider nicht. Die Website gibt mir keine Möglichkeiten, andere Websites zu testen, kannst du mir erklären wie das genau funktionieren tut? Ich habe mich versucht eben schnell schlau zu machen, bins aber leider nicht geworden.
> 
Denke nicht, dass Zonefiles eine Möglichkeit bietet Websites testen zu lassen. Das ist ja nicht deren Aufgabe.

> 
> Ja es gibt ein CMS. UmbracoCMS welches auf MS IIS laufen tut. Das ist alleine schon so exotisch, dass ich mir kaum vorstellen kann, dass dies sehr stark angegriffen wird. 

Du kannst Dir kaum vorstellen, dass das stark angegriffen wird? Reicht schon, wenn es 1x angegriffen wird. Exotische Software ist auch kein Garant für keine Lücken im System. Wordpress ist relativ sicher, weil es von 100.000 von Entwicklern entwickelt wird. Was Wordpress unsicher macht, sind dumme Plugins, die nur von einem Entwickler entwickelt wurden. 

>Wäre es Wordpress würde ich dir recht geben, aber ein kurzer Ausflug auf die Website und dann mit Wappalayzer die Software anschauen, haette dir bestimmt gut getan.
> 

Richtig, weil ich mir die Mühe geben sollte, die sich der Admin nicht machen wollte?

> Open Relay kann ich jetzt ausschliessen, Mail Ports sind geschlossen, von daher sollte das in Ordnung sein. Habe nen Zenmap Scan gemacht, nur Standard Dinger wie FTP, HTTP, HTTPS und Remote Access via VNC or whatever ist erlaubt.
> 

Es gibt hier noch ein paar elementaren Punkte, die Du noch nicht verstanden hast, bzw. die Du durcheinander bringst.

Du glaubst offenbar, dass wenn jemand Schadware auf der Seite hat, dass die Schadware Alles und Jeden angreift und dadurch einfach zu erkennen sei. Solche Angriffe gibt es natürlich, aber nicht auf der Website Deines Freundes. Solche Angriffe gibt es auf hoch-frequentierten Websites, weil da die Masse angegriffen werden soll.

"Normale" Webserver, auf denen sich nicht viel tut, z.B. von KMU-Unternehmen wird nur Schadware "hinterlegt". Dann kommt ne Spam-Mail/Schadware Kampagne und in den eMails findet sich dann ein Link auf ein ganz tolles Angebot. Wer dann da drauf klickt lädt Schadware vom Webserver (Deines Freundes).

Das wird so gemacht, damit Dein Freund es nicht erkennt. Der schaut nur auf seine Website und der Webcode ist sauber. Er schnallt nicht, dass in seinem CMS irgendwo eine Datei liegt die von den Opfern runtergeladen wird. Dann gibts natürlich auch Admins, denen es völlig egal ist, dass sie Schadware für andere hosten...

Oder eine XSS-Lücke. Da liegt keine Schadware auf dem Rechner, aber die XSS-Lücke erlaubt fingierte Links, mit denen Opfer angegriffen werden können. 

Das alles reicht schon um in den Schadware-Listen zu landen.

Da scheint auch Dein nächstes Missverständnis zu liegen. Völlig Latte, dass die Domain in unserer Malware-Liste aufgeführt ist. Ich würd' mir eher Sorgen machen, dass da draußen noch 100e oder 1000e andere Listen sind, die ebenfalls alle Zonefiles.io als Quelle nutzen.

Selbst wenn ich die Domain also entfernen würde, würd' das gar nichts bewirken. Die anderen Listen führen die Domain trotzdem noch.

Daher ist es das Beste, wenn Dein Freund seinen Server mal aufräumt und die Schadware/Lücke löscht/schließt. Dann erledigt sich das mit den Listen von selbst.

Viele Grüße

**Comment by DanielOberlechner** [comment]
Hmm, schwierige Situation.
Ich verstehe deine Argumente, aber ich kann mich auch gut in Tolpeit's Situation versetzen, und der ist wirklich alles andere als ein Amateur. 

Ich glaube bei uns wird euer Angebot eh so selten benutzt, dass es auf den Traffic nicht ankommen tut.

Nur ich habe gemeint, die Website wäre offline, bis ich gemerkt habe mein pihole blockiert die Domain. Wäre fast peinlich für mich geworden xD

Da ich mit ihm nicht mehr aktuell in Kontakt stehe, kann ich für ihn nicht weiters Partei ergreifen.

Übrigens, die Frage ob ich mit Andreas oder einer der ihn vegoettert spreche, hat sich erübrigt ;)

Danke dennoch, für die ausführlichen Erklärungen!

Mit freundlichen Grüßen
Daniel Oberlechner
