### ISSUE TITLE
cert.at in malware block list

### ISSUE THREAD

**Issue by sysadmin0815** [RPiList/specials#686]
in your malware block list you have actually cert.at listed. 
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

that's the Computer Emergency Response Team in Austria. Maybe it was added by mistake.

**Comment by RPiList** [comment]
Its not coming from us, it got washed in by a source list 25 days ago.

Looks like this source list is no longer maintained... so I will whitelist cert.at for our list. 

Thanks for letting me know. Greetings.
