### ISSUE TITLE
apps.identrust.com blocked

### ISSUE THREAD

**Issue by taker218** [RPiList/specials#689]
The following urls are blocked by mistake I think:
apps.identrust.com
r3.o.lencr.org

The identrust.com is a public key authority, the second one is a security server from Let's Encrypt and is used to check if a certificate was revoked.
First URL is on the child-protection list, second one on the malware one.

**Comment by RPiList** [comment]
Thankx for letting uns know. It is fixed now. Please update your blocklists. Greetings
