### ISSUE TITLE
Update Download Links

### ISSUE THREAD

**Issue by JanisPlayer** [RPiList/specials#692]
Ich habe die neue Version auf meinem IPFS Knoten aktualisiert:

https://ipfs.io/ipfs/QmXYKzninZE5s9DHWYtExvuQwoDFU9SBxXdwFrthBFBMAU?filename=svpihole2013.zip
https://heldendesbildschirms.dynv6.net/download/software/betriebssysteme/svpihole/

https://ipfs.io/ipfs/QmQtGpaXT3uRWx2oZ69chxrKJS7TMaKPuUgzSeP3QkpkTz?filename=svPiholeVM2103.zip
https://heldendesbildschirms.dynv6.net/download/software/betriebssysteme/svPiholeVM/

Falls andere die Datei zu ihrem Knoten hinzufügen wollen, ihr könnt einfach den Hash pinnen oder die Datei hinzufügen.
Es handelt sich um die Originaldatei, ohne dass sie wie sonnst von mir verkleinert wurde.

Kleine Information:
Leider hatte ich letztens Probleme wegen einer Fehlkonfiguration von meinem Knoten, sodass dieser nicht im gesamten Netzwerk erreichbar war.
Falls das noch einmal passiert einfach bei mir melden. :)

**Comment by RPiList** [comment]
Vielen Dank, links wurden hinzugefügt.
