### ISSUE TITLE
wieistmeineip.de blocked

### ISSUE THREAD

**Issue by WiredLife** [RPiList/specials#694]
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist:
   wieistmeineip.de 
   www.wieistmeineip.de 

why?

**Comment by RPiList** [comment]
Listed because of https://blocklist.site

**Comment by RPiList** [comment]
Pushed it into our whitelist so it got deleted from our easylist. But I guess it's on a lot of other lists, because as of stated before.
