### ISSUE TITLE
Domains that begin with a hyphen are invalid, and should not be included in the lists.

### ISSUE THREAD

**Issue by T145** [RPiList/specials#695]
I've noticed several domain listings which start with a hyphen. Any domain that begins or ends with a hyphen is considered illegal.

This site can be used to validate some domains included in these lists: http://sqa.fyicenter.com/1000207_Domain_Name_Validator.html

**Comment by RPiList** [comment]
Thank you for pointing this out. It's fixed now. Greeting.
