### ISSUE TITLE
Admin Passwort für das Backend

### ISSUE THREAD

**Issue by hk1000** [RPiList/specials#700]
Probleme beim ersten Start.
Der FTL Dienst offline.
Und der DNS service läuft auch nicht.
Auf dem Dashboard steht nur "Lost connection to API" ohne Statistikangaben in den Graphen.
Hierzu soll ich den FTL Dienst neu starten mit den Befehlen:
```
service pihole-FTL restart 
systemctl restart pihole-FTL
```

Alternativ soll ich folgendes probieren:
```
service pihole-FTL stop
rm /etc/pihole/pihole-FTL.db
service pihole-FTL start
```

Ich logge mich mit Putty auf der IP Adresse meines Pi ein und muss nun den Benutzernamen und das Passwort eingeben.
Alle möglichen Standardpasswörter funktionierten nicht.
Probiert habe ich folgende Kombinationen

Benutzernamen:
(leer gelassen)
root
pi

Passwörter:
(leer gelassen)
root
rootme
openelec
raspberry
raspberrz

Nun zu meinen anderen Einstellungen. In meinem Speedport Rooter habe ich unter Internet -> Zugangsdaten -> Anderen Anbieter -> den Primären DNS-Server auf die IP des Pi-Hole umgebogen.
Zuvor habe ich dem Pi-hole bei Heimnetzwerk -> Heimnetzwerk (LAN) -> Übersicht der Geräte im Heimnetzwerk -> SVPi-hole ->ändern -> immer die selbe IP-Adresse zuordnen angewählt.

Im Pi-Hole habe ich bei den Settings -> DNS -> Upstream DNS Servers (Custom 1 (IPv4 und Custom 2 IPv4)  die beiden Telekom DNS Server eingetragen, die vorher im Router konfiguriert waren.
Die DHCP Einstellungen habe ich im Router, sowie im Pi-Hole nicht angefasst.

**Comment by joestr** [comment]
Das Passwort für den Benutzer `root` müsste `123456` sein.

**Comment by hk1000** [comment]
Fast, ich hab es jetzt raus gefunden.
Der Benutzername ist: `pi`
Das Passwort ist: `123456`
