### ISSUE TITLE
false positive bayernlabo.de in Phishing-Angriffe list

### ISSUE THREAD

**Issue by tankcom** [RPiList/specials#707]
Bayernlabo seems to be a legitimate domain, as it is referenced here on the freistaat.bayern site:

https://www.freistaat.bayern/dokumente/behoerde/3622278927117

```
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
   bayernlabo.de 
   www.bayernlabo.de 
```

**Comment by RPiList** [comment]
Thx for letting us know. It's fixed. Greetings.
