### ISSUE TITLE
Blocklist von Zelo72 nicht mehr verfügbar.

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/specials#709]
Habe gerade festgestellt, dass @zelo72 sein komplettes Repo hier gelöscht hat.
Dementsprechend ist seine Blocklist auch nicht mehr abrufbar.

@RPiList Weißt Du was darüber?

**Comment by RPiList** [comment]
Nein, weiß nichts darüber. Aber in dem Bereich gibt es auch keine Art von Community, die sich untereinander austauschen würde. Insoweit meldet sich da keiner bei keinem ab oder ähnliches. :-)

Nehme mal an, er hatte einfach keine Zeit mehr für das Projekt.

Habe seine Liste aus unserer Blocklisten.md rausgenommen.

**Comment by Knuschberkeks** [comment]
Hi,
ich weiß der thread ist alt, aber ich bin hier gerade drübergestolpert und wollte nur sagen: falls jemand die letzte Version von Zelo72s liste braucht, ich hab hier ne kopie davon in meinem eigenen Repository:
https://raw.githubusercontent.com/Knuschberkeks/Knuschberblock/Split/Lists/Zelo72_fake_list
Ich pflege die nicht aktiv aber es ist die letzte Version der Liste bevor sie offline gegangen ist.
