### ISSUE TITLE
Request - Apple List

### ISSUE THREAD

**Issue by FoxXxHater** [RPiList/specials#710]
Hallo, 

da ich irgendwie keine Request stellen konnte mache ich jetzt mal hier... 

Wie wäre es mit einer Block Liste für die Apple DNS's oder die von Amazon/ Smart Home Geräten?

Meinem openmediavault habe ich z.B. den kompletten Zugang gesperrt da von diesem 30% aller 80k Anfragen kam (3 Tage)

Gruß
John

**Comment by RPiList** [comment]
Liste kann ich gerne erstellen. Wo sind die Quellen, welche Domains in die Liste müssten? Viele Grüße

**Comment by FoxXxHater** [comment]
Das ist jetzt eine gute Frage... Ich meine ich benutze zwar nicht genau Pi Hole sondern AdGuard... Aber wenn ich die ganzen Apple Domains nehme die da drin stehen, ist ja auch nicht klar ob das zu Fehlern führen kann. 

Vielleicht weiß die Community darüber bescheid 🤔

**Comment by RPiList** [comment]
Ohne Quelle kann leider keine Liste erstellt werden. Insoweit kümmern wir uns um das Thema, wenn wir entsprechende Quellen gefunden haben.
