### ISSUE TITLE
Accidental addition of legit domains via the hyperphish api

### ISSUE THREAD

**Issue by BlackWolfWoof** [RPiList/specials#711]
discord.gift (official domain of Discord) and discord.gq (not owned by Discord) got added to https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe but shouldn't have been.
They have imidietly been removed from the API but it seems like not from the repo yet.
If i find any sites that shouldn't have been added i'll let you know right away.

Huge sorry for this

**Comment by RPiList** [comment]
It is fixed. Thankx for letting us know. Greetings.
