### ISSUE TITLE
Corona-Blocklist - False positiv

### ISSUE THREAD

**Issue by ch4d1** [RPiList/specials#712]
terminbuchung.covid-schnelltest-bonn.de
terminbuchung.covid19-apotest.de 

The listed websites are the booking portal of the respective test centres. They have no right to be on the list. Even if the pages are certainly not pretty, they are part of the test strategy in Germany. Many of their locations are in Bonn.

**Comment by ch4d1** [comment]
covid-schnelltest-bonn.de seems to have subdomains for company tests. So unblocking them as well would be great.

**Comment by RPiList** [comment]
It is fixed. Thankx for letting us know. Greetings.
