### ISSUE TITLE
Amazon Alexa and Backblaze B2 false positive

### ISSUE THREAD

**Issue by GR3ee3N** [RPiList/specials#717]
US Amazon Alexa portal is on the phishing list:
```
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
   alexa.amazon.com 
```

And some of Backblaze's API subdomains are on the phishing list:
```
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
   api002.backblazeb2.com 
   f002.backblazeb2.com 
   f003.backblazeb2.com 
   f004.backblazeb2.com 
```

**Comment by RPiList** [comment]
Hi,

thanks for letting us know. I removed the ones you mentioned but there are still many *.backplazeb2.com Domains in Phishing. Their service is being misused for phishing a lot.

Greetings
