### ISSUE TITLE
opensubtitles.com

### ISSUE THREAD

**Issue by baluwastaken** [RPiList/specials#726]
Warum ist opensubtitles.com auf der Blockliste für Streaming?

**Comment by RPiList** [comment]
Nehme mal an, dass es auf der Liste gelandet ist, weil es quasi als Suchmaschine für "Streaming-Angebote" fungiert.
![123](https://user-images.githubusercontent.com/56664851/155448812-1409eaeb-c49c-4eef-90cc-f333c4617790.PNG)

Bei dem Rip-Title ist es kein Problem den Film über Google zu finden... und wenn ich auf %value% online ansehen klicke, werde ich auf eine Streaming-Seite geleitet und kann den Film direkt anschauen. Und genau dafür ist die Streaming Liste ja da. Für Eltern, die nicht wollen, dass ihre Kids da evtl. P2P-Streaming durchführen.
