### ISSUE TITLE
Whitelist cisecurity.org

### ISSUE THREAD

**Issue by ProfDrToast** [RPiList/specials#728]
Ahoi zusammen,

könntet ihr bitte folgende Url Whitelisten?

*.cisecurity.org
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

**Comment by RPiList** [comment]
Hi,

die betroffene Domain wird von zwei unterschiedlichen Diensten als CNAME-Tracking Domain klassifiziert. Insoweit ist ein whitelisting derzeit nicht möglich. Viele Grüße
