### ISSUE TITLE
Streaming Blockliste

### ISSUE THREAD

**Issue by wernersbacher** [RPiList/specials#73]
Moin moin,
wieso wird in der Streaming-Blocklist cineplex.de aufgeführt? Ist das ein Fehler oder ist ab Absicht?

**Comment by RPiList** [comment]
Das ist ein Fehler, der nun korrigiert ist.

Vielen Dank für den Hinweis und die Mühen.

Viele Grüße

Am So., 26. Jan. 2020 um 11:36 Uhr schrieb wernersbacher <
notifications@github.com>:
