### ISSUE TITLE
false-positive Eintrag in Blocklist "pornblock4"

### ISSUE THREAD

**Issue by Dodo1102** [RPiList/specials#735]
in der Liste findet sich die Domain "keepersecurity.com"
Das ist keine Website die berechtigt auf dieser Liste zu finden ist, sondern die Website von einem Passwort-Manager
ich hoffe, der Eintrag kann schnell rausgenommen werden
Vielen Dank :)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Ist gefixt. Domain wurde entfernt.
