### ISSUE TITLE
Sparkassen Phishing

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#749]
Folgende Adressen wurden in aktuellen Sparkasse Phishing Mails verwendet:

spk-fingerprinting2022.com
spk-kunden-kredit2022.com
spk-mitarbeiter-daten2022.com
spk-kundencenter2022.com
spk-kunden-manager.com

**Comment by RPiList** [comment]
vielen Dank fürs Update. Viele Grüße
