### ISSUE TITLE
Kolumbien Regex blockiert .com Seiten

### ISSUE THREAD

**Issue by Foxeronie** [RPiList/specials#75]
Moin!

Ich habe bei mir die regex

```
Sperrt alle Domains aus Kolumbien:
([a-zA-Z0-9\-\.]{2,256})(\.co)
```

hinzugefuegt. Danach werden bei mir saemtlichen .com Seiten blockiert.
![regex](https://user-images.githubusercontent.com/10115997/73590893-535e1e80-44e8-11ea-946c-7896bf524973.PNG)

Viele Gruesse,
Foxeronie

**Comment by AleksCee** [comment]
Wieso für TLD nicht einfach ein
\.co$
\.ru$
Oder denke ich hier zu einfach... ich verstehe den ganzen Anfang nicht... am Ende muss doch nur die TLD Matchen auf das Zeilenende wofür das $ steht....

Liebe Grüße, Alex

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Die Zeile wurde entsprechend angepasst.

Am Sa., 1. Feb. 2020 um 12:24 Uhr schrieb Alexander Palm <
notifications@github.com>:

**Comment by AleksCee** [comment]
Ich meinte das eigentlich wirklich auch so kurz. Das ganze (a-z.... davor muss auch nicht sein.

Siehe: https://regex101.com/r/kodaul/1
Mit dem erschlägt man alles was auf .ru .co oder .cn endet 
\\.(ru|c(n|o))$

**Comment by RPiList** [comment]
Derzeit verfolgen wir noch nicht das Ziel die RegEx-Anweisungen so weit wie möglich zu komprimieren. Derzeit ist uns wichtiger, dass die Nutzer die Zeilen lesen können. Dies soll erleichtern, dass Nutzer die Zeilen verstehen und selbst evtl. Teile der Anweisung ändern können. Z.B. die Nutzer, die Kolumbien wieder "frei" haben wollen.
