### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [RPiList/specials#755]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto). Thanks!

**Comment by RPiList** [comment]
Hi, thanks for letting us know. Domain has been removed. Greetings.
