### ISSUE TITLE
False positive: *.contabostorage.com

### ISSUE THREAD

**Issue by croxxx** [RPiList/specials#757]
While trying to access some backups I noticed my provider (contabo.de) ended up on the phishing block list (Blocklisten/Phishing-Angriffe).
This is very similar to what has been observed for other S3 storage providers Like Wasabi (#733), Google (#670) and Backblaze (#717).

I can see these services being (ab)used for any kind of web-based attack as they offer a convenient, cheap and reliable way of storing data. However, I don't think those should be blocked by default, as they do serve a legitimate purpose (same as amazon or google storage).

For now I've manually whitelisted these on my system, but please reconsider inclusion in the lists.

PS: Given the above, I expect their third storage location (US) to turn up on your radar soon as well, so maybe keep that in mind when updating.

**Comment by croxxx** [comment]
Currently included in my lists:
```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
  eu2.contabostorage.com
  sin1.contabostorage.com
```

**Comment by RPiList** [comment]
Thanks for letting us know. Domains have been removed. Greetings.
