### ISSUE TITLE
Samsung-Liste blockiert integrierte Apps

### ISSUE THREAD

**Issue by Haituga** [RPiList/specials#76]
Die aktuelle Samsung-Liste blockiert neben der lästigen Werbung (was stattdessen ein kaum sichtbares Transparent darstellt) auch den Zugang zu Apps wie Netflix oder YouTube.
Leider konnte ich selbst noch nicht herausfinden, welche Domain das explizit verhindert.

**Comment by RPiList** [comment]
Hi,

uns steht kein Samsung TV (mehr) zur Verfügung, sodass wir das nicht mehr
genauer prüfen können.

Aber wenn Sie sich im Query Log alle Zugriffe Ihres Samsung TV auflisten
lassen, sollten Sie die Domain recht leicht finden können.

Ich würd den TV anschalten und zur Ruhe kommen lassen... also dass er
seinen normalen Traffic abwickelt. Dann nach 10 Minuten... er er nichts
mehr sendet Netflix und Co starten. So kann man in den Logs recht einfach
sehen, welche Verbindung er aufbauen wollte...

Am So., 2. Feb. 2020 um 20:01 Uhr schrieb Lukas Arndt <
notifications@github.com>:

**Comment by DjCrays** [comment]
Also ich hab hier privat einen Samsung SmartTV laufen und hier funktioniert alles.
