### ISSUE TITLE
Delete outdated, old lists

### ISSUE THREAD

**Issue by Dynasty-Dev** [RPiList/specials#761]
Thank you for these lists, here is a suggestion. I think to clean up this repository it would be better to delete lists that are no longer maintained. Again, thank you for putting so much time and effort on these lists.

**Comment by BulldozerPete** [comment]
Which lists?

**Comment by Dynasty-Dev** [comment]
Ah, just thought the lists that haven't been touch since 2 years ago were maintained. I mean I'm sure theres more fake science that has been added since 2020

**Comment by RPiList** [comment]
These fake science list resulted in a project a few years ago, pointing out hat problem of fake science. Thats why we created our list. Finding new sites is not so easy, since it is very time consuming. If you have new entries to the list, we will gladly add them. Greetings.
