### ISSUE TITLE
unblock amazon aws @ phishing-angriffe

### ISSUE THREAD

**Issue by WiredLife** [RPiList/specials#764]
Mit dem kompletten Block von Amazon AWS, blockt ihr auch sinnvolle Dienste wie z.b. die Grafiken in der WarnWetter App.
Nehmt bitte
s3.ap-northeast-2.amazonaws.com
s3.eu-central-1.amazonaws.com
s3.eu-west-1.amazonaws.com
s3.eu-west-2.amazonaws.com
s3.eu-west-3.amazonaws.com
s3.us-east-2.amazonaws.com
s3.us-west-1.amazonaws.com
raus.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Sind alle entfernt. Viele Grüße
