### ISSUE TITLE
Steam-Cloud sync

### ISSUE THREAD

**Issue by Xindrrobo** [RPiList/specials#767]
Hallo, ich habe festgestellt, auf der Liste "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe", befindet sich der Eintrag "objectstorage.eu-frankfurt-1.oraclecloud.com". Diese Domain scheint für die Steam-Cloud funktion zu sein. Erst als ich diese Domain auf die Whitelist meines PiHole setzte funktionierte die Steam-Cloud-Sync für die Spiele ETS2 und LEGO: The Hobbit, bestimmt auch weiter die diese Funktion nutzen.
Es verwundert mich das man für Steam-Cloud diese Domain abfragt und sie dann auch als "Phising" markiert wurde.

MfG

**Comment by joestr** [comment]
Ja, es ist über dns nicht möglich legitime Objekte von Objekt-Speichern zu identifizieren.

Eine Blockierung von `objectstorage.*.oraclecloud.com` sorgt halt dafür das auch legitime Anfragen nicht durchkommen.

Das Problem scheint in der Steam-Community bekannt zu sein:
https://steamcommunity.com/discussions/forum/1/3183488224881540789/

**Comment by RPiList** [comment]
Habe die zur Diskussion stehenden URLs erst mal von Hand entfernt. Schauen wir mal ob sie wieder reingespielt werden. Viele Grüße und vielen Dank für die Info.
