### ISSUE TITLE
False positive: urlscan.io

### ISSUE THREAD

**Issue by BlackWolfWoof** [RPiList/specials#771]
["urlscan.io is a free service to scan and analyse websites. When a URL is submitted to urlscan.io, an automated process will browse to the URL like a regular user and record the activity that this page navigation creates."](https://urlscan.io/about/)
I found out the domain was blocked because I wanted to scan a phishing site with urlscan.io

**Comment by RPiList** [comment]
Fixed. Thanks for letting us know. Greetings
