### ISSUE TITLE
False positive: www.fr.de and fr.de

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#774]
Both domains are owned by Frankfurter Rundschau (RheinMain.Media - rmm.de)

Sources:
 - https://www.rmm.de/medien/frankfurter-rundschau/frde/
 - Google Cache: https://webcache.googleusercontent.com/search?q=cache:S5aZz5MW3hcJ:https://www.fr.de/+&cd=1&hl=de&ct=clnk&gl=de

**Comment by RPiList** [comment]
Thankx for noticing us. It's fixed now.
