### ISSUE TITLE
False positive: reg.ru

### ISSUE THREAD

**Issue by BlackWolfWoof** [RPiList/specials#775]
Even tho I had to encounter the domain register reg.ru more often that I wanted due to the amount of phishing domains registered under their service, it is still just a register and not a malicious domain.
I found this in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious 
![Awooo nZBjMQd6yK](https://user-images.githubusercontent.com/29355595/179351405-8e091bfb-b514-4b89-83cb-b55821b05fea.png)

**Comment by BlackWolfWoof** [comment]
Oh and publicdomainregistry.com
Same goes for that one. Also just a domain register

**Comment by RPiList** [comment]
thanks for letting us know. It's fixed now. Greetings.
