### ISSUE TITLE
Currently used domains in Sparkasse scam mails

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#777]
spk-fingerprinting2022.com
spk-kunden-kredit2022.com
spk-mitarbeiter-daten2022.com
spk-kundencenter2022.com
spk-kunden-manager.com
spk-mitarbeiter-bereich2022.com
spk-mitarbeiterportal.com
deka-financialdepot.com
deka-aktienfonds.com
deka-nachhaltig-anlegen.com
deka-sofort-anlegen.com
deka-lowrisk-fonds.com
spk-umstellung-update.com
sparka-kundentermin2022.com
kontribute.info
farisleeinvestments.com
bunburyaustralia.com
sparka-sparen-leicht.com
blackboardconnectcorp.com
struq.us
recoveryassignment.org
staplesandstevens.com
uni-t.com

**Comment by zeus1999** [comment]
Opened Pull Request #778

**Comment by dieechtenilente** [comment]
Please add following domains as well:
`recoveryassignment.org
www.recoveryassignment.org
staplesandstevens.com
www.staplesandstevens.com
uni-t.com
www.uni-t.com`
