### ISSUE TITLE
sempervideo(.de) links tot

### ISSUE THREAD

**Issue by calgia** [RPiList/specials#782]
Hallo

Es gab eine schlichte und einfache HTML-Seite auf der die pi-hole Commands für manuelles Installieren veröffentlicht waren.
Die Seite finde ich nicht mehr und auch sempervideo.de ist nicht mehr erreichbar.

Kann jemand bitte hier die entsprechenden Commands einstellen oder mir dioese einfach irgendwie senden?

Ich möchte mein Raspberry neu aufsetzen und dazu dann wieder das PiHole installieren.

LG calgia

**Comment by RPiList** [comment]
Dauert noch ein wenig, bis die Site wieder online ist. Viele Grüße

**Comment by calgia** [comment]
Vielen Dank!

Ich warte freudig auf die Wieder-Veröffentlichung!
Von: RPiList ***@***.***>
Gesendet: Freitag, 5. August 2022 18:35
An: RPiList/specials ***@***.***>
Cc: calgia ***@***.***>; Author ***@***.***>
Betreff: Re: [RPiList/specials] sempervideo(.de) links tot (Issue #782)


Dauert noch ein wenig, bis die Site wieder online ist. Viele Grüße

-

**Comment by H4ckZ** [comment]
@calgia 

Wenn du das Pi-Hole gerne als Docker laufen lassen möchtest kannst einfach das compose-File nehmen: [LINK](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml.example).

Für einfaches, direktes Installieren einfach auf dem gewünschten Raspi

`bash
git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh
`

Die beiden Varianten oben installieren jeweils nur ein neues PiHole. Wenn noch eine alte Installation vorhanden ist müsstest du die ggf. selber vorher entfernen 

LG

**Comment by RPiList** [comment]
Seite ist inzw. wieder online gegangen. Vielen Dank für die Info. Grüße.
