### ISSUE TITLE
express.adobe.com blocked in Phishing-Angriffe

### ISSUE THREAD

**Issue by NoSubstitute** [RPiList/specials#784]
Adobe Express is Adobe's official light-weight online versions of their famous production tools.

**Comment by RPiList** [comment]
Yeah... unfortunately being an official site does not prevent you from getting hacked.

Phish-Score is listing https://express.adobe.com/page/WLuFlEK6QfvWV/ as a phishing attack. 

But it looks like they check the same sources as we do so they fixed their hole and deleted the phishing-page.

**Comment by NoSubstitute** [comment]
Oh, but nobody "hacked" Adobe Express!
That is just a page created by a random user of their service. Here's one I just created.

https://express.adobe.com/page/ckLptqeDQg1Rn/
