### ISSUE TITLE
Anfrage :: specials/Internet Services/youtube & vimeo

### ISSUE THREAD

**Issue by Tabrael** [RPiList/specials#789]
Hallo,
wäre es möglich eine Liste für die InternetServices Youtube, Vimeo ... zu erstellen?

Gruß

Tab

**Comment by RPiList** [comment]
Standardmäßig sind keine Listen für Internet Dienste notwendig. Nur wenn es Ausnahmen bedarf, werden welche erstellt. Z.B. für Spotify, weil die .co Domain für Malware/Phishing/Spam oft benutzt wird und Spotify sie auch nutzt. Probleme bei YT und Vimeo sind derzeit aber nicht bekannt. Viele Grüße

**Comment by Tabrael** [comment]
Hallo,

ich hätte damit für die Kids den youtube Zugang gesperrt.

Gruß

**Comment by mschabhuettl** [comment]
InternetServices sind eigentlich als Whitelist gedacht. Aber zum sperren verwende dich einfach eine Regex.
