### ISSUE TITLE
stylecaster.com is yellow-press/boulevard but not porn

### ISSUE THREAD

**Issue by thomasmerz** [RPiList/specials#790]
```
$ pihole pihole -q stylecaster.com
 Match found in https://dbl.oisd.nl/nsfw/:
   stylecaster.com
   [www.stylecaster.com](http://www.stylecaster.com/)
```
But after reporting to https://oisd.nl/report it says:
```
False positive report
stylecaster.com is not being blocked

Possible causes it is being blocked for you:

Are you perhaps using;

.. a service like Adhole/AHADns/DNSKu?
Their used oisd list might be out of date, or worse, they might be blocking domains that are not in oisd at all!
.. the oisd extra list?
False positive reports on the extra list will be ignored, as stated on it's [download page](https://oisd.nl/downloadsXtra)
.. an other app/blocklist that is blocking it?
.. a mirror instead of the direct links?
Please use a link found on the Downloads page
.. regex?
.. an older version of this list that contained it?
Make sure you are using the latest version.

[Report another?](https://oisd.nl/reportfalsepositive)

 -----------------
| stylecaster.com |
 -----------------

www.stylecaster.com Not listed
    stylecaster.com Listed

    Found in the following blocklists:
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock3
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4
```

So please remove this domain (and subdomains) from list(s).

**Comment by thomasmerz** [comment]
See https://stylecaster.com/about-us/
> STYLECASTER’s mantra is ‘style to the people’— and our mission is to be an accessible, inclusive, ahead-of-the-trend destination for the millennial woman who wants to live with style and substance. Our fashion, beauty and entertainment coverage is informative, inspiring and visually immersive; aspirational yet attainable. From hair styling hacks and pro skincare tips to shoppable street-style galleries and in-depth profiles on celebrities and influencers, STYLECASTER stories are smart, sophisticated and urbane — just like the women we serve. The site has been a Webby nominee and honoree for the Best Fashion & Beauty Site in 2015, 2016 and 2017.
> 
> STYLECASTER was acquired by [SHE Media](https://www.shemedia.com/), a mission-driven women’s media company, in 2014. SHE Media’s flagship properties also include [SheKnows.com](http://sheknows.com/) and [BlogHer.com](http://blogher.com/).

**Comment by RPiList** [comment]
A few sources view the topic porn quite narrow. A naked chick on one page is enough to blocklist it.
Domain has been deleted. Lets see if someone washes it in again. Greetings
