### ISSUE TITLE
https://kirchenaustritt24.de/

### ISSUE THREAD

**Issue by ZeroDot1** [RPiList/specials#792]
Über die Seite kann man nicht aus der Kirche austreten.
: https://kirchenaustritt24.de/ : 
Man muss für einen Austritt immer zu den Amtsgerichten.

**Comment by RPiList** [comment]
ich stell das hiermit mal zur Diskussion, ob solche Seiten mit unserer "Abzocker" Liste geblockt werden sollen.
Ich finde in dem Text steht klipp und klar drin, dass es nur ein "Ausfüll-Service" ist. Den Wisch bekommt man dann zugeschickt und soll man dann an die Behörden geben.

Auch die zwei Bewertungen von Kunden besagen im Grunde Gleiches.

Natürlich sind 30 EUR für ein 0-8-15 Formular sehr teuer. Richtet sich wohl an die Nutzer, die nicht mal einen Drucker zur Verfügung haben. Wundere mich, dass es sowas heute noch gibt.

Wie sehen das andere?

Ist die Website vornehmlich für Abzocke? Oder kommt es klar rüber dass es nur ein "Ausfüllservice" ist?

**Comment by RPiList** [comment]
okay... wird gesperrt. Eine einfache Google-Suche zeigt https://www.domradio.de/artikel/gericht-erklaert-kirchenaustritt24de-fuer-irrefuehrend, wonach ein Berliner Zivilgericht die privat betriebene Internetseite kritisiert. Sie sei "irreführend oder mindestens missverständlich".

Das reicht mir dann. Vielen Dank für den Hinweis.
