### ISSUE TITLE
Viele False Positives in "Malware" Liste

### ISSUE THREAD

**Issue by maof97** [RPiList/specials#798]
Hallo, ich finde das Projekt hier sehr cool und auch wirklich hilfreich zum blockieren, jedoch bekam ich in letzter Zeit mehrere Fehlalarme von meinem SIEM, welches alarmiert, wenn eine Domain aus der "Malware" Liste aufgerufen wurde (Schließlich möchte man über eine Infektion auch bescheid wissen). 

Mir sind dabei folgende Domains aufgefallen die mit Sicherheit nervig sein können (Werbung/Telemetrie etc.) aber ganz sicher nicht Malware ausliefern:

collector.github.com
clc.stackoverflow.com
browser.events.data.msn.com
vortex.data.microsoft.com
browser.events.data.msn.com

Mich haben insbesondere die microsoft-Domains in der Liste stutzig gemacht und habe dann mal eine Regex-Suche auf folgende Domains gemacht:
\\.msn.com$ -> 64 Ergebnisse
\\.microsoft.com$ -> 15 Ergebnisse
\\.google.com$  -> 10 Ergebnisse

Meiner Meinung nach sollten alle diese auch Ergebnisse aus der Liste fliegen, da es doch wohl eher unwahrscheinlich ist, dass Google, Microsoft & Msn Malware verbreiten ;)

**Comment by RPiList** [comment]
Hi,

"unsere" Malware Liste setzt sich aus mehreren Quellen zusammen. Dabei kann man festhalten, dass jeder dieser Maintainer die Begriff Malware anders definiert. 

Sie definieren - nach meiner Interpretation - den Begriff Malware mit einem aktiven Angriff auf den Nutzer und dem Versuch Schadware auf den Rechner zu kopieren.

Andere definieren Schadware aber auch schon mit dem Versuch sog. Tracking-Cookies dem Nutzer unterzuschieben oder andere Tracking-Techniken anzuwenden.

Daher umfassen viele dieser Listen auch sog. Tracking-Domains. So kommen dann auch die von Ihnen genannten Domains in die Liste.

Viele Grüße

**Comment by maof97** [comment]
Hallo,

danke für die Rückmeldung. Dann muss ich das wohl auf unserer Seite rausfiltern.

Erlauben Sie noch folgende Frage: Aus welchen Quellen kommen denn meist solche Einträge?
Mich würde sehr interessieren, welche Anbieter das so einschätzen, da ich zumindest innerhalb meiner Profession (Security Analyst) bei den Auslieferern von Tracking- und Werbe Cookies nicht von Malware-Domains gesprochen wird. Unter diesem Begriff verstehen wir entweder Domains die Malware ausliefern, Phishing betreiben oder als Malware Command&Control (C2) verwendet werden.

**Comment by hagezi** [comment]
Hallo @maof97,
@RPiList,

ja es ist eine "Höllenfahrt" eine Threat Intelligence Feed Liste aus verschiedenen Quellen zu generieren, die auch nur Domains enthält die zum Thema passen. Dieses Ziel verfolge ich mit meiner [Threat Intelligence Feeds](https://github.com/hagezi/dns-blocklists#threat-intelligence-feeds---increases-security-significantly) Liste.

Für die Generierung werden aktuell [105 Quellisten](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#tif) verwendet, falsch positive und tote Domains werden entfernt.

Hier mal eine [Statistik der letzten Generierung](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#tif), von 824012 Quelldomains, bleiben nativ 365889 Domains:

`824012 total unique domains | 394814 (48%) included | 63309 (8%) removed | 365889 (44%) dead`

Gruß und schönen Sonntag,
Gerd

**Comment by maof97** [comment]
@hagezi Oh das sieht doch gut aus! Habe die Liste geprüft und keine der oben beschriebenen False Positives gefunden. Werde diese Liste fortan zum alarmieren benutzen, vielen dank!
Die Malware Liste hier werde ich weiter einbinden zum blocken, nur nicht mehr zur Alarmierung.
