### ISSUE TITLE
Systemzeit ist falsch nach stromverlust

### ISSUE THREAD

**Issue by togir2** [RPiList/specials#80]
Nach einem trennen der Stromversorgung stimmt die Uhrzeit auf dem Raspberry Pi nicht mehr. 
DNS anfragen werden deshalb mit "BOGUS" gekenzeichent und abgelehnt.
Können Sie den "ntp"-dienst  in dem Image Installieren, sodass der PI die Uhrzeit von selbst richtigstellen kann?

Als Workaround hat mir geholfen die Uhrzeit manuell anzupassen:
1. per ssh auf dem Pi einloggen
2. sudo date --set 17:49:00

**Comment by RPiList** [comment]
Das scheint ein "bekanntes" Problem bei Raspbian zu sein, dass mir noch
nicht untergekommen ist.

Es tritt nur auf, wenn der Zeitunterschied zu groß ist. Dann würde NTP sich
weigern zu updaten.

Dafür wird dann Raspi-Config empfohlen.

Das Einzige was wir da machen könnten wäre ein erzwungenes Time-Update nach
jedem Boot-Vorgang. Werd ich mal beobachten und dann evlt. einbauen.

Grüße



Am Fr., 7. Feb. 2020 um 17:49 Uhr schrieb togir <notifications@github.com>:

**Comment by RPiList** [comment]
Erzwungenes Update nach Reboot funktioniert scheinbar auch nicht. Also wird noch mal ein extra NTP installiert.

**Comment by RPiList** [comment]
die neue Version 2003 hat jetzt den NTP (und Unbound) installiert. Viele
Grüße und vielen Dank für die Mühen.

Grüße

Am Fr., 7. Feb. 2020 um 19:45 Uhr schrieb B. Trug <rpilist@gmail.com>:
