### ISSUE TITLE
(www.)deutschepost.de False-Positive 

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#801]
https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting

List: DomainSquatting

Domains

- deutschepost.de
- www.deutschepost.de

Both of which are the official domain of Deutsche Post DHL Group

https://www.dpdhl.com/de.html
https://de.wikipedia.org/wiki/Deutsche_Post_AG

**Comment by RPiList** [comment]
Thankx for letting us know. It's fixed now. Greetings
