### ISSUE TITLE
schemas.xmlsoap.org False-Positive

### ISSUE THREAD

**Issue by PHPGangsta** [RPiList/specials#809]
Hi,

`schemas.xmlsoap.org` is on the "malware" list. It's a domain from Microsoft, hosting XML SOAP schema files like for example the encoding schema:
http://schemas.xmlsoap.org/soap/encoding/

The domain is also listed on Wikipedia as one of the "Web Services" namespaces:
https://de.wikipedia.org/wiki/Liste_der_XML-Namensr%C3%A4ume#Web_Services

Using SOAP WSDL-APIs fails because of the block.

**Comment by RPiList** [comment]
thx for letting us know. Should be fixed with your next pi-hole update. Greetings.
