### ISSUE TITLE
Samsung Blockliste blockt zu viel

### ISSUE THREAD

**Issue by StephanBussmann** [RPiList/specials#81]
Hallo,
ich hatte nach dem einspielen der Samsung Liste folgende Probleme:
* die Youtube-App auf dem SmartTV startet nur mit einer Zertifikatswarnung
* in der ARD Mediathek auf dem SmartTV werden keine Grafiken geladen

Danach habe ich in einem anderen Repo den Hinweis gefunden, dass
* time.samsungcloudsolution.com
* samsungotn.net
* cdn.samsungcloudsolution.com
nicht belockt werden sollten

*time.samsungcloudsolution.com* verursacht den Fehler in der Youtube App
*samsungotn.net* ist für den Update Check bei Samsung UE65RU7455
*cdn.samsungcloudsolution.com* ist für den Update Check bei Samsung UE40F5500

Mein Gerät schick Anfragen sowohl an samsungotn.net als auch cdn.samsungcloudsolution.com.
Außerdem vermute ich, dass cdn.samsungcloudsolution.com wohl mit den fehlenden Grafiken in der ARD Mediathek zusammen hängt.

Nach dem ich die URLs auf die Whitelist gesetzt habe, funktioniert wieder alles wie gehabt.
Eventuell sollte das mit aufgenommen werden.

**Comment by RPiList** [comment]
Hallo,

vielen Dank für die Info. Die Einträge wurden entfernt. Viele Grüße

Am Sa., 8. Feb. 2020 um 14:58 Uhr schrieb Stevie <notifications@github.com>:
