### ISSUE TITLE
Legit Websit, No Domain Squatting - vrn.de  

### ISSUE THREAD

**Issue by Emre-24** [RPiList/specials#813]
Hello,

it is the normal website of a German transport association.

https://en.wikipedia.org/wiki/Verkehrsverbund_Rhein-Neckar

Greetings

Servus,

vrn.de ist die Website eines deutschen Nahverkehrverbundes im Rhein-Neckar-Kreis.
Hier auch der deutsche Wikipedia Artikel.

https://de.wikipedia.org/wiki/Verkehrsverbund_Rhein-Neckar

Grüße

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domain wurde entfernt.
