### ISSUE TITLE
False Positive: wellsfargo.com

### ISSUE THREAD

**Issue by Tater-K7S5A** [RPiList/specials#814]
Thank you for compiling and curating these lists.  It is truly a service to humanity.

I found a false positive via https://v.firebog.net/hosts/RPiList-Phishing.txt.  It lists the domain 'connect.secure.wellsfargo.com' which is in fact the login page for Wells Fargo Bank. The next entry is that string plus a string of '.auth.login.present.stonehamweb.com'. I assume the legit domain got copy/pasted in by mistake during an update.

Thank you again.

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.
