### ISSUE TITLE
Fake-Geldanlageseiten

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#815]
Hallo,

folgende Fake-Seiten habe ich entdeckt die die Listen von sempervideo nicht kennen:

Verzinst.com
sparkasa.net
zinsgurus.com
sind Kopien des Anlagemarktplatzes weltsparen.de

hansaspar.de
wird angeblich von check24 betrieben

Vorschlag für eine weitere externe Quelle:
https://www.test.de/Warnliste-Geldanlage-Unserioese-Firmen-und-Finanzprodukte-1131965-0/

**Comment by RPiList** [comment]
Vielen Dank für die Infoo. Die 3 Domains wurden der Liste hinzugefügt. Viele Grüße
