### ISSUE TITLE
ims-na1.adobelogin.com

### ISSUE THREAD

**Issue by Deutschi** [RPiList/specials#818]
Die Domain "ims-na1.adobelogin.com" ist in der Liste "Phishing-Angriffe" vorhanden. Dadurch konnte heute ein Mitarbeiter sich nicht in die Adobe Creative Cloud anmelden - weder im Programm noch im Browser. Nach dem Whitelisten ging es dann... ist also in meinen Augen eine legitime Domain ;-)

Edit: Die Domain steht sogar auf der offiziellen Hilfeseite: https://helpx.adobe.com/de/muse/kb/could-not-connect-to-server.html

Edit2: Die Domain "na1r.services.adobe.com" aus der verlinkten Hilfeseite ist auch in der Liste "Crypto" enthalten. Kann da denke ich auch entfernt werden.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
