### ISSUE TITLE
nach ersten start passiert nix

### ISSUE THREAD

**Issue by Taschentoster** [RPiList/specials#82]
hallo ich habe vorhin auf yt (Taschentoster) geschrieben das die img 2003 sich nicht im netz finden lässt oder sich per DHCP einträgt. habe das beim pi2+ und pi3+ getestet. der pi3+ ist jetzt über 8minuten an und nix passiert mehr, in ersten 1-2min hatt der noch geblinkt dann ende.

**Comment by Taschentoster** [comment]
hab den jetzt an bildschirm angeschlossen, und er meind die ip 192.168.111.93 zu haben.
ich bin aber in x.x.10.xxx netz. kann keine verbindung auf bauen. mus jetzt gucken ob mein pc ins netz bekomme zum umstellen.

**Comment by RPiList** [comment]
Nein, lassen Sie das einfach. Es lohnt sich nicht das zu reparieren, wenn
wir da einen Fehler gemacht haben.

Ich suche den Fehler noch und fixe es dann. Dann kommt eine neue Version.

Am Mo., 10. Feb. 2020 um 18:01 Uhr schrieb Taschentoster <
notifications@github.com>:

**Comment by Taschentoster** [comment]
fehler gefunden er macht zwar sein script aber vergibt falsche ip!
nach pihole -r konnte ich ihn die richtige ip setzen.

**Comment by RPiList** [comment]
Bis jetzt habe ich den Fehler noch nicht gefunden, bzw. die Stellen die ich
geprüft habe, sind so wie sie sein sollen.

Was passiert ist Folgendes:

Beim Startvorgang wird ein Cronjob gestartet.

Der Cronjob startet die Datei /home/pi/mylanip

Die Datei extrahiert die IP, die die LAN-Schnittstelle in Ihrem Netzwerk
erhalten hat.

Diese IP wird dann in die Datei /etc/pihole/setupVARS.conf (oder so
ähnlich) geschrieben.

Danach wird der Pi noch mal gestartet und dann sollten die richtigen Daten
in der Setup Datei stehen und Pi kann arbeiten.


Am Mo., 10. Feb. 2020 um 18:18 Uhr schrieb Taschentoster <
notifications@github.com>:

**Comment by Taschentoster** [comment]
dann muss an mein Lan setup was falsch sein. das er die 192.168.111.xxx ip zieht.
der pi ist per DLAN angeschlossen nicht das auswirkung hat.

**Comment by RPiList** [comment]
Ja, das dürfte es sein.

Was ist DLAN?

Am Mo., 10. Feb. 2020 um 18:25 Uhr schrieb Taschentoster <
notifications@github.com>:

**Comment by RPiList** [comment]
Wenn Sie ein Ifconfig durchführen... wie heißt die Schnittstelle die die richtige IP bekommen hat?
Die sollte eigentlich "eth0" lauten. Hier sucht das Script nach der IP.

**Comment by Taschentoster** [comment]
DLAN ich sag immer DOSEN-Lan damit es alle verstehen.
das ist LAN Dosen die mann am stromnetz hängt um sich das verlegen von lan kabel zu sparen, weil die dosen ihrentwie über schutzleiter die signale senden. Gib mal DLAN in google ein, an sich ne tolle idee wenn da die bitrate nicht so schwach wäre. aber für DNS wie pihole & netz drucker perfekt.

kann sein das mylanip nicht lang genug oder das abgreift was der pi im cache hat vom booten was falsch sein könnte.

**Comment by Taschentoster** [comment]
> 
> 
> Wenn Sie ein Ifconfig durchführen... wie heißt die Schnittstelle die die richtige IP bekommen hat?
> Die sollte eigentlich "eth0" lauten. Hier sucht das Script nach der IP.

er kennt den Ifconfig command nicht

**Comment by RPiList** [comment]
[image: image.png]
Wie heißt die Schnittstelle bei Ihnen?

Viele Grüße

Am Mo., 10. Feb. 2020 um 18:39 Uhr schrieb Taschentoster <
notifications@github.com>:

**Comment by Taschentoster** [comment]
die img kann ich vergessen. der schreibt immer wieder 111.1 in der Gateway rein, egal wie oft ich reconf mache.
ifconfig gibs nicht....

**Comment by Taschentoster** [comment]
nur zur info die img 2002 hat sofort funktioniert! und dir richtige ip gezogen! hab nix geändert nur die img von 2003 die 2002 genommen.

**Comment by RPiList** [comment]
Ja, pihole kann nicht rekonfiguriert werden.

Ich könnte noch den Namen der Schnittstelle gebrauchen. Den kann man über
das Webinterface des pihole abfragen, wie in Screenshot oben gezeigt.

Taschentoster <notifications@github.com> schrieb am Mo., 10. Feb. 2020,
19:04:

**Comment by Taschentoster** [comment]
eth0 trägt er die ip ein.
vorhanden sind eth0 und lo bei lo steht nur 127.0.0.1 und so.
was interessant ist war das die ip nicht im setting/system stand, erst wo ich sie eingetragen habe in reconfig die ip6 hat auch komplett gefehlt und auch hostname.... als wäre die script irgentwo stehen geblieben.

**Comment by RPiList** [comment]
Danke für das Feedback.
Also lag es nicht am DLAN, bzw. die Schnittstelle heißt immer noch eth0.

Dann liegt der Fehler evtl. am neu installieren Unbound.

Am Mo., 10. Feb. 2020 um 19:41 Uhr schrieb Taschentoster <
notifications@github.com>:
