### ISSUE TITLE
connect.secure.wellsfargo.com

### ISSUE THREAD

**Issue by thequackdaddy** [RPiList/specials#820]
This is on your blacklist ... 

connect.secure.wellsfargo.com

I'm guessing it was added accidentally when you tried to block the phising link. 

<img width="999" alt="image" src="https://user-images.githubusercontent.com/8186432/194448878-df4f6031-fc62-4a54-8ee6-a2e1d4d3b2ef.png">

**Comment by thequackdaddy** [comment]
Oh wait. this is a duplicate of #814. Looks like the list hasn't been updated since then.

**Comment by WaLLy3K** [comment]
I've been made aware of this @thequackdaddy and have manually run an update. I believe I've resolved the reason why it failed to run, but I'll just have to keep an eye on it :)
