### ISSUE TITLE
JoynMe App von Pro7 funktioniert nicht.

### ISSUE THREAD

**Issue by Powerbless** [RPiList/specials#823]
Weiß jemand wie man die App zum laufen bekommt mit Pihole? Habe schon diverse Blacklisten probiert aber die App lädt mit Pihole nicht. Ohne Pihole funktioniert sie. Danke

**Comment by RPiList** [comment]
Hi,

dazu einfach in den Log-Daten vom Pi-hole nachschauen, welche Domain vom Pi-hole gesperrt wird. Die dann einfach freischalten. Viele Grüße

**Comment by Powerbless** [comment]
Habe ich schon probiert mit dem Query Log und dann diverse Domains auf die Whitelist gesetzt aber irgendwie bekomme ich es nicht hin. Oder muss man nach jedem ändern "Update Gravity" machen?

**Comment by hagezi** [comment]
@Powerbless 
Schau mal ob `middleware.p7s1.io` geblockt wird, wenn ja, setze sie mal auf die whitelist. Auf welchem System verwendest du die App? Unter iOS läuft sie bei mir mit meiner [Pro++-Liste](https://github.com/hagezi/dns-blocklists#proplus). Android kann ich leider nicht testen.

Gruß, Gerd - https://github.com/hagezi/dns-blocklists
