### ISSUE TITLE
commondatastorage.googleapis.com

### ISSUE THREAD

**Issue by Nick1st** [RPiList/specials#825]
`commondatastorage.googleapis.com` is on the `Phishing-Angriffe` blocklist. This domain is owned by Google and provides various services. It is also possible to use it to publish own services. This possibility may have been used by malware and fishing in the past, but since it still offers various useful services, the domain should probably be removed from this list. For example, it contains the raw endpoint for Google Cloud Storage. e.g.: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/videos.json

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed.
