### ISSUE TITLE
miweba.de aus 'notserious' entfernen

### ISSUE THREAD

**Issue by Beast76** [RPiList/specials#831]
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious:

www.miweba.de

Ich glaube die Seite kann entfernt werden. Der Shop sieht vertrauenswürdig aus.
https://de.trustpilot.com/review/miweba.de

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
