### ISSUE TITLE
Incorrect entry

### ISSUE THREAD

**Issue by lcsaszar** [RPiList/specials#834]
netbank.takarekbank.hu should not be blocked in Phishing-Angriffe, it is a legitimate domain

**Comment by RPiList** [comment]
I'm afraid it has to stay on the phishing list, as it is reported as hosting malware/phishing on their website by phishing.army
It will be removed, then they fixed the problem.

**Comment by lcsaszar** [comment]
Hello,I am just a humble user, client of Takarekbank (recently merged into MKB Bank) in Hungary. I use their mobile app with 2 factor authentication. It used to work until 2 or 3 days ago, and stopped working today. When was a phishing reported on their web banking site? Did you notify the owner of the domain? I mean Takarekbank (MKB Bank) has an IT security team for sure, and their task is to resolve this security issue (if it exists at all).Thanks
-------- Eredeti üzenet --------Feladó: RPiList ***@***.***> Dátum: 2022. 10. 27.  16:28  (GMT+01:00) Címzett: RPiList/specials ***@***.***> Másolatot kap: Császár László ***@***.***>, Author ***@***.***> Tárgy: Re: [RPiList/specials] Incorrect entry (Issue #834) 
I'm afraid it has to stay on the phishing list, as it is reported as hosting malware/phishing on their website by phishing.army
It will be removed, then they fixed the problem.

**Comment by RPiList** [comment]
I don't know any specifics. I can only state that phishing.army reported the domain. I don't know if phishing.army contacted the owner, but I would not be surprised if they didn't. They find new malware/phishing in the thousand every day... contacting every owner would be a second full time job. :-)

If you need this domain for your homebanking, please whitelist it in your pi-hole. Greetings

**Comment by Protodjango** [comment]
Can you check www.digitec.ch and www.galaxus.ch in domain squatting1 list  ? Those are legit

**Comment by RPiList** [comment]
Domains have been removed.
