### ISSUE TITLE
[FP] self.events.data.microsoft.com

### ISSUE THREAD

**Issue by Dynasty-Dev** [RPiList/specials#837]
Endpoint self.events.data.microsoft.com is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.

Found in: Malware
Is it malware? No.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

**Comment by RPiList** [comment]
The domain in question has been reported by the Adguard Team as a disguised cname tracker domain. Greetings.

**Comment by Dynasty-Dev** [comment]
Hello, greetings. This is a domain whitelisted in almost every well known blocklist. Even if it were a tracker (IT's NOT!) it should not be in the malware blocklist. Also I have tested and it does indeed break functionality with Microsoft office in browser.

**Comment by hagezi** [comment]
Blocking *.events.data.microsoft.com causes various problems in Office365 and Teams online collaboration. It is a required endpoint. See the Microsoft description of required endpoints.
No idea why these ended up on the AdGuard CNAME list, but they are not blocked in AdguardDNS.
As the Adguard team themselves say, you shouldn't blindly use the CNAME list as a blocklist either.

Gerd - https://github.com/hagezi/dns-blocklists

**Comment by RPiList** [comment]
> As the Adguard team themselves say, you shouldn't blindly use the CNAME list as a blocklist either.

They say don't use CNAME in Blocklists and have it on their list themselves?

However, I have created a services file for Office, so user can easily whitelist it.

**Comment by RPiList** [comment]
> Even if it were a tracker (IT's NOT!) it should not be in the malware blocklist.

There is no use fighting over it. Tracking is considered by many as a form of malware. That is why many malware lists carry cname domains. That is why it is on the Adguard list in the first place. We are only importing their list. When the Adguard Team deletes the domain from their list, it gets automatically deleted on ours.

**Comment by Dynasty-Dev** [comment]
But its not a tracker..

Whatever, I will be contacting the adguard team and switching sources..

**Comment by Dynasty-Dev** [comment]
> > Even if it were a tracker (IT's NOT!) it should not be in the malware blocklist.
> 
> There is no use fighting over it. Tracking is considered by many as a form of malware. That is why many malware lists carry cname domains. That is why it is on the Adguard list in the first place. We are only importing their list. When the Adguard Team deletes the domain from their list, it gets automatically deleted on ours.

I don't understand why you are so against whitelisting this domain, it's a CLEAR false positive whitelisted in almost list. You are saying its in adguards cname tracker list, yeah and?? Steven Black's list also includes adguards cname list but he has whitelisted that domain carefully.

**Comment by RPiList** [comment]
> I don't understand why you are so against whitelisting this domain, it's a CLEAR false positive 

I am sorry if I can't make myself as clear as it is needed here. English ist not my native language.

1. If it is such a clear case of false positive, the Adguard Team will remove it. 

2. Most of the false positives that get reported to us, are not false positives.

3. We provide a broad set of domains which the user has to fine-tune himself/herself. Thats why we have the "Internet Services" Sektion.

4. If a list breaks a service you are using, you can whitelist that domain with a single mouse click on your pihole. But instead you are suggesting that we should whitelist it for all users. But not other user seem to experience the same problems. We have two users at RPiList that use Office 365, and they don't have any problem. I will check that again, but I guess they would have mentioned such problems.

Greetings

**Comment by RPiList** [comment]
Hi,
just a quick follow up on if its "tracking" or not.

The german BSI (Federal Office for Information Security) lists self.events.data.microsoft.com as tracking domain which every official government branch has to block. Its mandatory for almost everyone, except endusers. Because they can allow the transmission of personal data to Microsoft. Everyone who can't has to block it.

**Comment by hagezi** [comment]
> > As the Adguard team themselves say, you shouldn't blindly use the CNAME list as a blocklist either.
> 
> They say don't use CNAME in Blocklists and have it on their list themselves?
> 
> However, I have created a services file for Office, so user can easily whitelist it.

https://github.com/AdguardTeam/cname-trackers/issues/62#issuecomment-1317576716
