### ISSUE TITLE
False positive: telex.hu

### ISSUE THREAD

**Issue by MicrosoftEggshell** [RPiList/specials#839]
telex.hu (and www.telex.hu) are included in the malware blocklist. Telex is one of the largest Hungarian news websites, definitely not malware.

They might have came from [https://v.firebog.net/hosts/Prigent-Malware.txt](https://v.firebog.net/hosts/Prigent-Malware.txt)? I'm not sure how you source your domains, but it was also included in this list (from your Blocklisten.md).

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.
