### ISSUE TITLE
unbound update routine restart service

### ISSUE THREAD

**Issue by DuschdrBabbe** [RPiList/specials#84]
macht doch nach dem kopieren noch einen restart des service rein

`service unbound restart`

grüßle

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis.
Restart-Befehl ist jetzt eingebaut.

Am Sa., 15. Feb. 2020 um 11:49 Uhr schrieb DuschdrBabbe <
notifications@github.com>:
