### ISSUE TITLE
https fehlt secure connection und neue Download Mirrors

### ISSUE THREAD

**Issue by JanisPlayer** [RPiList/specials#840]
http://sempervideo.de/svpihole/svpihole2211beta.iso
Mixed Content: The site at 'https://github.com/' was loaded over a secure connection, but the file at 'http://sempervideo.de/svpihole/svpihole2211beta.iso' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
Ihr solltet den Link auf HTTPS umstellen. ;)

Ich bin gerade auch dabei eure Datei wieder bei mir zu aktualisieren.
Ist das schon das Maximale an Kompression, was man erreichen kann mit ISO?
IPFS stellt sich nämlich mit sehr großen Dateien sehr blöd an.
Update: habe es rausgefunden, geht noch kleiner und habe ein paar Komprimierungsverfahren ausprobiert für ZIP. :)
Jedenfalls braucht das Effizienteste 4 Stunden und die anderen mehr als 20 Minuten auf meinem Ryzen 5800H, dass ich dann doch ein schnelles genutzt habe und ich bin auf eine Größe von 1,7 GB gekommen. :D
Vielleicht könnt ihr das noch einmal richtig komprimieren, 18 % Größe sollten möglich sein, ich habe ab der 20-50 % aber abgebrochen und es gibt sicher bessere Formate als ZIP dafür, aber da weiß ich nicht, ob die Nutzer das entpacken können.

Neue Download Links:
https://heldendesbildschirms.de/download/software/betriebssysteme/svpihole/
https://ipfs.io/ipfs/QmdGeqEVRGGt1s89zLTu6185euHbi32NXCT3GamL3kFz3L?filename=svpihole2211beta.zip

**Comment by joestr** [comment]
Im Firefox übrigens auch
![image](https://user-images.githubusercontent.com/20691668/200194855-8bb71175-4e50-4268-be1b-de222b468156.png)

**Comment by RPiList** [comment]
Downloadlinks wurden hinzugefügt. Vielen Dank für die Unterstützung. Viele Grüße
