### ISSUE TITLE
war mal so frech n torrent zu erstellen

### ISSUE THREAD

**Issue by crazymindstorm** [RPiList/specials#841]
link zum torrent file ist  https://mindstormsit.net/download/svpihole2211beta.iso.torrent

**Comment by mschabhuettl** [comment]
Jap, der Link zeigt auf 404er @RPiList @crazymindstorm

**Comment by crazymindstorm** [comment]
> Bei mir kommt da ein 404-Fehler zurück. Kann das mal jemand bitte kurz prüfen?

hatte was n wort im link vergessen
