### ISSUE TITLE
Whitelist Mastodon instance: ioc.exchange

### ISSUE THREAD

**Issue by WaLLy3K** [RPiList/specials#843]
https://ioc.exchange/about
This is a popular Mastodon instance with over 10,000 users, and 8400 active.

Thank you for your timely resolution 🙂

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed.

But it is still listed on https://dsi.ut-capitole.fr/blacklists/index_en.php if you want to go for the source of blocking.

Greetings

**Comment by WaLLy3K** [comment]
Yep, submitted a whitelist request alongside this one. Cheers! 👍
