### ISSUE TITLE
Incorrect entry

### ISSUE THREAD

**Issue by oe3jtb** [RPiList/specials#844]
Hi in this list 
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
this matches are found
___Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious:
  funkelektronik.at
  funkelektronik.eu
  www.funkelektronik.at
  www.funkelektronik.eu_
Theese are vailid domains of a serious shop

tnx

**Comment by RPiList** [comment]
thx for letting us know. Domains have been removed. Greetings.
