### ISSUE TITLE
pihole reports incorrect entries.

### ISSUE THREAD

**Issue by t0mm13b** [RPiList/specials#846]
Pi-hole reports invalid entries

> [i] Target: https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting
>   [✓] Status: Retrieval successful
>   [i] Analyzed 14 domains, 14 domains invalid!
>       Sample of invalid domains:
>       - content="github.com">
>       - content="github.com">
>       - data-target="input-demux.source"
>       - data-targets="input-demux.sinks"
>       - cache-key="v0:1668121643.765652"

**Comment by RPiList** [comment]
Hi,
thx for letting us know.

According to my piholes, the DomainSquatting list does not contain invalid domains.
![](smb://userver/6gb-wd/temp-VMs/Unbenannt.PNG)

**Comment by RPiList** [comment]
It looks like you are referencing the wrong Blocklist, you mentioned https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting

The correct url should be https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting

Check out: https://github.com/RPiList/specials/blob/master/Blocklisten.md
