### ISSUE TITLE
add page.link

### ISSUE THREAD

**Issue by tarumes** [RPiList/specials#849]
page.link wird aktuell massiv für DHL und GLS scam verwendet

ne kleine auswahl:
```
vdsvdshtgrfe.page.link
vdfetefds.page.link
vdbdnjtrjtkjdgdfsc.page.link
kjfjkfgkgfkdgkgdshk.page.link
jhgjgjgjgjgjgjg.page.link
jfgjfjfgjfgjfg.page.link
hfdhdfghdfhdfghfdghfdgh.page.link
gfhsdghqdhfqdfhqdfhdqfh.page.link
fezcdsqc.page.link
```

würde als gleich
`page.link`
hinzufügen

**Comment by RPiList** [comment]
Domains wurden hinzugefügt. Aber ja, am besten über RegEx direkt page.link oder ganz .link sperren.
