### ISSUE TITLE
updates.cdn-apple.com von spam.mails entfernen

### ISSUE THREAD

**Issue by c0by85** [RPiList/specials#850]
Hi,

bitte `updates.cdn-apple.com` von der Liste https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails entfernen. Die URL wird für Apple Updates benötigt. Siehe https://support.apple.com/de-de/HT210060.

![image](https://user-images.githubusercontent.com/25707747/203246803-e8790127-9f0b-4b0e-b022-8cca6c2d3455.png)

Danke.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt.
