### ISSUE TITLE
[Possible FP] `badges.twitch.tv`

### ISSUE THREAD

**Issue by Felanbird** [RPiList/specials#851]
Hello, 

Over in https://github.com/Chatterino/chatterino2/issues/4071#issuecomment-1324280890 we had a user comment that they were unable to load badges in our application, due to their pi-hole having the badge endpoint blocked. `Blocklisten/easylist#L51868`

While I'm willing to bet money Twitch is tracking you, I do not believe the badge endpoint is how they are doing it.

Currently the only URL I'm aware of from this subdomain, is https://badges.twitch.tv/v1/badges/global/display - which is used for 3rd party applications to load Twitch badges, but it might be possible the system that flagged this URL, knows something I do not.

Cheers

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.
