### ISSUE TITLE
trackingshipment.apple.com

### ISSUE THREAD

**Issue by fratzi** [RPiList/specials#855]
trackingshipment.apple.com is used for picture to text parcel tracking-id detection and resolution via iphone.
wrong entry in two lists.

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist:
  trackingshipment.apple.com
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling:
  trackingshipment.apple.com

**Comment by RPiList** [comment]
thx for letting us know. Domain has been removed. Greetings
