### ISSUE TITLE
Ungerechtfertigte Blockierung

### ISSUE THREAD

**Issue by AtimoWorld** [RPiList/specials#856]
Leider mussten wir feststellen, dass in diesen Listen legitime Domains eingetragen werden.

Unter anderem sind folgende Domains von uns betroffen zb.:
gaylaktika.de
gaylaktika.com
gaynight-dresden.de
weitere prüfen wir aktuell.

Für uns ist das nicht nachvollziehbar, da wir keine sexuellen Inhalte hosten, geschweige denn Schadcode verbreiten oder anderweitige Beeinträchtigungen verursachen.
Wir betreiben auf unseren Webseiten zumeist Ticketshops für entsprechende Partys und Events.
Bisweilen wurde unsere Anfrage, mit der Bitte uns dies zu erklären, per Mail nicht beantwortet.

**Comment by RPiList** [comment]
> Leider mussten wir feststellen, dass in diesen Listen legitime Domains eingetragen werden.

naja... am Ende sind alle Domains legitim. Auch die, die auf den Blocklisten sind. Die von Ihnen genannten Domains befinden sich, aufgrund der jeweils ersten drei Buchstaben, in der Pornblock-Liste.

Das dürfte aber nicht wirklich überraschen. Jeder Jugendschutz-Filter schlägt bei dem Wort an. Da steht man nicht mal in Listen drin und wird trotzdem geblockt.

Das sind Listen die i.d.R. von Erziehungsberechtigten genutzt werden, weil man nicht will, dass Sohn/Tochter auf Domains zugreifen, die evtl. Material vorhalten, das für Minderjährige nicht geeignet ist. Für Minderjährige ungeeignetes Material ist nicht zwangsweise nur Porn.

> gaynight-dresden.de
weitere prüfen wir aktuell.

Wenn Sie noch weitere Domains registriert haben, die szenetypische Begriffe enthalten, dann können wir davon ausgehen, dass die auch von unserem WebCrawler erfasst wurden.

Die abonnierten Listen lassen sich aber problemlos mit jedem Pihole in Sekunden durchsuchen.

> Für uns ist das nicht nachvollziehbar, da wir keine sexuellen Inhalte hosten, 

Der "Treffer" in der Domain reicht unserem Crawler schon zur Listung der Domain. Bei insg. 9,2 Mio Einträgen in der Pornblock-Liste, können diese nicht in Augenschein genommen werden.

> Bisweilen wurde unsere Anfrage, mit der Bitte uns dies zu erklären, per Mail nicht beantwortet.

Wir reagieren auf Anfragen i.d.R. innerhalb von 48 Std. Das ist ein nicht kommerzielles Community-Projekt. Hier macht jeder freiwillig mit.

Die drei genannten Domains schreibe ich in die Whitelist und damit werden sie beim nächsten Update entfernt.

Viele Grüße

**Comment by AtimoWorld** [comment]
Hallo liebes Team,

Danke für die schnelle Reaktion.

> Die von Ihnen genannten Domains befinden sich, aufgrund der jeweils ersten drei Buchstaben, in der 
> Pornblock-Liste.
> Das dürfte aber nicht wirklich überraschen. Jeder Jugendschutz-Filter schlägt bei dem Wort an. Da steht man nicht mal in Listen
> drin und wird trotzdem geblockt.

Das Wort "Gay" übersetzt "Homosexuell" in einer Domain, ist das kein Indiz für jugendgefährdenden Inhalt, außer Ihr arbeitet nach homophoben Maßstäben, was hoffentlich nicht der Fall ist.

> Wenn Sie noch weitere Domains registriert haben, die szenetypische Begriffe enthalten, dann können wir davon ausgehen, dass die auch von unserem WebCrawler erfasst wurden.

Wir haben einige weitere Domains gefunden, welche zu unserem Portfolio gehören ua.:
gay-dresden.de
gaydresden.com

Generell lässt sich feststellen, dass Ihr sehr viele Domains blockt, welche keine sexuellen Inhalte führen. Der reine Crawler Auswertung der Domain erscheint uns zu willkürlich und unzuverlässig. Ua. Pornblock Liste Nummer 6, Stichwort "Versicherungsexperte", dies ist nur ein Beispiel von vielen.

Bitte entschuldigt unseren ausgedrückten Zeitdruck. Tatsächlich waren wir sehr geschockt über diese Eintragungen und danken Euch um so mehr für die schnelle Reaktion. Seid Euch versichert, dass wir das Projekt in unserer Agentur sehr schätzen und schon oft an Kunden und Freunde sowie Familie weiterempfohlen haben.

**Comment by RPiList** [comment]
Hi,

> Das Wort "Gay" übersetzt "Homosexuell" in einer Domain, ist das kein Indiz für jugendgefährdenden Inhalt, außer Ihr arbeitet nach homophoben Maßstäben, was hoffentlich nicht der Fall ist.

Es ist richtig, dass Gay kein Indiz für jugendgefährdenden Inhalt ist. Dies gilt dann aber auch wieder für (fast) alle anderen Trigger-Begriffe des Crawlers. Don't judge a book by its cover.

Das ist die Abwägung, die man als Maintainer einer solchen Liste machen muss. Insoweit legen wir den Maßstab daran, was den Nutzern der Liste (Eltern von Kindern) wichtiger ist. "Gay" zu blocken und damit false positives in Kauf nehmen und diese bei Bedarf mit einem Mausklick whitelisten oder 381.000 Domains mit dem Codewort nicht blocken und dann zu riskieren, dass die Kids Inhalte aufrufen die ungeeignet sind.

Die Eltern werden sich dafür entscheiden sog. False Positives in Kauf zu nehmen. 

Die Entscheidung für diesen Maßstab ist um so einfacher, da wir davon ausgehen können, dass den geblockten Domains kein Schaden entsteht. Dies weil - an Ihrem Beispiel -  12-jährige, 14-jährige oder 16-jährige wahrscheinlich nicht an Ihren Events teilnehmen können.

> Wir haben einige weitere Domains gefunden, welche zu unserem Portfolio gehören ua.:
gay-dresden.de
gaydresden.com

Die Domains werden dann ebenfalls entfernt.

> Generell lässt sich feststellen, dass Ihr sehr viele Domains blockt, welche keine sexuellen Inhalte führen. Der reine Crawler Auswertung der Domain erscheint uns zu willkürlich und unzuverlässig. Ua. Pornblock Liste Nummer 6, Stichwort "Versicherungsexperte", dies ist nur ein Beispiel von vielen.

Ja, das ist richtig, wie oben bereits erläutert. Aber auch hier zeigt sich, dass ich immer noch davon ausgehe, dass unsere Herangehensweise funktioniert. Entsteht dem 14-jährigen Kind oder dem Versicherungsexperte ein Schaden, wenn die Domain für Kids gesperrt ist? Die Antwort dürfte 'Nein' sein.

Evtl. ist nicht allen Nutzern klar, dass die Blocklisten im Pihole nicht automatisch für alle Nutzer gelten müssen. Der sog. Default-User bekommt die Pornlisten und damit sind alle Kinder im Netzwerk sowie auch Gäste und der Kinder "sicher". Aber die Eltern bzw. die Nutzer, die nicht die Pornliste aktiv haben wollen, verschieben sich von der Default Gruppe in eine andere Gruppe. Gleiches gilt für die Glückspiel-Liste und die Liste "child-protection".

Viele Grüße
