### ISSUE TITLE
FP Tabakwebseiten auf Gambling Liste

### ISSUE THREAD

**Issue by KonstiSG** [RPiList/specials#857]
Folgende Einträge sind fälschlicherweise auf der Gambling Liste und haben mit "gambling" nichts zu tun und würden wohl besser auf einer "Tabak" Liste Platz finden:

www.cigarworld.de
www.cigarworld.com
cigarworld.com
decent-cigar.com
www.decent-cigar.com
simplycigars.co.uk
www.cigarmaxx.de
www.cigarre24.de
www.cigarrenversand.de
www.zigarren-bugge.de
www.zigarren-herzog.com
www.zigarren-krueger.de
tabak-goetz.de
www.habana-tabacos.de
www.tabaco.de
www.tabak-goetz.de
www.tabak-heinrich.de
www.tabak.de
www.tabakwaren-brucker.de
www.wolf-tabakwaren.de

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden alle entfernt. Schaue mir mal genauer an, wie die überhaupt auf der Liste landen konnten. Viele Grüße
