### ISSUE TITLE
false entry

### ISSUE THREAD

**Issue by ManfredBrauchle** [RPiList/specials#858]
please remove *spk-schwaben-bodensee.de from the list _spam.mails_ … this is the official url of the bank network

**Comment by dieechtenilente** [comment]
https://www.spk-schwaben-bodensee.de does appear to be the correct domain for Sparkasse Schwabach-Bodensee. They recently renewed their SSL certificate from QuoVaids and it looks okay

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings
