### ISSUE TITLE
Falsche Einträge und doch www Subdomains vorhanden?

### ISSUE THREAD

**Issue by Kristall97** [RPiList/specials#859]
DomainSquatting1:
www.hetzner.com
www.lieferando.de
www.instant-gaming.com

Leider sind in den gesplitteten Dateien sehr viele www Subdomains drinnen.
Macht das Sinn diese mitzunehmen?

**Comment by dieechtenilente** [comment]
Die Seiten leiten sogar auf die www.* Domain um, also ergeben diese Einträge keinen Sinn.

**Comment by RPiList** [comment]
Die o.g. Domains wurden entfernt.

Die DomainSquatting List ist ja schon über ein Jahr alt und insoweit wurden bis gestern auch immer die www. Domains hinzugefügt.

Die www. Domains ergeben in bestimmten Umfang auch Sinn. Können wir ja morgen im Stream noch mal besprechen.
