### ISSUE TITLE
False Positive customercontrolpanel.de

### ISSUE THREAD

**Issue by dieechtenilente** [RPiList/specials#860]
The following domains are blocked in the "DomainSquatting" blocklist but are associated with netcup GmbH.

 * customercontrolpanel.de
 * www.customercontrolpanel.de

https://www.netcup.de/
https://www.netcup-wiki.de/wiki/Kategorie:CCP

**Comment by MilchreisMitZimt** [comment]
- edeka.de
- thalia.de

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Alle Domains wurden entfernt.
