### ISSUE TITLE
lieferando.de in DomainSquatting1

### ISSUE THREAD

**Issue by Todsuende** [RPiList/specials#864]
It looks like, there is the original Site in there to.

**Comment by RPiList** [comment]
Hi,

thx for letting us know. Domain has been removed. Greetings

**Comment by ErdbeerbaerLP** [comment]
It is back again
(just did update)

![image](https://user-images.githubusercontent.com/27149563/205746370-907f3eb0-d770-4727-a992-9017b1379ce5.png)

**Comment by RPiList** [comment]
And again, Domains have been deleted. But I don't know why it reappeared in the first place...
