### ISSUE TITLE
Viele Domains von Sparkassen blockiert

### ISSUE THREAD

**Issue by rockermeier** [RPiList/specials#867]
Die offizielle Website der Sparkasse Landshut ist in der Blockliste spam.mails

sparkasse-landshut.de
www.sparkasse-landshut.de

**Comment by rockermeier** [comment]
Es sind offenbar noch mehr Sparkassen betroffen, u.a.:

sparkasse-regensburg.de
www.sparkasse-regensburg.de

sparkasse-passau.de
www.sparkasse-passau.de

uvm.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden entfernt. Viele Grüße
