### ISSUE TITLE
Sparkasse gesperrt

### ISSUE THREAD

**Issue by Kristall97** [RPiList/specials#868]
Hallo,

www.kskgg.de
kskgg.de

Der Ersteller der Sparkassen Domains hat anscheinend alles mit WWW auch nochmal angefragt.
Obwohl ja von Sempervideo vorgegeben wurde, dass dies nicht zu machen ist.

Dazu stehen auch die richtigen Domains in den Listen drinnen.

Bitte diese raus löschen.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden entfernt. Viele Grüße
