### ISSUE TITLE
Unklare Anweisungen

### ISSUE THREAD

**Issue by DanielOberlechner** [RPiList/specials#870]
Ich lade gerade das 6GB Image herunter warum auch immer, und die gezeigten Informationen vom SemperVideo stimmen leider auch nicht mehr herein..
Hat hier jemand vielleicht einen etwas 'idiotensicheren' Link bzw. Anweisung wie man das richtig macht?

 Mir ist leider mein Server abgeschmiert und die Daten sind nun anscheinend verloren ...

Mit freundlichen Grüßen
Daniel Oberlechner

**Comment by RPiList** [comment]
Hi,
um da zu helfen bräuchte ich genauere Infos wo die Unterschiede sein sollen.
Zw. dem alten und dem neuen (6GB) Image, gibt es in Bezug auf Pihole keine Unterschiede. Insoweit funktionieren die alten Videos noch.

Die Unterschiede durch Docker & Co. sind in der dem ZIP beiliegenden Info-Datei erläutert.

Viele Grüße

**Comment by RPiList** [comment]
Das neue 6GB Image wird genauso installiert, wie Sie das alte Image "installiert" haben. Da hat sich nichts geändert. Danach funktioniert alles genauso wie es nach dem Einrichten des alten Image ursprünglich funktioniert hat.

Videos dazu wurden vor 3 Jahren erstellt.

Viele Grüße
