### ISSUE TITLE
False-Positive for learn.cisecurity.org

### ISSUE THREAD

**Issue by IAreKyleW00t** [RPiList/specials#876]
`learn.cisecurity.org` is a domain used to provide downloads for the PDF versions of the CIS benchmark.

--- 

`learn.cisecurity.org` ist eine Domain, die verwendet wird, um Downloads für die PDF-Versionen des CIS-Benchmarks bereitzustellen.

**Comment by RPiList** [comment]
This domain has been classified as cname tracking domain by the AdguardTeam. When they change their classification, it will be automatically updated on our list too.
