### ISSUE TITLE
svpihole2212 Logdaten

### ISSUE THREAD

**Issue by defr0ke** [RPiList/specials#878]
Hallo...

Bezüglich ihrer svipihole2212 Instanz:

Im Pi-hole Protokoll sind noch ihre Anfragedaten vom 05.11. bis 24.11.  vorhanden. Außerdem stehen bei "Netzwerk" all ihre Geräte mit IP-, Mac-Adresse und Schnittstelle drin.

Sie reden in Ihren Videos ständig über Datenschutz, warnen die Zuschauer vor Idenditätsdiebstahl und bieten Blocklisten an, wo alles mögliche geblockt werden kann. Sie sind Verfechter von Sicherheit, Schutz der Nutzerdaten usw.

Aber bieten öffentlich Zugriff auf Ihre eigenen Netzwerkdaten, indem man nur "svpihole" installieren muss.

Klar, könnte man sagen, die meisten Nutzer können mit den vorhandenen Infos nicht viel anfangen. Das gilt aber nicht für versierte Cyberkriminelle die mit solchen Daten ihrem illegalen Geschäft nachgehen.

**Comment by mschabhuettl** [comment]
Hallo!

Also wenn Sie die alte FTL-Datenbank stört, können Sie die DB auch ganz einfach löschen (https://www.reddit.com/r/pihole/comments/s7u6ca/guide_how_to_clear_all_pihole_logs/):
```
sudo service pihole-FTL stop
sudo rm /etc/pihole/pihole-FTL.db
sudo service pihole-FTL start
```

Und die entsprechenden Logs bei Bedarf. Siehe: https://scotthelme.co.uk/the-first-ever-issue-with-my-pi-hole/

LG

**Comment by RPiList** [comment]
Vielen Dank für die Info.

Werde zusehen, dass es beim nächsten Update vorher entfernt wird.

Die Daten selbst dürften aber keine Probleme darstellen. Die Daten in der DB sind die DNS-Anfragen die bei der Installation von Docker und den entsprechenden Containern angefallen waren.

Aber trotzdem sollte die DB vor der Auslieferung gelöscht werden. Viele Grüße
