### ISSUE TITLE
Phishing

### ISSUE THREAD

**Issue by Henriks9** [RPiList/specials#879]
https://unhooklines.info/d712d5a06d06bee2d49d9878496e2958

**Comment by mschabhuettl** [comment]
Hallo!

Also ein bisschen mehr Info wär vielleicht nicht schlecht. Ausserdem zeigt die Seite auf eine (etwas seltsame) 404-er.

LG

**Comment by RPiList** [comment]
Ich gehe davon aus, dass auf der Seite Phishing-Seiten lagern, die recht schnell routiert werden können. Vielen Dank und viele Grüße
