### ISSUE TITLE
IP detection gives 2 lines

### ISSUE THREAD

**Issue by freezly** [RPiList/specials#88]
Hi SVPI-hole team,

I had problems with the PI image:

Within the script "mylanip" is a detection for IPV6 address. When I execute this line on my PI it gives me 2 lines of IPV6 addresses (seccond is shorter ... cannot find, why). The problem is, that the propertiy file which should be filled with this information is broken if there are more than one line and svpihole doesn't start anymore.

I got a second problem: "apt-get update" doesn't work, so pi-hole update was also not possible. There was an errormessages regarding a corrupt status file. I can't find why, because a "diff" with the 'old' version gives me: is a binary file". 

I don't have the exact error messages for both problems anymore. I had too much problems with your image, so I installed pi-hole manually on a clean raspbian image. So this issue is only for your information. If you have questions, feel free to ask.

Thanks
Denis

**Comment by RPiList** [comment]
Hi,

thank you very much for your feedback. 

We will monitor this issue, but we never had a user with two lines of IPv6 addresses.

The fix would have been to edit the setup*.conf in the pihole directory to get pihole running.

But if you know what you are doing, we always encourage users to install pihole by themselves.

Can you name me your internet provider? Maybe it's a provider thing...

Greetings.

**Comment by freezly** [comment]
My internet provider is kabel deutschland. 

following some output from my PI fyi. IP addresses are manually veiled a bit by me:

`
pi@raspberrypi:~ $  ip addr show dev eth0 | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d'                                                                                                 
2f22:810e:903f:efa0:3ab5:1e94:106f:f2dd                                                                                                                                               
f2ff::58bb:efa5:fdec:ada1                                                                                                                                                             
pi@raspberrypi:~ $ ip -6 addr                                                                                                                                                         
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000                                                                                                                       
    inet6 ::1/128 scope host                                                                                                                                                          
       valid_lft forever preferred_lft forever                                                                                                                                        
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000                                                                                                                
    inet6 2f22:810e:903f:efa0:3ab5:1e94:106f:f2dd/64 scope global dynamic mngtmpaddr noprefixroute                                                                                    
       valid_lft 5040sec preferred_lft 2340sec                                                                                                                                        
    inet6 f2ff::58bb:efa5:fdec:ada1/64 scope link                                                                                                                                     
       valid_lft forever preferred_lft forever 
`

This line gives me only the first IP (hopefully it is the correct one): 
`
ip addr show dev eth0 | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d' | sed -n '1!p'
`

Thank you for your work with PIhole. Keep your work up. Its a great thing and more people should use it.

**Comment by RPiList** [comment]
Is it okay, when I create an image with your text-version to grab ipv6 ip AND you would test it for us?

**Comment by freezly** [comment]
Cool, thanks. Yes I can test. Not on the original PI, because there is allready a running PiHole installation, which I don't want to touch. But I have a second PI. Its the same model like the first one.

**Comment by RPiList** [comment]
If you have a second micro-SD-card it would suffice to just switch the
memory card. In and out in a few seconds. :-)

I will create an image and mail you the link.



Am Sa., 22. Feb. 2020 um 20:40 Uhr schrieb freezly <notifications@github.com

**Comment by freezly** [comment]
Sounds good.

**Comment by RPiList** [comment]
Problem sollte gefixt sein. Mehrere Nutzer haben die gleichen Probleme gemeldet. Die kommende Version 2003 sollte das Problem bereinigen.
