### ISSUE TITLE
Phishing Sparkasse

### ISSUE THREAD

**Issue by obakuhl** [RPiList/specials#880]
Hi guys, thanks for your work. I received a SMS a few hours ago with a url and a request regarding Pushtan 2.0, see picture, but this is obviously phishing.

![grafik](https://user-images.githubusercontent.com/1564765/208962148-9f64185f-3da1-445e-8ff7-7741ba901bec.png)

URL: `https://custom247support.de/?tkn=`...

thx.
br Ben

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been added. Greetings
