### ISSUE TITLE
Gelöschte Blocklist DomianSquatting

### ISSUE THREAD

**Issue by leachimus** [RPiList/specials#881]
Hallo zusammen! Die Blockliste
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting
ist gelöscht worden. War das Absicht?

**Comment by RPiList** [comment]
Hi,
die DomainSquatting Listen haben ein großes Update erhalten und sind auf eine neue URL umgezogen. Bitte die alte Adresse im Pihole löschen und die neuen Listen hinzufügen. Vielen Dank und viele Grüße
