### ISSUE TITLE
apple.co seems to be actually legitimate

### ISSUE THREAD

**Issue by macgeneral** [RPiList/specials#883]
apple.co get's used by Apple in macOS 13 (and probably other versions of mac and iOS) as shortcut URL for certain services.

For example if I click on "Service Options..." it takes me to **[https://apple.co/MacBatteryService](https://apple.co/MacBatteryService)**.

![Screenshot 2022-12-26 at 12 33 52](https://user-images.githubusercontent.com/9381035/209544572-c9cad0b7-99a6-4275-a4b8-783b7c3a33ee.jpg)

It's currently listed in the **[notserious](https://github.com/RPiList/specials/blob/master/Blocklisten/notserious)** list.

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings
