### ISSUE TITLE
Phishing auf Sparkassenkunden: https://tan-synchronisierung.com/de/sp/index4.php

### ISSUE THREAD

**Issue by RichardBeisser** [RPiList/specials#888]
Hallo,

die URL
https://tan-synchronisierung.com/de/sp/index4.php
wird gerade per SMS verbreitet.
Bitte in die entsprechenden Listen mit aufnehmen.

Danke.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße
