### ISSUE TITLE
e8218.dscb1.akamaiedge.net

### ISSUE THREAD

**Issue by p1r473** [RPiList/specials#890]
This is just a CNAME for a bunch of OSCP domains
ocsp.verisign.com
ocsp.thawte.com
ts-ocsp.ws.symantec.com

**Comment by RPiList** [comment]
Not quite sure what the issue is. Do want the domain to be blocked or is it blocked and you want to unblock it?

**Comment by p1r473** [comment]
I think we should whitelist it

**Comment by RPiList** [comment]
Domain has been removed from the easylist. Thx for letting us know. Greetings.
