### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by rube200** [RPiList/specials#893]
This domain('cdn.weasy.io') is marked as block in this list https://github.com/RPiList/specials/blob/master/Blocklisten/Phishing-Angriffe but it should not be block since it provide content like images.

Found from:
https://xiaomistore.pt/pt/produtos/auriculares-xiaomi-buds-3t-pro
https://cdn.weasy.io/users/xiaomi/catalog/6934177746369_buds_3t_pro_gloss_white_03.png

**Comment by RPiList** [comment]
Thx for bringing this up. Domain has been removed. Greetings.
