### ISSUE TITLE
false positive - neueraeume.jetzt

### ISSUE THREAD

**Issue by jfastnacht** [RPiList/specials#895]
I don't know why it is on your blocklist and I could not find it in any of your sources, so please remove `www.neueraeume.jetzt` and `neueraeume.jetzt` from https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails

**Comment by RPiList** [comment]
Spam.mails entries are usually reported by users getting spam. Domains have been removed. Greetings
