### ISSUE TITLE
false positive: go.powunity.com

### ISSUE THREAD

**Issue by andreasbrett** [RPiList/specials#896]
This is part of the web app for a bike tracking app (used for tracking thieves). It is not a malicious app. Listed as malware in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware.

**Comment by RPiList** [comment]
Hi,

the domain is still being listed as malicious by the adware team. Some sources consider tracking as an attack. 

It will be automatically removed when the adware teams removes the url as well. 

Greetings
