### ISSUE TITLE
false positive jetzt-fuer-morgen.de

### ISSUE THREAD

**Issue by thisni1s** [RPiList/specials#897]
Hi, 
the domains ```jetzt-fuer-morgen.de``` and ```www.jetzt-fuer-morgen.de``` are on one of your blocklists.
(https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails)

They are valid domains from a German foundation and i do not see a reason for them being blocked. 

Would be great if you can remove them :)

**Comment by RPiList** [comment]
Hi,
showing up in a list does not mean, that they are invalid domains. Being listed in the spam.mail list just means, that various users reported the domain as a spam domain.

**Comment by thisni1s** [comment]
Yeah i get that, bad wording on my part.
Still the domain should not be on the block list imo
