### ISSUE TITLE
Fake Regierungsseite

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#900]
**Phishing**
Seite gibt sich als luxemburgische Regierung aus und versucht Geld von Unwissenden Nutzern durch gefälschte Rechnung abzuziehen.

Wäre einmal folgender Link zum Blocken:
guichetlu-lux.de

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain ist jetzt in der Phishing-Liste. Grüße
