### ISSUE TITLE
[False Positive] updates.cdn-apple.com

### ISSUE THREAD

**Issue by ZepDonald** [RPiList/specials#901]
Die URL oben ist für die Updates von diversen Apple-Systemen.

Es gab bereits zwei Issues, dass die URL von der Liste spam.mails entfernt werden soll, die URL ist aber wieder enthalten. Siehe #847 und #850

Bitte wieder von der Liste entfernen. Es wäre auch super, wenn die URL nicht wieder aufgenommen wird (keine Ahnung, warum das immer wieder passiert), falls sich das irgendwie verhindern lässt.

Danke! :)

**Comment by RPiList** [comment]
Domain wurde entfernt. Es ist auch bekannt, warum die Domain immer wieder vom Crawler erfasst wird. Ist aber zu komplex um das hier zu schreiben. Wenn Erklärung nötig, dann einfach mal im Twitch-Stream fragen. Viele Grüße.
