### ISSUE TITLE
False positive for world.std.com

### ISSUE THREAD

**Issue by mschabhuettl** [RPiList/specials#903]
Hi

I've noticed that following domain: world.std.com is included in pornblock4:

> Exact match for world.std.com found in:
>  - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4

world.std.com (and in fact std.com too) redirect to theworld.com now.

I actually found this cause I wanted to visit: https://world.std.com/~reinhold/diceware.html

On this website there's a guide on secure password generation, called [Diceware](https://en.wikipedia.org/wiki/Diceware). Which is in fact the original site of Arnold G. Reinhold on this topic. Also quoted on [Wikipedia](https://en.wikipedia.org/wiki/Diceware#cite_note-4) as reference Number [4.]:

> ["Diceware wordlist"](https://web.archive.org/web/20161205210511/http://world.std.com/~reinhold/diceware.wordlist.asc). world.std.com. Archived from [the original](https://world.std.com/~reinhold/diceware.wordlist.asc) on 5 December 2016. Retrieved 4 December 2016.

So please remove world.std.com as some Diceware-Lists still reference this domain and not the "new" theworld.com

Diceware is in fact an interesting topic on random password generation. The YouTube Channel Computerphile also alluded to this. Look here: https://www.youtube.com/watch?v=Pe_3cFuSw1E

Might also be an interesting Video-Idea.

Cheers,
Matthias

Edit 1: Mixed up new and old domain. Corrected.
Edit 2: history explanation

**Comment by RPiList** [comment]
Hi,
thx for letting us know. Domain has been removed. Greetings.
