### ISSUE TITLE
False-positive Intuit Quickbooks Workforce

### ISSUE THREAD

**Issue by nwh3365** [RPiList/specials#906]
RPiList-Phishing, parsed and mirrored by https://firebog.net
Updated 28JAN23 from https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
List corrections can be requested at https://github.com/RPiList/specials/issues

links.notification.intuit.com
This domain is used in email notifications sent via Intuit Quickbooks Workforce to notify users that new documents (e.g., pay stubs, tax forms, etc.) are available for download in their accounts.

**Comment by RPiList** [comment]
Hi, 

thx for letting us know. Domain has been removed. Greetings
