### ISSUE TITLE
Next malicious link

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#907]
Hallo, 

Ich hätte einen weiteren Link für unsere Malware Blacklist. Auch hier wird dem Benutzer der Download von Spyware unterjubelt

ihelp247.us

Liebe Grüße

**Comment by SpielenmitLili** [comment]
Zusätzlich Phishing auf Domain:

web9826.web07.bero-webspace.de

Grund: Gefakte IHK-Seite

Wäre auch etwas für die Liste

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info. Beide Domains sind den jeweiligen Domains hinzugefügt worden. Viele Grüße
