### ISSUE TITLE
Domainsquatting

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#908]
Hallo zusammen,

wieder mal ein Link für die Domainsquattingliste.
Heute frisch reinbekommen.

Heute mal ein Versuch an die Twitch Accountdaten ranzukommen:
twltch.us

Liebe Grüße

**Comment by SpielenmitLili** [comment]
Soeben noch einen zweiten erhalten auf demselben Wege.
Ist dann ebenfalls für die Domainsquattingliste:

twltch.co

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße
