### ISSUE TITLE
Phishing links; Malware links

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#911]
Weitere Links entdeckt bei heutigen Recherchen in Tiefen des Internets

Einmal Phishing (Seite gibt sich als offizielle Supportseite von Geeksquad um Daten von Benutzern zu erhalten)
geeksquadpsupport.weebly.com

Malware (unter folgender Domain wird dem Benutzer Download von Spyware angedreht)
bcare.pro

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden hinzugefügt. Viele Grüße
