### ISSUE TITLE
Links für Blacklist

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#914]
Unseriöse Domains (zeigen gefälschte Banner von Antivirenprogrammen wie Avira um eine Virusinfektion vorzutäuschen)

hodmcn.click
toppillarrect.com
newssysstem.net
rvht9.gprk.pro
sl31a.gprk.pro
investment-articles.com
www44.nathanaeldan.pro
www90.nathanaeldan.pro
www94.nathanaeldan.pro
www36.orvilleandrea.pro

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Domains. Wurden der Schadware-Liste hinzugefügt. Viele Grüße
