### ISSUE TITLE
Game Tracking Liste hinzufügen?

### ISSUE THREAD

**Issue by LierschIT** [RPiList/specials#916]
Vielleicht kann man die Game Tracking Liste von https://github.com/KodoPengin/GameIndustry-hosts-Template/blob/master/Gaming-Mini-Template/hosts mit hinzufügen?

[game_tracking_block - Kopie.txt](https://github.com/RPiList/specials/files/10611656/game_tracking_block.-.Kopie.txt)

Grüße

**Comment by RPiList** [comment]
Hi,

vielen Dank für den Hinweis.

Ist wahrscheinlich das Beste, wenn wir dafür eine eigene Trackingliste erstellen. Wollte ich bis jetzt eigentlich vermeiden, da solche Listen immer einen sehr hohen Duplikat-Faktor mit der Schadware-Liste haben. Viele andere Maintainer betrachten Tracker als Schadware...

Viele Grüße
