### ISSUE TITLE
Blocklisten Domain Squatting CH - Auch regulare Domainnames enthalten

### ISSUE THREAD

**Issue by HiltiRaceteam** [RPiList/specials#918]
Die Domain Squatting Listen für die Schweiz enthalten auch reguläre Domains dazu gehören unter anderem:

www.ubs.com
ubs.com

www.credit-suisse.com
credit-suisse.com

Besten dank für die Entfernung der Einträge.

**Comment by erichstoeckli** [comment]
Auch die Schweizerische Bundesbahnen sind fälschlicherweise enthalten:
[sbb.ch](url)
[www.sbb.ch](url)

**Comment by RPiList** [comment]
Vielen Dank für die Hinweise und sorry für den Fehler. Domains wurden entfernt. Viele Grüße.
