### ISSUE TITLE
Google.com und Apple.com in den Blocklisten?

### ISSUE THREAD

**Issue by Twisterado** [RPiList/specials#92]
Hi,
Stichprobenartig ist mir aufgefallen, dass www.google.com und auch www.apple.com in notserious oder auch PhishingAngriffe gelistet sind.
Was hat es damit auf sich?
Die Domains kann man natürlich wieder whitelisten, aber insbesondere google.de bzw. .com behindern das normale Surfen schon enorm, also haben die da glaube ich nichts zu suchen :)
Grüße

**Comment by RPiList** [comment]
Die Begriffe sind bei mir nicht (mehr) drin. Phishing habe ich noch mal
aktualisiert.

Am Do., 20. Feb. 2020 um 20:41 Uhr schrieb Thomas N. <
notifications@github.com>:

**Comment by Twisterado** [comment]
Ja, jetzt sind sie bei mir auch raus.
Ich hab die Commits mal ein bisschen durchgesehen, ist es wirklich tragbar, dass immer jemand manuell nach false positives wie Google.com und Instagram.com sucht?
Das Projekt ist ja auch insbesondere für Leute gedacht, die sich nicht ständig damit auseinandersetzen möchten/können.
Könnte man nicht eine Möglichkeit finden, das zu unterbinden bzw. automatisch zu bereinigen?

**Comment by RPiList** [comment]
Ja, das überlegen wir derzeit auch.

So wie zur Zeit ist es wohl kaum nutzbar. Dass die Domains auf der
Phishing-Liste landen ist klar. Haben wir auch schon in einem Video
gezeigt, dass man Google-Drive als Phishing-Site nutzen kann.

Insoweit wundert das nicht. Aber die dann alle automatisch zu finden und zu
entfernen ist nicht möglich. Jetzt fällt uns evtl. Google und Apple recht
schnell auf. Aber Spotify stand auch drauf und danach sucht nicht jeder...

Das eigentliche Problem sind dabei nicht die False-Positives, die man evtl.
rausfiltern könnte, sondern die Tatsache, dass die definitv nach dem
nächsten Update wieder da sind und immer wieder erneut entfernt werden
müssen.

Naja... wir geben der Liste noch ein paar Versuche, sonst wird die wieder
entfernt.

Am Do., 20. Feb. 2020 um 21:31 Uhr schrieb Thomas N. <
notifications@github.com>:

**Comment by Twisterado** [comment]
Wie genau wird die Liste denn gesammelt?
Wenn es genug Leute gibt, die false positives melden, hätte man ja innerhalb kurzer Zeit die Wichtigsten zusammengetragen und könnte diese von einem Script vor dem Upload aus der Liste entfernen!?

**Comment by RPiList** [comment]
Die Liste wird durch Internet-Dienste erstellt, die in dem Bereich tättig
sind. Über deren API erhalten wir dann z.B. folgende Meldung:

19:46 Uhr
new #phishing at http://winedownweekends[.]com/ | 210[.]16[.]102[.]149 |
India |
22:35 Uhr
new #phishing at http://158[.]197[.]95[.]34[.]bc[.]googleusercontent[.]com/
| 34[.]95[.]197[.]158 | United States | GOOGLE |

Wir "extrahieren" dann nur die Domain...

Viele Grüße

Andreas






Am Do., 20. Feb. 2020 um 23:17 Uhr schrieb Thomas N. <
notifications@github.com>:

**Comment by DjCrays** [comment]
Ich weiß ja nicht ob das das problem lösen würde, aber könnte man nicht einfach sagen man nutzt die Top 100 ALEXA-Liste an seiten + halt noch einmal ne whitelist-Liste die man ja auch regelmäsig bei nem Updatescript hinzupacken könnte?

Siehe: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212
https://github.com/anudeepND/whitelist (https://github.com/anudeepND/whitelist)
20. Februar 2020 23:49, "RPiList" <notifications@github.com (mailto:notifications@github.com?to=%22RPiList%22%20<notifications@github.com>)> schrieb:
Die Liste wird durch Internet-Dienste erstellt, die in dem Bereich tättig
sind. Über deren API erhalten wir dann z.B. folgende Meldung:

19:46 Uhr
new #phishing at http://winedownweekends (http://winedownweekends)[.]com/ | 210[.]16[.]102[.]149 |
India |
22:35 Uhr
new #phishing at http://158[.]197[.]95[.]34[.]bc[.]googleusercontent[.]com/
| 34[.]95[.]197[.]158 | United States | GOOGLE |

Wir "extrahieren" dann nur die Domain...

Viele Grüße

Andreas
Am Do., 20. Feb. 2020 um 23:17 Uhr schrieb Thomas N. <
notifications@github.com (mailto:notifications@github.com)>:

**Comment by RPiList** [comment]
Ich stelle gleich mal eine Datei ein, die als Whitelisting-Datei gegen alle Listen geprüft werden soll. Die Nutzer können dann Einträge hinzufügen (über Pull Request), wenn eine wichtige Domain fehlt.

Die Alexa Top 100 oder 1000 zu importieren würde nicht viel bringen, weil da z.B. auf Platz 47 eine Domain steht, die explizit in einer der Listen geblockt werden soll.

Viel wichtiger sind die Domains, die NICHT in Alexa stehen, aber trotzdem wichtig sind. Z.B. die Google-Usercontent-Pages. Klar, kann jemand auf seinen eigenen Seiten dann z.B. Porn anbieten. Aber deswegen halt alle Seiten zu sperren, würde ich als Overkill betrachten. 

Gleiches gilt für die Linkverkürzer. Diese stellen mitunter eine große Gefahr dar, wie schon in mehreren Videos gezeigt. Aber der Linkverkürzer amzn.to verweisst immer nur auf Shopping-Seiten von Amazon. Da kann nicht viel passieren. 

Beide dieser Domains sind wichtig, findet man aber nie in den Top1000. Das sind die "wichtigen" Domains die dringend in die Liste müssen.

**Comment by RPiList** [comment]
Whitelist ist online.
