### ISSUE TITLE
"api-app.wetteronline.de" should be removed from "specials/master/Blocklisten/spam.mails"

### ISSUE THREAD

**Issue by Muffexx** [RPiList/specials#922]
Hello.

The domain "api-app.wetteronline.de" should be removed from "specials/master/Blocklisten/spam.mails" because it is necessary for the [Weather&Radar Android app](https://play.google.com/store/apps/details?id=de.wetteronline.wetterapp&hl=en-us) to work.

regards

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.
