### ISSUE TITLE
The swiss domain squatting blocklist hits false positives for raiffeisen ebanking

### ISSUE THREAD

**Issue by CraftingDragon007** [RPiList/specials#923]
When you enable the [https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting/CH/H-R](https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting/CH/H-R) blocklist, the real Raiffeisen eBanking site is blocked.

**Comment by RPiList** [comment]
To remove a domain we have to know which domain is blocked. Greetings.

**Comment by CraftingDragon007** [comment]
The falsly blocked domain is [login.raiffeisen.ch](https://login.raiffeisen.ch)

**Comment by RPiList** [comment]
Hi,

the domain login.raiffeisen.ch is currently not on any of our blocklists. But it might have been previously. If you are sure there is no typo in your domain, please update your pihole-lists.

Greetings
