### ISSUE TITLE
Cronjob für regelmässiges Aufräumen der FTL.db

### ISSUE THREAD

**Issue by mhuber665** [RPiList/specials#924]
Viele User kriegen häufig die Fehlermeldung: Disk shortage (/etc/pihole/pihole-FTL.db) ahead: 96% used
Teilweise können Updates deshalb nicht durchlaufen.
Evtl. lässt sich das Problem mit einer regelmäßigen Routine beheben?

**Comment by Tuxtom007** [comment]
sudo service pihole-FTL stop
sudo sqlite3 /etc/pihole/pihole-FTL.db 'VACUUM
sudo service pihole-FTL start

das ganze in eine Script verpacken, regelmässig ausführen, bevor der Speicherplatz zu gering wird.
( ist aus dem PiHole Forum )

**Comment by RPiList** [comment]
Das ist eigentlich eine Funktion, die ins Pihole selbst gehört. Und mit der rotation Datei gibt es dass auch schon für Logdatein.
Warum die FTL-Datei nicht entsprechend ebenfalls berücksichtigt wird, kann ich nicht nachvollziehen.
Das Problem entsteht ja "nur" wenn die Datei für den Speicherplatz problematisch wird.
Also wann sollten wir die Datei triggern? 1x pro Woche? 1x pro Monat?

Kann für den mit der zu kleinen SD-Karte schon zu lang sein... und dem anderen löschen wird die DB regelmäßig und killen damit wertvolle Daten...

**Comment by LizenzFass78851** [comment]
Es gibt auch eine möglichkeit nur die Datensätze aus der pihole-FTL.db zu löschen die z.b. älter sind als 30 Tage.

```
service pihole-FTL stop


sql="SELECT count(*) FROM query_storage; "
sql+="DELETE FROM query_storage WHERE timestamp <= strftime('%s', datetime('now', '-30 day')); "
sql+="VACUUM; "
echo "$sql" | sqlite3 /etc/pihole/pihole-FTL.db


service pihole-FTL start
```

Die idee ist eine Ergänzung von https://discourse.pi-hole.net/t/delete-queries-error/53761
Zur der ursprünglichen idee von https://discourse.pi-hole.net/t/tip-how-reduce-db-stat-size/26070

**Comment by c0by85** [comment]
> sudo service pihole-FTL stop sudo sqlite3 /etc/pihole/pihole-FTL.db 'VACUUM sudo service pihole-FTL start
> 
> das ganze in eine Script verpacken, regelmässig ausführen, bevor der Speicherplatz zu gering wird. ( ist aus dem PiHole Forum )

Funktioniert, schrumpft um die "Häfte". 
```
-rw-rw-r-- 1 pihole pihole 1.4G Feb 25 10:49 /etc/pihole/pihole-FTL.db
-rw-rw-r-- 1 pihole pihole 773M Feb 25 10:50 /etc/pihole/pihole-FTL.db
```

Aber gibt nen Typo. Hier der Fix. Ein ' fehlte.
```
sudo service pihole-FTL stop
sudo sqlite3 /etc/pihole/pihole-FTL.db 'VACUUM'
sudo service pihole-FTL start
```

So lange bis es ggf. eine offizielle Lösung gibt.

**Comment by thomasmerz** [comment]
Warum lasst ihr den Pi-hole die FTL.db eigentlich nicht selber aufräumen? 🤔 

# https://docs.pi-hole.net/ftldns/configfile/
```
MAXLOGAGE=24.0
DBIMPORT=yes
#MAXDBDAYS=365
MAXDBDAYS=100
DBINTERVAL=1.0
DBFILE=/etc/pihole/pihole-FTL.db
```

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Das ist genau der Schaltern, den wir gesucht haben. Scheint ja default-mäßig drin zu sein.

Vielen Dank für die Mühen. Viele Grüße
