### ISSUE TITLE
yet another blocklist

### ISSUE THREAD

**Issue by al1ce23** [RPiList/specials#926]
Hallo,
danke erstmal für dieses nützliche Projekt! Ich pflege eine persönliche Blockliste die aus "bösen" Hosts einer Unternehmens-Firewall resultiert. Kann gerne benutzt werden: https://raw.githubusercontent.com/al1ce23/bad_hosts/main/bad_hosts.md

**Comment by RPiList** [comment]
Hi,

vielen Dank für das Angebot. Das Pihole, das unsere Blocklisten nutzt, ist ein DNS-Resolver. Wird also nur angesprochen, wenn es eine Domain auflösen soll. Bei einer IP würde das Pihole nicht angesprochen werden können. Insoweit können Blocklisten aus IPs leider nicht eingepflegt werden. 

Trotzdem vielen Dank für das Angebot. Viele Grüße
