### ISSUE TITLE
Valide Domain aus Blockliste entfernen

### ISSUE THREAD

**Issue by savernation** [RPiList/specials#928]
Bitte die Domain sparda-n.de aus der Blockliste https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/sonstige_Banken/Sparda-Bank entfernen, da diese valide ist. Vielen Dank!

**Comment by RPiList** [comment]
Hi,

um eine Domain zu entfernen brauche ich die genaue Domain die zu entfernen ist.

**Comment by savernation** [comment]
Die genaue Domain lautet https://[www.sparda-n.de](https://www.sparda-n.de/)/ und befindet sich in Zeile 20343 und 19818 der Blockliste https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting/DE/sonstige_Banken/Sparda-Bank

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domains wurden entfernt. Viele Grüße
