### ISSUE TITLE
PiHole and Android

### ISSUE THREAD

**Issue by freezly** [RPiList/specials#93]
Do you have an idea for following problem?

I have pihole in fritzbox configured. PiHole works fine with my linux PC. But two Android devices  (GalaxyS7 and HuaweiP30Pro) doesn't work with pihole. Domains on blacklists are available in browser. The query within pihole doesn't show my requests.

In settings of both devices dhcp is enabled like on my linux pc. When I change to static I can see two dns servers configured. First the pihole and second 8.8.4.4. I don't know why google dns is setted here ... maybe this is the problem, but I don't know how to solve it.

Additionally I changed DNS server for IPv6 to the pihole but this doesn't change anything.

**Comment by RPiList** [comment]
Where, in your Fritzbox, is your Pi-DNS configured? Is it configured as
Local-DNS or WAN-DNS?

If you give and Android the 8.8.4.4 DNS, it might prefer it because it
recongnizes it. I would delete it and force Android to use Pi-hole.

Am Do., 20. Feb. 2020 um 20:48 Uhr schrieb freezly <notifications@github.com

**Comment by freezly** [comment]
I made exaclty the steps which are shown in your documentation: https://github.com/RPiList/specials/tree/master/RouterKonfiguration/Fritz!Box%206490%20Cable

Unfortunately my statement regarding "on linux it works" is not correct anymore. Sometimes dns resoulution is successful and pihole has no entry in query for my dns request.

Configuration of every device is not possible for me. The big advantage of pihole was the transparent dns filter possibilities without changing anythin in devices.

**Comment by beerisgood** [comment]
@freezly test your Android phone with that site:
https://dnsleaktest.com/

If it display different server, you config that or Android itself use Google DNS as fallback. Then you need to config it to your needs / or use a App which enforce the change.

**Comment by freezly** [comment]
Thanks for your hint: Strange ... Android and Linux shows only 1 server. But the Android device doesn't appears in query log of pihole.

**Comment by freezly** [comment]
Maybe I found my problem. In browser I use "www."[EVILPORNDOMAIN.COM] ... but in blacklist the domains dont have "www." prefix.

If I use it without "www" in my browser the domain is blocked. This is not very optimal. is there a simple possibility to configure, that "www" is also blocked if domain is blocked?

**Comment by beerisgood** [comment]
> 
> is there a simple possibility to configure, that "www" is also blocked if domain is blocked?
>
Sure. Add the www domain to your blacklist

**Comment by freezly** [comment]
ok. *smile* ... this is not the simple solution I meant. :) My Pihole has actually over 2Mio blacklist entries ... when I want to update all domains with www it will be a full time job.

Am I the only one who has this behavior? Blocked domains without "www" seems to be a bit useless. If I am not the only one, and more people want to blacklist domains with "www" I could create a script to parse the existing blacklists and enrich it with the same domains + www-prefix. what do you think of it?

**Comment by RPiList** [comment]
Yes, www.evilshit.com can be on a completely different server as evilshit.com. So regarding to Pi-hole, it is as different as www.goodstuff.de.

As suggested, you could ad the www-subdomain. But you cant add it to the original list, since it would be overwritten by the next update.

Because of that, every entry on our main lists has each entry with www. and without.

Is it the porn-list with the missing www? We could copy the list and add www. in front of every domain.

**Comment by freezly** [comment]
> Is it the porn-list with the missing www?

Yes. I tested it with different domains from this list. Yes, it would be cool, if you can provide this list with www.

**Comment by RPiList** [comment]
We have created a list which is to be used as an addition to Chad's List.
You can find it at
https://raw.githubusercontent.com/RPiList/specials/master/wwwpornblock

Am Sa., 22. Feb. 2020 um 20:38 Uhr schrieb freezly <notifications@github.com

**Comment by freezly** [comment]
thank you very much
