### ISSUE TITLE
(www.)nitrokey.com ist eine valide Domain

### ISSUE THREAD

**Issue by mangobananenkeks** [RPiList/specials#930]
nitrokey.com und www.nitrokey.com ist eine valide Domain von Nitrokey - einem Hersteller/Händler von security-Tokens (Fido2, PGP, etc.), sicheren Smartphones (u.a. ausgelötete Sensoren/Kameras/Mikrofone), Firewalls, etc.
Wäre nett, wenn die beiden Domaineinträge von der Liste entfernt werden würden.

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße
