### ISSUE TITLE
[False Positive] dlf24-appapi.dradio.de

### ISSUE THREAD

**Issue by D3rHase** [RPiList/specials#931]
Domain wird von der [DLF Nachrichten App](https://www.deutschlandfunk.de/apps-100.html) benötigt. 
Gefunden in [spam.mails](https://github.com/RPiList/specials/blob/master/Blocklisten/spam.mails).

Danke :)

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
