### ISSUE TITLE
Please removed nitrokey from Phishing

### ISSUE THREAD

**Issue by 103058167** [RPiList/specials#932]
Nitrokey is an official business who create and sell nitrokeys, There are many users who buy and use it.

They aren't shown on Phishstats.info as one of the phishing sites.

Please remove nitrokey.com and www.nitrokey.com from 
https://v.firebog.net/hosts/RPiList-Phishing.txt

**Comment by RPiList** [comment]
Hi,
thanks for letting us know. Domain has been removed.

The really strange thing is, we already had it removed two days ago but it got reported as phishing again.

Let's if it gets reported again. Greetings.

**Comment by jans23** [comment]
It is still (or again) on that list. What to do?

**Comment by RPiList** [comment]
It's not on our list at the moment (or in the last 8 hours). If it is still on your list, it means you need to do an update of your list in your pihole or another list, you are using, is importing the domain to your pihole. Greetings.
