### ISSUE TITLE
Malware/Spyware

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#936]
Guten Abend,

auch heute habe ich einen Link unter dem Benutzern der Download von Malware und Spyware aufgedrückt wird.

Wäre einmal der folgende Link:
ncsupport.online

Bitte wenn möglich einmal auf die Blockliste setzen

Danke

**Comment by SpielenmitLili** [comment]
Auch folgende Domains werden für denselben Zweck missbraucht: 

cwwbackend.xyz
vksupport.online
tassist.me
gcsupport.live
kassist.live
ctshelp.live

Bitte diese wenn möglich auch einmal in die Liste aufnehmen

**Comment by SpielenmitLili** [comment]
Und hier einmal Phishing.
Unter folgender Domain wird sich als österreichische Regierung ausgegeben und es wird versucht Daten der Benutzer abzugreifen

web9840.web07.bero-webspace.de

Wäre auch toll wenn die Seite gesperrt werden könnte

**Comment by RPiList** [comment]
Vielen Dank für die Domains. Wurden auf die entsprechenden Listen gesetzt. Viele Grüße
