### ISSUE TITLE
False-positive: `forms.zohopublic.com` in `Blocklisten/Phishing-Angriffe`

### ISSUE THREAD

**Issue by PeterDaveHello** [RPiList/specials#937]
It's service provided by https://www.zoho.com/forms/, also in Akamai and Cisco Umbrella top domain list, and I saw that www.zoho.com is in the whitelist, not sure if I can send a pull request to include it in the whitelist?

Some reference:
- https://www.urlvoid.com/scan/forms.zohopublic.com/
- https://www.virustotal.com/gui/domain/forms.zohopublic.com/detection

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings.

**Comment by PeterDaveHello** [comment]
@RPiList thanks for the prompt response! Is there any commit can be referred to? Thank you!

**Comment by RPiList** [comment]
Sorry, I don't understand the question. 
But you need to update your pihole list to get the domain deleted on your pihole. Greetings.

**Comment by PeterDaveHello** [comment]
@RPiList oh, sorry, I mean where's the removal happened? Can send a pull request for it the next time.

**Comment by lightr4in** [comment]
@PeterDaveHello Probably [commit #df8c3bae5ac9c0aa5e1d5ead0b4b83c3a1d672f0](https://github.com/RPiList/specials/commit/df8c3bae5ac9c0aa5e1d5ead0b4b83c3a1d672f0)

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello Probably [commit #df8c3ba](https://github.com/RPiList/specials/commit/df8c3bae5ac9c0aa5e1d5ead0b4b83c3a1d672f0)

Thanks @lightr4in, I doubt it's only the result of the auto update, maybe it's actually whitelisted in front of the auto update 😅
