### ISSUE TITLE
Webseiten zum hinzufügen

### ISSUE THREAD

**Issue by ich423** [RPiList/specials#94]
Bitte in eine der Listen ergänzen: www.e-mail-porto.de

**Comment by ich423** [comment]
https://github.com/RPiList/specials/pull/95

**Comment by RPiList** [comment]
Wurde hinzugefügt.

**Comment by ich423** [comment]
Danke für das hinzufügen. Und in welche Liste wurde das hinzugefügt.

**Comment by ich423** [comment]
Lesen hilft...
