### ISSUE TITLE
Malware + Popup seiten

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#940]
Hallo, hier weiterer Müll gefunden auf einer anderen link shortener Seite:

Malware (das selbe wie https://github.com/RPiList/specials/issues/935):

```
9bghqk3avg2gnh.click
lrhxz60alkjtik.click
6t09fag307ep.click
klwukospapf.click
uerqelim91ut.click
```

Seiten die Popup scripts hosten die zu diesen Seiten führen (Beispiel: `https://tvbxrr4ym3.click/260744106674061676908386?s=11&g=31&q=file.zip`) :

```
tvbxrr4ym3.click
8ebtdbsjsu.click
eicxz6jfjaw.click
```

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden den Listen zugefügt. Viele Grüße
