### ISSUE TITLE
hopp.to false positive 

### ISSUE THREAD

**Issue by shaulgo** [RPiList/specials#942]
Hey, 

Hopp.to is a link shortener/link-in-bio product by Wix.com. 
Could you add it to the whitelist and url shortener list. 
It should only be handled by subdomains. 

Thanks

**Comment by RPiList** [comment]
Hi,
thx for letting us know, Domains have been removed. Greetings.

**Comment by shaulgo** [comment]
Hey, could you also add us to the white lists. Like bit.ly.
https://github.com/RPiList/specials/blob/96d831115b28cde6b6de8d6056293ec802aeeb54/dev/URL-Shortener#L13
https://github.com/RPiList/specials/blob/96d831115b28cde6b6de8d6056293ec802aeeb54/dev/whitelist#L260

**Comment by RPiList** [comment]
Hi,
bit.ly is currently not on our lists, so no need to "whitelist" it. Our whitelist is intended for sites that got blocked in the past and are in danger of being blocked again (because of misuse of their users...).
So when needed, we will whitelist it automatically. Greetings.

**Comment by RPiList** [comment]
Hi, 
I might have misunderstood your comment. You probably meant whitelisting hopp.to. Hopp.to is currently "in between" because you were blocked once... but we don't know right know which service on the internet reported you. So we are waiting for the renewed block. When this happens, we will whitelist hopp.to as well.

**Comment by shaulgo** [comment]
Thanks for the reply. 
As a link shortener that is growing in popularity we will surely be blocked again.
If possible to preempt and add to the whitelist that would be amazing ;)

**Comment by hagezi** [comment]
@shaulgo It was flagged in phishing activities:

https://github.com/mitchellkrogza/Phishing.Database/blob/e0ec83d4572f27ed68391eec6ae167d76ed02c7d/phishing-domains-NEW-today.txt#L6783

Detected by alphaMountain.a and Phishing.Databasei:
https://www.virustotal.com/gui/domain/hopp.to/detection
https://www.urlvoid.com/scan/hopp.to/

As long as that happens, it will always end up on block lists.

**Comment by drego85** [comment]
Hey, domain hopp.to is being used in recent weeks as a shorturl (redirect) to phishing websites!

Personally, I don't think it should be listed in a blocklist like any other shorturl service!

In Phishing.Army this domain is whitelisted!

**Comment by hagezi** [comment]
Many Thanks @drego85

**Comment by shaulgo** [comment]
@hagezi can you also add hopp.bio please. It's an additional domain for the same service as hopp.to (which is already in the whitelist). But it is directed more towards the link-in-bio part of the platform.

**Comment by hagezi** [comment]
> @hagezi can you also add hopp.bio please.

Fixed.
