### ISSUE TITLE
bbv.konferenz.jetzt false positive

### ISSUE THREAD

**Issue by EnigmaG** [RPiList/specials#943]
bbv.konferenz.jetzt
  srv02.bbv.konferenz.jetzt
  srv03.bbv.konferenz.jetzt
  srv04.bbv.konferenz.jetzt
  srv05.bbv.konferenz.jetzt
  srv06.bbv.konferenz.jetzt
  srv07.bbv.konferenz.jetzt
  srv08.bbv.konferenz.jetzt
  srv09.bbv.konferenz.jetzt
  srv10.bbv.konferenz.jetzt
  srv11.bbv.konferenz.jetzt

Video conference server of the Bavarian farmers' association (bayerischer bauernverband) please whitelist

**Comment by RPiList** [comment]
Thx for letting us know. Domains have been removed. Greetings.
