### ISSUE TITLE
www.smarthomejetzt.de false/postive

### ISSUE THREAD

**Issue by mschabhuettl** [RPiList/specials#944]
Hello!

I've discovered that

> www.smarthomejetzt.de

is on RPiList/specials/master/Blocklisten/spam.mails

I've noticed this when I tried opening this manual: [https://www.smarthomejetzt.de/wasserzaehler-mit-esp32-cam-und-ai-on-the-edge-device-fuer-iobroker-smart-machen/](https://www.smarthomejetzt.de/wasserzaehler-mit-esp32-cam-und-ai-on-the-edge-device-fuer-iobroker-smart-machen/) - a tutorial for making a water meter smart.

Cheers,
Matthias

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Ist jetzt entfernt. Viele Grüße
