### ISSUE TITLE
teslavpn.net

### ISSUE THREAD

**Issue by Vickyistda2003w** [RPiList/specials#947]
Moin Sprecher,

Die Seite http://teslavpn.net/ hat nicht mal ein Impressum und man kann das nur nutzen wenn man es kauft somit finde ich das es Abzocke ist

LG
Vicky

**Comment by RPiList** [comment]
Hi,
passt leider nicht zu den Ansprüchen, die unsere NotSerious Liste i.d.R. stellt.
