### ISSUE TITLE
digitale-freiheit.jetzt keine spam-mail

### ISSUE THREAD

**Issue by craiten** [RPiList/specials#949]
Hallo RPiList,

in der Liste https://github.com/RPiList/specials/blob/master/Blocklisten/spam.mails finden sich die Einträge 
`matrix.digitale-freiheit.jetzt`,   
`digitale-freiheit.jetzt` &  
 `www.digitale-freiheit.jetzt` 
welche generell keine spam mails verschicken. Gab es einen Grund dafür, dass die Adressen aufgenommen wurden? Wen nicht, bitte löschen. Danke.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
