### ISSUE TITLE
FP Coronawarnapp

### ISSUE THREAD

**Issue by KonstiSG** [RPiList/specials#950]
Subdomains der Domain coronawarn.app welche zur offiziellen deutschen "Coronawarnapp" gehören, befinden sich derzeit fälschlicherweise auf der Corona-Blockliste. 
*.coronawarn.app 
z.B.: data.coronawarn.app

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
