### ISSUE TITLE
link.chatgpteverywhere.com

### ISSUE THREAD

**Issue by p1r473** [RPiList/specials#953]
Chrome addon for using Chat GPT everywhere
False positive

**Comment by RPiList** [comment]
Are you sure? It looks quite fishy to me.

![image](https://user-images.githubusercontent.com/56664851/225686040-6520e490-fb6d-4166-bd42-940dce4eab4b.png)

There are only two links on the page. The first is to go back (if you are here by mistake...) and the second is to "GET STARTED" with your own branded short link domain.

So it looks like someone is using chatgpt to get on the hype train to promote his own link shortener... But maybe I am missing something...

**Comment by p1r473** [comment]
Sorry it looks like I have made a mistake here!
