### ISSUE TITLE
Falsch Positiv

### ISSUE THREAD

**Issue by Julian0021** [RPiList/specials#955]
Die legitime OpenAI domain ist auf der Malware Liste.

**Comment by RPiList** [comment]
Welche Domain wäre das?

**Comment by Julian0021** [comment]
platform.openai.com

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernet. Viele Grüße

**Comment by kb-elmo** [comment]
Adding to this:
labs.openai.com is currently in the list as well which is the legitimate URL for many OpenAI projectpages (like Dall-E 2)

**Comment by RPiList** [comment]
domain has been removed. Greetings.

**Comment by mcdallas** [comment]
same for api.openai.com

**Comment by RPiList** [comment]
> same for api.openai.com

has been removed as well. Greetings.
