### ISSUE TITLE
Remove "duplicates" by removing all subdomains when a domain.tld is already given

### ISSUE THREAD

**Issue by thomasmerz** [RPiList/specials#956]
My follow-up PR will **remove all subdomains for any given domain.tld because any subdomain will already be blocked if domain.tld has been blocked** and there's no need (except for "marketing") to blow up this adlist.
This will reduce the size for the blocklist and improves performance and makes this list better maintainable 😃

"Explanation":
```
$ host pixel.ad
pixel.ad has address 0.0.0.0
pixel.ad has IPv6 address ::

host $(sha512sum README.md | awk '{print $1}'|cut -b12-40).pixel.ad
c88553a937ca37301f26773d67c42.pixel.ad has address 0.0.0.0
c88553a937ca37301f26773d67c42.pixel.ad has IPv6 address ::
```

I'm using this little script to check/remove subdomains for any given domain.tld:
```
#!/bin/bash
# ---
# remove subdomains when domain.tld is already given:
# ---
# To read lines rather than words, pipe/redirect to a 'while read' loop. [SC2013]
# shellcheck disable=SC2013
for liste in $(grep -l footprintdns Blocklisten/* 2>/dev/null); do
  echo "working on $liste:"
  for domain in $(grep -P "[^.]+\.[a-zA-Z]{3}$|^.[^.]+\.[a-zA-Z]{2}\.[a-zA-Z]{2}$" \
    "$liste" | rev | cut -d"." -f1-2 | rev | sort -u); do
      # do only change if domain.tld is also in list:
      echo "$domain"
      grep -c ^"$domain" "$liste" 2>/dev/null | grep -v ^0
      grep -q ^"$domain" "$liste" 2>/dev/null || continue
      # change:
      sed -i "/\.$domain\$/d" "$liste"
  done
done
```

Currently running this very long running task and as an example this removes the following sudomains:
```
working on Blocklisten/child-protection:
000359.xyz
0005210.com
000asmr.com
1
000dn.com
000webhostapp.com
000webhost.com
001edizioni.com
001fzc.com
001kanpou.com
1
…
```

And removing…
```
diff --git a/Blocklisten/child-protection b/Blocklisten/child-protection
index b37a6fea..12034ad9 100644
--- a/Blocklisten/child-protection
+++ b/Blocklisten/child-protection
@@ -4842,7 +4842,6 @@
 0026645142c89aeb1.com
 003999.cc
 003store.com
-005.0x1f4b0.com
 005.free-counters.co.uk
…
```
With `0x1f4b0.com` still in blocklist:
```
$ grep 0x1f4b0.com Blocklisten/child-protection
0x1f4b0.com
```

**Comment by RPiList** [comment]
I think there might be a misunderstanding.
Subdomains get not automatically block just because the TLD gets blocked.  For Pihole as for the complete DNS system a subdomain makes a domain a complete different domain.

For example:
sempervideo.de resolves to 195.90.213.85 and 
arma3.sempervideo.de resolves to 178.254.32.104 on a completely different server.

Greetings

**Comment by thomasmerz** [comment]
See also https://github.com/lightswitch05/hosts/pull/394#issuecomment-1478463679 for the same discussion… 🤷🏼‍♂️ 
Pi-hole seems to be "different" than /etc/hosts normally will work.

**Comment by joestr** [comment]
Besides that, the script is error prone. According to https://publicsuffix.org/list/public_suffix_list.dat `com.ac` isn't event matched by the supplied Regex.

**Comment by thomasmerz** [comment]
@joestr , thanks for hint. I'll check my bash-skills…

And, lessons learned:
* some (useless) bash scripting 😉 
* ABP-syntax is much more powerful than simple hosts files ❤️

**Comment by RPiList** [comment]
> 



> (My) Pi-hole seems to be "different" than /etc/hosts normally will work due to using ABP-syntax

Yes, your Pihole is a basic DNS resolver, and it is only given the domain.
ABP ist a Browser Plugin and sees the complete Domain. So it has more possibilities. Greetings
