### ISSUE TITLE
xoom.com - A PayPal service - false positive

### ISSUE THREAD

**Issue by Root-Core** [RPiList/specials#958]
This is a false positive. `t.xoom.com` should still be blocked though, as it is for tracking.

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious:
  www.xoom.com
  xoom.com

Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist:
  t.xoom.com
  www.xoom.com
  xoom.com
```

**Comment by RPiList** [comment]
Domains have been removed. Let's see if they get washed in again. Greetings.

**Comment by RPiList** [comment]
yes, because of tracking. You sure you need it for using this service?

**Comment by JoniRousu** [comment]
Yes, ``xoom.com`` and ``www.xoom.com`` are needed.
However ``t.xoom.com`` can remain blocked as @Root-Core  mentioned.

**Comment by RPiList** [comment]
Thx for clearing that up. Domains have been removed and are whitelisted to avoid future re-listing. Greetings.
