### ISSUE TITLE
False positives due to request uris in lists

### ISSUE THREAD

**Issue by 5t4cktr4c3** [RPiList/specials#96]
Your blocklists contain in addition to the domain itself the request uri, for example in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock-4 (line 360370): `google.de/notebook/public/05160677075035842971/BDRkwSgoQ2Iiezpwj` leads to blocking `google.de` entirely.
For blocking `google.de/notebook/public/05160677075035842971/BDRkwSgoQ2Iiezpwj`specifically a dns-specific blocker is not suitable.

**Comment by RPiList** [comment]
Will be fixed with the next update.
