### ISSUE TITLE
False positive api.openai.com

### ISSUE THREAD

**Issue by MiguelMachado-dev** [RPiList/specials#961]
`api.openai.com` false positive on list `https://v.firebog.net/hosts/RPiList-Malware.txt`

Need this host to authenticate via `platform.openai.com`

**Comment by RPiList** [comment]
Hi,

Domain has already been removed a few hours ago. Greetings.

**Comment by RPiList** [comment]
No, as already said, it is not on our list.
You are saying https://v.firebog.net/hosts/RPiList-Malware.txt still has it, but that's not our list. I guess firebog has not updated his copy of our list yet.

Greetings

Our list:
https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware

import it and check that the api.openai.com is not on it.

Greetings
