### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#963]
Hallo zusammen,

die in den Blocklisten enthaltene Domain db.de ist eine legitime Domain der DB AG und gehört nicht auf die Blocklist.

Wäre nett, wenn diese aus den Listen entfernt werden könnte.

Domain befindet sich in der folgenden Liste: 
- https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1

Liebe Grüße

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domain wurde entfernt. Viele Grüße
