### ISSUE TITLE
Ungültige URLs in vereinzelten Listen

### ISSUE THREAD

**Issue by cms04** [RPiList/specials#964]
Beim Import von einzelnen Blocklisten werden ungültige URLs gemeldet (Bindestriche unmittelbar hinter einem Punkt sind in URLs nicht zulässig).

Beispiel:
```
  [i] Target: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming
  [✓] Status: Retrieval successful
  [i] Imported 4185 domains, ignoring 1 non-domain entries
      Sample of non-domain entries:
        - op.-23.olink.tv
```

Eine vollständige Übersicht der ungültigen URLs kann mit folgendem Befehl (ausgeführt im Projekt-Wurzelverzeichnis) abgerufen werden:
```
grep --recursive "\.-" ./Blocklisten
```

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Info. Domains wurden entfernt. Viele Grüße
