### ISSUE TITLE
Not serious

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#966]
Ich habe eine Seite mit Bitcoin-Abzockern gefunden.

Dabei wird man angerufen und durch Gewinnversprechen dazu verleitet Geld aufzuladen, sieht das Geld dann allerdings nicht wieder.

Die entsprechende Domain die auf die Blocklist hinzuzufügen wäre lautet:
onspotcap.com

Liebe Grüße

**Comment by RPiList** [comment]
Vielen Dank für die Info.
Domain ist jetzt auf der Schadware-Liste. Viele Grüße
