### ISSUE TITLE
jetzt.de / Spam-Mails

### ISSUE THREAD

**Issue by yoshimo** [RPiList/specials#974]
```
caching-production.jetzt.de
www.jetzt.de
```
gehören zum JugendAngebot der Süddeutschen Zeitung.

**Comment by RPiList** [comment]
Vielen Dank für den Hinweis. Domains wurden entfernt. Viele Grüße

**Comment by yoshimo** [comment]
'''
iqdtms-stage.jetzt.de
iqdtms.jetzt.de
'''
ist der IQ AD Controller

````
data-86d2aee9fa.jetzt.de
data-ac3d45df06.jetzt.de
```
gehört wie alle data-X SubDomains zu InfOnline, mal mit Cname , mal mit reinem A-Record.
Hätte ich drin gelassen genau wie

```advertorial.jetzt.de``` was vom Namen her unerwünscht ist.

**Comment by RPiList** [comment]
Da die Domains von unserem Crawler nur auf Grund des "jetzt" in der Domain gecatcht wurden, welches oftmals in Scam-Websites benutzt wird, haben wir alle entfernt. Jetzt.de ist ja dann offenbar keine Website bzgl. Scam.
Die Werbe- und Tracking Domains werden aber wahrscheinliche früher oder später von anderen Listen geführt und dann landen sie auch wieder bei uns. Nur halt nicht in der Spam-Mail Liste sondern in der Schadware oder Easylist.

oder wenn Jetzt.de neue Zertifikate erstellen lässt, dann landen sie auch wieder bei uns. :-)
