### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by TinoM** [RPiList/specials#976]
The domain 
`fme.safe.com`
is an official Subdomain of Canadian software Vendor Safe Software Inc.

No malware to my knowledge.

**Comment by RPiList** [comment]
Hi,
fme.safe.com is reguarding to the Adblock Team a so called Tracker-Domain, used to track users. So I'm afraid it has to stay on the malware list.
The moment the adblock team removes the URL, it gets deleted on our list as well. Greetings.
