### ISSUE TITLE
False positives on Phishing-Angriffe

### ISSUE THREAD

**Issue by EternalList** [RPiList/specials#98]
There is a wrong URL on your list "[Phishing-Angriffe](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe)".
The URL outlook.office365.com is needed if you have a Hotmail account to received mails.

**Comment by Dennis-Mootz** [comment]
I approve strongly - just the default Microsoft-Outlook Service.

**Comment by RPiList** [comment]
o.g. Einträge wurden in die Whitelist aufgenommen. Künftige Vorschläge auch gerne per Pull Request. Die Liste Phishing-Angriffe wurde entsprechend bereinigt und neu eingestellt. Sie können Ihr Pi-hole aktualisieren.

Vielen Dank für Ihre Mühen.
