### ISSUE TITLE
Neue Phishing Domains

### ISSUE THREAD

**Issue by Zoey2936** [RPiList/specials#983]
Hallo, netcup Kunden bekommen zurzeit viele Phishing Mails (https://forum.netcup.de/netcup-anwendungen/ccp-customer-control-panel/16878-gezielter-spam-domain-l%C3%A4uft-in-wenigen-minuten-ab/), wäre es bitte möglich diese Domains zu den Sperrlisten hinzuzufügen?:
a161a7b0.orson-consulting.eu
customercontrolpanel-netcup.eu
www.customercontrolpanel-netcup.eu

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains wurden der Spam.mail Liste hinzugefügt. Viele Grüße
