### ISSUE TITLE
okcupid.com

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#984]
Moin Herr RPiList,

okcupid.com ist eine normale Dating ab wie Tinder. Bitte folge Domians entfernen.
Exact match for api.okcupid.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection

Exact matches for okcupid.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock3
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection

Mfg
mfg

**Comment by RPiList** [comment]
Hi,

vielen Dank für die Nachricht. Dass die Domain in der Childprotection Liste ist, ist korrekt. Es hat nichts damit zu tun, ob es eine normale Dating Site ist, sondern nur damit, ob Eltern Kindern Zugriff gestatten wollen.

Aus den Porn-Listen sind die Einträge aber entfernt worden.

Vielen Dank für die Mühen.

Viele Grüße
