### ISSUE TITLE
Spyware

### ISSUE THREAD

**Issue by SpielenmitLili** [RPiList/specials#988]
Hallo, 

ich hätte wieder 3 Domains auf denen dem Benutzer ohne dass dieser es mitbekommt der Download von Spyware aufgedreht wird. 

Diese wären einmal 

abackup01.xyz
ckhelp.us
qassist.us

Bitte am besten einmal in die entsprechende Liste aufnehmen.

Vielen Dank und einen schönen Abend noch

**Comment by RPiList** [comment]
Vielen Dank für die Info. Domains sind jetzt auf der Schadware Liste. Viele Grüße
