### ISSUE TITLE
okcupid.com und knuddels.de

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#989]
Moin Meister,

Ich hatte bereits einen Issues aufgemacht zu denn Sachen aber sie sind wieder drin.
Exact match for okcupid.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection
Exact match for api.okcupid.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection

Desweittern bitte diese Domians freigeben da sie nichts mit Porn zutuhen haben.
Exact match for knuddels.de found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock2
Exact match for www.knuddels.de found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock5

Mit freundlichen Grüßen

**Comment by RPiList** [comment]
Hi,

ja, und wir hatten auch beim letzten Mal erläutert, dass es auf der Childprotection Liste bleiben muss.

Aber Knuddels wird von der Porn-Liste gestrichen. Viele Grüße
