### ISSUE TITLE
Bitte in Whitelist aufnehmen

### ISSUE THREAD

**Issue by stgriesb** [RPiList/specials#99]
facebook.com
www.facebook.com

**Comment by Dennis-Mootz** [comment]
Selbst der Datenkrakte Facebook ist es bislang nicht gelungen, ohne dass der Nutzer genau diese Domain eingibt, Daten zu sammelt.
Diese Domain sollte daher nicht besonders förderlich sein, solange der nutzer die Domain nicht selber eingibt. Was dann auch dessen Schuld ist.

**Comment by stgriesb** [comment]
Du hast anscheinend bei Facebook kein Konto und bist bei keiner Facebook-Gruppe Mitglied. 
Leider öffnet er mir ohne die Einträge in der Whitelist mein Konto nicht mehr.

**Comment by RPiList** [comment]
o.g. Einträge wurden in die Whitelist aufgenommen. Künftige Vorschläge auch gerne per Pull Request. Die Liste Phishing-Angriffe wurde entsprechend bereinigt und neu eingestellt. Sie können Ihr Pi-hole aktualisieren.

Vielen Dank für Ihre Mühen.
