### ISSUE TITLE
adblock.click malware

### ISSUE THREAD

**Issue by JobcenterTycoon** [RPiList/specials#991]
Hallo, ich möchte die Domain `adblock.click` melden da es eine Malwareseite und eine fake Seite ist. Payload: `https://adblock.click/en/dl.php`, Webseite Design gestohlen von: `https://getadblock.com/`

VT: https://www.virustotal.com/gui/url/66b2f0889146484f9e6da2ed7bed6620869c6c32c2bb8836b357c9a53d38f392?nocache=1
VT 2: https://www.virustotal.com/gui/file/48baa03dab0584764ca5d7aaee98d6ca34ce7707a42c2b558bd9d166be3486da?nocache=1

**Comment by RPiList** [comment]
Hi,
vielen Dank für die Info. Domain wurde hinzugefügt. Viele Grüße

**Comment by JobcenterTycoon** [comment]
Ok der Eintrag kann wieder weg, die Seite ist down.
