### ISSUE TITLE
False positive: chatgptwith.me

### ISSUE THREAD

**Issue by AnimMouse** [RPiList/specials#992]
I have searched my domain on Google for SEO research, and one of the results come up is this RPiList on `Blocklisten/malware`, I don't know how is my website got caught on malware filters, but this is not malware.

This is my website that publishes conversations with ChatGPT, you can see here my [source code](https://github.com/AnimMouse/ChatGPT-with-Me-Website) so that you can be assured that this website is free of malware.

Also, the domain on Cloudflare Pages `chatgpt-with-me.pages.dev` is also caught on malware filters, I don't even use that domain since I have custom domain and yet it is considered a malware.

**Comment by RPiList** [comment]
Hi, 
these domains are considered as malware because of the recent scam wave on the internet all things chatgpt related.

Your domains have been removed. Greetings.

**Comment by AnimMouse** [comment]
Thanks!
