### ISSUE TITLE
false positive aeotec.com

### ISSUE THREAD

**Issue by dr2okevin** [RPiList/specials#993]
I'm wondering why aeotec.com is on the notserious list. I have bought a product from them via amazon, and wondered why I can't access manuals, well it was blocked by this list.

https://en.wikipedia.org/wiki/Aeotec
https://www.amazon.de/AEOTEC-ZWA010-C-Z-Stick-7/dp/B094VTQQCR

**Comment by RPiList** [comment]
Hi, thx for letting us know. Domain has been removed. Greetings.
