### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by tdiekel** [RPiList/specials#994]
In der Liste [malware](https://github.com/RPiList/specials/blob/master/Blocklisten/malware) steht `dealer.spotify.com` drin. Spotify auf meinem Android TV benötigt Zugriff auf die Domain für den Login. Laut diesem [Reddit Post](https://www.reddit.com/r/pihole/comments/rn4p1v/comment/hpq8vy5) könnte es sich um einen Loadbalancer handeln.

**Comment by RPiList** [comment]
Vielen Dank für die Info. Die Domain wurde entfernt. Viele Grüße

**Comment by bxkx** [comment]
Seems like it is still in the list. It  breaks the Spotify rich presence in Discord and prevents Spotify from scrobbling to Last.fm
