### ISSUE TITLE
False positive in https://v.firebog.net/hosts/RPiList-Malware.txt -  dealer.spotify.com

### ISSUE THREAD

**Issue by thechrisgregory** [RPiList/specials#997]
I'd like to suggest removing the false positive (?) domain name 'dealer.spotify.com' from the [RPiList-Malware.txt.](https://v.firebog.net/hosts/RPiList-Malware.txt)

This domain appears to be used by Spotify severs to allow the 'Spotify Connect' functionality (https://support.spotify.com/uk/article/spotify-connect/) to work correctly with mobile/tablet devices.

If 'dealer.spotify.com' is blacklisted, mobiles/tablets fail to see other devices on a local (192.68.*.*) network. 

Thanks for your time.

**Comment by RPiList** [comment]
Hi,
thx for letting us know. Domain has been removed. Greetings.

**Comment by lfg6000** [comment]
- first of all thanks for creating and maintaining this list. Thank You.
- i also noticed that if i unblock dealer.spotify.com a spotify connect issue would go away.
- above RPiList reports that dealer.spotify.com was removed (excellent, thanks)
- so did a pihole -g 
- i then look at   [i] Target: https://v.firebog.net/hosts/RPiList-Malware.txt
       # RPiList-Malware, parsed and mirrored by https://firebog.net
       # Updated 02MAY23 from https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
       # List corrections can be requested upstream at https://github.com/RPiList/specials/issues
- dealer.spotify.com is still in this list (pihole -g does not get the updated list)
       it is like https://v.firebog.net/hosts/RPiList-Malware.txt does not have the latest changes?
- obviously i am doing something wrong (or i do not understand how to manage pihole lists)
- i am wondering you might suggest a fix so i get the latest version of this list.

btw: i created a website spotifyfinder.com that helps spotify users curate/organize playlists (search/find dups)...it is free, open source on github, tracker free, ad free (google spotifyfinder for a link)

**Comment by thechrisgregory** [comment]
Indeed, I too found that dealer.spotify.com has not yet been removed from https://v.firebog.net/hosts/RPiList-Malware.txt after updating my pi-hole gravity list and searching all adlists. 

Perhaps this will happen soon !

**Comment by WaLLy3K** [comment]
I've corrected this issue on my end, thanks 🙂

**Comment by thechrisgregory** [comment]
Looks good to me, dealer.spotify.com has been removed as requested/suggested.

**Comment by lfg6000** [comment]
Wally3K, thanks for straightening this out.

**Comment by RPiList** [comment]
Might be a problem with @Wally3K update script. Domain was removed from my list 3 Weeks ago. But for some reason the removal didn't "copy" to @Wally3k mirror.
