### ISSUE TITLE
Remove wl.spotify.com from malware

### ISSUE THREAD

**Issue by thomasmerz** [RPiList/specials#998]
This domain is used to "confirm your Spotify data request".

**Comment by RPiList** [comment]
wl.spotify.com is currently flagged as malicious by the Adguard-Team, for being a cname tracker. According to Google it is on the list for almost 2 years now.
So it has to stay on our list.

The strange part is, that we don't experience any problems with it being blocked. 

Greetings.

**Comment by thomasmerz** [comment]
Yes, strange, I had to whitelist `wl.spotify.com` to be able to confirm my Spotify data request… 🤷🏼‍♂️ I'll check and ask the Adguard-Team…
